### ISSUE TITLE
[builder-web] Fix Acceptance Tests

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#1001]
Running `npm run test-e2e` fails (there's a note in the README indicating this is so.)

Reason for failure are either (1) Protractor has been super flaky and failed in lots of cases from the get-go (2) Things have changed so the tests are no longer valid.

Make them all green. We don't necessarily need to use Protractor. Maybe [WebdriverIO](http://webdriver.io/) would be something to try.

You should be able to run tests against a running development or acceptance environment.

**Comment by cnunciato** [comment]
Chatted a bit with @smith on this -- I'm working up a change that replaces these with coverage from the [Angular testing utilities](https://angular.io/docs/ts/latest/guide/testing.html#!#atu-apis).
