### ISSUE TITLE
Alternate storage (S3) for depot artifacts

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#1002]
## The Story

As a Habitat administrator, I would like to store depot artifacts in a storage system other than a filesystem, so I can have a more reliable and easier to administer system.
## Description

Right now the only way to store packages in the depot is on disk. It would be nice to be able to use S3 or another cloud storage provider to store the packages and perhaps the keys.

It would even be possible to [upload directly to S3 without sending the file through our backend servers](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingHTTPPOST.html), though this would require some more complexity on the client.
## Acceptance Criteria
- A depot can be run with configuration options specifying that artifacts be stored in something other than the filesystem and the associated needed secrets
- Running the depot in such a configuration will make it so the depot stores and retrieves artifacts in the configured storage service

**Comment by rsertelon** [comment]
I think this has been taken up by someone in core team as issue #2697 has been opened by @chefsalim to do exactly that ;)
