### ISSUE TITLE
Unused method in openssl plan

### ISSUE THREAD

**Issue by tomrobison** [habitat-sh/habitat#1007]
The method _common_prepare is not used by the openssl plan.  But is used by openssl-musl. So either _common_prepare should either be added to do_prepare or moved to openssl-musl/plan.sh.

https://github.com/habitat-sh/habitat/blob/bdc6aa827de93520ac7045d5cf94b0ffdd782d93/plans/openssl/plan.sh#L16-32

**Comment by tomrobison** [comment]
After reviewing the commits for openssl/plan.sh, I think the issue was created at https://github.com/habitat-sh/habitat/commit/c0069872955256d7e9b9848c17f6045d0bfe0e19.  I think we need to add _common_prepare into the do_prepare block.

**Comment by tomrobison** [comment]
Added to block in https://github.com/habitat-sh/habitat/pull/1014

**Comment by smith** [comment]
Fixed in #1014.
