### ISSUE TITLE
"hab studio [enter]" command forwarded to docker binary

### ISSUE THREAD

**Issue by walterdolce** [habitat-sh/habitat#1008]
Hi, I'm not sure what could have changed in the past few days. I used to enter and build from the studio, but suddenly it seems otherwise.

Command issued is:
```
~/myplan $ hab studio enter
/usr/local/bin/docker: Error response from daemon: Container command 'enter' not found or does not exist..
```

While when:
```
~/myplan $ hab studio 
```
Then it goes into something:
```
/src #
```

Note `docker ps` returns nothing. The docker machine is running. Initial `eval (docker-machine env dockervm)` has been issued, too.

Do you need any more info to form a theory for this?

**Comment by smith** [comment]
Could you please post the output of `docker images | grep studio` and `hab --version`?

**Comment by walterdolce** [comment]
@smith sure. So the first is 
```habitat-docker-registry.bintray.io/studio   latest              c2f77b9942c8        5 days ago          1.113 MB``` 

While `hab` is at 
```hab 0.7.0/20160614231131```

**Comment by walterdolce** [comment]
Should you also need Docker's version, here it is:
```Docker version 1.11.2, build b9f10c9```

**Comment by smith** [comment]
I'm not sure what's happening here. The versions of everything you have look fine, but the commands you're typing aren't giving the correct output. `hab studio enter` should enter a studio, and `hab studio` should print out the usage information for that subcommand.

Are you on Mac or Linux? If you're on Mac, maybe trying the [Docker for Mac beta](https://docs.docker.com/docker-for-mac/) would work.

**Comment by walterdolce** [comment]
@smith I'm on Mac. My docker related tools have all been installed via Homebrew while waiting foe the docker for Mac to be released/considered stable.

**Comment by walterdolce** [comment]
Hi, just a quick update on this issue.

By destroying and recreating my docker machine the issue didn't occur anymore.
Current status is:
```
hab 0.7.0/20160614231131

docker-machine version 0.8.1, build 41b3b25

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Thu Aug 18 22:32:50 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

Please note I'm still *not* using Docker for Mac, but I have everything installed out of homebrew.
Thanks all.
