### ISSUE TITLE
Cannot install a .hart file into another studio

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#1011]
Our brave warrior continues on his path to enlightenment, while being beset upon by yaks from all directions. This time, he hopes, he can make a difference in the world.

One such yak, being of a particularly prickly nature, approaches. It's branding shows a name, faded slightly over the years. "*SCons*"

"What ho! What a lovely yak", says the warrior, "Certainly this is a yak worth shaving, since it is so hairy and gross right now, but will be worthwhile for others to ride this yak and any further offspring it has!"

The warrior hammers out an attack plan, and after consulting with his trusty scrying glass, whets his blade. He lures the yak into a cave with some sweet sedges, and [shaves the yak named SCons](https://gist.github.com/miketheman/beeaa495fc00b185c6229c39c31c10d8#file-plan-sh).

Success! Or so he thought.

With his newly-shaved yak, he now is more confident that he can ride into the sunset. He mounts up, rides out of this cave, and traverses the rolling hills until he finds another cavern.

This cavern has another unshaven yak in it, and this one looks like it won't be lured by sedges, but appears to be attracted to SCons. It must have sniffed some pheromone of  not only a fresh-shaved yak, but also any yaks from the shaven-yak's original herd.

With the attraction of greater yaks at hand, our hero tries to coax his shaven yak into the new cavern, only to be met with some magical resistance - [a ghostly message appears](https://gist.github.com/miketheman/beeaa495fc00b185c6229c39c31c10d8#file-console-log) at the entrance of the cavern, and an invisible wall prevents our hero from shaving this new yak.

The warrior, a little confused, consults his scrying glass to no avail. He then [paints his notes](https://gist.github.com/miketheman/beeaa495fc00b185c6229c39c31c10d8#file-notes-md) on the wall at the entrance of the cavern for others in the tripe to find, in hopes they may succeed where he has failed.

![sig-3889974 924803__safe_animated_screencap_table_discovery family_destruction_pure unfiltered evil_table flip_spoiler-colon-s05e11_party pooped](https://cloud.githubusercontent.com/assets/529516/16458570/823f1a5c-3ded-11e6-8dcb-0a857aa3ef22.gif)

**Comment by metadave** [comment]
hey @miketheman, we were unable to reproduce this locally. Would you be willing to try to trace this for us?

I added some tracing to the `hab` source on this branch:
https://github.com/habitat-sh/habitat/tree/dp_trace_install

```
make shell
cd /src/components/hab
cargo build
./target/debug/hab
cp ./target/debug/hab /src/plans/somedir
```

enter a studio,
try to install your .hart with the hab that you copied into somedir
you'll need to set `RUST_LOG=debug`

```
RUST_LOG=debug ./path/to/custom/hab pkg install miketheman-scons-2.5.0-20160629142158-x86_64-linux.hart
```

**Comment by miketheman** [comment]
With the help of another tribesman, our warrior places some shards of tinted glass over his eyes in an attempt to discern the meaning of the mysterious message, and tries again to enter the cavern.

This time, he is able to see deeper meaning than before.

He brings back this seemingly confusing message to the tribe, in hopes that in their collective wisdom, help find a way in.
```
...
DEBUG:habitat_core::package::archive: content = core/acl/2.2.52/20160612075215
core/attr/2.4.47/20160612075207
core/bzip2/1.0.6/20160612075040
core/cacerts/2016.04.20/20160612081125
core/coreutils/8.24/20160612075329
core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/gmp/6.1.0/20160612064724
core/libcap/2.24/20160612075226
core/linux-headers/4.3/20160612063537
core/make/4.1/20160612080650
core/ncurses/6.0/20160612075116
core/openssl/1.0.2h/20160612081127
core/python2/2.7.11/20160620182552
core/readline/6.3.8/20160612075601
core/zlib/1
DEBUG:habitat_core::package::archive: content = # miketheman / scons
...
DEBUG:habitat_core::package::archive: body = [core/acl/2.2.52/20160612075215
core/attr/2.4.47/20160612075207
core/bzip2/1.0.6/20160612075040
core/cacerts/2016.04.20/20160612081125
core/coreutils/8.24/20160612075329
core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/gmp/6.1.0/20160612064724
core/libcap/2.24/20160612075226
core/linux-headers/4.3/20160612063537
core/make/4.1/20160612080650
core/ncurses/6.0/20160612075116
core/openssl/1.0.2h/20160612081127
core/python2/2.7.11/20160620182552
core/readline/6.3.8/20160612075601
core/zlib/1]
DEBUG:habitat_core::package::archive: id = [core/acl/2.2.52/20160612075215]
DEBUG:habitat_core::package::archive: id = [core/attr/2.4.47/20160612075207]
DEBUG:habitat_core::package::archive: id = [core/bzip2/1.0.6/20160612075040]
DEBUG:habitat_core::package::archive: id = [core/cacerts/2016.04.20/20160612081125]
DEBUG:habitat_core::package::archive: id = [core/coreutils/8.24/20160612075329]
DEBUG:habitat_core::package::archive: id = [core/gcc-libs/5.2.0/20160612075020]
DEBUG:habitat_core::package::archive: id = [core/glibc/2.22/20160612063629]
DEBUG:habitat_core::package::archive: id = [core/gmp/6.1.0/20160612064724]
DEBUG:habitat_core::package::archive: id = [core/libcap/2.24/20160612075226]
DEBUG:habitat_core::package::archive: id = [core/linux-headers/4.3/20160612063537]
DEBUG:habitat_core::package::archive: id = [core/make/4.1/20160612080650]
DEBUG:habitat_core::package::archive: id = [core/ncurses/6.0/20160612075116]
DEBUG:habitat_core::package::archive: id = [core/openssl/1.0.2h/20160612081127]
DEBUG:habitat_core::package::archive: id = [core/python2/2.7.11/20160620182552]
DEBUG:habitat_core::package::archive: id = [core/readline/6.3.8/20160612075601]
DEBUG:habitat_core::package::archive: id = [core/zlib/1]
✗✗✗
✗✗✗ Invalid package identifier: "core/zlib/1". A valid identifier is in the form origin/name (example: acme/redis)
✗✗✗
```

**Comment by metadave** [comment]
Excellent, I pushed another change to [this branch](https://github.com/habitat-sh/habitat/compare/dp_trace_install), can you recompile `hab` and try again?

If this works, I'll add some tests and open a PR.

**Comment by miketheman** [comment]
The tribe's shaman provides the warrior with a new set of yak-shoes, which provided traction to his yak's hooves and allowed him to barrel past the entrance.

Will he be able to continue on his journey? Only time will tell...
