### ISSUE TITLE
Incorrect argument to chpst in hab-plan-build.sh

### ISSUE THREAD

**Issue by josb-mi** [habitat-sh/habitat#1016]
hab-plan-build.sh has
```
exec chpst \\
    -U ${pkg_svc_user}:$pkg_svc_group \\
    -u ${pkg_svc_user}:$pkg_svc_group \\
    $pkg_prefix/$pkg_svc_run 2>&1
```
(I'm assuming this is where the `run` hook from core/hab-depot comes from.)

I noticed that `sudo hab start core/hab-depot` gave `Permission denied` errors. The source seems to be the `-u hab:hab` in the above - when I remove it, the process starts correctly.

**Comment by smith** [comment]
I wouldn't necessarily say it's an incorrect argument, as the default user/group for services is `hab`.

So, at the moment, the system expects there to be that user/group. Admittedly this isn't the best experience, but I'm going to close this because things have improved drastically with #1012.

**Comment by josb-mi** [comment]
@smith how do you explain this, please?
```
dev-josb% id hab
uid=42(hab) gid=42(shadow) groups=42(shadow)
dev-josb% sudo hab start core/hab-depot
hab-sup(MN): Starting core/hab-depot
hab-sup(GS): Supervisor 10.50.110.119: 8d831ac2-6834-4cdd-bb2c-bf6732c4ff7e
hab-sup(GS): Census hab-depot.default: 2aacfd7c-5487-4f4f-befb-2d946c8c956b
hab-sup(GS): Starting inbound gossip listener
hab-sup(GS): Starting outbound gossip distributor
hab-sup(GS): Starting gossip failure detector
hab-sup(CN): Starting census health adjuster
hab-depot(SV): Starting
hab-depot(O): chpst: can't execute '/hab/pkgs/core/hab-depot/0.6.0/20160612143006/bin/hab-depot': Permission denied
hab-sup(SV): hab-depot - process 6069 died with exit code 126
hab-sup(SV): hab-depot - Service exited
hab-depot(SV): Starting
hab-depot(O): chpst: can't execute '/hab/pkgs/core/hab-depot/0.6.0/20160612143006/bin/hab-depot': Permission denied
hab-sup(SV): hab-depot - process 6072 died with exit code 126
hab-sup(SV): hab-depot - Service exited
hab-depot(SV): Starting
...
```
What am I doing wrong? I followed what little docs there are on running core/hab-depot, and this is what I get. As you can see, `hab:hab` already exists, I created it per the instructions.

When I make the suggested change to the `run` script, it works.

**Comment by smith** [comment]
I'm not sure why /hab has 750 permissions on you machine. Everywhere I'm looking it has 755. Do you know if you start using it on a new machine, if it will get created with 750 permissions like that?

I don't know if using the core/hab-depot package directly will work very well, if at all. It looks like it was last build June 12 (which is an eternity ago in this project's current state. I'd like to leave this open to resolve your issue, but we've got some work to do before running the depot on-premises will be as easy as we would like, and I don't think running this package is the way to get you there.

**Comment by adamhjk** [comment]
It's probably the umask. We should consider setting the permissions on /hab correctly ourselves.

**Comment by josb-mi** [comment]
Fwiw, umask is `007`.

I ran into another problem with the depot key being zero'd that @juliandunn tried to assist me with on Slack, so I'll probably start over with a new machine, this time making sure to create `hab:hab` right off the bat.

It would indeed be very useful to be able to run one's own depot server. From what I have seen so far, it seems to sort of work but no doubt the experience could be improved.

Thanks for your help sorting this out.
