### ISSUE TITLE
can't run `core/openvpn` from within an interactive Studio session

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#1026]
Running this on macOS with the Docker beta.
example output:
```
[23][default:/src:0]# hab start core/openvpn
hab-sup(MN): Starting core/openvpn
hab-sup(GS): Supervisor 172.17.0.2: 47299759-1590-4a4d-a3d0-b29fe4ead838
hab-sup(GS): Census openvpn.default: 3290522a-fa71-4727-a91c-e56373c45ce8
hab-sup(GS): Starting inbound gossip listener
hab-sup(GS): Starting outbound gossip distributor
hab-sup(GS): Starting gossip failure detector
hab-sup(CN): Starting census health adjuster
hab-sup(SC): Updated server.conf
hab-sup(TP): Restarting because the service config was updated via the census
openvpn(SV): Starting
hab-sup(SV): openvpn - process 5923 died with exit code 1
hab-sup(SV): openvpn - Service exited
openvpn(SV): Starting
hab-sup(SV): openvpn - process 5928 died with exit code 1
hab-sup(SV): openvpn - Service exited
```

**Comment by bixu** [comment]
Looks like this is an issue with missing certs, which I should have realized.

**Comment by reset** [comment]
@bixu is your isssue resolved then?

**Comment by bixu** [comment]
I feel like there's still a lack of clarity in the README for the openvpn plan, but I'll close this issue.

**Comment by reset** [comment]
@bixu I think there still might be some work to be done to get it working. I haven't consumed it yet and I'm the person who started the work and then asked for somebody to follow up on it ;)

**Comment by bixu** [comment]
@reset I'm continuing to hack on it before I pass out here in Berlin - end result will be a README for my org, and I can pass back any findings/docs to this plan.
