### ISSUE TITLE
feature request: hab supervisor act as syslog

### ISSUE THREAD

**Issue by paulczar** [habitat-sh/habitat#1034]
some apps ( haproxy? ) really want to use syslog ...  since we have a supervisor running, maybe we should tie in a minimal syslog server that would just reprint anything sent to it to stdout.   this would help old apps behave more 12-factorish

**Comment by adamhjk** [comment]
I'm :-1: on putting a minimal syslog server into the supervisor itself. If you really need this functionality, we can package up a minimal syslog and run it along side with the director.
