### ISSUE TITLE
Docs needed for do_check callback

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#1039]
The `do_check` callback is a powerful mechanism to validate the build process has completed successfully, and does not appear in the docs: https://www.habitat.sh/docs/reference/plan-syntax/#callbacks

**Comment by adamhjk** [comment]
When we document this, lets make it clear that you need to set `env DO_CHECK=true`, not just `DO_CHECK`.

**Comment by bscott** [comment]
This was resolved in PR#1062

**Comment by miketheman** [comment]
Thanks! Using #1062 (without a `PR`) to autolink.
