### ISSUE TITLE
activating do_check during build cycle doesn't follow expected pattern

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#1040]
In order to activate the `do_check` callback, the expectation is that an environment variable be set.

My expectation was that you run the build like so:
```
$ hab studio enter
[1][default:/src:0]# DO_CHECK=true build
...
```

However this is not picked up in the execution environment, rather I have to `export DO_CHECK=true` before the build.

Minor issue, would have probably been prevented a lot of time waste by #1039.

code: https://github.com/habitat-sh/habitat/blob/9081c0a41df7fc32f08c803fe6ed7457b2d39206/components/plan-build/bin/hab-plan-build.sh#L1742-L1768

**Comment by adamhjk** [comment]
This isn't a bug. You want $DO_CHECK to be true for sub-shells as well. Lets include this in the documentation, but you should use `env` to set environment variables. Thanks, Unix!
