### ISSUE TITLE
Documentation section links

### ISSUE THREAD

**Issue by tomrobison** [habitat-sh/habitat#1046]
I would like to be able to link to specific sections of a page of documentation. Such as directly to the section "Running packages in any environment" in https://www.habitat.sh/docs/run-packages-overview/.  Maybe even highlight the whole section like specific lines on Github.

**Comment by juliandunn** [comment]
You can already do that because Middleman generates an ID that can be used as a name href to each section. To get to the section you want: https://www.habitat.sh/docs/run-packages-overview/#running-packages-in-any-environment

**Comment by juliandunn** [comment]
Also, I couldn't find anything in Middleman that will do what you are asking for about highlighting sections of _text_ (`middleman-syntax` appears to handle blocks of code at first glance). You're welcome to play with it and see if you can get it to go: https://github.com/middleman/middleman-syntax

**Comment by tomrobison** [comment]
Thanks
