### ISSUE TITLE
Origin support to unlist packages

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#1051]
Currently there is no way to remove a package(unless there is good reason).

I propose `habitat` to support unlisting packages, like `crates.io` does.
The idea is that some packages might be broken or some other issues might appear with them.
The person that published that package might release another version with a fix and desire to unlist the broken package, currently this is not possible.
After unlisting, the package will still be present and work for those that specifically select to use that version, but it will not be available/visible to new users.

**Comment by eeyun** [comment]
This is absolutely something that we're going to want to take on. Thank you for opening the issue and we'll come back to close this circle when we have it implemented.

**Comment by lilianmoraru** [comment]
I gave these examples but the main reason I opened this was because there were to many old versions of packages and it was really confusing when trying to search for a package.

**Comment by gfodor** [comment]
+1 for this, we had a mis-naming of one of our packages ("libopus" vs "opus", a redistribution of the opus codec) and now we have the "libopus" (wrong) package floating around. not the end of the world but confusing until we can unlist it.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #18](https://github.com/habitat-sh/builder/issues/18) via [**ZenHub**](https://www.zenhub.com/)
