### ISSUE TITLE
Failed to build habitat on ubuntu 14.04

### ISSUE THREAD

**Issue by bobhlo** [habitat-sh/habitat#1058]
Following 'Setup on native Linux' from https://github.com/habitat-sh/habitat
Issue found - Failed to build habitat on ubuntu 14.04  running in vagrant.

root@default-ubuntu-1404:/home/vagrant/habitat#  make RUST_BACKTRACE=1
sh -c 'cd components/director && cargo build'
   Compiling openssl-sys v0.7.13
   Compiling libarchive3-sys v0.1.1
error: failed to run custom build command for `libarchive3-sys v0.1.1`
Process didn't exit successfully: `/home/vagrant/habitat/components/director/target/debug/build/libarchive3-sys-39241d32e3a42785/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Unable to locate libarchive, err="Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libarchive\"`: No such file or directory (os error 2)"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libarchive3-sys-0.1.1/build.rs:32
stack backtrace:
   1:     0x5608f9acd74f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x5608f9ad42ab - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x5608f9ad3f33 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x5608f9ac407d - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x5608f9ad44f1 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:     0x5608f9ac54ca - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:     0x5608f9aaa720 - build_script_build::main::he5071e1b00fcfe0e
                        at /home/vagrant/habitat/components/director/<std macros>:8
   8:     0x5608f9ad3b78 - std::panicking::try::call::hbbf4746cba890ca7
   9:     0x5608f9ade0db - __rust_try
  10:     0x5608f9ade07e - __rust_maybe_catch_panic
  11:     0x5608f9ad361e - std::rt::lang_start::hbcefdc316c2fbd45
  12:     0x5608f9ab0a09 - main
  13:     0x2b76128fbec4 - __libc_start_main
  14:     0x5608f9aa9858 - <unknown>
  15:                0x0 - <unknown>

make: *** [build-director] Error 101
- [ ] The OS (including version) where you are running any of the Habitat commands.
root@default-ubuntu-1404:/home/vagrant/habitat#  uname -r
4.2.0-35-generic
root@default-ubuntu-1404:/home/vagrant/habitat# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

**Comment by metadave** [comment]
These are the Ubuntu deps we use for our development environment: https://github.com/habitat-sh/habitat/blob/master/Dockerfile#L4-L25

**Comment by bobhlo** [comment]
For people want to test out habitat on ubuntu, what's the suggestion to get around build issues with libsodium and libczmq?

**Comment by metadave** [comment]
Here are the docs to build on Ubuntu Xenial: https://github.com/habitat-sh/habitat/pull/1064/files#diff-dad363871d9408c4438794858aa44f57R3

Older versions of Ubuntu may need to build libsodium manually similar to the Centos instructions: https://github.com/habitat-sh/habitat/pull/1064/files#diff-dad363871d9408c4438794858aa44f57R58

Note, in the Centos 7 build docs, `PKG_CONFIG_PATH` and `LD_LIBRARY_PATH` must be set. You'll probably need the same.

I haven't tried to build libczmq from source, there was a yum repo I could use for Centos.

**Comment by metadave** [comment]
I'm writing up some docs for this, I'll post a PR when they're complete.

Cheers -
Dave

**Comment by metadave** [comment]
ok, PR here: https://github.com/habitat-sh/habitat/pull/1068

Cheers -
Dave

**Comment by metadave** [comment]
For future reference, Ubuntu build docs are located [here](https://github.com/habitat-sh/habitat/blob/master/docs/BUILDING.md#ubuntu-1404)
