### ISSUE TITLE
Documentation fix - TOML usage

### ISSUE THREAD

**Issue by bscott** [habitat-sh/habitat#1059]
Documentation only shows how to use default.toml, not including user.toml

https://github.com/habitat-sh/habitat/blob/7a95707158be8669884c5d48d1ec78e861031edd/components/sup/src/service_config.rs#L337-L340

**Comment by metadave** [comment]
`environment.toml` isn't a thing, [this](https://github.com/habitat-sh/habitat/blob/7a95707158be8669884c5d48d1ec78e861031edd/components/sup/src/service_config.rs#L437) code loads environment variables.

**Comment by bscott** [comment]
@metadave thx I'll update issue, meant to just keep user in the desc.

**Comment by bscott** [comment]
@metadave Any preference where I can put the user.toml documentation in the docs?

**Comment by metadave** [comment]
@bscott lets get @davidwrede's input on that

**Comment by metadave** [comment]
what are your thoughts on putting them somewhere under https://www.habitat.sh/docs/run-packages-overview/ ?

cc @davidwrede @juliandunn

**Comment by davidwrede** [comment]
@bscott, as @metadave suggested, under run-package-overview probably makes the most sense. We can always tweak and move it around later if needed.

**Comment by bscott** [comment]
@davidwrede Ok thanks

To clarify, user.toml is for user defined overrides of config settings.

**Comment by asymmetric** [comment]
@bscott any progress on your work documenting `user.toml`? :)

**Comment by rsertelon** [comment]
Shouldn't it be in https://www.habitat.sh/docs/using-habitat/#config-updates now?

**Comment by tashimi** [comment]
Yes, this looks good now. Thanks @rsertelon!

**Comment by asymmetric** [comment]
@tashimi AFAICT there's still no mention of the `user.toml` on [this page](https://www.habitat.sh/docs/using-habitat/#config-updates), isn't that what this issue was about?

**Comment by rsertelon** [comment]
@asymmetric issue #3977 opened by @christophermaier is in the direction you suggest here IMHO.
