### ISSUE TITLE
Create Community Guides markdown

### ISSUE THREAD

**Issue by bscott** [habitat-sh/habitat#1061]
Hello,

Create a directory with a Markdown file for community guides and screen casts.

**Comment by bscott** [comment]
@smith @davidwrede Suggestions on where we might place this?

**Comment by smith** [comment]
Is this something that's going in the repo or on the website. If it's just in the repo, you could put it doc/community-guides.md and put a link to it in the README. If it's on the website it could go in /community somewhere.

**Comment by davidwrede** [comment]
@bscott, what's the scope for the community guides and screencasts? Contributing to the Habitat binaries or core plans? Tutorial-type content that would be/could be consumed by people visiting habitat.sh?

**Comment by eeyun** [comment]
For now I think we are going to use the habitat [forums](https://forums.habitat.sh) for this content at least until we are able to fill a page with useful information like this. Once we _can_ we'll likely create a link in CONTRIBUTING.md to a community guides type document.

Thank you for bringing this to our attention!
