### ISSUE TITLE
Failed to build habat on CentOS 7.2

### ISSUE THREAD

**Issue by jmstallard** [habitat-sh/habitat#1063]
Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [ ] The OS (including version) where you are running any of the Habitat commands.
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		RUST_LOG=debug RUST_BACKTRACE=1 hab ...
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		env | grep HAB | grep -v HAB_AUTH_TOKEN

	- ***DO NOT include `HAB_AUTH_TOKEN`*** or any other sensitive information. More info on Habitat environment variables can be found [here](https://www.habitat.sh/docs/reference/environment-vars/).
	- [ ] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:
		- [ ] a. before starting the studio
		- [ ] b. inside the studio

- [ ] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.

		ls -la /hab/cache/keys
		ls -la $HOME/.hab/cache.keys

**Comment by jmstallard** [comment]
Hello all:
Just tried to install habitat on a fresh CentOS 7 version in AWS, can't seem to resolve the libarchive3-sys dependencies. I can't implement hint ( add the directory containing `libarchive.pc) because no libarchive.pc exists.
I do have the package installed, and of latest version available (with defautl centos yum repos):
Package libarchive-3.1.2-7.el7.x86_64 already installed and latest version

I see others have had issues with these libraries - and the habitat team states this should work on CentOS 7. Any help would be appreciated.


OS version:

]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core) (AWS Centos 7 marketplace image

Traceback:
...
   Compiling libarchive3-sys v0.1.1
error: failed to run custom build command for `libarchive3-sys v0.1.1`
Process didn't exit successfully: `/tmp/habitat/components/director/target/debug/build/libarchive3-sys-39241d32e3a42785/build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'Unable to locate libarchive, err="`\"pkg-config\" \"--libs\" \"--cflags\" \"libarchive\"` did not exit successfully: exit code: 1\n--- stdout\nPackage libarchive was not found in the pkg-config search path.\nPerhaps you should add the directory containing `libarchive.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'libarchive\' found\n"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/libarchive3-sys-0.1.1/build.rs:32
stack backtrace:
   1:     0x7fe43019072f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x7fe43019728b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x7fe430196f13 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x7fe43018705d - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x7fe4301974d1 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:     0x7fe4301884aa - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:     0x7fe43016d700 - build_script_build::main::he5071e1b00fcfe0e
                        at /tmp/habitat/components/director/<std macros>:8
   8:     0x7fe430196b58 - std::panicking::try::call::hbbf4746cba890ca7
   9:     0x7fe4301a10bb - __rust_try
  10:     0x7fe4301a105e - __rust_maybe_catch_panic
  11:     0x7fe4301965fe - std::rt::lang_start::hbcefdc316c2fbd45
  12:     0x7fe4301739e9 - main
  13:     0x7fe42f56ab14 - __libc_start_main
  14:     0x7fe43016c838 - <unknown>
  15:                0x0 - <unknown>

**Comment by metadave** [comment]
Hello -
  I'm writing up some docs on how to build on Centos 7, I'll post them shortly.

Cheers -
Dave

**Comment by jmstallard** [comment]
oh, now that would be sweet. I'll give feedback as soon as they're posted.


Thanks!!

________________________________

**Comment by metadave** [comment]
I tested these build instructions w/ Centos7 in Docker via

        docker run -it centos:centos7 /bin/bash

```
# Install the zeromq yum repo
curl http://download.opensuse.org/repositories/home:/fengshuo:/zeromq/CentOS_CentOS-6/home:fengshuo:zeromq.repo > /etc/yum.repos.d/zeromq.repo

# Install common development tools
yum groupinstall -y 'Development Tools'
# install sudo as the Rust installation needs it
yum install -y sudo libarchive-devel protobuf-devel openssl-devel zeromq-devel libczmq1-devel gpm-libs which

# pkg-config will be able to find libsodium with the following:
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
# needed for the Habitat binaries to find libsodium at runtime
export LD_LIBRARY_PATH=/usr/local/lib

# Install libsodium from source
git clone https://github.com/jedisct1/libsodium.git
(cd libsodium && ./autogen.sh && ./configure && make && make install)

# Install Rust
curl -sSf https://static.rust-lang.org/rustup.sh | sh

# Clone the Habitat source
git clone https://github.com/habitat-sh/habitat.git
cd habitat && make
```


- Once make has finished, executables will exist in `components/**/target/debug/foo`, where `foo` is the name of an executable (`hab`, `hab-sup`, `hab-depot`, etc).

- Executable names are specified in each components `Cargo.toml` file in a TOML table like this:

		[[bin]]
		name = "hab-depot"

- If you have issues with libsodium at runtime, ensure that you've set `LD_LIBRARY_PATH`:

	     export LD_LIBRARY_PATH=/usr/local/lib

**Comment by jmstallard** [comment]
Oh great., let me try this out now..


-j


________________________________

**Comment by metadave** [comment]
I submitted a PR with build instructions for Centos 7 + Ubuntu Xenial: https://github.com/habitat-sh/habitat/pull/1064

**Comment by jmstallard** [comment]
These instructions worked for me Dave. Thanks for the quick response!


components/hab/target/debug/hab --help
hab 0.7.0

Authors: The Habitat Maintainers <humans@habitat.sh>

"A Habitat is the natural environment for your services" - Alan Turing

USAGE:
    hab [FLAGS] [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    cli        Commands relating to Habitat runtime config
    config     Commands relating to Habitat runtime config
    file       Commands relating to Habitat files
    help       Prints this message or the help of the given subcommand(s)
    origin     Commands relating to Habitat origin keys
    pkg        Commands relating to Habitat packages
    ring       Commands relating to Habitat rings
    service    Commands relating to Habitat services
    studio     Commands relating to Habitat Studios
    sup        Commands relating to the Habitat Supervisor
    user       Commands relating to Habitat users

ALIASES:
    apply      Alias for: 'config apply'
    install    Alias for: 'pkg install'
    setup      Alias for: 'cli setup'
    start      Alias for: 'sup start'


-j.


________________________________

**Comment by metadave** [comment]
excellent @jmstallard, I'll close this issue and work out of https://github.com/habitat-sh/habitat/pull/1064

**Future readers: please note, the instructions here may changed and will be reflected in `docs/BUILDING.md`** per PR #1064
