### ISSUE TITLE
Most executables and libraries are not stripped (feature not bug?)

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#1066]
Despite the following log output:

```
Stripping unneeded symbols from binaries and libraries
```

Most of the executables and libraries are not stripped.  The cause of this is the following invocation of `find` in plan-build:

https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L2046

`-perm u+w` will only match files with mode 0200 which is likely rather rare.  I believe the intent here was probably `-perm -u+w` (note the leading `-`), which will match any permission where the owner has write permissions.  

Before I put together a quick PR, I was wondering if, given the fact that most of the packages I've pulled down from `core` aren't currently stripped, if y'all still feel if stripping the executables are the right default behavior.  Stripping the executables reduces their size but at the expense of what can be valuable debugging information.

**Comment by miketheman** [comment]
I can understand if the concern is "disk space on embedded systems is tight" - but that could/should be an opt-in, since as @stevendanna mentions, debugging info is lost.

I can see a case for this in potentially  speeding up data transfers - but has this been measured? (I guess not, if they aren't really being stripped right now.)

It may also reduce the depot overhead and bandwidth transfer - but if there's no way to get the debug symbols (a la `apt-get install xserver-xorg-core-dbg`), getting into low-level tracing is going to be more difficult.

**Comment by stevendanna** [comment]
For clarity, my preference would be that we don't strip by default and either provide an environment variable(`DO_STRIP=true`) or provide a helper function that people could use in their own `do_strip` function.

**Comment by reset** [comment]
@stevendanna I'd rather we swap that behaviour. We should strip by default and provide an environment variable to disable it. With the logic swapped we're essentially making debug builds the default.

An environment variable or a flag to the build app would be nice. I actually wanted this feature so I didn't need to modify my plan to create a release build vs a debug build by switching on a variable set and made available inside my `plan.sh`.

**Comment by fnichol** [comment]
Yep, that was a bug--the intended default was to strip as all other OS packaging systems do by default. The easiest "opt-out" for Plan authors is to override the `do_strip()` phase like so:

```sh
do_strip() {
  return 0
}
```

I'd advocate that we need to be extremely careful with environment variables that drive different build behaviors. If we push things too far, it will no longer be possible to have a) consistent builds, b) full knowledge about how the package was built. The `DEBUG_BUILD` env var in #1085 but I'm not totally sold yet :) Just thinking on it though

**Comment by fnichol** [comment]
Having said the above, there's nothing preventing a Plan author from honoring an environment variable, local file, or config in their `plan.sh`. Just remember that currently: 1 Plan yields exactly 1 package artifact. That was by design, even if it means writing more Plans.

**Comment by stevendanna** [comment]
@fnichol Yup, I'm +100 on removing the env variable personally, I just included it based on the previous discussions.

**Comment by stevendanna** [comment]
Per my original comment, I personally like having the debug symbols around by default, but I think being in line with other distros does make sense.  I could be nice for core-plans to provide some facility for shipping debug symbols similar to the -debuginfo packages you can install in Fedora.  We'd have to get gdb configured to use them: https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html
