### ISSUE TITLE
Package hierarchy howto

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [habitat-sh/habitat#1072]
Is there currently a way for creating packages as hierarchies? I'm trying to **extend** a package, meaning I want to download extra files and put them in places. Specifically, I have created a neo4j-enterprise package which works fine, now I want to have a _fork_ which downloads `graphaware-framework` and adds it as an unmanaged extension. The logic for download and amendments in config could be achieved by the `plan.sh` file and callbacks.

``` bash
pkg_origin=myorigin
pkg_suffix=server-community
pkg_name=graphaware-framework
pkg_version=3.0.3.39
pkg_source=http://products.graphaware.com/download/framework-${pkg_suffix}/graphaware-${pkg_suffix}-all-${pkg_version}.jar
pkg_filename=${pkg_name}-${pkg_version}.jar
pkg_shasum=a825cc711648b64a2c5fe456b941374c83d444886af3608158b661f3a694d7b4
pkg_deps=(myorigin/neo4j-enterprise)

do_begin() {
  export NEO4J_HOME=$(hab pkg path myorigin/neo4j-enterprise)/neo4j
}

do_unpack() {
  mv $HAB_CACHE_SRC_PATH/$pkg_filename $NEO4J_HOME/plugins
}

do_build() {
  export NEO4J_CONF=$NEO4J_HOME/conf
}

do_install() {
  echo "dbms.unmanaged_extension_classes=com.graphaware.server=/graphaware" >> $NEO4J_CONF/neo4j.conf
}
```

The way I'm currently trying to achieve this is to add `neo4j-enterprise` that I've created as a `pkg_deps`. I'm not sure though how I could inherit the `init` and `run` hooks.

A side issue, I get an error referencing my own package `myorigin/neo4j-enterprise`:

```
» Installing myorigin/neo4j-enterprise
✗✗✗
✗✗✗ failed to lookup address information: Try again
✗✗✗
   neo4j-enterprise: WARN No installed packages of 'myorigin/neo4j-enterprise' were found
ERROR: Resolving 'myorigin/neo4j-enterprise' failed, should this be built first?
```

**Comment by miketheman** [comment]
First off, there's a builtin shortcut for determining the path, so this could better be expressed as:
```
export NEO4J_HOME=$(pkg_path_for neo4j-enterprise)/neo4j
```
ref: https://www.habitat.sh/docs/reference/plan-syntax/#utility-functions

Re: The error message for `myorigin/neo4j-enterprise` - if you're building that package locally into a .hart file, you might be able to experiment with copying the file into a place that the builder can access (next to the plan.sh file is what I've done) and then inside the studio, before the build, run:

    hab pkg install <path to myorigin-neo4j-enterprise.......hart>

Then running the `build` should find the installed package.

**Comment by keyvan-m-sadeghi** [comment]
Thank you very much @miketheman, I'm over the side issue of `✗✗✗ failed to lookup address information: Try again` thanks to your suggestion.

The `pkg_path_for` utility function does not work in my `studio` though, not sure why that is, I copied `export NEO4J_HOME=$(hab pkg path myorigin/neo4j-enterprise)/neo4j` from the approach taken in [most of the core plans](https://github.com/habitat-sh/core-plans/search?utf8=%E2%9C%93&q=%22%24%28hab+pkg+path%22).

The main issue, however, still persists. It's not clear how one could construct packages as hierarchies. I faced more serious problems down my way, as an example I'm trying to run neo4j from the original package via this ugly hack:
```bash
do_install() {
  cd $pkg_prefix
  printf "export \$NEO4J_HOME=$NEO4J_HOME\n" >> neo4j.sh
  printf "export \$NEO4J_CONF=$NEO4J_CONF\n" >> neo4j.sh
  printf "cd \$NEO4J_HOME/bin\n" >> neo4j.sh
  printf "ls -lah" >> neo4j.sh
  printf "./neo4j console\n" >> neo4j.sh
  sed -i "1i #!/bin/bash" neo4j.sh
}
```
and then the run hook:
```bash
#!/bin/bash
cd {{pkg.path}}
head neo4j.sh
./neo4j.sh
```
This doesn't work for reasons I'm not aware of yet, but even if it did its utterly wrong, unreadable and hence not maintainable. I'm creating a duplicate of a logic that I've already written once. There should be a more elegant way. A method for **composing** a package from several package. In my case, a *neo4j instance* augmented with *graphaware-framework* and other *plugins*.

**Comment by keyvan-m-sadeghi** [comment]
I ended up creating a custom package specific for my need, which is hacky since it cannot benefit from the subtleties that plan files provide.
For future reference though, I propose adding a feature named **package extensions**.
A package extension could look like this:

`plan.sh`
```bash
ext_origin=myorigin
ext_pkg=myorigin/neo4j-enterprise
ext_name=graphaware-framework
ext_version=3.0.3.39
ext_source=http://products.graphaware.com/download/framework-server-community/graphaware-server-community-all-${pkg_version}.jar
ext_filename=${pkg_name}-${pkg_version}.jar
ext_shasum=a825cc711648b64a2c5fe456b941374c83d444886af3608158b661f3a694d7b4

# Logic via the same callback mechanism as pkg plans.
```
An extension would apply changes described in it's plan file to a specific package and inherits the `ext_pkg`'s `init`, `run`, etc. hooks.

Using extension mechanism, one could easily create a plan tuned specifically for her own needs:
```bash
ext_origin=myorigin
ext_pkg=myorigin/neo4j-enterprise
ext_name=mycompany-stack
ext_version=1.0
# dependencies listed at ext_deps should have the same ext_pkg
ext_deps=(graphaware-framework graphaware-reco graphaware-uuid)

# No downloads or logic is needed, all requirements are satisfied via the ext_deps
```

**Comment by smith** [comment]
I'm not sure exactly what you're trying to accomplish here, but this looks similar to something that we're doing already.

The [openssl-musl plan](https://github.com/habitat-sh/core-plans/blob/d14c15db0b4a85bc12002ceca4a159678e6ea341/openssl-musl/plan.sh) uses the Bash `source` command to pull in the [openssl plan](https://github.com/habitat-sh/core-plans/blob/d14c15db0b4a85bc12002ceca4a159678e6ea341/openssl/plan.sh) and then overrides its variables and functions for what it needs to do specifically.

Is this similar to what you're trying to do? If not could you provide some more explanation?

**Comment by keyvan-m-sadeghi** [comment]
Hi @smith,

Thank you very much, yes, it is very similar to what I'm trying to accomplish, though it lacks the functionality that I need. In `open-musl`'s case, the only difference between the `source`d package (parent) and child is different `prepare` method.

[Graphaware Hirearchy](http://graphaware.com/products#download_products)

For extending `neo4j`, I need to download a `jar` file for each of the extensions (`graphaware-framework`, `graphaware-uuid` and `graphaware-reco`). Each `jar` file should be verified against it's `sha256sum`. Then each of them should be configured -- amend changes specific to it in the `neo4j.conf` file. These are scenarios that `plan` files are designed to help with, yet bash's `sourc`ing would not suffice since each of the `jar` files would need their own `pkg_source`, `pkg_shasum`, etc. Further, using `source`, the corresponding callbacks (`do_download`, `do_unpack`, ...) would be occupied by the parent package.

Also there is the matter of customisation. Say my stack would consist of `neo4j`+`graphaware-uuid`+`graphaware-reco`:

`graphaware-uuid/plan.sh`
```bash
source ../neo4j/plan.sh

# graphaware-uuid's custom logic
```

`graphaware-reco/plan.sh`
```bash
source ../graphaware-uuid/plan.sh

# graphaware-reco's custom logic
```
Now due some changes, I no longer need `graphaware-uuid` in my stack, but still need `graphaware-reco`. The way my packages are currently laid wouldn't allow that, `graphaware-reco` is hardcoded to source `graphaware-uuid`.

Let me know what you think, cheers.

**Comment by smith** [comment]
I think the simplest thing to do would just be making separate plans for all of them and not sharing anything. If there were a single plan that all of the rest of them depended on, and there was code you needed to share between them, you could, at build time, do something like `source $(package_path_for my/base-thing)/plan-functions.sh`, but is there really so much in common between these that you would really need to do that?

**Comment by keyvan-m-sadeghi** [comment]
@smith 
> but is there really so much in common between these that you would really need to do that?

There are parts that are *not* in common which cause the issue -- `sourc`ing `neo4j`'s plan would override the callbacks which I intended to use, not sourcing it means there is no '`neo4j`.

There is a gap that seems appropriate for habitat to address here, especially if acting as an isolation layer for legacy applications is on your radar., Many legacy apps have similar `plug-in`, `extension`, `add-on`, etc. mechanism.
Even looking at modern apps, like core's [rust package](https://github.com/habitat-sh/core-plans/blob/master/rust/plan.sh#L29), there are scenarios where single `download`, `verify`, `unpack`, `build`, `install` would not suffice -- more complex apps might have to fetch resources from different places and each resource may have it's own `build`/`install` mechanism.

Thinking further from this perspective, instead of my previous proposal of having special syntax for extensions, plan syntax could be extended to support `phase`s. Each phase embodying steps for building one `part` of the app. I'm no shell pro, a simple Google search yields [`Blocks`](http://www.tldp.org/LDP/abs/html/abs-guide.html#EX8), so using some block mechanism, each part in a plan could have it's own callbacks.

This would pave the way for your `source` suggestion, as new callbacks won't shadow previous ones. Also, it could be added without introducing breaking changes to the current plan syntax. Phases would be optional, one could implement only one phase, as plans do today.

**Comment by keyvan-m-sadeghi** [comment]
@smith If you point me at where to start, I might find the time to cook up a PR.

**Comment by keyvan-m-sadeghi** [comment]
@smith 
Hmmm actually there might be an easier way:
If we change the final lines of [`hab-plan-build.sh`](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L2342) and add an `apply_plan` wrapper function to it:
```bash
apply_plan() {
  # Run `do_begin`
    build_line "$_program setup"
    do_begin
  
  # Determine if we have all the commands we need to work
    _find_system_commands
  
  # Enure that the origin key is available for package signing
    _ensure_origin_key_present
  
    _determine_hab_bin
  
  # Download and resolve the depdencies
    _resolve_dependencies
  
    _set_path
  
  # Download the source
    mkdir -pv $HAB_CACHE_SRC_PATH
    do_download
  
  # Verify the source
    do_verify
  
  # Clean the cache
    do_clean
  
  # Unpack the source
    do_unpack
  
  # Set up the build environment
    _build_environment
  
  # Fix any libtool scripts in the source
    _fix_libtool
  
  # Prepare the source
    do_prepare_wrapper
  
  # Build the source
    do_build_wrapper
  
  # Check the source
    do_check_wrapper
  
  # Install the source
    do_install_wrapper
  
  # Copy the configuration
    do_build_config
  
  # Copy the service management scripts
    do_build_service
  
  # Strip the binaries
    do_strip
  
  # Write the manifest
    _build_manifest
  
  # Render the linking and dependency files
    _build_metadata
  
  # Generate the artifact and write to artifact cache
    _generate_artifact
  
  # Copy produced artifact to a local relative directory
    _prepare_build_outputs
  
  # Cleanup
    build_line "$_program cleanup"
    do_end
}
apply_plan
```
then it'll be possible to use your `source` suggestion:
```bash
source ../neo4j/plan.sh
pkg_name=graphaware-framework

# Explicit call to apply neo4j's plan which creates it's binaries and other stuff needed for the extension to function
apply_plan

pkg_name=graphaware-framework
pkg_version=3.0.3.39
pkg_source=http://products.graphaware.com/download/framework-server-community/graphaware-server-community-all-${pkg_version}.jar
pkg_filename=${pkg_name}-${pkg_version}.jar
pkg_shasum=a825cc711648b64a2c5fe456b941374c83d444886af3608158b661f3a694d7b4

# An implicit invocation of apply_plan would be carried out by hab-plan-build.sh
```

**Comment by smith** [comment]
I'm not sure I completely follow. @fnichol do you have any thoughts?

**Comment by smurawski** [comment]
Thanks for filing a GitHub Issue.

In the Habitat org, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Habitat?" are better answered by our awesome community on the Habitat forums, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists here. On StackOverflow, please tag your question with the "habitat" label so that it shows up in this list.

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.
