### ISSUE TITLE
Package names with a dot generate invalid default group

### ISSUE THREAD

**Issue by pharaujo** [habitat-sh/habitat#1089]
I'm trying to package in habitat an upstream service that has a dot in its name (e.g. `service.something`).

Building the `.hart` works with no warnings. However, when running the service without specifying a `--group`, the generated group becomes `service.something.default` which can't be used with `hab config apply` because it's invalid.

My suggestions are either making these names an error, emitting a warning in the build process, or removing the dots from the generated default group.

I'm running `hab 0.8.0/20160708161531`.

**Comment by metadave** [comment]
thanks @pharaujo, we'll take a look. 

related Slack discussion: https://habitat-sh.slack.com/archives/general/p1469025611000427

**Comment by metadave** [comment]
@habitat-sh/habitat-core-maintainers what are your thoughts on limiting package names during build to `^[A-Za-z0-9_-]+$`

**Comment by beddari** [comment]
As a user I'm perfectly happy about your suggestion @metadave

**Comment by reset** [comment]
@metadave packages are most certainly not supposed to be allowed to have a dot (`.`) in their name. Oops!

**Comment by davidwrede** [comment]
Docs will be corrected shortly. Apologies for any confusion!

**Comment by metadave** [comment]
@davidwrede we'll also need to update `hab-plan-build.sh` with the [regex above](https://github.com/habitat-sh/habitat/issues/1089#issuecomment-234004136), but having doc updates would be excellent!
