### ISSUE TITLE
Clarify origin key documentation

### ISSUE THREAD

**Issue by metadave** [habitat-sh/habitat#1096]
- we should state that if multiple people are building for a single origin, they'll have to share the keys somehow.
- clarify the text on the "origins" page, which currently reads:

```
Origin keys ensure only authorized users (or organizations) are able to push updates to packages in this origin.

Read the docs for more information on managing and using keys.
```

See: https://habitat-sh.slack.com/archives/general/p1469212072000790

**Comment by smurawski** [comment]
Additional info for https://github.com/habitat-sh/habitat/issues/912.

Thanks!
