### ISSUE TITLE
Please add search to the habitat docs page

### ISSUE THREAD

**Issue by jekriske** [habitat-sh/habitat#1098]
The Habitat docs page has no search functionality. It'd be nice if we could search the docs directly from the site.

**Comment by bscott** [comment]
There are a few solutions for this, since the docs are served using middleman, we may be able to use one of the existing solutions like the ```middleman-search``` ruby gem.

**Comment by smith** [comment]
That looks interesting. https://docs.chef.io/search.html uses Google Site Search which is probably what we'll go with.

**Comment by metadave** [comment]
cc @davidwrede

**Comment by davidwrede** [comment]
Going with the same mechanism as the docs.chef.io site, I've assigned this ticket to CIA to get them to implement Google Site Search on the habitat docs.

**Comment by cwebberOps** [comment]
This is handled by #1110
