### ISSUE TITLE
core/python2 can't use sqlite

### ISSUE THREAD

**Issue by ThisGuyCodes** [habitat-sh/habitat#1099]
I'm not even sure if this is where I should report/ask this. But I figure it's a good start:

I noticed the latest version of core/python2 added a `do_check()`:

``` sh
do_check() {
  LD_LIBRARY_PATH=$PWD ./python -E -c 'import sqlite3'
}
```

However, if you (try to) run this fairly basic plan.sh, you'll notice python's sqlite still doesn't work :/

``` sh
pkg_origin='thisguy'
pkg_name='python2sqlitenowork'
pkg_version='/shrug'
pkg_maintainer='Travis Johnson <travis@thisguy.codes>'
pkg_license=(MIT)
pkg_source='NONE'
pkg_shasum='FAKE'
pkg_filename='some_name.tar.gz'
pkg_deps=(core/python2/2.7.12/201607160020591)

do_download() {
        return 0
}

do_unpack() {
        return 0
}

do_verify() {
        return 0
}

do_build() {
        python -c 'import sqlite3'
}

do_install() {
        return 0
}
```

I've tried manually setting `LD_LIBRARY_PATH` with `$(pkg_path_for core/python2)`, but still nothing:

``` sh
LD_LIBRARY_PATH="$(pkg_path_for core/python2)" python -c 'import sqlite3'
```
- [x] The OS (including version) where you are running any of the Habitat commands:

Ubuntu 16.04 -> 4.4.0-31-generic
- [x] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:

```
HAB_ORIGIN=thisguy
```

**Comment by smith** [comment]
We probably need to do something similar to what we did for python3 in https://github.com/habitat-sh/core-plans/commit/c1486d2ed3ba58ab9f225317c3f55dc7d1e89340#diff-fd1ebda2a8d3c619984801f9afd54b1b.

Adding a dependency on `core/sqlite` should make it work.

**Comment by smurawski** [comment]
@ThisGuyCodes if this is still an issue, this should be opened against the core-plans repo.  Thanks!
