### ISSUE TITLE
Emacs keybindings difficult to use inside docker-based studio

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#1102]
When running `hab studio enter` on OS X, the studio is started inside a docker container.  By default, docker uses the key sequence `CTRL+p CTRL+q` as the `detach keys`.  Unfortunately for emacs users, this means that the common "Up one line" key combination `CTRL+p` becomes `CTRL+p CTRL+p` which is nearly enough to get me to use vim. 

It appears possible to set the key sequence docker will use with `--detach-keys`.  Perhaps this could be exposed to users via an option to `hab studio enter`?  On my mac at least, actually trying to use the escape sequence causes the whole terminal to hang and never return, so another option is to use an alternate sequence completely.

**Comment by stevendanna** [comment]
If I were to implement this, what would y'all think of a generic HAB_DOCKER_OPTS environment variable.  The value of that environment variable could be directly injected to the docker command line when starting the studio.  It has the advantage of giving users access to other 1-out-of-a-100-users docker features without cluttering up the main set of command line options with one-offs.

**Comment by juliandunn** [comment]
That works for me, @stevendanna.

**Comment by reset** [comment]
@stevendanna I also 👍 that idea

**Comment by bdangit** [comment]
doing that then we could possibly expose ports out of studio.

**Comment by juliandunn** [comment]
Another thought @stevendanna would be to move some of the existing options we pass to Docker into a default setting for this variable. This would allow you to, for example, make `hab pkg export` use a user-specified Docker socket instead of always assuming it's the one on the host system.

**Comment by juliandunn** [comment]
`HAB_DOCKER_OPTS` was implemented in Habitat 0.12.x.
