### ISSUE TITLE
Supervisor attempts to perform config substitutions on directories in the config directory

### ISSUE THREAD

**Issue by tevert** [habitat-sh/habitat#1116]
I found this by accidentally 'cp -R <mysrc>/config <myPkg>/config', which creates '<mypkg>/config/config'. 
The supervisor attempts to perform handlebars substitution on _everything_ in the config directory, which naturally blows up on the nested directory. 

Suggested possible fixes: 
- Nicer error message than a generic IO error
- Skip directories
- Recurse inside directories

**Comment by bdangit** [comment]
oh probably explains why can't have nice nested config directories inside the config folder.

**Comment by fnichol** [comment]
Looks like #1236 is a candidate fix here, we'll follow up in the PR to close this loop, thanks!

**Comment by christophermaier** [comment]
Closing for fix in #1236
