### ISSUE TITLE
Allow ignoring of certain file types (e.g. *.swp) in config/ dir during build

### ISSUE THREAD

**Issue by mivok** [habitat-sh/habitat#1120]
When editing files with vim, it opens up a filename.swp file while the editor is open. If you build a package while the editor is open on a config file (as you do often during development), the config/config.json.swp file ends up included in the final package, resulting in the following error when you go to run the package with hab start:

```
DEBUG:habitat_sup::service_config: Config template .config.json.swp at "/hab/pkgs/chefops/foo/0.1.0/20160803162046/config/.config.json.swp"
hab-sup(ER)[src/error.rs:322:8]: IOError(Error { repr: Custom(Custom { kind: InvalidData, error: StringError("stream did not contain valid UTF-8") }) })
```

It would be nice to be able to specify a list of files to exclude from the package, possibly via environment variable that is passed to the studio (so you could just put something like `export HAB_CONFIG_EXCLUDE="*.sw* *~ *.bak"` in your .bashrc and have it work), so that these files are not included in the final package.

It might also be worth having defaults for common editor swap and backup files in the excludes too, so that people don't run into this issue by default.

**Comment by efyang** [comment]
So to be clear you would have a list of defaults that would be overridden if the environment variable was set?

**Comment by mivok** [comment]
Yes, although I haven't thought through the implementation in detail, so it's quite possible there's a better way.

**Comment by efyang** [comment]
Alright, I'll try making a basic implementation of it this week.

**Comment by chefsalim** [comment]
Hey @efyang that is awesome, let us know if you need any help!  This work is on our radar/list to work on, let me know if you don't get to it in the next day or so...

**Comment by efyang** [comment]
@chefsalim I should be able to get started on it tomorrow or the day after, I just need a little time to get acquainted with the internals and the internal structure. I'll definitely ask if I have questions though, thanks!

**Comment by efyang** [comment]
Alright @chefsalim, so I've taken a look through the source, and so I think I understand what I should be doing now (correct me if I'm wrong on any of these). So the only possible ways for a file to get copied into the final package or processed are if they're explicitly copied in the `do_install` step in their project's `plan.sh`, in which case those files should be kept and not ignored, or if they're config templates, in which they are registered [here](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/service_config.rs#L176). So from what I understand, to do the ignore step I would just need to find out where the `Package` (the `pkg` argument) is initially created, and just exclude the files at that step based on the value of the `HAB_CONFIG_EXCLUDE` environment variable.

**Comment by chefsalim** [comment]
Hi @efyang - you are correct on the do_install step, which we don't need to worry about.  The key change I think will be in components/plan-build/bin/hab-plan-build.sh. Take a look at this function: do_default_build_config for example. You can see that there is a 'cp -r' command here. In the repro case above, this causes all the files in the config folder to be copied over to the package (you can check the manifest for the package in/hab/pkgs/<your origin>/<your app name>/<your app version>/<your app id>/FILES and see that the extra file appears in this list). Hope this helps!

**Comment by efyang** [comment]
Ah alright makes sense.

**Comment by efyang** [comment]
Sorry for bugging you again, but how do you get hab to use an updated `hab-plan-build.sh`? I'm currently just running `make` to rebuild habitat, and then running the debug binary from another test directory, but I think that only updates the binaries and not the shellscripts that are used, so the studio just uses the old `hab-plan-build.sh` when I run `build`.

**Comment by efyang** [comment]
Never mind, figured it out. Sorry for the noise.

**Comment by chefsalim** [comment]
Hi @efyang - your PR looks pretty good, however there are a couple of review comments that would be good to update in the PR.  Please let us know if you need further assistance - thanks!

**Comment by efyang** [comment]
Will do. So at the current point the general consensus is just to change `*.sw*` to `*.sw?` if I'm not mistaken?

**Comment by chefsalim** [comment]
Yes, that should be sufficient @efyang - thanks!

**Comment by chefsalim** [comment]
Your change is merged!  Thanks @efyang
