### ISSUE TITLE
be able to populate hook content with dynamic config from cfg.*

### ISSUE THREAD

**Issue by noxxious** [habitat-sh/habitat#1126]
Just trying to do a simple package where the run hook would include parameters based on config values. If there's no file under config then the run hook is not updated an the package is not restarted resulting in the values not being picked up.

As a workaround I could place a bogus env.sh file under config that would contain all the settings variables and then include it in the hook, or just by having in there the hooks are updated upon restart.

run hook:
# !/bin/sh

export USE_RUBY=1
export LOGSTASH_WORKERS="{{cfg.num_workers}}"
export LANG=en_US.UTF-8
export LOGSTASH_CONFIG="{{pkg.svc_config_path}}/logstash.conf"

echo "=== cfg.num_workers = ${LOGSTASH_WORKERS}"
echo "=== cfg.config_path = ${LOGSTASH_CONFIG}"

if [ ! -z {{cfg.config_path}} ]; then export LOGSTASH_CONFIG="{{cfg.config_path}}"; fi

echo "cfg.num_workers = ${LOGSTASH_WORKERS}"
echo "cfg.config_path = ${LOGSTASH_CONFIG}"
echo "sys.ip          = {{sys.ip}}"
echo "sys.hostname    = {{sys.hostname}}"

exec {{pkg.path}}/bin/logstash -w ${LOGSTASH_WORKERS} -f ${LOGSTASH_CONFIG} --log {{pkg.svc_var_path}}/log/logstash.log 2>&1

**Comment by eeyun** [comment]
@noxxious thank you for opening this feature request!


This is definitely something that would be worth addressing. For now the workaround you've proposed above definitely seems like a reasonable way to move forward. We haven't had any other community members ask us to address this just yet. So, what we're going to do is add this into our Help Wanted milestone for today and then discuss internally about whether this feature is something we can/should get prioritization over internally.

Thanks again!

**Comment by adamhjk** [comment]
Pretty sure this is done in the latest version of the supervisor. We should double check, @eeyun.

**Comment by smith** [comment]
Verified this is working. Example: https://app.habitat.sh/#/pkgs/smith/bar/0.1.0/20170529035106
