### ISSUE TITLE
Supervisor enters infinite loop with CPU spike after receiving configuration update for package

### ISSUE THREAD

**Issue by noxxious** [habitat-sh/habitat#1127]
Just noticed that if I do configuration update with debug logging enabled (tried to see why there's a CPU usage spike on hab-sup process after configuration update) and noticed that the supervisor enters an infinite loop of trying to update the configuration, but not producing any changes.

Tried to see in the code and I think the culprit is the code block checking the gossip.toml file checksum and in case it matches it does not update written to true, hence resulting in a loop. 
https://github.com/habitat-sh/habitat/blob/master/components/common/src/gossip_file.rs#L209

[log.txt](https://github.com/habitat-sh/habitat/files/402865/log.txt)

**Comment by reset** [comment]
@noxxious thank you for doing the digging here! We'll get this fixed up soon

**Comment by adamhjk** [comment]
I can confirm this. To recreate the issue:

```bash
$ hab start core/redis
```

In another container:

```bash
$ echo 'loglevel = "debug"' > /tmp/redis.toml
$ hab config apply redis.default 1 /tmp/redis.toml --peer PEER
$ hab config apply redis.default 2 /tmp/redis.toml --peer PEER
```

You can then observe that the supervisor goes from using almost no CPU to ~4-10%, and its because of the constant checksum loop.

The fix is exactly as @noxxious surmised. Working the patch up now.

**Comment by adamhjk** [comment]
It's a little more complex, actually. I'll take a look this afternoon.

**Comment by smurawski** [comment]
We've shipped a number of releases since this point, including having most of the supervisor re-written, so if this is still an issue, please re-open.  Thanks!

**Comment by adamhjk** [comment]
This is resolved, FYI.
