### ISSUE TITLE
Habitat does not honor HAB_STUDIOS_HOME environment variable

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#1131]
There are 2 issues here.
1. When running `hab studio` without `sudo` it should set `HAB_STUDIOS_HOME` to [`$HOME/.hab/studios`](https://www.habitat.sh/docs/reference/environment-vars/) but it seems to not do this.
   After a build, you cannot see a `studios` folder in there.
2. When setting manually `HAB_STUDIOS_HOME`, after a build you can see only a few folders in there and not the entire studio environment(the rest are still in `/hab/studios`): `dev  proc  run  sys  var`.
   And all these folders are completely empty.

**Comment by rsertelon** [comment]
Issue number 2 seems to be resolved. At least, my studio is completely in `~/.hab/studios` when setting `HAB_STUDIOS_HOME`

However, for the first point, I see that there has not been any change yet.

Is using `~/.hab/studios` when not run with `sudo` still something that should be implemented?

**Comment by lilianmoraru** [comment]
This behaviour was described in the docs.
I don't know if this is still in there(can't check right now).

**Comment by tashimi** [comment]
@davidwrede could you take a look and see if the docs still describe this behavior?

**Comment by lilianmoraru** [comment]
Seems like the docs didn't change. You can check this in [the link](https://www.habitat.sh/docs/reference/environment-vars/) I provided in the initial comment.
Short: this issue is still valid.
