### ISSUE TITLE
Support for separated build and source directories

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#1132]
Currently habitat extracts source code and builds it in the same folder. And that folder by _default_ is always in `${HAB_CACHE_SRC_PATH}/${pkg_dirname}`, aka [`${HAB_STUDIOS_HOME}`](https://github.com/habitat-sh/habitat/issues/1131)`/hab/cache/src/${pkg_name}-${pkg_version}`.

Having the [_input_ and _output_](https://www.debian.org/News/2016/20160513) on the same hardware device is not desirable for build speed. Not to name the manufacturer, but an NVMe that has 2500 MB/s read speed and 1500 MB/s write speed goes down to 400-500 MB/s when reading and writing on the same device...

It would be desirable for `Habitat` to support building applications in configurable, separate folders.
It probably would mean a new [environment variable](https://www.habitat.sh/docs/reference/environment-vars/)(to select the folder where the source code should be extracted).
The build could have a separate folder. But I am not sure how to make sure all packages automatically adapt to this, without having to go through packages and replace `./configure` with `"${pkg_source}/configure"`, although, it does not seem like a big problem to me right now. This is the same as going through `do_build` and passing always `--prefix="${pkg_prefix}"`.

**Comment by smurawski** [comment]
Thanks @lilianmoraru for the suggestion.  We discussed this idea at length in our triage meeting today (with ideas all over).  I think the better workaround (given it sounds like you have a larger code base you are working with) would be to download and extract outside the studio (where you have easier control of the disks you are landing on) and then enter the studio from where you extracted the source to.

The principal case we are optimizing for is the  app developer who would have the source locally.  We support other scenarios, but our primary optimizations will focus around that scenario.
