### ISSUE TITLE
Invalid Status provided trying to build Habitat on Mac

### ISSUE THREAD

**Issue by hiucimon** [habitat-sh/habitat#1134]
I want to build Habitat in hopes of contributing eventually, but in attempting to build, I get:

hab-0.8.0-20160708161531-x86_64-linux.tar.gz: OK
» Installing core/hab
✗✗✗
✗✗✗ Invalid Status provided
✗✗✗
/bin/sh: 1: hab: not found
The command '/bin/sh -c /tmp/install.sh   && hab install core/busybox-static   && rm -rf /tmp/install.sh /hab/cache' returned a non-zero code: 127
make: *** [image] Error 1

OSX 10.11.6
Source pull was noon today. hab-0.8.0-20160708161531
I have the hab command working fine on my Mac (with the exception of it not working through my corp firewall), but does not seem to find the one it looks to have downloaded in the Docker container when it is trying to build.

**Comment by metadave** [comment]
The easiest way to get started with Habitat development is by using the provided development shell, which can be accessed by `make shell` after cloning the project (which has a dependency on Docker).

Building the entire system in OSX isn't something that we have documented at this point.

The other thing that I'll throw out is you may have to update your `PATH` variable to be able to find the `hab` binary.

**Comment by reset** [comment]
@hiucimon building native on OSX is something we might document in the future but as @metadave notes, we all build inside a Docker container for consistency and simplicity's sake. I'm going to close this discussion for now, but please re-open it if the project's README contains bad or missing information about how to contribute!
