### ISSUE TITLE
Mirror the public depot

### ISSUE THREAD

**Issue by jtimberman** [habitat-sh/habitat#1138]
As a Habitat user with network restrictions or other requirements, I want to run a Depot on my local network. To do this, I need to download all the core dependencies from the public depot or build them myself. The former is preferred as it will require less of my time, care, and feeding, and ensures that I can use known good builds of all packages. 

UX ideas

```
# mirror the entire public depot, including all origin public keys
hab depot mirror

# download a single package and its dependencies
hab depot download core/pkgname

# download an origin public key
hab depot download core
```

Open to other ideas or feedback. This would go nicely with our internal work to make the Depot easier to run for people.

**Comment by bdangit** [comment]
yes! 👍

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #16](https://github.com/habitat-sh/builder/issues/16) via [**ZenHub**](https://www.zenhub.com/)
