### ISSUE TITLE
build error: 'ssl:error:SslError' is undefined

### ISSUE THREAD

**Issue by agrover** [habitat-sh/habitat#1155]
Fedora 24 x64

SslError went away between rust-openssl 0.7.14 and 0.8, I think the openssl = "*" is pulling in 0.8, since it came out 4 days ago.

```
/home/agrover/git/habitat/components/http-client/src/error.rs:32:14: 32:34 error: type name `ssl::error::SslError` is undefined or not in scope [E0412]
/home/agrover/git/habitat/components/http-client/src/error.rs:32     SslError(ssl::error::SslError),
                                                                              ^~~~~~~~~~~~~~~~~~~~
/home/agrover/git/habitat/components/http-client/src/error.rs:32:14: 32:34 help: run `rustc --explain E0412` to see a detailed explanation
/home/agrover/git/habitat/components/http-client/src/error.rs:32:14: 32:34 help: no candidates by the name of `SslError` found in your project; maybe you misspelled the name or forgot to import an external crate?
```

**Comment by metadave** [comment]
@agrover thanks for reporting this, I'm trying to duplicate the issue in our dev shell.

**Comment by reset** [comment]
@agrover We set our constraints to a wildcard (`*`) because we try to keep our dependencies up to date and don't release Habitat as a create. The `Cargo.lock` at the root of the project is locked to `0.7.14` so building should be just fine. Did you happen to run a `cargo update` to bump the locked version in the lockfile?

**Comment by reset** [comment]
@agrover also you might need to run `make distclean` to update your dev shell image. We recently switched to using Cargo 0.13.0 which isn't on the path in older dev shells. We now have one lockfile for the entire project here and if you devshell has an older version of Cargo in it then it won't know how to read that lockfile ;)

**Comment by metadave** [comment]
In a fresh clone of Habitat in a new dev shell (via `make shell`), I'm unable to reproduce the issue. I'm curious if [these](https://github.com/habitat-sh/habitat/blob/master/docs/BUILDING.md#centos-7) docs need to be updated.

**Comment by chetan** [comment]
I ran into this issue as well, building directly on Ubuntu 16.04 following the [build docs](https://github.com/habitat-sh/habitat/blob/master/docs/BUILDING.md#ubuntu-xenial) (no docker/devshell). Upgrading to Cargo 0.13 [nightly](https://github.com/rust-lang/cargo/#installing-cargo) fixed it for me.
