### ISSUE TITLE
Origins do not display until logging back in

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#1161]
Upon initial login, my Origins are visible; however, if I am away for a day (haven't narrowed this down further) then when I re-visit https://app.habitat.sh/#/origins I see this error message (although I am still logged in):

_Failed to load origins: Unauthorized_ (screenshot attached)

If I log out and back in, then the Origins return.

<img width="585" alt="screenshot 2016-08-16 14 10 37" src="https://cloud.githubusercontent.com/assets/446285/17712498/cf9542ce-63bb-11e6-84d2-c5be7fc0d9ac.png">

**Comment by metadave** [comment]
This happened to me this morning as well.

**Comment by juliandunn** [comment]
@ryankeairns do you still have this problem?

**Comment by ryankeairns** [comment]
@juliandunn seems to be working now... I was in there yesterday, again this morning, and did not see this error message.

**Comment by eeyun** [comment]
I haven't seen any of this either.

**Comment by juliandunn** [comment]
Ok. Closing for now.
