### ISSUE TITLE
Warn when docker-based studio is out of date

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#1167]
On OS X`hab studio enter` starts a docker container. The version of `hab` inside of the studio is baked into the docker container.  If the user hasn't run ` docker pull habitat-docker-registry.bintray.io/studio` they may be using an older version of hab without realizing it.

To help users quickly identify the problem, it might be nice to print a warning when the version of `hab` inside the studio doesn't match the version of hab launching the studio.

**Comment by miketheman** [comment]
Related: https://github.com/habitat-sh/habitat/issues/889#issuecomment-226582103

/cc @juliandunn 

This is a pretty confusing behavior, and the `docker pull` command to resolve is pretty much encapsulated here in Issue reports. Until the "new thing" exists, it would be most helpful to remind users on how to update on the [release announcements](https://forums.habitat.sh/t/habitat-0-9-0-released/162) or somewhere appropriate.

**Comment by juliandunn** [comment]
As of Habitat 0.10.x, `hab` on OS X (and later, Windows) will automatically update the studio version to bring it inline with the version of `hab`.

**Comment by miketheman** [comment]
Confirmed with hab 0.10.2/20160930234832 on OSX.

Thanks!
