### ISSUE TITLE
hab pkg upload fails if public key isn't present in /hab/cache/keys

### ISSUE THREAD

**Issue by metadave** [habitat-sh/habitat#1172]
As of [this PR](https://github.com/habitat-sh/habitat/pull/916), when a package is uploaded, it's public key is uploaded as well. Keys can be located in one of 2 places:
- `$HOME/.hab/cache/keys`
- `/hab/cache/keys`

It appears that only keys in the `$HOME/.hab/cache/keys` directory are uploaded if you aren't `root`. If a user has a key in `/hab/cache/keys` upon upload, they'll receive the following error:

```
✗✗✗
✗✗✗ No such file or directory (os error 2)
✗✗✗
```

Compounding the issue is permissions for key files: if they're generated as `root`, you _may_ not have access to upload keys. 

Possible solution: if the key is written by a regular user, we upload from `$HOME/.hab/cache/keys`.

See also: 
https://chefio.slack.com/archives/habitat/p1471396906005146

cc @habitat-sh/chef-engineering-services

**Comment by schisamo** [comment]
> It appears that only keys in the /hab/cache/keys directory are uploaded. If a user has a key in $HOME/.hab/cache/keys upon upload

@metadave We were actually experiencing the opposite. The key existed in `/hab/cache/keys` (with the correct permissions) but `hab` was only looking in `$HOME/.hab/cache/keys`.

**Comment by metadave** [comment]
my bad, fixed

**Comment by metadave** [comment]
Note: I'm able to upload as root with keys in `/hab/cache/keys`

**Comment by bdangit** [comment]
> @metadave: Note: I'm able to upload as root with keys in `/hab/cache/keys`

My keys are setup under `/hab/cache/keys` just like @schisamo however, I needed to recreate the keys under `$HOME/.hab/keys` in order for the upload to work.

My setup:  I am running on Mac with Docker.

```
[25][default:/src:0]# hab --version
hab 0.9.3/20160916191534

[26][default:/src:0]# whoami
root
```

**Comment by juliandunn** [comment]
We will soon be changing some behavior in an upcoming release that will make this easier. It is in part to address #903 -- or at least the parts of it that we can address. The new behavior will be that on Linux, `sudo` will not be necessary for commands other than `hab studio enter` or `hab pkg build`, because those require setting up a `chroot` as `root`.

This will resolve these permissions problems where keys end up located in either `/hab/cache/keys` or `$HOME/.hab/cache/keys` and cause confusion.

**Comment by juliandunn** [comment]
I'm going to close this issue. As of Habitat 0.10.x, `hab pkg upload` should be run as your own user, with your own user keys inside `$HOME/.hab/cache/keys`, and this should solve the problem.
