### ISSUE TITLE
Location for config templates

### ISSUE THREAD

**Issue by spa-87** [habitat-sh/habitat#1173]
Hi, I've noticed there's no way to change location of directory with config templates. It's a significant limitation as there're apps which use the same folder and storing there config templates adds a mess. Actually I just have such use-case. 

The other problems with config files in a single folder - not all apps allows to define config locations so I have to copy/symlink configs to the expected places after variables substitution is done. 

For addressing that habitat should provide a way to define array of direct locations for config templates. I believe it should understood wildcards as well, what would let to use both direct paths to files and folders with configs.

**Comment by reset** [comment]
@spa-87 I just need a little bit more information to be able to triage this properly. Are you speaking about the config template directory that is located next to your `plan.sh` file?

**Comment by spa-87** [comment]
@reset right, I'm talking about mustache templates which are located in `config` directory next to `plan.sh` and rendered by habitat.

**Comment by adamhjk** [comment]
@spa-87 I think the right thing here is to move the directory your plan.sh and config folders live in to a sub-directory, such as "habitat". Does that solve the issue for you, at least at build time?

**Comment by smurawski** [comment]
Storing the config (and plan.sh) in `./habitat` should solve the build time conflict of where to put the templated files.  For the runtime deployment to other locations of the evaluated config files, most people are using the `init` and `reconfigure` hooks to do that.
