### ISSUE TITLE
Support different toml files with default configs

### ISSUE THREAD

**Issue by spa-87** [habitat-sh/habitat#1174]
Currently habitat reads default configs from default.toml which is located in the package root. I believe it make sense to extend that behavior via providing an environment variable where can be set which file with default configs should be used.

Then we can have a bunch of toml files in the package and define at launch time which one should be used.

Our use case: we have kubernetes infrastructure and want to use habitata for building docker containers.

Described above feature will let to both developers and operations to manage values for habitat variables based on application environment:
Developers create per-environment toml-files where they set values which can be different for different environments.
Operations define which config should be used based on environment where service is running, and override infrastructure-specific parameters.

**Comment by smurawski** [comment]
Thanks for the request @spa-87.  We currently support the overriding of default.toml with a user.toml that could contain the runtime settings for your deployment.  You can either provision that file to the /hab/svc/{your package name}/user.toml or inject it via the `hab config apply` command.

You can find some other resources around configuration application 

* https://www.habitat.sh/docs/reference/habitat-cli/#hab-config-apply
* https://www.habitat.sh/tutorials/getting-started/mac/configure-plan/
