### ISSUE TITLE
Provide a `fix_interpreter_unsafe` function

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#1182]
In some plan's I would like to fix the interpreter on scripts only required during the `do_build()` or `do_check()` phases.  In this case, it would be nice to include `core/coreutils` (or whatever other package contains the interpreter I need) only at build time.  However, the default `fix_interpreter` script will fail with:

```
   mercurial: WARN Could not resolve the path for core/coreutils, is it specified in 'pkg_deps'?
   mercurial: WARN fix_interpreter() 'core/coreutils' is not a runtime dependency
   mercurial: WARN Only runtime packages may be used as your interpreter must travel
   mercurial: WARN with the 'mercurial' in order to run.
```

It would be nice if the same functionality was available via `fix_interpreter_unsafe` that skips this check.

**Comment by miketheman** [comment]
Feels like a dupe of #1041.

**Comment by stevendanna** [comment]
Yup, shoulda searched!
