### ISSUE TITLE
Add dedicated content about GitHub scopes needed in CLI setup

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#1194]
Per #1189, we should have a dedicated section or topic that describes what GitHub scopes or other authentication mechanisms we require as part of both setup and/or general workflow when using the `hab` CLI to upload and download keys, packages, etc.

**Comment by smurawski** [comment]
@davidwrede just a quick ping to bring this back to your attention.

**Comment by davidwrede** [comment]
Thanks @smurawski for the ping. I'm pivoting over to Habitat work this week and next. I'll add this to my queue.
