### ISSUE TITLE
More information when reporting file/io related errors

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#1229]
In the habichat many users end up reporting errors where the only output from `hab` is

```
✗✗✗
✗✗✗ No such file or directory (os error 2)
✗✗✗
```

Often you can find the source of the problem either (1) by turning on debug logging or (2) knowing what files each command tries to access; however, it would speed up problem solving if the original error message had the path of the file that `hab` failed to read.

**Comment by fnichol** [comment]
Agreed, we have several spots where we convert-and-return raw IO errors straight up to the end user which certainly could be improved.

**Comment by smurawski** [comment]
This is definitely something we want to do, however without a specific example this is not really actionable.  We'll keep working to make specific error conditions better as we go.  Thanks!
