### ISSUE TITLE
want `hab pkg build` to do multithreaded `xz` compression when more than one core available

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#1253]
My Rust is, well, 'rusty', but I'd be willing to take a stab at this if someone can point me at the code...

**Comment by bixu** [comment]
Looking through the code, it seems we are using `--threads=0`, and `man xz` says:
```
       -T threads, --threads=threads
              Specify the number of worker threads to use.  Setting threads to
              a special value 0 makes xz use as many threads as there are  CPU
              cores  on  the system.  The actual number of threads can be less
              than threads if the input file is not big enough  for  threading
              with  the  given  settings or if using more threads would exceed
              the memory usage limit.
```
so unless I'm reading this wrong, we are already fully optimized here. Closing request.

**Comment by fnichol** [comment]
@bixu The underlying program which execute the build (i.e. turns the `plan.sh` into a `.hart`) is actually a Bash program called [`hab-plan-build.sh`](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh) in the source tree. It's the program that becomes `build` inside a Studio. The xz compression options and strategy happens in the  [`_generate_artifact()`](https://github.com/habitat-sh/habitat/blob/7f108f5530f12ecadaba31882b99fb5bd4562983/components/plan-build/bin/hab-plan-build.sh#L2185) internal function which currently uses `--compress -6 --threads=0 --verbose` as its flags.

I switched us from gzip compression to xz compression before our launch but was trying to find a balance between a small end product, a reasonable time to compress, and a not unreasonable burden on the CPU (both build side and on the end user side when extracting). We might still be able to play with this a bit if you're finding issues (time waiting, cpu pegging, etc).

If memory serves, the `xz` command honors a `XZ_OPT` environment variable for tweaking further options which I believe would be honored in the `build` program after entering a Studio. Who knows, it may be worth a play!

Hope this helps a little with background and pointer to the location in code!

**Comment by bixu** [comment]
Yup, that's the code I was looking at. I had another look at a build with `top` during the compression step, and it looks like `xz` is using `--threads 0 --compression 6`, which seem sane to me.

*However*, also noticed that only one core on my 2-core Docker host (macOS native) was pegged. Since I also got errors from Python/scipy earlier that multiprocessing was disabled (Docker security setting in the Studio container?), there may be an explanation outside of Hab...

Thanks for the note on env vars - will have a stab at that when I get a chance.

**Comment by fnichol** [comment]
It may depend how many CPUs are assigned to the underlying Docker VM. I noticed that after updating a couple of days ago, my settings were reset to 1CPU and 2GB RAM. Given how much Habitat work I'm doing these days (and that I shut the VM down when not using), I usually give the VM all my CPUs (2 core with hyperthreads = 4 I guess?) and 8GB RAM.

![general 2016-09-18 09-36-48](https://cloud.githubusercontent.com/assets/261548/18616977/7ebb41b4-7d83-11e6-945b-70e8f22f5ecc.png)

**Comment by smartb-pair** [comment]
@fnichol, I'd like to re-open this as I've just confirmed that (at least in the native macOS Docker), multithreaded compression is broken. I feel like this might be related to multiprocessing limits in Docker. See screenshots attached.
![screen shot 2016-09-28 at 6 43 22 pm](https://cloud.githubusercontent.com/assets/16775146/18923654/64b3269c-85ad-11e6-85bb-fa93acdb1f7b.png)
![screen shot 2016-09-28 at 6 54 46 pm](https://cloud.githubusercontent.com/assets/16775146/18923727/c1138594-85ad-11e6-9252-886a1e578aaf.png)

**Comment by smartb-pair** [comment]
The package itself is a Python app running under uWSGI. This message seems to support my theory that somehow multiprocessing is disabled somehow in the studio:
```
api(O): /hab/pkgs/<origin>/<package>/0.1.0/20160928171003/lib/python2.7/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:29: UserWarning: [Errno 13] Permission denied.  joblib will operate in serial mode
```

**Comment by smartb-pair** [comment]
Related I think:
```
[5][default:/src:2]# hab pkg exec core/python2 python
Python 2.7.12 (default, Sep 26 2016, 15:43:20)
[GCC 5.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> int(os.environ.get('JOBLIB_MULTIPROCESSING', 1))
1
```

**Comment by fnichol** [comment]
@smartb-pair Nice debugging, thank you!

I'm wondering if we have a problem with the proc fs mounting which is how I expect some of these programs to determine number of processes.

**Comment by bixu** [comment]
That was me - happy to help!

I agree that proc seems a likely culprit. Maybe we can calculate ourselves and then pass the right concurrency flag to xz?

**Comment by bixu** [comment]
Just conformed that even after manually specifying >1 threads (in `hab-plan-build.sh`) we still only see single-threaded behavior. So I'm guessing this is a limitation of the studio Docker environment rather than `xz` or the plan builder?

```
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
 8198  4506 root     S     719m 18.1   1 97.2 /hab/pkgs/core/xz/5.2.2/20160612080402/bin/xz --compress -6 --threads=3 --verbose /hab/cache/artifacts/...
 4506     1 root     S    25180  0.6   2  0.0 {hab-plan-build} /hab/pkgs/core/bash/4.3.42/20160612075613/bin/bash /hab/pkgs/core/hab-plan-build/0.7.0/201606
    1     0 root     S    24784  0.6   1  0.0 /hab/pkgs/core/bash/4.3.42/20160612075613/bin/bash --login +h
```

**Comment by Hoverbear** [comment]
@bixu check the docker for mac/windows config, there should be an option for `NUM_CPUS`

![screen shot 2016-11-04 at 10 26 51](https://cloud.githubusercontent.com/assets/130903/20000720/3a5dbd9c-a279-11e6-86c5-7bfbc2143d8e.png)

**Comment by bixu** [comment]
I've been setting my CPU count in Docker.app to 3 in most cases, including the test I posted `top` output from.

**Comment by adamhjk** [comment]
I think it's because docker for mac uses a user-land file sync that's pretty darn awful.

**Comment by smartb-pair** [comment]
Yes the file sync is...suboptimal...on macOS Docker. I don't follow how this affects `xz` threading tho...am I missing something?

**Comment by bixu** [comment]
Just did a test at home with the Alpine Docker image and `xz` compressing a large file. I can definitely get multiple cores going with the same macOS Docker setup being used with the Studio - so I feel like there is something about multiprocessing tuning in the Studio? But my Docker fu is weak...any ideas?[
![screen shot 2016-11-05 at 7 16 20 pm](https://cloud.githubusercontent.com/assets/339799/20032559/c1fe8eb6-a38c-11e6-90ae-4e0f780233f8.png)
](url)

**Comment by bixu** [comment]
Happy to sound the false alarm here. My assumption that `xz` was not multithreaded was based on looking at `top` output, and the Busybox `top` we use doesn't display threads 😣 - however, `watch`-ing the appropriate `ps` command in the Studio container shows that we *are* going multithreaded:
```
Every 1s: ps -eT                                                                                    2016-11-06 09:06:18

PID   USER     TIME   COMMAND
    1 root       0:00 /hab/pkgs/core/bash/4.3.42/20160729192720/bin/bash --login +h
 3140 root       0:00 sh
 3163 root       0:05 xz --compress --threads=2 bigfile
 3164 root       4:42 xz --compress --threads=2 bigfile
 3167 root       4:40 xz --compress --threads=2 bigfile
```

So I'll close this issue, and agree with @adamhjk that the macOS Docker implementation is just so slow that I assumed a deeper issue. Maybe, though, it would be useful to include a `top` or similar (`htop`?) in the Studio that shows threads by default, to help users understand build performance better?
