### ISSUE TITLE
Generated svc `run` script assumes binaries are on path

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#1268]
https://github.com/habitat-sh/habitat/pull/1240/files#diff-cd7d95517e09fa7942c3596f1507226dL2035

The run script generated and placed to `/hab/svc/${service}/run` does not append the bin directories to the path as assumed by the changes in #1240.

Here is a sample run script from the builder-api currently on live:

```
#!/bin/sh
cd /hab/svc/hab-builder-api

if [ "$(whoami)" = "root" ]; then
  exec chpst \
    -U hab:hab \
    -u hab:hab \
    bldr-api start -c /hab/svc/hab-builder-api/config.toml 2>&1
else
  exec bldr-api start -c /hab/svc/hab-builder-api/config.toml 2>&1
fi
```

This may easily be fixed by adding the bin directories exposed by the plan metadata to the path before starting the service in the script

**Comment by raskchanky** [comment]
After some discussion, we've decided that this is actually working.  The buggy behavior we saw previously was likely unrelated, and if we see it again, the changes from #1240 are probably not the issue.
