### ISSUE TITLE
[documentation] Testing locally compiled dependencies without `hab pkg upload`-ing

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1273]
Reference: https://habitat-sh.slack.com/archives/general/p1474500129003190

As a habitat user, having documentation that exposes the strategy for testing multiple dependent packages locally could be very useful. Likely it would cut down on the number of new hab users uploading  broken packages to the depot instead of testing their chained dependencies locally first.

A section could fairly easily be added here:
https://github.com/habitat-sh/habitat/blob/9a8f985ace20ca3b2b8fc3485673cfbd0cda9f25/www/source/docs/create-packages-build.html.md

If we already have documentation on testing layered deps.  before upload feel free to close.

**Comment by marklap** [comment]
This is helpful in isolated environments also where a Habitat user may not have direct outbound access to a community Depot nor the ability to create a local "personal" Habitat depot.

**Comment by eeyun** [comment]
So I think we've pretty much discussed our way through this in habichat here: https://habitat-sh.slack.com/archives/general/p1474565463003408

Its probably not "necessary" to specify a specific organization for where to enter the studio and build from. I'm going to close this issue for now. If this continues to be an ongoing issue for people I'll reopen it.
