### ISSUE TITLE
hab pkg build returns code 0 on error

### ISSUE THREAD

**Issue by dmajere** [habitat-sh/habitat#1285]
OS = Linux
hab = 0.9.3/20160916191534

hab pkg build . 
Output
```
....
cp: omitting directory '/src/habitat/../source/app.tar.gz'
   app: Build time: 0m14s
   app: Exiting on error
Script done, file is /src/results/logs/..2016-09-27-135632.log
# echo $?
0
```

**Comment by metadave** [comment]
confirmed on my end too, thanks for reporting!

**Comment by metadave** [comment]
It appears as though we ignore the return value here: https://github.com/habitat-sh/habitat/blob/master/components/hab/src/exec.rs#L62

**Comment by rrxtns** [comment]
So easy I just out and out replaced the execv! see merge: https://github.com/habitat-sh/habitat/pull/1324

@metadave @dmajere - good to close?

**Comment by smurawski** [comment]
Closed by #1324

**Comment by rrxtns** [comment]
Cool @fnichol - I didn't know enough about the inner workings to know that Studio was the better place to fix this issue. That being said, I do think it make sense to leverage std::process::Command vs. execv wherever possible, you can "shell out" inline.

Mind tagging me in your PR so I can get a sense of what your solution is?

**Comment by fnichol** [comment]
@rrxtns Absolutely will do. In support of what I'm currently working on, I want the specific behavior of `exec` vs `fork/exec` (or `spawn`) so hopefully this will make more sense shortly.

**Comment by fnichol** [comment]
@rrxtns As promised, you can check out #1329 with most of the relevant parts in the [first commit](https://github.com/habitat-sh/habitat/pull/1329/commits/407aee63fdc6ffc2e9ed71228e7f1a22adfaace8) (link good unless and until we rebase). Hope this helps!

**Comment by fnichol** [comment]
Got this, and y'all are going to love it 😉

**Comment by fnichol** [comment]
Given the solution was so small (add `-e` to the `script` call in our `record()` function), this could have taken **forever** to find! Thanks all for your help on this one!
