### ISSUE TITLE
`hab` user is required

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#1312]
This [release announcement](https://forums.habitat.sh/t/habitat-0-9-0-released/162) states:

> If `pkg_svc_user` and `pkg_svc_group` are specified in the plan, these will be honored by the supervisor when starting the package. You can either start the supervisor as the `pkg_svc_user` ID, or as root. In the latter case, the supervisor will run as root but start the process as `pkg_svc_user`.
> 
> If `pkg_svc_user` or `pkg_svc_group` are not specified in the plan, the supervisor will try to start the process using the hab user and group, but if those do not exist, it will start the process as the current user/group.

A package created without specifying `pkg_svc_user` or `pkg_svc_group` on a system without a `hab` user fails to start with the following error message:

`hab-sup(UR)[src/util/users.rs:44:27]: Package requires user hab to exist, but it doesn't`

I expected the service to start as the current user/group (`uid=1001(chef) gid=1001(chef) groups=1001(chef)`)
- OS:  Ubuntu 14.04
- Current Habitat environment variables:  NONE
- Habitat environment inside the studio:  `HAB_ORIGIN=nathentest1`
- Backtrace

``````
chef@ip-172-31-27-210:~/habitat-example-plans/mytutorialapp_finished$ RUST_LOG=debug RUST_BACKTRACE=1 sudo -E hab start results/nathentest1-mytutorialapp-0.
2.0-20160930202415-x86_64-linux.hart
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab::exec: Calling execv: ("/hab/pkgs/core/hab-sup/0.10.1/20160929220948/bin/hab-sup") ["start", "results/nathentest1-mytutorialapp-0.2.0-20160930202415-x86_64-linux.hart"]
DEBUG:hab_sup: clap matches ArgMatches { args: {}, subcommand: Some(SubCommand { name: "start", matches: ArgMatches { args: {"pkg_ident_or_artifact": MatchedArg { occurs: 1, vals: {1: "results/nathentest1-mytutorialapp-0.2.0-20160930202415-x86_64-linux.hart"} }}, subcommand: None, usage: Some("USAGE:\n    hab-sup start [FLAGS] [OPTIONS] <pkg_ident_or_artifact>") } }), usage: Some("USAGE:\n    hab-sup [FLAGS] [SUBCOMMAND]") }
DEBUG:hab_sup: subcommand name "start"
DEBUG:hab_sup: Subcommand matches ArgMatches { args: {"pkg_ident_or_artifact": MatchedArg { occurs: 1, vals: {1: "results/nathentest1-mytutorialapp-0.2.0-20160930202415-x86_64-linux.hart"} }}, subcommand: None, usage: Some("USAGE:\n    hab-sup start [FLAGS] [OPTIONS] <pkg_ident_or_artifact>") }
DEBUG:habitat_core::package::archive: content = core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = # nathentest1 / mytutorialapp


* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>
* __Version__: 0.2.0
* __Release__: 20160930202415
* __Architecture__: x86_64
* __System__: linux
* __Target__: x86_64-linux
* __Upstream URL__: upstream project's website or home page is not defined
* __License__:
* __Source__: [foo](foo)
* __SHA__: SHA256 checksum not provided or required
* __Path__: `/hab/pkgs/nathentest1/mytutorialapp/0.2.0/20160930202415`
* __Build Dependencies__: no build dependencies or undefined
* __Dependencies__: `core/node `
* __Interpreters__: no interpreters or undefined

# Plan

## Build Flags

```bash
CFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CPPFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
CXXFLAGS: -I/hab/pkgs/core/node/4.2.6/20160926154453/include
LDFLAGS: -L/hab/pkgs/core/node/4.2.6/20160926154453/lib
LD_RUN_PATH: /hab/pkgs/core/node/4.2.6/20160926154453/lib
``````
## Plan Source

``` bash
pkg_origin=nathentest1
pkg_name=mytutorialapp
pkg_version=0.2.0
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_license=()
pkg_deps=(core/node)
pkg_expose=(8080)
pkg_source=foo

do_download() {
  return 0
}

do_verify() {
  return 0
}

do_unpack() {
  return 0
}

do_build() {
  # The mytutorialapp source code is in a relative directory, so you must copy the
  # contents of the source directory into your $HAB_CACHE_SRC_PATH/$pkg_dirname as this
  # is the same path that Habitat would use if you downloaded a tarball of the source code.
  cp -vr $PLAN_CONTEXT/../source/* $HAB_CACHE_SRC_PATH/$pkg_dirname

  # This installs both npm as well as the nconf module we listed as a
  # dependency in package.json.
  npm install
}

do_install() {
  # Our source files were copied over to HAB_CACHE_SRC_PATH/$pkg_dirname in do_build(),
  # and now they need to be copied from that directory into the root directory of our package
  # through the use of the pkg_prefix variable.
  cp package.json ${pkg_prefix}
  cp server.js ${pkg_prefix}

  # Copy over the nconf module to the package that we installed in do_build().
  mkdir -p ${pkg_prefix}/node_modules/
  cp -vr node_modules/* ${pkg_prefix}/node_modules/
}
```

DEBUG:habitat_core::package::archive: content = # Default values that can be updated.
# Message of the Day

message = "Hello, World!"
# The port number that is listening for requests.

port = 8080

```
DEBUG:habitat_core::package::archive: content = nathentest1/mytutorialapp/0.2.0/20160930202415

DEBUG:habitat_core::package::archive: content = core/gcc-libs/5.2.0/20160612075020
core/glibc/2.22/20160612063629
core/linux-headers/4.3/20160612063537
core/node/4.2.6/20160926154453

DEBUG:habitat_core::package::archive: content = 8080

DEBUG:hab_sup: Gossip IP = 172.31.27.210
DEBUG:hab_sup: Gossip port = 9634
DEBUG:hab_sup: HTTP IP = 0.0.0.0
DEBUG:hab_sup: HTTP port = 9631
DEBUG:hab_sup: Config:
Config { command: Start, package: PackageIdent { origin: "nathentest1", name: "mytutorialapp", version: Some("0.2.0"), release: Some("20160930202415") }, local_artifact: Some("results/nathentest1-mytutorialapp-0.2.0-20160930202415-x86_64-linux.hart"), url: "https://willem.habitat.sh/v1/depot", topology: Standalone, group: "default", path: "/hab/svc/hab-sup/data", archive: "", bind: [], key: "", email: None, expire_days: None, gossip_listen_ip: "172.31.27.210", gossip_listen_port: 9634, http_listen_ip: "0.0.0.0", http_listen_port: 9631, userkey: None, servicekey: None, infile: None, outfile: None, gossip_peer: [], gossip_permanent: false, update_strategy: None, service_group: "", file_path: "", version_number: 0, organization: None, ring: None, config_from: None }
hab-sup(MN): Starting nathentest1/mytutorialapp/0.2.0/20160930202415
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_sup::command::start: Setting the PATH to :/hab/pkgs/core/node/4.2.6/20160926154453/bin:/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/busybox-static/1.24.2/20160926152859/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG:habitat_sup::util::users: SVC_USER = hab
DEBUG:habitat_sup::util::users: SVC_GROUP = hab
hab-sup(UR)[src/util/users.rs:44:27]: Package requires user hab to exist, but it doesn't
```

**Comment by metadave** [comment]
The docs should be clarified with the following:

> If pkg_svc_user and pkg_svc_group are not specified in the plan, they are both defaulted to `hab` during plan build. 

via https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L360-L362

>The supervisor will try to start the process using the specified user and group from a package, but if those do not exist, it will start the process as the current user/group. 

This doesn't seem to work. I changed the redis plan to use `foo:foo`, which don't exist, and received the following message as well:

```
hab-sup(MN): Starting metadave/redis
hab-sup(UR)[src/util/users.rs:44:27]: Package requires user foo to exist, but it doesn't
```

Original user/group work here:
https://github.com/habitat-sh/habitat/pull/1050

**Comment by nathenharvey** [comment]
Current behavior:

`pkg_svc_user` and `pkg_svc_group` not defined in plan, `hab` user and group exist:  start the service as the `hab` user.

`pkg_svc_user` and `pkg_svc_group` not defined in plan, `hab` user and group do not exist:  service fails to start.

`pkg_svc_user` and `pkg_svc_group` defined in plan and that user and group exist on the system:  service starts as the defined `pkg_svc_user` and `pkg_svc_group`.

`pkg_svc_user` and `pkg_svc_group` defined in plan but that user and group do not exist on the system:  service fails to start.


I'm not sure if this is the intended behavior but it is definitely [not in-line with note posted in the release announcement for version 0.9.0](https://forums.habitat.sh/t/habitat-0-9-0-released/162).


I believe next steps are

* update the release announcement with a clarification:  easy

**Comment by juliandunn** [comment]
@nathenharvey let's update the release announcement to start. I think we need to discuss further whether we want to fail starting a package in [situation 2 you describe](https://github.com/habitat-sh/habitat/issues/1312#issuecomment-251387063) or just fall back to starting as the current user/group. The other three scenarios seem like correct behavior, including situation 4 (you defined a `pkg_svc_user` and `pkg_svc_group` but those don't exist, therefore it blows up)

**Comment by reset** [comment]
@juliandunn what about taking the "do what I mean" approach and creating the user and group if they don't exist?

**Comment by juliandunn** [comment]
@reset in many cases I would say DWIM is fine but not in the case of users and groups, because in larger orgs those come from a directory (LDAP, AD, etc.) and we don't want to be randomly creating local users if that directory connection happens to have a blip. You'd also start getting into having to define the UID and GECOS fields of that user somewhere in Habitat, and the groups it should be in... something I don't think I want to bite off right now 😁

**Comment by reset** [comment]
@juliandunn this is a service user, though, which should be a user that can't even start an interactive session. I wouldn't manage these users by LDAP/AD, do people actually do that?

**Comment by juliandunn** [comment]
@reset yeah they do... unfortunately (and yes, even though it's an awful idea)

**Comment by eeyun** [comment]
@nathenharvey It appears that part of this issue might be resolved here: https://github.com/habitat-sh/habitat/blob/412082c6006c8346079a5180d02c3cc71fb60bd6/components/sup/src/util/users.rs#L88

It appears that we fall back to current user and group and cross our fingers that we have the appropriate permissions with that account. We will try to verify that is in fact the case. If you have know that this issue has been resolved for yourself feel free to update this issue. For now I'm going to close the issue and test this functionality in the immediate future. If the bug persists we can obviously reopen the issue.

Thanks for submitting it!
