### ISSUE TITLE
[hab-backline] Add minimal terminfo package for full `hab` coloring

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#1314]
Due to the terminfo capability logic now in the `hab` package, we should add a minimal terminfo package as a dependency of `core/hab-backline`. This will allow all `hab` calls to be colored inside an interactive Studio.

**Comment by jaredmichaelsmith** [comment]
Hi @fnichol, I would like to work on this. Can you give any more guidance on where to start? I have been following this project, but I haven't yet contributed anything to it.

**Comment by reset** [comment]
Closed by #1318
