### ISSUE TITLE
Results dir should be owned by regular user instead of root

### ISSUE THREAD

**Issue by dos1** [habitat-sh/habitat#1339]
Currently when packages are built, the _results_ directory and all its files are owned by root, as the building process requires root permissions granted, for instance via _sudo_.

**Feature request:** would be great if the resulted files were owned by regular user that called the build system via sudo instead of root.

**Why:** I just had to hack my CI system to _chown_ all files after build because it couldn't clean up the environment directory after building with habitat, and that made me sad :(

**Comment by smith** [comment]
Fixed in #2413.
