### ISSUE TITLE
hab 0.10.2 doesn't copy keys inside the studio

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#1341]
- [x] The OS (including version) where you are running any of the Habitat commands.
 - Ubuntu 16.04 LTS, Linux 4.4.0-38-generic, x86_64
 - hab 0.10.2/20160930230245
- [x] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:
 - https://gist.github.com/lilianmoraru/e242716d0e633fb9f6012caf329c4a72
 - After it loaded(you can scroll to the end for this) I did `ls /hab/cache/` so you can see that there is no `keys` folder inside it.
 After that I exited and entered the studio again(less output there) and listed `/hab/cache` again.

- [x] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:
 - Does not print anyhing(no variables except for AUTH).

- [x] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.
 - ls -la /hab/cache/keys
 ```
ls -la /hab/cache/keys
total 32
drwxr-xr-x 2 root root 4096 oct  8 09:41 .
drwxr-xr-x 6 root root 4096 iul 23 10:34 ..
-rw-r--r-- 1 root root   75 iul 17 15:20 core-20160612031944.pub
-rw-r--r-- 1 root root   75 sep 15 00:54 core-20160810182414.pub
-r-------- 1 root root   77 iul 23 10:30 lilian-20160723073001.pub
-r-------- 1 root root  121 iul 23 10:30 lilian-20160723073001.sig.key
-r-------- 1 root root   77 oct  8 09:41 lilian-20161008064147.pub
-r-------- 1 root root  121 oct  8 09:41 lilian-20161008064147.sig.key
 ```
 - ls -la $HOME/.hab/**cache.keys**
 ```
ls -la $HOME/.hab/cache/keys
total 16
drwxr-xr-x 2 root root 4096 oct  8 09:10 .
drwxr-xr-x 3 root root 4096 oct  8 09:09 ..
-rw-r--r-- 1 root root   75 oct  8 09:09 core-20160612031944.pub
-rw-r--r-- 1 root root   75 oct  8 09:10 core-20160810182414.pub
```

I generate the keys with `sudo` and start the studio with `sudo`. I have always used it that way, it doesn't work just now.

**Comment by smurawski** [comment]
@lilianmoraru in the gist it did not appear to have the studio launched with sudo, which would explain the missing keys. (Unless I'm misreading the gist.)

**Comment by lilianmoraru** [comment]
@smurawski I did `alias hab="sudo RUST_LOG=debug hab"` before running(I've done this specifically to get the log).
But normally I have in `.bashrc` this: `alias hab="sudo hab"` since most of the commands needed it before.

**Comment by smurawski** [comment]
Thanks @lilianmoraru

**Comment by juliandunn** [comment]
Just to confirm:

* when you ran `hab setup` you specified `lilian` as your default origin?
* do you have the `lilian` keys under `$HOME/.hab/cache/keys`?

**Comment by lilianmoraru** [comment]
@juliandunn 
 * Yes, `lilian` is the default origin.
 * No, I do not have `lilian` keys under `$HOME/.hab/cache/keys`.

2 Notes here:
 * It was working on `0.9`(I'll go home and retest this claim).
 * Running `hab setup` again, puts the keys in `/hab/cache/keys/`.

**Comment by juliandunn** [comment]
> Running hab setup again, puts the keys in /hab/cache/keys/.

As of 0.10.x you don't need to run `hab setup` anymore as `root`; are you doing that?

**Comment by lilianmoraru** [comment]
I have `hab` set as an alias to `sudo hab`.
So, `hab setup` -> `sudo hab setup`
`hab studio enter` -> `sudo hab studio enter`.

**Comment by juliandunn** [comment]
Yeah. You don't need to do that anymore. The workflow with the current version of Habitat will be:

* `hab setup` as normal user
* `sudo hab studio enter` to get into studio

In the next version of Habitat (0.11.x?) the need for typing `sudo` for the latter will be eliminated, i.e. it will prompt you for the `sudo` password, but you will no longer need to `sudo` yourself.

**Comment by lilianmoraru** [comment]
@juliandunn But I do have 2 `core` keys in `$HOME/.hab/cache/keys` and it doesn't download those.
Or it downloads only the keys for the default `origin`?

**Comment by juliandunn** [comment]
@lilianmoraru that's right - when you enter a studio, if you have a default origin set, it will copy the keys for that origin (if they exist) into the studio so you can build things.

**Comment by lilianmoraru** [comment]
I tried not to run `hab setup` without sudo an I get:
```

  Enter the name of your origin. If you plan to publish your packages 
  publicly, we recommend that you select one that is not already in use on 
  the Habitat build service found at https://app.habitat.sh/. 

DEBUG:hab::config: No CLI config found, loading defaults
Default origin name: [default: lilian] 
DEBUG:hab::config: No CLI config found, loading defaults
✗✗✗
✗✗✗ Permission denied (os error 13)
✗✗✗
```

**Comment by juliandunn** [comment]
Who owns the `$HOME/.hab` directory and all the files underneath it?

**Comment by lilianmoraru** [comment]
Yep, `.hab` and everything under `.hab` is owned by `root`.
I'll remove the folder and try again.

**Comment by lilianmoraru** [comment]
`hab setup` worked but there are still issues with the keys.
Running `hab setup` after removing the `$HOME/.hab` folder, prompted me again to insert the Github token(usually it's already inserted, you just have to hit enter).

Running `sudo hab studio enter` now displays a message which says that the key is imported:
```
sudo hab studio enter
   hab-studio: Creating Studio at /hab/studios/home--lilian--Git--core-plans (default)
   hab-studio: Importing lilian secret origin key
» Importing origin key from standard input
★ Imported secret origin key lilian-20161012213140.
   hab-studio: Entering Studio at /hab/studios/home--lilian--Git--core-plans (default)
   hab-studio: Exported: HAB_ORIGIN=lilian
```

But the `/hab/cache/keys` folder is still missing.
I decided to try anyway if I can build a package and I get this:
```
# build
   : Loading /src/gdb/plan.sh
   gdb: Plan loaded
   gdb: hab-plan-build setup
find: `/hab/cache/keys': No such file or directory
ERROR: Signing origin key 'lilian' not found in /hab/cache/keys, aborting
```

**Comment by travisfinch** [comment]
I think I may be hitting this issue too, or something like it.

I am running this inside a docker container. Here is the Docker file: https://github.com/travisfinch/docker-node-sample/blob/master/jenkins-dind-habitat-slave/Dockerfile

```
$ hab --version
hab 0.10.2/20160930230245
```

```
$ sudo hab origin key generate travisfinch
» Generating origin key for travisfinch
★ Generated origin key pair travisfinch-20161012203942.
```

Note: I have also tried this without sudo, and it does not really make a difference other than the keys end up in /home/jenkins/.hab/cache/keys instead of of /hab/cache/keys.

```
$ ls -l /hab/cache/keys
total 12
-r-------- 1 root root  82 Oct 12 20:39 travisfinch-20161012203942.pub
-r-------- 1 root root 126 Oct 12 20:39 travisfinch-20161012203942.sig.key
```

```
$ sudo hab pkg build .
<output truncated>
ERROR: Signing origin key 'travisfinch' not found in /hab/cache/keys, aborting
```

**Comment by juliandunn** [comment]
Yeah. It should be owned by your user, not root. That's the issue... could have been an issue with migrating it from the previous version.

**Comment by travisfinch** [comment]
Here's an example of not using sudo to generate the keys:

```
$ hab origin key generate travisfinch
» Generating origin key for travisfinch
★ Generated origin key pair travisfinch-20161012232214.
```

```
$ ls -l /home/jenkins/.hab/cache/keys
total 8
-r-------- 1 jenkins jenkins  82 Oct 12 23:22 travisfinch-20161012232214.pub
-r-------- 1 jenkins jenkins 126 Oct 12 23:22 travisfinch-20161012232214.sig.key
```

```
$ sudo hab pkg build .
<output truncated>
ERROR: Signing origin key 'travisfinch' not found in /hab/cache/keys, aborting
```

**Comment by travisfinch** [comment]
If I run:

```
$ sudo hab studio enter
$ hab origin key generate travisfinch
$ build .
```

the build is successful. I need to do a non-interactive build as this is for CI though.

**Comment by juliandunn** [comment]
@travisfinch it doesn't work if you have the `travisfinch` key outside the studio?

I wasn't able to repro this on a fresh Linux VM using 0.10.2. I did the following:

* download `hab` onto that VM
* `hab setup` and set an origin as `julian` and generate an origin key for `julian`
* `sudo hab studio enter`
* `build jq-static`

I got a `.hart` in `results` that was in the `julian` origin.

**Comment by travisfinch** [comment]
@juliandunn Correct.

I am using Ubuntu 14.04 LTS. Here are the different behaviors I have tested and observed:

1.) If I generate the key (either as jenkins or root), then run "sudo hab pkg build" with or without the -k option, the build fails with no key found
2.) If I generate the key (either as jenkins or root), then run "sudo hab studio enter" and "build .", the build fails with no key found
3.) If I run "sudo hab studio enter", generate the keys inside, then run "build .", the build succeeds
4.) If I generate the key, then run "sudo hab studio -k travisfinch enter" and "build .", the build succeeds

I am fine explicitly defining the keys I want to pull into the studio environment, but to me, if "hab studio -k travisfinch" can find the key, but "hab pkg build . -k travisfinch" can not, this is a bug.

**Comment by juliandunn** [comment]
When you say, in cases #1 and #2, "the build fails", do you mean you are getting an error

```
✗✗✗
✗✗✗ Crypto error: Error reading key directory /hab/cache/keys: No such file or directory (os error 2)
✗✗✗
```

?

**Comment by travisfinch** [comment]
@juliandunn No. The error I see is:

`ERROR: Signing origin key 'travisfinch' not found in /hab/cache/keys, aborting`

**Comment by juliandunn** [comment]
@travisfinch if you have time next week, I'd love to Zoom with you to understand better what is happening. E-mail me offline? jdunn@chef.io

**Comment by juliandunn** [comment]
For folks that are watching; @travisfinch, @eeyun and I zoom'd and we found there's a bug with `hab pkg build` and `-k` in that `-k` doesn't pass the correct origin key. Furthermore, if you have an origin key `foo` set in `$HOME/.hab/etc/cli.toml` and you try to pass `-k bar`, `bar` does not override `foo`. We will open a separate bug on this.

**Comment by eeyun** [comment]
I have been able to repro this issue.

Details of the test system are 
- Ubuntu 16.04
- Habitat 0.11.0

To repro the user must *not* run `hab setup` command before generating origin keys.

Process essentially looked like this:
- Built fresh Ubuntu node in kvm
- Installed Habitat-latest-x86_64 `sudo ./install.sh`
- Generated origin key `hab origin key generate mjolnir`
- Created new plan with `pkg_origin=mjolnir`
- Ran non-interactive build `hab pkg build test`

Which generated the following error:
```
Script started, file is /src/results/logs/test/.2016-10-21-142912.log
   : Loading /src/test/plan.sh
   bc: Plan loaded
   bc: Validating plan metadata
   bc: hab-plan-build setup
ERROR: Signing origin key 'mjolnir' not found in /hab/cache/keys, aborting
Script done, file is /src/results/logs/test/.2016-10-21-142912.log
vagrant@server-ubuntu-1404:~$ hab pkg build -k mjolnir test/
```

It _seemed_ initially like perhaps we just weren't looking in the user path for the keys at all, however I found that if I define `origin = "mjolnir"` in the  `~/.hab/etc/cli.toml` the keys in the user path are found without issue. My working theory being that we are keying off the `cli.toml` to determine whether or not to traverse the user path for the keys or look  in `/hab/cache/keys`. I'm going to dig into the code in a moment.

**Comment by lilianmoraru** [comment]
@eeyun I have `origin = "lilian"` in that file and it doesn't work for me.
It was after the authorization key, so I thought, may be it is a bug with the order. I've put it first and it still doesn't work.
I tried `hab studio enter`, `hab studio -k lilian enter`, `sudo hab studio enter`, `sudo hab studio -k lilian enter` - none of these worked.
I tried removing the keys from `/hab/cache/keys` and leave the ones in `$HOME/...` - didn't work.
Tried the other way around, still doesn't work.
Tried removing the keys and generating them with `hab origin key generate` and then enter the studio with and without `-k` - doesn't work.
Tried removing all the keys and retrying the same with `sudo hab origin key generate` - still doesn't work.

Is there a workaround for this?

**Comment by eeyun** [comment]
@lilianmoraru i think you might be running into a different error here, can you share to me what your user scope is set to on your GitHub Personal Access Token?

**Comment by lilianmoraru** [comment]
` hab cli — user:email` - as a side note, I've uploaded packages before.

**Comment by eeyun** [comment]
Ah we've like found your problem here, we actually had a user scope requirement change a few weeks ago, I'd guess if you change your token to use the full user scope your problem will resolve!


https://forums.habitat.sh/t/401-errors-on-depot-requests/220

**Comment by lilianmoraru** [comment]
@eeyun Thanks! This solved the issue with `hab pkg upload`.

**Comment by eeyun** [comment]
Awesome! I'm going to close this issue out and open a new one with my findings on the issue @travisfinch raised which is unrelated to the original issue here. I believe I've isolated the source of the `hab pkg build -k`  and will comment here with the reference to the new issue.

Thanks everyone!

**Comment by lilianmoraru** [comment]
@eeyun Note that this did not fix the bug report, just the second issue I had with `pkg upload`(after manually copying the keys).

**Comment by bdangit** [comment]
@eeyun for the token scoping, I too received 401 errors.  However, I was able to upload when I added `read:org` to existing `user:email`.  I did this in accordance to the document here: https://www.habitat.sh/docs/share-packages-overview/
