### ISSUE TITLE
Unauthorized when uploading keys/packages to depot

### ISSUE THREAD

**Issue by freethejazz** [habitat-sh/habitat#1343]
I've been running into issues uploading keys/packages to both a private depot and the public depot. Whenever I attempted to upload either, I was getting 401s.

### Environment
Running Mac OS X - 10.11.6 (El Capitan)
`hab` version - hab 0.10.2/20160930234832

### Steps to duplicate
1. Visit app.habitat.sh for the first time and log in
2. Get redirected to github. Authenticate and allow access.
3. Create origin (`freethejazz` for the remainder of the issue)
4. Visit https://github.com/settings/tokens to create a personal access token, as prescribed in the https://www.habitat.sh/docs/share-packages-overview/ (with `read:org` and `user:email` scopes)
5. run `hab setup` and provide said token
6. generate an origin key
7. Attempt to upload the origin key

ER: Key is uploaded
AR: 401 Unauthorized

1. Attempt to upload the key using the `-z` flag to explicitly pass the personal access token created in step 4 above.

ER: Key is uploaded
AR: 401 Unauthorized

1. Via the web UI, manually copy and paste the the public/private keys generated in step 6 above
2. Attempt to upload a package

ER: Package is uploaded
AR: 401 Unauthorized

### Debug/Backtrace of key upload failure
```
─$ RUST_LOG=debug RUST_BACKTRACE=1 hab origin key upload -z <my_key> freethejazz                                                                 1 ↵
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "origin", "key", "upload", "-z", "<my_key>", "freethejazz"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_http_client::api_client: User-Agent: hab/0.10.2/20160930234832 (x86_64-darwin; 15.6.0)
» Uploading latest public origin key freethejazz
DEBUG:habitat_core::crypto::keys: checking file: freethejazz-20161009005001.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: freethejazz-20161009005001.sig.key
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: freethejazz-20161009043225.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: freethejazz-20161009043225.sig.key
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys::sig_key_pair: Attempting to read key name_with_rev freethejazz-20161009043225 for freethejazz
DEBUG:habitat_core::crypto::keys::sig_key_pair: Attempting to read key name_with_rev freethejazz-20161009005001 for freethejazz
↑ Uploading /Users/joecoolspy/.hab/cache/keys/freethejazz-20161009043225.pub
DEBUG:habitat_http_client::api_client: POST https://willem.habitat.sh/v1/depot/origins/freethejazz/keys/20161009043225 with ApiClient { endpoint: "https://willem.habitat.sh/v1/depot", inner: Client { redirect_policy: FollowAll, read_timeout: None, write_timeout: None, proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.10.2/20160930234832 (x86_64-darwin; 15.6.0)") }
DEBUG:hyper::net: http scheme
DEBUG:hyper::net: https scheme
DEBUG:hyper::http::h1: request line: Post "/v1/depot/origins/freethejazz/keys/20161009043225" Http11
DEBUG:hyper::http::h1: headers=Headers { User-Agent: hab/0.10.2/20160930234832 (x86_64-darwin; 15.6.0), Content-Length: 82, Host: willem.habitat.sh, Authorization: Bearer <my_key>, }
    82 B / 82 B | [==============================================================================================================================================] 100.00 % 794 B/s
DEBUG:hyper::client::response: version=Http11, status=Unauthorized
DEBUG:hyper::client::response: headers=Headers { Accept-Ranges: bytesbytes, Content-Type: text/plain, Fastly-Debug-Digest: cc8dfac89a00cd4472f107d19a5d55fb4792cbd16db2e915d4189fccf4e3798e, X-Cache-Hits: 0, 0, X-Cache: MISS, MISS, Via: 1.1 varnish1.1 varnish, X-Served-By: cache-sea1927-SEA, cache-ord1734-ORD, X-Frame-Options: SAMEORIGIN, Content-Length: 28, Strict-Transport-Security: max-age= 7776000; includeSubDomains, Server: nginx/1.10.1, Connection: keep-alive, Date: Sun, 09 Oct 2016 23:03:42 GMT, }
✗✗✗
✗✗✗ [401 Unauthorized] [err: BUG, msg: rg:auth:2]
✗✗✗
```

### Keys
Including this just in case, but the presence/reading of these files doesn't appear to be an issue.
```
╰─$ ls -alh ~/.hab/cache/keys                                                                                                                                                    1 ↵
total 32
drwxr-xr-x  6 freethejazz  501   204B Oct  8 23:32 .
drwxr-xr-x  4 freethejazz  501   136B Oct  8 19:51 ..
-r--------  1 freethejazz  501    82B Oct  8 19:50 freethejazz-20161009005001.pub
-r--------  1 freethejazz  501   126B Oct  8 19:50 freethejazz-20161009005001.sig.key
-r--------  1 freethejazz  501    82B Oct  8 23:32 freethejazz-20161009043225.pub
-r--------  1 freethejazz  501   126B Oct  8 23:32 freethejazz-20161009043225.sig.key
```

### Workaround
I noticed the bearer token auth header on the post request from the debug logs. I then looked at the chrome network traffic while logged into app.habitat.sh. The bearer token that was being successfully used by the depot was different than the token I was using on the CLI. That's to be expected, since one was created from an OAuth application and the other I created manually. For kicks, I tried the above commands using the token app.habitat.sh was using to communicate with GitHub on my behalf and I was able to successfully upload keys and packages.

Any ideas?

**Comment by reset** [comment]
@freethejazz this was a catch all error that we've improved in master but haven't pushed out to live yet. My best guess is that you're missing one of the two required authentication scopes on your GitHub token. Do you have both the `user:email` and `read:org` scopes enabled on your token?

**Comment by freethejazz** [comment]
I do have both scopes enabled on my token.

@bdangit pointed me to a post in the forum that says that the token now needs access to the full `user` scope: https://forums.habitat.sh/t/401-errors-on-depot-requests/220?u=eeyun

Is that accurate? If so, the documentation update referenced in the post wasn't comprehensive, and I'd be happy to make the remaining updates and submit a PR.

**Comment by reset** [comment]
@freethejazz the requirement for full user scope has been dropped but (right now) our documentation releases faster than our software. I'd give it a shot with the full user scope and drop a note back here with your results. You won't need full user scope once we've pushed an update to the live evnrionment.

**Comment by freethejazz** [comment]
Hmm, I must have gotten some access tokens mixed up at some point. I created a new token with the same permissions as the old token and everything worked just fine. Closing the issue since it seems it may have been PEBCAK from the beginning 😳

**Comment by reset** [comment]
@freethejazz no worries! FYI: The error message you get back will be much more helpful in the next release.

**Comment by freethejazz** [comment]
👍 Thanks!
