### ISSUE TITLE
`hab config apply` does not work as expected

### ISSUE THREAD

**Issue by scarolan** [habitat-sh/habitat#1355]
- [x] The OS (including version) where you are running any of the Habitat commands.

Habitat studio running on CentOS
Linux ip-172-31-54-231.ec2.internal 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 GNU/Linux

- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		RUST_LOG=debug RUST_BACKTRACE=1 hab ...
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

```
RUST_LOG=debug RUST_BACKTRACE=1 hab config apply default 1
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): false, supports_color(): false, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): false, supports_color(): false, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "config", "apply", "default", "1"]
DEBUG:hab: remaining cli args: []
error: SERVICE_GROUP: 'default' is invalid
```

Command I used to start the app (note the --group flag)
`hab start /src/results/seancarolan-mytutorialapp-0.2.0-20161013185143-x86_64-linux.hart --group default`

Command I tried to update config:
`hab config apply default 1`

Error message:
`error: SERVICE_GROUP: 'default' is invalid`

Expected results:  
Config should be updated

Actual results:
`default` service group not recognized.

**Comment by sobakasu** [comment]
I believe the command should be something like:
`hab config apply mytutorialapp.default 1 config.toml`

**Comment by eeyun** [comment]
Yeah @scarolan in this case I believe @sobakasu is correct. This syntax is documented here https://www.habitat.sh/docs/run-packages-apply-config-updates/. 

However, if you find any other place in the documentation where we could improve lets open a separate issue specific to correcting that.

**Comment by juliandunn** [comment]
Nothing more to do here, closing.
