### ISSUE TITLE
hab pkg binlink needs some improvements

### ISSUE THREAD

**Issue by lamont-granquist** [habitat-sh/habitat#1360]
See:

https://github.com/chef-cookbooks/habitat/issues/3

The plan.sh needs something analogous to Gem::Specification#{bindir,executables} in it.   Its probably a better idea to build this as an array of complete paths, rather than a bindir + executables split (since the plan author may have some difficulty wrangling all the binaries into a single directory depending on how the software was originally written).

The default binlink dir should also not be /usr/bin.  That is going to become an issue the first time someone accidentally blows something critical away in /usr/bin.  At the very least it needs to be /usr/local/bin by default and controllable by the user.

The API of having to specify every single binlink individually is also overly fussy.  It may be what some people need, but the common path is going to look more like "please install _all_ of the executable from this package into /usr/local/bin".

There's also an exceedingly useful thing to do in order to create and manage a symlink farm for the user of all the `last` builds of all the versions of packages.

Something like:

/hab/pkgs/lamont-granquist/binstubs/ruby/latest -> /hab/pkgs/lamont-granquist/binstubs/ruby/2.4.0-preview1
/hab/pkgs/lamont-granquist/binstubs/ruby/2.4.0-preview1/ruby -> /hab/pkgs/lamont-granquist/ruby/2.4.0-preview1/20160719231024/bin/ruby
/hab/pkgs/lamont-granquist/binstubs/ruby/2.3.1/ruby -> /hab/pkgs/lamont-granquist/ruby/2.3.1/20160719184108/bin/ruby

That allows for manually adding `/hab/pkgs/lamont-granquist/binstubs/ruby/2.3.1` to the `PATH` and then picking up the latest version of the 2.3.1 binaries.

We should also allow `hab pkg binlink` to be able to be configured so that we could do:

/usr/local/bin/ruby -> /hab/pkgs/lamont-granquist/binstubs/ruby/2.3.1/ruby
/usr/local/bin/ruby24 -> /hab/pkgs/lamont-granquist/binstubs/ruby/2.4.0-preview1/ruby
/usr/local/bin/ruby22 -> /hab/pkgs/lamont-granquist/binstubs/ruby/2.2.8/ruby

The problem this addresses is that while I can setup a global binlink to a given specific version, it is very difficult to inject the latest version and build of a package into the PATH.  A utility could be made to echo the pathname of the latest version and make it up to the user, but that's poorly idempotent, and it would be better to have the hab pkg process which installed the latest version to update a symlink, to make it not the responsibility of the consumer to manage that state.

This basically is what I wanted to manage multiple perl versions and multiple tomcat versions across infrastructure, and I've half built crappy implementations of this around rpm packages a couple dozen times (having to bludgeon rpm into submission in the process and tell it that rn-perl-5.8 and rn-perl-5.10 were different packages).  I'm pretty confident there's a "market" for this feature out there.

**Comment by lamont-granquist** [comment]
(the implementation examples are just the first thing i thought of on a day where i have a pile of other busted shit i need to go fix right now, i'm pretty certain that can be improved...)

**Comment by lamont-granquist** [comment]
Also it might be useful to have a symlink to (for example) the latest ruby-2.3.1 and ruby-2.2.8 builds -- the whole tree.  I wrote this around binstubs, but really just a path that didn't involve the build number and resolved to the latest buildnumber.

Again, you can provide a utility that prints this out, but that requires the consumer to update their paths constantly instead of having one path that always points at latest.  I can see arguments for either way being better depending on the needs of the consumer, and would like to see both.

**Comment by smith** [comment]
@lamont-granquist I've opened #1920, #1921, and #1922 that break out some of your suggestions into separate issues. Please comment on them with any corrections.

I'm going to close this issue for now, but if you would like to open issues for any other of your suggestions in this one please do. Thanks!
