### ISSUE TITLE
No feedback when downloading hab studio

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#1361]
[Screen cast video of the process is available on YouTube](https://youtu.be/zHPW_MeihgI).

When entering the studio for the first time it feels like the command just hangs.

I have hab version 0.11.0.

I do not have the docker image `habitat-docker-registry.bintray.io/studio`   tagged as `0.11.0` downloaded.

I run the command `sudo hab studio enter`

The command takes almost 90 seconds to complete and I think it's not working.

I think there was some user feedback in previous versions so that I knew the studio was being downloaded.  I miss this feedback.

**Comment by juliandunn** [comment]
Fixed by #1374
