### ISSUE TITLE
feature request: hab updates self

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#1395]
From #habitatsummit discussion

>  `hab update` command for hab to pull down the newest release?

Quick discussion with @eeyun on how this might be implemented:
- execute `hab update`
- store current binary path
- rename the current binary to `hab-last`
- download newest binary release to the stored binary path
- confirm download successful, delete `hab-last`, otherwise rollback with error message

With Linux, renaming a running file is supported, and when exiting successfully, the deleted file should be released by the filesystem.

/cc: @jjasghar

**Comment by jjasghar** [comment]
👍

**Comment by onlyhavecans** [comment]
👍

**Comment by jjasghar** [comment]
https://www.habitat.sh/docs/get-habitat/ is the location FYI

**Comment by kbknapp** [comment]
I'm probably saying something that's already known, but [`rustup` does this](https://github.com/rust-lang-nursery/rustup.rs/blob/master/src/rustup-cli/self_update.rs) and it's immensely appreciated!

**Comment by eeyun** [comment]
I started down the path of writing a PR for this but I think theres a bit of chore work that would need to be done to get it right.

The ideal architecture for this is:
- leverage current download logic for getting packages from the depot to pull the hab package
- leverage current unpack logic to get the bin
- determine the location from which the original `upgrade` thread was called
- drop it in place over top of what's there.

The challenge I ran into with this is that the crates we use for the current logic have not made public the  fn's we need to do that download and unpack etc. Not only that but some of that logic is tightly bound to the install logic, which won't work for what we need to do here. Essentially that means getting some chore PRs against the existing crates to open some of those things up. This is further complicated by the fact that we may be re-organizing the `core` and `common` crates in the near future.

I'm going to put this into backlog but it's status could change in the near future. If anyone wants to take a stab, feel free!

**Comment by rsertelon** [comment]
We could also use habitat packages. The way I install habitat on my computers is:

* Use binary download from habitat's website
* untar anywhere
* bootstrap habitat with `sudo ./hab pkg install core/hab`
* create a symbolic link: `/hab/pkgs/core/hab/X.X.X/XXXX/bin/hab` -> `/usr/local/bin`

When I need to update habitat, I actually run `sudo hab pkg install core/hab` and change the symlink.

It wouldn't work on windows, but at least on Unix it should, and I think it's quite elegant. I was inspired by my experience, and by the fact that it is done exactly like this in tar exports of packages.
