### ISSUE TITLE
UX: The makefile should be a little more helpful

### ISSUE THREAD

**Issue by martinisoft** [habitat-sh/habitat#1397]
OS: Mac OS El-Capitan (10.11.6)

Issue: As a new, eager contributor to habitat I went through the README. After cloning the habitat repo and running make, I am greeted with this backtrace:

```
$ make shell
if [ -n "" -o -n "" -o -z "`env http_proxy= https_proxy= docker images -q habitat/devshell`" ]; then \
                if [ -n "" ]; then \
                  env http_proxy= https_proxy= docker build --no-cache --build-arg HAB_DEPOT_URL= -t habitat/devshell .; \
                else \
                  env http_proxy= https_proxy= docker build --build-arg HAB_DEPOT_URL= -t habitat/devshell .; \
                fi \
        fi
env: docker: No such file or directory
env: docker: No such file or directory
make: *** [image] Error 127
```

Ideally, I think if docker is unavailable it should not output that and give me a gentle reminder that I need Docker to be available and point me back at the README. After getting Docker installed everything seems to be good with `make` but it was a small thing that initially confused me.

**Comment by martinisoft** [comment]
As an aside, I think the make script might also want to warn you that initial make commands will take a long time on a slow connection. Given it has to build a docker image then sync up everything else, on my limited connection it took over 15 minutes just to get halfway through the process.

**Comment by bdangit** [comment]
There is this https://github.com/habitat-sh/habitat#setup-on-mac-os-x where Step 1 says install Docker.  :smile:

**Comment by martinisoft** [comment]
> There is this https://github.com/habitat-sh/habitat#setup-on-mac-os-x where Step 1 says install Docker. 😄

So true @bdangit though imagine you come back to it after some time or on a new system. Hopefully you've remembered to run or setup Docker, but having the tool hold your hand a little goes a long way. Even the smartest of us forget the smallest details such as making sure Docker is available.

**Comment by raskchanky** [comment]
Closed via https://github.com/habitat-sh/habitat/pull/3979
