### ISSUE TITLE
Ability to pin habitat versions

### ISSUE THREAD

**Issue by chetan** [habitat-sh/habitat#1409]
### Problem

While #1292 ensured that the hab studio image version matches that of the `hab` binary being used to launch it, there are still several cases where versions can get mismatched. For example:

```
$ ./hab --version
hab 0.10.2/20160930234832

$ ./hab studio enter

[1][default:/src:0]# hab --version
hab 0.10.2/20160930230245

[2][default:/src:0]# hab pkg install core/hab
» Installing core/hab
↓ Downloading core/hab/0.11.0/20161013211955
    2.33 MB / 2.33 MB - [====...] 100.00 % 8.41 MB/s
↓ Downloading core-20160810182414 public origin key
    75 B / 75 B | [====...] 100.00 % 2.02 MB/s
☑ Cached core-20160810182414 public origin key
✓ Installed core/hab/0.11.0/20161013211955
★ Install of core/hab/0.11.0/20161013211955 complete with 1 new packages installed.
```

Essentially, any reference to `core/hab` or `core/hab-studio` will always cause the latest release version to be pulled. This makes it difficult to stage the upgrade process in a build pipeline. One moment you are building against `0.10.2` and a few hours later you are building against `0.11.0` which is suddenly broken. This happened to us during that release cycle and it hit us hard -- in addition to the bad binary issue, we were affected by the changes to root/sudo as mentioned in #1408.
### Solution?

I propose that subshells launched from a given version of `hab` pin to that version. This could be done by exposing a new environment variable when hab is run and propagating that to any subshells as necessary. I'm not sure of all the implications of this as it would have to touch quite a few areas (hab, hab-sup, studio, export pkgs(?))

**Comment by reset** [comment]
@chetan if you enter a studio using `hab 0.10.2` and then install the latest version of `hab`, the `hab` command will not be replaced by that latest version unless you run `hab pkg binlink core/hab hab`.

We can't create an escape hatch to *completely* disallow installation of a newer version of the `hab` package because software you are building may depend on the ability to install another version of `hab`.

I'm not sure how your build process ended up using the binary of the latest installed `hab` without binlinking or pkg exec'ing, but that sounds like the mystery to solve ;)

**Comment by chetan** [comment]
@reset I guess I should have been clearer. The issue manifests itself primarily when you go to export a package and a new studio environment is created and then your packages installed inside: 

`hab pkg export [docker|tar] core/mysql` which creates a new studio context and then packages it up - 

```sh
base_pkgs="core/hab core/hab-sup"
...
  for pkg in $base_pkgs; do
    _hab install $pkg
  done
```
https://github.com/habitat-sh/habitat/blob/master/components/studio/libexec/hab-studio-type-bare.sh#L9-L38

At this point, your new studio contains the latest upstream hab version, and not the one launched with your original export command.

**Comment by reset** [comment]
@chetan I completely understand now, we just need to ensure we pin the version we're installing instead of latest inside of the studio type script that gets loaded from the main studio program. Thanks for the report!

**Comment by chetan** [comment]
Yes, I think that would be the minimum change necessary, but I'm not 100% sure. I can take a stab at working up an initial patch.

**Comment by eeyun** [comment]
I totally noticed this this week, my local bin was v0.11.0 but entering the studio I was still met with the studio bug of v0.12.0 because the studio automatically pulls the latest hab on enter.
