### ISSUE TITLE
'make' failing to finish on (minimally) OSX

### ISSUE THREAD

**Issue by cglewis** [habitat-sh/habitat#1411]
Environment:

`OS X: 10.11.6`

Docker:

```
$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

Command:

`make`

Error:

```
...

env http_proxy= https_proxy= docker-compose run --rm -e HAB_DEPOT_URL= -e HAB_ORIGIN= shell sh -c 'cd components/director && cargo build'
Pulling cargo (tianon/true:latest)...
latest: Pulling from tianon/true
29c5c256db64: Pull complete
Digest: sha256:060df72cb7daf7f3a692cc7e98a04180600d629b21f692dac82e55e96ff1abe7
Status: Downloaded newer image for tianon/true:latest
Creating habitat_cache_artifacts_1

...

   Compiling router v0.4.0
   Compiling habitat_depot_client v0.0.0 (file:///src/components/builder-depot-client)
   Compiling habitat_common v0.0.0 (file:///src/components/common)
error: failed to link `/src/target/debug/deps/libhabitat_director.rlib` to `/src/target/debug/libhabitat_director.rlib`

To learn more, run the command again with --verbose.
make: *** [build-director] Error 101
```

**Comment by juliandunn** [comment]
How did you get this Docker version on your Mac? I am using the stable Docker for Mac and it shows:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

and I can compile it fine.

**Comment by cglewis** [comment]
I'm using toolbox with docker-machine via virtualbox

**Comment by juliandunn** [comment]
Ah. We recommend that you use Docker for Mac, or if you can't, use Docker Machine with VMWare Fusion. Early on we used to use VirtualBox, but found that it had horrible file-sharing bugs that would cause certain objects to disappear inside the guest, which may be what you're seeing.

**Comment by bdangit** [comment]
I was actually able to compile habitat under virtualbox VM. I hacked up the Dockerfile to get the nightly build of rust/cargo.

The error you see above is related to a known issue that rustacaeans have fixed but hasn't been released as a stable build.

When I get my laptop back I'll share a gist.  (Note: would use Mac Docker but my laptop is built in the 2003 :frown:)

**Comment by bdangit** [comment]
Here is the gist as promised.  https://gist.github.com/bdangit/60a5842c1499254131094c577bf79027#file-habitat-dockerfile-patch

-----

Virtualbox does not support hardlinks as discovered in this [Cargo Issue #3098](https://github.com/rust-lang/cargo/issues/3098).

In the nightly's, a [pull-request](https://github.com/rust-lang/cargo/pull/3118) was made to fallback to resort to plain ole `cp` when `hardlinks` does not work.

-----

**Comment by juliandunn** [comment]
Thanks @bdangit. We'll close this for now assuming that Cargo will eventually fix this.
