### ISSUE TITLE
Command 'hab pkg search billmeyer' finds data but panics anyway.

### ISSUE THREAD

**Issue by martinhbramwell** [habitat-sh/habitat#1434]
- [ ] The OS (including version) where you are running any of the Habitat commands.

    you@hab4metdev:~$ lsb_release -d
    Description:	Ubuntu 16.04.1 LTS

- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

    https://gist.github.com/martinhbramwell/97ed25761cf1346ef4773d5ffc21ce88
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

    None

	- [ ] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:
		- [ ] a. before starting the studio
		- [ ] b. inside the studio

    Not applicable

- [ ] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.

		ls -la /hab/cache/keys
		ls -la $HOME/.hab/cache.keys

    Not applicable

**Comment by martinhbramwell** [comment]
Possibly related  ::

[https://github.com/habitat-sh/habitat/pull/1387](https://github.com/habitat-sh/habitat/pull/1387)

[https://habitat-sh.slack.com/archives/general/p1478014300009446](https://habitat-sh.slack.com/archives/general/p1478014300009446)

**Comment by juliandunn** [comment]
Fixed in #1439
