### ISSUE TITLE
Improve error message when user doesn't have read:org github permissions

### ISSUE THREAD

**Issue by teknofire** [habitat-sh/habitat#1444]
When running the `hab pkg upload` you will get a `[504 Gateway Timeout] [err: TIMEOUT, msg: net:route:3]` if the github auth key doesn't have `read:org` permission.  

```
$ hab --version
hab 0.12.0/20161031220814

$hab pkg upload <THE_PKG>.hart
✓ Signed artifact with <THE_PUB_KEY>.pub
» Uploading public origin key <THE_PUB_KEY>.pub
    78 B / 78 B | [...] 100.00 % 465 B/s
✗✗✗
✗✗✗ [504 Gateway Timeout] [err: TIMEOUT, msg: net:route:3]
✗✗✗
```

**Comment by smurawski** [comment]
We've got the right error to throw, I think we might be missing catching the error condition at the right place. 

https://github.com/habitat-sh/habitat/blob/ae07b682e5a94194ae1edf8217ebbca9da1d9146/components/net/src/error.rs#L31
