### ISSUE TITLE
RFC: Studio Origins and Key Management

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1453]
CC @juliandunn @fnichol @smurawski @ryankeairns 

I'd like to discuss the current Architecture of Key and Origin injection into the studio.

The issue is somewhat documented here https://github.com/habitat-sh/habitat/issues/1341#issuecomment-253392497 and appears to be related specifically to the -k flag as part of the `hab pkg build` subcommand. The -k flag allows us to specify multiple origins who's keys we might need when we enter a studio. It does not however set or check the HAB_ORIGIN envvar which is what we use to get the _right_ keys.

The discussion's we've had in person have pointed to a couple of possible solutions to the issue that should be discussed. Should we continue to support passing multiple keys into the studio with -k? If so, should we add a feature flag that allows users to explicitly define a HAB_ORIGIN from the cli? Or should we provide a different path for the same behavior (something like having the pkg build command set HAB_ORIGIN itself based on the value in pkg_origin in the plan.sh)

Either way its an issue that users keep hitting. Some of this pain could also likely be mitigated by more documentation on the errors you might hit without having HAB_ORIGIN or the cli.toml set, but in the cases where people don't I think a safety net will be useful.

**Comment by juliandunn** [comment]
My two cents to @eeyun was that we've seen nobody exercise the use case of actually passing more than one key to the studio, which leads me to believe that the functionality is superfluous and we should really only support one key. Happy to hear other viewpoints.

**Comment by reset** [comment]
I'm a big fan of having an environment configuration per studio and having the key as part of that. I'm definitely open to hearing other solutions, though!

**Comment by smurawski** [comment]
There are two different behaviors here that bleed over into each other.

First, we have the environment variable `HAB_ORIGIN` or the `origin` setting from the `cli.toml`.  If `-k` is not passed, we attempt to copy the signing key matching that origin from either `~/.hab/cache/keys` or `/hab/cache/keys` (which is confusing enough behavior on its own).

Then there is `HAB_ORIGIN_KEYS` or `-k`, which specifies an array of origin names for which to copy the signing keys, but does not set the active `HAB_ORIGIN`.

The main use case I see is the first (setting `HAB_ORIGIN` and copying the key), but there is no CLI setting for that.

The second use case is entering a studio and building for multiple origins, which is not supported by just the `HAB_ORIGIN` or `cli.toml` settings.

I think there is value in making `-k` work properly, but it needs to play well with the other settings and `HAB_ORIGIN` needs a CLI switch.

**Comment by juliandunn** [comment]
As a user I had just assumed that `-k` and `HAB_ORIGIN` were the same thing, in that the value of `-k` would take precedence over any existing origin setting (whether in env var or `cli.toml`). Can we just make that the behavior?

**Comment by eeyun** [comment]
@juliandunn that would be the simplest solution, in fact thats originally what we had planned to do. I think the question becomes whether supporting injecting multiple origin keys into the studio is something we care about from a product perspective.

**Comment by eeyun** [comment]
I think a better question here is: Once depot channels are bubbled up, would there be any use case in which a person would need to upload packages to more than one origin from the same studio?

**Comment by juliandunn** [comment]
Seems unlikely @eeyun. Also it's the same situation whether channels exist or not. You'd create or modify the channel content after you uploaded everything.

**Comment by smurawski** [comment]
I started to outline a scenario where I thought multiple keys makes a difference, but that scenario goes away with the build worker running. (contributor to "core" and having my own packages that depend on "core" -> I want to rebuild a "core" package, then rebuild my package that depends on it from the same studio and upload them both.) 

So, maybe re-documenting -k to be HAB_ORIGIN bringing HAB_ORIGIN_KEYS into that is a better, more simple route.

**Comment by bdangit** [comment]
I vote to keep it simple stupid which means keep it limited to ONE key.  I am sure when the time comes the community will either do two things: 

1. yell really loud and demand we need to have a set of keys
2. Hack around to get past the limitation. 

They would do this because they have deeper clarity on the keys. (Me, I sadly do not have much clarity except it was confusing when collaborating.  But that's probably a different issue. )

**Comment by eeyun** [comment]
The confusion around the keys is totally understandable. The way we handle them right now is incredibly circular. We hand them all over the place only to dump them out into the same location in I think 2 distinctly different ways.

I'm more than happy to go the route of simplifying if it makes UX better personally.

**Comment by rsertelon** [comment]
Given that we now have a `.studiorc`, I feel like if someone needs something complicated, they could be able to do it with that. (Habitat's `.studiorc` actually copies/imports keys).

Maybe we can consider this conversation closed?

**Comment by elliott-davis** [comment]
Seconded on closing this issue. @eeyun please re-open if you want to discuss further.

**Comment by eeyun** [comment]
Yeah i'm all for having this one done. We've actually fixed a bunch of bugs related to this over the course of last year too. Good call :+1:
