### ISSUE TITLE
[pre-release] hab node status not updated when node is down

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1531]
This is an error report for pre-release of hab-butterfly (version: 0.14.x-dev in acceptance from 11/30/2016)

Steps:
1. Spin up multiple (4, in our case) hab nodes in a leader topology
2. Bring down one of the nodes (shut down hab service)
3. Look at the hab sidecar status

Result:
The sidecar info shows that all nodes are alive

Expected:
Status to show one of the nodes is down

**Comment by adamhjk** [comment]
I can help troubleshoot this - pretty sure I know what's up. Also, you really want an odd number of members in leader.

**Comment by adamhjk** [comment]
This is fixed in #1532.
