### ISSUE TITLE
Gateway API does not return health check output

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1548]
When calling the gateway API with a "/services/:svc/:group/health" path, the output from the health hook(s) is not returned (the output returned just says "Finished").

We should return the hook output, preferably in JSON format.

**Comment by smurawski** [comment]
Finished is no longer in the output.  The health check/supervisor cannot buffer the random amount of output from the health check.  We could possibly add an endpoint that could stream back a file and have the healthcheck output to a file, but that would be the most we'd do in this scenario.

**Comment by reset** [comment]
We recently made an addition to our hooks system to log the output of the last run hook. This will now allow us to provide not only the health check result, but the output from that run. This will be in an upcoming release after some of the concurrency refactorings I am working on to the supervisor land!

**Comment by reset** [comment]
Closed by #1987
