### ISSUE TITLE
Config updates can cause an outage if all the nodes are getting updated at once

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1558]
Config updates need to have a roll out - shooting everything with sig-term isn't good for availability

**Comment by smurawski** [comment]
We should support something like the rolling update strategy for config apply and also document the reconfigure hook better to show examples of reconfiguring software without restarting the process.

**Comment by smith** [comment]
Done! https://www.habitat.sh/docs/run-packages-update-strategy/#rolling-strategy

**Comment by mwrock** [comment]
This is actually still an outstanding issue. While the rolling strategy works great for package updates, config updates are currently always at-once.

**Comment by christophermaier** [comment]
Closing this in favor of #4924, since that includes file uploads as well
