### ISSUE TITLE
Need to document pattern for wrapper packages

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1559]
We should nail down a pattern for 'wrapper' packages / dependencies on other pkgs... such that we can merge values from default.toml or overwrite same values from the 'wrapped' pkg...

Also: Wrapper plans require knowing a lot about what the do_ functions do and which to override.  The plan generation doesn't give any hints either

Possible options: Blog post, tutorial, docs update, etc.

**Comment by davidwrede** [comment]
Part of this is covered in the "Connect to Nginx" topic covered in #3108; however, we should also have a general topic that discusses this scenario.

**Comment by rsertelon** [comment]
This is actually something that is missing from the documentation, I found myself without a clue on this subject, until I saw your pull request.

Maybe this could be a new page under Best Practices? If so, I could use your tutorial as an inspiration to create this page.

**Comment by robbkidd** [comment]
Poking this issue in light of the word written in RFC 0009. Is the wrapper pattern or configuration plan pattern known well enough at this point for (it to have a name) words to be added to Best Practices section in the docs?

**Comment by jeremymv2** [comment]
@cm @chefsalim I can also see a valid need for being to have a wrapper package load and render hook / config files from a dependent package so that they are not just duplicated in the wrapper.
I think some clever planning and documentation exposure will be immensely valuable as I know the wrapper pattern is already out in the wild.

**Comment by jeremymv2** [comment]
@christophermaier additionally it would prove really helpful to have "config-only" wrapper packages that merged/overwrote the 'wrapped' pkg's config.
