### ISSUE TITLE
Feature request: provide a hook for service member change

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1561]
Need a hook for when the service group members change - even if there isn't a config change.

**Comment by moretea** [comment]
This would be very applicable to the case where multiple instances are run by an orchestrator such as Kubernetes. A change in group membership might require reconfiguration of e.g. the list of peers of a service.

**Comment by smurawski** [comment]
This could be tied to one of the lifecycle events - like reconfigure.

**Comment by christophermaier** [comment]
What's the use case here? How do you envision a service being affected by membership changes if not through a change in configuration?

**Comment by christophermaier** [comment]
Going to close this, since I think it should be doable through existing reconfiguration methods. Feel free to reopen if new information or use cases surface.
