### ISSUE TITLE
Document all the available runtime config values 

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1562]
Ensure attributes of a bound member are documented 
Eg: {{cfg.message}} 

The config values are documented in an ad-hoc way today (in examples).

**Comment by rsertelon** [comment]
I'd like to help, but I don't understand what needs to be documented here. Do you talk about `{{sys.ip}}` etc.?

**Comment by rsertelon** [comment]
I think this is done in https://www.habitat.sh/docs/reference/#template-data @eeyun maybe you can close this one? :)

**Comment by raskchanky** [comment]
That does look like the right kind of documentation for what this issue is referring to.  If I'm wrong, and there's something not documented there that needs to be, please reopen this.
