### ISSUE TITLE
Document best practice to determine the deps for packages

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1564]
Hard to figure out what hab package you need for a particular dep (partly because list shows all versions of each package making it hard to even read through)

Eg: scenario: want to remove hab packages that are not being used.  How do I determine that?

**Comment by chefsalim** [comment]
The context is a little fuzzy - the original issue is based on a customer engagement where a specific package version needed to be installed (eg, curl or ls).  It's not clear we have sufficient info here to proceed much further with this.

**Comment by reset** [comment]
@chefsalim ok, I'm going to close this issue but we can reopen it if we can reassemble what it's intent was
