### ISSUE TITLE
Add 'ps' hab plan and available from within studio

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1565]
ps command missing from within hab studio

**Comment by moretea** [comment]
I would also like to see `netstat` and `curl` added to the Studio

**Comment by eeyun** [comment]
@chefsalim and @moretea thank you for opening this issue.

During triage today we discussed this and here's where we landed. Adding more packages into the studio image gets really complicated quick. Currently we provide a few different ways for you to get access to binaries that you might want available inside the studio.

For example the most direct:
```
[default:/src:1]# hab pkg install core/busybox
» Installing core/curl
→ Using core/curl/7.51.0/20161214014615
★ Install of core/curl/7.51.0/20161214014615 complete with 0 new packages installed.
[default:/src:1]# hab pkg exec  core/busybox netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 192.168.1.173:51794     4.35.2.167:443          ESTABLISHED
```

The `hab pkg install` command can get you access to many of the packages that you might need. Currently `netstat` and `ps` are both provided by the `core/busybox` package, while `curl` is provided by `core/curl`. You can also take this one step further and use the binlink subcommand to place those binaries in an easy to access location. https://www.habitat.sh/docs/reference/habitat-cli/#hab-pkg-binlink . There are few other undocumentated ways that we will look at getting documented as well.

For now we are going to close this issue. In the future we may revisit this to include more ways to customize the studio experience but for now we are inclined not to add more packages to the studio image.

Thank you again for taking the time to open this issue!

**Comment by moretea** [comment]
Ah, I had not discovered `hab pkg exec` yet.

https://github.com/habitat-sh/habitat/issues/1679 would also come in handy here.
