### ISSUE TITLE
Consider providing a way to expose different runtime ports

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#1571]
Consider providing a way to declare a different expose port(s) when booting a service. at build time we have `$pkg_expose` but at runtime in a package we might want to have a custom port. Should we provide a way that the supervised service can share this custom port to override the exposed port value? We could then bind to get IP addrs as well as the port(s).

**Comment by smurawski** [comment]
We've got this coming with 
* https://github.com/habitat-sh/habitat/pull/1667
* https://github.com/habitat-sh/habitat/pull/1712
* https://github.com/habitat-sh/habitat/pull/1716
