### ISSUE TITLE
RFC: a mechanism to declare runtime environment variables at build time

### ISSUE THREAD

**Issue by robbkidd** [habitat-sh/habitat#1579]
### Problem:

`$(hab pkg path origin/thingie)` in a hook does not guarantee that that the path returned is the version the hook's package was built against. The presence of this command in a hook should be considered a code smell.

```
habitat-sh/core-plans > ack --files-with-matches "hab pkg path" | ack "hooks" | wc -l
      10
```

First notion I can find on this problem is [a forum post](https://forums.habitat.sh/t/allow-env-vars-to-be-passed-from-plan-to-runtime/264) from @elliott-davis.

### Affects: 

Anyone running multiple habitat packages on a single host, the bare-metal scenario. Should not affect those running habitat packages exported to containers.

### Solutions Today:

* Paths can be computed at build time and ...
    * written out to wrapper scripts that act like binstubs for the real binaries, see this pattern in `wrap_with_cert_path` (used for [cargo-nightly](https://github.com/habitat-sh/core-plans/blob/d882abe701aaadc0bd60364df2af38ef0a08676b/cargo-nightly/plan.sh#L40-L54) and [rust](https://github.com/habitat-sh/core-plans/blob/d882abe701aaadc0bd60364df2af38ef0a08676b/rust/plan.sh#L91-L109)) and `write_shim` (used for [github_changelog_generator](https://github.com/habitat-sh/core-plans/blob/d882abe701aaadc0bd60364df2af38ef0a08676b/github_changelog_generator/plan.sh#L45-L59))
    * written out to a file that is sourced by hooks, see notional work on packaging Supermarket with Habitat ([write out in plan](https://github.com/chef/supermarket/blob/a7133c66182aa9410f6f5872170b136497e3a677/habitat/supermarket/plan.sh#L139-L150) and then [source it in a hook](https://github.com/chef/supermarket/blob/a7133c66182aa9410f6f5872170b136497e3a677/habitat/supermarket/hooks/init#L4))

### Solution Idea

Throwing a noodle at the wall:

* A `do_pkg_exports` function that would write out given exports from a plan to an `EXPORTS` file at `$pkg_prefix`.
    * The generator for the default run hook would source this `EXPORTS` file.
    * A `make_binstub` (similar to `fix_interpreter`) to be called during build/install to rename an original binary (like in `wrap_with_cert_path` & `write_shim`) and write out a binstub/wrapper/shim to the original binary's location that sources the `EXPORTS` file.

**Comment by smurawski** [comment]
Currently the `hab pkg path` problem should be helped with a new helper `pkgPathFor`, but the greater problem remains and is one that we need to solve.

**Comment by robbkidd** [comment]
@christophermaier 👋  Heeeey ... runtime env vars!
