### ISSUE TITLE
How to specify versions of dependencies?

### ISSUE THREAD

**Issue by carrete** [habitat-sh/habitat#1582]
I'm sorry if I've missed this in the documentation. I don't see how to do this under "Define your dependencies" in https://www.habitat.sh/docs/create-plans/. For example, because of https://github.com/habitat-sh/core-plans/pull/316 I'd like to require that core/python is at least some recent version. If I could only specify a particular version for core/python that would be acceptable too.

I suppose there are two versions involved, a version for python, e.g. 3.5.2, and a build id, e.g. 20161214023627. Given that the build id "contains" the python version I think all I need to be able to specify is the build id.

**Comment by mwrock** [comment]
You define your dependencies in `pkg_deps` and `pkg_build_deps`. These take an array of packages. To quote the [plan syntax documentation](https://www.habitat.sh/docs/reference/plan-syntax/):

>  You can refer to packages at three levels of specificity: origin/package, origin/package/version, or origin/package/version/release.

So the following would be legal:

```
pkg_build_deps=(
  core/coreutils
  core/cacerts/2016.09.14
  core/rust/1.13.0/20161209032413
)
```
If you omit the release timestamp, habitat chooses the latest release and likewise if you omit the version, habitat will choose the last version.
