### ISSUE TITLE
[PROPOSAL]: Allow passing application command line flags when running under hab-sup

### ISSUE THREAD

**Issue by dmajere** [habitat-sh/habitat#1587]
Hello, 
currently hab-sup does not allow passing command line flags to application.

```
# /hab/bin/hab sup start $(cat /.hab_pkg) --flag
error: Found argument '--flag' which wasn't expected, or isn't valid in this context

USAGE:
    hab-sup start [FLAGS] [OPTIONS] <pkg_ident_or_artifact>

For more information try --help
```
Please, consider adding ability to pass configuration flags when application is stared under habitat supervisor.

**Comment by reset** [comment]
@dmajere this can be accomplished by reflecting on configuration data in your plan's run hook. During a reconfigure the hook is re-compiled and the application is restarted with it, so you will be able to pick up those changes.

It's important that the configuration of the application can always be manipulated by the contents of the ring data for the package's service group (what is gossiped between supervisors). Unfortunately a flag like this, which looks slick and totally makes sense on the surface, would violate that requirement.
