### ISSUE TITLE
Document that hab command can be installed with homebrew on OS X

### ISSUE THREAD

**Issue by kazimuth** [habitat-sh/habitat#1607]
[Homebrew](http://brew.sh/) can install `hab` (and Docker for Mac) with the following command:

```sh
$ brew cask install hab
```

This is more frictionless than downloading a zip file and moving it to a user-local bin directory, and also checks the file hash for you.

**Comment by till** [comment]
Could also help to call it "habitat". :) But that's just me.

**Comment by smurawski** [comment]
Thanks for the suggestion.  The Homebrew cask publishing is not part of our official pipeline and we don't control those releases.  We are happy someone is out maintaining the cask, but we won't be making that an "official" download.
