### ISSUE TITLE
Proposal: pass configs to director services in same layer of TOML

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#1632]
It seems like the best way to pass config into a service from a director config file right now is through env with nested TOML like this:
```
[cfg.services.myorigin.mypackage.mygroup.myorg.env]
HAB_MYPACKAGE="""
[foo]
bar = "baz"
"""
```

Why not enable something like:
```
[cfg.services.myorigin.mypackage.mygroup.myorg.config.foo]
bar = "baz"
```

**Comment by metadave** [comment]
See here for more info on director config: https://github.com/habitat-sh/habitat/blob/master/components/director/src/main.rs#L78-L115

**Comment by themightychris** [comment]
thanks @metadave I've reviewed that as well as the source code, did I miss a more elegant way to do this?

**Comment by smurawski** [comment]
We've retired the director and the supervisor will shortly be able to manage multiple processes, which should streamline this scenario.
