### ISSUE TITLE
[feature] Output full name of build artifcact

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1674]
**TL;WR**:  It would be very useful if `hab studio build` could output a fully qualified name that can be used in a shell command to compose a workflow.

----

## Background
I usually have a workflow to:

1. Make a change to a `plan.sh` (or `Dockerfile` or `package.nix` for that matter)
2. Build an artifact `hab pkg build . -R -k moretea` (and respectively `docker build .` and `nix-build`)
3. Verify that it's correct, by e.g. inspecting the file tree of the generated artifact

## How other systems solve this
Docker and Nix solve this problem in two different ways.
* Docker has a `-q` flag which shows no build output, and only prints the SHA of the generated container to `stdout`.
* Nix redirects all build output (both the `stdout` and `stderr` of the building processes) to `stderr`, and always prints out the filesystem path of the generated artifact to `stdout`.

These features enable me to combine step 2 and 3 of my workflow in one bash command:
* With docker:  `docker run --rm -ti $(docker build -q .) "find /some/path"`
* With Nix:`find $(nix-build)`

## What Habitat does
As far as I have seen, the output of all build processes is outputted to `stdout`.
The command `hab pkg build . -R -k moretea > /dev/null` outputs nothing.

I'm using the following workaround to get to the latest artifact build dir:
```
hab studio run "find /hab/pkgs/moretea/php-redis/0.1.0/\$(ls -t /hab/pkgs/moretea/php-redis/0.1.0 | head -n1)"
```

## Suggested feature
`hab pkg build` should provide a similar mechanism to `docker build -q` or `nix-build` to enable composability at the CLI during development (or potentially even CI)

**Comment by smurawski** [comment]
@moretea Thanks for the feedback.

The habitat build also outputs a `last_build.env` file which contains (for example)

```
pkg_origin=core
pkg_name=hab-builder-api
pkg_version=2941
pkg_release=20170120192802
pkg_ident=core/hab-builder-api/2941/20170120192802
pkg_artifact=core-hab-builder-api-2941-20170120192802-x86_64-linux.hart
pkg_sha256sum=fd38be00d2333966cabc2bfcbae75a55fd2f107c3c3a664639d617b9f3c75f6a
pkg_blake2bsum=c115db678b2a9d0dbb3e39396adc00f5873ed13f21010504f16ac50e24335c84
```
This can be sourced as is to create environment variables that can be referenced, which include the package artifact name, package ident (and the components of the ident), and some hashes. 

If that doesn't meet your needs, please re-open this issue and advise what additional information you'd need.

**Comment by moretea** [comment]
:+1: I spoke about this with @fnichol  IRL last Friday. This solution is acceptable as well.
