### ISSUE TITLE
[UX] Make `hab pkg build -R` the default

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1678]
It's an easy flag to forget, which will break your dev-flow for a few minutes, because it first deletes the old studio and then downloads the new one. If you `CTRL+C` just after you realized that you forgot to pass this flag, you're already too late, since the old studio has been removed by then.

What about making it the default choice to to reusing the existing one.  Then a  `-P` (for pure) flag could be added  to `hab pkg build`, that would create a new studio if the user requests it.

**Comment by adamhjk** [comment]
The workflow we've been advising is that interactive work get done with `hab studio enter`, not repeated external calls to `hab pkg build`. Does this not fit your use case?

**Comment by moretea** [comment]
I spoke about this with @fnichol, and learned that you're only supposed to use use `hab pkg build` during CI-like builds, not during development.
