### ISSUE TITLE
[UX] Binlink option to `hab install`

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1679]
Making a package available in a studio (like `netstat` and `curl`, that one uses regularly) must be installed with e.g. `hab install core/curl` and made available with `hab pkg binlink core/curl curl`.

It would be a bit more ergonomic if `hab install` had a flag to also directly link all binaries in that package.

**Comment by adamhjk** [comment]
This seems legit, and should be pretty easy to implement. I have one behavior question - do you binlink every binary in every binary path thats declared in the plan? 

I suspect the answer is yes.

**Comment by moretea** [comment]
@adamhjk yes, but only the binaries that are build that plan, not all bins that are transitively reachable
