### ISSUE TITLE
Failure when trying to install the same thing multiple times

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#1681]
If many processes are trying to install one package all at once, an error can happen:

```
hab install core/hab-sup && rm -rf /hab/pkgs/core/hab-sup && hab install core/hab-sup & hab install core/hab
-sup & hab install core/hab-sup & hab install core/hab-sup & hab install core/hab-sup & hab install core/hab-sup & hab install core/hab-sup &
...
→ Using core/zlib/1.2.8/20161118033245
✗✗✗
✗✗✗ Couldn't read MetaFile: TARGET, not found
✗✗✗
✓ Installed core/hab-sup/0.16.0/20170119213934
★ Install of core/hab-sup/0.16.0/20170119213934 complete with 1 new packages installed.
✓ Installed core/hab-sup/0.16.0/20170119213934
★ Install of core/hab-sup/0.16.0/20170119213934 complete with 1 new packages installed.
...
```

Ran into this because we have a monolithic app where after install it has a bunch of systemd units that all run `hab start x`. Since systemd starts them all at the same time and hab-sup isn't there, when this error happens some services don't start, even though everything is fine after a restart.

**Comment by smurawski** [comment]
We should somewhat randomize the temp download file name on package install.

**Comment by fnichol** [comment]
![gif-keyboard-6087454174194206133](https://cloud.githubusercontent.com/assets/261548/22487697/9da489ac-e7cb-11e6-90fe-0f40ffc76b4e.gif)

**Comment by arochaf** [comment]
We are still seeing this in some cases where we start/install several packages at once.
