### ISSUE TITLE
[doc] Document the difference between `hab pkg build` and `hab studio enter`

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1701]
Follow-up on https://github.com/habitat-sh/habitat/issues/1678#issuecomment-275543342

I understood from @fnichol that `hab pkg build` is not really supposed to be used to do development, and therefore re-downloading all dependencies is acceptable.

It would be quite helpful if this intention was mentioned in the help text on the CLI

```
$ hab pkg build --help
hab-pkg-build
Builds a Plan using a Studio
```

The help text printed out at the moment does not inform the user of why and when this command should be used.

**Comment by fnichol** [comment]
Agreed, we should be able to make this clearer in the CLI usage and the website docs.
