### ISSUE TITLE
[bug] `hab studio rm` deletes files outside the studio

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1705]
Last Friday I lost some data. `hab studio rm` removed not just the studio, but also all files in my working directory (including the .git directory)

**Comment by tashimi** [comment]
Let's prioritize this one.

**Comment by eeyun** [comment]
@fnichol and I have discussed this. It's possible I have  a way to repro but we need more information from @moretea .

The repro case ONLY effects linux users:
If you enter two separate studio's in the same directory structure
```
$ cd /foo/bar
$ hab studio enter
```
and
```
$ cd /foo
$ hab studio enter
```
This functions normally. However, when you remove these studios in the order of outer first, followed by inner, you experience data loss.
```
$ cd /foo
$ hab studio rm
```
and
```
$ cd /foo/bar
$ hab studio rm
```
You won't experience data loss until you attempt to RM the inner studio. It will continue to function normally and the moment you run the remove command the second time you'll get a huge list of errors about being unable to remove things followed by being unable to enter the studio and the directory being void of content.

**Comment by moretea** [comment]
I don't remember exactly what happened here. Just that I lost some file. Could very well be the scenario that you mentioned @eeyun

**Comment by nellshamrell** [comment]
Attempted to repro on an Ubuntu VM with:

```
$ mkdir foo
$ touch foo/one.txt
$ mkdir foo/bar
$ touch foo/bar/two.txt
$ ls foo
    bar
    one.txt
$ ls foo/bar
    two.txt
$ cd foo
$ (foo) hab studio enter
$ (foo) hab studio exit
$ cd bar
$ (foo/bar)
$ (foo/bar) hab studio enter
$ (foo/bar) hab studio exit
$ cd ..
$ (foo) hab studio rm
$ (foo) cd bar
$ (foo/bar) hab studio rm
```

Currently not seeing any file loss when running that sequence

```
$ ls foo
    bar
    one.txt
$ ls foo/bar
    two.txt
```

**Comment by nellshamrell** [comment]
I can confirm that manually removing the foo studio (using the setup above) empties the foo directory....and breaks just about everything

**Comment by nellshamrell** [comment]
Possible fix - as discussed with Fletcher last week

* when someone runs "exit" in hab studio, unmount filesystems
* if someone attempts to run hab studio rm (or manually remove the studio directory) when things are still mounted, return an error.
