### ISSUE TITLE
supervisor member reincarnation handling issue

### ISSUE THREAD

**Issue by juliandunn** [habitat-sh/habitat#1711]
Supervisors that are killed and come back as a new GUID aren't properly seen by the rest of the network as new entities. There is still some associated state in the network.

To reproduce, you can do the following:

1. Start up one peer (doesn't matter what workload it's running)
2. Start up a `core/redis` cluster (i.e. at least three) using `--topology leader` and point them at the peer from step 1
3. A leader election happens and that's great - that's normal
4. Kill all the Redis peers
5. Wait a while for the peer from 1 to confirm all the members are dead
6. Repeat step 2. You'll notice that quorum is never achieved so an election never happens.

I have a video that illustrates this: https://chef.zoom.us/recording/play/6AtR9rOO_xkxXsRr5aHo7dBXJAJuByI6OUcLSkFbp5eQ6Gj27CZgkdKJ2T3akQjD

This is using `hab-sup` built from master as of yesterday, so it's 0.17.0-dev

**Comment by adamhjk** [comment]
This will be solved when #1994 is implemented.

**Comment by reset** [comment]
Fixed by https://github.com/habitat-sh/habitat/commit/5edaee5e041b4ffcd6b635a07596e65801ab323f
