### ISSUE TITLE
[depot] Accept invitation from Web UI changes the least significant digit in the ID to 0

### ISSUE THREAD

**Issue by smurawski** [habitat-sh/habitat#1717]
The submitted invitation ID was 

```
217909067547418620
```

but the real invite ID is 

```
217909067547418625
```

- [X] The OS (including version) where you are running any of the Habitat commands.

Server is running on Ubuntu 16.04 off of master (currently 87fdfe2f193a29e3c0d025c6d01f98c2bb4a0609).

Web client is Chrome on Windows 10.

- [X] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

Debug log from the vault server

```
hab-builder-vault.monolith(O): DEBUG:habitat_builder_vault::server::handlers: Got invites for account 217460054159261696
hab-builder-vault.monolith(O): DEBUG:habitat_builder_vault::server::handlers: Error accepting invite, maybe it's already been accepted? No value for key found
hab-builder-vault.monolith(O): DEBUG:habitat_builder_vault::data_store: Can't find origin invite for invite_id 217462153542631424:No value for key found
```

JSON from the client after loading the user's origin page:

```
{
  "account_id":217460054159261696,
  "invitations":[{
    "id":217909067547418625,
    "account_id":217460054159261696,
    "accaccount_name":"smurawski",
    "origin_id":217908492869058562,
    "origin_name":"testing",
    "owner_id":217462007236927489
  }]
}
```

Request submitted when clicking the accept invitation button:

```
PUT https://depot.stevenmurawski.com/v1/user/invitations/217909067547418620 HTTP/1.1
Host: depot.stevenmurawski.com
Connection: keep-alive
Content-Length: 0
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
Origin: https://depot.stevenmurawski.com
authorization: Bearer 9cb847c26ff48392c6f7a7ca2ff88bda7c8908f5
Accept: */*
Referer: https://depot.stevenmurawski.com/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8
```

**Comment by smurawski** [comment]
Note, if I resubmit the request (via Fiddler) and change the ID to match the real invite ID, things just work.

**Comment by cnunciato** [comment]
Closing as invitations have undergone some work and seem to be working properly now. Feel free to reopen if you run into it again, though!
