### ISSUE TITLE
Export to docker fails in tutorial

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1721]
The fix https://github.com/habitat-sh/habitat/pull/1720 addressed the syntax error described in https://github.com/habitat-sh/habitat/issues/1718 but the export to docker step still fails when running the tutorial.

```
Sending build context to Docker daemon 194.9 MB
Step 1/8 : FROM scratch
 --->
Step 2/8 : ENV PATH :/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/node/5.6.0/20161214013051/bin:/hab/pkgs/core/hab-sup/0.16.0/20170119213934/bin:/hab/pkgs/core/busybox-static/1.24.2/20161214032531/bin:/hab/pkgs/core/bzip2/1.0.6/20161208225359/bin:/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/openssl/1.0.2j/20161214012334/bin:/hab/pkgs/core/xz/5.2.2/20161208230159/bin:/hab/pkgs/core/busybox-static/1.24.2/20161214032531/bin:/hab/bin
 ---> Running in 1ac314db40ba
 ---> 54582426fc2b
Removing intermediate container 1ac314db40ba
Step 3/8 : WORKDIR /
 ---> 8b39f0312a06
Removing intermediate container bc2a1723642b
Step 4/8 : ADD rootfs /
 ---> defdd5dea245
Removing intermediate container 6dc630657edd
Step 5/8 : VOLUME /hab/svc/mytutorialapp/data /hab/svc/mytutorialapp/config
 ---> Running in af74e19b5d88
 ---> c88f431e0948
Removing intermediate container af74e19b5d88
Step 6/8 : EXPOSE 9631 port
Invalid containerPort: port
```

**Comment by adamhjk** [comment]
@reset is this due to changes in the build script due to the exports functionality? it seems unlikely, since we haven't released.

**Comment by bodymindarts** [comment]
Running `hab start ...` inside of `hab studio` also fails:
```
 hab start myorigin/mytutorialapp --config-from /src
hab-sup(MN): Starting myorigin/mytutorialapp
hab-sup(MR): Butterfly Member ID 63511c1e3c034258a86165a16b2384b0
mytutorialapp.default(SR): Process will run as user=hab, group=hab
hab-sup(MR)[src/manager/mod.rs:126:27]: Invalid port number in package expose metadata: invalid digit found in string
```

**Comment by reset** [comment]
@adamhjk I don't expect any breaking changes on master, it's interesting that the literal `port` is being passed as an expose - let me see how that's leaking in the tutorial on master

**Comment by bodymindarts** [comment]
```
hab -V
hab 0.16.0/20170119214652
```

**Comment by reset** [comment]
@bodymindarts you'll want to either build your own hab/supervisor from the master branch or [look at the docs tagged to 0.16.0](https://github.com/habitat-sh/habitat/tree/0.16.0/www)

@adamhjk the website auto-updated with the doc changes from what is on master - we need a way to specify "stable" and "nightly" docs

**Comment by smurawski** [comment]
@bodymindarts Sorry for the confusion, but we currently don't have versioned docs (but we should!).  So you are seeing some upcoming features/behavior.  Hopefully we'll get that sorted out in the near future.
