### ISSUE TITLE
"hab origin key export" should default to --type=public

### ISSUE THREAD

**Issue by msuriar** [habitat-sh/habitat#1728]
Current behaviour:

```
% hab origin key export msuriar
error: The following required arguments were not provided:
    --type <PAIR_TYPE>

USAGE:
    hab origin key export <ORIGIN> --type <PAIR_TYPE>

For more information try --help
```

In the spirit of:
- Have sensible defaults
- Make things easy

I'd suggest that maybe `--type` should default to "public", since that's what you should be doing 99% of the time?

Possibly this is less relevant once #1727 is fixed. What I'm trying to do right now is step through this [tutorial](https://www.habitat.sh/docs/create-packages-build/).

In the case where you have multiple origin keys, it would be useful to be able to get a list of them quickly.

**Comment by fnichol** [comment]
I totally agree here, that's a very reasonable default and more pleasurable experience.
