### ISSUE TITLE
Document `hab pkg header`

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1735]
As a user of habitat I'd like to have documentation exposed for the `hab pkg header` command and it's uses.

**Comment by smurawski** [comment]
Hey @eeyun, `hab pkg header` isn't a command we wanted to document and surface as it's more of a feature for developers working on habitat itself (rather than remembering `head -n5` or trying to figure out the Windows equivalent).  This is one reason why the command is not visible in the CLI help.

You can see some of the discussion in the PR for the implementation - https://github.com/habitat-sh/habitat/pull/1388

**Comment by eeyun** [comment]
@smurawski I've read the discussion in the past. I'm not suggesting that we necessarily expose it into the help commands. I'm suggesting that as this is an OSS project there is a possibility of community members or contributors needing to be aware that the command exists. In fact this came up during conversations with community members in berlin. 

I'm willing to have my opinion changed but I disagree that "external contributors don't need to be aware of it" is a valid reason for not documenting the behavior. Perhaps we can continue this discussion, @habitat-sh/habitat-core-maintainers ?

**Comment by adamhjk** [comment]
I think there is no damage in documenting this - it's either a useful interface or it isn't. I suspect it is, so we should expose it.

**Comment by smurawski** [comment]
You won me over @eeyun  :)

**Comment by reset** [comment]
@eeyun perhaps renaming the command to something less tied to our implementation and not hiding it would be enough since the CLI is self documented. What about `hab pkg info`?

**Comment by eeyun** [comment]
That would be fine with me!

**Comment by reset** [comment]
@eeyun perhaps this is something you'd like to do? 😄

**Comment by eeyun** [comment]
Yeah. I'm literally going through old issues and trying to burn a bunch of
them. I can clean this up.

**Comment by reset** [comment]
I'm going to close this out - `hab pkg header` is a debug command for support/devs. We should keep these documented in a support guide or a special section in the ref docs but not in the CLI
