### ISSUE TITLE
cannot manually install artifacts dropped into /hab/cache/artifacts

### ISSUE THREAD

**Issue by juliandunn** [habitat-sh/habitat#1736]
Scenario:

1. Drop a `.hart` into `/hab/cache/artifacts` that isn't already installed into `/hab/pkgs`
2. `hab pkg install /hab/cache/artifacts/yourhart.hart`

You get an error:

```
DEBUG:habitat_common::command::package::install: Found core/hab-sup/0.17.0-dev/20170202154310 in artifact cache, skipping remote download
✗✗✗
✗✗✗ Crypto error: Can't read format version
✗✗✗
```

This does not happen if you try to install that `.hart` from any *other* directory, like `/tmp`.

**Comment by fnichol** [comment]
Ah, this could easily be an edge case--the install process will copy any local artifact files into the artifact cache before extracting (i.e. installing). We should check to make sure that a temp file gets used (I suspect that the source file is trying to be written right back to the destination file).

**Comment by reset** [comment]
We're not recommending that the contents of `/hab` are touched by the end-user at all. There is one exception to this in writing a `user.toml` which we are currently abstracting in #2119
