### ISSUE TITLE
[UX] hub setup on white background does not show the default values

### ISSUE THREAD

**Issue by tuxmea** [habitat-sh/habitat#1740]
During habitat Workshop on provided VM:

sudo hab setup running on a terminal (iTerm2) with white background.
Default values are not shown.

<img width="549" alt="image" src="https://cloud.githubusercontent.com/assets/763214/22795058/92834ffa-eef5-11e6-89c9-2f8ea504fa15.png">

**Comment by alicebob** [comment]
There is also some unreadable yellow-on-white. Would it be possible to simply drop the colors and use bold without specifying any color? That way it works everywhere.

**Comment by alicebob** [comment]
![screenshot from 2017-05-22 23-22-55](https://cloud.githubusercontent.com/assets/621306/26329020/a0609b3c-3f45-11e7-994a-f2cf18e58936.png)

**Comment by alicebob** [comment]
And to drive the point home:

![screenshot from 2017-05-22 23-28-22](https://cloud.githubusercontent.com/assets/621306/26329212/768b19da-3f46-11e7-9407-a6f8f8a6e247.png)
