### ISSUE TITLE
Inconsistency between {{svc.me.leader}} && {{svc.me.follower}}

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1742]
In a 3 node setup there will be 1 node where 
```
{{svc.me.leader}} = 'true'
{{svc.me.follower}} = 'false'
```
 and 2 where 
```
{{svc.me.leader}} = 'false'
{{svc.me.follower}} = 'true'
```

After killing the leader the situation is as follows:
1 node has : 
```
{{svc.me.leader}} = 'false'
{{svc.me.follower}} = 'true'
```
and 1 has:
```
{{svc.me.leader}} = 'false'
{{svc.me.follower}} = 'false'
```

So there is obviously still a leader (`follower != 'true'`) but you cannot discover it via querying `{{svc.me.leader}}`

**Comment by adamhjk** [comment]
@bodymindarts has the election finished on the followers?

**Comment by adamhjk** [comment]
We dug a little more into this via zoom. We found a couple things:

1) We are currently re-configuring during interstitial election states; we really only want to reconfigure when an election is finished, not while its in progress.

2) We run reconfigure before we run the init hook - this should be reversed

3) Lets write some test coverage for when hooks get triggered :)
