### ISSUE TITLE
Elect 'healthiest' follower when leader goes down

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1767]
When running clustered statefull services where follower nodes count on streaming replication to sync with a leader node we want to elect the follower that is 'furthest along' as the new leader.

Are there any thoughts as to how this can be achieved? Either as a work around or supported in the core. I'd be happy to brainstorm and hack on a solution.

**Comment by adamhjk** [comment]
Yay! This is a feature we've known the election logic needs, but haven't wired it all the way through the code base. To get started, check out:

1. Check out the Election rumor wire protocol itself in `components/butterfly/protocols/swim.proto`. The field you want is `suitability`.

2. Check out `src/rumor/election.rs`, and check out how we pass `suitability` in when we call `Election::new()`.

3. In the same file, check out the `merge` function for the `Rumor` trait. The suitability logic is implemented there, and should be working - worth reading through just for your own reference.

4. See in `butterfly/src/server/mod.rs` where we call `start_election(sg, 0, term)` within `restart_elections`, and how `start_election` takes a suitability.

5. This gets wired in to the supervisor in `sup/src/manager/mod.rs` in the `restart_elections` function. It's here that you would add passing the suitability in, and threading it through what you saw in 4.

6. To get the suitability, you'll need to add a check to `sup/src/manager/service/hooks.rs`. I would call it `suitability` or `election_suitability` if we're feeling terse. 

7. In the `sup/src/manager/service/mod.rs`, you'll want to add a function to run the hook. Something like the `smoke_check` function. One problem you're going to run in to is that the `try_hook` function in `hooks.rs` has a return signature of `Result<()>` - this is the first hook that returns meaningful data beyond its error code. Here you have a choice to make. 

Either your new hook uses `exit` codes for the value, at which point your new function in `service` can look at the error struct, grab the exit code, and make that the value. Downsides here are that now you're not allowed to exit with an error code. It's the short code path, but I suspect the wrong one for the project.

Alternatively, your hook should write its suitability to a location on disk, much like we do for things like `PID` and friends. This has the advantage of giving you at-a-glance suitability on the filesystem, and makes the lookup cheap (we'll get to that in a moment).

Finally, we could do something with stdout and stderr of the script itself. Right now we write the stdout of the script to hab - you would need to have some logic to intercept that, and change the function signature of `Hook.run` to return something stringy.

We should have @reset and @fnichol weigh in here, but I think I would take option 2, writing to disk.

8. I would refactor the `restart_election` logic in butterfly to split into two functions. You need a `check_restart_elections` that corresponds to the top of the function, and returns the set of elections that need to be restarted. For these elections, in the `managers` corresponding `restart_elections`, you would then call the suitability hook for each, then pass the data back in to butterfly with the remainder of the current `restart_elections` function`. 

9. Celebrate.

![gif-keyboard-15896957672388965030](https://cloud.githubusercontent.com/assets/4304/22982800/025b6250-f355-11e6-8986-6b41fcc40566.gif)

**Comment by adamhjk** [comment]
My lookup cheap astatement above - we might want to consider making this easy to run from the http gateway.

**Comment by bodymindarts** [comment]
Without taking the implementation complexity into account yet (haven't looked at the code) I vote for using stdout / stderr as the method of returning the value.
To me this seems the most intuitive from a pkg dev perspective.
If there is a need to be able to compute and lookup the suitability value independently from each other for performance reasons or something like that then I guess writing to disk would also make sense and might be a sensible trade off.
Using exit codes feels like complete abuse.

So yeah... either of those 2 options seems reasonable.

**Comment by adamhjk** [comment]
Go with the stdout/stderr.

**Comment by bodymindarts** [comment]
Quick question @adamhjk @reset: should `suitability` be taken into account for the update election as well?
I'm thinking probably not but want to see what you guys have to say.

**Comment by reset** [comment]
@bodymindarts for the update election, at least how it is today, we do take suitability into account. We make sure that if you're the leader of a topology that you have a less desirable suitability to become an update leader. This way the leader of a topology always updates last

**Comment by bodymindarts** [comment]
There is an issue:
The hab-sup manager code [supports multiple services](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L157) and each of them could hypothetically have a `suitability` hook.
How do we decide which one should take precedent?

**Comment by reset** [comment]
@bodymindarts we're starting an election [per service group](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L125) so the elections of one shouldn't interfere with another (theoretically 😄). Are you seeing something different or was this just a general heads up question?

**Comment by bodymindarts** [comment]
@reset no it was just a question. I'm still in the process of looking through the code and obviously haven't found all the relevant code paths yet. Thanks for pointing out that line.

**Comment by bodymindarts** [comment]
https://github.com/habitat-sh/habitat/pull/1794 handles adding suitability when a service _initializes_ an election. But there is still the issue of when it receives an election issued by another server. Still thinking about that. The relevant method that gets called [is here](https://github.com/habitat-sh/habitat/blob/master/components/butterfly/src/server/mod.rs#L576).

**Comment by bodymindarts** [comment]
Alright https://github.com/habitat-sh/habitat/pull/1794/commits/8f53ecc99871be24733082b22cb7f8e385f15315 handles it. Basically using a function object to allow on demand lookups of suitability.

**Comment by bodymindarts** [comment]
Reopened because travis wasn't happy https://github.com/habitat-sh/habitat/pull/1795
