### ISSUE TITLE
Remove dependency on docker daemon to export docker images

### ISSUE THREAD

**Issue by moretea** [habitat-sh/habitat#1778]
I would suggest to create a file that can be loaded with `docker load`. This will remove the dependency on a running docker daemon on the host system, and remove lots of impurities.

For details on how to implement this, see
https://github.com/NixOS/nixpkgs/tree/d5316884e4177f8d77366886eeffc2d66f599358/pkgs/build-support/docker

**Comment by eeyun** [comment]
@fnichol is out of the office this week, but we'd like to take a look at this with him next week! Thanks for opening this issue.

**Comment by adamhjk** [comment]
FWIW, I would be stoked to see this - when we implemented this, there was no documented/supported way to build a docker container without docker. Is there now?

**Comment by adamhjk** [comment]
As a secondary question, what does this do to the UX? Right now you wind up with a docker container you can run immediately - this would create something you can use `docker load` with?

**Comment by moretea** [comment]
@adamhjk yes indeed, it should produce an artifact that you could load into docker, or host on e.g. S3.

**Comment by fnichol** [comment]
While working on #3213 I looked at this possibility and really wanted to shed the dependency on either a Docker client (i.e. shell out to `docker`) and possibly a Docker Engine. In the final implementation however, between building, tagging, and optionally pushing this felt untenable--at least in the first implementation. I wasn't too keen on writing raw image layers unless I could find some more official docs as this would create a support burden on us as soon as any of those assumptions changed. There's also a small improvement we can make which would drop the run dep on `core/docker` in favor of using a Rust Docker client (still unpublished by yours truly, due only to making time).

For now, I'd like to close this out and hold on to this idea if it becomes easier and supported in the future. My hope is that the new functionality outweighs the extra dependencies on Docker (currently both Client and Server).
