### ISSUE TITLE
Use crates.io versions for staticfile and zmq

### ISSUE THREAD

**Issue by rushmorem** [habitat-sh/habitat#1798]
Currently these crates are pointing to Github repos however updates have already been released to crates.io. I ran into this while trying to package `v0.17.0` for NixOS. I would really appreciate it if we can do a point release that incorporates these changes once we are done.

These will need to be updated in `components/builder-admin/Cargo.toml ` and `components/builder-api/Cargo.toml `.

**Comment by moretea** [comment]
I'm importing the hab binary as a binary artifact on my NixOS machine:

```nix
with (import <nixpkgs> {});
let
  hab = stdenv.mkDerivation rec {
    name = "habitat-${version}-${build-nr}";
    version = "0.17.0";
    build-nr = "20170214234052";

    phases = "unpackPhase buildPhase";

    src = fetchurl {
      name = "${name}.tar.gz";
      url = "https://bintray.com/habitat/stable/download_file?file_path=linux%2Fx86_64%2Fhab-${version}-${build-nr}-x86_64-linux.tar.gz";
      sha256 = "68f71b1359af42276151254d2ef9b43246718d8f6d266a9f8db9ea52f83aa63c";
    };

    buildPhase = ''
      mkdir -p $out/bin
      cp hab $out/bin
    '';
  };
in
{
  inherit hab;
  env = stdenv.mkDerivation {
    name = "habitat-env";
    TERM="vt100";
    buildInputs = [hab];
  };
}
```

I use the `env` key to start a nix-shell with hab in the environment and the terminal set to something that doesn't have colors, since the colors that habitat outputs are not visible properly on a black-text-on-a-white-background terminal : `nix-shell <pathtonixfile.nix> -A env`

**Comment by rushmorem** [comment]
@moretea Thanks. I know I can install it as a binary just fine on NixOS. However in `nixpkgs` we prefer to install packages from source. In any case, it's no longer necessary to depend on Github versions for those crates since they are now updated on crates.io.

**Comment by rushmorem** [comment]
I have just managed to package `v0.30.2` successfully.
