### ISSUE TITLE
Slow hash generation for lots of files

### ISSUE THREAD

**Issue by chetan** [habitat-sh/habitat#1800]
When the package being built contains lots of files (in my test case, a nodejs app with 50k+ files, blake2b generation can be very slow due to (I think) shell overhead:

Timestamps show elapsed times:
```
00:02:47.404    xxx: Generating blake2b hashes of all files in the package
00:04:08.652    xxx: Generating signed metadata FILES
```

(not entirely sure why the times differ so much above and below, but the `user` time appears to match)

```sh
$ time find . -type f     | sort     | while read file; do hab pkg hash "$file"; done > ~/hashes2

real	4m1.489s
user	1m55.800s
sys	0m49.140s
```

vs a simple ruby script for comparison:

```sh
$ time find . -type f | sort | ruby -rblake2 -ne 'puts Blake2.hex(File.read($_.strip)) + "  " + $_;'  > ~/hashes-ruby-sorted

real	0m4.644s
user	0m3.784s
sys	0m0.844s
```

Obviously I'm using a different blake2b impl here, and it could be that the impl used by `hab` is just slow. Needs some more investigation.. 

- [x] The OS (including version) where you are running any of the Habitat commands.

Ubuntu 14.04.5 LTS + hab 0.17.0/20170214234052

**Comment by smith** [comment]
This is the function that's actually doing the work, where I suspect the slowness is coming from: https://github.com/habitat-sh/habitat/blob/f4d8813210601bc01738644441b8b8477f9dd860/components/core/src/crypto/hash.rs#L65-L91

I've noticed the slowness too, especially on Node projects. I knew it was correlated to the number of files, but thanks for showing this comparison, as it shows this absolutely should be fixed.

**Comment by chetan** [comment]
So I whipped up a version of `hab pkg hash` that could read files from STDIN and generate the correct output (`"<hash>  <filename>"`) and the results are much better:

```sh
$ time find . -type f | sort | /vagrant/hab pkg hash > ~/hashes-new

real	0m8.423s
user	0m7.192s
sys	0m1.148s

$ wc -l ~/hashes-new
53509 /home/vagrant/hashes-new
```

**Comment by chetan** [comment]
Code here https://github.com/chetan/habitat/commit/aa4cccf41d2aec4215eef95e94fdd02a8cd895c5

**Comment by chetan** [comment]
Should I open a PR? I can also change the output of the single file mode `hab pkg hash <file>` to have the standard `*sum <file>` output but it would be a breaking change so I didn't change that yet.

**Comment by smith** [comment]
@chetan please open a PR. The breaking change shouldn't be a big deal since the only consumer I know of is the script you're changing, and if not, well we're on version 0.17 and breaking changes happen.

**Comment by chetan** [comment]
@smith done, see #1804
