### ISSUE TITLE
[RFC] Reconfigure without restart

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1801]
In some cases processes can be reconfigured without requiring a restart.
EG:
`haproxy -f /tmp/haproxy.cfg -p /tmp/haproxy.pid -sf $(cat /tmp/haproxy.pid)`

Would adding a var to the plan like `pkg_svc_restart_on_config_change = false` or something like that make sense?

Then _only_ the `reconfigure` hook would be executed instead of stopping and starting the process as well. For that to work we'd have to inject the `PID` somehow to the reconfigure hook.
Perhaps via an environment variable:
```
haproxy -f {{pkg_svc_config_path}}/haproxy.conf -p ${HAB_SVC_PID}
```

**Comment by smith** [comment]
I think this will be very common, as many services can be reconfigured with just a HUP signal.

If there were a variable representing the PID, could we make it so the default reconfigure hook restarts the service using the hook itself, then if you override it it would do whatever you script said instead?

**Comment by bodymindarts** [comment]
That would make it difficult to bosh restart and reconfigure when the service requires (which is currently the behaviour)

**Comment by mwrock** [comment]
I wonder if the ideal scenario would be to only restart if there is no reconfigure hook. If I know my app needs to do something other than simply restart, I'd have that in the hook. If my app needs extra logic AND a restart, I should be able to stop and start my app in the hook perhaps with the help of a helper function.

**Comment by bodymindarts** [comment]
@reset and I had a discussion about this.
Currently the process is being restarted and then the `reconfigure` hook is run.
We were considering renaming the `reconfigure` hook to `after_reconfigure` to better reflect the current way that hook is being used and add an additional mechanism to differentiate between a `restart` or `reload` type of mechanic for dealing with the process.

**Comment by reset** [comment]
I'm going to provide some details in this thread which @bodymindarts discovered through attempting to implement this and then were relayed to me by @eeyun.

A simple hook to send a reload command or run a binary to communicate to a PID is definitely in the scope of how the supervisor works right now, but if any sort of process draining/swapping needs to happen where the PID will change, we don't have a way to represent that just yet. The supervisor starts a process as a child of itself and attempts to restart it if that PID ever goes away. Simply put, there's no way for a process' PID to change as part of the application's life cycle.

In some near future work we're going to be reworking how we start processes so they are no longer a child process of the supervisor. We'll be creating another process - the launcher - which the supervisor communicates with to spawn a child process. This will allow us to upgrade the supervisor without needing to restart PID 1. This also means that the supervisor will now be supervisoring processes a little bit differently, it'll need to read the PID file from the svc directory and then watch the process table/wait for signals from the launcher which it'll proxy to the supervisor.

By writing to the PID file in the svc directory from the reload hook with the PID of the newly spawned process, this might mean we just get PID swapping for free. What do you think?

**Comment by bodymindarts** [comment]
I have split out the `PID` handling issue into its own ticket https://github.com/habitat-sh/habitat/issues/1838.
https://github.com/habitat-sh/habitat/pull/1837 handles the default case.
