### ISSUE TITLE
[RFC] Graceful departure from cluster

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1812]
Typically schedulers (eg: nomad, k8s, mesos) have a way of putting a node into a `drain` state which will trigger the scheduler to redistribute workload away from that node to allow for cluster downsizing, maintenance or updates.

Since running clustered apps on such schedulers is a core use case of habitat we should also provide a way to gracefully leave a habitat ring and provide a hook for services to perform cleanup prior to shutdown.

The implementation of this use case should address the bug observed https://github.com/habitat-sh/habitat/issues/1711

**Comment by adamhjk** [comment]
See also #1994

**Comment by reset** [comment]
Closing in favor of #1994, thanks for the bug report @bodymindarts!
