### ISSUE TITLE
pkg_exports values are not gossiped when updated on  hab config apply

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#1816]
I have an nginx service that uses `pkg_exports` for the port it listens on, and an haproxy service that binds to the nginx service group and consumes the port value in its configuration.

When adding/removing nginx services, the haproxy configuration updates as expected.  However, when running `hab config apply nginx.default ...`,  the nginx services in the group restart on their new port, but haproxy doesn't update its configuration until nginx is stopped/started. 

Looking at the `/butterfly` endpoint after the `config apply`, it still contains the original value.

I have the following repo with a test case to reproduce:  https://github.com/smacfarlane/hab-bind-example

**Comment by mwrock** [comment]
Should be fixed by #2190
