### ISSUE TITLE
Rendering config is failing

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1818]
With current master
```
$ hab sup start core/postgresql --group reference
hab-sup(MR): Butterfly Member ID 882060ebb5c14e5e8d53cafe367226c4
hab-sup(SR): Adding core/postgresql/9.6.1/20170215221136
hab-sup(MR): Starting butterfly on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
postgresql.reference(SR): Failed to write service configuration: hab-sup(ER)[src/error.rs:379:8]: Failed to encode TOML: values must be emitted before tables
```

Could this be due to @fnichol recent upgrade to the serialization libs?

**Comment by smurawski** [comment]
I was able to replicate @bodymindarts and am looking into it.

**Comment by fnichol** [comment]
@bodymindarts Looks like @smurawski and I have a lead on this--a post 0.3.0 commit in the toml crate ([source](https://github.com/alexcrichton/toml-rs/commit/fba7778782193f0d0899f82d6b322da59a9044a0)) that addresses the issue.
