### ISSUE TITLE
Setup SumoLogic to aggregate Builder service logs

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1841]
### The Story
As a developer of the Builder service, I need a way to centrally access builder application logs and receive slack/email notifications when certain regex patterns are hit, so I can easily search and inspect application log output in a distributed builder installation and receive notifications on warnings and errors

### Criteria of acceptance
I can navigate to a log aggregation service in my browser and tail all application logs
I can use that log aggregation service to set up alarms for particular regexes
I receive a notification on error/warning via Slack, Email, or both when a warning/error happens in a log

**Comment by rhass** [comment]
@eeyun We are looking at LogDNA right now, and it's pretty slick. May be worth looking into for your team as well.
