### ISSUE TITLE
hab supervisor 'at once' update strategy doesn't seem to work as expected

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1842]
We ran into this at a customer working session.
Starting a hab application with hab sup using the 'at once' upgrade strategy does not work as expected.

Expected: hab sup checks periodically (~ 60 secs?) for new versions of the application, and upgrades to the new version.

Observed: hab sup does not upgrade the application even when new versions are published to the depot.

**Comment by reset** [comment]
This is fixed in master
