### ISSUE TITLE
Configure a Listener for Builder Operational Metrics

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1844]
### The Story
As a developer of the Builder service, I need to have an instance of a listener that can collect operational metrics and (eventually) forward them on to a permanent back end.

### Criteria of acceptance:
The Docker-based builder dev environment should include a statsd-compatible listener, and the service environments should be configured to point to that listener
The acceptance and production environment Terraform scripts should include a statsd-compatible listener, and the service environments should be configured to point to that listener

**Comment by christophermaier** [comment]
Update: We have metrics listeners in our acceptance and production environments, and builder services are configured to use them.

However, they are [DogStatsD](https://docs.datadoghq.com/developers/dogstatsd/) clients, and not pure StatsD clients, so there may be additional work to do if we want to add a metrics backend into our development environment

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #285](https://github.com/habitat-sh/builder/issues/285) via [**ZenHub**](https://www.zenhub.com/)
