### ISSUE TITLE
View Builder Operational Metrics in Ops Dashboard

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1845]
### The Story
As a Developer of the Builder service, I need to be able to view operational metrics in a easy to use Dashboard.

### Criteria of acceptance:
The operational metrics that are being aggregated by a listener in the acceptance and production environments should be forwarded on the internal Chef Ops backend
The network traffic between the hab environments and the Chef backend should be encapsulated in a VPN
The operational metrics should be easily viewable on the Chef Ops dashboard

**Comment by elliott-davis** [comment]
Closed by sumologic/datadog dashboard
