### ISSUE TITLE
Extend hab-spider to be able to do builds

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1849]
As a Habitat engineer, I want to be able to build a package and the chain of packages that depend on my re-built package easily. Until we get the full builder service up and running, I'd like to be able to do this with a command line app.

### The Story
This story is about extending the functionality of hab-spider to also trigger build commands, thus saving hab engineers manual effort when re-building packages.

### Criteria of acceptance
1. hab-spider should have a command to build a package as well as the packages that depend on it
2. There should be a confirmation required from the user before the build(s) start
3. There should be some reasonable limit to the # of builds.

**Comment by chefsalim** [comment]
We don't actually need to do this, and it will be redundant to the overall builder functionality.
