### ISSUE TITLE
Add reverse dependency graph to builder depot

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1850]
As a Habitat engineer, In order to provide automated building functionality, I need to be able to access package reverse dependencies in the builder depot in order to automatically schedule builds.

### The Story
This story is a spike about integrating the reverse dependency graph code into the builder depot.

### Criteria of acceptance
1. The builder depot is able to build the dependency graph on startup
2. The builder depot logs the graph stats to console at startup.

**Comment by reset** [comment]
This has taken form in builder-core and builder-scheduler crates
