### ISSUE TITLE
Use Postgres to build package graph

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1851]
As a Habitat engineer or builder service user, I want to be able to build or query the package reverse dependencies without waiting a long time for the graph to be built from the file system scan.

### The Story 
This story is about speeding up the package graph building by using the new Postgres DB instead of scanning the file system.

### Acceptance criteria:
1. The package graph is built via Postgres queries
2. The time to build the graph is reasonable and much faster than the fs scan time.

**Comment by chefsalim** [comment]
This is already done (different card).
