### ISSUE TITLE
Processes are restarted several times on rolling updates

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1853]
When performing a rolling update (maybe at once too), after the package updates services are restarted 2 to 3ish (sometimes more) times. They should just be restarted once.

**Comment by rsertelon** [comment]
I used the rolling strategy not so long ago and couldn't reproduce this behavior.

For me it worked properly.

**Comment by christophermaier** [comment]
Need to investigate further.

@eeyun do you mean each individual service restarted multiple times by itself, or that everything seemed to restart as each member of the group updated?

**Comment by dmccown** [comment]
We need to confirm if this is still an issue.
