### ISSUE TITLE
Builder: GitHub Webhook

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1857]
As a Builder user, I want to choose a Git branch to monitor for changes and, when a change is made, automatically issue a build and publish a new artifact to a depot, so I always have a package for the latest HEAD of the given branch

### Criteria of acceptance
A project can be configured to watch a branch (master by default)
Pushing a commit to the watched branch automatically builds and uploads a new `.hart` to the depot

**Comment by reset** [comment]
Closed by #3442
