### ISSUE TITLE
Fix the release process

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1862]
As a Habitat engineer, I want a fully automated release process so that releasing Habitat doesn't consume a full day of my time.

### Acceptance criteria:
1. Whenever a pull request is merged to master, we should end up with unstable builds of hab for Linux, Windows, and Mac all pushed up to the unstable repo on bintray.

**Comment by smith** [comment]
Will this include studio images in dockerhub as well? I currently don't use unstable builds because they won't start the corresponding studio because the image doesn't exist.

**Comment by smith** [comment]
Does this not actually work then? https://github.com/habitat-sh/habitat/blob/5c8a0282b5a5dab5cf0b307dd898a657b62e23eb/components/hab/static/template_plan.sh#L163-L170

**Comment by raskchanky** [comment]
@smith Right now, this doesn't cover studio images, just unstable builds.  I don't think it would be too hard to add studio images to the linux build.  I'm not sure what the current status of the windows studio is.  @mwrock or @smurawski would know.  And the mac studio isn't even a thing yet.

**Comment by reset** [comment]
@smith I think maybe the link you provided is off - it's not to do with studios at all. Are you also wondering about `pkg_binds_optional`? If so, yes, it should work!

**Comment by smurawski** [comment]
@raskchanky @smith building the docker image will require us to publish, and have the image assembly pull in, new .harts for linux hab cli/studio/other deps.  Right now, the unstable builds are only the CLI bits, unpacked from their .hart and published to bintray.  

It's definitely doable, it's just a matter of how much time do we want to invest in it before we have channels available (which then make this trivial).

To get around the issue of what studio to pull, there is an environment variable - `HAB_DOCKER_STUDIO_IMAGE`, which I set to `habitat-docker-registry.bintray.io/studio:latest`, which makes the current Windows and Mac hab CLI pull the current studio image.  You don't have the new CLI in the studio image, but it's a step in that direction.

**Comment by reset** [comment]
This was completed and it was a huge home run - we released 0.20.0 with almost NO problems!
