### ISSUE TITLE
Channel API Docs

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1863]
As a Habitat builder user, I channels to exist in the depot so that users have more choices about how they want to consume my packages.

### The Story
Channels exist right now but don't really work. There has been a lot of discussions around how channels should work. We need to come up with an API for channels in written form so we can move ahead with the implementation.

### Criteria of acceptance
Have a doc that outlines what channels are and how they should work in detail that's sufficient enough to drive an implementation.

**Comment by rsertelon** [comment]
@eeyun is there still work to be done here? Channels are implemented and seem to work just fine :)

**Comment by raskchanky** [comment]
Not only is there an implementation, but there's also API docs https://github.com/habitat-sh/habitat/blob/master/components/builder-depot/doc/api.raml#L400
