### ISSUE TITLE
TOML parsing of config files fails with toml-rs 3.0

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1865]
The latest version of toml-rs has changed the way the 'get' function works on TOML Values. This means that the way we have implemented the ParseInto trait for TOML types is no longer working - it silently fails to parse table values.

Also opened the following issue in toml-rs: https://github.com/alexcrichton/toml-rs/issues/154

**Comment by reset** [comment]
This has bee solved in master
