### ISSUE TITLE
Research multi-service Supervisor design

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1866]
This is a timeboxed research task which is focused on answering:
* What should the user experience look like (files, user commands, etc)?
* Are there any design gotchas that paint us into a corner?
* What are other ideas and designs worth stealing?
* What is the first logical place to start in code?
I'd like to spend no more than a day's worth of time on this and move into code immediately afterwards

**Comment by reset** [comment]
This was released in 0.20.0
