### ISSUE TITLE
Add pkg_bind_required and pkg_bind_optional feature to plan

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1868]
We define a producer contract in the form of pkg_exports and we need to create the consumer contract to enable a "duck-typed" polymorphic relationship between two services connecting together.
We will do this by adding two new overidable variables to our plan syntax
* pkg_bind_required
* pkg_bind_optional
This will allow us to connect to `core/redis`, `chef/redis`, or anything which looks like what we expect

**Comment by smith** [comment]
Does this not actually work then? https://github.com/habitat-sh/habitat/blob/5c8a0282b5a5dab5cf0b307dd898a657b62e23eb/components/hab/static/template_plan.sh#L163-L170

**Comment by reset** [comment]
@smith totally! We just were moving our board and we had some things we never cleared out - closing this one ;)
