### ISSUE TITLE
Upload/Download Windows Packages from the Depot

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1869]
This is the last piece necessary for a releasable windows MVP. While there is a pending data migration that could incur lost or "double" work in regards to the windows work, I'd like to staert looking at this now. Perhaps lost work will be very minimal? Not sure.

### Acceptance Criteria:
1. Build a windows package that has an accompanying bash plan
2. Upload the package to the depot
3. Install the package both on windows and linux
4. Each platform should get the release intended for its target

**Comment by mwrock** [comment]
fixed via #1835
