### ISSUE TITLE
Fix zmq crate compile in hab-sup windows plan on system w/o vs 2015 installed

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1872]
I recently reconfigured my personal laptop removing all vs 2015 installs to make way for the latest 2017 RC. After doing this, I get errors in the supervisor plan when it compiles the zmq crate.

mwrock Matt Wrock added a comment - 15/Feb/17 9:20 AM
ends up the main problem here was my PATH. ChefDK adds the msys2 tools which was causing problems. Building in a studio fixed that but I did catch a small bug that I had fixed locally and never commited.

**Comment by mwrock** [comment]
fixed
