### ISSUE TITLE
Package updates restart old package and not the updated one

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#1873]
The updater is triggered and does pull down the new package but after restarting the service, it continues to run the older package. Perhaps due to the fact that the updater dies? Here is the output:
hab-sup(SU): Updating from core/habitat-aspnet-sample/0.2.0/20170214142640 to core/habitat-aspnet-sample/0.2.0/20170214143216
habitat-aspnet-sample.default(SV): Stopping...
habitat-aspnet-sample.default(O): Application is shutting down...
hab-sup(SV): habitat-aspnet-sample.default - Shutdown method: Graceful Termination
hab-sup(SV): habitat-aspnet-sample.default - process 8236 died with exit code 1
hab-sup(SV): habitat-aspnet-sample.default - Service exited
habitat-aspnet-sample.default(SV): Starting process as user=mwrock, group=
habitat-aspnet-sample.default(O): RUN: pkg path is /hab/studios/dev--habitat-aspnet-sample\hab/pkgs\core\habitat-aspnet-sample\0.2.0\20170214142640
habitat-aspnet-sample.default(SU): Service Updater worker has died ; restarting...
habitat-aspnet-sample.default(O): Hosting environment: Production
habitat-aspnet-sample.default(O): Content root path: C:\hab\svc\habitat-aspnet-sample\var
habitat-aspnet-sample.default(O): Now listening on: http://*:8090
habitat-aspnet-sample.default(O): Application started. Press Ctrl+C to shut down.

**Comment by mwrock** [comment]
fixed.
