### ISSUE TITLE
Transitive dependencies not added to path

### ISSUE THREAD

**Issue by igalic** [habitat-sh/habitat#1895]
In `hab` version 0.17.0 and 0.18.0 transitive dependencies are not added to the path of the build.
Example plan.sh:
```bash
pkg_name=app
pkg_origin=me
pkg_version=0.0.1
pkg_source=nosuchfile.tar.gz
pkg_shasum=TODO
pkg_build_deps=(core/composer)
pkg_deps=(core/php)

do_download() { :; }
do_clean() { :; }
do_unpack() { :; }
do_verify() { :; }
do_strip(){ :; }
do_check(){ :; }

do_build(){
  cp -vRap "$PLAN_CONTEXT/../source/." "$HAB_CACHE_SRC_PATH/$pkg_dirname"

  mkdir -p logs
  composer install
}

do_install(){
  mkdir "$pkg_prefix/srv"
  cp -vRap "$HAB_CACHE_SRC_PATH/$pkg_dirname/." "$pkg_prefix/srv"
}
```

in this plan, we have `pkg_build_deps` on [`core/composer`](https://github.com/habitat-sh/core-plans/blob/master/composer/plan.sh), which has a `pkg_deps` on `core/git`. However, when executing `composer install`, we see warnings that `git` cannot be found. indeed `attach`ing to the build shows that, too.

**Comment by smacfarlane** [comment]
@igalic It looks like the wrong variable is being referenced inside the loop here:

https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L1597-L1601
