### ISSUE TITLE
add link to the core-plans

### ISSUE THREAD

**Issue by Sgtpluck** [habitat-sh/habitat#1900]
Currently, there seems to be only one buried link to the core-plans depot. Please add something more prominent to increase discoverability.

**Comment by eeyun** [comment]
@Sgtpluck Thanks for opening this issue. We definitely have some usability concerns. Can you clarify if you are referring to the repo in github or app.habitat.sh?

**Comment by Sgtpluck** [comment]
@eeyun I was referring to the github link, (wanted to look at the code of some of the core plans) but I also didn't even know about the one in app.habitat.sh, so I would say that one is also not particularly discoverable?

**Comment by tashimi** [comment]
We have done a lot of work recently to raise visibility of core plans, so I'm going to close this out. Let me know if you have more ideas for how to improve!
