### ISSUE TITLE
Regression 0.18.0 - Binding Config Fails To Populate ServiceConfig For Templates

### ISSUE THREAD

**Issue by smurawski** [habitat-sh/habitat#1907]
When running a service that exposes configuration (via `pkg_exports`), those values are not available to services that bind in 0.18.0.  They were in 0.17.0.

Binding config from 0.17.0 supervisor.

Binding config from 0.18.0 supervisor.

The relevant section - 

https://gist.github.com/smurawski/c1f3d216e4f9bae90a5f49c65a482c83#file-0-17-0-toml-L46

and 

https://gist.github.com/smurawski/c1f3d216e4f9bae90a5f49c65a482c83#file-0-18-0-toml-L117

The linked gist also contains a .kitchen.local.yml to recreate the problem with test-kitchen and kitchen-habitat.  https://gist.github.com/smurawski/c1f3d216e4f9bae90a5f49c65a482c83#file-kitchen-local-yml

**Comment by reset** [comment]
@smurawski I think this has this been fixed, can you confirm?

**Comment by smith** [comment]
I originally reported this to @smurawski and can confirm it's working in 0.20.0

**Comment by reset** [comment]
@smith thanks man!
