### ISSUE TITLE
Bug fix in Hab CLI setup instruction: GitHub access token scope missing

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#1913]
There are two required GitHub access token scope: `user:email` and `read:org` (see the doc: https://www.habitat.sh/docs/share-packages-overview/).
But in the CLI setup instruction (when running `hab setup`), there is only one `user:email` (see the screenshot below).
![pasted image at 2017_03_06 01_41 pm](https://cloud.githubusercontent.com/assets/9401459/23631937/e6c36504-0274-11e7-9213-8bbf3f201106.png)
We need to add the `read:org` in the CLI setup instruction.

**Comment by rsertelon** [comment]
Hi, it seems this has been done (see https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/cli/setup.rs#L121)

**Comment by tashimi** [comment]
![tenor-124615657](https://user-images.githubusercontent.com/719646/31057265-cc4318a4-a694-11e7-88fc-c4718971a06b.gif)
