### ISSUE TITLE
Allow specifying filename with `hab pkg binlink`

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#1922]
Right now if I do `hab pkg binlink core/ruby/2.3.0 ruby`, I get a binlink called /bin/ruby. If I then do `hab pkg binlink core/ruby/2.3.1 ruby`, that one gets overwritten.

What I would like to do is:

```
hab pkg binlink core/ruby/2.3.0 ruby --dest-file ruby230
hab pkg binlink core/ruby/2.3.1 ruby --dest-file ruby231
```

so I can have multiple versions.

**Comment by lamont-granquist** [comment]
it'd be kind of nice if hab pkg automatically tracked these as the packages were installed without having to manually issue binlink commands.

again the idea is that without having to binlink into a directory you could insert into your $PATH a directory which would track the latest ruby-2.3.1 and which would track the latest ruby version overall.
