### ISSUE TITLE
habitat.sh should have a search bar at the top...

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/habitat#1923]
I remember some time ago there was a link to search habitat packages on the main page (habitat.sh).  There does exist one at the bottom.  Recommend to have a link or a search bar at the top like most sites normally do when you want to search for such items.

**Comment by eeyun** [comment]
@bdangit Theres definitely a usability concern here. Thank you for opening this issue. I think for now we are going to close this out as what we really _want_ to do to achieve this accessibility is to add a new link, or something like that to the home page that clearly redirects users to the depot.

**Comment by bdangit** [comment]
:thumbsup:
