### ISSUE TITLE
RFC: have a flag to advertise service groups on local network using multicast DNS or similar

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#1939]
(This might be more of an RFD (Request For Discussion). Full disclosure, I'm not sure if this is a good idea, but I keep thinking about the sharp edges gossip ring setup has for new users.)

What if we allowed Supervisors to find each other using MDNS (this would certainly be a non-default option as MDNS can be quite noisy). The thoughts I've had so far go something like:

```
hab sup start <origin>/<app> --group <group> --mdns
```

As the first Supervisor starts, it uses it's namespace to construct and advertise an MDNS record for itself:
```
0-<app>-<origin>-<group>.local
```

Later Supervisors 'guess' the MDNS name the first Supervisor and try to use that name as their gossip `--peer`:
```
hab sup start <origin>/<app> --group <group> --mdns
hab sup start <origin>/<app> --group <group> --peer 0-<app>-<origin>-<group>.local
1-<app>-<origin>-<group>.local
```

**Comment by rsertelon** [comment]
This is similar as what is written in #849

**Comment by elliott-davis** [comment]
Closing as a duplicate of #849
