### ISSUE TITLE
Specify target path in `components/hab/install.sh`

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1945]
In order to complete https://github.com/habitat-sh/habitat/issues/1896 we need `components/hab/install.sh` to accept an install target path either as an environment variable or a cli option since homebrew has its own way of managing a directory structure to its installed packages.

**Comment by fnichol** [comment]
I suppose we could honor a `FS_ROOT` environment variable for the non-Linux cases (i.e. maybe only Mac?). In Linux we already honor `FS_ROOT` which is only for setup/install (not for runtime) like if you have a mounted disk that will reboot into a root/boot drive. Would that be helpful?
