### ISSUE TITLE
Document "blueprints" (real name TBD) Feature Usage

### ISSUE THREAD

**Issue by rhass** [habitat-sh/habitat#1951]

**Comment by rhass** [comment]
WIP: https://gist.github.com/rhass/7e4c7ade90539b8a97356b90748fb183

**Comment by rhass** [comment]
This is ready for review! :smile:

**Comment by mhedgpeth** [comment]
Have you considered making the terminology a bit more domain specific?

I.e.:

builder = how things get built
for example:
builder = java-maven-tomcat

A builder could also be:
builder = bash

Which is what it is now

You could also have:

source_retriever = github
github_source_url = https://github.com/mhedgpeth/cafe
github_branch = master
github_revision_id = 438290fjdklsafdj;afdsa

I think the product should "feel" like blueprints are a first class, default citizen. Which means you call it what it is in a DDD sense, not add a concept/metaphor (which is what you do when you add on to an existing domain language)

**Comment by adamhjk** [comment]
What we have is a single syntax for writing plans on a given platform, written in the native scripting language of that platform.

We then provide `scaffolding` for as many different kinds of applications as you want - these are published as normal habitat packages, making it easy to ship new scaffolding types. 

What's important here is how the experience degrades - you need to be able to go from a no touch, fully declarative experience, to one that is "normal go18, but we use..." by simply overriding a callback. This is in contrast to writing a full DSL - what we learned early in the development of habitat is that for people who are already used to Chef, it feels great. But the abstraction actually doesn't buy you much - when we got rid of the DSL, you started being able to cut-and-paste directions from the upstream into the packaging system itself, and given the artifact as immutable, you don't need much of the behavior you do in something like Chef.

**Comment by reset** [comment]
We've got the initial docs done and additional improvements coming down the pipe, gonna close this one out for now in favor of what is on our tracker
