### ISSUE TITLE
Need target/shell specific hooks

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#1952]
Currently the supervisor will run hooks using the interpreter appropriate to the package target. While it is straightforward to writye bash and powershell plans for the same service, it is not for hooks because they currently have no extension.

We should allow hooks to have an optional `.sh` or `.ps1` extension in order to allow a single service to have different hooks for different targets.

**Comment by eeyun** [comment]
Hey @mwrock is this still something we want to get community feedback on? Or is this something that you're actively pursuing?

I know it's come up once before and I think it has the possibility of being a breaking change but if you have any new perspective on this issue let me know!

**Comment by mwrock** [comment]
Funny I had almost forgotten about this until I bumped into the mysql plan on windows about an hour ago and realized this needs to happen. Lets keep this open but it does not necessarily need to remain an "RFC". I think we can settle approach more informally.

**Comment by rsertelon** [comment]
I've seen the announcement on slack, so here I comment.

I agree that it would be nice to have two targets available for one package and as @mwrock says, it's easy for the plan files as it is. I think it would be a simple, yet effective solution to add an extension that would allow for having hooks for different targets.

However, small question: does habitat plan (haha) to support other archs than windows/linux? If we have, for example, a macos target, it could use .sh files, might they be different between linux/macos?

**Comment by mwrock** [comment]
This is coming up more and more often. Currently we have to separate `plan.ps1` and `plan.sh` that include hooks into entirely separate plans. Also note that another benefit of supporting `.sh` or `.ps1` extensions for hooks is a better editor experience. Many editors will discover the scripting language and properly highlight the syntax based on extension.

**Comment by mwrock** [comment]
BTW: Anyone wanting a hacked workaround you can omit individual hook files from your plan repo and have your plan directly write them. So for example a `plan.ps1` would:
```
function Invoke-Build {
  @"
Set-Location {{pkg.svc_path}}
if(Test-Path var) { Remove-Item var -Recurse -Force }
New-Item -Name var -ItemType Junction -target "{{pkg.path}}/www" | Out-Null
"@ | Out-File "$PLAN_CONTEXT\hooks\init" -Encoding ascii
}
```

Your `plan.sh` would include the bash equivalent.

**Comment by smacfarlane** [comment]
Another possible work-around is to create  `hooks.sh` and `hooks.ps1` directories and as part of the build process, and either rename to `hooks` to let plan-build copy the hooks to the artifact for you, or do the copy as part of your install phase.

**Comment by smacfarlane** [comment]
This is also partially solved by [plan variants](https://github.com/habitat-sh/habitat/pull/5345)  but you do need to know some implementation details (below) to make it work so I view this as more workaround than solved.

plan-build will prefer loading a "variant" plan if it exists, so you _could_ create an `x86_64-windows` directory that contains all hooks,config,the plan.ps1 and any supporting materials. The catch here is that plan-build expects a `plan.ps1` in the root of your Plan, so you would have to create an empty plan.ps1 to "trick" it into loading a variant, which is actually the default.  You would end up with a directory structure like this:

```
.
├── hooks
│   └── run
├── plan.ps1 (empty)
├── plan.sh
└── x86_64-windows
    ├── hooks
    │   └── run
    └── plan.ps1
```

From a layout perspective, this is cleaner than the above workarounds,  but, again, it does require some knowledge of how plan-build works to understand why it works.

**Comment by mwrock** [comment]
However this ends up looking from a directory structure point of view, it would also be great if we could somehow support `.ps1` and `.sh` extensions. I've heard a number of offline requests for this with the desire to associate these files better with syntax highlighting in various editors. Perhaps this is a separate issue though.

**Comment by mwrock** [comment]
We already have an internal concept of "plan variant" where a plan can have a subfolder for a viariant platform. This is not in our public docs and mainly exists today to support a few core plans that need entirely different plan/config files for linux2. With some minor tweaks to this logic, we will now look for plan files in the following locarions:

```
    "$PLAN_CONTEXT/plan.ps1",
    "$PLAN_CONTEXT/habitat/plan.ps1"
    "$PLAN_CONTEXT/$pkg_target/plan.ps1",
    "$PLAN_CONTEXT/habitat/$pkg_target/plan.ps1"
```

The `$PLAN_CONTEXT` will "re-root" to the directory the plan file is located in. For backwards compatibility, if there is a plan in both the target folder and outside of the target folder. The target folder will take precedence.

I will file a separate issue for allowing extensions to the hook files.

**Comment by mwrock** [comment]
see #7535 for issue addressing hook file extensions.
