### ISSUE TITLE
Thoughts on binding apps to databases

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#1993]
Some thoughts regarding typical multi-tier webapp. They could turn into concrete issues depending on what we decide are best practices to deal with them.

1) Binding to database
When a front end connects to a backend database via a binding and the database could be in either `standalone` of `leader` topology the front end needs to know what ip to bind to.
In the `standalone` case (with just 1 node) it can use `{{bind.database.members.sys.ip}}` in the `leader` case it can use `{{bind.database.leader.sys.ip}}`. But how does the app know which topology the database is in? Should we expose the topology via `bind.database.topology`?
Another option would be to put the database behind an haproxy that takes care of forwarding to the correct database node. That way the frontend would connect to the proxy. This indirection doesn't really solve the problem because then the decision is with haproxy which node to forward to and it also brings another problem:

2) Providing connection info via bindings
When a front end wants to connect to a database it would make sense to expose a database name and user credentials via `pkg_exports`. This is currently no problem but there are 2 issues that don't have obvious solutions
  - If we have a clustered database that is behind an haproxy that forwards to the leader, the haproxy would be bound to the database and receive the exposed credentials but the front-end would not receive the credentials because it would only be bound to haproxy that doesn't forward the exposed config from the database.
  - Instead of having to 'forward the bound credentials' we could bind the front-end to 2 entities, a `database_address` (haproxy) and `database_credentials` (the database).

**Comment by adamhjk** [comment]
Are we worried about exposing credentials that way? The idea that the database tells the clients what the credentials are is kind of awesome, but it would be scary insecure right now - we would need to encrypt for the service group that's connecting, and no such credentials exist. 

I think we could fix 1 by providing a 'first' dynamic - where there is always something, and in leader it's the leader. We should expose topology by default.

**Comment by smurawski** [comment]
Related #2003

**Comment by smurawski** [comment]
Also #2002

**Comment by bodymindarts** [comment]
Closing this in favor of the tickets opened to deal with the individual issues.
