### ISSUE TITLE
expose topology in binding

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2003]
eg:
```
{{bind.database.topology}}
```
should show `leader|standalone`

**Comment by christophermaier** [comment]
Though not exactly in the form requested here, you can do this with the 0.56.0 release, as a result of some template data refactoring.

`{{bind.<SVC>.leader}}` will give you an object representing the leader, if running in a leader topology. If running in a standalone topology, however, this will be `null`, allowing you to use it in a boolean expression.

Until we have more than two topologies, this should work fine. At that point, we would probably need to express the information with boolean flags (e.g., `{{bind.<SVC>.is_leader_topology}}`, `{{bind.<SVC>.is_standalone_topology}}`), or introduce helpers that can do equality checks on strings.
