### ISSUE TITLE
Downloads are sometimes password protected

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#2013]
If you go to https://www.habitat.sh/docs/get-habitat/ and try to download habitat, sometimes you're prompted for an HTTP Basic username/password.

It works correctly for me in Chrome (macOS), Firefox (macOS), curl (macOS) and prompts for a password in Safari (macOS).  @smurawski reports that it prompts for a password for him in Chrome (Windows).  Liz reports that it prompts her for a password in Chrome (macOS).

I've emailed jFrog support about this but the inconsistent nature of it makes me unsure if it's a problem on their side.

**Comment by mwrock** [comment]
FWIW I found deleting my bin-tray cookies removed the auth prompt.

**Comment by raskchanky** [comment]
Deleting cookies didn't have any effect for me.  However, jFrog support emailed me back this morning and notified me that it has been fixed on their end.  I tested everything that was failing for me and it all works now.
