### ISSUE TITLE
Secure http_gateway

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2015]
Currently anyone can curl the http endpoint and access the entire config of all services without any kind of credentials.

**Comment by stevendanna** [comment]
Do we considered this fixed by:

- https://github.com/habitat-sh/habitat/pull/5874

We will also support TLS client-authentication soon:

- https://github.com/habitat-sh/habitat/pull/6172

**Comment by raskchanky** [comment]
@stevendanna Yeah good call, I think this is fine to close.
