### ISSUE TITLE
Need way to query required binds a package requires

### ISSUE THREAD

**Issue by mfdii** [habitat-sh/habitat#2021]
Much like you can query the default.toml of a package, we need a way to query the binds that a package requires. We also might want metadata regarding each bind, such as what keys are used from the bind and what the purpose of the bind is, eg "backend - This is the application service you want HAProxy to load balance. Use the IP of the members."

**Comment by eeyun** [comment]
We likely want to either extend the `pkg config` subcommand to expose this data or add another subcommand in the vein of `pkg binds`
