### ISSUE TITLE
Make working with Corporate SSL Firewalls easier

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/habitat#2026]
As a developer who works behind a firewall where the SSL traffic is inspected, I want `hab` to work with my own corporate cert.

Under linux environment, I am able to insert my own cert to get into a studio, by locating where the `$HAB_STUDIOS/$studio_name/hab/cache/ssl/cert.pem`.  However, once I attempt to do a build, `hab` is setting the SSL context to `cert.pem` that is located in `core/cacerts`.  I could overwrite this file after the first failure, but then this makes it tricky moving forward.

**Comment by bdangit** [comment]
Diving deep, there are at least 3 spots where I see the `cert.pem` and `cacerts.pem` are getting stored.

1. `$HAB_STUDIOS/$studio_name/hab/cache/ssl/cert.pem`: This is required on first initial building of the studio, and is used to download all the necessary studio dependencies.
2. Within the studio, dependencies use the cert stored from `$(pkg_path_for core/cacerts)/ssl/certs/cacert.pem`
3. From my base linux host, I have them at `/etc/ssl/certs/MYCOMPANY.pem`

One would think that your build dependencies should assume what you have setup in your `$HAB_STUDIOS` but it looks like this feature is only specific to linux.  And the commonality between mac and linux would be the use of `core/cacerts` package.  So no more assumptions.  It is interesting to see where certs are used all around and that it's literally everywhere.  

## Workaround
I had to manually overwrite the files inside `core/cacerts` and `hab` was happy to continue downloading dependencies.

## Longer Term Solution
I wish there was an ability to allow companies to insert their own `myorigin/cacerts` to be used instead of the `core/cacerts`.  This should probably get introduced when we start to build a studio.

**Comment by bdangit** [comment]
ah okay something I didn't know, but `export SSL_CERT_FILE=/path/to/your/company/cert.pem` will allow you to override the default of resorting to `core/cacerts` within the studio.

**Comment by bdangit** [comment]
This adds ability to install hab behind a firewall using the `components/hab/install.sh` script https://github.com/habitat-sh/habitat/pull/2597

**Comment by robbkidd** [comment]
This issue has come up in another environment. Whileexport SSL_CERT_FILE=/path/to/your/company/certchain/totally-trust-the-corporate-man-in-the-middle.pem`

**Comment by bdangit** [comment]
haha that almost sounds like what I had to do in my `hab` wrapper.  There should be an easy way.

**Comment by robbkidd** [comment]
I _think_ I'd like for `hab studio *` commands to detect the presence of `SSL_CERT_FILE` being set on the host and if set:

* copy the file at that path to the hab cache that gets mounted into the studio
* set `SSL_CERT_FILE` inside the studio session to that cached file path

I see hints in `http-client/src/lib.rs` about caching a `certs.pem` in the build of the http-client itself. I also see `/hab/cache/ssl/cert.pem` appear inside a studio. Are there code paths that can be updated to replace that cached `cert.pem` with a custom certs bundle when creating a studio?

That's a solution for the _build_ environment. If the _packaged services_ should be using that cert-chain, the cert.pem should _also_ get packaged up as `muhcompany/ourcerts` and packages set `SSL_CERT_FILE={{pkgPathFor muhcompany/ourcerts}}` in run hooks as appropriate.

**Comment by rsertelon** [comment]
@robbkidd the package `muhcompany/ourcerts` could be used as a build dependency to, couldn't it? I mean, I like a clear story for the CERT_SSL_FILE being picked up by the studio, but I don't see why for building it could not be included in the package itself as a dependency?

**Comment by bdangit** [comment]
Sorry cat made me close. :X

**Comment by Belogix** [comment]
We have just hit this issue (two years later) after trying and failing to install Chef Automate v2, which in turn uses Habitat under the covers. Chef Automate must be squarely aimed at the Enterprise and it is surprising to find that we still have to use these work around steps in our process. We are reaching out to Chef to see if this really has not been resolved and there is no better alternative.
