### ISSUE TITLE
Incorrect reference of Sitecore.Feature.Media in Sitecore.Foundation.Indexing.Tests project

### ISSUE THREAD

**Issue by agehlot** [habitat-sh/habitat#2039]
Hi Team,

There is a reference of Feature layer in Foundation layer which should not be there based on Helix principle. I think, somebody by mistaken add reference of Sitecore.Feature.Media in Sitecore.Foundation.Indexing.Tests project.

If my understanding is correct and this reference should be removed from Sitecore.Foundation.Indexing.Tests, please remove this reference and commit the code.

Thanks,
Arvind Gehlot

**Comment by smurawski** [comment]
Hi @agehlot 

I think you have the wrong Habitat project.  There is a SiteCore Habitat repository which I believe your issue  would be more appropriate for - https://github.com/Sitecore/Habitat
