### ISSUE TITLE
Validate `-bind <bind>:<svc>.<group>` before starting service

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2046]
Currently when starting the supervisor if a binding is required and none is provided via the `-bind` cli flag the supervisor doesn't start.
It is however possible to provide values to `-bind` that aren't services in the ring.
I have spent quite some time trying to figure out unexpected behaviour until I noticed that I just made a small typo in the `-bind` setting.

Ideally the supervisor would inspect the first census data it receives for the presence of a bound service and then fail with a helpful error message if the binding isn't present.

**Comment by adamhjk** [comment]
Is this validating not just the existence of a required bind, but that the service group you are binding too is present? 

If so, I think this would be a warning but not an error - since there are valid use-cases for setting up a service and essentially waiting for the binding to appear. We've talked in the past about waiting to start the service itself in this scenario. @fnichol has opinions, I suspect.

**Comment by bodymindarts** [comment]
Okay if this has been talked about then that I'm sure that is a reasonable position.

I would however strongly advocate a warning in that case since I just got burned by `--bind daemon::shield.default` and another time by another typo to `--bind` so I documented my annoyance.

**Comment by adamhjk** [comment]
I wasn't dismissing it - we should definitely fix it. :) I was more trying
to make sure I understood the badness.

**Comment by reset** [comment]
It's definitely something that I felt we should implement but skipped on my first pass. I think we should wait until our consumer's expectations (binds) are met by our producers (exports). The app shouldn't continue on it's lifecycle until they are

**Comment by fnichol** [comment]
Ah dang, I was considering adding some more validation when I touched the arg parsing around binds. We should certainly add better parsing and detection of values that will lead to a bad time and possibly warn if there is currently no service group present to satisfy the binding. @adamhjk is correct that we were thinking of blocking until the (required) binding was satisfied. In my mind's eye, this would look extremely similar to the "waiting for leader election to reach quorum" experience.

**Comment by reset** [comment]
Closed by #2076
