### ISSUE TITLE
New Tutorial for Building and Running Your own Application for the First Time

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2063]
<p>User story: I&#39;m a junior application developer. I&#39;ve finished coding my app, and want to get my app up and running. But I have very little experience building and running applications. After seeing how powerful Habitat could be in the Quick Start demo, I want to learn how I can build and run my own application.</p><p>How it should work: this new tutorial aims at helping the new Habitat users understand how Habitat builds and runs applications/services at a high level. It teaches the foundational knowledge necessary to use Habitat with a recommended happy path. At the same time, it should show the flexibility Habitat offers for customized build and runtime behaviors and integration with the developer workflow/tools.</p>

[See more on IDEA 017 New Tutorial for Building and Running Your own Application for the First Time](https://app.prodpad.com/ideas/17/canvas)

**Comment by nellshamrell** [comment]
This approach might be helpful for teaching the foundational knowledge necessary to use Habitat. https://blog.chef.io/2017/03/08/what-can-you-do-with-habitat-today/

**Comment by cnunciato** [comment]
This one's pretty old, so I'm partial to closing it (unless of course there's something new we should be building that I'm unaware of). @tashimi what do you think?

**Comment by tashimi** [comment]
Yup! :)
