### ISSUE TITLE
Supervisor exits and fails to clean-up running services

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#2065]
Steps to reproduce:

1.  Start the supervisor (`sudo hab sup run`)
1.  Load a service (`sudo hab sup load learn/mongodb`)
1.  Load another service, one that requires a bind, but don't specify the bind (`sudo hab sup load learn/national-parks`)

The supervisor raises an error and exits at this point.

1.  Unload both services (`sudo hab sup unload learn/national-parks ; sudo hab sup unload learn/mongodb`)
1.  Restart the supervisor (`sudo hab sup run`)
1.  Reload MongoDB (`sudo hab sup load mongodb`)

MongoDB fails.  

Cancel the supervisor, check running habitat processes and see that mongod is still running.  

Was it not shutdown cleanly when the supervisor exited?

Killing the mongod process and restarting everything works.

A screen cast of the issue can be found here - https://youtu.be/64Ql6hDWhxY

**Comment by fnichol** [comment]
Thanks for the repro! Yes, agreed, this is a bug which was introduced in 0.20.0. We will need to fix this up for sure by pushing these checks into a concern of a Service (and not just the Supervisor)
