### ISSUE TITLE
Export / Run multiple services in 1 container

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2086]
Now that the multi-service feature has landed it would be great to support exporting and running multiple services inside a container so that we can have side car processes for eg. backups working.

currently the `/init.sh` script execs to the hab supervisor so trying to:
```
docker run && docker load <origin>/<pkg>
```
Errored (it doesn't accept the `&&` as another command.

@fnichol do you have time soon to discuss this?

**Comment by bodymindarts** [comment]
FYI I have found a workaround for my current usecase (starting a side car process for backups)
I have found I can run `hab service load <origin>/<pkg>` in the `hooks/init` script of the data service I want to backup.

**Comment by fnichol** [comment]
As of #3213, the Docker exporter will take one or more Package Identifiers and/or Artifact files and can now contain multiple services. For the time being the behavior is that the first "service package" that is provided by the calling user will be the default service to run if the Docker container is started with default args.

In addition, the composite package work in #2902 should make the pattern of running closely related services much easier to express.

Given both of these additions (one current and one imminent), I'm going to close this issue out. If anyone disagrees or I've misunderstood the intention behind this issue, please do reopen.
