### ISSUE TITLE
`hab sup load` does not allow `--config-from`

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2104]
In an 0.20.0 studio:

```
[14][default:/src:0]# hab sup load core/postgresql --config-from=/src/postgresql
error: Found argument '--config-from' which wasn't expected, or isn't valid in this context
```
Expected behavior is to allow and use this flag.

**Comment by bodymindarts** [comment]
Is it possible that https://github.com/habitat-sh/habitat/pull/2098 has already fixed this @fnichol?

**Comment by smith** [comment]
> Is it possible that #2098 has already fixed this @fnichol?

This should fix it for `hab start` but not `hab load`.

**Comment by reset** [comment]
Now that I'm back I've had some time to think about the flow for iterating on multiple packages within the same studio. I think this is a two part fix to pushing this experience over the finish line:

1. The existing documentation needs to be updated to include how to iterate on one or more services within a studio. We've got a single paragraph talking about the `--config-from` flag but it doesn't do you any favors explaining how you could start more than one
1. We should consider starting a supervisor without services as part of the studio itself by daemonizing `hab sup run` and dumping the output to a log file that a developer can tail. I think that this will make the feeling of using `hab start` a bit more inviting to the changes we recently made. The behaviour of `hab start` changes depending on if there is a supervisor running or not. The first call to `hab start` will start a supervisor and output to the current shell. Any additional call to `hab start` will start an additional transient service in that supervisor. If we were to start the supervisor for the user then every call to `hab start` will have the same feel

**Comment by mwrock** [comment]
Yeah I'd also add including acknowledgement to the `hab start` call so the user understands that something just happened. I have noticed that when calling `hab start` against an already running supervisor, the command simply returns with no output while one can indeed see activity in the console running the supervisor.

**Comment by reset** [comment]
Gonna close this out in favor of the work happening in #2131. Thanks for the conversation @smith and helping us make this experience better!
