### ISSUE TITLE
hab sup status command

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2118]
When using the `hab sup` commands, it's often necessary to know information about a service. Including:

* Is it running?
* How long has it been running?
* What's it's PID?
* What child processes are it running?

This issue specifies some attributes of a `hab sup status` command. Please discuss and modify as needed.

Running `hab sup status` should output a list services configured to run in a supervisor and show information about them.

Running `hab sup status $PKG_IDENT` should give the status of an individual service and exit 0 if the service is loaded, or exit non-zero if the service has not been loaded.

**Comment by mwrock** [comment]
@smith how crucial is the need to list child processes. I can certainly see the value, but its the one bit of info the supervisor does not curently store that is not trivial to obtain and differs on linux and windows. Its not super hard but if its not critical, I'd prefer to add it in a separate item.

**Comment by smith** [comment]
>  how crucial is the need to list child processes.

Not really crucial.

**Comment by mwrock** [comment]
fixed via #2170
