### ISSUE TITLE
hab command to generate "user" config

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2119]
Right now the ways to give initial configuration to a service are:

* `hab config apply` into a running supervisor
* `hab start` or `hab sup run` with `HAB_MYTHING="some toml"`
* Write a /hab/svc/mything/user.toml

The third one is the only one that does not use a `hab` command, and it's not documented. In addition, user.toml is the only exception to the expectation that users shouldn't need to be making changes to things in the /hab directories.

This could be a new command, or another use of `hab config apply`, except that it doesn't need a version number or service group, just a service name.

TOML can be given by a filename on the command line or from standard input. It would take that TOML and write it out to /hab/svc/mything/user.toml, so when that service starts it takes that initial config.

**Comment by bodymindarts** [comment]
How about `hab config init`.

**Comment by rsertelon** [comment]
`hab config init` does not seem really meaningful to me because we might want to use it several times for example.

What about `hab config override core/service path/to/toml.file`? This would convey the fact that any existing configuration will be replaced by the contents of target file.

**Comment by rsertelon** [comment]
Not sure we should reuse `hab config apply` for this similar but different use case.

`hab config init` conveys a "one time thing" message that I think might be misleading.

What about `hab config local /path/to/toml/file`?

**Comment by rsertelon** [comment]
@reset @christophermaier I think this might be part of the needed changes of the CLI API reported in the PR for the new sup ;)

**Comment by christophermaier** [comment]
This would need to be a command that would work over the control gateway, which would be possible, but different from any existing commands.

The UX would probably be the most important thing to sort out.
