### ISSUE TITLE
Investigate running windows services via habitat

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#2123]
In windows application development, it is very common to write back end services that are not hosted by a web service as a "windows service". Windows services are very similar to applications targetting linux and hosted inside of a service manager like systemd. One of the key differences with windows services is that the start/stop/pause logic is often compiled inside the service binary which may make decoupling the service application from the windows service manager very difficult. This difficulty may mean it is not so simple for a user to run their app in hab INSTEAD of the service manager. We should explore what it might look like to have the supervisor interact with the service inside of the service manager.

This card represents a spike to experiment with different approaches. The findings may lead to a significan windows supervisor refactoring, some small enhancements or simply documentation clarifications.

cc @mhedgpeth

**Comment by mhedgpeth** [comment]
@eeyun is this done? If so where is it documented?

**Comment by mwrock** [comment]
Hey @mhedgpeth I wrote a post on doing this at https://www.habitat.sh/blog/2017/12/Packaging-Windows-Services/. I'd love to address any feedback if you have any.
