### ISSUE TITLE
Review and update `Add Configuration` topic

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#2137]
- Add info on `pkg_exports` and `pkg_binds` and how the information on the `Add Configuration` topic ties into the `Runtime Binding` topic
- Review and clean up examples that use the `cfg.` prefix to address any consistency issues between the plan docs and the toml docs

**Comment by rsertelon** [comment]
@davidwrede Is this still something that needs to be done? Do you need help?

**Comment by davidwrede** [comment]
@rsertelon I think we can close this out. The [Runtime Binding](https://www.habitat.sh/docs/developing-packages/#pkg-binds) section of the docs has been significantly modified since this issue was opened to include info on `pkg_exports` and `pkg_binds`. 

Can't remember my specific thoughts on the second sub-issue, but if something triggers a memory, I'll open a new issue with more details.
