### ISSUE TITLE
Builder-scheduler service: provide API to support Explore view

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2143]
This is a work item for the builder services to provide an API that the depot UI can use for the Explore view.

**Comment by ryankeairns** [comment]
Particular items to start with might be 'Total core packages built' and 'Top dep' (which would indicate which packages are most often rebuilt/used). We may also look into 'Most recently rebuilt'... just tossing out some initial thoughts. I'm sure we could assemble a laundry list, but focusing on the Depot Explore page is probably a good focal point to get us moving.
