### ISSUE TITLE
svc_data_path should be configurable

### ISSUE THREAD

**Issue by ramonskie** [habitat-sh/habitat#2163]
it would be nice to make svc_data configurable
so when we want to use it in combination with other systems like bosh
we can set the data store to /var/vcap/data/ for example

**Comment by mwrock** [comment]
There is currently an `FS_ROOT` environmernt bvariable that can copnfigure the root of the svc path. We should document this to make it better discoverable.

**Comment by mwrock** [comment]
One can accomplish this using mounts, but we can certainly reopen this if those strategies do not adequately work.

**Comment by ramonskie** [comment]
the problem is with bosh
that it always mounts its persistent disk under /var/vcap/store

so i don't see an option that we can fix this with mounts

**Comment by tashimi** [comment]
We can look at this.

**Comment by tashimi** [comment]
@elliott-davis is +1 on this.

**Comment by themightychris** [comment]
Does creating a symlink at the `/hab/svc/myservice/data` path to wherever work? Semantic path+symlink always seemed like a good configuration layer to me for where things get stored
