### ISSUE TITLE
[builder-web] Build the new initial front page 

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2181]
When a user clicks "Explore" in the header, they should be taken to the new front page (https://chef.invisionapp.com/share/EU9BOXKF6#/screens/229781862) and have the ability to explore packages and see interesting information about: 
- popular packages (this can be curated at first, and dynamic later) 
- top dependencies (what package gets called the most? can be dynamic later if APIs not available now) 
- recently added (what packages just got added? can be dynamic later if APIs not available now) 

- Getting started with habitat & info video 
- Scaffolding information 
- Inspec and habitat information

**Comment by cnunciato** [comment]
@tashimi I think all we need to finish off this view are the getting-started video (it's just a placeholder graphic now), the list of items that should appear in the Top Deps and Recently Added boxes, and the links that should show up under scaffolding (if they're different from the ones here).

**Comment by cnunciato** [comment]
![image](https://cloud.githubusercontent.com/assets/274700/25820435/13d418c0-33e6-11e7-9b5c-426958e89c38.png)

**Comment by ryankeairns** [comment]
One additional tweak that Liz pointed out, change the orange bold link text to Titillium Web (instead of Montserrat Alternate)

**Comment by ryankeairns** [comment]
Awaiting the final list of packages, then we'll get this updated and out the door.

**Comment by ryankeairns** [comment]
Merged, just waiting for it to land in acceptance before closing this issue out.
