### ISSUE TITLE
[builder-web] Show build output from streaming logs 

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2183]
Streaming log output should be included in the builder-web UI so users can see the status of their builds.

This is a "current job view" that shows streaming log output when you click on an origin/package for more information. It includes information such as: 
- time running
- time completed 
- authored by 
- etc.

**Comment by reset** [comment]
Associated with #2024

**Comment by tashimi** [comment]
See also #2203, closed as duplicate but good user story.
