### ISSUE TITLE
[builder-web] [placeholder] add dynamic content for front page

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2184]
For https://chef.invisionapp.com/share/EU9BOXKF6#/screens/229781862, some of this data cannot currently be accessed via the builder API. We need to add those API endpoints and update the UI to render this data dynamically as it changes.

**Comment by ryankeairns** [comment]
@tashimi  Same here, are these updates to the Explore page still in scope for Pre-Neighborhoods?

**Comment by tashimi** [comment]
@ryankeairns I think this is a nice to have, we can manually update with interesting content for the meantime

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #20](https://github.com/habitat-sh/builder/issues/20) via [**ZenHub**](https://www.zenhub.com/)
