### ISSUE TITLE
[builder-web] Add build alerts to UI

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2185]
When a user has a package that has dependencies that have more recent builds than the user's most recent build of their package, the UI should show a visual cue to indicate that the user needs to take an action to rebuild their package and take advantage of this newer version. 

This will require API & front end work.

**Comment by ryankeairns** [comment]
@tashimi can we remove the Pre-Neighborhoods milestone from this issue (UI alerts)?

**Comment by tashimi** [comment]
@ryankeairns Sure, but let's create a follow up milestone because notifications is important and should be done short term (I would prefer to have it done by the end of October)

**Comment by ryankeairns** [comment]
Done, added an On Deck milestone.

**Comment by tashimi** [comment]
Fletcher would like to request a "Builder kicked off a build of xxx" in Slack

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #21](https://github.com/habitat-sh/builder/issues/21) via [**ZenHub**](https://www.zenhub.com/)
