### ISSUE TITLE
[builder-web] Add "harts" to UI 

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2186]
When a user finds a package or dependency that they want to bookmark, they should be able to click a "hart" icon that creates a list of favorites they can browse and edit later.

**Comment by ShalokShalom** [comment]
You mean a heart icon?

**Comment by rsertelon** [comment]
Could be the hab heart we see on slack ;)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #22](https://github.com/habitat-sh/builder/issues/22) via [**ZenHub**](https://www.zenhub.com/)
