### ISSUE TITLE
[web-ui] new top bar navigation and uniform dark theme styling

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2188]
Reorganize the web app to follow the new organization. 

Web app & builder UI should have an identical look and feel for navigation elements and theme.

Style all pages in the website & builder application site to follow uniform dark theme (including docs).

Mockups: https://chef.invisionapp.com/share/EU9BOXKF6#/screens/229568265_Habitat_Web_-_Blogs
Information Architecture: https://chef.invisionapp.com/share/XBBEYR4JH#/screens/230346156_HabitatIA

**Comment by tashimi** [comment]
The web app and the builder ui should map 1:1 with the header etc.

**Comment by ryankeairns** [comment]
I'll be tackling the www. side and Chris will handling app.
