### ISSUE TITLE
[web ui] Add new community content

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2189]
Add new community page organization & content

Mockups: https://chef.invisionapp.com/share/EU9BOXKF6#/screens/229568265_Habitat_Web_-_Blogs
Information Architecture: https://chef.invisionapp.com/share/XBBEYR4JH#/screens/230346156_HabitatIA

Specific features: 
 

- [x] Add & facelift blog 
- [x] Facelift community page 
- [x] Add Roadmap
- [x] Add github issue tracker (if possible, otherwise add link)

**Comment by ryankeairns** [comment]
Moved blog portion to a separate issue:
https://github.com/habitat-sh/habitat/issues/2336

**Comment by ryankeairns** [comment]
Chatted with Marketing about accessing the Events data and learned that it is managed via Wordpress. They provided the rss feed below, so it seems we'd have to parse that and wrap it with HTML elements... or something :)

https://events.chef.io/events/categories/habitat/feed/

**Comment by tashimi** [comment]
Prod Pad feedback portal: https://portal.prodpad.com/24539
ProdPad public roadmap link: https://ext.prodpad.com/ext/roadmap/0fe93038ea3ea1f8f4589ada044eaf0898658a83
