### ISSUE TITLE
[web ui] Add interactive run time demo

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2192]
Add an interactive CLI-in-the-browser run time demo. This can go live as soon as the content is done.

Mockups: https://chef.invisionapp.com/share/EU9BOXKF6#/screens/229568265_Habitat_Web_-_Blogs
Information Architecture: https://chef.invisionapp.com/share/XBBEYR4JH#/screens/230346156_HabitatIA

**Comment by davidwrede** [comment]
WIP code is being pushed up to `dw/interactive_CLI_update` branch.

**Comment by reset** [comment]
Closed by #2861
