### ISSUE TITLE
[builder-web] ReadMe in Package View

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2197]
When a user looks at an origin/package, if that origin/package has a ReadMe, that ReadMe should be displayed to provide information such as:
- what is the package
- who authored it 
- its contents
- how to use it (do you call it as a dependency of your application, or do you need to add additional plan & configuration to use it)
- its expected use
- scaling up/scaling down behavior
- clustering behavior (if available)
- what habitat topology it should use 
- what is the best update strategy for different deployments  
- how to monitor the health of the service at the application level 
- is an HA configuration possible? if so how

To-do
- [ ] Update the generated README with instructions for the additional items above (see #2571 )
- [ ] Add the README as a tab in the UI package view (this issue)

**Comment by ryankeairns** [comment]
We should also provide a link from the package view to the plan on github (regardless of whether it has a README).

**Comment by ryankeairns** [comment]
Related, we would also like to generate a templated README via `hab plan init` - see issue is #2571

**Comment by ryankeairns** [comment]
Prototype for a revised package detail view that includes README content.
https://chef.invisionapp.com/share/3ZBKYLQTW#/239684122_package_Detail_V2

**Comment by ryankeairns** [comment]
@tashimi FYI, here's the issue for adding READMEs in the web ui (that we discussed wrt UX priorities). There's a link to the prototype included here as well and it's currently in the Backlog.

**Comment by ShalokShalom** [comment]
THIS

**Comment by rsertelon** [comment]
#4077 shoud fix templated README generation :)

**Comment by ryankeairns** [comment]
Updated the description...
There are two parts to this effort - 1) add additional topics to the generated README #2571 and 2) display the README in the web app UI (this issue).

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #23](https://github.com/habitat-sh/builder/issues/23) via [**ZenHub**](https://www.zenhub.com/)
