### ISSUE TITLE
[web ui] Add "About Us" Page

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2200]
Add "About Us" page link to habitat.sh footer and "About Us" page. 

Mockup: https://chef.invisionapp.com/share/EU9BOXKF6#/screens/231393034_Habitat_Web_-_About_Us

(Make sure footer is uniform across habitat.sh and builder.habitat.sh)

**Comment by ryankeairns** [comment]
Closing as duplicate to #2405 which has further details. Copied this description to that issue.
