### ISSUE TITLE
Improve discoverability of release notes

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2202]
Can we add a link in the the [github release](https://github.com/habitat-sh/habitat/releases/tag/0.21.0) to the [release anouncement](https://forums.habitat.sh/t/habitat-0-21-0-released/322) in the forums. That would make it a lot easier to find  out whats happening for people who are new and don't know about the forums.

**Comment by tashimi** [comment]
Yeah for sure, I will add that to the release process doc. Good idea!

**Comment by tashimi** [comment]
Opened #2211

**Comment by reset** [comment]
Closed by #2211
