### ISSUE TITLE
Hard to dynamically calculate version

### ISSUE THREAD

**Issue by thommay** [habitat-sh/habitat#2212]
#2074 has eliminated the need for the `pkg_source` variable when building local packages, but `pkg_version` is still required and results in some funky dancing around, for example in `cacerts`.
When packaging a sinatra app, I've been running in to difficulties executing a ruby binary wrapper that's in my `pkg_bin_dir`:
```
dcob.default(O)[src/supervisor.rs:383:23]: /hab/svc/dcob/run: 11: exec: dcob: not found
```
I've updated my plan to use the same techniques as in `cacert` or `cargo-nightly`: https://github.com/chef/dcob/pull/22/files

and when building the package, the output from `build` correctly has the version as 0.1.1:
```
   dcob: Installed Path: /hab/pkgs/chef_community_engineering/dcob/0.1.1/20170502182018
   dcob: Artifact: /src/results/chef_community_engineering-dcob-0.1.1-20170502182018-x86_64-linux.hart
```

However, running `hab pkg env` still contains `dcob/_computed_in_a_function_below_`:
```
[11][default:/src:0]# hab pkg env chef_community_engineering/dcob
export PATH="/hab/pkgs/chef_community_engineering/dcob/_computed_in_a_function_below_/20170502182018/bin:/hab/pkgs/core/coreutils/8.25/20161208223423/bin:/hab/pkgs/core/ruby/2.4.1/20170424051947/bin:/hab/pkgs/core/acl/2.2.52/20161208223311/bin:/hab/pkgs/core/attr/2.4.47/20161208223238/bin:/hab/pkgs/core/glibc/2.22/20160612063629/bin:/hab/pkgs/core/grep/2.22/20161213233954/bin:/hab/pkgs/core/libcap/2.24/20161208223353/bin:/hab/pkgs/core/libtool/2.4.6/20161214014759/bin:/hab/pkgs/core/ncurses/6.0/20161213233720/bin:/hab/pkgs/core/openssl/1.0.2j/20161214012334/bin:/hab/pkgs/core/pcre/8.38/20161213233903/bin:/hab/pkgs/core/sed/4.2.2/20161208223647/bin"
```

**Comment by robbkidd** [comment]
Another use case is being able to call `git describe` to look up the current version from a git tag.

**Comment by tashimi** [comment]
Sounds like something we should sort out as part of the local build experience. Thanks for filing @robbkidd!

**Comment by eeyun** [comment]
Also @thommay ;)

**Comment by fnichol** [comment]
Glad to see this. I had this in my own "backlog" and have some thoughts about an implementation.

**Comment by fnichol** [comment]
Hopefully the combination of #2234 and #2235 will help this problem with a supported solution. I'm also hoping that the Scaffolding packages can take advantage by defaulting their `do_default_before()` build phase to:

```sh
do_default_before() {
  update_pkg_version
}
```

so that a Plan author packaging a Rails app (or similar) need only implement the `pkg_version()` function like so:

```sh
pkg_build_deps=(core/git)

pkg_version() {
  git describe --tags
}
```

or something like that.
