### ISSUE TITLE
Package identifier version comparison barfs on non-numeric versions

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2213]
We allow non-numeric pkg_versions, however the version comparison code currently expects a numeric version, and returns an InvalidPackageIdent.

fn split_version(version: &str) -> Result<(Vec<&str>, Option<String>)> {
    let re = try!(Regex::new(r"([\d\.]+)(-.+)?"));
    let caps = match re.captures(version) {
        Some(caps) => caps,
        None => return Err(Error::InvalidPackageIdent(version.to_string())),
    };

**Comment by eeyun** [comment]
I think this issue might be resolved and could have been re-opened accidentally or at least removed from accepted accidentally. @tashimi can you validate?
