### ISSUE TITLE
Remove `hab pkg exec` calls from Builder Plan hooks

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#2239]
This came up in #2238 and was already present so we can clean this up after the fact. As a general rule we shouldn't use `hab pkg exec` in `plan.sh` or in any hook file implementations. There are always better alternative including the `pkg_path_for` helper at build time and the `{{pkgPathFor …}}` templating helper at runtime.

**Comment by reset** [comment]
Closed by #2338 :)
