### ISSUE TITLE
Service config not available via API

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#2250]
Testing out Habitat version `0.22.0/20170506041148` on linux.

Steps to reproduce:

1.  Install hab 0.22.0/20170506041148
2. `$ sudo hab sup run`
3. `$ sudo hab sup load learn/mongodb`
4. Open http://YOUR_IP:9631/services/mongodb/default/config in a web browser.

I expect to see the configuration for the running mongodb service.  Instead, I get a 404 page not found error.

Using curl against the local host yields the same result:

```
$ hab sup status learn/mongodb && curl -I http://localhost:9631/services/mongodb/default/config
hab-sup(MN): The learn/mongodb/3.2.10/20170407074757 service entered the running state with PID: 2422 667 seconds ago.
HTTP/1.1 404 Not Found
Content-Length: 0
Date: Sun, 07 May 2017 15:04:50 GMT

```

census, services, and health endpoints all seem to be working correctly.

**Comment by reset** [comment]
@nathenharvey thanks for the report! This was an oversight in some refactoring that I recently did to the supervisor. I'll get this fixed pretty quickly

**Comment by bodymindarts** [comment]
This is quite important for debugging runtime behaviour while developing a plan. Now that `config.toml` there is no easy way to find what config a service is running and what fields are available for interpolation.

**Comment by reset** [comment]
@bodymindarts enable debug output (`RUST_LOG=debug`) and you'll see what is in the rendering context ;)

**Comment by nathenharvey** [comment]
@reset it looks like 0.22.1 has this fix but...

* the output format is now JSON
* there is significantly less data available.  for example, I cannot see a services dependencies or transitive dependencies.

Are these changes intentional?  Is there another way to get the deps and tdeps for a service from the API?

**Comment by reset** [comment]
@nathenharvey this is intentional, this endpoint is supposed to return to you the current *configuration* of the service. Prior, it was returning the rendering context for the templating system. You can access almost all of that information instead on the services endpoint which has also been overhauled. The output of the http-gateway was never documented before or well defined, the changes I made recently added some docs that should help you navigate how and where to get the information you need.

If you'd like the body to contain something other than JSON we could allow you to set an accept header with something other than `application/json`

**Comment by reset** [comment]
@nathenharvey I just realized i didn't answer your last question. You should be able to get the deps and tdeps from a service by the `/services/{name}/{group}` endpoint. However, I just noticed somebody changed the way we serialized the `pkg` field of the service struct which is stopping it from rendering. I'll get this fixed up

**Comment by nathenharvey** [comment]
Thanks.  The docs also mention `/services/{name}/{group}/{organization}/config` as a valid endpoint.  It does not currently work.  http://52.87.171.153:9631/services/mongodb/default/learn/config is an example for at least a few hours.

**Comment by reset** [comment]
@nathenharvey that might be another bug, I'll take a peek

**Comment by reset** [comment]
@nathenharvey actually, it looks like you haven't set an organization for your service which is probably why it's not showing up

**Comment by nathenharvey** [comment]
right...I think I'm confusing organization and origin ;)

so it's just the deps that I think we should be able to get from the api one way or another.  I don't really care if it's JSON or toml or whatever.  As long as we can get the data and know when the format changes (via release notes or whatever).

**Comment by reset** [comment]
@nathenharvey the format was stabilized in 0.22.0 (we even host the docs at `/` now) but there's a bug in serialization which is stripping the particular field you're looking for. We'll get that fixed and the deps will be included in there
