### ISSUE TITLE
{{ has_<bind>}} removed

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2257]
in v0.22.0 there is no way anymore to check wether a certain binding is present in the template context.

**Comment by mwrock** [comment]
@bodymindarts see https://github.com/habitat-sh/habitat/pull/2226#issuecomment-299601629. The `has_` helper has gone away in favor of syntax like:
```
{{~#eachAlive bind.backend.members as |member|}}
    server {{member.sys.ip}} {{member.sys.ip}}:{{member.cfg.port}}
{{~else}}
    server {{sys.ip}} {{sys.ip}}:8080
{{~/eachAlive}}
```
which accomplishes the same objective. We only found a handful of core plans using the `has_` syntax and we will be retrofitting those.
