### ISSUE TITLE
svc.members count/length

### ISSUE THREAD

**Issue by fearoffish** [habitat-sh/habitat#2258]
When booting up consul in server mode you can give it a `bootstrap_expect` value to indicate how many servers will be joining the group. It would be nice if I could use `svc.members_count` or something similar to put that value in the config.

After speaking with @bodymindarts it's clear this isn't a simple addition and will need discussion. The current options looks to be:

* A handlebars helper `arrLength` that returns the value
* Another field on svc like `members_count`

Thoughts welcome.

**Comment by bodymindarts** [comment]
@fearoffish by using that field in `bootstrap_expect` this would cause a restart of all nodes every time the node count changes (due to the config being updated). Is this your intention?

**Comment by fearoffish** [comment]
No, you're right for consul it's a bad idea. However, I still feel it's a valid additional helper.

**Comment by adamhjk** [comment]
@reset can weigh in too, but I think we want to move more towards helpers.

**Comment by reset** [comment]
Yep! You'd want to add this as a helper

**Comment by bodymindarts** [comment]
Related https://github.com/habitat-sh/habitat/issues/2281
