### ISSUE TITLE
Make hab sup status more friendly for machine use

### ISSUE THREAD

**Issue by jtimberman** [habitat-sh/habitat#2274]
Automated systems, such as Chef, may want to use the `hab sup status` command to parse and report on the status of running services. The current output is rather verbose for machine use, and also uses ANSI color escape sequences.

One might think that using HAB_NONINTERACTIVE would be useful, but it still shows the color output:

![1__root_service-ubuntu-1604_____ssh_](https://cloud.githubusercontent.com/assets/12483/25828708/f9e420e4-340e-11e7-9554-84448f15502f.png)

Or as a string in, e.g., Ruby:

```ruby
require 'mixlib/shellout'
s = Mixlib::ShellOut.new('hab sup status core/nginx')
s.run_command
s.stdout
# => "\e[36mhab-sup\e[0m(\e[1;37mMN\e[0m): The core/nginx service is not currently loaded.\n"
```

**Comment by jtimberman** [comment]
In addition to respecting `HAB_NONINTERACTIVE`, II propose adding a `--machine` or similar  option that returns output based on these conditions:

Service has not been loaded - no spec, nothing in the current supervisor.

```
core/nginx unloaded
```

Service has been loaded, but was told to stop.

```
core/nginx/1.11.10/20170215235242 stopped
```

Service is loaded and currently running (not in a flapping/restarting state)

```
core/nginx/1.11.10/20170215235242 running
```

Perhaps something that detects whether the service has been loaded but may have some error state causing it to restart?

```
core/nginx/1.11.10/20170215235242 loaded, flapping
```

**Comment by rsertelon** [comment]
Is this issue still relevant after #2334 and #2414 seem to have addressed it?

**Comment by raskchanky** [comment]
It looks like https://github.com/habitat-sh/habitat/pull/2414 should address this, but if it doesn't feel free to reopen this issue.
