### ISSUE TITLE
Allow non root user to run `hab service load`

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2280]
At the moment only root users can run `hab service load` due to ownership of `/hab/sup/` directory.

For services that require a side car process it is handy to run `hab service load <origin>/<side-car-serivec>` in the `init` or `post-run` hooks. Since doing this requires `root` access that means the whole plan needs to be run as `root` though this may not actually be necessary.

Is there a way around this?

**Comment by reset** [comment]
@bodymindarts we may need to take a pass at privileges one more time. We initially had a hard requirement that you must run Habitat as root. Provided that you aren't starting any processes with a privileged port, I think you pretty much don't need to run as root - every file a service interacts with should be within it's habitat service directory.

With that said, I don't think there's a reason that `/hab` or `/hab/sup` must be owned by root

**Comment by chrisortman** [comment]
If non-root user can load a hab service, then you would have to make sure you were using different svc_user and/or svc_group in your packages else any user could load their service that reads all your data owned by the hab user?

**Comment by bodymindarts** [comment]
Closing because duplicate of https://github.com/habitat-sh/habitat/issues/1408
