### ISSUE TITLE
Add handlebar array filters

### ISSUE THREAD

**Issue by IxDay** [habitat-sh/habitat#2281]
I came across an issue when trying to write a configuration generator, I needed to join the content with commas like this: `foo, bar, baz`. Adding a comma at the end by using `{{each}}` made the program stop with an error, so I am kind of stuck here.

I believe that in general it would be useful to have several array operators like `length`, `map`, `filter`, `join`, given that there is no other layer where logic can be run.

**Comment by adamhjk** [comment]
For this specific issue, I think you can work around it by using '@last' to check if your at the end of the integrator.

**Comment by IxDay** [comment]
I don't have math operators neither, so no way to avoid putting a comma at the end by checking if index in not @last

**Comment by bodymindarts** [comment]
You can put a coma before the value and check on @index to see if you
should add the comma. When @index is 0 it won't add it because 0 is false
in handlebars.

**Comment by IxDay** [comment]
This one can do the trick

**Comment by IxDay** [comment]
But nonetheless adding helpers will definitely help writing config files, there is a good list of what can be done easily here: http://docs.ansible.com/ansible/playbooks_filters.html

**Comment by adamhjk** [comment]
Oh, we for sure need the helper. Just helping with a workaround :)

**Comment by rsertelon** [comment]
We now have a `strJoin` helper (see [this for complete list](https://www.habitat.sh/docs/reference/#habitat-helpers)).

Maybe we could close this one? Or are there other helpers missing?

**Comment by jsirex** [comment]
Up
