### ISSUE TITLE
.studiorc is sourced twice on 'hab studio enter'

### ISSUE THREAD

**Issue by jonsmorrow** [habitat-sh/habitat#2308]
Ever since the new auto-starting of the supervisor in a interactive studio shipped the .studiorc file is sourced twice once as part of the chroot to start the supervisor, then again during chroot to enter the studio. On our team we are using the .studiorc file to provide some dev docs about the habitat base dev environment we are building out for our project when developers enter the studio. Since the .studiorc is sourced twice we see the out put twice which is kind of ugly.

I know the intent of sourcing this file before starting the supervisor was to allow users to put NO_BG_SUP=1 in the file to prevent the supervisor from auto starting. I think this behavior might be better handled by an environment variable set prior to calling studio enter. This way we can load the .studiorc file once at the end.

Not directly related to this issue... But as we build out this dev env we'd like to load services into the supervisor which seems to require that it be sourced after the supervisor is started. Our end game is that a developer can cd to our repo, run hab studio enter, and have all our services running with an at-once update strategy and accessible via localhost.

We are using the mac docker studio environment.

Repro steps:
1. Create .studiorc with a simple execute in a directory
2. Run hab studio enter

hab_bug hab studio enter
   hab-studio: Creating Studio at /hab/studios/src (default)
   hab-studio: Importing jmorrow secret origin key
» Importing origin key from standard input
★ Imported secret origin key jmorrow-20160714024457.
   hab-studio: Entering Studio at /hab/studios/src (default)
   hab-studio: Exported: HAB_ORIGIN=jmorrow

>>> FROM STUDIORC! <<<<
** The Habitat Supervisor has been started in the background.
** Use 'hab sup start' and 'hab sup stop' to start and stop services.
** Use the 'slog' command to stream the supervisor log.
** Adding 'NO_BG_SUP=1' to your .studiorc file will disable the background supervisor.

>>> FROM STUDIORC! <<<<`
`

**Comment by smith** [comment]
I think everything on here has been addressed in 0.24.
