### ISSUE TITLE
Contents of /etc/hosts does not resolve.

### ISSUE THREAD

**Issue by therealpadams** [habitat-sh/habitat#2317]
- hab 0.22.1/20170509234454
- CentOS 7 (Linux 3.10.0-514.16.1.el7.x86_64)

Observation:
After entering the habitat studio it is not possible to resolve hostnames contained within /etc/hosts. The same hostnames can be resolved outside the studio.

Expectation:
Entries in the host machine's /etc/hosts should be resolvable within the habitat studio.

Example:
https://asciinema.org/a/5200a4tvjkd0d5c2bdw3nrzyx

**Comment by eeyun** [comment]
This is a pretty easy fix, I might be able to handle it over the weekend. The reason this happens is we don't drop an /etc/nsswitch.conf down inside of the studio and wget is attempting to use DNS to resolve.

As a workaround until we can get a PR in to fix the problem -

Inside the studio run:

`[1]default:/src:p] touch /etc/nsswitch.conf && echo 'hosts: files' > /etc/nsswitch.conf`

You should then be able to resolve with wget
