### ISSUE TITLE
Rolling config apply

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2324]
This is a request for a feature that has come up very often in discussions I have had. Habitat provides a rolling update strategy for package updates but (so far) not for config changes.

This feature was recently acknowledged by @reset in slack:
> reset 
> [7:00 PM] @padams @jcarter we definitely need to add rolling config apply. We've got everything in place to make it happen, just gotta hook it up
> 
> [7:00]  We can leverage the existing rolling update code

I'm just adding it here for visibility.

**Comment by rsertelon** [comment]
This issue is already opened at #1558 :)

**Comment by tashimi** [comment]
Closing as duplicate.
