### ISSUE TITLE
Add sharing and contributing features to the blog

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2327]
After the initial launch of the Habitat blog, we'll need to add a few more features to finish it off.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Add the social sharing buttons on posts (Twitter, FB, LinkedIn)

- [ ] Add the sidebar button to 'Contribute a Guest Post' which links to README instructions (yet to be written at the time this issue was created)
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by eeyun** [comment]
This is a great feature idea. I _think_ that the new search stuff pulls in the blog content now, I've been seeing responses to searches including them. But the other two bits would be awesome!

**Comment by rsertelon** [comment]
@eeyun they may appear, but there's no search field on the blog page :)

**Comment by baumanj** [comment]
The hab blog is no more
