### ISSUE TITLE
Link and style change for 'Dashboard' nav

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2330]
![image](https://cloud.githubusercontent.com/assets/9401459/25975529/b0b4a324-3663-11e7-8db1-4fddfa969a80.png)
- Click on the DASHBOARD should open up the dashboard view, same as clicking on the habitat logo.

- The font style needs to be changed to the same as 'Packages' and 'Origins'

**Comment by ryankeairns** [comment]
That heading should stay but it should read 'DEPOT' with the dashboard link below it... the mockup we're aspiring to contains this: 

https://www.dropbox.com/s/tlef84wkyrq5mu0/Screenshot%202017-05-12%2008.49.39.png?dl=0
