### ISSUE TITLE
Add rich data to `hab sup status` output.

### ISSUE THREAD

**Issue by rhass** [habitat-sh/habitat#2334]
As a habitat user, I would like to know more details about services which are running when executing `hab sup status`. Useful information would be things like, `update_stategy`, `start_style`, `binds`, `topology`, and supervisor update interval. This will help users quickly answer multiple questions in a single command. Eg: "Is the service up, and if so why hasn't it updated?"

**Comment by reset** [comment]
Closed by #2414
