### ISSUE TITLE
[web ui] Update main app footer to match www footer

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2337]
We recently updated the website footer per the new mockups and IA; need to apply that updated version to the app.habitat.sh views as well.

Current app footer:
<img width="1435" alt="screenshot 2017-05-12 10 12 12" src="https://cloud.githubusercontent.com/assets/446285/26004511/bef0c1fa-36fb-11e7-97f5-e1108144012f.png">

Desired/updated footer:
<img width="1435" alt="screenshot 2017-05-12 10 12 34" src="https://cloud.githubusercontent.com/assets/446285/26004512/bef48a42-36fb-11e7-94e1-05695eec38fd.png">

**Comment by raskchanky** [comment]
Closed via https://github.com/habitat-sh/habitat/pull/2379
