### ISSUE TITLE
Update cert for app.acceptance.habitat.sh

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2350]
Currently the cert for our acceptance environment is not accepted by the browser or by the openssl API calls.  We need to update to a cert that passes validation.

**Comment by cnunciato** [comment]
Could we get one for **www.acceptance.habitat.sh** as well? Pretty sure we'll need this in order for the cookie-sharing to work properly.

**Comment by reset** [comment]
@cnunciato as long as we get `*.acceptance.habitat.sh` we'll have coverage for `www`, `api`, `builder`, all sub domains!
