### ISSUE TITLE
Auto-create origin project when uploading a package

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2357]
Currently, in order for the builder service to auto build a plan, it needs an origin Project that contains metadata such as the repository and other plan location info. The origin project needs to be explicitly created before a package can be successfully built by builder. 

This issue is a proposal to automatically create the origin project during package upload if the project doesn't already exist. The package plan would need to contain sufficient metadata for this. We could also elide the metadata for core packages.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #24](https://github.com/habitat-sh/builder/issues/24) via [**ZenHub**](https://www.zenhub.com/)
