### ISSUE TITLE
[builder-scheduler] Smarter dispatching

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2374]
The scheduler can be smarter about dispatching projects - for example, it can look ahead in it's queue to look for multiple builds of the same package, and assess whether it can do only a single build of the package.  It should also have some minimum time interval for dispatching the same project (eg, don't dispatch same project within X seconds as the release versions can then potentially be the same, later causing an upload conflict).

**Comment by tashimi** [comment]
@chefsalim is this ok to close now?
