### ISSUE TITLE
hab pkg binlink does not use PATH correctly

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2376]
```
[1][default:/src:0]# hab --version
hab 0.23.0/20170511215221
[2][default:/src:0]# hab install chef/inspec
...
[3][default:/src:0]# hab pkg exec chef/inspec inspec version
1.24.0
[4][default:/src:0]# hab pkg binlink chef/inspec inspec --dest /hab/bin
» Symlinking inspec from chef/inspec into /hab/bin
★ Binary inspec from chef/inspec/1.24.0/20170511185749 symlinked to /hab/bin/inspec
[5][default:/src:0]# inspec version
/hab/pkgs/core/coreutils/8.25/20161208223423/bin/env: 'ruby': No such file or directory
```

Expected behavior: It shows the InSpec version.

Running a program with `hab pkg exec` sets the PATH to the path of the `pkg_bin_dirs` of all the transitive dependencies, so this works correctly. `hab pkg binlink` just makes a symlink, so you get the same results as if you would have run `$(hab pkg path chef/inspec)/bin/inspec`.

**Comment by ShalokShalom** [comment]
Confirmed and it exists since at least 0.27: 

![screenshot_20170811_164819](https://user-images.githubusercontent.com/6344099/29218401-0673d7f0-7eb5-11e7-88ed-5e0ac4ec86ed.png)

**Comment by smith** [comment]
@ShalokShalom this is a different issue. In a studio, /bin/ is not on the `$PATH`. If you want to have something symlinked in a studio, use `hab pkg binlink --dest /hab/bin core/pkg-config pkg-config`.

What you're describing is #1680. Hope that helps.

**Comment by baumanj** [comment]
Subsumed by https://github.com/habitat-sh/habitat/issues/4493
