### ISSUE TITLE
hab stop command

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2377]
The opposite of `hab start` is `hab stop`.`hab start` works but you have to do `hab svc stop`. `hab stop` should work as expected. Maybe `hab status` too.

**Comment by mwrock** [comment]
I also think we should have `hab stop` with no args stop all services and stop the supervisor with a confirmation prompt and the option to override with `--force`.

**Comment by smith** [comment]
> I also think we should have hab stop with no args stop all services and stop the supervisor with a confirmation prompt and the option to override with --force.

Would you also then have a `hab start` which behaves similarly to `hab svc run`?

**Comment by mwrock** [comment]
Good question. Maybe. Bottom line is I'd like a cleaner way of shutting down a supervisor without manually sending a signal to the process. `stop` seems a clear opposite of `run` but we do need to tighten the nomenclature.

**Comment by reset** [comment]
We really only left `hab start` for compatability reasons. The next release of Habitat will include a shortened version of `hab service`, `hab svc`. @mwrock is spot on why `hab stop` wasn't added as an alias, does it stop a service or does it stop the entire supervisor? Is it the opposite of `hab svc start` or is it the opposite of `hab run`?

We could make the opposite of `hab run` something different than stop, like `hab terminate` or `hab shutdown`, or we could do something like add `hab stop` and remove `hab start`. The top level alias of `hab start` was conceived before we had second way to run the supervisor.

IMO I think we should add a deprecation warning to `hab start` and add `hab stop` which is the way to shutdown an entire supervisor

**Comment by smith** [comment]
@reset I'm ok with that decision but the reason I opened the issue was an behalf of my good friend symmetry. Everybody on my team tries, logically to type `hab stop` but has to remember that it doesn't work, but `hab start` does. I'm ok with removing `hab start` as long as there is symmetry between things like start/stop.

**Comment by smith** [comment]
Fixed in #2419.
