### ISSUE TITLE
[builder-jobsrv] occasionally panics when starting jobs

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2386]
The builder-jobsrv can occasionally panic when starting jobs.  This results is a "net:route:3" error.

Backtrace (Not very useful) below:

May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O): thread 'worker-manager' panicked at 'other was less than the current instant', /checkout/src/libstd/sys/unix/time.rs
:276
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O): stack backtrace:
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    0: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    1: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    2: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    3: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    4: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    5: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    6: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    7: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    8: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):    9: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):   10: <unknown>
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):   11: start_thread
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):              at /hab/cache/src/glibc-2.22/nptl/pthread_create.c:334
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):   12: clone
May 16 19:24:29 ip-10-0-0-205 hab[10899]: builder-jobsrv.acceptance(O):              at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

**Comment by chefsalim** [comment]
I haven't seen this recently - its possible this might be resolved by some other fix.

**Comment by chefsalim** [comment]
Saw it in acceptance again :(

**Comment by raskchanky** [comment]
That backtrace turned out to be exceptionally useful, actually.  😁
