### ISSUE TITLE
[builder web] Redirect when not logged in

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2397]
I've not been able to re-create this on the production depot, but it is also is not up to date with acceptance... 

Hitting the root url of the acceptance environment - when you are not signed in - redirects you to a www. url that results in a ‘not found’.

**Comment by christophermaier** [comment]
Apparently this is because we do not currently have an instance of the website running in acceptance 😝

**Comment by eeyun** [comment]
There are a few things we need to figure out about this but correct me if I'm wrong: this is more or less a side effect of us using netlify for the acceptance site and not having a way to get the site linked to the acceptance bldr instance in an appropriate manner?

There are a couple ways we could correct this, one of which is rebuilding the acceptance site/deployment mechanism to make it look significantly more like production.

**Comment by ryankeairns** [comment]
@eeyun what you described makes sense and I also agree that this is minor. At the time I wrote this issue (prior to chef conf), it felt more concerning given that we were working on detecting whether a user was logged in while on the marketing site/redirecting them to the app (if logged in).

**Comment by cnunciato** [comment]
This should be good now: http://www.acceptance.habitat.sh/.
