### ISSUE TITLE
RFE: hab sup status should print some logs of the service

### ISSUE THREAD

**Issue by tixxdz** [habitat-sh/habitat#2402]
`hab sup status myservice`

Should print some lines of the service's logs, or maybe add another argument to print them.

The ideal would be to print the status of the health check then some lines of the logs so we have a better status. Only saying that the pid is running does not tell much since some services may fork etc.

**Comment by smith** [comment]
systemd does this with the `--lines` switch:

```
[ec2-user@ip-172-31-47-228 ~]$ systemctl status dbus-org.freedesktop.NetworkManager.service
● NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-20 18:00:12 EDT; 3 weeks 6 days ago
     Docs: man:NetworkManager(8)
 Main PID: 480 (NetworkManager)
   CGroup: /system.slice/NetworkManager.service
           ├─480 /usr/sbin/NetworkManager --no-daemon
           └─547 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-eth0.pid -lf /var/lib/NetworkManager/dhclient-5...

May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2803] dhcp4 (eth0):   address 172.....228
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   plen 20 (255...0.0)
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   gateway 172.31.32.1
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   server ident...32.1
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   lease time 3600
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   hostname 'ip...228'
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   nameserver '...0.2'
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0):   domain name ...nal'
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal NetworkManager[480]: <info>  [1495134133.2804] dhcp4 (eth0): state changed ...ound
May 18 15:02:13 ip-172-31-47-228.us-east-2.compute.internal dhclient[547]: bound to 172.31.47.228 -- renewal in 1647 seconds.
Hint: Some lines were ellipsized, use -l to show in full.
[ec2-user@ip-172-31-47-228 ~]$ systemctl status dbus-org.freedesktop.NetworkManager.service --lines=0
● NetworkManager.service - Network Manager
   Loaded: loaded (/usr/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2017-04-20 18:00:12 EDT; 3 weeks 6 days ago
     Docs: man:NetworkManager(8)
 Main PID: 480 (NetworkManager)
   CGroup: /system.slice/NetworkManager.service
           ├─480 /usr/sbin/NetworkManager --no-daemon
           └─547 /sbin/dhclient -d -q -sf /usr/libexec/nm-dhcp-helper -pf /var/run/dhclient-eth0.pid -lf /var/lib/NetworkManager/dhclient-5...
```

**Comment by reset** [comment]
The Supervisor doesn't perform any log capturing, it just pipes the stdout/stderr streams of it's children directly to it's own stdout. Our current intent is for the Supervisor to be run by another mechanism, like systemd, which handles the log capturing and rotation for you.

In the future we may make some improvements here, but as it stands we can't reliably provide this functionality to the `svc status` command

**Comment by tixxdz** [comment]
> The Supervisor doesn't perform any log capturing, it just pipes the stdout/stderr streams of it's children directly to it's own stdout. Our current intent is for the Supervisor to be run by another mechanism, like systemd, which handles the log capturing and rotation for you.

In systemd, it is systemd-journald [1] that handles these operations which is a hard dependency, and not proper systemd pid1. systemctl print those logs by opening the journals with the appropriate filters and unit target and print them. It is a shortcut to journactl --unit etc... and it only works if systemctl is acting on the local machine bus.

> In the future we may make some improvements here, but as it stands we can't reliably provide this functionality to the svc status command

Ok, then if this is a desired feature, maybe it is better to edit the title and re-open it, at least it is not forgotten.

Thank you!

[1] https://www.freedesktop.org/software/systemd/man/journald.conf.html
