### ISSUE TITLE
Support -advertise-ip for bridged networks

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2420]
In situations where containers are used on a host using bridged network the supervisor will advertise its ip as the container internal one. This ip will not be accessible from outside of the host.

We need a way to set the ip and port to advertise to other supervisors what the host port / ip is that get mapped to the container.

**Comment by adamhjk** [comment]
Yep. My question is how - obviously we could make you specify the IP, but it would be neat if we could figure out how to let this be dynamic. Interface name? IP to attempt to route to?

**Comment by tashimi** [comment]
Closing as duplicate
