### ISSUE TITLE
Stats API responding with 503

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#2441]
On bldr.habitat.sh, it's currently returning `{"code":6,"msg":"rt:route:2"}`.

https://bldr.habitat.sh/v1/depot/pkgs/origins/core/stats

**Comment by mwrock** [comment]
This seems to be returning a valid response now. This particular error would indicate that the scheduler service was down. I'm going to close for now but we should absolutely investigate if we see this again.
