### ISSUE TITLE
Scheduler API responding with 503

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#2443]
<img width="1914" alt="screen shot 2017-05-20 at 9 22 06 am" src="https://cloud.githubusercontent.com/assets/1130349/26276498/3a6cd5b0-3d3e-11e7-888c-59d40b5586c9.png">

currently returning`{"code":6,"msg":"rt:route:2"}`

https://bldr.habitat.sh/v1/depot/pkgs/schedule/core/packer

**Comment by chefsalim** [comment]
Resolved - the router needed a restart.
