### ISSUE TITLE
Configurable kill signal and timeout

### ISSUE THREAD

**Issue by sethvargo** [habitat-sh/habitat#2447]
Right now, Habitat sends TERM to any process it's supervising on stop. Not all applications respond to TERM, some respond to INT or even USR1 for a custom, clean shutdown.

I talked with @fnichol about this, and I think we agreed that it makes sense for plans to describe their termination schedule, perhaps like this:

```sh
pkg_kill_signal=(INT)
```

Additionally, it would be nice if packages could customize the amount of time they want to wait for a clean shutdown like:

```sh
pkg_kill_timeout=(30)
```

**Comment by smith** [comment]
How about `pkg_svc_kill_signal` to indicate that it concerns the service provided by the package? More consistent with variables like `pkg_svc_user`.

**Comment by sethvargo** [comment]
I'm indifferent on the naming tbh - more concerned with the feature 😄

**Comment by bodymindarts** [comment]
@sethvargo what is the use case you need this for?
I agree that the shutdown process needs to be configurable in a more granular way. I was thinking of a `shutdown` hook that could be called pre `kill`ing. How would that fit in to your needs?

**Comment by bodymindarts** [comment]
https://github.com/habitat-sh/habitat/issues/1994 is related to supervisor shutdown behaviour.

**Comment by sethvargo** [comment]
> what is the use case you need this for?

I have an app that stops gracefully on sigint (it's a webserver). Given INT, it properly drains connections and shuts down gracefully. Given TERM, it dies and closes all connections, potentially killing a download or active request.

**Comment by christophermaier** [comment]
This is blocked pending the refactorings involved with #1973

**Comment by stevendanna** [comment]
Somehow I didn't see this when filing https://github.com/habitat-sh/habitat/issues/5135 which is a aimed at solving the same basic issue

**Comment by dmccown** [comment]
Is this still blocked on #1973?
