### ISSUE TITLE
Stats API returns total packages, UI refers to total plans

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2453]
We have a discrepancy between what the stats API returns and what the UI says.  Need to fix one of them.

**Comment by mwrock** [comment]
I think the best option would be to fix the UI. Packages seems a better and more accurate term. no?

**Comment by cnunciato** [comment]
I agree -- as a user, packages are what I care about, more than plans. What do you think, @tashimi?

**Comment by reset** [comment]
@cnunciato the intent was to reflect packages and not plans. This is supposed to be the McDonald's "million customers served" type of stat. It's just a for fun thing ;)

**Comment by tashimi** [comment]
Yup, +1 what @reset said @cnunciato. Thanks for checking in, I love your attention to detail! 

![](https://media.tenor.co/images/78cb55b0463f3f320ede52b121910e65/tenor.gif)
