### ISSUE TITLE
svc_default_user and svc_default_group not accessible in templates

### ISSUE THREAD

**Issue by sethvargo** [habitat-sh/habitat#2459]
- Mac OS 10.12
- Habitat 0.24.0/20170519202549

The [Plan interpolation](https://www.habitat.sh/docs/reference/plan-syntax/#pkg) section describes the following variables:

- svc_user_default
- svc_group_default

These values do not seem to be interpolated in templates:

```
{{pkg.svc_user_default}} #=> ""
```

However, `pkg.svg_user` works fine, as long as one is specified in the plan. I'd like to use the behavior of `svg_user_default` as described in the docs, but it always renders as the empty string.

**Comment by mwrock** [comment]
This definitely looks like a documentation bug. There is absolutely no handling of that `svc_user_default` or `svc_group_default` in the code. We solely use `svc_user` and `svc_group` which *should* resolve to the default user (`hab`) if none is explicitly defined in the plan. If you do not define that in your plan and the template is not rendering it to the default, that sure sound like a bug to me.

**Comment by sethvargo** [comment]
Hey @mwrock 

Thank you for the reply. There doesn't seem to be a page that clearly lists what is/is not available in the template interpolation vs plan. That would be a great addition for new users I think.

**Comment by mwrock** [comment]
The "Runtime configuration settings" section of the plan syntax doc is a complete list and I think it is up to date but it definitely seems like we could surface this key information better instead of embedding it in that larger doc. Not to mention removing the bogus default user variable.
