### ISSUE TITLE
Add link to Habitat logos/brand assets on About page

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2476]
They are uploaded to the Drive folder: https://drive.google.com/open?id=0B6wx-y4RiRvoeHhaWjc5V0ZwdUk

Add them to the repo so that people can use them for media, blog post, presentation, etc.

**Comment by ryankeairns** [comment]
@apriofrost as we discussed on Slack, can we just point to brand.chef.io for this?

If so, we can also close #2582

**Comment by apriofrost** [comment]
@ryankeairns Yes. The link should be included in the About Us page which hasn't been implemented yet.

**Comment by ryankeairns** [comment]
The link to be added is here: https://brand.chef.io/habitat/
