### ISSUE TITLE
Files inside svc/*/config belong to 'root' even though svc_user/group is 'hab'

### ISSUE THREAD

**Issue by tduffield** [habitat-sh/habitat#2479]
When you start a service using the supervisor, the files inside the config directory belong to the 'root' user even though the svc_user and svc_group are the default 'hab'

```shell
$ hab --version
hab 0.24.0/20170519210222
```

**Comment by rsertelon** [comment]
This is linked to #1547

**Comment by tashimi** [comment]
Closing as duplicate
