### ISSUE TITLE
'Unload' hook

### ISSUE THREAD

**Issue by therealpadams** [habitat-sh/habitat#2485]
## Preamble

Introduce an "unload" hook for performing tasks _each_ time that `hab stop` is called for a service.

## Example use case

- The `core/drupal` plan background loads `core/nginx` in the init hook. 
- When the user runs `hab stop core/drupal` the core/nginx instance is left running.
- An unload hook would allow the plan writer to additionally stop the nginx which is now cruft.

**Comment by reset** [comment]
@therealpadams yeah we'll definitely do this 👍
