### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by mytototo** [habitat-sh/habitat#2487]
Hi!

Is there any chance to see a Habitat provider for Terraform?

Thanks.

**Comment by christophermaier** [comment]
@mytototo @nsdavidson is working on one: https://github.com/nsdavidson/terraform-provisioner-habitat

**Comment by eeyun** [comment]
For now I think we're happy to contribute to nolan's project. Closing this but if you'd like it reopened for any reason feel free.
