### ISSUE TITLE
[builder scheduler] Add re-try logic for job failure

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2488]
If a job fails to schedule (ie, call to jobsrv does not succeed), or fails a build, the scheduler currently fails the schedule group. This exacts a large penalty when there are a lot of build jobs in the schedule group, as the reason for failure could be something intermittent. This card is for adding re-try logic to the scheduler for job schedule or build failure.

**Comment by raskchanky** [comment]
Per @chefsalim's suggestion, I'm going to implement this in the worker instead of the scheduler.

**Comment by chefsalim** [comment]
Covered by https://github.com/habitat-sh/habitat/issues/2686

We no longer Fail groups, we complete them with Skipped jobs. The job cli will allow for retry of failed jobs.
