### ISSUE TITLE
[builder-web] Fix some usability issues

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2493]
- searching with a `/` is still generating an error, and doesn't have consistent behavior
-- from here https://bldr.habitat.sh/#/explore, search for `core/postgres`. You will see that the string is converted to `core%2Fpostgres` but no results are found.
-- from here https://bldr.habitat.sh/#/pkgs/core, search for `core/`. As soon as you add `/` you receive the message that `No packages found.` 

- I use my keyboard to navigate the web a lot, and I suspect a lot of our users do as well. If I `<ctrl-a>` and `delete` the string `core/` while I am getting `No packages found`, I get stuck in a state where the list of packages does not regenerate and I have to reload the page to see any result other than `No packages found`.

- Get that list of packages to show back up on https://bldr.habitat.sh/#/pkgs/core. Scroll down and click on `core/postgres`. Just kidding, it doesn't show up and you'll have to manually load a bunch more pages. 
- Instead, type `postgres`. You'll see a bunch of postges packages. 
-- core packages should be on top of the list, instead of a bunch of other random origins. (This is an opinion and up for debate, but I think it's correct for now). 
- Click on `core/postgres` and end up here https://bldr.habitat.sh/#/pkgs/core/postgresql
-- Newer versions should be on the top (currently the older version is on the top).
- Click on the newest version, end up here https://bldr.habitat.sh/#/pkgs/core/postgresql/9.6.1
-- Newer versions should be on the top (currently the older version is on the top)
- Click on the newest build, end up here https://bldr.habitat.sh/#/pkgs/core/postgresql/9.6.1/20170514001355
-- This page should have the date of last build on it in the manifest

**Comment by ryankeairns** [comment]
This covers #2477 so I'll close it.
