### ISSUE TITLE
[builder services] Fix migrator to not use sequence #s

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2498]
Currently the DB migrator uses sequence #s to determine which changes to apply to the DB when services are started. This can cause change to get missed or incorrectly applied as the sequence # is just a incrementing integer so changes must be very specifically applied in the last file processed. This is quite fragile. This proposal is to change to something other change sequence #s - eg, hash the function content and if they don't match, re-apply the migration.

**Comment by christophermaier** [comment]
Is writing our own migrator still something we want to do, vs. using something else like, say, [sqitch](http://sqitch.org)? I'm not sure what the general feeling on sqitch is these days, but I'm a big fan of it.

**Comment by reset** [comment]
I'm personally not married to any implementation provided that our application runs the migrations on startup 😄

**Comment by chefsalim** [comment]
A couple of other things to think about if considering a move to a structured tool:
1. Ability to refactor and clean up DB scripts - once we get into a structured tool like sqitch we may lose the ability to refactor and keep things tight and simple.
2. Ability to make changes to tables across constraints - how straightforward is it to make a table change that requires a change to a previous constraint.
3. Related to #1 - having the ability to cleanly remove unused changes. Example - we iteratively start building feature X and make some schema changes. We merge some PRs/ship a release without enabling feature X (it's still in development iteratively). Now we decide that feature X is cancelled and should be removed. 
4. Having the ability to override the tool - eg, in cases where we know better than the tool. Helpful for emergencies and other scenarios.

**Comment by christophermaier** [comment]
I'll speak to how sqitch manages things, since that's the tool I'm most familiar with, but I think these probably apply generally.

1. We shouldn't be changing past migrations anyway. You end up getting into all kinds of trouble that way.
2. With Sqitch at least, your changes can be as big or as small as you want. In practice, it's often  a good idea to keep them pretty focused, at least with functions. This is mainly due to the refactoring and updating tooling that Sqitch provides (which is _really good_).
3. Removing changes is just adding a script that drops / reverts said changes. This is also made pretty easy with Sqitch.
4. Do you have an example of this case? With sqitch, changes are literally just SQL files. Ideally, any kind of "manual changes" we find would be in testing environments; whatever solution we ultimately discover could be turned into a set of proper migration scripts.

**Comment by raskchanky** [comment]
I have very little experience with sqitch, so I can't comment on that.  I definitely agree though that migrations should be treated as immutable things and not changed after they've been applied.

**Comment by christophermaier** [comment]
I haven't used Sqitch in about 2 years, but helped introduce it at Chef... if we want to consider using it, it'd be good to touch base with the other teams in Engineering to see what their experience with it has been in the past 2 years.

**Comment by christophermaier** [comment]
I will note that there is already a [core/sqitch](https://github.com/habitat-sh/core-plans/blob/master/sqitch/plan.sh) Habitat package thanks to @elliott-davis

**Comment by raskchanky** [comment]
There was some discussion around sqitch today in Chef's internal dev chat and the main objections to it were:

1. It brings in 100MB of perl dependencies, which feels a bit wasteful given that nothing else relies on perl.
1. Some of the dependencies it brings in have licenses that prohibit their use in certain kids of Chef products.
1. Standalone schema management tools can be harder to operationalize than application-integrated ones.

It feels like our needs for this tool are relatively simple.  In my experience at least, the main issue with our current system is that it's tricky to get new migrations into the correct spot so we know they'll get run.  I think this has less to do with sequence numbers and more to do with the fact that the migration must be positioned at a specific spot within the migration file.

I'm currently looking at https://github.com/Keats/dbmigrate as a possible replacement for our current system.  Its feature-set seems small, but adequate.  I'm going to try a small spike with it and see how it feels to use.  I'll address @chefsalim's points after I have some more data about the tool.
