### ISSUE TITLE
[QUESTION] Should habitat packages support man pages?

### ISSUE THREAD

**Issue by ghost** [habitat-sh/habitat#2500]
Very similar to the helper methods such as `pkg_bin_dirs`, should a similar construct be created to support man page entries?

The thought process is the following ....

I agree that runtime environments probably do not need things such as man pages but if that is the case, they should be stripped out of the build and maybe this is an issue against the core-plans repository ....

That being said, it would be interesting to see that is man is on the path, the man packages would optionally be installed and could be determined by another helper utility such as `pkg_man_dirs` ...

**Comment by reset** [comment]
I think we should add this support but we need to think a bit on how we figure out which man pages we should show you. Perhaps this is part of the binlink process?

**Comment by steakknife** [comment]
Just encountered this issue:

- Perhaps `hab man [{{section}}] {{package_name}}` 
- Generate a `man.conf` dynamically that adds `MANPATH {{each of pkg_man_dirs}}`
- Then passed on to the underlying `man` (`man [{{section}}] {{package_name}} -C /path/to/temp/man.conf`)
