### ISSUE TITLE
Update the dev docs

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#2511]
A few things changed in the run up to ChefConf. We should take a pass through these docs:

https://github.com/habitat-sh/habitat/blob/master/BUILDING.md
https://github.com/habitat-sh/habitat/blob/master/BUILDER_DEV.md
https://github.com/habitat-sh/habitat/blob/master/components/builder-web/README.md
https://github.com/habitat-sh/habitat/blob/master/www/README.md

... and make sure they're up to date.

**Comment by eeyun** [comment]
@cnunciato and @tashimi is it safe to assume this card was also completed and can be close?

**Comment by tashimi** [comment]
Yup
