### ISSUE TITLE
[builder] [chore] Fix hab graph tool

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2514]
This is a chore item.  The hab graph tool (hab-spider) is currently erroring out when building via its plan. It needs to be fixed and published to the depot.  It should also be auto-installed to the datastore instance via our terraform scripts so that it can be used for analysis of live data. Finally, it should probably move to a 'tools' folder, and be fully renamed to hab-graph.

**Comment by reset** [comment]
Closed by #2598
