### ISSUE TITLE
[builder] [chore] Terraform for acceptance should mount package snapshot

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2515]
Currently, when building up the hab acceptance environment, the process to create and mount a snapshot with packages data from prod is manual, and also requires re-loading the API services manually into a new service group along with other manual cleanup. 

A better approach would be to mount a packages snapshot as a separate mount, and update the packages path to point to that mount point.  This should be automated via Terraform.

**Comment by mwrock** [comment]
Since we know we are moving away from EBS mounts (https://github.com/habitat-sh/habitat/issues/1933) perhaps we should hold off on this until that work is done.

**Comment by reset** [comment]
Yes, I'm going to close this in favor of configuring acceptance instead to use the work found in #1933
