### ISSUE TITLE
[builder] [feature] Integrate dependency graph 

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2516]
Currently, the scheduler service has internal logging that can be used to generate gantt charts of job scheduling progress. This would be a good feature to build into the UX for builder admins and other stakeholders.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #25](https://github.com/habitat-sh/builder/issues/25) via [**ZenHub**](https://www.zenhub.com/)
