### ISSUE TITLE
Service "bootstrapping"

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2520]
Say I have a service, "myapp", that needs core/redis and core/mysql to run. My primary deployment mechanism is to run all of these services on one machine (though in the future I might run them on different machines)

Right now, if I have `hab` on the machine, I have to do the following to get everything running:

```
# ...create a hab user...
# ...set up an initscript to run and start the supervisor...
hab svc load myorigin/myapp --bind redis:redis.default --bind mysql:mysql.default
hab svc load core/mysql
hab svc load core/redis
```

What I would want to do is have a single command (`hab start myorigin/myapp` or `hab bootstrap ...`) that would start all of my services in the "standard" configuration and have them bound correctly, and also maybe take care of creating a user and initscript.

As of now I can run these commands in the init or run hook of myapp, but this could have bad consequences and is not recommended.

What would a feature that solves this problem look like?

/cc @reset @fnichol @adamhjk

**Comment by reset** [comment]
@smith @jonsmorrow and I had a good chat about this. I proposed a few ideas on how to bundle up things and start them and @smith notes them here. I think there are potentially more ways we could do this but I want us to write the docs first / figure out the end user experience. The overall goal as @smith states is that we should just be able to ask Habitat's supervisor to start and stop a set of services atomically and also have them automatically bind to each other

**Comment by fnichol** [comment]
This is an interesting problem and I bet there are things we can do here to help. I would be cautious however that currently services are not inherently host-aware and services don't have host affinity--these would be in the domain provisioning or scheduling solutions.

**Comment by reset** [comment]
Closing in favor of #2661
