### ISSUE TITLE
[forum] There is currently no link to it on the homepage

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2538]
As the title says:
![screenshot_20170606_085659](https://cloud.githubusercontent.com/assets/6344099/26817254/20cebc62-4a96-11e7-957f-dbc5a4e75635.png)

**Comment by fnichol** [comment]
No link to our forum, yep!

**Comment by apriofrost** [comment]
Hi @ShalokShalom . Thanks for the feedback! Currently, the forum is mainly for users to subscribe to email notifications about updates. You can find the same information in #announcements and #general channels in the Habitat Slack. Product feedback and discussions can happen here in GitHub or Slack. You can also request new features by clicking the 'Request New Features' button under 'Product Roadmap' in the community page.

**Comment by rsertelon** [comment]
Shouldn't this issue be closed wrt the fact that the forum is almost not used by core team members ? :) Maybe we should even redirect people from the forum to github or slack as you said @apriofrost so they don't wait for answers too long?

**Comment by rsertelon** [comment]
@eeyun With the recent blog post about discourse, what should we do here?

**Comment by tashimi** [comment]
Yup, all the info is here: https://www.habitat.sh/blog/2017/11/Discourse-Migration/ 

Closing this issue out.
