### ISSUE TITLE
[homepage] new builder links are not working

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2539]
app.habitat.sh is the only one working for me:

https://github.com/habitat-sh/habitat/issues/2195

Firefox and Opera

**Comment by ShalokShalom** [comment]
Sorry, I was still sleepy, that is why I opened up a new issue, instead of commenting on the old one. :)

**Comment by fnichol** [comment]
Yeah, l agree, there are some confusing redirects and cnames here

**Comment by cnunciato** [comment]
I think we finally have our URL story straight. 😄 Closing.
