### ISSUE TITLE
[Feature Request] CLI command to fetch current svc config

### ISSUE THREAD

**Issue by johnjelinek** [habitat-sh/habitat#2551]
if I want to get the current config of a service group, I need to curl it, example:
```
$ curl http://localhost:9631/services/consul/default/config

{
  "bootstrap": {
    "expect": "3"
  },
  "client": {
    "bind": "127.0.0.1"
  },
  "ports": {
    "dns": 8600,
    "http": 8500,
    "https": -1,
    "rpc": 8400,
    "serf_lan": 8301,
    "serf_wan": 8302,
    "server": 8300
  },
  "server": {
    "bind": "127.0.0.1",
    "data-dir": "/hab/svc/consul/data/consul",
    "datacenter": "vagrant",
    "loglevel": "INFO",
    "mode": true
  },
  "website": true
}
```

It would sure be nice if I could get the same toml format that I get with `hab pkg config core/consul` but in a new command. Perhaps: `hab svc config consul.default`

**Comment by eeyun** [comment]
@johnjelinek this is a super cool idea. I've labeled this as a mentored issue. It would probably be a fun PR for folks looking to dive into some of the supervisor and cli code!

**Comment by rsertelon** [comment]
@eeyun If I understand correctly, configuration seems to be stored in a file in JSON format (this is how it's retrieved for http response it seems).

So implementing this feature would be converting from json to toml and printing result to cli? If so, I could give it a try.

I see there's a toml lib with `toml::ser::to_string()` which could apparently take a serde json struct. Do you think this would be the way to implement conversion?

I've dug a bit in cli code, and I think I'll be able to implement that part too.

**Comment by eeyun** [comment]
@rsertelon that might be a way to handle it. We already pull in the serde_json crate in the supervisor which would have all of the functions you might need to aggregate that info and print to stdout. I'm on EU time, Builder launched today, and the last of the Community Summits the next few days but I will try to share some places to look through when I get a free moment this week!

**Comment by rsertelon** [comment]
I'm EU time too. No worries, just needed to be sure that I wouldn't do anything useless :) Thanks for your answer, I'll try to implement it then!

**Comment by jeremymv2** [comment]
@eeyun @christophermaier isn't this already implemented, however via [hab config show ..](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L867-L892)?

```
SUBCOMMANDS:
    bldr             Commands relating to Habitat Builder
    cli              Commands relating to Habitat runtime config
    config           Commands relating to a Service's runtime config
```

```
20:44 $ sudo hab config show core/redis
✗✗✗
✗✗✗ [Err: 2] Service not loaded, core/redis
✗✗✗

✘-1 ~/habitat [jeremymv2 L|…1⚑ 16]
20:44 $ sudo hab svc start core/redis
hab-sup(AG): Supervisor starting core/redis. See the Supervisor output for more details.
Supervisor starting core/redis. See the Supervisor output for more details.
✔ ~/habitat [jeremymv2 L|…1⚑ 16]
20:45 $ hab-sup(MR): Starting core/redis
redis.default(UCW): Watching user.toml
...
```

```
✔ ~/habitat [jeremymv2/hook_line_endings L|…1⚑ 16]
20:45 $ sudo hab config show core/redis
appendfsync = 'everysec'
appendonly = 'no'
bind = []
databases = 16
dbfilename = 'dump.rdb'
logfile = '""'
loglevel = 'notice'
min-slaves-max-lag = false
...
```

**Comment by rsertelon** [comment]
@jeremymv2 I think this shows the default config. not 100% sure though

**Comment by jeremymv2** [comment]
🤔 since `hab config show $SERVICE` already exists, I think it makes sense to close this issue in favor of https://github.com/habitat-sh/habitat/issues/5055 and focus on making that command display the _active_ config and not just what is in `default.toml`.
