### ISSUE TITLE
[Feature-Homepage] Add feature to make subheader easily shareable 

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2557]
Move your cursor over the different subheaders here and recognize the symbol next to it:

http://ring-lang.sourceforge.net/doc1.3/languagedesign.html#why-ring

You can share links directly to the specific categories doing this. 
Our Habitat Documentation is already able to share such links when you enter the specific URL by hand.

**Comment by rsertelon** [comment]
I think there have been improvements on that side. The sidebar menu used anchors to link to documentation contents. One could copy these links to answer your need, even if not really as simple as what you propose.

However, titles in documentation that are linked to, are not links to their own anchors. And there's no simple way to find it in the page.

**Comment by ShalokShalom** [comment]
Yes, my suggestion targets (sub)titles in the documentation. 
Often, you want to specifically link to such things. 
I can close this Issue, since I am not interested in Habitat anymore, do as you think.

**Comment by rsertelon** [comment]
No problem @ShalokShalom. There's still a bit more to be done to help other persons navigate/share documentation :)

**Comment by ShalokShalom** [comment]
Oh yeah.
