### ISSUE TITLE
[alias] generate = create

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2558]
I suggest adding `create` as an alias for `generate` since it is shorter and maybe even more common?

**Comment by eeyun** [comment]
As it stands right now we've adopted a strategy/philosophy for the way we alias cli subcommands. We definitely need to document this in our contribution documents / wiki going forward. But the philosophy and strategy we are using we'd prefer to limit creating aliases for commands that are not top level subcommands. For now we're going to close this issue but thank you for bringing our attention to it!
