### ISSUE TITLE
[alias] use easy alias to show local keys

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2559]
Currently, ls /hab/cache/keys is the way to go in order to show the local keys. 
`keys` as alias is doing very fine here. ^-^

**Comment by ShalokShalom** [comment]
I was just curious, what keys are currently in my studio

**Comment by eeyun** [comment]
Lets keep this one open. I think this could be a useful subcommand!

**Comment by ShalokShalom** [comment]
ok, fine ^-^

**Comment by ShalokShalom** [comment]
I think this is solved: https://github.com/habitat-sh/habitat/pull/2714
