### ISSUE TITLE
Patches and more

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2561]
Currently is it not possible to build with more sources than one

I see different use cases for this features, while i guess they all may be a bit different when it comes to their integration

First of, of course, patches: So far as I understand, blocks this issue currently the correct build of libxcb
https://bugs.freedesktop.org/show_bug.cgi?id=95490

So, speaking of that, this issue is one year old and patches seem to exist since then. Since our core/python is up to date is it likely that they didnt find their way yet into the upstream project, for which reason ever. 

I guess that this happens to all of you from time to time

Other use cases are licenses, .desktop files, and app specific files.  

Any other ideas?

**Comment by stevendanna** [comment]
@ShalokShalom On the specific issue, I was able to build libxcb using the core/python2 package: https://github.com/stevendanna/habitat-plans/blob/master/xorg/libxcb/plan.sh

**Comment by christophermaier** [comment]
@ShalokShalom You could use `download_file()` in your `plan.sh` for this; see [the Utility Functions section](https://www.habitat.sh/docs/reference/plan-syntax/#utility-functions) section of the plan reference documentation.

**Comment by ShalokShalom** [comment]
@stevendanna 

@smith already hint me that a few days ago, yes this is working.  thanks

**Comment by ShalokShalom** [comment]
And .desktop files? ;)

**Comment by eeyun** [comment]
Patching right now is definitely supported in the way that you would normally patch C libraries.
We would suggest that for patching source you do the actual patching operation in the `do_prepare()` callback. We have a few examples in the core-plans repo.

For a more complex example I'd suggest checking out the [bash plan](https://github.com/habitat-sh/core-plans/tree/master/bash) or the [glibc plan](https://github.com/habitat-sh/core-plans/tree/master/glibc)!

We'd prefer to minimize the amount of patches we put into our codebase and respect upstream as much as we possibly can. Our pattern for that kind of follows the Nix project and Arch Linux project.

For now I don't think we plan to implement a first class citizen approach to this problem. We'd prefer to keep it as native an experience as possible!

**Comment by ShalokShalom** [comment]
I think i found a good way to implement this: 

1) Add patch options 

_patch_files=(URL)
_patch_shasums=()

You can set both instead in the hab-plan-build.sh, like pkg_patches= and pkg_patches_shasums=

2) Now build with this additional code, that you trigger with the patch options in hab-plan-build.sh 

To do_download()
```
  for i in $(seq 0 $((${#_patch_files[@]} - 1))); do
    p="${_patch_files[$i]}"
    download_file $p $(basename $p) ${_patch_shasums[$i]}
  done; unset i p
```

To  do_verify()
```
  for i in $(seq 0 $((${#_patch_files[@]} - 1))); do
    verify_file $(basename ${_patch_files[$i]}) ${_patch_shasums[$i]}
  done; unset i
```

And to do_prepare() 

```
  for p in "${_patch_files[@]}"; do
    build_line "Applying patch $(basename $p)"
    patch -p0 -i $HAB_CACHE_SRC_PATH/$(basename $p)
  done
```

If there is no callback section specified, add those lines to the do_default sections. 
I mean to make those additional lines invisible for the users. 

We can do that with .desktop files and so on in a similar way and i am really sure, a package manager in 2017 should can do this, since its basic functionality in all those package managers since decades. 
Potential switchers will think Habitat is far behind in the development, if these features are not present.
