### ISSUE TITLE
Pagination on Community Events Page

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#2564]
Currently we are consuming a massive stream of data from the events.chef.io page to populate our community event list. The data we have access to has no pagination and is a bit unwieldy. Right now how we handle the data is to just create event cards for all events.

We should implement some sort of pagination over those event cards!

A theoretical starting point could be to check out listjs.com

**Comment by apriofrost** [comment]
Updated the Community page mockup to include the pagination and filter feature using the same widgets from Blogs page:
https://chef.invisionapp.com/share/BUC52LR3M#/screens/229552733

**Comment by nellshamrell** [comment]
This appears to have been dealt with.
