### ISSUE TITLE
proper endpoint to expose metrics

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/habitat#2566]
Currently using `health_check` hook to expose a metric.

```
# health_check
#!/bin/sh

record_count=$(/bin/sqlite3 /hab/svc/woof/var/woof.db 'SELECT COUNT(*) FROM stuff;')

echo "db_count: $record_count"

> sup-log
woof.default hook[health_check]:(HK): db_count: 288
woof.default hook[health_check]:(HK): db_count: 288
woof.default hook[health_check]:(HK): db_count: 336

> curl http://0.0.0.0:9631/services/woof/default/health | jq
{
  "stdout": "db_count: 336\n",
  "stderr": ""
}
```

It would be nice if there was a way to support exposing metrics that can be placed into the health endpoint.  Would be nice so we can expose counters, stats, etc via this `/health` endpoint or some other sane endpoint.

Something like this:

```
> curl http://0.0.0.0:9631/services/woof/default/health | jq
{
  "stdout": "0 OK",
  "stderr": "",
  "db_count": "336",
  "rps": "1000",
  ...
}
```

**Comment by smith** [comment]
Comments on #1469 indicate we could use a metrics hook to add additional metrics to this existing endpoint.

**Comment by eeyun** [comment]
I think this is a pretty dang good idea. We should discuss further to determine what the appropriate implementation details are but I think you're onto something here.

An endpoint that allows a trivial way for your app to expose metrics that can then be consumed by another service feels like a sweet spot in the habitat wheelhouse.

**Comment by raskchanky** [comment]
Given that https://github.com/habitat-sh/habitat/pull/5986 just merged, I'm going to close this issue.  If there's something further that's needed that that PR didn't cover, feel free to reopen this.
