### ISSUE TITLE
Add additional instructions to the generated README

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2571]
It would be much easier to get started with a plan if it was accompanied by a README file that explained things in further detail. For example, the README could answer questions such as "What can this plan do?", "How should I use it?", etc.

Going forward, we will be encouraging all plan writers to include a README. We can make that a bit easier/more apparent by generating a template README.md (with notes and suggestions) whenever you run `hab plan init`.

The README would be created at the root of the generated directory (by default, it's `/habitat`), and should include the following text (DRAFT):

```
# Name of this package
Add a brief description of the package and what it does

## Authored by
Add the author’s name (person, organization, etc.)

## How to use this plan
Provide clear, step-by-step instructions that describe how to use this package successfully. Questions you should try and answer (if applicable) might include:
- Can a user simply call this pacakge as a dependency of their application or do they need to fork the package into their origin and set some configurations?
- How does it integrate into their developer workflow? (e.g. suppose a user currently uses Docker, Jenkins, etc.)

In addition, call out any relevant topical instructions. Suggested topics have been added below, but feel free to add/remove as needed.

### Configuration updates
If applicable, add information about any built-in configuration that the user can make or whether they need to rebuild for any/all configuration changes.

### Scaling
If applicable, add information about the scaling up/scaling down behavior

### Clustering
If applicable, add information about clustering behavior

### Topology
If applicable, add information about which Habitat topology should be used

### Update Strategy
If applicable, add information about which Habitat update strategy should be used

### Health Monitoring
If applicable, add instructions on how to monitor the health of this service at the application layer

### High Availability
If applicable, add information about setting up HA configuration

### Disaster Recovery
If applicable, add information about setting up HA configuration

### Backup Strategy
If applicable, add information about recommended backup configuration

```

**Comment by rsertelon** [comment]
I think #4077 fixes this issue :)

**Comment by ryankeairns** [comment]
@rsertelon thanks for offering to assist here. This is part of a larger topic where we would display this more robust README in the UI as its own tab. That said, I think the example above needs further definition (or a simple example, perhaps?) before we can add this additional information.

Do you have any thoughts on how to better complete this sample README?

**Comment by rsertelon** [comment]
Hey @ryankeairns I have no specific idea, just wanted to let you know that `hab plan init` now generates a README :)

**Comment by ryankeairns** [comment]
Sure, no problem. I've re-titled this issue and referenced the related issue for adding the README to the package view in the web UI.
