### ISSUE TITLE
[web ui] New Get Started pages

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2577]
We've created a new set of UI design and content for the Get Started pages to help onboarding new Habitat users.

In Get Started, users could walk through a high-level explanation of Habitat and its values, and view the simulated runtime CLI demo without downloading and installing the binary in their machine. 

In each page, we added two new UI features:
- 'Quick Reference', which will provide details-on-demand to help explain new concepts without jumping between docs and tutorials. 
- 'Help icon', which will provide users options to ask questions, give feedback and request features.

The UI work is mostly done. The content will be fleshed out with a separate PR from @davidwrede 

View Get Started UI mockup here:  https://chef.invisionapp.com/share/VKC55C6T6#/screens/238187456

**Comment by cnunciato** [comment]
@apriofrost Is it okay to close this now, or should we make other issues for the items we might still want to take on (like the help icon, etc.)?

**Comment by apriofrost** [comment]
@cnunciato Yeah, we can close it for now. Since we are going to implement Intercom on the site, some of the functionalities may be included. We will chat with marketing and Tasha to see what we can take on with it. Thanks for checking in @cnunciato
