### ISSUE TITLE
[Documentation] How to use third party origins

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2578]
Mention here, how to use third party Origins like Xorg: https://www.habitat.sh/docs/create-plans/

**Comment by eeyun** [comment]
I think custom origins and the core origin are something that we've documented pretty heavily. The create-plans page actually draws us through using `hab plan init` which has a note on automatically populating the plan with the origin that a new user should have set up when they run the `hab setup` command.

The tutorial also covers this and we've got more docs on the plan syntax page. That being said: it might make sense in this paragraph to simply detail what those prefixes mean:

```
It has the name of the software, the version, where to download it, a checksum to verify the contents are what we expect, run dependencies on core/glibc and core/readline, build dependencies on core/coreutils, core/make, core/gcc, libraries files in lib, header files in include, and a binary file in bin. Also, because it's a core plan, it has a description and upstream URL for the source project included.
```

In case someone wants a quick contribution: https://github.com/habitat-sh/habitat/blob/master/www/source/docs/create-plans.html.md.erb#L29

**Comment by ShalokShalom** [comment]
So, the tutorial is already somewhere written? Then maybe link? This gets up again this documentation linking issue.

**Comment by rsertelon** [comment]
@eeyun @ShalokShalom I've added a small note, is it sufficient?

**Comment by ShalokShalom** [comment]
Yes, fine.
