### ISSUE TITLE
[Documentation] How to set environment variables

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2579]
Add here how to actually set this environment variables including one example, like: 

export ENVIRONMENT=variable 

https://www.habitat.sh/docs/reference/environment-vars/

**Comment by eeyun** [comment]
This is going to be OS dependent and not specific to habitat. Mostly the deviation will exist between *nix and dos, it doesn't hurt to have an example of setting an environment variable for folks who have never done so before but it'll definitely be something thats sort of outside the scope of the project.
That being said, I'll drop this in help wanted for someone to get an easy contribution!

**Comment by ShalokShalom** [comment]
I think i can do that for Linux.

**Comment by davidwrede** [comment]
IMHO, I don't think we need to doc this. A certain amount of basic knowledge is assumed when working with bourne-type shells or Powershell. If you disagree, feel free to re-open.

**Comment by ShalokShalom** [comment]
This one here is Habitat specific.

**Comment by rsertelon** [comment]
@ShalokShalom how so, could you describe what you mean here please? :)

**Comment by ShalokShalom** [comment]
I oversaw the next section, which makes it more clear. 
Well, I think "Customizing Studios" could be above the list of environment variables to make it more obvious. In this case, change "above" in the text into "below".

I am still thinking, that a simple one-liner could make things easier to understand. 
What speaks against that?

**Comment by rsertelon** [comment]
So you want actual examples on how we can use documented variables in a habitat context, is that right? like documented, for example, for the `HAB_PACKAGENAME="<toml content>" hab start my/service`?

**Comment by ShalokShalom** [comment]
Like in the [first post](https://github.com/habitat-sh/habitat/issues/2579#issue-235670475) here.
