### ISSUE TITLE
[Documentation] How to use an exported tarball 

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2580]
![screenshot_20170607_093803](https://user-images.githubusercontent.com/6344099/27101275-6440703a-5081-11e7-822f-547a08bceba1.png)

**Comment by eeyun** [comment]
Yep. This is another good one. Its easy to forget that not everyone is using containers all the time so showcasing habitat behaviors that make running software anywhere easy is a very good thing. This actually might serve better if we had a blog post to accompany it!

**Comment by rsertelon** [comment]
Should this fit in https://www.habitat.sh/docs/developing-packages/#exporting-to-a-tarball or should it be in https://www.habitat.sh/docs/best-practices/ (with a dedicated page, that might be quite small)?
