### ISSUE TITLE
[www] Add recruitment link to Community page and footer

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2589]
We're setting up a recruitment form at uxresearch.habitat.sh in https://github.com/habitat-sh/habitat/issues/2541 

Once that is setup, we can reference the link in the following places:

- [ ] Community page
- [ ] Site footer

@apriofrost please provide a mockup on how you'd like that to look. Thanks!

**Comment by apriofrost** [comment]
Hey @ryankeairns I updated the community page and the footer to include links to the research form. 
As we discussed before, there would be a separate UX research form for Habitat community.
To view and comment on the mockup: https://chef.invisionapp.com/share/VJCB5YZ6M#/229552733_Habitat_Web_-_Community

**Comment by rsertelon** [comment]
@apriofrost @ryankeairns is this issue fixed then? :)

**Comment by apriofrost** [comment]
@rsertelon Not yet :) Still waiting for the development. I may need to update the cat since we now have a new Habicat look.

**Comment by rsertelon** [comment]
Oh misread then sorry :) when you said `updated` I thought about the code, not the mockups ;)

**Comment by apriofrost** [comment]
@rsertelon The code needs updates as well. It is not on the website currently. Would you like to pick it up? I can update the mockup fairly quick.

**Comment by ryankeairns** [comment]
I'm not sure if we still want to do this and survey would need some updates as well. Lets hold off on doing anything just yet.

**Comment by apriofrost** [comment]
@ryankeairns OK!

**Comment by cnunciato** [comment]
Closing as no longer a current priority.
