### ISSUE TITLE
[web ui] Remove Depot link from the top navigation & Homepage url jump for signed-in users

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2590]
The Depot link in the top navigation is confusing - it links to 'Search Packages' for both signed-in and non-signed-in users, which is only one part of the Depot experience, and has been enabled by the 'Search Packages' widget in 'Explore' page in the top navigation.

For a signed-in user, the homepage with the marketing content is not helpful anymore. The default homepage should be their dashboard (https://bldr.habitat.sh/#/).

Two tasks are indicated:
- [x] 1. remove the Depot link in the top navigation from both the www and blder sites.
![image](https://user-images.githubusercontent.com/9401459/27104058-cbda248a-503f-11e7-8403-52f75ab2c9b8.png)
- [ ] 2. If a user has already signed in, when they type in 'habitat.sh' in the browser, the site will jump directly to https://bldr.habitat.sh/#/, where the homepage is the Depot with Dashboard selected.

**Comment by ShalokShalom** [comment]
Consider renaming "Explore" into "Packages" ;)

If that is thinkable, i can create an own issue for that one.

**Comment by apriofrost** [comment]
Hi @ShalokShalom , for the "Explore' page, we wanted to be the place where new users could see the values of Habitat. Not just what's out there in the package depot, but also other values Habitat brings. Such as the Scaffolding, continuous compliance and much more.

**Comment by ShalokShalom** [comment]
And where will you put this menu?
![screenshot_20170619_083723](https://user-images.githubusercontent.com/6344099/27272477-9298e730-54ca-11e7-8669-7e52ca81822b.png)

**Comment by apriofrost** [comment]
@ShalokShalom This page will be the default home page if you have signed in. You can return to it by clicking the logo.

**Comment by ShalokShalom** [comment]
i see, i quickly assumed https://bldr.habitat.sh/ is the explore page

thanks a lot dear

**Comment by tashimi** [comment]
Closing this one out based on convo in #general today
