### ISSUE TITLE
[core-plans] Fix failing core plans

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2603]
There are a number of core plans that no longer build.
See the gist here for the failures:
https://gist.github.com/chefsalim/6748bb6bb3319ad6b9b8d43322b4f96b

**Comment by eeyun** [comment]
I was able to build `core/libpcap` yesterday without any trouble. Also I wonder if this issue shouldn't go on against the core-plans repo, unless these build failures are specific to builder.

**Comment by chefsalim** [comment]
Closing - issues for broken core plans should be entered in core plans depot
