### ISSUE TITLE
[builder-web] Handle 404s on package pages

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#2612]
For known bad package URLs:

https://bldr.habitat.sh/#/pkgs/hahanodoesntexist/nonsensepkgetc/0.1.0
https://bldr.habitat.sh/#/pkgs/hahanodoesntexist/nonsensepkgetc/0.1.0/20170615150934

.. we should render a more appropriate "not found" view.

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #292](https://github.com/habitat-sh/builder/issues/292) via [**ZenHub**](https://www.zenhub.com/)
