### ISSUE TITLE
[web ui] Reduce fixed header size & add GitHub tab on it

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2615]
The current fixed header on the site takes too much real estate on the screen (about 122 px in height). See the screenshot from @ShalokShalom 's 15.4- inch screen.
![screenshot_20170616_202442](https://user-images.githubusercontent.com/9401459/27240029-175fece2-5288-11e7-91a6-ae35d1f526cf.png)

The suggested design is to make it shorter (about 77px in height). See the screenshot from the mockup:
![image](https://user-images.githubusercontent.com/9401459/27240707-b9c185f2-528a-11e7-8b91-7e456c78f174.png)

Another suggested improvement on the design is to replace the current GitHub ribbon with the tab style. So that it can fit into the fixed header and always available.
![image](https://user-images.githubusercontent.com/9401459/27240797-10f3a5bc-528b-11e7-80c4-3705a7bf02aa.png)

To inspect the mockup: https://chef.invisionapp.com/d/main#/console/9499228/229572977/preview

**Comment by ryankeairns** [comment]
We might also want to reduce the logo size when it's fixed... it's hugging rather close to the bottom of the fixed nav background.

**Comment by apriofrost** [comment]
@ryankeairns Yeah. For sure! (as a designer from agencies, I often struggled with the logo being not big enough from the clients' point of view) :D

**Comment by ryankeairns** [comment]
Haha!

https://youtu.be/5AxwaszFbDw

**Comment by rsertelon** [comment]
@apriofrost @ryankeairns @eeyun  it seems that there's no more fixed header on the website and bldr. Is this issue still a thing? :)

**Comment by apriofrost** [comment]
I think we turned off the fixed header off after the Builder launch on Oct 9th. There were some complaints about it covering too much content underneath.

**Comment by ryankeairns** [comment]
The fixed header was removed here: https://github.com/habitat-sh/habitat/pull/3849
