### ISSUE TITLE
[documentation] Update 'view' with 'channel'

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2616]
In the Supervisor Internal doc, under Architecture, we refer the concept of 'channel' as 'view'. Maybe we should update the name:

> Rings are further divided into service groups, each of which has a name. All supervisors within a service group share the same configuration and topology. It is typical to name each service group using the pattern service_name.environment and have these service group names correspond to a **view** within the depot. In this way, the supervisors can self-update whenever the **view** is updated. For more information on this, please read the continuous deployment topic.

Link to the doc: https://www.habitat.sh/docs/internals-supervisor/

**Comment by davidwrede** [comment]
Easy fix. I'll get a PR out shortly.
