### ISSUE TITLE
Add Habitats package search engine to the browser

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2619]
Hi there :)

![screenshot_20170617_081937](https://user-images.githubusercontent.com/6344099/27250710-015ddad6-5336-11e7-8b02-988cb99afe2a.png)

Firefox provides us with the feature to add search engines to its search bar.
The habitat package search engine does not support that now. 

I guess the implementation counts for other browsers then too.

**Comment by rsertelon** [comment]
Tried to implement it, but was blocked by #3435 . It is now fixed, but does not seem to be deployed to https://bldr.habitat.sh. Any idea about when it will please? :)

**Comment by rsertelon** [comment]
I can see this has been fixed in production. Will try to impl then :)

**Comment by rsertelon** [comment]
@ShalokShalom Implemented :)

**Comment by ShalokShalom** [comment]
Fine, thanks.
