### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2636]
Currently is the explore and depot page aimed for developers.

It may be worth to focus on casual users and their home servers as well, with a page like that: 
(The link to it can replace that one of the depot: https://github.com/habitat-sh/habitat/issues/2590)

https://www.flockport.com/store/
![screenshot_20170621_182752](https://user-images.githubusercontent.com/6344099/27395236-6839b348-56af-11e7-8dd0-9594f7b83f36.png)

**Comment by nellshamrell** [comment]
This is something we are trending towards with the explorer page https://bldr.habitat.sh/#/explore.  It will continue to evolve :)
