### ISSUE TITLE
[builder ui] Allow editing/deleting origin names when there is no package uploaded to it

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2640]
People make typos and mistakes, our UI should support 'undo' when it doesn't cause other usage issues -- such as if there's no packages and no neighborhood connected.

This may be particularly important when a new Habitat user go through the new 'download and install' steps, which will guide them to the builder UI to create an account and the first origin.
The reason why we want to guide them to the UI (instead of the CLI) to create the origin is that we can validate if the origin is not taken by others upfront.

**Comment by eeyun** [comment]
THIS SO MUCH. We've needed the ability to remove origins that have no packages for a while now. I think this request kind of goes hand in hand with #1051 . I squatted on origins at launch expected to be able to delete them and not been able to so I have like 10 that I don't need.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #26](https://github.com/habitat-sh/builder/issues/26) via [**ZenHub**](https://www.zenhub.com/)
