### ISSUE TITLE
[Documentation] Document `sup-run` studio functionality

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2645]
If i have a studio which is not running a sup, how do i start a new one in the background... not the foreground?

**Comment by ShalokShalom** [comment]
Answer: 

`sup-run` or `sr`

`sup-run` is a function in the studio that starts the sup in the background and logs to a specific file.

**Comment by tashimi** [comment]
`hab sup run` is included in the cli docs upgrade [3162](https://github.com/habitat-sh/habitat/pull/3162)

**Comment by davidwrede** [comment]
Also described in #3154.
