### ISSUE TITLE
Implement feature to auto-upload a successful build

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#2651]
This can help us to avoid situations, in which we forgot to upload a package after the build and it is more comfortable anyway. 
Once someone assume, that he/she uploaded a package, while its not, might this cause issues with the packages who are build upon it and so on. 

I think about an environment variable, which auto-uploads a successful build and it seems suitable to ask the user to confirm this with a simple y/n.

P.S: As an (additional) alternative consider `upload` as an alias for `hab pkg upload latest_package`

Thanks a lot

**Comment by ShalokShalom** [comment]
As an alternative consider `upload` as an alias for `hab pkg upload latest_package`

**Comment by fnichol** [comment]
At the moment, the activity of building a package and uploading it are seperate for a few reasons:

* we may not know the intended destination for the package (is it the default depot, a custom depot, a specific channel, etc)
* the package being built might contain proprietary code and *cannot* be uploaded
* the package being built might be an experiement and not intended for production.

---

There might be a workaround here though which I believe we haven't documented enough:

Every time a build is successful a file called `./results/last_build.env` will be written which contains shell variables for the package identifier, the full .hart file name, shae256 sums, etc. A post processing step of `(. ./results/last_build.env && hab pkg upload ./results/$pkg_artifact)` should provide an equivalent for those who desire this kind of workflow.

**Comment by ShalokShalom** [comment]
Again, i dont get why you close this issue, without any chance by me, to answer on it while open.

1) You can specify that. Most users might prefer a default origin. The question can be: 
Do you like to upload this package to ___? Y/N

2) This is anyway always the case. 

3) Same. 

You seem to jump over "and it seems suitable to ask the user to confirm this with a simple y/n." in my text?
