### ISSUE TITLE
[chore] pg_restore will not restore public keys from current prod to acceptance

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2657]
Recently we made a change in acceptance to disallow duplicate origin keys.  However, in production we are still running the old datastore which has duplicate keys.  

pg_restore fails to restore the public origin keys table(s) that have duplicates.

We need a solution to this in order to restore data from prod, and also a plan for when we upgrade prod.

**Comment by raskchanky** [comment]
Is it worth building a tool for this or would it be easier to just take a production outage where we manually remove the duplicates and migrate the production db to the latest schema?  Doing the latter is manual work, which is a bit of a bummer, but it's likely going to be a lot quicker than building a tool to somehow patch pg_restore and also upgrade the production db.

**Comment by mwrock** [comment]
Didnt we include a migration that handled the deduping? If so I'd think just a deployment would be necessary.

**Comment by raskchanky** [comment]
I remember talking about such a migration but I'm not sure one ever got written.  We'd need to make sure it got run before the migration to add the index back.

**Comment by raskchanky** [comment]
@mwrock No, you're right.  Migrations exist for both public and private keys:

https://github.com/habitat-sh/habitat/blob/master/components/builder-originsrv/src/migrations/origin_public_keys.rs#L89-L110

https://github.com/habitat-sh/habitat/blob/master/components/builder-originsrv/src/migrations/origin_secret_keys.rs#L74-L95

**Comment by raskchanky** [comment]
I think @mwrock is right and all we need to do is deploy to prod and pg_restore will work again.  I'm going to close this.
