### ISSUE TITLE
[Plan-Build] Composite Plan feature

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2661]
Add a feature to the Plan syntax to describe a service which is only of use when started with one or more additional services within the same Supervisor. An example of this is the relationship between a proxy and api server or php applications.

This will be a new pkg variable or a slightly different file name for a plan. The generated package is a "pointer" to other packages and forces all operations to be atomic - that is, if you start the composite package then all services it points to will also be started.

In the composite plan we will also need to map it's `pkg_binds` and `pkg_exports` to the packages it is composed of. This will require some small modifications to service rumors to identify a "composite package".

See #2520 for the initial discussion start

**Comment by smith** [comment]
More detail is in #2902.
