### ISSUE TITLE
Non-semantic Version Sorting Failure

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#2664]
There's an issue in a subset of non-semantic version sorting at build-time.

The only packages I've seen exhibit this are specifically the oracle versions within the JDK package.
The most recent example popped up with `core/jdk8/8u131`.

Repro: If you create a package with `pkg_deps=(core/jdk8 core/tomcat8)` the collision will occur at build time in which the "latest" version of `core/jdk8` that gets returned is in fact NOT the latest version and as such will conflict with tomcat. The jdk8 package will instead return `core/jdk8/8u92`.

I haven't had a chance to look through the code to try to deduce what the actual root cause is. But I _think_ just from looking through the UI it looks like its possibly related explicitly to the way we handle sorting of available packages/builds. If you hit the depot and look at the available jdk8 packages they get returned in the order below:
```
core / jdk8
package

VERSIONBUILDSLATEST
8u92 3 2016-06-20
8u131 1 2017-06-22
8u111 4 2017-05-14
8u102 2 2016-10-31
```

**Comment by rsertelon** [comment]
I've dug into source and found the [function that sorts versions](https://github.com/habitat-sh/habitat/blob/master/components/core/src/package/ident.rs#L270).

The documentation of the method clearly explains why java versions sorting fails. They are sorted lexicographically (as one would suspect).

Maybe we could support other separators for version numbers, but it's hard to define which ones. To make it work for java, `u` must be one of them. `.` is obviously one too. Maybe all unique characters that are not numbers could be used as separator?

Don't know if there are other versions than java that have this problem though. Can someone if core team check if there are version numbers without `.` in bldr data? I feel like this might be the only case...

If so, they changed the version scheme from java 9 onwards, so is it worth modifying our version sorting policy for this case? Maybe we could instead change java versions in core plans (although it may not feel right either ^^).

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #27](https://github.com/habitat-sh/builder/issues/27) via [**ZenHub**](https://www.zenhub.com/)
