### ISSUE TITLE
[web ui] Make blog page responsive on mobile devices

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2666]
Problem: The current blog page left column doesn't collapse/repond to smaller screens.
![image](https://user-images.githubusercontent.com/9401459/27652145-86e298a6-5bef-11e7-9806-89f66276858e.png)

Need a new UI design for this page for smaller screens.

**Comment by rsertelon** [comment]
Also, there are many tags now, and they eat up lots of space. Maybe they could take less place too? :)

**Comment by apriofrost** [comment]
Good suggestion! will definitely take it into consideration for the next design iteration. Thanks, @rsertelon !
