### ISSUE TITLE
[www] Make the Depot URL configurable

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#2676]
We currently default to bldr.habitat.sh as the Depot URL, but in environments like dev or acceptance, we should honor a configurable URL to make navigation (e.g., from the main navigation bar, footer, etc.) operate more seamlessly.

**Comment by eeyun** [comment]
@cnunciato can you clarify where you imagine this configuration to happen? Are we talking about via the build service or in our packages/runtime of those things?

**Comment by cnunciato** [comment]
@eeyun There's a [setting for this now](https://github.com/habitat-sh/habitat/blob/4e3a088df6c537075c7f6f12382e52b010f84029/www/config.rb#L79) -- we just need to set that environment variable for it when we deploy to acceptance and start up in dev.

**Comment by cnunciato** [comment]
[Fixed with this change](https://github.com/habitat-sh/habitat/blob/0a219d01377a529b37556b1728757bd9ff898613/support/ci/deploy_website.sh#L13).
