### ISSUE TITLE
[web ui] Add and replace tutorial pages

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2683]
- [x] Add a new landing page for tutorials

- [x] Replace the current tutorial pages with new content and layouts.

The purpose of the new layout design is to make the web pages responsive to different screen sizes and devices(GUI v.s. NUI). So that Habitat users can enjoy the content and services on a wide range of devices they use.

View mockup here: 
Desktop view: https://chef.invisionapp.com/d/main#/console/9499228/239663661/preview
Tablet view: https://chef.invisionapp.com/d/main#/console/11538084/243716677/preview
Mobile view: https://chef.invisionapp.com/d/main#/console/10087644/242540052/preview

**Comment by ShalokShalom** [comment]
Do i need a special account for this one?

**Comment by tashimi** [comment]
These are now live on the site https://www.habitat.sh/tutorials/ !
