### ISSUE TITLE
Automated Backups

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2693]
1. We need automated disk and database backups
2. We need a reliable way to do snapshots (if snapshots are the backup strategy) 
3. Look into implementing Postgres DR / backup solutions (someone mentioned S&W's shield last week)
4. Investigate running Postgres in HA mode - don't rely on a single instance (another S&W follow-up)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #28](https://github.com/habitat-sh/builder/issues/28) via [**ZenHub**](https://www.zenhub.com/)
