### ISSUE TITLE
Builder Operations RunBook

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2694]
1. We need to have an operations run-book that walks through typical operations on the production site - eg, re-creating / re-depolying builder nodes, recovering from datastore or package backups, etc.
2. The run-book should include how to communicate outages
3. It should also include information on alternate communication mechanisms for the team (eg, in case Zoom is not working)
4. It should include procedures for AWS and Terraform tasks as well 
5. Run-book tasks should be regularly practiced / practicable.

**Comment by nellshamrell** [comment]
Update -

I've got a new, basic builder environment terraform config working in a branch of the cloud_environments repo.  I still need to add in instructions for setting up github, testing builds, etc.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #29](https://github.com/habitat-sh/builder/issues/29) via [**ZenHub**](https://www.zenhub.com/)
