### ISSUE TITLE
Get Packages off disk and onto S3

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2697]
Currently we are storing the package repository on disk.  We should get them into S3 in order to reduce the incident surface area and reduce backup/restore tasks.

**Comment by mwrock** [comment]
also see #1933 for more context

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #30](https://github.com/habitat-sh/builder/issues/30) via [**ZenHub**](https://www.zenhub.com/)
