### ISSUE TITLE
Branch & tag specification for Builder builds

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2698]
We should be able to specify a branch or a tag for builds that are kicked off via the Builder.
Currently, the site shows only a 'Request Build' button without being able to customize anything.

**Comment by eeyun** [comment]
@reset and @chefsalim can you verify if this was incorrectly added back into the issues stack?

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #31](https://github.com/habitat-sh/builder/issues/31) via [**ZenHub**](https://www.zenhub.com/)
