### ISSUE TITLE
Problems with finding packages in depot

### ISSUE THREAD

**Issue by alexey-pankratyev** [habitat-sh/habitat#2700]
- OS: 
        CentOS Linux release 7.3.1611 (Core)

I have a problem's
    - Debug/backtrace:
       WARN No installed packages of 'cvasquez/sbt/0.13.15' were found ERROR: Resolving 
       'cvasquez/sbt/0.13.15' failed, should this be built first?" or " No installed packages of 
       'dmitrijfedorov/kogia/lite' were found 
       ERROR: Resolving 'dmitrijfedorov/kogia/lite' failed, should this be built first?"
 
There were problems not only for me:
     - Debug/backtrace: 
	```07:49:52 » Installing smartb/api_requirements from channel 'stable'
           07:49:53 ∅ The package does not have any versions in the specified channel.
           07:49:53 ∅ Did you intend to install one of the folowing instead?
           07:49:53 ∅   smartb/api_requirements/0.0.1/20170629134736 in channel unstable
           07:49:53 ✗✗✗
           07:49:53 ✗✗✗ Package not found
           07:49:53 ✗✗✗
           07:49:53    api: WARN No installed packages of 'smartb/api_requirements' were found
           07:49:53 ERROR: Resolving 'smartb/api_requirements' failed, should this be built first?```

**Comment by guskovd** [comment]
+1
Does this mean that i need to install your own packages like this:
```bash
hab pkg install my_origin/package -c unstable 
```
?

**Comment by alexey-pankratyev** [comment]
With version 25 you need to put the packets in a stable channel  ` hab pkg promote  test/test stable`
Bypass route hab studio run `HAB_DEPOT_CHANNEL=unstable build`
