### ISSUE TITLE
HAB_WINDOWS_STUDIO ignored in windows studio v25.0

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#2701]
It looks something broken in version 25:0

```powershell
$env:HAB_WINDOWS_STUDIO=1
cd /path/to/windows/plan
hab pkg build .
```

```powershell
✗✗✗
✗✗✗ `docker' was not found on the filesystem or in PATH
✗✗✗
```

**Comment by guskovd** [comment]
I read changelog, Found the correct command for building packages
```powershell
hab studio build . -w
```
=
---
Probably need to add a similar logic in hab pkg build ?

**Comment by reset** [comment]
@mwrock I think you were fixing this one up before our hotfix today?

**Comment by mwrock** [comment]
yup...incoming
