### ISSUE TITLE
Change hab pkg install logic

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#2722]
We need to do two things:

1. If you do a `hab pkg install` and you specify a fully qualified package name, e.g. `hab pkg install core/redis/3.2.4/20170514150022` and that fully qualified package is _not_ in the channel you've specified (either explicitly via the `--channel` flag or the implicit `stable` channel) then the `hab` CLI should warn you that we're going to install the package anyway, even though it's not in that channel.

2. For all transitive dependencies, we need to ignore the channel completely and just straight up install them.  Transitive dependencies are always fully qualified so there's never any ambiguity and warning the user in this case is not necessary.

**Comment by fnichol** [comment]
Totally, A++ here!

**Comment by raskchanky** [comment]
From what I can tell by reading through the code, for fully qualified packages, we are already doing the right thing by download regardless of channel.  Specifically, item 2 in the list above is how things are today.
