### ISSUE TITLE
Implement `--peer-watch-file` flag for joining the ring

### ISSUE THREAD

**Issue by krnowak** [habitat-sh/habitat#2735]
This flag could be used instead of the `--peer` flag; it would take a path to a file as a value. It would then watch it for changes (with inotify or something more portable). The contents of the file should be one or more IP addresses, just like in the `--peer` flag.

This would solve the issue of a different invocation for the initial supervisor in K8s, as all the invocations would include the `--peer-watch-file` flag. The file would be provided by the k8s controller/operator.

Also, you don't need to set up the k8s cluster to test this solution.

**Comment by adamhjk** [comment]
Interesting. In this use case, is the file itself guaranteed to have every member in it? 

i.e. - as we launch more services, will every peer be here? Or is this something that gets seeded with some smaller set somehow?

**Comment by krnowak** [comment]
@adamhjk: I was rather thinking that it would serve as a seed only. When the supervisor is in the ring that has more than one different supervisor in it, it would stop caring about it. So, something similar to the `--peer` flag, but with the file that may not exist when starting the supervisor.

It can contain all the services, why not? But it is not required, in the same way like you don't need to pass all the services through the multiple `--peer` flags - one is enough.

In our k8s case, the file would be created by habitat-k8s operator after it starts all the supervisors. It would put there an IP address (and port number) of the first supervisor. The supervisors will need to be a bit smart about filtering out the entries there that has their IP address and port. The operator will need to take into account a situation where the first supervisor goes away (gets killed, crashes, or whatever) - the operator will need to update the peers file to contain the IP address of the other supervisors that are still alive, so the new supervisor the operator creates in place of the killed one will know how to join the ring.

@asymmetric: Does this sound good?

**Comment by adamhjk** [comment]
Sure - I don't quite understand what an operators role is here, but I don't necessarily need to. The idea that there is a peers configuration that you can update feels legit.
