### ISSUE TITLE
Cross platform issues with /bin/sh and bashisms

### ISSUE THREAD

**Issue by lnxchk** [habitat-sh/habitat#2736]
Hi!

I'm currently working on a project that uses the core/mysql plan.

Platform:  Ubuntu 16.04 with hab 0.25.1/20170708004945

Top line issue: On this platform, core/mysql doesn't run due to the use of a bash-specific option to the "set" command in the init hook.

Error message:
sudo hab start core/mysql 
hab-sup(MR): Supervisor Member-ID 36cc6b5333104e589fd69108ea38cff1
hab-sup(MR): Starting core/mysql
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
mysql.default(SR): Hooks recompiled
mysql.default(SR): Initializing
mysql.default hook[init]:(HK): /hab/svc/mysql/hooks/init: 5: set: Illegal option -o pipefail
mysql.default(HK): Initialization failed! 'init' exited with status code 2

Cause:
Ubuntu uses the dash shell by default.
/bin/sh is a symlink to /bin/dash
The shebang line in the hab hooks is /bin/sh
The init hook is using "set -eo pipefail" for the setup of the database
/bin/dash doesn't support "-o pipefail" and hab start fails

Fixing the core/mysql is easy enough, such as removing pipefail or explicitly selecting /bin/bash for the shebang if pipefail is necessary, but it would be helpful for the larger habitat community to have some guidance around either using /bin/bash explicitly or suppressing bashisms for portability with help from a linter or other tool.

**Comment by smith** [comment]
If it's in a hook and you need a real bash, you can have a `pkg_dep` on `core/bash` and make your shebang be:

    #!{{pkgPathFor "core/bash"}}/bin/bash

this is not done consistently in core plans, but it is often necessary if you're assuming authentic bash. Using `/bin/bash` can even fail sometimes if you end up using Busybox bash or some other thing that claims to be bash but is not.

**Comment by eeyun** [comment]
Yep. This is definitely something that we should have discussion around. The workaround above is certainly a clean and easy way to avoid this situation with any of the core plans but it brings with it a bit minor complication. Primarily if we change the run hooks of our core plans to use the `#!{{pkgPathFor "core/bash"}}/bin/bash` we end up in a situation where you MUST have the bash core plan installed on a system in order to run any of those packages. It's not the end of the world, but we should discuss it.

**Comment by stevehill1981** [comment]
I just ran into this issue when following the instructions in https://www.habitat.sh/blog/2017/07/Habitat-mysql-cluster/.

Given that's probably one of the first things anyone new to Habitat will try, should the blog post at least be updated so that this issue is fixed? :)

**Comment by rsertelon** [comment]
This has been fixed directly in the `core/mysql` plan by https://github.com/habitat-sh/core-plans/pull/838 (merged Oct 10th 2017).
