### ISSUE TITLE
Document template helper functions

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#2775]
As a Habitat package author, I would like to know what helper functions are available to me in templated files.

Currently we have a [handful of helper functions](https://github.com/habitat-sh/habitat/tree/master/components/sup/src/templating/helpers), but their existence and proper usage don't appear to be documented anywhere.

**Comment by webframp** [comment]
Does this count? https://www.habitat.sh/docs/create-packages-configure/#advanced-helpers

**Comment by eeyun** [comment]
Yeah I think these are in fact documented on the page that @webframp shared there. I'm not aware of any other handlebars helpers that ARENT documented there? 

If so, perhaps we have a discover-ability issue @christophermaier?

**Comment by reset** [comment]
Gonna close this one out - things are documented but after switching our search from google to the new platform discoverability went to hell
