### ISSUE TITLE
development version of `hab-sup` can be installed under certain circumstances

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#2789]
We use a shared `servers` cookbook to pin the version of `hab` to 0.25.1 currently.

After calling this cookbook, we then use the `habitat` community cookbook to set up our Supervisor like:
```
hab_sup 'default'
```

This appears to have the unwanted side-effect of installing a development version of `hab-sup`:
```
$ hab --version
hab 0.25.1/20170708004945

$ hab sup --version
hab-sup 0.27.0-dev/20170720002931
```

**Comment by wduncanfraser** [comment]
@smartb-pair Just as an FYI, after discussion with @tas50 yesterday he opened https://github.com/chef-cookbooks/habitat/pull/41 for the community cookbook. 

Though it may make sense for hab to ensure it always installs the proper version of hab-sup (for example when you do a hab sup run and sup isn't already installed, it installs a version matching the hab version)

**Comment by reset** [comment]
The Habitat cookbook is a separate project and not maintained by the Habitat team. I've made recommendations to @tas50 to lock the version of the supervisor installed to that of the version of the cookbook itself to avoid this issue in the future
