### ISSUE TITLE
Depot: Search does not retain phrase when going back to search page

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2790]
This is an annoyance that would be nice to fix.

1. Type in a phrase in the search bar (eg, 'builder')
2. Select one of the entries in the list of found packages (eg, to look at the build date)
3. Hit back on browser

Result is that the search phrase is lost, and has to be re-typed.
Expected: search phrase is retained.

**Comment by eeyun** [comment]
@reset and @chefsalim can you verify if this was incorrectly added back into the issues stack?

**Comment by reset** [comment]
For another reader: This isn't crucial to a particular milestone right now so we removed it from the board

**Comment by cnunciato** [comment]
This actually works if you press enter in the search box, because that submits the query and changes the URL, but few users will probably do that, so we should probably look into handling the behavior described here as well.
