### ISSUE TITLE
hab install --binlink fails if file exists at destination

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#2798]
If I'm doing a `hab install --binlink` which installs multiple binaries, but one of those binaries exists at the destination, the whole install will fail:

```
$ ls $(hab pkg path core/openssh)/bin
scp  sftp  ssh  ssh-add  ssh-agent  ssh-keygen  ssh-keyscan
$ sudo hab install core/openssh --binlink
» Installing core/openssh from channel 'stable'
→ Using core/openssh/7.5p1/20170711154302
★ Install of core/openssh/7.5p1/20170711154302 complete with 0 new packages installed.
» Symlinking sftp from core/openssh/7.5p1/20170711154302 into /bin
✗✗✗
✗✗✗ File exists (os error 17)
✗✗✗
```

This behavior seems wrong: it will go through and symlink things until one fails, then it will stop.

What is should do is either:

* Fail completely if any of the files it's planning to symlink already exist
* If it finds a file that already exists, print a warning and attempt to complete the rest of the symlinks

**Comment by christophermaier** [comment]
Closing this, since it references old behavior; see discussion on the closed PR above.
