### ISSUE TITLE
Group setting ignored by first node

### ISSUE THREAD

**Issue by thommay** [habitat-sh/habitat#2814]
When starting the first node in a ring, the `group` setting is ignored.

```
root@ip-172-31-13-6:~# hab start thom/container_sched_backend  --group prod
hab-sup(MR): Supervisor Member-ID 403b975c08d34cc481b9f43a01ade5ef
hab-sup(MR): Starting thom/container_sched_backend
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
container_sched_backend.default(SR): Hooks recompiled
container_sched_backend.default(SR): Initializing
container_sched_backend.default(SV): Starting service as user=hab, group=hab
container_sched_backend.default(O): I am a follower
```

however, when i join a second node, it gets the group correctly:
```
ubuntu@ip-172-31-6-82:~$ sudo hab start thom/container_sched_backend --peer 172.31.13.6 --group prod
hab-sup(MR): Supervisor Member-ID 9a270e63587b44399b041c510a018148
hab-sup(MR): Starting thom/container_sched_backend
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
container_sched_backend.prod(SR): Hooks recompiled
```

Debug logs from the first node are at https://gist.github.com/thommay/aebc3bbb1ba6ba7464113c6723078d8d 

Running on ubuntu 16.04 in ec2.

code/plan etc: https://github.com/thommay/container_sched_backend

**Comment by reset** [comment]
@thommay can you run `hab svc status` and show the output? I think this is because the previous service was loaded with `hab svc load` and then start is preferring it's loaded config. You can't override the config with `hab svc start`, but we probably should raise a warning

**Comment by thommay** [comment]
```
sudo hab svc status
thom/container_sched_backend/0.1.0/20170719112337, state:up, time:PT29.612813509S, pid:32259, group:container_sched_backend.default, style:transient
```

I just checked back through my bash history, and i only ever used `start`, although i did run without specifying a group the first time, so that sounds like what's happened. A warning (or just a flat out refusal to run) would be good.

**Comment by christophermaier** [comment]
Closing since the functionality of the `start` command has changed drastically with the 0.56.0 release.
