### ISSUE TITLE
Show streaming build output for public packages when not logged in

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2824]
Right now, to see the streaming log output (Build output) tab, you have to be successfully logged into builder. For public origins, this becomes a functionality discoverability issue. Let's show this tab to non-logged in users too. 

E.g. https://bldr.habitat.sh/#/pkgs/core/testapp/0.1.0/20170717235348

Private origins/packages in the future will not want this displayed to non-authenticated users.

**Comment by reset** [comment]
Closed by #2967
