### ISSUE TITLE
Add channels to the build output page

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#2825]
When viewing build output, the channel tags should appear in the build metadata section above the streaming output.

A mockup of the desired UI design is here:
https://chef.invisionapp.com/share/3ZBKYLQTW#/240518817_channels_Mvp_-_Build_Output

![screenshot 2017-07-25 16 39 49](https://user-images.githubusercontent.com/446285/28595075-e5d900a2-7157-11e7-903c-643cc36095b0.png)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #32](https://github.com/habitat-sh/builder/issues/32) via [**ZenHub**](https://www.zenhub.com/)
