### ISSUE TITLE
Supervisor is not restarting processes when they are updated

### ISSUE THREAD

**Issue by afiune** [habitat-sh/habitat#2832]
## Problem
OS: Ubuntu 16.04
Habitat version: 0.26.1

The supervisor stop restarting the processes that needs to be restarted when there is a package update. You can replicate this behavior from within a *studio*:
1) Enter your studio.
2) Build your service/app.
3) Start the service under the control of the habitat supervisor. 
4) Update your code and re-build your service/app.

If you tail the supervisor logs, you will see an output similar to this one: 
```
service.default(SR): Updating service afiune/service/0.1.0/20170725145636 to afiune/service/0.1.0/20170725150000
service.default(SR): Hooks recompiled
```
But the service never gets restarted, so it wont actually update it with the new code even though it detected the update.

cc/ @reset 

## Workaround
Rollback to Habitat version `0.25.1`

**Comment by reset** [comment]
@afiune I just tested this in our acceptance environment with the Supervisor that's going out today (0.27.0) and all seems well. Please reopen if you see this behaviour again after today's release!

**Comment by afiune** [comment]
![tenor-190588317](https://user-images.githubusercontent.com/5712253/28686684-11a776a4-72da-11e7-9450-ef46a7d568a6.gif)
