### ISSUE TITLE
hab CLI allows creating origins that are invalid in depot

### ISSUE THREAD

**Issue by SpamapS** [habitat-sh/habitat#2833]
Hello!

I was walking through the Habitat tutorial and I created an origin with my usual IRC and GitHub username: SpamapS. I created it with the `hab setup` command, which happily accepted it. I used this in the mytutorial app, and it all worked fine for local tests. However, when I wanted to create an origin in the depot, I had to conform to the depot rules, which require the name to start with lowercase.

hab 0.26.1/20170715033447

- [x] The OS (including version) where you are running any of the Habitat commands.
```
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by reset** [comment]
@SpamapS thanks for the report! We'll make sure this input is validated in a fix soon
