### ISSUE TITLE
[www] code blocks in blog post don't look right

### ISSUE THREAD

**Issue by srenatus** [habitat-sh/habitat#2862]
For example in [this blog post](https://www.habitat.sh/blog/2017/05/use-shield-to-backup-and-restore-redis/), the markup of code blocks isn't correct:

Some are not shown as code at all:

<img width="849" alt="screen shot 2017-08-03 at 14 53 53" src="https://user-images.githubusercontent.com/870638/28922793-da18c1ca-785b-11e7-8b6a-c8c2c33cad67.png">

and some are shown as code, but lost their newlines:

<img width="820" alt="screen shot 2017-08-03 at 14 54 03" src="https://user-images.githubusercontent.com/870638/28922805-e2c91acc-785b-11e7-970c-fd8f43ece341.png">

Interestingly, [the markdown file of that post looks great](https://github.com/habitat-sh/habitat/blob/master/www/source/blog/2017-05-22-use-shield-to-backup-and-restore-redis.html.md#L2)

It also seems to affect `## headers`:

<img width="242" alt="screen shot 2017-08-03 at 14 54 14" src="https://user-images.githubusercontent.com/870638/28922748-afce88be-785b-11e7-9e59-dc8d79d564df.png">

but that specific one might be wrong because the line preceding it is ```.

**Also**, the blog post doesn't show up when I select "Community" (or "community", it's in the left hand side twice) here:

<img width="179" alt="screen shot 2017-08-03 at 14 57 55" src="https://user-images.githubusercontent.com/870638/28922888-2ba52c68-785c-11e7-9ce7-433efff0fd06.png">

**Comment by eeyun** [comment]
Fixed by #2901
