### ISSUE TITLE
RFE: want Docker-based builds on Linux as well as macOS

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#2863]
There's a lot to love about doing builds the macOS way, inside a Docker container. Specifically, this means cleanup post-build is a lot easier (we've run into many issues with open file handles, etc. due to weirdnesses in our build). A flag/var to pass/set to enable this on Linux build systems would be super helpful for anyone like us who still has a build server in the Jenkins tradition.

**Comment by eeyun** [comment]
This has been closed by #2886

After the next release you'll be able to use the `-D` flag with any studio commands which will utilize the docker studio as opposed to chroot. Great feature suggestion! Thank you for putting it together!
