### ISSUE TITLE
Service not getting hupped after providing a new configuration

### ISSUE THREAD

**Issue by computeracer** [habitat-sh/habitat#2864]
On ubuntu 14.04 when a new toml config is provided and the version is incremented the package does not accept the new config until manually started and stopped. Confirmed a bug with @eeyun

**Comment by christophermaier** [comment]
@computeracer Can you provide the configuration templates you're using, an example of the config you're injecting into the ring, and any `default.toml` or `user.toml` files you're using in your package? Thanks!

**Comment by computeracer** [comment]
default.toml of moodle package:
wwwroot = "http://localhost"

config.php of moodle package:
$CFG->wwwroot   = '{{cfg.wwwroot}}';

running command:
hab apply 'moodle.default' $(date +%s) /home/ubuntu/hab/config/moodle-default.toml

where moodle-default.toml:
wwwroot = "http://mydnsaddress.com"

@christophermaier  Let me know if anything is missing.

**Comment by christophermaier** [comment]
@computeracer One more thing; what version of Habitat are you using?

**Comment by computeracer** [comment]
@christophermaier 
hab -V
hab 0.28.0/20170729012530

**Comment by christophermaier** [comment]
@computeracer Excellent, thank you very much!

**Comment by christophermaier** [comment]
Closing this as not-a-bug
