### ISSUE TITLE
Private "Projects" in Origin

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2867]
In current Builder we only have one kind of project - a public project. This is  project whose packages are freely available for download and whose build output is readily available.

We need to add an additional project type - the private project. This is a project whose packages are available only to clients who have an authentication key which proves they are a member of the origin before allowing to download, list, or show packages and their related build output.

**Comment by ryankeairns** [comment]
Note: the UI portion of this is in #3261

**Comment by raskchanky** [comment]
Closed by https://github.com/habitat-sh/habitat/pull/3423
