### ISSUE TITLE
[Builder] Set up limit for syslog

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#2874]
We can get into a state where the syslog can fill up the system disk on our builder instances.
This card is to set up a syslog limit when provisioning instances via our Terraform scripts.

Set the following in /etc/systemd/journald.conf :
SystemMaxUse=500M

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #33](https://github.com/habitat-sh/builder/issues/33) via [**ZenHub**](https://www.zenhub.com/)
