### ISSUE TITLE
Create advanced "Scaffolding" docs

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2880]
This is a topic for advanced "Getting started" flow. 

Document Scaffolding for users: 
- how to get started 
- how to customize if the basic defaults don't work for you
- what Scaffolding is 
- how to connect other services 

Include examples from Ruby on Rails, Node.js, and IIS.

**Comment by davidwrede** [comment]
This is covered in #3108 for the Ruby scaffolding.
