### ISSUE TITLE
Create "local development" guide

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#2882]
Create a step by step guide to using `hab studio` and `docker compose` for a great local development experience. 

Highlight any gaps in functionality back to the engineering team to prioritize for development. 

Target persona is an application developer who has been using `docker compose` and wants to start using habitat.

**Comment by eeyun** [comment]
I'm all about this because docker compose is a great tool. But, I wonder if it wouldn't be better for us to build a "Game Guide" that follows a sane workflow top to bottom and includes some common errors and common pitfalls that occur in the different areas of the codebase.

**Comment by apriofrost** [comment]
I love the idea about including the common errors and pitfalls in the guide. @eeyun you probably have the best understanding about that the FAQ from our users. David and I are putting together an outline for another guide about 'build your web app' (https://docs.google.com/document/d/1YnaDh4DSy-NR1Ec4bWWsIPgjo-4bbuXv6-4Aywsj_78/edit#) It will be great if you can review it and add those common errors/pitfalls where you see fit.

**Comment by ShalokShalom** [comment]
https://github.com/habitat-sh/habitat/issues/2585

**Comment by ShalokShalom** [comment]
https://github.com/habitat-sh/habitat/issues/2581
