### ISSUE TITLE
Sharding assumptions

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#2884]
There are places in the codebase where we're making assumptions about our database shards that aren't going to work out once we have more than one database server.  Searching for packages is one example.  Right now, the expectation is that when you search the depot for "redis", you see every redis package for every origin.  We shard on origin, though, so in order to retrieve results for all origins, we build up a query and run that query on every shard.  This works right now because the entire database is on one machine, but once that's not the case, this will fail.

I'm guessing there are probably other places as well, and it would be good to find these problems sooner rather than later.  One way to do this would be to setup our acceptance environment with a minimum of 2 database servers.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #34](https://github.com/habitat-sh/builder/issues/34) via [**ZenHub**](https://www.zenhub.com/)
