### ISSUE TITLE
[builder-web] Project create

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2889]
We need to clean and hook up the UI components for project create. These were cut from our initial release but still accessible from manually keying in the URL. These components are used for hooking up a "project" to a GitHub repository's path to a `plan.sh` (and in the future, a `plan.ps1`)

**Comment by raskchanky** [comment]
I'd like to provide some historical context on this one.  Last summer, when work on the project creation UI was happening, @ryankeairns and I intentionally didn't link the project create page to anything, to avoid introducing users to the term "project".  It was thought at the time (and I still agree with this) that having users deal with both "projects" and "packages" would be too confusing.  Indeed, even in discussions with the core team, it's challenging for core team members to keep the terms and their meanings straight.

Instead, @ryankeairns mocked up an interface on the screen that lists packages for an origin that let you "link a package to a repo", but put you through the same UI flow as project creation.  At some point, for reasons I don't recall, that interface was removed.

Here's a screenshot of the current production depot, showing where that link used to be.

![](https://dl.dropboxusercontent.com/s/8v4fyk760gq37wo/2017-08-08%20at%2011.11%20AM.png)

**Comment by ryankeairns** [comment]
Will this include the Docker hub publishing configuration on Step 2 of this flow, or will that be a separate issue?

**Comment by mgamini** [comment]
@ryankeairns That'll be separate

**Comment by ryankeairns** [comment]
@mgamini I've created issue #3259 to capture this. Feel free to edit it and unassign yourself if that's not something you'll be tackling. Thanks!
