### ISSUE TITLE
Builder WebHooks

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2891]
We need a mechanism for notifying external systems of build and publish status for packages. This is often manifested in an HTTP callback known as a WebHook.

We should aim at a minimum to support WebHook notifications for
* Build finish - with a payload containing the status and information about the generated artifact
* Publish finish (i.e. Docker Hub export) - with the same payload as above

**Comment by tduffield** [comment]
I would also be interested in a promotion notification.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #35](https://github.com/habitat-sh/builder/issues/35) via [**ZenHub**](https://www.zenhub.com/)
