### ISSUE TITLE
Use latest powershell beta in supervisor and studio on windows

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#2892]
We have been on the last version of powershell's alpha release because their beta releases had broken compatibility with win7 and 2008 R2. The[ latest beta.5 release](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0-beta.5) not only fixes that but also includes our PR to fix service stops so that we no longer need to patch.

We will need to release our latest launcher code that includes the `-NonInteractive` before releasing this so that stopped services do not enter a interactive debug prompt.

**Comment by tashimi** [comment]
@mwrock should this stay open?

**Comment by mwrock** [comment]
Oh this is done
