### ISSUE TITLE
Encrypt sensitive fields in `builder.toml` configuration 

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2896]
## User Story

As a plan author and user of automated builds with Builder, I need a way to encrypt sensitive information which will be stored to configure my build jobs and held inside of `builder.toml` next to my `plan.sh` or `plan.ps1`, so I can configure credentials for post-build phases to accomplish things like publishing an artifact to bintray or exporting and publishing a Docker container to Docker Hub.

## Suggested Implementation

It may be easiest to encrypt configuration with the public key used to verify package signatures. The corresponding private key is already obtained from the depot inside the builder-worker before the build phase.

The public key is also typically readily available on a plan author's local machine where they will be authoring/editing the `builder.toml` and, if it's not, it's very easy to automatically obtain it.

I suggest that we implement a command `hab bldr encrypt` or something along those lines which takes a value and outputs the encrypted result which the author then places into the `builder.toml` and commits it to version control

**Comment by chefsalim** [comment]
We may need to use a 'User key' for the encryption. Libsodium differentiates between signing keys and encryption (box) keys.  The origin keys are signing keys, and it does not look like we will be able to use them for encryption.
