### ISSUE TITLE
Visualize publish phases in UI

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2898]
Post-build publishing phases need to be represented in the build output component if configured for a build. Their logs should be separate and they should be represented as a phase after the build.

[Invision Mock](https://chef.invisionapp.com/share/Y4DJGE1MR#/251301072_270_-_Docker_Published)

**Comment by ryankeairns** [comment]
The mockup above is outdated. We've move to the version below that has the output attached to the box for each process. That said, v1 will have the output combined into the output on the first box (i.e. the Docker publishing output will not be separated out, initially).

https://chef.invisionapp.com/share/Y4DJGE1MR#/251301072_270_-_Docker_Published

**Comment by fnichol** [comment]
Pretty sure we're done here, the worker is concatenating both the Studio build and Docker export into the same output stream (in #3443). We'll need to do some work to introduce discrete logging streams before the UI gets the benefit.
