### ISSUE TITLE
Key Generation in Web UI

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2899]
## User Story

As a user of Builder, I want to be able to generate the keys for my origin upon creation of my origin in the Builder UI, so I can begin working with Builder before even attempting to download the Habitat CLI

* [x] Generate keys in the Keys tab
* [x] Generate keys when I'm creating an origin

**Comment by ryankeairns** [comment]
To be clear, there are two UI components here:

1. when creating a new origin, there is a checkbox to generate a key pair - [mockup](https://chef.invisionapp.com/share/3ZBKYLQTW#/249657340_create_Origin_Single_Step)
2. for an existing origin, you can generate a new key pair on the Keys tab - [mockup](https://chef.invisionapp.com/share/3ZBKYLQTW#/250295494_origin_Keys_Empty)

Also, note that dialog when generating a key pair on the Keys tab. We can use the existing Angular Material dialog for this.

**Comment by reset** [comment]
Inflight work #3285
