### ISSUE TITLE
cfg is not defined in events.proto

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#2927]
`cfg` is a field in CensusEntry as a binary but there is no reference as to how it is serialized. It feels like `cfg` should have a Message format defined in [events.proto](https://github.com/habitat-sh/habitat/blob/master/components/eventsrv-protocol/protocols/event.proto)

**Comment by christophermaier** [comment]
The event server was removed in #6069, so this is no longer required.
