### ISSUE TITLE
`No revisions found for ring sym key` when `--ring` is set but key is in env

### ISSUE THREAD

**Issue by cwebberOps** [habitat-sh/habitat#2938]
If you set `--ring` when the `HAB_RING_KEY` is set in the environment, the supervisor blows up, even if then name of the ring matches.

Steps to reproduce:
1. generate a ring key
2. export the key in the `HAB_RING_KEY` env variable
3. Start the supervisor with the `--ring <ring name>`
4. Watch supervisor go crazy.

**Comment by christophermaier** [comment]
That being said, I think we could tweak the docs and perhaps the error message to make the situation more clear.

**Comment by mpeck** [comment]
Fixed in https://github.com/habitat-sh/habitat/pull/5846
