### ISSUE TITLE
[www] missing an thumbnail image for the homepage when shared on social medias

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#2941]
When the habitat.sh website gets shared on Twitter, it misses a thumbnail image in the meta data (see the screenshot below)
<img width="583" alt="screen shot 2017-08-15 at 11 39 44 am" src="https://user-images.githubusercontent.com/9401459/29330878-7e8aa6a4-81af-11e7-8629-b4ae6b26ad5a.png">

**Comment by rsertelon** [comment]
This is a bug. The twitter card is already configured and has all that should make it work.

However, the image link points to a 404 (https://www.habitat.sh/images/habitat-social.jpg)

In the source tree, there _is_ a `habitat-social.jpg` in the `images` folder. It might not be deployed correctly?

**Comment by apriofrost** [comment]
Thanks @rsertelon for the investigation! @mgamini could you take a look at this issue and the comment thread?

**Comment by mgamini** [comment]
@rsertelon looks great! I'll approve the PR once I see it.
