### ISSUE TITLE
Handle static sites with core/scaffolding-node

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#2942]
Node is a popular build tool for static/single-page websites as well (e.g., Angular, React, Ember and others). We should support using Node as a build-time dependency to package these kinds of apps and, ideally, lend them some sort of service-like behavior to allow them to be managed by the Habitat supervisor.

**Comment by eeyun** [comment]
@cnunciato I couldn't agree more. For now, I'm actually going to close this issue and ask that it get re-opened on the core-plans repository. If you'd like me to do this I'm happy to, just let me know!
