### ISSUE TITLE
Remove member from Origin

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2943]
As an owner of an origin, I need a way to remove members from my origin, so I can remove access for phased out members

**Comment by mgamini** [comment]
@elliott-davis did you do this, or was it just invitations?

**Comment by ryankeairns** [comment]
Based upon what I see in acceptance, this doesn't appear to have been done yet. A side note here is that up to this point we have not identified the owner of the origin. From what I understand, we do track who originally created the origin and we discussed marking them as the owner. @reset can verify that and I suspect that may need a card of its own (to set all origin creators as owners on the backend?)

Here is the mockup for member removal from the point of view of an owner. Note that a non-owner would not see the remove icons. Also, note that an owner cannot remove themselves as their must always be an owner.

[Mockup for removing a member](https://chef.invisionapp.com/share/3ZBKYLQTW#/248797136_my_Origins_V2_Members)

**Comment by reset** [comment]
We already record who the "owner" of an Origin is but we don't ever use it for anything. We need to ensure only the owner of the origin can remove people from it
