### ISSUE TITLE
Transfer ownership of Origin

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#2944]
As an owner of an origin, I need a way to transfer ownership to another member, so I can leave the origin or entrust it to somebody else

**Comment by ryankeairns** [comment]
**Note** that there must always be one owner.
**Note** that we discussed setting the origin creator of the origin as the owner (we'll need to go back and retroactively do that for current origins).

[Mockup for transferring ownerhisp](https://chef.invisionapp.com/share/3ZBKYLQTW#/248797136_my_Origins_V2_Members)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #36](https://github.com/habitat-sh/builder/issues/36) via [**ZenHub**](https://www.zenhub.com/)
