### ISSUE TITLE
Allow `hab ring key generate` to output to STDOUT

### ISSUE THREAD

**Issue by asymmetric** [habitat-sh/habitat#2948]
As a Kubernetes cluster administrator, I'd like to mount ring keys as secrets.

In order to to this, I have to run `hab ring key generate`, and then Base64 encode the resulting file, located in `/hab/cache/keys`.

Since I have no use for the file on my machine, it would be nice if I could pipe the output of `hab ring key generate` straight into `base64`.

This would generally be useful for all cases where the supervisor is not running on the host machine.

**Comment by mwrock** [comment]
You should be able to then `hab ring key export` the key to STDOUT

**Comment by reset** [comment]
The combination of generate & export as @mwrock pointed out is the way to go here. It won't be exported as base64 so you'll need to pipe the results of export to `base64`
