### ISSUE TITLE
ssl errors, mac os

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#2950]
version: hab 0.29.1/20170810235219

```bash
sudo hab pkg install core/coreutils
```
output:
```bash
» Installing core/coreutils from channel 'stable'
✗✗✗
✗✗✗ the handshake failed: The OpenSSL library reported an error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264:: unable to get local issuer certificate
✗✗✗
```

**Comment by srenatus** [comment]
@guskovd Can you provide more information? Is this run in the studio? (I've just been able to install packages from within the studio flawlessly, so I'd think this is somewhat environmental)

If I run this on osx (no idea if this should work, nor what exactly it should do, though) -- I get this:
```
$ hab pkg install core/coreutils
∅ Installing a package requires root or administrator privileges. Please retry this command as a super user or use a privilege-granting facility such as sudo.

✗✗✗
✗✗✗ Root or administrator permissions required to complete operation
✗✗✗
$ sudo hab pkg install core/coreutils
Password:
» Installing core/coreutils from channel 'stable'
✗✗✗
✗✗✗ Package not found
✗✗✗
$
```

**Comment by eeyun** [comment]
Hey @guskovd , Thanks for opening an issue! If you could provide us a bit more context that would be super useful in being able to repro this. Ideally if we could find your run context e.g. if you're inside or outside the studio, being run in docker or outside docker etc.

As soon as we get that information we should re-open but for cleanliness sake im going to close this for now.

**Comment by iainrose** [comment]
I'm seeing this same error.

MacOS 10.13.3
hab 0.55.0/20180321215236

The error is occuring when trying to search for packages in the builder.

Iains-MBP:hab-0.55.0-20180321215236-x86_64-darwin iainrose$ hab pkg search iainrose/national-parks
✗✗✗
✗✗✗ the handshake failed: The OpenSSL library reported an error: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed:s3_clnt.c:1264:: unable to get local issuer certificate
✗✗✗

I'm doing this from the terminal on my Mac, I am not in the Hab studio.

**Comment by iainrose** [comment]
FYI - If I run the same command from inside the Hab studio, it's working

[1][default:/src:0]# hab pkg search iainrose/national-parks
iainrose/national-parks/6.3.0/20180111214454
iainrose/national-parks/6.3.0/20180315165006
iainrose/national-parks/6.4.0/20180319201145
iainrose/national-parks/6.4.0/20180319203322
iainrose/national-parks/6.4.0/20180319213659
iainrose/national-parks/6.4.0/20180319214059
iainrose/national-parks/6.4.0/20180403232809
iainrose/national-parks/6.4.0/20180404001809

**Comment by christophermaier** [comment]
See extended discussion at https://forums.habitat.sh/t/ssl-error-on-macos/478
