### ISSUE TITLE
Rolling strategy fails to apply when RUST_LOG is at debug

### ISSUE THREAD

**Issue by tyler-ball** [habitat-sh/habitat#2955]
# The Setup

We have a ruby application that we are running in a habitat container. We are trying to test out rolling restarts of the service and encountered some weird behavior. When debug logging is off everything appears to work well - the update_leader applies the new package first, then the other nodes do in serial order.

But when we run our experiement and have `RUST_LOG=debug` set in the environment we do not see the same behavior. The leader appears to install the new package but the other nodes do not, each with different errors.

I have 3 docker containers I am running locally. I start our hab service on the containers by logging in and running (each line on a different container):
```
hab start cabbage/ntp-north-america -v --no-color --strategy rolling --channel stable
hab start cabbage/ntp-north-america -v --no-color --strategy rolling --channel stable --peer ubuntu1
hab start cabbage/ntp-north-america -v --no-color --strategy rolling --channel stable --peer ubuntu1
```

Our run script:
```
#!/bin/bash

function finish {
  echo "Exiting remediate loop"
}
trap finish EXIT

exec 2>&1

while true; do
  $(hab pkg path #{origin}/#{name})/bin/remediate -l debug
  sleep 3
done
```

@eeyun linked us to another bug that talked about issues with using `sleep` in a run hook, so that could very well be the issue. 

Once the service starts on all 3 containers I upload and promote a new version of the `cabbage/ntp-north-america` package. It looks like the update leader correctly detects this and downloads it, but then the other 2 nodes end up in a weird state.

I cannot reproduce this locally now (tried for the last half hour) so I only have some partial logs. But here is the log from one of the `update_follower` nodes:

https://gist.github.com/tyler-ball/664cc7315d7a835544d5e60f73f94cce

You can see it gets into a state where it knows there is an update going on (the leader has already updated) but it never thinks it is its turn.

Tagging @eeyun since he was there and saw this happening, even though I cannot reproduce it now.

**Comment by reset** [comment]
It's unlikely that the log level had any affect on the election but we had pushed a number of fixes to elections and health in general in July and August. Do you remember what version of the Supervisor you were running when you experienced this?

**Comment by fnichol** [comment]
@tyler-ball If it's okay, I'm going to assume that we're good here now (as @reset mentioned above) and close this out. If I'm wrong, don't hesitate to reopen. Thanks!
