### ISSUE TITLE
Census not present on all nodes

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#2976]
I have [this docker-compose file](https://github.com/starkandwayne/habitat-plans/blob/master/postgresql/tests/docker-compose.yml) with 1 standalone postgres node (group postgresql.default) and a 3 node cluster (group postgresql.cluster) that gets bootstrapped by peering with the standalone node. The containers that get brought up are built using the latest habitat `0.29.1`

The bootstrapping and clustering works but when querying the standalone node the cluster nodes aren't visible in the returned census data.

To reproduce run the following in [this](https://github.com/starkandwayne/habitat-plans/tree/master/postgresql/tests) folder:
```
$ docker-compose up -d
$ docker-compose run tests curl -s standalone:9631/census | jq -r '.census_groups | keys'
Starting tests_standalone_1 ... done
[
  "postgresql.default"
]
$ docker-compose run tests curl -s pg1:9631/census | jq -r '.census_groups | keys'
Starting tests_standalone_1 ... done
[
  "postgresql.cluster",
  "postgresql.default"
]
```

**Comment by smartb-pair** [comment]
I think I'm seeing this as well on a standard VM.

**Comment by reset** [comment]
This looks like a network connectivity issue. Can you verify that TCP/UDP ports are open and communication is flowing between all nodes over the port you've configured (default: 9638)?

**Comment by bodymindarts** [comment]
This is running locally on docker for mac! No way its a connection issue.

**Comment by bodymindarts** [comment]
Just made sure and can confirm that I am able to telnet from every node to every other node on port 9638.

**Comment by smartb-pair** [comment]
I'm able to talk to my permanent peer's supervisor over HTTP as well as hitting the UDP port with `netcat`.  Census and butterfly data look wrong to me:
```
root@dev-postgres-0:~# curl -s permanent-peer.domain.tld:9631/census | jq .[]
false
{}
"c88bb5aec0a94d1b8260962d58796ec1"
0
0
0
0
0
0
root@dev-postgres-0:~# curl -s permanent-peer.domain.tld:9631/butterfly | jq .[]
{
  "members": {},
  "health": {},
  "update_counter": 0
}
{
  "list": {},
  "update_counter": 0
}
{
  "list": {},
  "update_counter": 0
}
{
  "list": {},
  "update_counter": 0
}
{
  "list": {},
  "update_counter": 0
}
{
  "list": {},
  "update_counter": 0
}
{
  "list": {},
  "update_counter": 0
}
```

**Comment by reset** [comment]
I'm pretty sure this is because the postgresql plan in master is broken - it blocks the supervisor's main thread by calling the `hab` binary from within it's post-run hook

**Comment by bodymindarts** [comment]
Okay that might be the issue. This used to work on an earlier version. I'll see if I can fix PG to not take those 'rules' into account.

**Comment by reset** [comment]
Gonna close this since it's the postgresql plan. This is the link to the ticket we're working on to enable multiple services per package: https://github.com/habitat-sh/habitat/issues/2902

**Comment by bodymindarts** [comment]
I can confirm that this issue doesn't come up when no sidecar process is being run.
