### ISSUE TITLE
Add an event message that exposes the channel a service is associated with

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#2982]
It would be nice to have the channel information for a service in the census message.

**Comment by mwrock** [comment]
@elliott-davis when you say "census message" are you referring to the `/census` monitoring endpoint? Note that it is in the `/services` endpoint. Or perhaps you mean the `hab status` message?

**Comment by elliott-davis** [comment]
@mwrock I think I actually meant the [CensusEntry](https://github.com/habitat-sh/habitat/blob/master/components/eventsrv-protocol/protocols/event.proto#L65).

**Comment by mwrock** [comment]
ah ok. got it.

**Comment by mwrock** [comment]
A `CensusEntry` reflects all of the CensusMember gossiped in the ring for an individual service group member. Channel is not included in this data and is not needed to be represented as part of the census data.

I just changed the title of this issue to better reflect the work we need to do. We do want an event service message that relays what channel a service group is bound to. We should have the supervisor feed this message to the event server when a service is started/loaded.
