### ISSUE TITLE
Panic on binary files in `hab/cache/keys` folder

### ISSUE THREAD

**Issue by georgemarshall** [habitat-sh/habitat#3002]
In PR #2946 a change was made to loop through and open all files in the `hab/cache/keys` folder. In cases where the OS may add metadata files that are not UTF-8 compatible it will cause the application to panic.

A real world case happened in macOS with `.DS_Store` metadata files.
```
✗✗✗
✗✗✗ stream did not contain valid UTF-8
✗✗✗
```
Ideally we should not be opening every file in the folder and instead globing for `*.pub` and `*.sig.key`.

**Comment by mwrock** [comment]
Aaaaaaarrrrrrggggghhhhh!!!!!!  So true!

**Comment by rsertelon** [comment]
This has been fixed in #4001 and can be closed.

**Comment by christophermaier** [comment]
Yup this should be fixed with #4001
