### ISSUE TITLE
roadmap.habitat.sh?

### ISSUE THREAD

**Issue by juliandunn** [habitat-sh/habitat#3005]
hiya... I can never remember where the Habitat roadmap is. Can I request a redirect be set up from `roadmap.habitat.sh` to the ProdPad link, `https://ext.prodpad.com/ext/roadmap/d2938aed0d0ad1dd62669583e108357efd53b3a6`

**Comment by tashimi** [comment]
I would suggest also adding habitat.sh/roadmap, for consistency.
