### ISSUE TITLE
Building.md Updates

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#3006]
The process and tooling available to contributors and folks looking to use unstable habitat have changed since we originally wrote our BUILDING.md. It could use a refresh around things like executing tests for various components of our project. https://github.com/habitat-sh/habitat/blob/master/BUILDING.md

For example our instructions on `make test` do not actually execute all of the testing stratagems we've scripted into our makefile.

```
running 2 tests
test config::tests::config_from_file_defaults ... ok
test config::tests::config_from_file ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running /src/target/debug/deps/bldr_admin-baf2fce830754816

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

   Doc-tests habitat_builder_admin

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Ideally we'd like to make the instructions in BUILDING.md more clear and useful.

**Comment by nellshamrell** [comment]
This should be written by @eeyun or another member of the core team.

**Comment by christophermaier** [comment]
Closing as superseded by the revamped development environment.
