### ISSUE TITLE
Can't find docs for package promotion

### ISSUE THREAD

**Issue by thommay** [habitat-sh/habitat#3010]
I was trying to figure out how to get a package in to the stable channel, but could not find anything under either `Share packages` or `Continuous Deployment` on the docs site. 
Now that I know the verb is promote it's easy to search for, but still :)

**Comment by davidwrede** [comment]
https://www.habitat.sh/docs/share-packages-overview was updated in #3020 with a section on package promotion and the first result in site search for "package promotion" is the shared packages topic, so I think we're good here.
