### ISSUE TITLE
Project Documentation Refactor

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#3011]
While we've started efforts over the last few months to refactor our project documentation (things like README.md, CONTRIBUTING.md, ETC) we have a lot of work to do in this area to minimize friction around people picking up our software, and/or contributing both plans and core code.

I'd like to propose a significant refactor around this project documentation to streamline contributor experience as well as maximize our communication efficiency with regards to the project.

Examples of FOSS projects with more tightly organized project documentation:
Inspiration docs: 
https://github.com/kubernetes/community 
  - Readme https://github.com/kubernetes/kubernetes/blob/master/README.md
  - Contributing.md https://github.com/kubernetes/community/blob/master/CONTRIBUTING.md 

https://github.com/kubernetes/helm 
  - Readme https://github.com/kubernetes/helm/blob/master/README.md 
  - Contributing.md https://github.com/kubernetes/helm/blob/master/CONTRIBUTING.md 

https://doc.rust-lang.org/std/
  - Readme https://github.com/rust-lang/rust/blob/master/README.md
  - Contributing https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md

**Comment by tashimi** [comment]
![image](https://user-images.githubusercontent.com/719646/29736360-27336950-89b5-11e7-9882-6385651ed35f.png)

**Comment by tashimi** [comment]
Addressed by: 
https://github.com/habitat-sh/habitat/pull/3238
https://github.com/habitat-sh/habitat/pull/3235

**Comment by tashimi** [comment]
Also addressed by: https://github.com/habitat-sh/habitat/pull/3234

**Comment by tashimi** [comment]
https://github.com/habitat-sh/core-plans/pull/788
