### ISSUE TITLE
Re-format the generated Manifest HTML

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3021]
Currently, the HTML that output in the web UI is stored as one big block of HTML in the database  which has precluded us from cleaning it up for better readability/scanability. 

In order to properly style the Manifest data and pull out the most important pieces of information, we'll need to change how the HTML is generated and potentially stored (currently its stored in a single db column).

@cnunciato and @ryankeairns will advise on the proper structure. This can happen after the Pre-Neighborhoods milestone.

**Comment by cnunciato** [comment]
This one's pretty old, and I feel like the UI's in a good place now and that this work is no longer needed. Anyone mind if I close it in favor of focusing on other things?

**Comment by raskchanky** [comment]
No harm in closing.  If this is still needed, someone can re-open.
