### ISSUE TITLE
Compiling takes longer than it should

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3026]
Steps to repro:

```
cd habitat
make clean
make bldr-run
```

Notice how long it takes everything to compile.  Once this process has completed, and builder is up and running, kill it with ctrl+c.  Now:

`make bldr-run`

Running this again, not having made any code changes at all, should blow through the compilation steps very quickly, but it doesn't.  It recompiles crates again, even though no code has changed.

Note that this _doesn't_ happen if you run `cargo build` twice inside one of the `builder-*` crates.  The first time, it takes awhile to compile, and the second time, it's done almost instantly.  Why doesn't this happen when running `make bldr-run`?

This isn't a huge priority, but given how much developer time is probably being wasted by it, it'd be good to figure out at some point.

**Comment by fnichol** [comment]
I saw this a couple of weeks ago but forgot to finish my hunt. I'm pretty sure there are 2 versions of the same dependency which have 2 different sets of features specified. Cargo doesn't currently differentiate between a crate version and feature set (only crate version) so I have a feeling there re-compiling going on.

**Comment by raskchanky** [comment]
@fnichol I've noticed that it always starts by re-compiling `chrono`.  Looking at `Cargo.lock`, we have two different versions of `chrono`, 0.2.25 and 0.3.1.  0.3.1 has been yanked from https://crates.io.  I wonder if that's related?

**Comment by raskchanky** [comment]
I don't know what changed, but I no longer see this behavior in my local dev environment. Now, everything compiles very quickly when no code has changed.
