### ISSUE TITLE
Supervisor crashing on acceptance environment

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3042]
Nodes in the acceptance environment are crashing with the following error in the journalctl log:

g 30 03:11:57 ip-10-0-0-53 hab[30638]: hab-sup(MR): Supervisor Member-ID 6619062b79af4f4688d02d2783334c49
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: hab-sup(MR): Starting core/builder-originsrv
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: hab-sup(PK): Confirmed latest version of core/builder-originsrv is core/builder-originsrv/4789/20170829154243
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ValueAfterTable', /checkout/src/libcore/result.rs:859
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: stack backtrace:
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    0: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    1: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    2: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    3: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    4: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    5: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    6: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    7: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    8: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:    9: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   10: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   11: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   12: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   13: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   14: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   15: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   16: __libc_start_main
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]:   17: <unknown>
Aug 30 03:11:57 ip-10-0-0-53 hab[30638]: hab-sup(MR): Supervisor Member-ID 6619062b79af4f4688d02d2783334c49

This causes the nodes to go into a bad state, where the supervisor is not restartable.

**Comment by christophermaier** [comment]
Not sure where the error is ultimately coming from, but it seems to be related to TOML serialization: http://alexcrichton.com/toml-rs/toml/ser/enum.Error.html.

I wonder if there's something in the template rendering logic combined with a template in the originsrv (and possibly some feature of our current topology?) that combines to yield invalid TOML?

**Comment by christophermaier** [comment]
Update: The error is coming from https://github.com/habitat-sh/habitat/commit/da026f27cd1a9584901a3189aac24383901cc62b#diff-634a43ff04325a487226bbc3f30b5d2fR192

It looks like we are indeed trying to render TOML with value keys after table keys, which is not allowed.

**Comment by chefsalim** [comment]
Also, here's the stack w/ actual symbols:
:   10: <core::result::Result<T, E>>::unwrap
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./checkout/src/libcore/result.rs:737
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   11: habitat_sup::manager::events::build_service_update
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/manager/events.rs:192
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   12: habitat_sup::manager::events::EventsCli::send_service
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/manager/events.rs:54
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   13: habitat_sup::manager::Manager::run::{{closure}}
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/manager/mod.rs:514
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   14: <core::option::Option<T>>::map
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./checkout/src/libcore/option.rs:392
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   15: habitat_sup::manager::Manager::run
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/manager/mod.rs:513
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   16: hab_sup::sub_run
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/main.rs:511
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   17: hab_sup::start
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/main.rs:118
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   18: hab_sup::main
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./src/components/sup/src/main.rs:69
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   19: __rust_maybe_catch_panic
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./checkout/src/libpanic_unwind/lib.rs:98
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   20: std::rt::lang_start
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./checkout/src/libstd/panicking.rs:433
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./checkout/src/libstd/panic.rs:361
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:              at ./checkout/src/libstd/rt.rs:57
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   21: main
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   22: __libc_start_main
Aug 30 17:00:32 ip-10-0-0-53 hab[4706]:   23: _start

**Comment by mwrock** [comment]
closing this since it is fixed by #3059
