### ISSUE TITLE
Optimize API endpoints

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3050]
Is there a way to create a new API endpoint that mashes together the information present in:
* `/pkgs/core/redis/3.2.4`
* `/projects/core/redis/jobs`

Ideally you just hit 1 endpoint, that can be paginated in the future, and you get all the information you need to know about builds that have succeeded and failed, complete with version information.

You'd want the information present in `/projects/core/redis/jobs` as a starting point. Then for each item, you'd also want to know:
* What channels is this release in?
* Who initiated this build?
* What platform is this release for?

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #37](https://github.com/habitat-sh/builder/issues/37) via [**ZenHub**](https://www.zenhub.com/)
