### ISSUE TITLE
Add build source

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3052]
We need to have a concept of build source, e.g. was this artifact built by the user and manually uploaded or was it built by builder.  That needs to be persisted as metadata about every package.  It also needs to be returned by the API everywhere we return full idents.

**Comment by mwrock** [comment]
I've talked this over with @tashimi and we are going to simply expose the owner's user name. This solves the issue of source with the additional benefit of knowing who exactly uploaded the package.

So the following needs to be done here:

* Create a new github account named `habitat-worker`. Perhaps we will want separate accounts for each worker, but I'll just set one up for now.
* We will want to either add a `owner_name` column to the `origin_packages` table or have the package messages get the owner_name from the session server. The former will require migrations and the latter is kinda weird. Still looking at this.

**Comment by mwrock** [comment]
Yeah I think we'll need to add owner_name to the origin_packages table. For the sake of backward compatibility, we will need to keep owner_id but it won't be used for anything. I don't think its used for anything now.

So there are 2 data migrations that will be be needed here:

1. populate the owner_names for all packages
2. Update all packages with the current builder_worker owner with the new one.

**Comment by mwrock** [comment]
closing this since builder builds are added to a `bldr-*` channel and that is rendered on package display

**Comment by raskchanky** [comment]
@chefsalim @mwrock  I'm confused why this issue was closed.  It looks like the PR for this was closed too?  Did we decide that we don't need a build source any more?

**Comment by raskchanky** [comment]
Never mind, I'm caught up on the relevant context now.
