### ISSUE TITLE
Redirect to My Origins upon Sign In

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3072]
While we all love the notion of the Dashboard, it's not quite ready for the big time yet. We would like to hide the Dashboard link from the left nav, and direct users to the My Origins screen upon signing in.

With another iteration or two on the Dashboard, we can re-introduce it.

**Comment by cnunciato** [comment]
We should wait on this until after the My Origins page has been updated to contain at least a couple of the new calls to action.

**Comment by cnunciato** [comment]
Closing as complete.
