### ISSUE TITLE
Discrepancy in error message vs help output

### ISSUE THREAD

**Issue by chrisortman** [habitat-sh/habitat#3106]
Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [bento/cent7.3 ] The OS (including version) where you are running any of the Habitat commands.
- [n/a ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		RUST_LOG=debug RUST_BACKTRACE=1 hab ...

- [n/a ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		env | grep HAB | grep -v HAB_AUTH_TOKEN

```
/home/vagrant # hab --version
hab 0.30.2/20170822232349
```

This is nitpicky but ….

```
/home/vagrant # hab svc load --help
hab-sup-load
Load a service to be started and supervised by Habitat from a package or artifact. Services started in this manner will persist through Supervisor restarts.

USAGE:
    hab-sup load [FLAGS] [OPTIONS] <PKG_IDENT>
```

Says pass flags and options before package

But
```
/home/vagrant # hab svc load --strategy at-once --channel stable --bind base:simple-node-1.default chrisortman/dependent-node-1
error: The following required arguments were not provided:
    <PKG_IDENT>

USAGE:
    hab-sup load <PKG_IDENT> --bind <BIND>... --channel <CHANNEL> --strategy <STRATEGY>
```

Results in an error and the error message has package first

https://github.com/chrisortman/hab-test if you need the environment

**Comment by fnichol** [comment]
That's a pretty interesting inconsistency with the 2 usages. We're using a CLI parsing library under the hood (PSA: [clap](https://clap.rs/) is pretty amazing), but  I *think* I might know why (possibly fixable): the last option that person provided was `--bind` which can take zero, one, or more values. I'm wondering if the CLI parser thinks the package identifier at the end is another `--bind` value.

Does slightly changing the order of your options change the behavior? Specifically, not putting `--bind` as the last option before the `PKG_IDENT` like:

```sh
hab svc load \
  --strategy at-once \
  --bind base:simple-node-1.default \
  --channel stable \
  chrisortman/dependent-node-1
```

**Comment by chrisortman** [comment]
Yes it does, if I run it as you have specified it works.

**Comment by rsertelon** [comment]
I think this is the same issue as in #2221
