### ISSUE TITLE
Add docker integration functionality to builder-web

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#3109]
The UI should expose an integrations tab under an origin that allows you to perform CRUD operations against the builder api as found in #3016

**Comment by ryankeairns** [comment]
The mockup for adding your Docker Hub creds in the UI can be found here:
[Integrations tab - adding creds](https://chef.invisionapp.com/share/3ZBKYLQTW#/251489938_my_Origins_Integrations)
