### ISSUE TITLE
Refactor Origin

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3111]
The [Origin protobuf](https://github.com/habitat-sh/habitat/blob/master/components/builder-protocol/protocols/originsrv.proto#L34) has gotten a little bloated and unwieldy.  The Origin itself should just contain `id`, `name` and `owner_id`.  The other fields (`private_key_name` and `default_package_visibility` as of this writing) should be separated out into OriginSettings, or something similar and future additions to Origin should happen there.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #39](https://github.com/habitat-sh/builder/issues/39) via [**ZenHub**](https://www.zenhub.com/)
