### ISSUE TITLE
Auto-generate CLI docs 

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3149]
We should be auto-generating new documentation for our docs page as we do for the CLI.

Pages that need to be converted:
There may be others that I haven't found yet.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] https://github.com/habitat-sh/habitat/blob/master/www/source/docs/reference/habitat-cli.html.md

- [ ] The entire in-browser demo content: https://github.com/habitat-sh/habitat/tree/master/www/source/tutorials/get-started/demo/responses
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by cnunciato** [comment]
CLI docs are now being generated automatically. @tashimi since this issue is a bit old, should we keep it open to address your second checkbox item, or close (and maybe file a separate issue for it, if you still want to do it)?

**Comment by tashimi** [comment]
@cnunciato yeah, if we are autogenerating cli docs, can we tag areas for auto-updating elsewhere in the front end so commands don't get out of date? I think this was originally Jamie's idea, but a way to make sure our tutorials etc. don't get broken in a release would be awesome.

**Comment by baumanj** [comment]
This is done
