### ISSUE TITLE
hab config apply - can't apply config to a service group that doesn't exist yet

### ISSUE THREAD

**Issue by mivok** [habitat-sh/habitat#3155]
This is using habitat 0.30.2/20170822230736 and replicated inside a fresh habitat studio.

If you run `hab config apply` before starting a service (or immediately afterwards, before the service comes up fully), the service never picks up the configuration.

Here's a copy/paste replication command. First, enter a blank studio `hab studio enter` then run the commands:

``` sh
hab pkg install -b core/jq-static core/curl; \
    hab pkg install core/nginx; \
    hab svc start core/nginx; \
    echo "Not waiting while service starts"; \
    echo 'worker_processes = 2' | hab config apply nginx.default 1; \
    echo "Allowing time for config to apply"; sleep 5; \
    curl 127.0.0.1:9631/census | \
        jq '.census_groups."nginx.default".service_config'
```

This will return `null`. You can also `curl 127.0.0.1:9631/services/nginx/default/config` to see the worker value is unchanged.

Next, repeat this, but insert a sleep in place of the "Not waiting..." echo:

``` sh
hab pkg install -b core/jq-static core/curl; \
    hab pkg install core/nginx; \
    hab svc start core/nginx; \
    echo "Waiting while service starts"; sleep 5; \
    echo 'worker_processes = 2' | hab config apply nginx.default 1; \
    echo "Allowing time for config to apply"; sleep 5; \
    curl 127.0.0.1:9631/census | \
        jq '.census_groups."nginx.default".service_config'
```

And this time it will show the service config as being applied.

Notes:

* I'm not sure the second sleep is necessary, but I'm just allowing some time to allow the configuration to apply.
* I actually start the service and then apply the configuration right afterwards, which is the original case where I hit this bug. Swap the order of the `hab svc start` and `hab config apply` if you wish to replicate setting the configuration before starting a service.
* This also works if you apply the configuration on one supervisor, and start nginx on the other supervisor (as long as the nginx.default service group doesn't exist prior to starting nginx up).

**Comment by rsertelon** [comment]
Is this linked to #3009 ?

**Comment by tashimi** [comment]
Closing as duplicate.
