### ISSUE TITLE
Extract data from rst files for debugging and troubleshooting

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3169]
The supervisor stores raw rumors in `/hab/sup/default/data/*.rst` files. These files are in a custom binary format, though (effectively raw Protobufs, with some extra headers and whatnot), making them difficult to examine manually, which can complicate troubleshooting.

It would be nice to extract the [logic for reading these files](https://github.com/habitat-sh/habitat/blob/b524e311165b15376ec10b8b71b773c771f28aa7/components/butterfly/src/rumor/dat_file.rs#L63-L239) into a library, allowing us to create a simple CLI tool that could at the very least convert these files into a plain text representation that you could at least run `grep` on.

Related to #3168 in that they're both increasing the debuggability of the system.

**Comment by baumanj** [comment]
Reopening due to reversion of https://github.com/habitat-sh/habitat/pull/6599. Will be closed again when https://github.com/habitat-sh/habitat/pull/6619 merges.
