### ISSUE TITLE
Support package deprecation in the Depot

### ISSUE THREAD

**Issue by adamleff** [habitat-sh/habitat#3173]
A while back, we decided to move InSpec from `core/inspec` to `chef/inspec` since it didn't make much sense to have it live as a core package, and none of the InSpec maintainers who control the release are core maintainers. However, since `core/inspec` still exists (because we all agree removing packages from the depot is A Bad Thing(tm)), it recently caused a problem when trying to automatically rebuild the world for the recent Ruby CVEs.

I'd like to propose a mechanism for marking a package as deprecated such that bldr doesn't try and rebuild it. Bonus points for the ability to de-list the package (while still having it available as an artifact), and double-bonus points for the ability to redirect a user from package A to package B so they can find the new hawtness.

Sorry if this is a duplicate. I know this has been chatted about before and I tried to find an existing issue unsuccessfully. Thank you!

**Comment by tashimi** [comment]
Agree! This is something we need to add.

**Comment by lilianmoraru** [comment]
Related issue #1051

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #40](https://github.com/habitat-sh/builder/issues/40) via [**ZenHub**](https://www.zenhub.com/)
