### ISSUE TITLE
Possible bug entering the Habitat studio on Windows

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#3199]
Hello!

I'm currently unable to enter the Habitat studio on windows with just the command $ hab studio enter, I need to use $ hab studio enter -w.  Although I know this is historic behavior, I thought an earlier release made it so we could use $ hab studio enter on windows as well without the flag.  If this is not the case, no worries, but we should add that flag to the commands in the Habitat tutorials for Windows.

**Comment by nellshamrell** [comment]
Note - this bug is also preventing me from building any plan.sh artifacts on Windows, I can only build plan.ps1

**Comment by mwrock** [comment]
Currently, `hab studio enter` brings up the docker studio and is what you would use to build linux packages. The `-w` enters a windows sytudio.

There are no tutorials yet for building windows packages. I believe that is on @davidwrede 's todo list.

@nellshamrell does `hab studio enter` not enter a docker studio? If not, whats the error it throws? Thanks!

**Comment by nellshamrell** [comment]
Hi @mwrock!  It does indeed throw an error when trying to enter a docker studio - I'm unable to build Linux packages on Windows.

```
PS C:\Users\nshamrell\core-plans\node> hab studio enter
0.31.0: Pulling from studio
image operating system "linux" cannot be used on this platform
✗✗✗
✗✗✗ The Docker image habitat-docker-registry.bintray.io/studio:0.31.0 is unreachable due to a network er
✗✗✗ The image must be reachable to ensure the versions of hab inside and outside the studio match.
✗✗✗ You can specify your own Docker image using the HAB_DOCKER_STUDIO_IMAGE environment variable.
```

**Comment by mwrock** [comment]
Hmm that sounds like a network issue. Are you able to spin up a vanilla docker container on that VM?

**Comment by davidwrede** [comment]
Doc work for native Windows package development is being tracked in #3201.

**Comment by mwrock** [comment]
closing this since I think its environmental but please reopen if you think differently!
