### ISSUE TITLE
Document how to natively build Windows packages 

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#3201]
Need a new topic/set of topics to show how to use the Windows-based studio to build packages for windows runtime environments.

Wrap, refactor, and reference Matt's blog posts [here](https://www.habitat.sh/blog/2017/07/Habitat-on-Windows) and [here](https://www.habitat.sh/blog/2017/08/Habitat-plans-for-net-full-iis-apps).

**Comment by mwrock** [comment]
this is super old. closing.
