### ISSUE TITLE
Update docs to be more clear

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3241]
callbacks are build phases
hooks are runtime lifecycle events (i.e. application lifecycle hook) 
runtime configuration setting variables need a better name

At https://www.habitat.sh/docs/run-packages-update-strategy/ add It’s a requirement to have 3 participants in a service group to use rolling (on both application.environment and service.group level)

**Comment by tashimi** [comment]
https://github.com/habitat-sh/habitat/pull/3250

**Comment by tashimi** [comment]
#3251

**Comment by tashimi** [comment]
https://github.com/habitat-sh/habitat/pull/3252

**Comment by tashimi** [comment]
@fnichol what do you want to call runtime configuration setting variables? :P

**Comment by fnichol** [comment]
👍

**Comment by nellshamrell** [comment]
Closing this for now, if anyone has suggestions for something else to call "runtime configuration setting variables" feel free to open this back up with your suggestions!
