### ISSUE TITLE
Package search response has incorrect total count

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3245]
Repro - issue a package search command, such as :
http GET http://localhost:9636/v1/depot/pkgs/search/testapp Authorization:Bearer:${HAB_AUTH_TOKEN}

Get back a bunch of results... and :
    "range_end": 61, 
    "range_start": 0, 
    "total_count": 12

The total count should be 62

**Comment by chefsalim** [comment]
The channels API is doing some wierd things with the range as well - eg
http GET http://localhost:9636/v1/depot/channels/chefsalim/stable/pkgs Authorization:Bearer:${HAB_AUTH_TOKEN}

returns (on my machine):
{
    "data": [], 
    "range_end": 49, 
    "range_start": 0, 
    "total_count": 0
}

**Comment by raskchanky** [comment]
This is related to https://github.com/habitat-sh/habitat/issues/3207
