### ISSUE TITLE
Refactor to utilize ngcli, ngrx

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#3253]
This is a comprehensive refactor of the front-end, and will not be worked on until current priorities are complete.

The refactor includes:
- Rewrite of reactive store utilizing ngrx and ngrx patterns
- Utilization of ngcli build process, including new webpack configuration
- Updating to current package versions and Node LTS
- Rewrite of routing architecture for more accurate linking, search via url, etc

Boilerplate for this is already in place in the `mgamini/monster` branch.

**Comment by cnunciato** [comment]
Let's discuss approaches to this before further work is done on it.

**Comment by cnunciato** [comment]
We chatted on this and decided a good first course of action would be to pull ngrx-store into builder-web on a branch and see how it feels, since that seems to be the primary pain point right now. @mgamini would you be up for creating a new issue for that exploration?

**Comment by cnunciato** [comment]
@mgamini @elliott-davis Closing this given #3757 and #2986 and that we're sticking with Redux for now. (If we decide to address the routing bullet, we can open a new issue for that.)
