### ISSUE TITLE
Remove sidebar content from the Origin page

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3264]
Based on feedback the the UI was too cluttered (and detracting from the new demo flow), we opted to remove the sidebar from the Origin view (Packages tab) and move the 'Create origin' button.

- [x] move 'Create origin' button
- [x] Remove sidebar; make table (package list) full width

[Origin - Packages tab](https://chef.invisionapp.com/share/CRDLQBKKP#/252955475_160D_-_Origin_Added_-2-)

**Comment by reset** [comment]
Related to #3315
