### ISSUE TITLE
Sign-in view looks odd when signed in

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#3287]
![image](https://user-images.githubusercontent.com/274700/30752308-c61db1d0-9f70-11e7-8f30-2b70605164c4.png)

There's little use for this view when you're signed in, so we should either redirect to Origins or show only a properly styled Sign Out button and nix the non-applicable messaging. 

You haz thoughts, @ryankeairns?

**Comment by ryankeairns** [comment]
@cnunciato  I would much prefer a redirect to My Origins... this screen was not designed as part of the flow, it just sorta appeared in the rush of the initial release.

The Sign Out link from the profile drop down is a sufficient means of exiting (and it already works as expected).
