### ISSUE TITLE
Front End Package Version Sorting Incorrect

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#3288]
Our front end package sorting doesn't appropriately build the list of available packages.

![2017-09-22-121134_864x576_scrot](https://user-images.githubusercontent.com/12615148/30754108-6a455b78-9f8f-11e7-9215-7ff13e75b8ef.png)

The order is incorrect. Ideally I think having the latest version at the top would be expected. But also you can see from the image the latest version isn't actually being sorted to bottom either.

**Comment by cnunciato** [comment]
Looks like this is happening in the API; the front end is just reporting what's returned in the `/versions` call.

**Comment by raskchanky** [comment]
I'll take a look at the API side of this.
