### ISSUE TITLE
Automate Git Credentials in the Studio

### ISSUE THREAD

**Issue by danielsdeleo** [habitat-sh/habitat#3297]
I'd like my "standard" credentials to get passed through to the studio automatically whenever feasible. The use case is for build tools that fetch things from git, which is especially common for golang code but frequent enough elsewhere.

This was reported in https://github.com/habitat-sh/habitat/issues/2099 and closed as "good enough" with the `studiorc`, but in my opinion the experience falls short of hab's standards. The way it's done now is referenced in this documentation issue: https://github.com/habitat-sh/habitat/issues/3145 but it seems silly for everyone to need to cargo-cult that code around.

If at all possible, authentication should just follow me in to the studio so I don't think about it. If some extra configuration is actually required (maybe my SSH key has a non-standard name or whatever), it would be nice if I got an error message that helped me figure out what to do. It's tricky since the build tool is in charge but maybe some magic could be done by wrapping `git clone` and annotating the error message in some way.

**Comment by reset** [comment]
Closing as this is a dup of #2099 which should have not been closed
