### ISSUE TITLE
Easily expose full Habitat package identity

### ISSUE THREAD

**Issue by tduffield** [habitat-sh/habitat#3311]
**Request for functionality / documentation:** 

For those us who want to ensure that we're running a specific version of the Habitat Release (e.g. `0.32.0/20170918224903`) it can be a tedious and repetitive task to figure out what the fully-qualified package identity is. So far, this has typically involved downloading the tarball from the website then copy-pasting the release string wherever I need it. 

There are two major use cases for needing this information easily accessible: 

1. Pinning your environment to the release instead of just the version
2. Writing a test (e.g. an InSpec test) to ensure the desired release is installed

**Comment by reset** [comment]
@tduffield that API endpoint you're looking for is actually already live, hit this one `https://bldr.habitat.sh/v1/depot/channels/core/stable/pkgs/hab/0.33.2/latest`

![tenor-35416628](https://user-images.githubusercontent.com/54036/30821269-98da215c-a1d9-11e7-9133-d7d7e2df5213.gif)

**Comment by tduffield** [comment]
@reset Except that isn't accurate.

```
▶ curl -s https://bldr.habitat.sh/v1/depot/channels/core/stable/pkgs/hab/0.33.2/latest | jq -r ".ident.release"
20170925045915

github/chef/es-lita  master ✔                                                                                                                                                                                                                     41m
▶ hab --version
hab 0.33.2/20170925042638
```

`20170925045915` != `20170925042638`

**Comment by raskchanky** [comment]
@tduffield @reset The reason there is a discrepancy here is because `hab 0.33.2/20170925042638` is a Mac only build.  The depot doesn't currently support Mac packages, which is why that version doesn't show up under latest.  `hab 0.33.2/20170925045915` is the latest release for linux, which is what builder returns by default.

**Comment by tduffield** [comment]
@raskchanky Sure. I understand that. What I am asking for is a way to know the release for my workstation (i.e. anything available here: https://www.habitat.sh/tutorials/download).
