### ISSUE TITLE
[www] Create sample Node app for the demo flow

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3312]
The new demo (on the website) depends upon the user forking a sample Node app which is essentially just single view that shows a message and the package version.

The user can find the sample app in a GitHub Habitat repo; see a README exaplaining that its for the Habitat Demo (and see a screenshot preview); fork the sample app; optionally run it locally via `npm start`. They will export/publish this to a Docker container later and run it locally to see the mockup below.  Lastly, they're change the version in the plan.sh (to 1.0.2); run the new/updated container locally and see the new version number displayed (second mockup below).

[Mockup - initial state](https://chef.invisionapp.com/share/NJDNA4PEZ#/252336618_315_-_App_Preview) (shows initial package version 1.0.1)

[Mockup - after version update](https://chef.invisionapp.com/share/T4DNA6CJM#/252336619_375_-_App_Preview_V2) (shows next package version 1.0.2)

**Comment by nellshamrell** [comment]
Hello!  

I've created a sample node app here - which includes instructions in the README on how to Habiterize it https://github.com/habitat-sh/sample-node-app

One thing to note - this one does NOT show the Habitat package version in the page rendered in the browser, but it is a functional sample node js app that uses the node scaffolding.  If showing the package version number on the rendered page is critical, I can look into it, but it will need to be prioritized along with my existing work.

**Comment by tashimi** [comment]
@nellshamrell Hi Nell! Showing the habitat package is critical because it's how we're showing the user that builder is auto-updating packages for them.

**Comment by nellshamrell** [comment]
ah, gotcha.

**Comment by tashimi** [comment]
@nellshamrell yeah, I think that makes sense.

**Comment by ryankeairns** [comment]
Thanks Nell! As Tasha noted, the version number is the key bit of information here that we explicitly edit in the demo to bring home the update and rebuild :)

**Comment by apriofrost** [comment]
Add the link to the visual assets here in case we want to add the cats and logos: https://drive.google.com/drive/folders/0B6wx-y4RiRvoOXdIS3Bpa3MxUXc?usp=sharing

background color: #243442

**Comment by nellshamrell** [comment]
@tashimi @ryankeairns - I've added the display version from the plan.sh to the default view!

It's pretty bare bones right now, but displays the messaging you are looking for.  Do we want to go further with the visual look of it?
