### ISSUE TITLE
Default API URL no longer handles `/depot` suffix

### ISSUE THREAD

**Issue by tduffield** [habitat-sh/habitat#3313]
Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [ ] The OS (including version) where you are running any of the Habitat commands.

> Any. This has occurred on Mac and Linux.

- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		RUST_LOG=debug RUST_BACKTRACE=1 hab ...

```
▶ RUST_LOG=debug RUST_BACKTRACE=1 hab pkg upload --url https://willem.habitat.sh/v1/depot results/chef-es-lita-0.5.11-20170925144300-x86_64-linux.hart
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "pkg", "upload", "--url", "https://willem.habitat.sh/v1/depot", "results/chef-es-lita-0.5.11-20170925144300-x86_64-linux.hart"]
DEBUG:hab: remaining cli args: []
DEBUG:hab::config: Loading CLI config from /Users/tom/.hab/etc/cli.toml
✓ Signed artifact with chef-es-20160623231409.pub
DEBUG:habitat_http_client::api_client: User-Agent: hab/0.33.2/20170925042638 (x86_64-darwin; 16.7.0)
» Uploading public origin key chef-es-20160623231409.pub
DEBUG:habitat_http_client::api_client: POST https://willem.habitat.sh/v1/depot/depot/origins/chef-es/keys/20160623231409 with ApiClient { endpoint: "https://willem.habitat.sh/v1/depot", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.33.2/20170925042638 (x86_64-darwin; 16.7.0)") }
DEBUG:hyper::net: http scheme
DEBUG:hyper::net: https scheme
DEBUG:hyper::http::h1: request line: Post "/v1/depot/depot/origins/chef-es/keys/20160623231409" Http11
DEBUG:hyper::http::h1: headers=Headers { Host: willem.habitat.sh
, User-Agent: hab/0.33.2/20170925042638 (x86_64-darwin; 16.7.0)
, Authorization: Bearer [redacted]
, Content-Length: 78
, }
    78 B / 78 B | [===========================================================================================================================================================================================================] 100.00 % 614 B/s
DEBUG:hyper::client::response: version=Http11, status=NotFound
DEBUG:hyper::client::response: headers=Headers { Server: nginx/1.11.10
, Accept-Ranges: bytes
Accept-Ranges: bytes
, Via: 1.1 varnish
Via: 1.1 varnish
, Fastly-Debug-Digest: 232d73ae98d3a497376390b76075cee892f3312518ed7b9b5f5d6c91d7c57f20
, Content-Length: 0
, Date: Mon, 25 Sep 2017 15:39:55 GMT
, Connection: keep-alive
, X-Served-By: cache-sea1020-SEA, cache-dfw18636-DFW
, X-Cache: MISS, MISS
, X-Cache-Hits: 0, 0
, Strict-Transport-Security: max-age= 7776000; includeSubDomains
, X-Frame-Options: SAMEORIGIN
, }
✗✗✗
✗✗✗ [404 Not Found]
✗✗✗
```
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		env | grep HAB | grep -v HAB_AUTH_TOKEN

	- ***DO NOT include `HAB_AUTH_TOKEN`*** or any other sensitive information. More info on Habitat environment variables can be found [here](https://www.habitat.sh/docs/reference/environment-vars/).
	- [ ] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:
		- [ ] a. before starting the studio
		- [ ] b. inside the studio

- [ ] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.

		ls -la /hab/cache/keys
		ls -la $HOME/.hab/cache.keys

---

The issue appears to be that in a recent release of the Builder API, the default base URL was changed to no longer supporting specifying `/depot` in the URL calls. The [habitat-build](https://github.com/chef-cookbooks/habitat-build/blob/master/attributes/default.rb#L20) has, for over a year, specified the default url as `https://willem.habitat.sh/v1/depot`. With a recent release of the API, it now only supports `https://(willem|bldr).habitat.sh/v1`. 

I've already proposed [a change to habitat-build](https://github.com/chef-cookbooks/habitat-build/pull/44) to fix this problem there, but it's possible that other users who have also coded against the above assumption are running into this issue as well.

**Comment by raskchanky** [comment]
This was an intentional change.  https://github.com/habitat-sh/habitat/pull/3239 has the rationale for why it was done.
