### ISSUE TITLE
[www] New content and design for habitat.sh home page

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3316]
Update the website home page with new content and design elements.
Mockup: https://chef.invisionapp.com/d/main#/console/11769359/250490810/preview

**Comment by apriofrost** [comment]
Mobile view: https://chef.invisionapp.com/d/main#/console/12020243/253301618/preview
note: it's an older version, I'll update it to the latest homepage design tomorrow.

**Comment by apriofrost** [comment]
Updated the mobile view with the latest homepage design.
