### ISSUE TITLE
Account for binlink --force change throughout codebase

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#3323]
Now that #3248 is merged we still need to audit where `hab pkg binlink` gets called and potentially update calls where `--force` behavior is required. Locations such as the `install.sh` hab installer, provisioning, etc.

**Comment by fnichol** [comment]
This will be required before the next Habitat release

**Comment by reset** [comment]
@fnichol did you go through and get this done last night?

**Comment by fnichol** [comment]
Let me push my branch--it mostly affects `install.sh` at this point so doesn't need to be in the release proper.
