### ISSUE TITLE
Studio supervisor not using latest version of package

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#3329]
When trying to debug my node app, I ran into a problem where the Studio supervisor was starting up an older version of my package. 

<img width="713" alt="screen shot 2017-09-25 at 5 11 54 pm" src="https://user-images.githubusercontent.com/1634752/30836753-123b7ee8-a215-11e7-888f-e099e343550a.png">

I've tried it both with fully-qualified idents as well as the latest (i.e. `origin/package`). Same result.

Running hab 0.33.2 in Studio 0.33.2 via Docker on Mac workstation.

My current workaround is to exit and destroy the Studio (`hab studio rm`) before rebuilding.

**Comment by fnichol** [comment]
Did you already have a version of this running? `hab svc status` should confirm. If yes, then you’ll want to stop the service and call start again. We don’t yet have restart and a new install of a running package won’t trigger updates automatically (at least not without an explicit update strategy).

**Comment by davidwrede** [comment]
I'll check. I was running `sup-term` and `sup-run` before each `hab start`.

**Comment by davidwrede** [comment]
Nm. Can't seem to repro it now. I'll re-open if I'm able to repro it consistently.
