### ISSUE TITLE
[Builder] Expansion of package dependencies

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3340]
Currently, Builder uses the package run-time dependencies (DEPS/TDEPS) to build it's reverse dependency graph. The dependency data comes from the origin_packages table.  

The fact that we only trigger on runtime deps means that there are cases (eg, core/hab) where we won't automatically build on a large build (like openssl) because it doesn't have any runtime deps. 

This issue is about discussion of expansion of the dependency graph by including both build dependencies, and dependencies for composite plans (which will likely have a different format).

Things to take into account:
- Data model changes and ingestion into builder 
- Potential introduction of circular dependencies
- Impact of expansion of build graph
- Scalability / build resources required to support the expanded graph
- Other unknowns

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #41](https://github.com/habitat-sh/builder/issues/41) via [**ZenHub**](https://www.zenhub.com/)
