### ISSUE TITLE
Optimize session tokens

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3345]
This is related to https://github.com/habitat-sh/habitat/pull/3271

We can save some time traversing shards during account/session creation and retrieval if we create a fat session token that holds all the data we care about and store that, instead of storing the GH token directly.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #42](https://github.com/habitat-sh/builder/issues/42) via [**ZenHub**](https://www.zenhub.com/)
