### ISSUE TITLE
DO_CHECK is not passed to studio

### ISSUE THREAD

**Issue by wduncanfraser** [habitat-sh/habitat#3355]
Following up on conversation with @fnichol on slack, DO_CHECK is not white-listed to be passed to the studio.

Finding if I do a

```bash
DO_CHECK=true hab pkg build <path>
```

or

```bash
export DO_CHECK=true
hab pkg build <path>
```

tests are never run.  Currently, DO_CHECK has to be explicitly set in the studio to take effect, which means when builds are being run pragmatically, they have to be executed in a way similar to this:

```bash
hab studio run "DO_CHECK=true build <path>"
```

**Comment by eeyun** [comment]
Ah good find indeed! Another thing you could try as a temporary workaround is to set this in your `.studiorc` file. Doing so will probably unblock folks who are trying to do non-interactive builds. Thank you for opening this issue!

**Comment by baumanj** [comment]
Can we roll this into https://github.com/habitat-sh/habitat/issues/5462? I'd rather see us move away from implicit magic than add more.

@apriofrost: what do you think?
