### ISSUE TITLE
Constrain use of HAB_UPDATE_STRATEGY_FREQUENCY_MS

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3363]
This variable determines how often we check for service updates. We should consider constraining its usage somehow (e.g., defining a floor below which you can't set the value).

Setting it to a low value is handy for testing, but you can cause problems if you set it to a very small number in a production setting.

**Comment by rsertelon** [comment]
What would be this value?

**Comment by christophermaier** [comment]
Not sure exactly, and we'd want a way to bypass for testing purposes. The current default is 60,000ms (1 minute), though; that seems like a decent candidate for a floor value.
