### ISSUE TITLE
`hab bldr channel` subcommand

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3384]
We've got API endpoints for CRUD operations on channels and we need to pipe it through to the CLI

* `hab bldr channel create <name>`
* `hab bldr channel destroy <name>`

**Comment by tashimi** [comment]
Mostly as a note for something I just went and figured out: 
- `hab pkg promote core/pkg/version channel_name`
- `hab pkg demote core/pkg/version channel_name`  
- ^^ but then what replaces the demoted package in that channel? Is the pointer just to nil until a new package is promoted?

**Comment by raskchanky** [comment]
@tashimi The package is just removed from that channel.  Nothing takes its place.  So if that package was the only package in channel `foo` and you demoted it from channel `foo` then now, channel `foo` is empty.

**Comment by rsertelon** [comment]
@reset Am I right to assume that we also need to provide an `origin` to the command? I suppose we try to use the configured one first, or override via a `--origin` flag?
