### ISSUE TITLE
Add cloudfoundry exporter on UI 

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3385]
We need to add the command `hab pkg export cf <pkg name>` to the UI under "export command", for example: https://bldr.habitat.sh/#/pkgs/core/erlang16/latest

**Comment by cnunciato** [comment]
@tashimi Should this be limited to packages that are also services (or some other criteria), or should it be visible to all packages?

**Comment by tashimi** [comment]
@cnunciato that is a great point, we should totally limit it in that way

**Comment by cnunciato** [comment]
Ok, we’ll restrict it to services only then, as we do with the others.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #43](https://github.com/habitat-sh/builder/issues/43) via [**ZenHub**](https://www.zenhub.com/)
