### ISSUE TITLE
Cant create job when no package has been uploaded

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#3391]
I created a project on an empty builder pointing to a GH repo. When i call `http://192.168.137.100:9636/v1/depot/pkgs/schedule/core/firewatch` I get a 404 with `{"code":4,"msg":"sc:group-create:3"}` which is coming from an error in the graph resolution.

**Comment by raskchanky** [comment]
@mwrock I wonder if that's because it can't find some of firewatch's dependencies.

**Comment by mwrock** [comment]
I doubt it because it would first have to clone it in order to discover its deps. However it would certainly fail on first build if those were not present.
