### ISSUE TITLE
Make sure builder-worker can still use the private key it fetches

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3396]
In https://github.com/habitat-sh/habitat/pull/3388 the API endpoint that returns a private key was changed so that it returns the key as a file, similar to how the public key API endpoint works.  However, builder-worker currently uses the private key API endpoint to fetch private keys for builds.  We should double check that everything still functions correctly after that change, and if it doesn't, modify the worker to use the new API endpoint.

**Comment by fnichol** [comment]
Confirmed, @chefsalim took care of this in #3417
