### ISSUE TITLE
Launcher not reaping children

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3406]
We're seeing two cases of log spamming which seem to occur after an auto-upgrade of a service and/or auto-upgrade of the Supervisor itself

1. When a child process exists it is supposed to be reaped but we seem to never clear it's pid from the `ServiceTable` https://github.com/habitat-sh/habitat/blob/master/components/launcher/src/server/mod.rs#L203-L209
1. Same issue as above but for when an IO error occurs https://github.com/habitat-sh/habitat/blob/master/components/launcher/src/server/mod.rs#L211-L214

We need to ensure the PID is dropped from the `ServiceTable`

**Comment by alex-bender** [comment]
subscribing to the notifications.

**Comment by mwrock** [comment]
fixed by #3764
