### ISSUE TITLE
Scrub docs for broken links, add in redirects

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#3407]
Now that #3374 has been merged, the docs need to be scrubbed for broken links. Also, redirects need to be added directing people to the new topics/sections.

**Comment by tashimi** [comment]
@davidwrede currently doing this too, will link PR here

**Comment by tashimi** [comment]
See #3416. I will keep going tomorrow, about 1/3 (optimistically) of the way through the partials.

Need to: 
- check every header to ensure it says `name` and *not* `href`
- fix all links to other docs pages
- the last partial I did alphabetically is _dev_pkgs_write-plans
- I saw a remaining bad link in the container scheduler doc when I was re-basing that should be re-addressed.

**Comment by davidwrede** [comment]
Note: We also need to scrub links from the blog posts back to the docs. I've fixed the link in the container scheduler doc and a few others, but I'm going to focus on the blog post links first before diving back into the others.

**Comment by davidwrede** [comment]
@tashimi Here's what I have so [far](https://github.com/habitat-sh/habitat/pull/3427). Feel free to pull down my branch and add to it. I'll jump back into this later tonight.

**Comment by tashimi** [comment]
@davidwrede I think I got everything in the partials via https://github.com/habitat-sh/habitat/pull/3429/

**Comment by tashimi** [comment]
@davidwrede #3429 has been merged, I will rebase your PR and try to get it in. Holler if you're already in process :)

**Comment by davidwrede** [comment]
All remaining broken links should be fixed in #3427, so once that's merged we should be gtg.

**Comment by tashimi** [comment]
![tenor-211836327](https://user-images.githubusercontent.com/719646/31064945-128eb4ec-a6f6-11e7-944d-16f88be85ec0.gif)
