### ISSUE TITLE
Reverse dependency lists and private packages

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3409]
Right now, the [builder-api rdeps_show handler](https://github.com/habitat-sh/habitat/blob/master/components/builder-api/src/server/handlers.rs#L148) does not respect private packages.  If you call that with a package identifier, it will fetch all of the reverse dependencies, even if those include private packages that you are not authorized to see.  The only place this API call is used is in the `hab bldr job start` command, where it is used to [print out a list of all the jobs](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/bldr/job/start.rs#L38-L55) that will be scheduled if you start a group.

I attempted to solve this problem already, and it is a delicate and sticky situation.  We should talk through how this should work.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #44](https://github.com/habitat-sh/builder/issues/44) via [**ZenHub**](https://www.zenhub.com/)
