### ISSUE TITLE
Search seems broken

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/habitat#3435]
When one searches for a package at https://bldr.habitat.sh/#/explore they will be directed at `https://bldr.habitat.sh/#/pkgs/search/<search>`

The website then tries to show a package with origin `search` at this point which, I believe, is not what's intended.

**Comment by tashimi** [comment]
@rsertelon thanks for filing an issue on this, we will take a look and see what's up

**Comment by rsertelon** [comment]
This seems to be a routing issue in `builder-web`.

Two namespaces collide `pkgs/:origin/:name` in file `package-routing.module.ts` and `pkgs/search/:query` in file `search-routing.module.ts`.

Maybe it's because of module import order in `app.module.ts` ? (Package is imported first)

**Comment by rsertelon** [comment]
Really hard for me to make Bldr work (and it's late ;)), can't validate my first guess, sorry!

**Comment by tashimi** [comment]
I've confirmed this is broken in prod and acceptance. 

![image](https://user-images.githubusercontent.com/719646/31160053-5a8f03cc-a882-11e7-9db7-97e8784192d1.png)

![image](https://user-images.githubusercontent.com/719646/31160062-6afc9526-a882-11e7-8a3d-af3409b69fd8.png)
