### ISSUE TITLE
UI should reflect not all packages are runnable

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3453]
Not all packages are runnable. I believe @raskchanky added an API endpoint to indicate if a package is runnable or not. If a package is not runnable, the UI should not indicate that you can "Run" or "Export" a package. 

![image](https://user-images.githubusercontent.com/719646/31097426-1b1da784-a774-11e7-83f0-edc90f84feaa.png)

cc @ryankeairns for general awareness

**Comment by cnunciato** [comment]
Fixed with #3572.
