### ISSUE TITLE
Fill in Dockerhub description fields

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#3456]
It would be great if we could add a "short" and "long" description to Habitat packages published to Dockerhub including a short description of the package, that it is built with harts (?) by Habitat Builder, and a link back to the correct Habitat Builder page. This will increase visibility and discoverability of the Habitat Builder service and be a better user experience. 

![image](https://user-images.githubusercontent.com/719646/31097696-09425c7a-a775-11e7-8e98-7516fc2e3277.png)

**Comment by fnichol** [comment]
This will take some research, but I'm hopeful!

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #46](https://github.com/habitat-sh/builder/issues/46) via [**ZenHub**](https://www.zenhub.com/)
