### ISSUE TITLE
New summary copy needed for Build Your Web App tutorial 

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#3463]
On the tutorial landing page(https://www.habitat.sh/tutorials/), the summary content for the Build Your Web App tutorial is copied directly from the one above it (build a sample app). It needs a new summary copy for its own.

![image](https://user-images.githubusercontent.com/9401459/31108872-d2595646-a7b0-11e7-9142-4a64fb5aeee7.png)

**Comment by davidwrede** [comment]
@apriofrost I noticed this as well and have updated the copy in the node web app guide content that I'm working on.

**Comment by davidwrede** [comment]
Update: I separated out this update from my new web app guide so that we could get it merged in sooner. #3551 is the correct PR for this fix

**Comment by eeyun** [comment]
Closed by #3551!
