### ISSUE TITLE
Provide a way to find where files exist in packages found in the Depot

### ISSUE THREAD

**Issue by burtlo** [habitat-sh/habitat#3465]
As a Habitat developer 
    Given that I am building ImageMagick
    When I configure and build ImageMagick 
    And it reports that the file `jerror.h` cannot be found
    Then I want to run a command like `hab pkg provides jerror.h` 
    And see a list of packages in the depot that contain the file `jerror.h`.

I am new to building software from source. So when I see a configuration script not find a particular file or build macro (autoconf) I don't know immediately where to look for it. I know that the core packages are using some naming conventions similar to what I would find in many Linux distros so searching the Internet sometimes gives clues. But there are enough variations that it makes it hard to know.

In this situation I describe above it is pretty clear that I need a JPEG library because ImageMagick makes it clear:

```
-------------------------------------------------------------
checking for JPEG...
checking jconfig.h usability... no
checking jconfig.h presence... no
checking for jconfig.h... no
checking jerror.h usability... no
checking jerror.h presence... no
checking for jerror.h... no
checking jmorecfg.h usability... no
checking jmorecfg.h presence... no
checking for jmorecfg.h... no
checking jpeglib.h usability... no
checking jpeglib.h presence... no
checking for jpeglib.h... no
checking for jpeg_read_header in -ljpeg... no
checking for JPEG library is version 6b or later... no
checking if JPEG package is complete... no
-------------------------------------------------------------
```

For other packages that I have attempted to build I have often times not known where to start.

I solved the above situation by using `hab pkg search jpeg`, installed the two core jpeg packages (`libjpeg-turbo` and `openjpeg`). Then used `hab pkg provides jerror.h` and was able to find the file I needed. I am suggesting this strategy to others in the documentation I am creating. However, this strategy will not always work or may require you to boil the ocean `hab pkg install EVERYTHING` to perform a `hab pkg provides`.

**Comment by reset** [comment]
@burtlo this is an enhancement that we'll definitely implement

![tenor-222252139](https://user-images.githubusercontent.com/54036/31150928-5c929cb6-a84a-11e7-8297-6da05dab2b6e.gif)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #47](https://github.com/habitat-sh/builder/issues/47) via [**ZenHub**](https://www.zenhub.com/)
