### ISSUE TITLE
Update the export command on the tutorials

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3467]
In order to avoid having to upload your build artifact first, we should change the export command in the tutorials so that you can still export the local build you just created.

More specifically, it should change from `hab pkg export docker origin/package` to something like `hab pkg export docker ./results/<hart-filename>`

- https://www.habitat.sh/tutorials/sample-app/mac/build-package/
- https://www.habitat.sh/tutorials/build-your-own/build-test/#export-container

**Comment by tashimi** [comment]
Closed #3471
