### ISSUE TITLE
The Supervisor repeatedly tries to run "services" that are not actually services

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3468]
Before loading or starting a service, we should actually check that the package is actually a service (i.e., something that has a `run` script). Otherwise, the supervisor will endlessly try to execute a non-existent file, as seen below when I try to start `core/hab-butterfly` (a library, not a service).

```
hab-sup(MR): Supervisor Member-ID b3f9ee13770f4cffa5f0f04d624790e7
hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
hab-sup(MR): Starting core/hab-butterfly
hab-butterfly.default(HK): Hooks compiled
hab-butterfly.default(SR): Error finding run file: No such file or directory (os error 2)
hab-butterfly.default(SR): Initializing
hab-butterfly.default(SV): Starting service as user=hab, group=hab
hab-butterfly.default(SR): Service start failed: hab-sup(ER)[src/error.rs:479:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
hab-butterfly.default(SV): Starting service as user=hab, group=hab
hab-butterfly.default(SR): Service restart failed: hab-sup(ER)[src/error.rs:479:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
hab-butterfly.default(SV): Starting service as user=hab, group=hab
hab-butterfly.default(SR): Service restart failed: hab-sup(ER)[src/error.rs:479:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
hab-butterfly.default(SV): Starting service as user=hab, group=hab
hab-butterfly.default(SR): Service restart failed: hab-sup(ER)[src/error.rs:479:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)
... etc, until the heat death of the universe
```

`PackageArchive` already has an [is_a_service](https://github.com/habitat-sh/habitat/blob/ab7d932ac4ece39a922b2961742f5531f84299ad/components/core/src/package/archive.rs#L113-L122) function, which can surface this information. We may want to add a similar function to `PackageInstall`, because that is what we'll have access to in the `hab` CLI when we're starting / loading services.

(We could add some checking in the supervisor itself to prevent it from trying to re-run if there's no `run` hook; that may be a more intricate change, though, and may end up falling out of the upcoming rewrite of the supervisor's internals. In any event, alerting the user as soon as possible that they can't run a given package is something we should do anyway.)

Incidentally, it may also be worth looking at factoring out these metadata-lookup functions from `PackageArchive` and `PackageInstall`; they're both returning the same information, but one is from a `.hart` file, and the other from an expanded directory on disk.

**Comment by rsertelon** [comment]
Is this linked to #3105 ? (looks really similar)

**Comment by christophermaier** [comment]
@rsertelon My initial impression is that they're different, particularly since the errors in #3105 were said to be random; if a package didn't have a run hook, this would happen 100% of the time.
