### ISSUE TITLE
[builder-worker] Clean up `job.root()/dockerd` directory on teardown.

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#3484]
Currently the Docker Engine's data directories aren't cleaned up when the job is torn down. It shouldn't be big at the moment as the exporter cleans up its image layers.

**Comment by fnichol** [comment]
This is non-critical and only applies to hosted Builder. We'll fix this shortly, but doesn't impact exporting Docker images.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #48](https://github.com/habitat-sh/builder/issues/48) via [**ZenHub**](https://www.zenhub.com/)
