### ISSUE TITLE
Habitat 0.34.1 docker export needs pkg uploaded to public builder

### ISSUE THREAD

**Issue by dmajere** [habitat-sh/habitat#3494]
Command output example:

```
» Installing jlebloas/myrailsapp from channel 'stable'
✗✗✗
✗✗✗ Package not found
```

Known workaround:
running export as  `hab pkg export docker ./results/<hart-filename>`

**Comment by fnichol** [comment]
Hi there! You are correct with the updated Docker exporter that if you provide a package identifier (i.e. `jlebloas/myrailsapp`) that this is assumed to be installed from Builder. Your known workaround is more than a workaround--it is exactly how the hosted Builder workers will build Docker images.

Is there anywhere (docs, blog posts, etc.) where we can help to make this clearer? Thanks!

**Comment by dmajere** [comment]
Well, there were several questions about that on a Slack channel.
It would be useful to have such info in release notes, or did I missed that?

**Comment by nellshamrell** [comment]
Apologies for the lack of communication - this had been updated in the tutorials and documentation.  We will work to make sure we communicate this kind of change better in the future.
