### ISSUE TITLE
re-building service results in spammed child exiting with code signal 15

### ISSUE THREAD

**Issue by tflecht** [habitat-sh/habitat#3505]
Running within a hab studio, host OS OSX 10.12.6, habitat version 0.34.1, I bring up several services together. If I then again build one of those services and re-apply the rendered configuration for it, habitat starts spamming

`hab-launch(SV): Child for service '<SERVICE-NAME>.default' with PID 4294961421 exited with code signal: 15`

```
$ # OUTSIDE OF STUDIO
$ env | grep HAB | grep -v HAB_AUTH_TOKEN
HAB_DOCKER_OPTS=-p 80:80 -p 443:443 -p 8076:8076 -p 9090:9090 -p 9631:9631 -p 8090:8090
$ # INSIDE OF STUDIO
[1][default:/src:0]# env | grep HAB | grep -v HAB_AUTH_TOKEN
HAB_ORIGIN=tflecht
HAB_BINLINK_DIR=/hab/bin
```

I can provide the full supervisor log, if that's helpful.

**Comment by srenatus** [comment]
Just chipping in with some details
> re-apply the rendered configuration for it, habitat starts spamming

☝️ this something internal, but it boils down to a `service-name.toml` being generated and passed to
```
vsn=$(echo $BASHPID) # strictly increasing
hab config apply service-name.default $vsn service-name.toml
```
just before
```
hab sup start $HAB_ORIGIN/service-name --strategy at-once --bind ...
```

**Comment by gfodor** [comment]
Wondering if this might be related to https://github.com/habitat-sh/habitat/issues/3406

I am seeing log spam with these large 4XXX pids when I shut down a service

**Comment by eeyun** [comment]
It _might_ be. Or at least might be tangentially related. The fix from #3406 hasn't been released just yet. Let's revisit this after our next release and see if it's resolved.

**Comment by reset** [comment]
Since we release the Launcher at a different interval this actually has been released to the stable channel for a few days now. We haven't been able to repro the issue and we verified with a few reporters that they haven't been able to either. I think this is good to close!

**Comment by chrisortman** [comment]
What version of the launcher do you need for this? How do I get it?

With 

```
 3107 ?        Ssl    0:00 /hab/pkgs/core/hab-launcher/5187/20170926171711/bin/hab-launch run
 3109 ?        Sl     0:03 /hab/pkgs/core/hab-sup/0.38.0/20171026221910/bin/hab-sup run
```

I am still seeing this error (but exit code 143 not 15)
