### ISSUE TITLE
plan files are not discovered for forked repositories

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#3510]
In my mwrock org I have forked the node app and installed the acceptance habitat app. However when connecting the plan, acceptance cannot find the plan file. I think this is related to the code search. Currently https://bldr.acceptance.habitat.sh/v1/ext/installations/57406/search/code?q=repo:mwrock/asamplenodeapp+filename:plan&page=1&per_page=100 is returning 0 hits.

**Comment by mwrock** [comment]
Discovered this is not related to org but rather if the repo is forked or not. The GH code search API call must include `fork:true` to include forked repos in the search. However a huge caveat is that the fork must have more stars than the parent in order for it to be indexed.

Per conversation with @ryankeairns and @cnunciato we will instead be asking users to explicitly specify the path to their plan via a text box entry.

**Comment by ryankeairns** [comment]
... and that text box entry existed previously. Let's bring it back as it was - defaulting to /habitat and verifying the plan.sh exists in the location entered (e.g. /habitat/plan.sh).

**Comment by cnunciato** [comment]
Doing the following things for this: 

* [ ] Show the GitHub-related message box explaining how to link up the app.
* [ ] Indicate when there aren't yet any orgs with the app installed.
* [ ] Indicate when the selected org doesn't contain a linked/permitted repository. 
* [ ] On repo select, provide a text field for specifying the plan
* [ ] Then the value of that field changes, validate that it actually exists
