### ISSUE TITLE
Dependency Conflict Output is Hard to Read

### ISSUE THREAD

**Issue by danielsdeleo** [habitat-sh/habitat#3515]
When hab gets a dep conflict, it prints the full dep graph, which can be quite large for something like a ruby app. An example of that is here: https://gist.github.com/danielsdeleo/c431943a6f6244a68fabbb70be4fef07 It's 255 lines long and shows me a lot of unrelated information. In order to understand where the dependencies are coming from, the relevant info is just this:

```
kallistec/chef-dk/2.3.9/20171004215509
    core/ruby/2.4.2/20170914220737
        core/openssl/1.0.2j/20170513215106 (*)
    core/openssl/1.0.2j/20170926165227 (*)
```

It also could just be written in english saying something like:
> Your plan has a dependency on `core/openssl` which is resolved to `core/openssl/1.0.2j/20170926165227` but `core/ruby` which is included by your plan was was built with `core/openssl/1.0.2j/20170513215106`

It would be great also to provide some advice on how best to resolve the situation, when feasible.

**Comment by reset** [comment]
@danielsdeleo absolutely, I particularly think the english/human readable version is the way to go

**Comment by eeyun** [comment]
Yes indeed. Can't agree enough.

**Comment by rickmarry** [comment]
totally agree.
