### ISSUE TITLE
[STABILITY] Permission denied issue on builder-api-proxy directory

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3521]
We need to fix the issue where the supervisor sets the service directories to be owned by root, when they should be owned by the 'hab' user (nginx scenario).

**Comment by chefsalim** [comment]
Re-opening as the hook fix does not seem to work.
Also we should handle the permission change for the builder api data folder.

**Comment by chefsalim** [comment]
Re-opening as this is still occuring

**Comment by tashimi** [comment]
pretty sure this issue is still happening, and known to be so; Chris had to fix the permissions in acceptance in builder-api-proxy manually today

**Comment by burtlo** [comment]
Thank you very much for fixing this!
