### ISSUE TITLE
Habitat tutorial "Create and Seed the Database" not found error

### ISSUE THREAD

**Issue by lhasadreams** [habitat-sh/habitat#3534]
Hi,
I am going through the Habitat tutorial here - [https://www.habitat.sh/tutorials/sample-app/mac/update-app/](https://www.habitat.sh/tutorials/sample-app/mac/update-app/) and have come to the section where `docker-compose exec railsapp myrailsapp-rake db:setup` is run to seed the database, however I am getting an `\"myrailsapp-rake\": executable file not found in $PATH"`
If I open a bash shell in the container I cannot find the process bin for rake or run the myrailsapp-rake command.
My plan is the same as the tutorial and just uses the core/scaffolding-ruby scaffolding, which I assumed would bring the required process bins with it?
hab 0.34.1/20171002011028 running on macOS 10.12.6 with Docker 17.06.2-ce-mac27 (19124)
Any idea what I may have done wrong?

**Comment by lhasadreams** [comment]
A work around has been provided as follows:

> Following on up the db creation step in the tutorial, run `docker-compose exec railsapp hab pkg exec origin/myrailsapp myrailsapp-rake db:setup` to work around the problem.
> 
> The new Docker export functionality changed what was included in the PATH variable, but the expected behavior will move back to what's currently shown in the docs (or something close to it) in an upcoming release while at the same time not including everything in PATH.
> 
> For now, run the command above and you should be unblocked.

**Comment by davidwrede** [comment]
As the right solution may not be implemented right away, the workaround has been added to the tutorials in #3634.
