### ISSUE TITLE
Habitat www : sidebar running into footer

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#3555]
![image](https://user-images.githubusercontent.com/223407/31246967-f9555d52-a9c3-11e7-9790-dd41e9ed2857.png)

**Comment by eeyun** [comment]
Is this an issue with the sidebar running into the footer or an issue of needing the sidebar to close a previously expanded section, when you open a new section?

**Comment by mgamini** [comment]
@eeyun I'd prefer the former, but we could solve both!
