### ISSUE TITLE
net:route:3 / Resource temporarily unavailable errors

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3561]
Seeing the following errors on acceptance:

Oct 05 19:41:51 ip-10-0-0-136 hab[32474]: builder-api.acceptance(O): ERROR:habitat_depot::server: Unable to check package dependency: origin: "core" name: "nats-streaming-server" version: "0.3.6" release: "20171005193914", err: NetError(code: BUG msg: "net:route:3")
Oct 05 19:41:52 ip-10-0-0-136 hab[32474]: builder-api.acceptance(O): WARN:habitat_depot: Package not found at "/hab/svc/builder-api/data/pkgs/54/5f/core-libsodium-1.0.13-20171005193911-x86_64-linux.hart"
Oct 05 19:41:56 ip-10-0-0-136 hab[32474]: builder-api.acceptance(O): ERROR:habitat_net::conn: [err: BUG, msg: net:route:3], Connection send/recv error, Resource temporarily unavailable

**Comment by reset** [comment]
We increased the socket send/recv timeouts from 5s to 10s and it alleviated the problem almost completely. I further increased the timeout to 15s. We can continue to tweak as needed, but this most certainly was a timeout occurring when reaching out to a remote service (like GItHub)
