### ISSUE TITLE
List origin projects and provide a way to navigate to them

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#3579]
We need a way to modify the settings of a project/plan-connection that doesn't yet have any packages. This can be handled in the Settings tab -- we just need the UI to provide a way to navigate to that.

**Comment by cnunciato** [comment]
cc @ryankeairns

**Comment by ryankeairns** [comment]
Adding link to mockups for this... in it you can:
1. view a pending packages (ie. plan connected, but not available releases yet)
2. view a package that has only manual uploads, just for comparison purposes

- [ ] Add a new table above Packages that lists projects which have not .harts in the depot yet.

### Mockups
[Pending packages](https://chef.invisionapp.com/share/X3DQCM6DU#/249855195_create_Package_Empty)

cc:/ @raskchanky

**Comment by ryankeairns** [comment]
This is good for launch, but I’d like to keep it open until it more closely resembles the mockup. We can move it to On Deck. 

Nice work knocking this out last minute @raskchanky !

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #49](https://github.com/habitat-sh/builder/issues/49) via [**ZenHub**](https://www.zenhub.com/)
