### ISSUE TITLE
hab pkg (uninstall|rm|remove|\?\?)

### ISSUE THREAD

**Issue by jtimberman** [habitat-sh/habitat#3586]
Hello habitat friends!

We have in the habitat cookbook repository an issue about [the remove action](https://github.com/chef-cookbooks/habitat/issues/9). We have this action available because the intent of the `hab_package` resource is to behave like other `package` resources in Chef. However, the removal of the packages via Chef is dangerous.

It would be much better if the `hab` CLI had a sub-command for removing/uninstalling packages. This was brought up in #2572 by @ryankeairns:

> I might want to remove specific packages that I no longer want to use/have replaced in my plan as I write and build from it. For example, something like hab pkg rm core/mysql or hab pkg uninstall core/mysql if, say, I switched to use a different db package.

**Comment by eeyun** [comment]
I wonder if this wouldn't also be a good spot to add some kind of pruning behavior (which would definitely make a PR in this area significantly more complex). It might be dope to be able to prune away all of the old packages on a system that are no longer being used.

**Comment by reset** [comment]
Working PR for this is here #3717

**Comment by rsertelon** [comment]
@eeyun for the pruning part, there's this issue already: #3499

**Comment by baumanj** [comment]
Resolved by https://github.com/habitat-sh/habitat/pull/5737
