### ISSUE TITLE
Build worker can panic

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3613]
Seeing a panic on live - need to investigate

Oct 07 22:14:24 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:24 ip-10-0-0-100 hab[3323]: builder-worker.live(O): ERROR:habitat_builder_worker::runner: failed to fetch origin secret key, err=Err(APIErro
Oct 07 22:14:27 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:30 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:33 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:34 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:35 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:37 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:38 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:39 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:40 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:41 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:45 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:48 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:49 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:54 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:14:55 ip-10-0-0-100 hab[3323]: builder-worker.live(HK): Hooks compiled
Oct 07 22:15:25 ip-10-0-0-100 hab[3323]: builder-worker.live(O): ERROR:habitat_builder_worker::runner: failed to fetch origin secret key, err=Err(APIErro
Oct 07 22:16:26 ip-10-0-0-100 hab[3323]: builder-worker.live(O): ERROR:habitat_builder_worker::runner: failed to fetch origin secret key, err=Err(APIErro
Oct 07 22:17:27 ip-10-0-0-100 hab[3323]: builder-worker.live(O): thread 'runner' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr:
Oct 07 22:17:27 ip-10-0-0-100 hab[3323]: builder-worker.live(O): note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by chefsalim** [comment]
Looks like the root cause was not having the encryption keys for the private repos, which causes the JWT library to cause a panic._

**Comment by reset** [comment]
@chefsalim yep, that's what it was. Let's close this out for now.

For anyone else following along we also are now building debug symbols into our release builds of Builder services and RUST_BACKTRACE is set to true in all of their run hooks.
