### ISSUE TITLE
Job status update did not make it to scheduler - group stuck

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3621]
Run of glibc on acceptance
Dependent job 'core/libcap-ng' was completed successfully, job srv thinks it's completed and status sync'd with scheduler, but scheduler thinks it is still in progress. There are no unprocessed status messages in the message queue.

builder_scheduler=# select * from projects where owner_id='823645485334888448' and project_state='InProgress';
  id  |      owner_id      |  project_name  |            project_ident            | project_state |       job_id       |          created_at           |
         updated_at
------+--------------------+----------------+-------------------------------------+---------------+--------------------+-------------------------------+-
------------------------------
 9278 | 823645485334888448 | core/libcap-ng | core/libcap-ng/0.7.8/20171005195945 | InProgress    | 823650667375706112 | 2017-10-08 08:46:24.145843+00 |
2017-10-08 09:02:26.415247+00
(1 row)

builder_jobsrv=# select id,owner_id,project_name,job_state,scheduler_sync from jobs where project_name = 'core/libcap-ng' order by created_at desc;
         id         |      owner_id      |  project_name  | job_state | scheduler_sync
--------------------+--------------------+----------------+-----------+----------------
 823650667375706112 | 823645485334888448 | core/libcap-ng | Complete  | t

**Comment by chefsalim** [comment]
Updated scheduler logging (and error handling) to better identify the root cause (and potentially resolve it).

**Comment by reset** [comment]
@chefsalim was this resolved by the recent changes?

**Comment by chefsalim** [comment]
Re-opening as it looks like this may still be occurring - happened with a core/node build group on 11/1.

**Comment by chefsalim** [comment]
So what I think is happening is that there is a race condition when a job status is being processed by the scheduler - if an update to the job status comes in (received by the worker manager thread during this time), then the scheduler_sync flag can get cleared by the scheduler without processing that new update, and the update gets lost.
