### ISSUE TITLE
Instruct users to reload after installing the app in the plan connect view

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#3631]
When a user lands on a "connect a plan" view and has not installed the builder app on their org, they will not have their repos recognized...we know that. We have an instructional box informing the user to install the app if they have not done so. It provides a link to the app that opens in a new tab. So if the user proceeds to install the app ina new tab, the connect a plan tab will still not see their repos until they reload the view. We should add a sentance to the efect of: "Reload this page after installing the app." And have "reload" be a link to actually reload.

There is likely a better experience to be had here but this may be the quickest fix for now.

**Comment by cnunciato** [comment]
@ryankeairns thoughts? Still a couple of rough edges here; we could probably poll GitHub every few seconds looking for an install, and kick in automatically when either an installation or the the repo you've selected turns up.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #50](https://github.com/habitat-sh/builder/issues/50) via [**ZenHub**](https://www.zenhub.com/)
