### ISSUE TITLE
[builder ui] Make it easier to copy package identifiers out of Builder web

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#3675]
When you have to do something on the CLI, it'd be great to be able to copy and paste the package identifier out of the web app. For example, when promoting a release, you need the full package identifier, but that's not easy to get from these views:

https://bldr.habitat.sh/#/pkgs/core/builder-api
https://bldr.habitat.sh/#/pkgs/core/builder-api/5693/20171009170247

Pre-requiste
- [x] UX: add mockup of copy feature

### Mockup
[Mockup - copy full ident from versions tab](https://chef.invisionapp.com/share/6CEFVIATX#/263696522_package_Detail_Version_Build_Promote)

Mockup Notes:
- Invision does not support an onmouseout trigger/action, but if you hover off the copy icon, then it would return to its original state (20% transparent color). 
- Also, upon clicking the copy icon, the 'copied' tip would appear just as it doesn in the current right-hand sidebar when copying a command.

**Comment by cnunciato** [comment]
cc @ryankeairns

**Comment by eeyun** [comment]
YES YES INDEED. I've hit this a bunch of times. This is a wonderful little UX spot.

**Comment by cnunciato** [comment]
It is done.
