### ISSUE TITLE
[builder ui] Better error message when connecting a plan more than once

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#3676]
As a user, when I'm connecting an Origin to a Plan file that is already connected, I get a 'danger' error message. It would be more helpful if the message could clarify that the Plan is already connected to this Origin.
![image](https://user-images.githubusercontent.com/9401459/31351172-e6d3873a-acde-11e7-94cd-6c6f99cd16df.png)

**Comment by mgamini** [comment]
This looks like it's already taken care of: 

![image](https://user-images.githubusercontent.com/223407/32239435-e9d2d6fc-be40-11e7-825b-1bc25fee7aa4.png)
