### ISSUE TITLE
Add endpoint to builder-api for validating integration creds

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3677]
We can't be sure that all integrations we'll be CORS friendly - Docker for example isn't. We need to add an endpoint to Builder-API under `/ext` (external) to validate integration credentials on behalf of our web client

Related, the UI side of this is in #3625

**Comment by ryankeairns** [comment]
There is an existing issue for this on the UI side: https://github.com/habitat-sh/habitat/issues/3625
