### ISSUE TITLE
Auto-build not triggered on GitHub PR merge

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3679]
We're only listening for push events right now which is fine for how the Habitat repositories work, but not for the typical GitHub work flow of opening an issue with a feature branch and pressing the merge button directly.

We need to add an additional handler for PR events and add read access to our GitHub App's permissions

**Comment by raskchanky** [comment]
Turns out push events _are_ sent when PRs are closed by clicking the merge button after all.  I confirmed this locally, so I think we're good here.
