### ISSUE TITLE
[builder ui] Surface Download & Install link more in Builder home and Docs

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#3684]
As a user, I want to be able to quickly get the latest version of the Habitat CLI on my machine. Currently, the link to the download page (https://www.habitat.sh/tutorials/download/) is through the _tutorials->download and install_ or _docs->using Habitat->install Habitat_  or the footer->Download CLI. It would be more helpful if it could be surfaced more obviously on the website/web app.

Places to consider:

- Under 'quick links' on the Builder Origin page (https://bldr.habitat.sh/#/origins)
- Under 'quick links' on the Docs page(https://www.habitat.sh/docs/)

Mockup link will be added once the design is sorted out.

**Comment by ryankeairns** [comment]
Closing as duplicate. Tracking work in #3819
