### ISSUE TITLE
Squelch error output in studio when installing package from sandbox fails (but fallback to stable succeeds)

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3692]
Currently, when we build in Builder we set the HAB_BLDR_CHANNEL to prioritize picking packages from that channel.  If a package is not found there, we pick it up from stable instead.  This is normal, however the logging makes it appear that something bad happened.  Would be good to have more intelligent logging.

   kibana: Resolved build dependency 'core/coreutils' to /hab/pkgs/core/coreutils/8.25/20170513213226
» Installing core/gcc from channel 'bldr-824744994724225024'
∅ The package does not have any versions in the specified channel.
∅ Did you intend to install one of the folowing instead?
∅   core/gcc/5.2.0/20170513202244 in channel stable
∅   core/gcc/5.2.0/20170513202244 in channel unstable
✗✗✗
✗✗✗ Package not found
✗✗✗

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #52](https://github.com/habitat-sh/builder/issues/52) via [**ZenHub**](https://www.zenhub.com/)
