### ISSUE TITLE
More auth fixes for workers and the core team

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3699]
This is a multi-faceted issue, so I'll do my best to lay out all the pieces.

### Currently workers have no session
The original thinking behind this was that workers needed a _special_ kind of auth. They have the responsibility of building packages on behalf of others, so they have a need for a kind of "superuser" capability. This was solved for by making session values an `Option` in several places and users had a value of `Some(session_id)` and workers had a value of `None`. If the session was `None` then we skipped certain security checks, e.g. does this person have access to this origin?

The problem with this approach is that it breaks private packages. Right now when we go to fetch a package the logic is:  you can see this package if 1) it's public OR 2) it's hidden/private and you're a member of the origin that the package belongs to. Origin membership is checked using a person's session id (which is really their internal account id). Since workers don't have a session, they don't have an account id, and they can't retrieve private packages.

### All members of the core origin are treated like workers
[This snippet of code](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L57-L61) sets the session to None if the session in question has the `BUILD_WORKER` flag. It turns out that all members of the core team have the `BUILD_WORKER` flag set, which means that none of us have sessions assigned to us when we access certain API endpoints. One of those endpoints is promoting packages. So members of the core team can't promote private packages, while regular users can. This surfaced while I was working on https://github.com/habitat-sh/habitat/issues/3689 and discovered that I couldn't promote a private package, while @echohack could.

Adding to the complexity is the fact that we have two different ways of retrieving an optional session, because we were using it in two different ways. One is the snippet linked above, and the other [is here](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L386-L391). Both of these exist because they're required for the job they're doing, which is almost the same, but different enough that we needed two different functions. We need to consolidate this.

### How does this affect the Supervisor?
One thing that was brought up in the issue I linked above is what does the Supervisor do when it needs to download a private package? I haven't tried this myself, but the issue says that it's broken. We should think through how the Supervisor gets access to private packages that it needs to download.

So the take away here is we need a solution that meets all of the following needs:
* Workers can retrieve all packages, whether they're public, private, or hidden. It's possible that our visibility settings will expand in the future to include ones that aren't listed here. This solution should accommodate future expansion needs, and not need to be re-worked every time we add a new visibility setting.
* Members of the core team are not treated differently from other authenticated users when it comes to performing actions on private packages. They are checked for origin membership like everyone else and can see packages for whatever origins they belong to like everyone else. This likely means not identifying them as workers.
* Supervisors can download whatever packages they need to operate effectively without compromising the security of Builder or interfering with workers and regular authenticated users.

**Comment by chefsalim** [comment]
We should rip out the NoSession stuff that I had added - that's not the right strategy and was mostly a stop-gap.  If the build workers are going to keep using the public facing gateway, then we need to consider the worker privilege everywhere we are doing origin checks.

**Comment by echohack** [comment]
![cookie wow](https://i.imgur.com/WhjuDXU.gif)
