### ISSUE TITLE
Handle GitHub account renames

### ISSUE THREAD

**Issue by reset** [habitat-sh/habitat#3706]
If a user renames their GitHub account and then attempts to login they are unable to. We need to store a mapping of external IDs to internal account IDs on the SessionSrv which holds the session (keyed by external ID). This will allow us to route by account ID instead of by account name if a mapping is found ignoring what GitHub believes their account name is.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #53](https://github.com/habitat-sh/builder/issues/53) via [**ZenHub**](https://www.zenhub.com/)
