### ISSUE TITLE
Version of Habitat binary different in Linux studio than the one on the host

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#3712]
When I enter a studio on OS X through Docker, the version of the hab binary on my host is the same one that is in the dockerized studio. When I enter a studio in Linux, the studio downloads the latest supervisor from the builder depot which could lead to confusion or inconsistencies in my build.

I should have the ability to pin the version of the supervisor in the studio or have it match the one I have currently installed on my host.

**Comment by tduffield** [comment]
This is the case even when `HAB_STUDIO_BINARY` is set.

**Comment by fnichol** [comment]
I'll get us a fix here--sorry about this, it's for sure not what we intended.

**Comment by tduffield** [comment]
@fnichol So once this is implemented, if the latest version is `a.b.e`, and I'm running `a.b.c`, do I need to specify this environment variables in order to run a studio with `a.b.c` or is that now the default behavior?

**Comment by fnichol** [comment]
The new behavior should be that if you're running `a.b.c` of `core/hab`, then that would install you `a.b.c` version of `core/hab-studio` to run and that Studio would install `a.b.c` version of `core/hab-backline` (which contains, `core/bash`, `core/coreutils`, `core/hab/a.b.c`, etc.).

The environment variable wouldn't be something you'd normally want to use--only if you had `core/hab-studio/a.b.c` and needed to get a different version of the package set in the Studio, like `core/hab-backline/old.version`.

However, until we ship the next release, you could use `env HAB_BACKLINE_PKG=core/hab-studio/0.34.1 hab studio build .` to get a specific version of backline installed. Just note that this variable name will change on the next release as it was never documented publicly--my bad.
