### ISSUE TITLE
Google magic for "habitat packages" > bldr.habitat.sh/#/explore

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#3713]
![screenshot_20171010_222540](https://user-images.githubusercontent.com/6344099/31408909-5701f326-ae0a-11e7-824d-21df5524ccb7.png)

People, who want to see the package list do not see the wonderful Explore page. 
Can we do some Google magic, to increase this chance?

**Comment by eeyun** [comment]
Yes. This is an excellent find. We need to spend some time on our SEO to be certain! Thank you for opening this issue!

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #54](https://github.com/habitat-sh/builder/issues/54) via [**ZenHub**](https://www.zenhub.com/)
