### ISSUE TITLE
lingering origin invite

### ISSUE THREAD

**Issue by robbkidd** [habitat-sh/habitat#3727]
I was invited to an origin a while back (Spring? May-ish?). I'm pretty sure I accepted it at the time.

Today, I see that I am a member of the origin and can definitely do things an origin Member can (I added a key, I connected a GitHub repo to a packge). But I've got a lingering invite that I don't know what to do with:

![both a member and awaiting RSVP](https://user-images.githubusercontent.com/517302/31452389-c96470ac-ae7c-11e7-8de5-e6e09c5f383c.png)

Last week, I only saw the invite which would error if I attempted to accept. I could _not_ interact with the origin.

**Comment by scotthain** [comment]
Doesn't seem to have any ill effects for me but I'm also seeing this, with a similar situation to Robb here.

**Comment by rsertelon** [comment]
@robbkidd @scotthain Do you still see the lingering invite? I've dug up in the code a little, but cannot find reasons for it to be shown.

**Comment by robbkidd** [comment]
Yep. My origins list still appears as shown in the screenshot in this issue.

**Comment by rsertelon** [comment]
Can one of you invite me (temporarily of course) to one of your origins? So we can test that it will still happen or if your lingering invites are just quirks that would need a one-time database update :)

**Comment by scotthain** [comment]
I would 100% agree with this - we were very very early adopters (before there was a UX for accepting, IIRC) and this is likely just cruft if you can't replicate it.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #55](https://github.com/habitat-sh/builder/issues/55) via [**ZenHub**](https://www.zenhub.com/)
