### ISSUE TITLE
Want long search results 

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#3728]
Right now `hab pkg search` returns only 50 entries total, which makes getting/parsing my complete package list programmatically (via cli) impossible.

**Comment by rsertelon** [comment]
The API seems to limit results to 50 at most [by](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L77) [design](https://github.com/habitat-sh/habitat/blob/master/components/builder-http-gateway/src/http/helpers.rs#L141).

To get this feature we'd first need to allow more than 50 results at once.

**Comment by bixu** [comment]
Correct. Maybe there’s a performance reason for this, but I expect most CLI workflows to happily handle several thousand lines of output from a call.

Plus, if we *do* need a limit, showing the newest first would be nice :)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #56](https://github.com/habitat-sh/builder/issues/56) via [**ZenHub**](https://www.zenhub.com/)
