### ISSUE TITLE
hab-launcher is not reaping some children

### ISSUE THREAD

**Issue by dmajere** [habitat-sh/habitat#3729]
Habitat 0.36.

Here is a top example:
```
   698   657 hab      S    7272m 11.0   2  0.0 {beam.smp} /hab/pkgs/repo/app/mas
    8     1 root     S     884m  1.3  13  0.0 {hab-sup} /hab/pkgs/core/hab-sup/0
    1     0 root     S    49556  0.0   7  0.0 {hab-launch} /hab/pkgs/core/hab-la
  914   913 hab      S    19916  0.0   0  0.0 inet_gethost 4
  915   913 hab      S    19916  0.0   6  0.0 inet_gethost 4
  637     0 root     S    13616  0.0  13  0.0 {epmd} /hab/pkgs/repo/app/master/
  913   739 hab      S    13584  0.0   0  0.0 inet_gethost 4
  739   698 hab      S     4200  0.0  30  0.0 erl_child_setup 65536
  657   645 hab      S     1140  0.0   5  0.0 {app.sh} /bin/sh /hab/pkgs/repo/d
 1942  1357 root     R     1092  0.0  18  0.0 top
 1357     0 root     S     1084  0.0   7  0.0 sh
  645     1 hab      S     1080  0.0   0  0.0 {app} /bin/sh /hab/pkgs/repo/app
  751     1 hab      Z        0  0.0   5  0.0 [erl_child_setup]
 2430     1 hab      Z        0  0.0   5  0.0 [erl_child_setup]
  331     1 hab      Z        0  0.0   0  0.0 [erl_child_setup]
 5296     1 hab      Z        0  0.0   8  0.0 [erl_child_setup]
 1714     1 hab      Z        0  0.0  10  0.0 [erl_child_setup]
 4146     1 hab      Z        0  0.0   8  0.0 [erl_child_setup]
 5004     1 hab      Z        0  0.0  14  0.0 [erl_child_setup]
 3288     1 hab      Z        0  0.0  14  0.0 [erl_child_setup]
```

I believe that problem occur because of the health check implementation I am using.
My health check is basically `erl_node ping`, and erlang creates several additional processes when
it starts erlang node, and it starts additional erlang node to do ping.
So, this processes are not associated with any service, and probably because of that their pids are not getting into list here.
```
    fn reap_zombies(&mut self) {
        let mut dead: Vec<u32> = vec![];
        for service in self.0.values_mut() {
            match service.try_wait() {
```

**Comment by reset** [comment]
@dmajere actually I'm pretty sure this isn't your fault at all ;). This is a known issue on our short list of things to fix. It should just be a benign log spamming issue but it for sure is annoying!

Closing duplicate of #3406

**Comment by dmajere** [comment]
Well, its actually more than annoying, cause marathon is running health check periodically and we have to restart containers once in a while because they become swarmed with zombies.

**Comment by reset** [comment]
@dmajere sorry for the trouble, we'll get to it pretty soon. If you'd like to take a crack at fixing it before we're able to the issue is most likely an integer overflow
