### ISSUE TITLE
[RFC] Allow Custom Dockerfile to Docker Exporter

### ISSUE THREAD

**Issue by alexey-pankratyev** [habitat-sh/habitat#3751]
Meaning in the following - it is necessary to connect the Dockerfile  (in which additional steps are described and its own image is specified) while executing the command `hab pkg export docker`.
example:
         `hab pkg export docker --dockerfile /path/Dockerfile`

Here are a couple of advantages for what it's needed:
   1.) It is necessary to add several files to the root of the file system of the docker
   container when exporting ` hab pkg export docker `.  
   2.) The possibility of using custom image when executing the command `hab pkg export docker`.

**Comment by mwrock** [comment]
Closing now due to lack of discussion. Happu to reopen in the future!
