### ISSUE TITLE
Don't check in all sandbox channels when building software

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3755]
We currently implement build "sandboxing" using dedicated channels for each group of dependent builds in Builder. We apparently end up searching through all these channels to find packages, though, when we should really just be looking in the channel for the group we're in.

As we build more software, we'll get more of these channels, which will take longer to search through, adding unnecessarily to build times.

Thanks to @stevendanna for reporting this.

**Comment by stevendanna** [comment]
This is most noticeable when trying to install a package that doesn't exist anywhere, as it then iterates through all channels before failing.

**Comment by raskchanky** [comment]
Just to be explicit for whoever ends up picking this up, `hab pkg install` is what triggers this behavior.
