### ISSUE TITLE
Scaffolding option on hab plan init doesn't work

### ISSUE THREAD

**Issue by davidkazuhiro** [habitat-sh/habitat#3784]
I was following the [Build a Sample App](https://www.habitat.sh/tutorials/sample-app/mac/) tutorial and executed `hab plan init -s ruby` as written but got the following error.

```
$ hab plan init -s ruby
error: Found argument '-s' which wasn't expected, or isn't valid in this context

USAGE:
    hab plan init [FLAGS] [OPTIONS] [PKG_NAME]

```

The -s option isn't listed as a supported option in the --help output

```
$ hab plan init --help
hab-plan-init 
Generates common package specific configuration files. Executing without argument will create a `habitat` directory in your current folder for the plan. If `PKG_NAME` is specified it will create a folder
with that name. Environment variables (those starting with 'pkg_') that are set will be used in the generated plan

USAGE:
    hab plan init [FLAGS] [OPTIONS] [PKG_NAME]

FLAGS:
    -f, --nocallbacks    Do not include callback functions in template
    -h, --help           Prints help information
    -V, --version        Prints version information

OPTIONS:
    -o, --origin <ORIGIN>    Origin for the new app

ARGS:
    <PKG_NAME>    Name for the new app.
```

So I'm not sure whether this is a `hab plan init` but or a tutorial bug, but I am sure that I want to use the ruby scaffolding 😄 .

Here is the environment info:

### OS Version

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

### Debug/backtrace

```
$ RUST_LOG=debug RUST_BACKTRACE=1 hab plan init -s ruby
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "plan", "init", "-s", "ruby"]
DEBUG:hab: remaining cli args: []
error: Found argument '-s' which wasn't expected, or isn't valid in this context

USAGE:
    hab plan init [FLAGS] [OPTIONS] [PKG_NAME]

For more information try --help
```

### Current Habitat environment variables
None set
```
$ env | grep HAB | grep -v HAB_AUTH_TOKEN
$
```

**Comment by fnichol** [comment]
Hi there!

I'm noticing that in the error message there was an older flag (namely, `--nocallbacks`) which is making me wonder if this is an older version of the hab CLI. Could you double check the version? You can run:

```sh
> hab --version
```

If it turns out that you have an older version, it would be most ideal to try the latest version (which right now is 0.36.0). If I'm wrong here, then we can check some other things, but I'm hopeful that this is what's going on.

Thanks!

**Comment by eeyun** [comment]
Yeah that's definitely going to be a previous version. We've since rebuilt all of those subcommands which is what the tutorial references!

**Comment by eeyun** [comment]
Closing this for now, if this issue persists please leave a new comment and we'll reopen.

**Comment by davidkazuhiro** [comment]
Doh! I'd updated hab in /Applications but my PATH was loading from /usr/local/bin which was from back in April. Thanks everyone and sorry for the time wastage.
