### ISSUE TITLE
Un-sharded services (eg, job server) should be able to route properly

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3787]
Currently, an unsharded service that sets it's 'shards' config to an empty list is unable to properly route messages. Need a proper solution so we don't have to iterate through 128 shards when only a single shard exists.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #61](https://github.com/habitat-sh/builder/issues/61) via [**ZenHub**](https://www.zenhub.com/)
