### ISSUE TITLE
Confusing My Origins UX when auth scope has changed

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#3788]
Web-related.

If you've been signed in for a while, and click on "My Origins" from Builder interface https://bldr.habitat.sh/#/pkgs/core the browser is redirected to www.habitat.sh and no user feedback is provided.

As a debug step, I signed out, and signing back in prompted for another GitHub auth scope - after which everything worked ok.

**Comment by cnunciato** [comment]
This behavior no longer exists. If your session expires while you've got Builder open in a browser, and you click My Origins, you'll be directed to sign in again, get a message about your session having expired, and once you do sign in, you'll be redirected to My Origins (or whatever page you'd requested before being prompted to sign in again).
