### ISSUE TITLE
[Builder UI] Add unique identifiers to buttons

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3792]
As a Habitat team member, 
I would like to capture data that helps me determine where users tend to get stuck
so that I can improve the experience of getting started with Habitat.

With analytics tools, we can track key events to find both challenging flows that make it difficult for users to see immediate value from Habitat. In order to target specific events, it would be helpful if buttons were uniquely identifiable through and `id` parameter and/or unique class name.

Currently, several buttons do not use either which makes them difficult to discern from one another in our data analysis.

- [ ] Add a unique `id` or `class` parameter to all buttons in the Builder UI

List of buttons:
- Sign in with Github
- Connect a plan
- Next (to step 2 of connect a plan file)
- Save connection
- Create an origin
- Generate key pair
- Add Docker Hub account
- Build latest version
- Send invitation

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #62](https://github.com/habitat-sh/builder/issues/62) via [**ZenHub**](https://www.zenhub.com/)
