### ISSUE TITLE
[Builder UI] Notify me when my packages have been recently rebuilt

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3798]
For *automated rebuilds* of packages connected to Habitat Builder:
As a user, I want to know when my package has been rebuilt by Builder
so that I can test and deploy the updated package.

For *non-connected builds* where your deps have changed and you should rebuild rebuild:
See #2185 

---------
Currently, I would have to manually/periodically check the UI to determine if there are new versions of packages (or deps of my package) available. It would be nice if, as soon as my package is rebuilt, I receive/see a notification (email also?) letting me know that it was rebuilt and why it was rebuilt (e.g. "Fix for CVE"). 

If my package (plan file) is not connected to Habitat Builder, then I receive/see a notification when one of my package deps has been updated; instructing me to rebuild my package.

**Comment by ryankeairns** [comment]
@cnunciato feel free to add more details; just added enough so that we don't lose track.

**Comment by rsertelon** [comment]
Maybe a reason for builds could be nice too (in the builds tab for a package)? 

For example knowing if build was started by a member of the organization, or following a commit, or even automagically by builder services because of dependency update.

**Comment by reset** [comment]
@ryankeairns yesterday @christophermaier, @fnichol and I had a brainstorming session about some things we'd find useful in this feature. Specifically we think it would be really useful if there was a "commit message" when promoting builds from unstable to stable and we think that the action of promotion is what should kick off builds in other origins. If we were to do this, you could submit a message like "Fix for CVE <X>" or include the entire changelog of a software's release in your promotion message. This could be a really neat way to surface release notes :)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #63](https://github.com/habitat-sh/builder/issues/63) via [**ZenHub**](https://www.zenhub.com/)
