### ISSUE TITLE
Builder should know about Composite Packages

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3801]
Builder should be able to rebuild a composite package when the services that it is built from are themselves rebuilt.

These builds will be quick, and will ensure that composites remain internally consistent as each component service evolves. Right now, a failure to build a composite will generally indicate that the binding contract between services has changed (e.g., a bind requires an additional exported value, a service exports fewer values, a service changes the name of an export, etc.), requiring the composite itself to be updated accordingly.

This will mean incorporating the contents of a composite's `SERVICES` metadata file into the overall dependency graph

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #64](https://github.com/habitat-sh/builder/issues/64) via [**ZenHub**](https://www.zenhub.com/)
