### ISSUE TITLE
[Builder UI] Display Composite Packages

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3802]
When displaying a composite package in the Builder UI now, we don't display composite-relevant information. Dependencies and transitive dependencies, while relevant to "standalone" packages, are not meaningful for composite packages. Instead, we should display the services that are members of the composite, as well as the exact releases that were resolved in the creation of the composite (i.e., the contents of the `SERVICES` and `RESOLVED_SERVICES` metadata files).

Additionally, some kind of prominent indicator that this is a composite package would be nice (which probably means displaying the contents of the `TYPE` metadata file, defaulting to "standalone" if it does not exist).

This will likely require #3801 first, as well as potential API updates.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #65](https://github.com/habitat-sh/builder/issues/65) via [**ZenHub**](https://www.zenhub.com/)
