### ISSUE TITLE
Templating and Bind/Export documentation example should show uses of #each's @first and @last

### ISSUE THREAD

**Issue by burtlo** [habitat-sh/habitat#3805]
When templatizing configuration that iterates over a collection it becomes important to know how to optionally include delimiters with `@last`.

```
server {
    enabled = true
    # Nodes to expect before bootstrapping cluster
    bootstrap_expect = {{cfg.nomad.bootstrap_expect}}
    retry_join = [{{#eachAlive bind.servers.members as |member|}}"{{member.sys.ip}}"{{#unless @last}}, {{/unless}} {{/eachAlive}}]
    retry_interval = "30s"
    retry_max = 0 
}
```

In the above example the ip addresses of the alive members returned by the `servers` binding is comma-separated. The logic check `{{#unless @last}}, {{/unless}}` at the end ensures that the comma is written after each element except the last element.

When configuration only expects a single entry for a member, like a single database source, it is useful to use `@first`.

```json
{
  "mongo": {
    {{~#eachAlive bind.database.members as |member|}}
      {{#if @first}}
      "host" : "{{member.sys.ip}}",
      "port"   : "{{member.cfg.port}}"
      {{/if}}
    {{~/eachAlive}}
    }
}
```

In the above example there is only one mongo database within the service group bound to this `database binding. JSON data does not support repetition of the same keys so allowing multiple entries would cause the application to fail to launch. This solution above opts to select the first member in the collection. It could have also been the last member.

**Comment by burtlo** [comment]
@davidwrede this one's for you!

**Comment by davidwrede** [comment]
Thanks @burtlo!
