### ISSUE TITLE
Homebrew download instructions don't show up

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3817]
This was intended to be added with #3700, but the downloads page doesn't display it. Digging into the code, it appears that our download page isn't using this partial: https://github.com/habitat-sh/habitat/blob/8a010141136561532d6fa4de42a0c0d03a110912/www/source/tutorials/download/index.html.slim#L21-L33

**Comment by mwrock** [comment]
The same applies to the chocolatey instructions.
