### ISSUE TITLE
`hab pkg path <ident>` against a plan with dynamic `pkg_version()` fails

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/habitat#3832]
When a user runs `hab pkg path <ident> against a plan with dynamic `pkg_version()', habitat is unable to return the path.  Looking deep, when a plan uses the `pkg_version() { }` option to generate dynamic version, the plan will generate the following directories:

```
/hab/pkgs/myorigin/mypackage
|- 0.1.0
|- __pkg__version__unset__
```

Also looking at the debug trace:
```
[47][default:/src:0]# RUST_LOG=debug RUST_BACKTRACE=1 hab pkg path myorigin/mypackage
DEBUG:habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG:habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): false }
DEBUG:habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG:hab: clap cli args: ["hab", "pkg", "path", "myorigin/mypackage"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_core::package::ident: Comparing non-numeric versions: __pkg__version__unset__ __pkg__version__unset__
DEBUG:habitat_core::package::ident: Comparing non-numeric versions: __pkg__version__unset__ 0.1.0
DEBUG:habitat_core::package::ident: Comparing non-numeric versions: __pkg__version__unset__ 0.1.0
✗✗✗
✗✗✗ Couldn't read MetaFile: TARGET, not found
✗✗✗
```

Possible solution is to ignore any directories with the name: `__pkg__version__unset__`.

**Comment by bdangit** [comment]
Looking through the code, the fix is somewhere in here.  https://github.com/habitat-sh/habitat/blob/master/components/core/src/package/ident.rs  Sorry my rust is pretty bad, So I can't exactly pinpoint exactly where to do this exclusion just yet.

Any pointers?

**Comment by eeyun** [comment]
@bdangit this is a great find! I'm marking this as an accepted bug for now and after our triage livestream i'll get back to you with some possibilities on resolving this issue! Thanks for being awesome!

**Comment by fnichol** [comment]
I bet this is a new bug. Chances are that if you had a plan that defined `pkg_version() { …; }` but you didn't call `update_pkg_version` (to fire the `pkg_version()` function and recompute things), then I bet we don't check for `[[ "$pkg_version" == "__pkg__version__unset__" ]]` at the right moment.

@bdangit, is it possible that a call to `update_pkg_version` is missing in the Plan?

In any case, we should be able to catch this and fail the build.

**Comment by tduffield** [comment]
I'm seeing this too, with this plan.sh: https://github.com/chef/ci-studio-common/blob/master/habitat/plan.sh.

**Comment by bdangit** [comment]
I unfortunately don't have my plan on public display.  However, I did something similiar to @tduffield: https://github.com/chef/ci-studio-common/blob/master/habitat/plan.sh#L9-L16
