### ISSUE TITLE
Website footer links are blocked when the viewport width is between 640px and 1020px 

### ISSUE THREAD

**Issue by burtlo** [habitat-sh/habitat#3843]
Essentially some element is getting bumped down and is laying over some of the links in the footer.
![image](https://user-images.githubusercontent.com/244426/31808252-ee90d5d4-b537-11e7-9e7a-2c2915471b53.png)

**Comment by eeyun** [comment]
Ok Definitely seeing this when I get my window size small enough. Thank you for the report @burtlo !
