### ISSUE TITLE
License Copyright in Readme doesn't match License File.

### ISSUE THREAD

**Issue by tomgco** [habitat-sh/habitat#3854]
Hello!

I am currently watching a member of your team demo Habitat at All Systems Go in Berlin. (It looks great!)

The Readme currently says that the License Copyright is for "Chef Software Inc" 2016 which mismatches with the License file. (Which still has the placeholder text of `Copyright  [yyyy] [name of copyright message]`).

I am not sure what these should be so I thought I should raise this issue!

Keep up the great work, and I look forward to having a play with Habitat in the near future!

**Comment by fnichol** [comment]
Hi @tomgco,

Thanks, speaking for myself, that was a great conference! I took a second look at our [LICENSE](https://github.com/habitat-sh/habitat/blob/master/LICENSE) and saw that the section at the end explains how to apply the Apache license to source code files. This looks to be in line with the [instructions](https://choosealicense.com/licenses/apache-2.0/) for applying the license to a project.

I'm going to close this out, but if I've misunderstood, please feel free to reopen.

Let us know when you start looking at Habitat!
