### ISSUE TITLE
Provide UI feedback when build requests fail

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#3856]
Currently, when clicking the Build button, the UI confirms the request was submitted even when submissions fail (e.g., on server error, conflict, etc.). We should indicate to the user that the request didn't succeed and provide a suggestion for what might be done about it. /cc @ryankeairns

**Comment by ryankeairns** [comment]
I'm presuming this would be a quick/temporary message... there are 3 UI elements that come to mind: 1) use a banner message like we do when builds are processing, 2) display a form validation style error below the build button, or 3) use our toast messaging.

When a build is successful, we display the 'processing' banner message. Perhaps we just show an 'error' (red) banner message when this occurs? That is a temporary message, so I'm also wondering if this failure event would also return any build output? or does it error before that generates?

**Comment by cnunciato** [comment]
@ryankeairns Yeah, we'd know about this immediately on click of the button; the API we call on that button click is what's returning the error. 

So in that sense, the toast message is probably be the most suitable place for it, since that's where we're (erroneously) displaying the "submitted successfully" message. We could easily display an error notification message here, and even keep it in view until the user dismisses it. (The other two options would be trickier in that they're used for specific purposes -- responding to currently running builds or a specific build log, neither of which we'll have in this case, since no job will have been submitted.)

**Comment by ryankeairns** [comment]
Ok, understood. I suspected there might be some hidden complexity here, so let's roll with the toast message and if we can make it dismissible that would be a nice-to-have.

Appreciate the explanation.
