### ISSUE TITLE
want formatted output for `hab svc status`

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#3859]
The current view is not pretty-printed (aligned into columns), which means that for more than 3 or so listed services the output becomes increasingly hard to read.

**Comment by eeyun** [comment]
Yessss. I think this is a dope feature add. Every time i'm running a bunch of services under a single supervisor it gets untenable to dissect which messages come from where (especially in the case where i'm running more than one instance of a specific service, e.g. like 3 postgresql nodes). Thanks for opening this issue!

**Comment by rsertelon** [comment]
A little workaround is to use `hab svc status | column -t -s ','`.

To do it in rust does not seem that simple (you warned with the  `E-less-easy` label :)).

**Comment by rsertelon** [comment]
I've found a create that might help with our problem https://crates.io/crates/tabwriter

Do you think I can add it to `Cargo.toml` and try to fix this issue?

**Comment by nellshamrell** [comment]
@rsertelon go for it!  Let us know how it goes and if you want some more input!

**Comment by rsertelon** [comment]
Went quite well actually ;)

**Comment by bixu** [comment]
🎉

**Comment by smartb-pair** [comment]
@rsertelon, looks great!
