### ISSUE TITLE
Post-login should take you back to your previous page

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#3882]
As a user of Builder who has previously been authenticated, when I'm on a package page and login again, I should be taken back to that page after logging in. At least, that's what I've been expecting 😉

**Comment by eeyun** [comment]
Yes please. I've hit this a bunch of times myself.

**Comment by cnunciato** [comment]
I am removing the `easy` label because this is actually not at all easy. ;) (I also wonder whether even having an "easy" label is appropriate, because how do we ever how easy something will be until we look at it, right? But I digress.)

**Comment by raskchanky** [comment]
I think all the difficulty labels should be removed. They’re completely subjective and don’t feel useful. What’s easy to someone else might not be easy to me, etc.

**Comment by reset** [comment]
The labels are definitely subjective and that's where they can fail us for sure. I think in general they're useful to communicate to people new to the project if the issue they're looking at is something they should be thinking of to pick up.

Using these labels to communicate difficulty between each other is more of a t-shirt sizing thing. You should feel free at anytime to change the difficulty once you've analyzed the work. This is how I've been taking the labels to mean at least ;)

**Comment by raskchanky** [comment]
@reset Thanks for clarifying the intended use case 👍
