### ISSUE TITLE
 .bldr.toml documentation is  un-searchable

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#3883]
If we have documentation of the .bldr.toml and how it works/it's purpose it doesnt exist in the documentation (or can't be found via search). 

While this won't be a super common requirement, it would be good for us to have documentation of  these things if only for other core plans contributors/maintainers.

**Comment by tashimi** [comment]
@eeyun this is addressed by #3616 but perhaps there is a typo in the sidebar code that is making it not appear?

**Comment by tashimi** [comment]
Nope, it's there: https://www.habitat.sh/docs/developing-packages/#multiple-plans-builder

**Comment by eeyun** [comment]
Updated description and re-opened ticket. bldr.toml does not currently return the bldr.toml documentation. Will close back out once I've corrected the search around this.
