### ISSUE TITLE
Update Segment tag.

### ISSUE THREAD

**Issue by hamburglar** [habitat-sh/habitat#3887]
Please update the current Segment snippet for www and the builder web app with the attached version.
[habitat-segment-chef-key.txt](https://github.com/habitat-sh/habitat/files/1412089/habitat-segment-chef-key.txt)

**Comment by cnunciato** [comment]
@hamburglar This script assumes `jQuery` is available, which is okay for www, but not for Builder. (We don't bundle jQuery there.) Does Segment offer a non-jQuery version of this? The previous one looks like plain ol' JS.

**Comment by cnunciato** [comment]
@hamburglar When I run this locally, as we do in development (localhost:4567), I get a 200  response from `api.kickfire.com`, but the payload is:

```
"URL Not Authorized"
```

... which causes the script to fail. 

```
Cannot use 'in' operator to search for 'data' in URL Not Authorized
```

Is there a whitelist of URLs somewhere that we need to add our sites to (e.g., local dev, acceptance, prod for both www and builder)?

**Comment by hamburglar** [comment]
@cnunciato There is a whitelist that Kickfire manages. We don't want to whitelist localhost, but I can make sure that acceptance is whitelisted. What domain or domains do you want whitelisted for acceptance?

**Comment by cnunciato** [comment]
@hamburglar Ok cool, thanks. For acceptance, I think we'd just need 

* https://www.acceptance.habitat.sh
* https://bldr.acceptance.habitat.sh

Still, it'd be good to whitelist localhost as well, so we're able to test these scripts before merging them. Is that just not possible?

**Comment by elliott-davis** [comment]
@hamburglar I'm closing this for now. Please re-open if it's still an issue.
