### ISSUE TITLE
Broken formatting at habitat.sh

### ISSUE THREAD

**Issue by alex-bender** [habitat-sh/habitat#3888]
Broken formatting at https://www.habitat.sh/docs/best-practices/#quickstart-guide
Installation section, missed `[` here
`ses on github](https://github.com/habitat-sh/habitat/releases).`

Update:
the same page, seems that this line is not complete:
`How does the package integrate into their`, section `Readme`

Section `Override The Build Phases You Don't Need`
`{: .language-shell}`

**Update**:
page https://www.habitat.sh/docs/best-practices/#quickstart-guide
Section `Override The Build Phases You Don't Need`

**Update**:
page: https://www.habitat.sh/docs/reference/#environment-variables
at the `pkg_description` variable:
`{::comment}` and `{:/comment}`

**Comment by eeyun** [comment]
Good catch, thank you for opening this issue!

**Comment by alex-bender** [comment]
Is it ok to post it here or it's better to write to slack?

**Comment by tashimi** [comment]
@alex-bender posting here is perfect! it gives us an issue to track that doesn't get lost in chat in the Slack scroll. Thank you!

**Comment by rsertelon** [comment]
@eeyun @tashimi 

As I told Ian on slack, I'm fixing these issues and disabling the quick start guide for now.

However, I don't understand the `{::comment}` thing. Is it a artefact of some older templating stuff? I don't see what it should do in markdown.

**Comment by tashimi** [comment]
@rsertelon yeah we have some older flavors of markdown hanging out. If you open a PR for your updates in the main habitat repo I can deploy it to acceptance and make sure everything renders nicely.

**Comment by rsertelon** [comment]
Will do then :)

**Comment by rsertelon** [comment]
@tashimi this is done :)

**Comment by tashimi** [comment]
Closing in favor of #3975
