### ISSUE TITLE
hab sup run fails if old LOCK file present

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/habitat#3897]
> OS: GNU/Linux CentOS7

We use `hab sup run` (via systemd) to start a supervisor on our EC2 instances and then load services into it.

When our instances shutdown (I don't exactly know how they do shutdown - hard, soft, other? - , but it's every day, automatically, to save money) habitat does not seem able to clear the LOCK file. So when the server comes back up, systemd is not able to start the supervisor and the service is not available.

We mitigated this issue with a nice `ExecStartPre=-rm -f /hab/sup/default/LOCK`. :weary: 

I think it might be interesting if `hab sup run` was able to remove (or override) the LOCK file if the pid in it does not exist. What do you think?

**Comment by christophermaier** [comment]
Related: #3865

**Comment by rsertelon** [comment]
Oops, yes it's the same. Sorry I was mislead by the studio context.

**Comment by eeyun** [comment]
Closing in favor of #3865 if there's something else not covered in that issue feel free to re-open and redraft this ticket!
