### ISSUE TITLE
[www] [Builder UI] Add additional footer links

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#3909]
As a user of Habitat,
I would like to have readily accessible information about the project
so that I am aware of policies and can contribute accordingly.

-----------
Add the following links to **both the website and web app** footers:

- [x] Add '[Security](https://github.com/habitat-sh/habitat/blob/master/CONTRIBUTING.md#report-a-security-vulnerability)' link under About Habitat
- [x] Add '[Contributing](https://github.com/habitat-sh/habitat/blob/master/CONTRIBUTING.md#contributing-to-habitat)' link under Legal 
- [x] Add '[Code of Conduct](https://github.com/habitat-sh/habitat/blob/master/CODE_OF_CONDUCT.md)' link under Legal 
- [x] Add '[Cookie Policy](https://www.chef.io/cookie-policy/)' link under Legal

**Comment by ryankeairns** [comment]
@apriofrost Can you add a mockup for this? I think the only tricky part will be the number of links added to the Legal section, which is a row at the very bottom of the footer currently... i.e. I think this will cause the current layout of links to wrap.

**Comment by cnunciato** [comment]
And now I see this note was already added. 🥇

**Comment by cnunciato** [comment]
@ryankeairns They don't wrap until 1100 pixels or so, so at normal desktop resolution it's all good, and on mobile it seems all right also.
