### ISSUE TITLE
List of origin packages should be sorted alphabetically

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#3916]
https://bldr.habitat.sh/#/origins/core/packages

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1V2d36421Y0p2l1H010p/Screen%20Recording%202017-10-26%20at%2011.16%20AM.gif?X-CloudApp-Visitor-Id=510591d6d7bb38844a0ab9ff118b28a4&v=5bfd8620)

**Comment by raskchanky** [comment]
I could've sworn that once upon a time, the server was returning packages pre-sorted.  I'm guessing this is a regression in the API.

**Comment by rsertelon** [comment]
This is a bit odd indeed. I've tried to locate the problem for this issue in builder api, with no much luck. I can confirm that the endpoint does return packages unsorted although they seem to be retrieved sorted:

https://github.com/habitat-sh/habitat/blob/master/components/builder-originsrv/src/data_store.rs#L1199

pg function is defined in a migration here: https://github.com/habitat-sh/habitat/blob/master/components/builder-originsrv/src/migrations/origin_packages.rs#L616

The pg function should return sorted results. Order might be lost in transit between the originsrv and the http gateway, I can't tell more :) Hope this little investigation will help.

**Comment by cnunciato** [comment]
It looks like packages are sorted properly, but projects (i.e., "Connected Plans") are not.
