### ISSUE TITLE
Building devshell is broken

### ISSUE THREAD

**Issue by bodymindarts** [habitat-sh/habitat#3924]
When trying to build the [devshell docker-image](https://github.com/habitat-sh/habitat/blob/master/Dockerfile) from scratch it fails when [installing docker](https://github.com/habitat-sh/habitat/blob/master/support/linux/install_dev_9_linux.sh#L19) with the following message:

```
#   curl -sSL https://get.docker.io | sudo -E sh

# Executing docker install script, commit: 49ee7c1

Either your platform is not easily detectable or is not supported by this
installer script.
Please visit the following URL for more detailed installation instructions:

https://docs.docker.com/engine/installation/

```

**Comment by christophermaier** [comment]
Closing since the local development setup process has changed drastically since this was filed.
