### ISSUE TITLE
attach shows a not working prompt when hab pkg build is called

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/habitat#3943]
This is with `hab 0.38.0/20171026215954`.

When there's a `attach` inside the `plan.sh` and we run the `hab pkg build .` command, the build effectively stops at the `attach` line, but the prompt shown does not work.

If it is not intended to work outside of an interactive studio, it might be good to ignore it, or print a warning during the build.

**Comment by eeyun** [comment]
Oh gosh, I hadn't seen this behavior before. Great catch. I'm guessing that as we drill into the studio as a first class development environment that this is behavior that more users will definitely expect (including myself). Thank you for submitting this issue!
