### ISSUE TITLE
`hab start <svcname>` inside Studio starts _all_ previously-started services

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#3950]
I have a composite plan that I've used to start 2 services.

If I stop the composite, then start only one of the 2 sub-services, both will start anyway (I think the Supervisor is always starting every service it knows about). I feel that this behavior is surprising in the bad kind of way.

**Comment by christophermaier** [comment]
Closing since the 0.56.0 release allows finer-grained service control. 

Please re-open if problems persist.
