### ISSUE TITLE
attempting to update/save configs for private packages origin yields 409 error

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#3951]
See screenshot attached. I've tried several times to reconfigure or remove/re-add the Habitat GitHub app and haven't seen any improvement.
![screen shot 2017-10-28 at 10 59 36 pm](https://user-images.githubusercontent.com/339799/32138487-e08279a4-bc33-11e7-839f-6612b3885745.png)

**Comment by cnunciato** [comment]
This appears to be secondary to non-core builds being disabled.

**Comment by eeyun** [comment]
Yeah it looks like this is a side effect of the current builder stuff thats being worked. You can check that out here https://status.habitat.sh/ and we'll update as the status changes! Thanks for the report!

**Comment by tashimi** [comment]
@bixu This issue should now be resolved, please let us know if you have any issues!
