### ISSUE TITLE
hab bldr job status

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#3959]
This is a sub-task of https://github.com/habitat-sh/habitat/issues/2686

Work includes:
- [x] hab CLI command
- [x] status API

**Comment by eeyun** [comment]
Per our conversation in Slack:

For coverage of the corner case where a job gets "stuck" in process it might be good to have this command return the project status and a timestamp maybe sort of providing the same outcome as the process we're doing here https://github.com/habitat-sh/habitat/wiki/Checking-for-stuck-Builder-builds-%5BDebugging%5D?
