### ISSUE TITLE
Add note on using the correct path for cfg keys with #each helper

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#3965]
When using the handlebars block helper `#each`, you need to reference the parent context to use any user-defined configuration values.

From the handlebars.js site:

> The exact value that `../` will resolve to varies based on the helper that is calling the block. Using `../` is only necessary when context changes, so children of helpers such as `each` would require the use of `../` while children of helpers such as `if` do not.

**Comment by rsertelon** [comment]
@davidwrede didn't you fix this with #4092 ? :)

**Comment by davidwrede** [comment]
Yup. I'll close this issue out.
