### ISSUE TITLE
Navigating to a package which doesn't exist should ideally show the 404 page.

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#3966]
As a user of Builder, if I navigate to a package which doesn't exist, I'd expect to see some kind of 404 page rather than a page with partial package data.

For context I was trying to track down a build of `core/scaffolding-go` by incorrectly editing the URL and visiting the page for `core/go-scaffolding` (which doesn't exist). Seeing a quick and clear "this package does not exist" would have helped!

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #68](https://github.com/habitat-sh/builder/issues/68) via [**ZenHub**](https://www.zenhub.com/)
