### ISSUE TITLE
Allow packages to define runtime environment variables

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#3978]
In some cases, it can be advantageous to allow packages to define environment variables that can be used to construct a runtime environment for a service. One example of this could be a dependency that creates Python libraries which need to be in the `PYTHONPATH` of a consuming service. By allowing packages to set this information, we can automatically compose a suitable runtime environment on behalf of a user (similar to what we do to generate a `PATH` that points to all the binaries a service depends on), which will simplify service hooks and unlock new usage patterns. 

This can be seen as an extension / refinement of ideas presented in:
  - https://forums.habitat.sh/t/allow-env-vars-to-be-passed-from-plan-to-runtime/264/6
  - https://github.com/habitat-sh/habitat/issues/949
  - https://github.com/habitat-sh/habitat/issues/1579
  - https://github.com/habitat-sh/habitat/pull/1830

cc: @georgemarshall @bixu

**Comment by georgemarshall** [comment]
Also https://github.com/habitat-sh/habitat/pull/3171

**Comment by christophermaier** [comment]
Closed by #4067
