### ISSUE TITLE
Saving plan connection fails

### ISSUE THREAD

**Issue by schu** [habitat-sh/habitat#3995]
Hello,

I'm trying to follow the Habitat tutorial at https://www.habitat.sh/tutorials/sample-app/ and got stuck at https://www.habitat.sh/tutorials/sample-app/linux/build-package/ "Connect a plan to Builder".

When I try to save the plan (button "Save Connection" in the package settings tab), I get an error message "Failed to save plan connection" in the bottom right. The console shows two errors:

```
app-326b2a2d1855d9610a04809feecc934d944cb71d47480327aef509574f06c76e.js:57 POST https://bldr.habitat.sh/v1/projects 409 ()
app-326b2a2d1855d9610a04809feecc934d944cb71d47480327aef509574f06c76e.js:307 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'origin_name' of undefined
   ...
```

The Habitat Builder is installed (only) for the selected repository. I see a green checkmark, i.e. the builder appears to find the `habitat/plan.sh` file.

I'm using a brand-new account created today (username schu).

Happy to provide more information if necessary. Thanks!

**Comment by tashimi** [comment]
Hi @schu - I believe the issue you were experiencing should be resolved. Could you give it another try and let me know if you run into it again? 

Thanks!

**Comment by schu** [comment]
@tashimi - thank you! I can now see the connected plans for the previously created packages (which were not visible and returned 409 before) as well as create new plan connections.

**Comment by VickyWinner** [comment]
@tashimi - I am getting the same error while connecting plan file to habitat builder".  How does the issues gets resolved?
failed to save plan connection.
