### ISSUE TITLE
Add job cancelation ability to the UI

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#3998]
Now that we have an API (as well as hab cli cancel command), we should hook up the same functionality as part of the UI.

### UI Prototype
[Job cancel UI Mockup](https://chef.invisionapp.com/share/AREOTA4KQ#/266390910_package_Detail_V2_-_Versions_ALT_Job_Cancel)

#### Notes for prototoype
- the cancel icon tip should show on hover, as it does on the BUILD JOBS screen
- due to a limitation with Invision, you can only view the modal confirmation mockup from the job detail screen. Click on the cancel icon to see the tip (this should be a hover, but it wouldn't work on Invision), then click on it again to display the modal. 
- As of now, you can only 'Close' the dialog and not confirm the delete. I'm waiting on some feedback with regards to what exactly happens to a cancelled job and what data about that job will exist.

**Comment by cnunciato** [comment]
cc @ryankeairns

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #69](https://github.com/habitat-sh/builder/issues/69) via [**ZenHub**](https://www.zenhub.com/)
