### ISSUE TITLE
Node-scaffolding blog post bugs & tweaks

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#4011]
Walked through the latest demo blog post and found a number of issues, for example:
- typos in demo code
- a few extra steps and errors for those not already set up
- 404 in the completed example

Going to polish those up as @nellshamrell is on PTO this week.

**Comment by nellshamrell** [comment]
Thank you!

**Comment by nellshamrell** [comment]
Is there more to be done on this?
