### ISSUE TITLE
Expose more Builder activity in user-facing build logs

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4018]
We currently expose the actual contents of the Studio build in logs, as well as subsequent Docker image creation. We don't expose details of package upload, though (and there may be other stages of the process that are currently "silent"). If there is ever an issue in such a "silent" stage, it can be difficult to diagnose, or to even realize there is an issue.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #72](https://github.com/habitat-sh/builder/issues/72) via [**ZenHub**](https://www.zenhub.com/)
