### ISSUE TITLE
Revisit log streaming

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4030]
In its initial incarnation, log streaming for Builder jobs was a simple affair. We took standard output from the job and streamed it back to the user, while also collecting the output in a log file for long-term storage. We also collected standard error, but only after standard output was read, which resulted in the following issue and its temporary fix:

https://github.com/habitat-sh/habitat/issues/4027
https://github.com/habitat-sh/habitat/pull/4029

When we added Docker exports, we piggybacked on the same infrastructure to append Docker image generation output to the same log file. (Our standard error output was also initially appended to the same log file; with the fix above it is now interleaved with standard output).

As we add more export types, this situation will compound itself, and will eventually result in a poorer user experience. It seems that at a conceptual level, we'd like to track the output and error streams of each of the sources (initial package build, subsequent export builds, etc.) as their own distinct entity, rather than just dumping them all into one file and telling the user to sift through it on their own.

This will require some changes to the current log forwarding system to allow for both stdout and stderr streams to be consumed simultaneously (perhaps with multiple threads, or with some of the newer async Rust libraries that are showing up), allowing those streams to remain distinct as they travel through the rest of the system, updating the API to deal with multiple log sources, and revisiting the UI and UX around interacting with the log streams.

These are just initial thoughts, and all this needs further discussion; this issue is just tracking the overall idea.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #73](https://github.com/habitat-sh/builder/issues/73) via [**ZenHub**](https://www.zenhub.com/)
