### ISSUE TITLE
API for notifications

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4036]
We would like to notify Habitat users when packages in their origin (or dependencies of packages in their origin) have been updated. **This would apply to all non-core origins.**

The initial set of notifications that we're targeting is as follows:

📣  Notify members of an origin when an artifact is promoted to unstable
📣  Notify members of an origin when an artifact is promoted to stable
📣  Notify members of an origin when a dependency of my package is promoted to stable

For each message, we would like to display the following information:
1. Notification title (e.g. [pkg name] was promoted to stable [x] minutes ago)
2. Reason/Type (e.g. dependency rebuild, manual request, uploaded, GitHub webhook)
3. Message, if applicable (e.g. job message (if provided), git commit message)

Additionally, individual origin members should be able to mark notifications as read. They can do this on 3 levels:
1. an individual notification
2. all notifications for a given origin
3. all notifications for all their origins

To-do:
- [x] Create issue for API changes to support channel promotion - #4038 
- [x] Create issue for adding 'promote to stable' feature in UI
- [ ] Create related issue for adding messages to Builder job/scheduler requests
- [x] Create related issue for the entire UI side of this Notifications feature - #3798 

Mockups:
[Web UI Notifications screens](https://chef.invisionapp.com/share/C5E6NIURX#/262349769_package_Detail_-_Build_Jobs)

**Comment by raskchanky** [comment]
Putting @cnunciato's gist here because it's relevant and I keep losing track of it.

https://gist.github.com/cnunciato/e9e9db16e50803326c68014e809c66f5

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #74](https://github.com/habitat-sh/builder/issues/74) via [**ZenHub**](https://www.zenhub.com/)
