### ISSUE TITLE
API for channel promotion in the UI

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4038]
Currently, the only means of promoting .harts from unstable to stable is via the CLI tool.
The API changes tied to this card would support a new Builder UI feature where users can click a link/button and promote an artifact from unstable to stable.

This should essentially bring the CLI `hab pkg promote` functionality (of a single artifact) to the UI, where the PKG_IDENT is the  one from which you click the promote button and the CHANNEL is **stable**. -> https://www.habitat.sh/docs/habitat-cli/#hab-pkg-promote 

A separate issue will be created for the UI portion of this feature.

**Comment by raskchanky** [comment]
The Builder API for promotion is already done.  That's what the `hab` CLI tool uses to do the promotion.  The UI can use the same API.

**Comment by ryankeairns** [comment]
![tenor-93351479](https://user-images.githubusercontent.com/446285/32632099-ec4dc6ac-c567-11e7-88a1-6a852252ace0.gif)
