### ISSUE TITLE
Website side nav looks bad in [Safari, Chromium, Firefox, Chrome]

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4040]
The nav appears truncated vertically.  You have to scroll in order to see the whole thing.  Also, the boxes around text look funky.

Here are some screenshots:

![screen shot 2017-11-09 at 4 34 43 pm](https://user-images.githubusercontent.com/947/32636987-405deb92-c56c-11e7-8006-8003a3698e61.png)

![screen shot 2017-11-09 at 4 34 55 pm](https://user-images.githubusercontent.com/947/32636991-454e3d32-c56c-11e7-96b2-6fc7ccf9c1cf.png)

This is on macOS 10.13.1, Safari 11.0.1.

**Comment by tashimi** [comment]
This is being reported on Chromium and Firefox, and I see it in Chrome as well.

**Comment by alex-bender** [comment]
Also, on page https://www.habitat.sh/tutorials/build-your-own/node/define-build-logic/
i see this:
![www habitat sh_tutorials_build-your-own_node_define-build-logic_](https://user-images.githubusercontent.com/3628862/32690428-3b550f56-c6ff-11e7-8e9e-ce4b07501443.png)
Browser: chrome 62
System: debian 8
