### ISSUE TITLE
Change order of meta info on the blog mobile view

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#4043]
![image](https://user-images.githubusercontent.com/223407/32736311-20181168-c865-11e7-96db-0bc1796c7271.png)

Tags / other info should be below the content.

**Comment by eeyun** [comment]
I'm not sure if you want to close this out just yet. This commit was reverted this morning because it had an adverse effect on the article view of the blog posts. https://github.com/habitat-sh/habitat/pull/4061
