### ISSUE TITLE
[Builder UI] Indicate when you're working in admin mode

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4051]
As an admin user, I want it to be obvious when I'm working under that mode
so that I can better understand why certain features and data are or are not available to me.

--------

### To-do
- [x] Add UI mockup 

### Mockup
[Admin mode mockup](https://chef.invisionapp.com/share/A9EGQR5TR#/263954722_profile_Godmode)
- adds banner that cannot be dismissed
- adds special profile photo and shadow

![profile godmode 2x](https://user-images.githubusercontent.com/446285/32803331-caf89542-c948-11e7-97a7-8234a623764d.png)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #75](https://github.com/habitat-sh/builder/issues/75) via [**ZenHub**](https://www.zenhub.com/)
