### ISSUE TITLE
Simplify error handling using failure crate

### ISSUE THREAD

**Issue by zeenix** [habitat-sh/habitat#4052]
Throughout the code base, I see a lot of code to create different error types and code to transform between them. During the GNOME+Rust hackfest, I was informed by Alex Crighton (a Rust hacker) about the failure crate that simplifies error handling and according to him, should have been part of Rust. The GStreamer folks seem to be using that a lot in gstreamer-rs already.

Tutorial: https://boats.gitlab.io/failure/
GStreamer using it: https://github.com/sdroege/gstreamer-rs/blob/master/examples/src/bin/appsink.rs

I was told it's best to use it from git repo rather than the version on crates.io: https://github.com/withoutboats/failure.git

There is also related failure-derive that GStreamer is using: https://github.com/withoutboats/failure_derive.git

Anyway, just wanted to bring this up for discussion and if we want to make use of failure crate to reduce the error handling code.

**Comment by eeyun** [comment]
I'd be super interested to see what effect this might have on our error handling. Seems like it could be a pretty cool body of work, if not extensive. I don't think anyone on the core-team would have major objections to seeing a PR like this so I'm going to add this into our "help wanted" bucket.

If any of the core team have other feelings please share them here!

**Comment by zeenix** [comment]
@eeyun here you go :)

https://github.com/habitat-sh/habitat/pull/4041/commits/839063680604e073ab0ccdae7813c22292ee8fd1
https://github.com/habitat-sh/habitat/pull/4041/commits/ce7d134f737e88bd9140ac56c1abca804b8a5630

**Comment by zeenix** [comment]
Oh and it seems I could have gotten rid of even more lines in https://github.com/habitat-sh/habitat/commit/0d021b13017ff048ffa367347d86db28f81c637d : https://github.com/habitat-sh/habitat/pull/4304/commits/e7e5a931dc7d60cf0c0ba6f2874c1f5406baf930
