### ISSUE TITLE
Howto run services that need to spawn multiple processes

### ISSUE THREAD

**Issue by chrisortman** [habitat-sh/habitat#4063]
I need a way to run and update multiple processes that have shared files & configuration. (for example rails web application with delayed job)

I think that the outcome I want could be achieved with one of these features:

1. update strategy that understands about composite packages and how to update them in order. and better control in the composite about what order things run in
2. support for multiple run hooks. Everything works the way it does now, but the supervisor _runs_ all the `run-*` files
3. a command to  invoke the same steps the supervisor takes when it _materializes_ the package under `/hab/svc/`
4. a stop hook

I will add more detailed|rambling context as a comment.

**Comment by chrisortman** [comment]
The scenario is a ruby on rails application that needs to start a web process and a delayed job process.

My first attempt was to have 3 habitat packages, -base, -web, and -job

In order to get the supervisor to realize that the -web and -job packages shouldn't run without the -base I started the -web and -job packages with a `--bind base:my.default`

The `init` script of the -base package would copy all the rails code down into the `/hab/svc/my/static`directory, then symlink files from `/hab/svc/my/config` into rails config. 

The `run` script does `sleep infinity`

The -web and -job packages start their respective processes from their `run` hooks

This kinda works, but it has its problems. The 2 biggest are that my `init` process is slow and updating the packages requires me to stop and restart the supervisor in order to get everything in order. I don't know all the reasons, it seems like it has changed over time as habitat has evolved.

I had hoped that composite packages might help this, but because the update mechanisms still rely on the existing behaviour I don't think they will.

I have also been following along with the ruby-scaffolding and noticed that it is now *not* copying files to the `/hab/svc/***` directory and instead symlinks some of the writable directories to that path. I changed to do this too which solves my 'slow init' issue. I also thought it would let me just have 2 packages that I need to `hab start` but, I still have to `start` the base package because it needs to materialize the config files and symlinked files & folders need a common place

The other route I have taken is to try to have 1 habitat package and use `god` as my thing that habitat runs. Then have `god` start my web & job processes. This almost works, but I think I have to break some habitat rules that I'm not sure all the implications of. When the `god` process exits it doesn't stop the processes it has started. So I added a `SIGTERM` trap to my run hook, but that means I can't `exec god` or the trap will never get called. So I could maybe make `god` work by not exec'ing but
I'm not sure how easy it will be for me to leave some zombie processes out there

**Comment by themightychris** [comment]
We need this for PHP applications too, as they are at least in some cases best deployed as a single service that happens to have two processes (e.g. php-fpm and nginx)

It would be great if habitat exposed a way to do this directly with the supervisor, as having the have supervisor launch another supervisor that than supervises 2-3 processes is silly and a mess

Maybe the form this could take is a separated core/hab-* package with a bare-bones sub-supervisor that makes use of some supervisor code and provides a way to wrap multiple processes under one service (with one config/start/stop lifecycle) in a maximally habby way

**Comment by bdangit** [comment]
Just food for thought, this is what Docker recommends for running multiple processes within one “service”: https://docs.docker.com/config/containers/multi-service_container/

**Comment by bdangit** [comment]
TL:DR, they have a wrapper “run” script that spawns any number of things you need up.

**Comment by themightychris** [comment]
@bdangit I've seen that approach and that's what I do now, but the PID capture and monitoring is very brittle. If the hardened code the habitat supervisor already has for this could be tapped to build another binary that was optimized to do all that heavy lifting with minimal user code within the context of habitat lifecycle hooks, that could be a lot more powerful and might be a relatively light lift if the current factoring is conducive to reusing the right bits

**Comment by chrisortman** [comment]
@themightychris In my rails projects I've been using https://github.com/kostya/eye as a gem and having hab start that.
It's been a useful tool in development as well.

I have another non-rails project I finished setting up last night that will use supervisiord http://supervisord.org/index.html
