### ISSUE TITLE
Hab does not start service and considers it up

### ISSUE THREAD

**Issue by jlebloas** [habitat-sh/habitat#4069]
Hi,

I'm running habitat `hab 0.38.0/20171026215954` on `CentOS Linux release 7.1.1503 (Core)` with systemd.

I've a supervisor, that run 2 services groups. The first `monit` that is running, and one java, the `myservice`, that did not start, although I can see in my supervisor log a `Starting mygroup/myservice`.

My issue is that habitat in the logs tells it started the service, but the hook seems to have not been started :(
```
journalctl -u habitat.service
-- Logs begin at Thu 2017-11-16 06:00:33 CET, end at Thu 2017-11-16 10:38:31 CET. --
Nov 16 06:00:41 ip-10-230-136-22.res.jcdecaux.org systemd[1]: Starting The Habitat Supervisor...
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org systemd[1]: Started The Habitat Supervisor.
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MN): Failed to resolve peer: some-peer.com:8369
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MN)[src/main.rs:1020:31]: Error resolving a name or IP address: Connection refused (os error 111)
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MR): Supervisor Member-ID 5ea4a4f5a4e44e1ab06078ed0310fae3
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MR): Starting mygroup/myservice
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MR): Starting mygroup/monit
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
Nov 16 06:00:43 ip-10-230-136-22.res.jcdecaux.org hab[732]: hermes.ppr(HK): Hooks compiled
Nov 16 06:00:43 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(SR): Reattached to myservice.ppr
```

The supervisor is running and here is the result of my hab sup status:
```
/hab/bin/hab sup status
mygroup/myservice/1.6.2/20171027084558 (standalone), state:up, time:PT1464.965456292S, pid:4733, group:myservice.ppr, style:transient
mygroup/monit/master/20171024132302 (standalone), state:up, time:PT1464.966358624S, pid:4736, group:monit.ppr, style:transient
```

Here is my systemd service file. Note that with @rsertelon we've added a `rm -f /hab/sup/default/LOCK` needed for habitat to restart since our ec2 where the service runs are shutdown the night and restarted at 6 in the morning. I cannot control the shutdown, it seems to be brutal.
```
[Unit]
Description=The Habitat Supervisor

[Service]
ExecStartPre=-/bin/rm -f /hab/sup/default/LOCK
ExecStart=/hab/bin/hab sup run --no-color --peer some-peer.com:8369

[Install]
WantedBy=multi-user.target
```

**Comment by jlebloas** [comment]
I found something interesting by looking on another service deployed with the same manner.

```
-- Logs begin at Thu 2017-11-16 06:00:28 CET, end at Thu 2017-11-16 15:19:22 CET. --
Nov 16 06:00:34 ip-10-230-137-102.res.jcdecaux.org systemd[1]: Starting The Habitat Supervisor...
Nov 16 06:00:34 ip-10-230-137-102.res.jcdecaux.org systemd[1]: Started The Habitat Supervisor.
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: hab-sup(MR): Supervisor Member-ID cc5993b48c7c4f6f93a96b067c101551
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: hab-sup(MR): Starting mygroup/otherservice
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: hab-sup(MR): Starting mygroup/monit
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: hab-sup(MR): Starting gossip-listener on 0.0.0.0:9638
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: hab-sup(MR): Starting http-gateway on 0.0.0.0:9631
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: otherservice.ppr(HK): Hooks compiled
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: otherservice.ppr(SR): Initializing
Nov 16 06:00:35 ip-10-230-137-102.res.jcdecaux.org hab[751]: otherservice.ppr(SV): Starting service as user=hab, group=hab
```
This server also restart at 6 in the morning. But this one that has no problem displays `otherservice.ppr(SV): Starting service as user=hab, group=hab`, whereas the other was logging `Reattached to myservice.ppr`:
```
Nov 16 06:00:43 ip-10-230-136-22.res.jcdecaux.org hab[732]: myservice.ppr(HK): Hooks compiled
Nov 16 06:00:43 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(SR): Reattached to myservice.ppr
```

When a service group is reattached or not ? Is this an expected behavior of the supervisor?
This may be linked with the fact that it seems that while starting, it was not able to connect to its peer.
```
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MN): Failed to resolve peer: some-peer.com:8369
Nov 16 06:00:42 ip-10-230-136-22.res.jcdecaux.org hab[732]: hab-sup(MN)[src/main.rs:1020:31]: Error resolving a name or IP address: Connection refused (os error 111)
```

**Comment by qhartman** [comment]
I'm also seeing this behavior in containers from time to time. It seems that the pid file (/hab/svc/my_svc/PID) from a previous run is being left behind in some cases.

I started a hab-created container this morning (12-11-17) and the creation date on the pid file for the service was from 12-7-17.

**Comment by qhartman** [comment]
To work around my problem, I've added the following to init hooks on all the plans I use:
`# hack to ensure that stale pid files are removed at startup
find /hab/svc -name PID -type f -exec rm {} \;`

Have had no instances of containers failing to start services since.

**Comment by christophermaier** [comment]
@qhartman Do you mount `/hab/svc` into your container (i.e., does it persist separate from the container itself)? I'm tracking this down at the moment, and that might help shed some additional light on things. Thanks!

**Comment by qhartman** [comment]
I am not mounting /hab/svc externally.

**Comment by christophermaier** [comment]
Closing due to age; if this is still a problem, feel free to reopen.
