### ISSUE TITLE
[Builder] Allow users to specify a branch when connecting a plan file

### ISSUE THREAD

**Issue by irvingpop** [habitat-sh/habitat#4079]
Currently the Builder UI only allows you to connect to a plan.sh in the `master` branch of a repo.

As a developer on a project that is being Habitized, I would like the ability to have my packages built for me off of a soon-to-be-merged branch.

I  imagine teams that maintain non-master "release" branches may also appreciate this feature.

**Comment by nathenharvey** [comment]
👍

**Comment by eeyun** [comment]
Yeah I think this is a feature we can all get behind!
