### ISSUE TITLE
Gather examples of application plans

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4083]
Gather examples of application plan.sh's (and plan.ps1's) for different application stacks to use as examples for people who are trying to get started.

Languages that have been requested (feel free to add more!):
- c++
- python
- php
- go

Looking for applications with plans in these stacks so we can use them as examples for new users.

**Comment by burtlo** [comment]
Python Flask example application: https://github.com/burtlo/pepper_python

**Comment by burtlo** [comment]
* [Apache Website Example](https://github.com/burtlo/habitat-httpd)
* [Java/Tomcat/Mongo (National Parks) Example](https://github.com/burtlo/national-parks)
* [MEAN Stack Example](https://github.com/burtlo/habitat-haikus)
* [Ruby Sinatra Example](https://github.com/burtlo/habitatize)

**Comment by tashimi** [comment]
Here's a go plan: https://github.com/indradhanush/habitat-demo-service

**Comment by themightychris** [comment]
Here's a haskell stack app, it could use some updating since a better GHC plan got merged but the app (`postgrest`) is a good one

**Comment by themightychris** [comment]
Another go plan: https://github.com/JarvusInnovations/habitat-plans/blob/master/gnatsd/plan.sh

**Comment by elliott-davis** [comment]
@ryankeairns, any thoughts on how we could showcase these?

**Comment by ryankeairns** [comment]
@elliott-davis yes! We have templates for Getting Started pages (e.g. http://habitat.sh/get-started/node ). Perhaps as a precursor to that we could start a section/page in the docs under Reference. Then, as it grows, create topical Get Started like this Node example. 

@apriofrost and I can work on a proper place to store these in the docs IA for the near-term.
