### ISSUE TITLE
Dependency conflict detection sometimes include non conflicting packages

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/habitat#4087]
> hab 0.38.0/20171026215954

I noticed several times while building `core/glib` and friends that if a conflict is detected with different versions of `core/glib`, `core/glibc` got picked up too:

```
soup: Resolved dependency 'core/glib' to /hab/pkgs/core/glib/2.50.3/20171118162036
   soup: WARN 
   soup: WARN The following runtime dependencies have more than one version
   soup: WARN release in the full dependency chain:
   soup: WARN 
   soup: WARN   * core/glib ( core/glib/2.50.3/20171118162036 core/glib/2.50.3/20171118151949 core/glibc/2.22/20170513201042 )
```

**Comment by rsertelon** [comment]
I think I've narrowed it down to [this line](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L1123).

I'll submit a fix.

**Comment by fnichol** [comment]
I bet that was some careful reading to find this one.
