### ISSUE TITLE
Ability to delete an origin integration

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#4090]
Currently the UI supports deleting an origin integration but it's calling the wrong API endpoint. The correct API endpoint for DELETE doesn't exist but should be implemented.

**Comment by raskchanky** [comment]
@elliott-davis Isn't this it?  https://github.com/habitat-sh/habitat/blob/master/components/builder-depot/src/handlers/integrations.rs#L151

**Comment by elliott-davis** [comment]
It certainly is - The issue was being masked by project deletes not cascading. It should be fixed by #4106
