### ISSUE TITLE
Randomly generated default values (if uninitialized)

### ISSUE THREAD

**Issue by irvingpop** [habitat-sh/habitat#4091]
As a user of the database plans like `postgresql` and `mysql`, I need to set secure admin passwords for my services.  Currently this is accomplished by injecting configuration (e.g. docker environment variables) but we could have something that is easier to automate and more secure.

Today, as a plan author I could achieve my desired results like so:
1.  create a `default.toml` with secrets defaulting to empty strings like so:
```
[secrets.postgresql]
db_superuser_password = ""
```
2.  create a template that writes all my secrets out to disk:
```
{{toToml cfg}}
```
3. at init or run time, run a script that detects all empty-string variables and generates secrets for them
4.  Inject the secrets back into the ring  (this works, but has delays propagating to bound services)
```
hab config apply myservice.default $version {{pkg.svc_data_path}}/hab-secrets-modified.toml
```

However, it could be so much better if I could ask Habitat to generate my secrets for me at the time of service load, thus avoiding the round trip entirely.   For example:

```
[secrets.postgresql]
db_superuser_password = "{{generateRandomString(32)}}"

[secrets.chef-server]
superuser_key = "{{generateRsaPrivateKey(superuser)}}"
superuser_pub_key = "{{generateRsaPublicKey(superuser)}}"
```

Naturally each of these plans would need init/reconfigure hooks smart enough to re-apply the generated values if they change (or if the ring data is lost, but the data volume persists) but that is a well bounded and solvable problem.

**Comment by rsertelon** [comment]
@irvingpop How would you access said passwords once generated? Or is it "just" so they don't stay default value, and you don't actually need to know them?

**Comment by irvingpop** [comment]
@rsertelon they would be in the ring, so available to any other services (for example, via bind.cfg)

**Comment by rsertelon** [comment]
ah yeah ok, I see :) that's a nice feature indeed! For the certificate generation, will they be self-signed?

**Comment by irvingpop** [comment]
this is an RFE, so the sky is the limit.  but practically speaking, I'm not sure if CA-signed certs would be practical here.

**Comment by eeyun** [comment]
This is 100% something that we would accept into core. It's not something that we're likely to get prioritization on right now, but if someone wrote it we'd definitely take it. It's also possible that this could get prioritization later in the year so for now I've removed  the RFE tag from this and put it into our Help Wanted milestone.
