### ISSUE TITLE
builder 0.39 or newer fails with "a password was requested but not provided"

### ISSUE THREAD

**Issue by dongsupark** [habitat-sh/habitat#4096]
While trying to run bldr with habitat 0.39 on Fedora 26, I saw the errors.

```
$ sudo -E make bldr-run-no-build
...
jobsrv.1 ERROR:r2d2: Error opening a connection: Invalid connection parameters: a password was requested but not provided
originsrv.1 ERROR:r2d2: Error opening a connection: Invalid connection parameters: a password was requested but not provided
...
```

According to `BUILDER_DEV.md` I would need to get a private key from 1password, but obviously as an external contributor, I cannot get the key. So I had to create my own github app, and from the app I had to create a private key. I saved the key to `/src/.secrets/builder-github-app.pem`. But even after that, bldr does not run with the error message above.

It's intesting that this issue happens only with Habitat builder 0.39 or newer, but it does not happen with 0.38.

**Comment by schu** [comment]
I think the error is about not being able to connect to the postgres database. The default is an empty password: https://github.com/habitat-sh/habitat/blob/master/components/builder-jobsrv/habitat/default.toml#L18

But the Postgres server doesn't accept an empty password as far as I can tell.

In `support/builder/config.sh` jobsrv is configured like this: https://github.com/habitat-sh/habitat/blob/master/support/builder/config.sh#L47

Looks like a password is required but the documentation wasn't updated.

**Comment by robertgzr** [comment]
Does this line seem related:
```
function psql() {
  hab pkg exec core/postgresql env PGPASSWORD=$(cat /hab/svc/builder-datastore/config/pwfile) psql -U hab -h 127.0.0.1 "$@"
}
```
| from support/linux/helpers.sh

**Comment by dongsupark** [comment]
Never mind. I don't see this issue since I configured github authentication correctly.
Sorry for the noise.

**Comment by nellshamrell** [comment]
Re-opening - I am seeing this when trying to run 

```
sudo -E make bldr-run
```

**Comment by dongsupark** [comment]
@nellshamrell Hmm, interesting. I've not seen this issue since then. Then there's probably another occasional issue.

**Comment by eeyun** [comment]
Closing as resolved!
