### ISSUE TITLE
uploading a built Linux package from macOS seems broken

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#4097]
First noticed this after updating from `0.38.0` to `0.39.1`

```
» Uploading results/<origin>-<vendored_python_modules>-0.0.1-20171121173101-x86_64-linux.hart
∵ Missing artifact for core-acl-2.2.52-20170513213108-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-acl-2.2.52-20170513213108-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-acl-2.2.52-20170513213108-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-acl-2.2.52-20170513213108-x86_64-darwin.hart was not found in results
∵ Missing artifact for core-acl-2.2.52-20170513213108-x86_64-darwin.hart was not found in results
✗✗✗
✗✗✗ Upload failed: We tried 5 times but could not upload core/acl/2.2.52/20170513213108. Giving up.
✗✗✗
make: *** [test] Error 1
```

cc: @christophermaier @eeyun

**Comment by christophermaier** [comment]
To my recollection, this behavior has been around for a while, but it's definitely surprising. It would be better to look for dependencies based on the target architecture of the package being uploaded, instead of the architecture of the system doing the uploading.

**Comment by nathenharvey** [comment]
The workaround is to upload from within the habitat studio.

From my Mac:

```
$ hab pkg upload results/nathenharvey-gs-accessing-data-mysql-0.1.0-20171129190233-x86_64-linux.hart
✓ Signed artifact with nathenharvey-20160614103115.pub
» Uploading public origin key nathenharvey-20160614103115.pub
    83 B / 83 B | [===============================================] 100.00 % 507 B/s
→ Using existing public origin key nathenharvey-20160614103115.pub
» Uploading results/nathenharvey-gs-accessing-data-mysql-0.1.0-20171129190233-x86_64-linux.hart
∵ Missing artifact for core-busybox-static-1.24.2-20170513215502-x86_64-darwin.hart was not found in results
...
```

I then ran `$ hab studio enter` and  `# hab pkg upload results/nathenharvey-gs-accessing-data-mysql-0.1.0-20171129190233-x86_64-linux.hart` from within the studio and the upload worked successfully.

**Comment by bixu** [comment]
@nathenharvey is correct, this is a viable workaround in lots of cases. In our case it's a bit trickier since we have multiple origins that we build/upload to, and we test the build tooling sometimes natively on macOS because test cycles in Travis are very slow.

**Comment by fnichol** [comment]
Yep, that's a bug--we compute a candidate .hart file name when trying to find un-uploaded dependencies but that logic pre-dated the notion of using the `TARGET` metadata in packages. That's why I'm almost 100% sure that we don't check the `TARGET` of the your desired artifact file and use *that* for the candidate .hart file name computing.

**Comment by chrisortman** [comment]
I am still seeing this as of `➜  hab --version
hab 0.52.0/20180119184453`
