### ISSUE TITLE
Exports should store generated artifacts in unified way

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/habitat#4104]
Currently there are multiple exports available for habitat packages:

* ACI
* CloudFoundry
* Docker
* Kubernetes
* Mesos
* Tar

Some of these generate artifacts in a another repository (docker for example), others on the filesystem.

For the latter there is for now, no standard on where artifacts should be stored (tar exports in `$PWD`, aci in `/src/results` thus works only in the studio).

Several discussions on slack lead to the following statement:

> Exports should generate artifacts in `$PWD` and provide a `--path <path>` flag to override this behavior.

I chose to rename the original issue to an RFC, because I think there might be other things to discuss that we didn't see in some minutes.

**Comment by bdangit** [comment]
how about `./exports/` instead as default? its clear, its where I could assume all my stuff is.  Its also easier for me to add `exports` to my `.gitignore` as a dir exclusion versus saying ignore any `.tar|.aci|or whatever exports`. ?
