### ISSUE TITLE
Finish API integration tests

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4105]
This is part of the https://github.com/habitat-sh/habitat/issues/4013 epic.

Right now, we have an integration test suite (written in TypeScript) for the Builder API.  It's only partially complete and requires some setup to run correctly.

In preparation for API v2, we need to:

- [x] Finish the test suite so that the entire API is covered
- [x] Make the setup/teardown easier so that we can run this in CI

**Comment by raskchanky** [comment]
The last thing left for these tests is to get them passing on Travis.  @baumanj will be carrying the torch across the finish line for that final piece.

**Comment by baumanj** [comment]
Currently blocked on the hab-based builder dev env https://github.com/habitat-sh/habitat/issues/4442

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #77](https://github.com/habitat-sh/builder/issues/77) via [**ZenHub**](https://www.zenhub.com/)
