### ISSUE TITLE
Vagrantfile: wrong port forwardings

### ISSUE THREAD

**Issue by schu** [habitat-sh/habitat#4107]
The current Vagrant file defines the following forwarded ports:

https://github.com/habitat-sh/habitat/blob/5568b7a72a9cb876318ca12168e2a5cc2ac7df28/Vagrantfile#L13-L15

Two ports are assigned to the same host port (`9636`). Also, it's not clear what is listening on port 80 on guest side. The documentation mentions port 3000 for the webUI in a few places. Is that meant instead?

**Comment by dongsupark** [comment]
FYI I already created a PR for this issue. https://github.com/habitat-sh/habitat/pull/4098

**Comment by schu** [comment]
@donaldguy thanks, I have missed the pull request.

**Comment by rsertelon** [comment]
This looks outdated.
