### ISSUE TITLE
[xxxproto] Make sure dependencies are ok

### ISSUE THREAD

**Issue by rsertelon** [habitat-sh/habitat#4110]
@stevendanna reported [here](https://github.com/habitat-sh/core-plans/pull/988#discussion_r152648158) that there might be useless dependencies for xxxproto packages.

```
> grep 'pkg_dep' *proto/plan.sh
fixesproto/plan.sh:pkg_deps=(core/glibc)
inputproto/plan.sh:pkg_deps=(core/glibc)
recordproto/plan.sh:pkg_deps=(core/glibc)
renderproto/plan.sh:pkg_deps=(core/glibc)
xcb-proto/plan.sh:pkg_deps=(core/glibc)
xextproto/plan.sh:pkg_deps=(core/glibc)
```

We should remove them if not needed :)

**Comment by stevendanna** [comment]
@rsertelon Let's move this over to core-plans I think

**Comment by rsertelon** [comment]
Oh yeah true! sorry x) can we move issues in github (as in gitlab?)
