### ISSUE TITLE
User-defined channels not showing up in package release page of Builder UI

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#4114]
The scenario I have is that I'm taking an existing package that is already in Builder and want to promote it to a user-defined channel. This action succeeds, but the custom channel doesn't show in up the release-specific page for that package (e.g. https://bldr.habitat.sh/#/pkgs/dwrede/sample-rails-app/0.1.1/20171116163114). 

![screen shot 2017-11-22 at 2 37 54 pm](https://user-images.githubusercontent.com/1634752/33152689-c19f43d8-cf92-11e7-8f32-62e6faaf880f.png)

However, it does show up in https://bldr.habitat.sh/#/pkgs/dwrede/sample-rails-app/latest and when drilling down by version (https://bldr.habitat.sh/#/pkgs/dwrede/sample-rails-app).

![screen shot 2017-11-22 at 2 37 24 pm](https://user-images.githubusercontent.com/1634752/33152682-b16cb5fe-cf92-11e7-85ef-f8857c22a4a6.png)

![screen shot 2017-11-22 at 2 38 23 pm](https://user-images.githubusercontent.com/1634752/33152701-d341fdd8-cf92-11e7-88aa-8be34a700ca3.png)

It appears the `range` query  (used in the release-specific page at the top) doesn't return the entire channel list

https://bldr.habitat.sh/v1/depot/pkgs/dwrede/sample-rails-app/0.1.1/20171116163114?range=0

while this one does

https://bldr.habitat.sh/v1/depot/pkgs/dwrede/sample-rails-app/0.1.1/20171116163114

**Comment by eeyun** [comment]
Hey @davidwrede in triage we're unable to duplicate this behavior, we did just do a deployment this morning so we're thinking this might be fixed. Can you double check on your local machine and let us know if this is still an issue for you? For now I'm going to close this out and if the issue remains please feel free to update and reopen.

**Comment by davidwrede** [comment]
Hey @eeyun Yeah, I'm still seeing the behavior above. Happy to sync with someone later today to show the repro.

**Comment by eeyun** [comment]
We've validated that this bug is fixed! Closing as completed!
