### ISSUE TITLE
Local Habitat environment

### ISSUE THREAD

**Issue by schu** [habitat-sh/habitat#4117]
Hey, I'm trying to setup a local Habitat environment in order to entirely test and run Habitat Builder on a local machine.

While the repository contains a good amount of developer oriented documentation, all of it seems to be partly outdated, incorrect, incomplete or only accessible to Habitat-internal folks. Below I try to collect a few examples / feedback to outline some of the problems that I encountered.

(Some of the points might be touched by https://github.com/habitat-sh/habitat/issues/4070)

### Setting up services

https://github.com/habitat-sh/habitat/blob/master/BUILDER_DEV.md appears to be the right point of information for a local development environment. But..
* as far as I can tell, it's only describing how to test/run a subset of Builder services and not for instance the web interface, which would obviously be needed for a full local development environment,
* it instructs to copy a private key file from a private Habitat 1Password store,
* it instructs to create configuration files, but misses a service `originsrv` (and doesn't touch the fact that `support/builder/config.sh` automatically configures the Vagrant VM with hard-coded Habitat credentials)

### Configuring GitHub OAuth/Apps

Configuration for GitHub authentication and integration is very confusing:
* Some parts seem to describe GitHub **OAuth**, some GitHub **Apps** OAuth
* There's no way for users to provide configuration w/o chaging source code in git
* The builder-web README appears to show an oudated configuration file: https://github.com/habitat-sh/habitat/tree/master/components/builder-web#configuration doesn't include `github_app_id`, https://github.com/habitat-sh/habitat/blob/master/components/builder-web/habitat.conf.sample.js#L24 does
  * It's also not clear which `github_client_id` actually needs to be used
* https://github.com/habitat-sh/habitat/blob/master/BUILDER_CONTAINER.md#github-oauth-application instructs to create an **OAuth** application with callback `http://${APP_HOSTNAME}/#/sign-in`, but that's not what is used for the `redirect_uri` parameter in the sign-in button; is this up-to-date?

### Using the Vagrant environment

https://github.com/habitat-sh/habitat/blob/master/BUILDING.md#vm-vs-docker-development gives instructions on how to start the Vagrant environment. Further down, `make bldr-run` is shown to run "all builder components" (what are all components?), but that doesn't seem to be tested / entirely work (on `master / 69211c1a597d4f7512cfc325204b322f46ad0a88`):

```
postgres.1  | builder-datastore.default hook[health_check]:(HK): could not change directory to "/root/habitat": Permission denied
```

Event if it would, It's not clear how to actually get started / use the components from that point on.

**Comment by schu** [comment]
The [example on how to create a project](https://github.com/habitat-sh/habitat/blob/master/BUILDER_DEV.md#create-the-projects-you-want-to-build) as well as the `projectCreate` schema seem to be wrong after https://github.com/habitat-sh/habitat/commit/c50870139fe87ab131a12ae6c5083385fe38d871 What is the `installation_id`?

**Comment by nellshamrell** [comment]
I've clarified instructions here https://github.com/habitat-sh/habitat/pull/4275

**Comment by schu** [comment]
@nellshamrell thanks, commented there.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #78](https://github.com/habitat-sh/builder/issues/78) via [**ZenHub**](https://www.zenhub.com/)
