### ISSUE TITLE
Kubernetes exporter output spec should use image tag scheme from Docker exporter

### ISSUE THREAD

**Issue by robertgzr** [habitat-sh/habitat#4123]
When exporting a pkg:
```
$ hab pkg export kubernetes origin/app
...
spec:
  image: origin/app
...
```

But:
```
$ hab pkg export kubernetes origin/app/0.0.0-version
...
spec:
  image: origin/app/0.0.0-version
...
```
which is not what I expect.
Since the docker exporter tags images with the version (and optionally timestamp of the build) it should be:
```
$ hab pkg export kubernetes origin/app/0.0.0-version
...
spec:
  image: origin/app:0.0.0-version
...
```

and:
```
$ hab pkg export kubernetes origin/app/0.0.0-version/20171127161029
...
spec:
  image: origin/app:0.0.0-version-20171127161029

...
```

**Comment by robertgzr** [comment]
cc @zeenix

**Comment by zeenix** [comment]
Actually it should be just:

```
$ hab pkg export kubernetes origin/app/0.0.0-version
...
spec:
  image: origin/app
...
```

and is the case when in my pending PR of mine: https://github.com/habitat-sh/habitat/pull/4041/commits/0b6f69f0aa120ede4abac07b1153149cccad2b47

**Comment by robertgzr** [comment]
To capture the in-person chat we had offline:

It should be possible to pin the image version the habitat-operator uses in the way described above so if I export a specific build using the full pkg identifier `origin/app/version/timestamp` I can be sure I get exactly that version when I deploy it...
