### ISSUE TITLE
Update habitat.sh wording

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4125]
- All of the `Learn More` buttons should be renamed to `Get Started` (in the "hero" and the "slider" sections, total of 4 buttons, and they should all link to the demo at https://www.habitat.sh/demo/
- Rename "Reference" to "Docs" in the header to be consistent across the site.

**Comment by apriofrost** [comment]
Another suggestion for the carousel: could we change the length of the three orange bar to fill the entire grey bar? Since we don't have it animated yet.
![image](https://user-images.githubusercontent.com/9401459/33284585-6baa1108-d364-11e7-932f-92b4e12a8ddf.png)

**Comment by mgamini** [comment]
Sure, no problem @apriofrost
