### ISSUE TITLE
Dealing with CLRF in habitat files

### ISSUE THREAD

**Issue by smford22** [habitat-sh/habitat#4144]
I built a simple plan for a java spring boot application. The application built fine, but when I loaded the `.hart` in my studio I received the error:

 `Service restart failed: hab-sup(ER)[src/error.rs:508:8]: Unknown: Unable to spawn process, No such file or directory (os error 2)`

Upon further debugging with Habitat engineering it turned out there were CLRF characters in the `hooks/run` like `^M` which were throwing the supervisor off. The error was very misleading though.

It would be great if there was a way for Habitat to deal with CLRF more gracefully.

**Comment by mwrock** [comment]
We could have habitat do a global replace of all carriage returns of the hooks. However that gets pretty messy and you may have other `*.sh` files that need fixing too. Its really the interpreter (bash) that fails to handle the carriage return. Another approach that is likely better is to add a `.gitattributes` to core-plans and perhaps to the `hap plan init` generator to keep cariage returns out of the repo.

**Comment by eeyun** [comment]
On review we're going to make sure that core-plans has some protection in place to avoid accidental carriage return use but, we feel like ultimately this is something that is handled best in one's text editor. We don't think the correct response would be to write features to catch this specific issue.

Closing for now, but if there is further discussion to be had please feel free to leave more comments!
