### ISSUE TITLE
Incorrect package name used when connecting a plan file

### ISSUE THREAD

**Issue by nathenharvey** [habitat-sh/habitat#4149]
* GitHub Repo - https://github.com/nathenharvey/gs-rest-service
* Plan file in that repo - https://github.com/nathenharvey/gs-rest-service/blob/master/complete/habitat/plan.sh (a subdirectory within the repository)

I connected a plan file before uploading any packages.
After connecting the plan file, https://bldr.habitat.sh/#/pkgs/nathenharvey/complete was created.
I had to "Build latest version" to kick-off a build.
This created https://bldr.habitat.sh/#/pkgs/nathenharvey/gs-rest-service, as expected.

The "complete" package remained connected but I have since disconnected it.

I had to manually configure the nathenharvey/gs-rest-service package to connect it to the git repository.  As noted in #4148 builds for this package never seem to begin automatically.

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #291](https://github.com/habitat-sh/builder/issues/291) via [**ZenHub**](https://www.zenhub.com/)
