### ISSUE TITLE
Builder: better error messages when having github authentication errors

### ISSUE THREAD

**Issue by dongsupark** [habitat-sh/habitat#4153]
When testing Habitat Builder I have seen strange cases where it's impossible for any plan to be connected. It means, on the web UI, connecting to plan hangs forever. In that case, there's no error at all, neither on the web UI nor in the bldr log.

The only warning that looks suspecious in the bldr log is like that:

```
sessionsrv.1 | WARN:habitat_builder_sessionsrv::server::handlers: Failed to obtain installation token, GitHub App Authentication error, message=Not Found, documentation_url=https://developer.github.com/v3/apps/#create-a-new-installation-token
```

However, the warning above is not actually meaningful, because it shows up no matter whether github authentication error happens or not. Rather the warning simply makes debugging harder.

In my case, the real reason was actually misconfiguration of client ID as well as client secret. If any error would have indicated an authentication error of client ID or client secret, it could have been much easier to track the issue.

It would be really great, if Habitat Builder could print out meaningful messages in case of github authentication errors.

/cc @schu @indradhanush @robertgzr

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #288](https://github.com/habitat-sh/builder/issues/288) via [**ZenHub**](https://www.zenhub.com/)
