### ISSUE TITLE
[www] Update pricing page copy to include the new ECR integration

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4155]
See https://www.habitat.sh/pricing/
![image](https://user-images.githubusercontent.com/9401459/33393818-46bcd19a-d4f5-11e7-9708-bc7eed30a23f.png)

**Comment by tashimi** [comment]
Yes! Let's say "DockerHub, AWS ECR, with more coming"

**Comment by elliott-davis** [comment]
#4156 Closes this
