### ISSUE TITLE
Tar exporter: the next generation

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4172]
The tar exporter is due for a re-write in the style of the new docker exporter. 

The resultant exporter should: 
- be written in rust
- follow the patterns of the docker exporter work by @fnichol 
- include `hab-launcher` in exports 
- follow a standard way across all new exporters as to where generated exports are stored (per #4104)

**Comment by nellshamrell** [comment]
Also related (defines need for hab-launcher in exports) #4039

**Comment by nellshamrell** [comment]
I think I've got a good handle on how the Docker exporter works now - details are here https://gist.github.com/nellshamrell/f38630f98c7b09d86607529e20208f45

**Comment by nellshamrell** [comment]
This includes a abbreviated explanation for how the current generate tar exporter works:

https://gist.github.com/nellshamrell/e9163880ef79f99e1fb17b0b7af1a66e

**Comment by nellshamrell** [comment]
Breakdown of work as I see it right now:

- [ ]  Create pkg-export-tar rust crate - should be BOTH a lib and a binary
- main.rs should call lib
- lib should include TarBuildRoot (modeled after DockerBuildRoot)
- lib should export new tarball (modeled after how the docker image is exported)
- [ ] Create hab/src/command/pkg/export/tar.rs - model after hab/src/command/pkg/export/docker.rs
- [ ] Wire hab pkg export tar to call hab/src/command/pkg/tar.rs

**Comment by nellshamrell** [comment]
Managed to isolate the silent failures I was seeing when the builder keys for the package could not be accessed:

- unset local HAB_BLDR_URL (will use public builder as default)
- hab install core/test-app
- copy test-app artifact to directory for habitat/components/pkg-export-tar
- run $ cargo run test-app-artifact
- tars package, includes test-app in tarball

- set HAB_BLDR_URL to http://localhost:9636
- hab install core/nginx-cc-demo
- copy nginx-cc-demo to directory for habitat/components/pkg-export-tar
- run $ cargo run nginx-cc-demo artifact
- tars package, includes nginx-cc-demo in tarball

- make sure local builder is running
- set HAB_BLDR_URL to http://localhost:9636
- hab install core/scaffolding-node
- copy scaffolding-node to directory for habitat/components/pkg-export-tar
- run $ cargo run scaffolding-node-artifact
- tars package, includes scaffolding-node

- unset local HAB_BLDR_URL (will use public builder as default)
- copy scaffolding-node to directory for habitat/components/pkg-export-tar
- run $ cargo run scaffolding-node-artifact
- tars package, includes scaffolding-node

- do a new local build of scaffolding-node app (with HAB_BLDR_URL set to http://localhost:9636)
- copy new sample-node-app artifact to directory for habitat/components/pkg-export-tar
- make sure HAB_BLDR_URL is not set
- run $ cargo run sample-node-app
- tars package, DOES NOT include sample-node-app

**Comment by elliott-davis** [comment]
@nellshamrell is this issue complete?

**Comment by nellshamrell** [comment]
Yep!
