### ISSUE TITLE
Add missing dep to docker & k8s exporter plans

### ISSUE THREAD

**Issue by zeenix** [habitat-sh/habitat#4179]
It's been reported by @schu that docker & k8s exporters are currently not buildable as hab packages, unless you add `core/make` to deps: https://github.com/habitat-sh/habitat/pull/4041#issuecomment-348483199

**Comment by elliott-davis** [comment]
Added here: https://github.com/habitat-sh/habitat/blob/master/components/pkg-export-docker/plan.sh#L13
