### ISSUE TITLE
Figure out how to release `hab` using Builder

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4180]
Our current release process relies, ironically enough, on a TravisCI pipeline. In an ideal world, we'd be using Builder to build and release `hab`.

The current release process is not atomic, in that Habitat packages are uploaded to Builder and promoted to the stable channel _as they are generated_, and not at the end of a complete build. If we run into a problem halfway through the build, we can be in a "half-released" state, with a new stable `core/hab` artifact, but no corresponding `core/hab-sup` artifact, for instance.

This can happen with increasing frequency, since our overall build process is starting to regularly exceed TravisCI's build timeout. This requires multiple runs and manual modifications to the build process.

There may be some short-term fixes that we can make to buy us some time. Figuring out how to make Travis do more atomic releases would be a huge win, as would coming up with a way to somehow decompose build steps to stay within TravisCI's build timeout.

Long term, however, we need to sort out how to have Builder run the show. Some initial thoughts:

* We'll need a MacOS build toolchain
* We'll need MacOS and Windows build workers
* Builder will need to be able to dispatch a job across multiple build platforms

The desired output from this issue is a roadmap for what we need to do to start releasing using Builder. Figuring out shorter term fixes that improve the current experience is decidedly within scope.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #80](https://github.com/habitat-sh/builder/issues/80) via [**ZenHub**](https://www.zenhub.com/)
