### ISSUE TITLE
ACI Exporter: The next generation

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4187]
The ACI exporter is due for a re-write in the style of the new docker exporter.

The resultant exporter should:
- be written in rust
- follow the patterns of the docker exporter work by @fnichol
- include `hab-launcher` in exports
- follow a standard way across all new exporters as to where generated exports are stored (per #4104)

**Comment by tashimi** [comment]
@rsertelon is working on this atm

**Comment by nellshamrell** [comment]
See the new pkg-export-tar for a pattern with all the Docker stuff stripped out :)

**Comment by rsertelon** [comment]
Yeah thanks @nellshamrell I was kinda watching your progress on tar export :) Will try to move forward this week-end ;)

**Comment by rsertelon** [comment]
Hey guys, an update on this. My spare time has been really thin since Xmas, and I can't find any time to work on such a big task at the moment. So I have to step down on this one, sorry!
