### ISSUE TITLE
Ensure pkg-export-docker (and all crates, really) get built by CI

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4192]
As we've added crates to the project, some have slipped through the cracks and aren't necessarily built during normal CI runs, only during releases. This is, of course, a bad time to find out that something's not working properly.

We need to take a survey and ensure that everything is being built, all the time. Coming up with a checklist of things to update as new crates, packages, etc. are added would be nice for the future, as well.

**Comment by mwrock** [comment]
closed by #4202
