### ISSUE TITLE
Add Kubernetes exporter to UI

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4213]
We're going to have the ability to link up to a running kubernetes cluster and deploy Habitat application updates using the Habitat Operator for Kubernetes. We should expose configuration settings in the UI so a user can give the information for their cluster and push updates to it. 

This will use exactly the same docker exporter we currently have, plus the kubernetes exporter piece. Images can be published to dockerhub &/or private dockerhub 

Info to gather: 
- dockerhub registry url 
- creds (same as now) 

Kubernetes specific cluster information will be: 
- api endpoint
- service account creds
- service account must have correct permissions to enable 
- builder will submit a habitat custom resource definition

cc @LiliC & team for more info/clarification

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #289](https://github.com/habitat-sh/builder/issues/289) via [**ZenHub**](https://www.zenhub.com/)
