### ISSUE TITLE
Node Scaffolding: Error messaging

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#4230]
`ERROR: A default proccess bin called 'web' could not be detected from a Procfile or package.json.`

Seems the error here is that the `package.json` file is lacking a start script, but that's not apparent from the error messaging. Probably should be more clear.

**Comment by eeyun** [comment]
Issue moved to [habitat-sh/core-plans #1181](https://github.com/habitat-sh/core-plans/issues/1181) via [**ZenHub**](https://www.zenhub.com/)
