### ISSUE TITLE
Node scaffolding: errors out if there are no node modules

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#4231]
>    02-basic-scaffolding: Installing vendored Node modules to /hab/pkgs/mgamini/02-basic-scaffolding/0.1.0/20171206184633/app/node_modules
> cp: cannot stat '/hab/cache/src/02-basic-scaffolding-0.1.0/node_modules': No such file or directory
>   02-basic-scaffolding: Build time: 0m9s
>   02-basic-scaffolding: Exiting on error

Seems to me that there may be scenarios in which users do not have any other modules installed, and thus lack a `node_modules` folder. We could either direct them to not use scaffolding, or modify scaffolding to handle the lack of folder. Thoughts?

**Comment by elliott-davis** [comment]
@mgamini is this still an issue?

**Comment by mgamini** [comment]
@elliott-davis I believe so. Will test tomorrow.
