### ISSUE TITLE
Codify incident process and communicate via blog post (and other ways of communicating?)

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#4239]
There is currently confusion about our incident process.

Today, we had an incident with Builder.  This was communicated on https://status.habitat.sh/, but nothing was communicated in the #incident channel in the Habitat slack.  This led to some confusion on the part of both community members and other chef staff - they were expecting to see communication in #incident.  We need to:
1) Codify whether we are communicating incidents only through status.habitat.sh and discussing/troubleshooting in a private channel 
2) Remove #incident from the Habitat Slack 
3) Communicate this through a blog post and whatever other medium is appropriate.

**Comment by schisamo** [comment]
It would also be nice to see discussion during the actual incident to take place in #incident (vs a private channel) so everyone can follow along.

**Comment by eeyun** [comment]
I've gone ahead and updated the [wiki incidents response doc](https://github.com/habitat-sh/habitat/wiki/Incidents) to to match the suggestion's covered here! If we feel the need to write a blog post to cover this we definitely can do so. We've done so in the past and I haven't found that it's gotten much traction. So perhaps this is something we should pin to #general?
