### ISSUE TITLE
Binlinking of symlinks fails in Docker exporter chroot environment

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4243]
In order to create a Docker container image from a Habitat package, we set up a chroot environment in which to assemble what will become the filesystem of the image. To ensure that the relevant binaries are easily accessible, we binlink all the packages. If any of the binaries
to be binlinked are actually symlinks, though, the exporter errors out with a failure to create the binlink.

The problem can be observed with packages that depend on the `core/openresty` package (`core/openresty/1.11.2.2/20171025112347`, specifically). In this package the `/hab/pkgs/core/openresty/1.11.2.2/20171025112347/bin/openresty` binary is actually a symlink to `/hab/pkgs/core/openresty/1.11.2.2/20171025112347/nginx/sbin/nginx`. When we try to generate a binlink, we follow symlinks, but in the context of the Docker exporter's chroot environment, this link resolves to a location *outside* of the chroot. The only way that the export can succeed is if the package in question has been installed on the system performing the export. This would ensure that the link destination actually exists. 

(It should be noted that in the generated container, the link will resolve properly; this is really an issue of container generation.)

I believe that if we end up traversing a symlink in the export process, we can perform path transformations to try and resolve it within the chroot (which we do already to find binaries on path entries). If it resolves properly, then we can continue; otherwise we should truly fail.

**Comment by elliott-davis** [comment]
Closing in favor of #4847
