### ISSUE TITLE
Blog tagging not working

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4254]
If I click on the "Windows" tag it is not showing every blog post tagged with "Windows." This is a big content discoverability problem - I am finding articles only through stubornness & because I know they exist, other users will not be able to dig them up. 

Reproduce: 
Click "Windows" 

This blog doesn't show up, even tho it's tagged with Windows: https://www.habitat.sh/blog/2017/08/Habitat-plans-for-net-full-iis-apps/

**Comment by ryankeairns** [comment]
It appears the tagging is considering lowercase and uppercase tags as being separate. As a short-term fix, I'll go through and lowercase all tags on existing posts.
