### ISSUE TITLE
Create style guide for habitat.sh site content submissions

### ISSUE THREAD

**Issue by davidwrede** [habitat-sh/habitat#4259]
This is definitely long overdue, but with more individuals writing content, there's a real need to have a style guide/cheatsheet for any content that goes in places like `/tutorials`, `/docs`, and to a certain extent `/blog`.

It'll cover things like:

- Tone and voice
- Heading capitalization style
- Other fun writing subjects

**Comment by tashimi** [comment]
Looks like Dave didn't get this done, so closing this out.
