### ISSUE TITLE
[builder UI]Unable to re-trigger the container registry settings modal when canceled/dismissed

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4263]
Currently, when a container registry is selected from the list, a container registry settings modal pops up and allows a user to fill in necessary information for the selected registry, see below:
 ![image](https://user-images.githubusercontent.com/9401459/33746230-c2605cfa-db70-11e7-809d-630963b16d21.png)
However, if the settings table is left unfilled and dismissed by clicking on the cancel button or anywhere outside the modal, a user would be trapped in this state with no hint about how to proceed (save connection button is disabled, and there is no information about what's wrong) :
![image](https://user-images.githubusercontent.com/9401459/33746235-cc9fa02c-db70-11e7-95e9-fd508c7fcc47.png)
If the setting for the container registry must be filled before saving the connection, then there should be instructions about the what's missing, and a control that allow the user to re-trigger the setting modal (currently you can re-trigger it by toggling the radio button twice, but it's not what  radio buttons should normally be used for).

**Comment by cnunciato** [comment]
@apriofrost This is a good fine. The UX we have now is a little imperfect, and we'll probably come back to it once we have proper support for running multiple exports, but I can definitely make this work by deselecting the radio and allowing it to be clicked again. Thanks for spotting it!

**Comment by apriofrost** [comment]
Cool. Sounds a good workaround! Thanks @cnunciato !
