### ISSUE TITLE
[STABILITY] workers losing ens4 network, not able to recover 

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4264]
We're seeing workers in prod (and acceptance) lose the ens4 network

```
Dec 08 01:23:45 ip-10-0-0-242 hab[18939]: builder-worker.live(O): FATAL: Could not find network interface ens4
```

Checking the IP address:
```
root@ip-10-0-0-242:~# ip address show dev ens4 | grep 'inet '
Device "ens4" does not exist.
```

We need to figure out a more robust way to apply the ens4 interface.

**Comment by fnichol** [comment]
I'm going to look at only setting up the network namespace at worker start rather than around each build activity.
