### ISSUE TITLE
[UI nitpick] Wording on pagination button is incorrect

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#4269]
This is a small nitpick.  You can close it as E_PEDANT if you want :D.

<img width="383" alt="screen shot 2017-12-08 at 4 22 05 pm" src="https://user-images.githubusercontent.com/852371/33774802-5ecdf386-dc34-11e7-85aa-ee00c664c754.png">

Technically that button doesn't show me 220 more.  It shows me 50 more of the 220 unshown packages.

**Comment by cnunciato** [comment]
Ah, you're right, this is weird. Easy enough to just change that to 50.

**Comment by cnunciato** [comment]
Turns out this is an actual bug! Thanks for spotting it. Fix on the way.
