### ISSUE TITLE
UX mobile view on blog: tags too busy 

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4273]
The mobile view of habitat.sh/blog forces you to scroll through all the tags instead of showing you the blog content. We should probably just remove the list of tags for the mobile view unless we can figure out a better mobile template where they are actually useful and not annoying. 

![image](https://user-images.githubusercontent.com/719646/33782318-d8f1bfb0-dc1d-11e7-8182-4ef9fee2375f.png)

cc @apriofrost @ryankeairns

**Comment by cnunciato** [comment]
This looks done. Closing.
