### ISSUE TITLE
Docker tags not honored during publish

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4274]
When connecting a plan to the Build Service, you can enable publishing to Docker Hub on step 2. Upon selecting your integration, a modal appears that allows you to select from a set of predefined tags (presented as checkboxes). Regardless of which tag combinations you select, the resulting container image shows all 3 default tags on your Docker Hub.

Settings:
<img width="586" alt="screenshot 2017-12-08 14 05 24" src="https://user-images.githubusercontent.com/446285/33783115-eb478e62-dc20-11e7-8098-60a7ef695673.png">

Resulting tags:
<img width="952" alt="screenshot 2017-12-08 14 05 41" src="https://user-images.githubusercontent.com/446285/33783131-fa25d93e-dc20-11e7-9acf-4bd5f951c67b.png">

**Comment by cnunciato** [comment]
I've verified the data's going into the DB correctly here, so it looks like the API and UI are doing the right thing.  @elliott-davis or @fnichol any ideas? Could the worker not be receiving those booleans properly through the `DockerExporterSpec` struct?

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #83](https://github.com/habitat-sh/builder/issues/83) via [**ZenHub**](https://www.zenhub.com/)
