### ISSUE TITLE
Render RAML docs into Habitat.sh docs

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4293]
We currently have RAML rendered docs for API endpoints, etc., that aren't making it into our website/docs page. We should fix this!

We'll need to render RAML docs and then include those renderings on the website.

I would propose adding an "API Docs" headline to the sidebar, and a sensible main redirect, i.e. habitat.sh/docs/api

![image](https://user-images.githubusercontent.com/719646/33860718-f935d48c-de8e-11e7-9662-cb2df7ded438.png)

**Comment by jonlives** [comment]
👍 would love to see this!

**Comment by bl4ckcontact** [comment]
Would really love to see this as well. In the meantime, what's the best way to get the current URI's from the codebase?
