### ISSUE TITLE
Suggest a set of API endpoints and responses for notifications

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#4294]
Based on existing designs in Builder UI, the notifications APIs should support:

* Listing all recent (e.g., most recent 50) notifications for a given user, grouped by origin
* An ability to page through notifications for a given user within an origin
* Deleting all notifications for a given user, irrespective of origin
* Deleting all notifications for a given user within an origin
* Deleting an individual notification

**Comment by cnunciato** [comment]
Additional details in #4036.

**Comment by cnunciato** [comment]
All right, I think this is in good enough shape to start talking about:

https://gist.github.com/cnunciato/e9e9db16e50803326c68014e809c66f5

**Comment by raskchanky** [comment]
@cnunciato I left a comment on your gist

**Comment by reset** [comment]
@cnunciato this looks like an excellent set of APIs to start by. Do you think we need an "acknowledge one" (delete one) as well?

**Comment by chefsalim** [comment]
@cnunciato I left a comment on the gist as well - this also brings up a bunch of architectural questions, to be tackled orthogonally perhaps.

**Comment by cnunciato** [comment]
Closing this as it seems we've captured enough feedback to get started.
