### ISSUE TITLE
Add Docker (install) as a pre-requisite for the tutorials

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4302]
The current 'Build Your Web App' tutorial (all 3 languages), does not state the need to install Docker up front. Later in the tutorial, this becomes necessary to enter the Habitat Studio.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Add some information and a link to install Docker on your machine at the beginning of https://www.habitat.sh/tutorials/build-your-own/ruby/
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by rsertelon** [comment]
I think this is not relevant anymore as docker installation is required in https://www.habitat.sh/demo/packaging-system/steps/2/
