### ISSUE TITLE
Getting Started Guides: Ruby

### ISSUE THREAD

**Issue by mgamini** [habitat-sh/habitat#4308]
Build the following example repos with both beginning and completed states for the following:

- [ ] Basic app with Rails
- [ ] Basic app with Rails & scaffolding
- [ ] Basic app with Sinatra
- [ ] Basic app with Sinatra & scaffolding
- [ ] Habitize an existing app

**Comment by cnunciato** [comment]
@ryankeairns Is this still something we want to do? I suspect we might want to close this for now and post a new issue once we have a better sense of the near future of docs.

**Comment by ryankeairns** [comment]
that's fine, no immediate plans here.
