### ISSUE TITLE
Create a hab command to expose various basic data about a package

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4309]
Sometimes it can be useful to programmatically extract information about a `.hart` file from the file directly, without having to install it or otherwise perform arcane shell scripting to get what you need.

For example, we allow hyphens in an origin name, but when generating `.hart` file names, we just join the origin, name, version, and release together using hyphens, making it difficult to extract information from a filename. Furthermore, you could just name the package `foo.hart` and bypass that altogether :)

We have a `hab pkg header` command that extracts signing information from a `.hart` file; it would be nice to have a similar command that could at least extract the identifier components from a file and expose them in a way that is easily amenable to shell scripting.

As a fun side note, here is how you would currently extract the origin name from an arbitrary `.hart` file:

```bash
#!/bin/bash

HART=${1}
IDENT_FILE=$(tail -n+6 ${HART} | tar --list --xz | grep IDENT)
tail -n+6 ${HART} | \
    tar --extract --xz --to-stdout ${IDENT_FILE} | \
    cut -f1 -d"/"
```

Doable, but clearly not the greatest experience.

**Comment by jeremymv2** [comment]
@christophermaier I think #4814 satisfies this issue.

**Comment by christophermaier** [comment]
@jeremymv2 indeed it does; thanks for that!
