### ISSUE TITLE
Builder webhook - fix case where plan file is in a "habitat" folder

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4323]
This issue deals with one specific case - where there is no .bldr.toml file, and the plan.sh file for the repo is in a "habitat" folder.

Under these conditions, and file change that is not inside of the "habitat" folder will not trigger an automated Builder build.

The reason is that the default rule requires a changed file to fall under the plan path folder.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #86](https://github.com/habitat-sh/builder/issues/86) via [**ZenHub**](https://www.zenhub.com/)
