### ISSUE TITLE
.bldr.toml should allow users to auto-promote to channels other than unstable

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4328]
This is expected/documented behavior but apparently doesn't exist in the code base. 

## Additional channel promotion

-You can specify a list of additional channels that packages should automatically publish to. By default, software is only published to the `unstable` channel.

-```toml
-# .bldr.toml
-[hab-launcher]
-channels = ["stable"]
-```

**Comment by tashimi** [comment]
- add behavior
- re-add docs removed in #4327

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #99](https://github.com/habitat-sh/builder/issues/99) via [**ZenHub**](https://www.zenhub.com/)
