### ISSUE TITLE
Run habitat as windows service: next steps

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4345]
The windows service is now self contained at https://github.com/habitat-sh/windows-service. The readme should explain how it behaves and can be installed.

Before this can be "publicized" the following needs to happen:

- [x] Issue a new hab client launch that contains the fix for running under Local System
- [x] Upload and promote the windows-service package

Follow up from #2766

**Comment by mwrock** [comment]
This was already done as part of https://github.com/habitat-sh/windows-service and has been promoted. I just neglected to close it!
