### ISSUE TITLE
Improve Builder search results

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4347]
Currently on the `hab` cli you can use `hab pkg provides <foo>` to find a utility or tool you want and then download the appropriate `core` package. The Builder search UI should also provide this level of information, i.e.: 

Search for: touch

Returns: `core/coreutils` 

Adding something along the lines of "The following packages contain the utility/library `touch`" to packages that are returning because of the utility they contain rather than their actual name will be important to the results text for added context. 

Here: https://bldr.habitat.sh/#/pkgs/core

**Comment by cnunciato** [comment]
It looks like `hab pkg provides` searches only locally installed packages, rather than packages residing in the Builder depot, and we don't currently store package contents in the database. We should totally do this, though -- it'll just take some effort to figure out how to attack it.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #87](https://github.com/habitat-sh/builder/issues/87) via [**ZenHub**](https://www.zenhub.com/)
