### ISSUE TITLE
Add clarification around copyable commands

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#4361]
The commands in the Builder package sidebar currently only work under certain scenarios. We might want to consider adding some explanatory text or moving them to another location to better explain how and where to use them.

![image](https://user-images.githubusercontent.com/274700/34226402-6f84af64-e57e-11e7-9289-8ec9ef98c074.png)

cc @ryankeairns

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #293](https://github.com/habitat-sh/builder/issues/293) via [**ZenHub**](https://www.zenhub.com/)
