### ISSUE TITLE
Stopping services in a container studio is not gracefully terminating powershell

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#4363]
powershell does not appear to be intercepting the ctrl+c signal when stopping a service in a windows container studio. Instead the service is forcefully terminated. If the service has cleanup code, that is not being run.

**Comment by mwrock** [comment]
Investigating further, sending the `ctrl+break` event via `GenerateConsoleCtrlEvent` in a container (which is how we "gracefully" kill a service) causes a `ERROR_INVALID_FUNCTION` error to occur. I don't know if this is due specific to a container of Windows Server Core which is the OS non-nano containers run.

Some preliminary googling did not yield any useful info.

**Comment by mwrock** [comment]
I'm not able to reproduce this any longer. It is possible that this was "fixed" in a windows container release after this was opened.

**Comment by susundberg** [comment]
Sorry to spam on bit of outside of the original scope, but this is like only reference to the situation to what i encountered (python3 inside dockers, tries to do os.kill and gets the error) 

For the record; what windows container were you using? I am having this issue (again?!) with  ```mcr.microsoft.com/windows/servercore:20H2```

Again sorry for the disruption,

**Comment by mwrock** [comment]
not sure @susundberg but it would have been whatever was `latest` in 2017 before they did away with `latest`.
