### ISSUE TITLE
RFC: Habitat built packages without the Supervisor

### ISSUE THREAD

**Issue by coderanger** [habitat-sh/habitat#4368]
Opening this to start a discussion, so consider this idea a bit nebulous so far. Basically I love hab studio, but as a k8s user I don't have a ton of need for hab-sup. Being able to build plain ol' images without the Habitat runtime would be a very nice alternative to `docker build`. I could certainly just use things as-is and ignore hab-sup, but it would be nice to not have the extra moving piece. This would mean a few Habitat plan features (like run-time templating) wouldn't work, but it's still a big leg up over `docker build`.

**Comment by eeyun** [comment]
This something we've had a bunch of conversations about over the last year. I think the general feeling on it most recently is that we'd prefer not to do something like that - BUT, thats not a 100% consensus across the community/core-team and I think a feature like this is something that others have also asked about so we ABSOLUTELY should discuss it further with the wider community.

I've updated the issue to include an RFC label and will post about it in the #announcements channel after this week's triage! 

Thank you for opening this issue @coderanger!

**Comment by bdangit** [comment]
Other things that the user may forgo is the ability to expose a health check via port 9631 (which I thought was a nice feature for `k8s` users), a process that tries its best to keep the processes spawned from it up and other nice runtime hooks for managing application health. 

Of course those features are nice when running and maintaining a service. 

In a lot of my use-cases, we use hab to help us build and contain our application.  We value the dependency management and isolation features. When we do run our applications which are really just command line tools, we just use `hab pkg binlink` and then we can use our tool as desired on any Linux machine. Thinking forward a bit we can easily export Docker containers so we can then run our tooling in any Docker machine whether on Linux or Windows.  In these cases, we don’t need to bloat our images with `hab-sup`.

Perhaps in the case where it is really desired not to have these, then we should allow the community to make a `hab-sup`-less exporter.  Or some how offer a `hab-sup` stub.

**Comment by coderanger** [comment]
Kubernetes already has strong restart-on-fail management and health check systems, so Habitat implementing those gets me very little.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #88](https://github.com/habitat-sh/builder/issues/88) via [**ZenHub**](https://www.zenhub.com/)
