### ISSUE TITLE
HAB_BLDR_CHANNEL and "Package not found" / builder builds working currently?

### ISSUE THREAD

**Issue by schu** [habitat-sh/habitat#4371]
Since earlier this week, we encounter the following early error when building packages:

```
worker.1    | _ The package does not have any versions in the specified channel.                                                                                              
worker.1    | _ Did you intend to install one of the folowing instead?                                                                                                        
worker.1    | _   core/hab-backline/0.51.0/20171219022621 in channel stable                                                                                                   
worker.1    | _   core/hab-backline/0.51.0/20171219022621 in channel unstable                                                                                                 
worker.1    | ___                                                                                                                                                             
worker.1    | ___ Package not found                                                                                                                                           
worker.1    | ___ 
worker.1    | DEBUG:habitat_builder_worker::runner::studio: completed studio build command, status=ExitStatus(ExitStatus(256))
```

This seems to be because builder attempts to install the packages from a channel custom to the build (`bldr-877267041537662976`):

```
worker.1    | DEBUG:habitat_builder_worker::runner::studio: setting studio build command env, HAB_BLDR_CHANNEL=bldr-877267041537662976
[...]
worker.1    | DEBUG:habitat_http_client::api_client: GET http://localhost:9636/v1/depot/channels/core/bldr-877267041537662976/pkgs/hab-backline/0.51.0/latest with ApiClient { endpoint: "http://localhost:9636/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 6
0, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "http", user_agent_header: UserAgent("hab/0.51.0/20171219021329 (x86_64-linux; 4.10.0-19-generic)") }
[...]
```

On Slack we were pointed to https://github.com/habitat-sh/habitat/pull/4289/files#diff-98ec64e3f381a5ccde4f4506db6aae9cL206 - reverting that particular line or explicitly setting it to stable (like below) doesn't seem to make a difference though:

```
diff --git a/components/studio/libexec/hab-studio-type-default.sh b/components/studio/libexec/hab-studio-type-default.sh
index 0682aeb5e..3dc9bb50f 100644
--- a/components/studio/libexec/hab-studio-type-default.sh
+++ b/components/studio/libexec/hab-studio-type-default.sh
@@ -203,7 +203,7 @@ PROFILE_ENTER
 
 _hab() {
   # We remove a couple of env vars we do not want for this instance of the studio
-  $bb env FS_ROOT=$HAB_STUDIO_ROOT HAB_CACHE_KEY_PATH= $hab $*
+  $bb env FS_ROOT=$HAB_STUDIO_ROOT HAB_CACHE_KEY_PATH= HAB_BLDR_CHANNEL=stable $hab $*
 }
 
 _pkgpath_for() {
```

Any ideas what could be wrong / have changed?

I currently test on top of latest master, https://github.com/habitat-sh/habitat/commit/79ff23433081234745b69a85c6fceeddf1931f52, with https://github.com/kinvolk/habitat/tree/schu/vagrant

Thanks.

**Comment by schu** [comment]
```
worker.1    | ___                                                                                                                                                             
worker.1    | ___ Package not found                                                                                                                                           
worker.1    | ___ 
```
also can be found on bldr.habitat.sh, there Builder does fallback to stable though. Example:
```
[...]
» Installing core/go from channel 'bldr-878135229032407040'
∅ The package does not have any versions in the specified channel.
∅ Did you intend to install one of the folowing instead?
∅   core/go/1.9.2/20171026082055 in channel stable
∅   core/go/1.9.2/20171026082055 in channel unstable
✗✗✗
✗✗✗ Package not found
✗✗✗
   demo-service: Trying to install 'core/go' from 'stable'
» Installing core/go from channel 'stable'
↓ Downloading core/go/1.9.2/20171026082055
☛ Verifying core/go/1.9.2/20171026082055
[...]
```

**Comment by christophermaier** [comment]
Doing some preliminary sleuthing: going to leave notes here.

The current build of `core/builder-worker` running in production is version 6447, which after some Git trial and error, means it was built from b84e3bc0c692764fdd41b6e14b6b51932fbbf73b. According to @schu's comments above, this does _not_ exhibit the build failure that he is observing locally with more recent code.

**Comment by schu** [comment]
Log from a coworker's machine: https://gist.github.com/indradhanush/35865df826654ba28af924c3f2be3761

**Comment by christophermaier** [comment]
@schu FYI, we are able to reproduce this in our acceptance environment.

**Comment by schu** [comment]
> FYI, we are able to reproduce this in our acceptance environment.

Good to know, thanks!

**Comment by christophermaier** [comment]
Some changes were made recently to ensure that we could generate fully-unstable studio artifacts in order to test prior to release. However, it appears that the implementation had the unintended side effect of leaking over into the normal worker build process, causing the studio to look for `core/hab-backline` in the build channel rather than stable. The studio setup code does not have fall-back logic that `core/hab-plan-build` does, which results in these early-terminating builds.

The workers in production do not have this version yet, and are unaffected.

**Comment by indradhanush** [comment]
@christophermaier Is there a workaround for this in the meantime?
I've tried undoing the change to  `components/studio/libexec/hab-studio-type-default.sh` introduced [here](https://github.com/habitat-sh/habitat/commit/0841ca889c221c439553431fea092850e354ddd6#diff-98ec64e3f381a5ccde4f4506db6aae9cL206) but was unsuccessful.

**Comment by mwrock** [comment]
@indradhanush I have a PR I'm about to submit to fix this. It does involve changing that code above however to "experience" the fix requires rebuilding the studio as well. So if you want an immediate workaround, you want to revert that one line and rebuild the studio via `hab pkg build components/studio`. That should create a new 0.52.0-dev studio. Now I'm uncertain what version of hab that the worker will be using in a local builder (I'm in the midst of testing this now). If its not, 0.52.0-dev then the above will not "take". Another method would be to revert that line in the installed version of the studio that the worker is using by directly editing `/hab/pkgs/core/hab-studio/<version>/<rel>/bin/hab-studio`.
