### ISSUE TITLE
[www] Broken secondary button style on community page 

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4374]
See Community page https://www.habitat.sh/community/ , under Product Roadmap and GitHub Project Tracker:

Secondary button labels not visible on the white background 
![image](https://user-images.githubusercontent.com/9401459/34272113-dd367d88-e643-11e7-9307-a196b7e9d144.png)
![image](https://user-images.githubusercontent.com/9401459/34272160-134c5a64-e644-11e7-9b81-021c00759209.png)

See reference button style on white background on the Pricing page: https://www.habitat.sh/pricing/

**Comment by ryankeairns** [comment]
Likewise, the 'next page >>' link at the bottom of the blog index page is also lacking contrast, so
I'll fix these together.

![screenshot 2017-12-22 08 42 16](https://user-images.githubusercontent.com/446285/34301893-24940596-e6f4-11e7-9dda-2dc1eb79e24b.png)

**Comment by ryankeairns** [comment]
... and the Pricing page had an orange on orange style, so I set out to make that the same as these (dark blue text), but found that section redundant with the one below it (both community related). Instead, I removed the white 'contact us' box on the community page and added a second GitHub button to the section below it.

Before:
![screenshot 2017-12-22 08 52 18](https://user-images.githubusercontent.com/446285/34302218-a2c04cda-e6f5-11e7-8ebf-43115c9bcb14.png)


After:
![screenshot 2017-12-22 08 54 23](https://user-images.githubusercontent.com/446285/34302248-bcdfc4c4-e6f5-11e7-94b2-6d7db9e18f1d.png)

**Comment by ryankeairns** [comment]
I've opened a PR for this one, it's Ready for Review - #4379
