### ISSUE TITLE
Update strategies don't work as expected when using Docker

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4375]
When starting a package via Docker and applying an update strategy (e.g. `docker run -it -p 8000:8000 myorigin/mypackage --strategy at-once`), the supervisor does not update the package when a new version is promoted to the **stable** channel.

I walked through this with @fnichol and he pointed out where the issue lies (see screenshots). Essentially, when the container starts up the fully qualified path is used, whereas the supervisor needs to watch for updates to the myorigin/mypackage (not the myorigin/mypackage/version/release). In turn, it does not see the package as updated when new promotions to stable occur.

As Fletcher put it, we need to lop off the version and release.

**/hab/sup/default/specs/sample-node-app.spec**
![screenshot 2017-12-20 14 40 36](https://user-images.githubusercontent.com/446285/34273546-76a9925a-e65a-11e7-98cd-e8aeb440f1bf.png)

**/init.sh**
![screenshot 2017-12-20 14 42 52](https://user-images.githubusercontent.com/446285/34273547-76c40e28-e65a-11e7-96f9-67b0cb606cac.png)

**directories where spec and init.sh live**
![screenshot 2017-12-20 14 52 58](https://user-images.githubusercontent.com/446285/34273549-76f8944a-e65a-11e7-9458-300b71769055.png)

FWIW, the workaround is to use `docker run -it -p 8000:8000 myorigin/mypackage start myorigin/mypackage --strategy at-once` as the part beginning with `start...` overrides the fully qualified default path.
![screenshot 2017-12-20 14 44 58](https://user-images.githubusercontent.com/446285/34273548-76e0c77a-e65a-11e7-8d4b-9af0536f409d.png)

**Comment by ryankeairns** [comment]
@christophermaier Here's the Docker issue I mentioned at standup.

**Comment by christophermaier** [comment]
@ryankeairns can you post the exact commands you used to export your image? I'm not able to replicate this locally.

**Comment by ryankeairns** [comment]
@christophermaier 

Here are the steps:

`hab studio enter`
`hab pkg export docker ryankeairns/sample-node-app`
`exit`
`docker run -it -p 8000:8000 ryankeairns/sample-node-app --strategy at-once`
[in a separate terminal window, I check which origin/pkg/version/release is running; it matches my latest stable]
`docker exec -it 49870246187a hab sup status`
[go to https://bldr.habitat.sh/#/pkgs/ryankeairns/sample-node-app]
click on ‘Build latest version’
once that completes, I click on ‘promote’ in the Builder web app
then I should see the sup log (the output of my `docker run`) update in my terminal (within 60 secs) to the latest stable version that I just promoted… but it does not update.

On the contrary, if I don’t export it to docker and just `hab sup start...` the package directly in the studio, then tail the sup log, I do see it update according to the defined strategy (at-once) after I promote a new build to stable.

**Comment by christophermaier** [comment]
With the 0.56.0 release, Docker images use the `<ORIGIN>/<PACKAGE>` form of the identifier, eliminating this problem.
