### ISSUE TITLE
Debug output in studio corrupts stdout

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4380]
In some places in `hab-studio`, we capture STDOUT of function calls as variables which we later manipulate. If those function calls end up generating calls to `debug()`, it can corrupt STDOUT, because messages are sent there instead of STDERR.

Debug messages should always be sent to STDERR to prevent this, and a survey of the rest of the code should be made to ensure no other inappropriate logging is occurring.

**Comment by fnichol** [comment]
Correct: `debug()` has incorrect behavior and should behave the same as the implementation of [`warn()`](https://github.com/habitat-sh/habitat/blob/21571e24577bf390fd67e7657048644e35f8248b/components/plan-build/bin/public.sh#L56). That's probably on me--I never used `debug()` myself and relied on the output of `set -x` instead. As a result I never updated the `debug()` implementation.

**Comment by fnichol** [comment]
And there is no equivalent of `debug()` in the Studio codebase for the reason above (use `set -x` instead in the general case which already emits to `stderr`)

**Comment by christophermaier** [comment]
@fnichol Recent addition: https://github.com/habitat-sh/habitat/commit/6242f72a023cd4c4790f844d7d6b66bc7af93f47

**Comment by christophermaier** [comment]
Though judging by that commit, it looks like this behavior has been there for a while 🤔

**Comment by fnichol** [comment]
I'd argue that this function need to go--you can get the same information from `set -x` and the originally flawed implementation is now travelling 😦

**Comment by fnichol** [comment]
Hm, it should also *not* key off `RUST_LOG`, only ever `DEBUG` to be consistent
