### ISSUE TITLE
[builder ui] Update label 'Tutorial' to 'Learn' in bldr global nav

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4384]
The www site global navigation has been updated to replace 'tutorial' with 'learn', we should do the same for the bldr.habitat.sh site to keep it consistent.
![image](https://user-images.githubusercontent.com/9401459/34310102-5ca4478c-e70a-11e7-8c81-cb47222fc7ac.png)

**Comment by rsertelon** [comment]
Seems to be fixed already by https://github.com/habitat-sh/habitat/pull/4350/files#diff-d8c14ed831b50d3ba73f902f9b0fea2aR27

**Comment by apriofrost** [comment]
@rsertelon I'm still seeing "Tutorials" in the header on the live site though. @ryankeairns any idea on this?

**Comment by rsertelon** [comment]
On acceptance it seems to be all good. I think it just lack prod deployment ;)

**Comment by ryankeairns** [comment]
Yeah, that's correct, changed but not yet deployed. We have some other web UI changes in the works this week, so this should all get updated very soon.

**Comment by christophermaier** [comment]
Closing, as it appears to no longer be applicable with the new design.
