### ISSUE TITLE
`hab pkg build -D` does not work on headless systems due to `-i ` flag to Docker`

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#4394]
I think this issue has been discussed informally with @eeyun before. This is on Ubuntu 14 as a Jenkins build using Habitat 0.51.0.

To reproduce, set up some build in a script like
```
hab pkg build -D /foo/bar
```
and run on a headless system (in our case, a Jenkins job). You should see a failure about not having a tty.

**Comment by raskchanky** [comment]
As of the latest release (0.79.0), you should be able to augment your call like so `hab pkg build -D --non-interactive --no-tty /foo/bar` and have it work correctly on a headless system.  I'm going to close this for now, but if this doesn't resolve this issue, please reopen it, and we can take a fresh look.

**Comment by raskchanky** [comment]
One more update on this.  I just merged https://github.com/habitat-sh/habitat/pull/6404 which means that after the next release (`0.80.0`) you shouldn't need the flags I mentioned above, or any special flags at all.  It should just do the right thing.  If it doesn't, please let me know.
