### ISSUE TITLE
0.51.0 compilation fails loading source for ipc-channel

### ISSUE THREAD

**Issue by TrevorBramble** [habitat-sh/habitat#4396]
I'm trying to update a [Habitat package](https://aur.archlinux.org/packages/habitat/) for Arch and it doesn't get very far before failing on something related to ipc-channel.

Is this related to #4364? Should we have a 0.51.1 tag to make this fix available?

```sh
+$ makepkg
==> Making package: habitat 0.51.0-1 (Fri Dec 29 15:51:42 EST 2017)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning habitat git repo...
Cloning into bare repository '/home/trevor/code/aur/habitat/habitat'...
remote: Counting objects: 67645, done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 67645 (delta 13), reused 15 (delta 4), pack-reused 67603
Receiving objects: 100% (67645/67645), 76.61 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (45931/45931), done.
==> Validating source files with sha256sums...
    habitat ... Skipped
==> Extracting sources...
  -> Creating working copy of habitat git repo...
Reset branch 'makepkg'
==> Starting build()...
sh -c 'cd components/hab && cargo build'
    Updating git repository `https://github.com/iron/urlencoded`
    Updating git repository `https://github.com/erickt/rust-zmq`
    Updating git repository `https://github.com/dnaq/sodiumoxide`
    Updating git repository `https://github.com/habitat-sh/frank_jwt`
    Updating git repository `https://github.com/habitat-sh/ipc-channel`
error: failed to load source for a dependency on `ipc-channel`

Caused by:
  Unable to update https://github.com/habitat-sh/ipc-channel?branch=hbt-windows#2d085faf

To learn more, run the command again with --verbose.
make: *** [Makefile:235: build-hab] Error 101
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by eeyun** [comment]
Hmm It's possible we broke something with #4364 but it actually just looks like your build is pulling the old sha from that version pin. Is it possible that @fnichol's change the pin wasn't getting picked up before this build was attempted?

**Comment by TrevorBramble** [comment]
@eeyun hey! Which SHA? The one in the error, `2d085faf`? Wherever that is picked up, it's caused by something done on my end. All I do (for this package) is update the version number, which corresponds to version tags here on GitHub. ([example](https://aur.archlinux.org/cgit/aur.git/commit/?h=habitat&id=30c55de8866a416edb539a166a6b250155373329)) Everything is based on that tag.

All build artifacts and intermediary files are wiped between builds, and I just attempted this build again with the same failure.

**Comment by qhartman** [comment]
I ran into this problem today trying to build the 0.51 tag as well. I can build current head (38be6fde) just fine though.

**Comment by elliott-davis** [comment]
Clearing your cargo cache or running a cargo update should fix this issue

**Comment by TrevorBramble** [comment]
@elliott-davis I found and removed a `~/.cargo` directory, removed `src` from prior build attempts, and tried again. Same failure.

**Comment by eeyun** [comment]
@TrevorBramble AUR is showing a 0.53 release available. Do you mind if we close this out? Or is there a need to continue supporting a previous release here? 

It sound from our discussion like version 51 might not be able to build... maybe ever.

**Comment by TrevorBramble** [comment]
@eeyun Yes. There's a larger issue here, that minor releases of Habitat aren't tagged as such, but we can call WONTFIX on this one and still walk away friends. =^)
