### ISSUE TITLE
[Stability] Github related front end errors

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4399]
Seeing a few github related errors:
1. Failure to fetch project
2. Rate limit exceeded
3. Unable to deserialize / bad response 

-- Logs begin at Wed 2017-11-29 22:14:22 UTC, end at Tue 2018-01-02 18:43:59 UTC. --
Jan 02 15:50:20 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 15:55:06 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: unable to retrieve bldr.toml, Received a non-200 response, status=403 Forbi
dden, response={"documentation_url": "https://developer.github.com/v3/#rate-limiting", "message": "API rate limit exceeded for installation:56215."}
Jan 02 16:13:55 ip-10-0-0-147 hab[121944]: builder-api.live(O): INFO:habitat_depot::server: File added to Depot at /hab/svc/builder-api/data/pkgs/3d/2e/ryan-sample-node-app-
1.0.3-20180102161229-x86_64-linux.hart
Jan 02 16:21:41 ip-10-0-0-147 hab[121944]: builder-api.live(O): INFO:habitat_depot::server: File added to Depot at /hab/svc/builder-api/data/pkgs/85/cb/ryan-sample-node-app-
1.0.3-20180102162023-x86_64-linux.hart
Jan 02 16:25:38 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): ERROR:iron::iron: Error handling:
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): Request {
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     url: Url { generic_url: "http://backend/v1/depot/pkgs/core/jdk8/versions" }
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     method: Get
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     remote_addr: V4(127.0.0.1:36536)
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     local_addr: V4(0.0.0.0:9636)
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): }
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): Error was: NetError(code: SESSION_EXPIRED msg: "ss:session-get:0")
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): ERROR:iron::iron: Error handling:
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): Request {
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     url: Url { generic_url: "http://backend/v1/projects/core/jdk8/jobs" }
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     method: Get
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     remote_addr: V4(127.0.0.1:36538)
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O):     local_addr: V4(0.0.0.0:9636)
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): }
Jan 02 16:31:25 ip-10-0-0-147 hab[121944]: builder-api.live(O): Error was: NetError(code: SESSION_EXPIRED msg: "ss:session-get:0")
Jan 02 17:16:23 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 17:16:59 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 17:27:33 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 17:27:52 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 17:29:09 ip-10-0-0-147 hab[121944]: builder-api.live(O): INFO:habitat_depot::server: File added to Depot at /hab/svc/builder-api/data/pkgs/f8/21/chef-inspec-1.48.10-2
0180102172806-x86_64-linux.hart
Jan 02 17:30:12 ip-10-0-0-147 hab[121944]: builder-api.live(O): INFO:habitat_depot::server: File added to Depot at /hab/svc/builder-api/data/pkgs/df/cb/adamleff-inspec-profi
le-builder-test-1-0.1.0-20180102172928-x86_64-linux.hart
Jan 02 17:42:35 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:habitat_builder_api::github: Failed to fetch project, [err: ENTITY_NOT_FOUND, msg: vt:origin-project-get
:0]
Jan 02 17:46:04 ip-10-0-0-147 hab[121944]: builder-api.live(O): INFO:habitat_depot::server: File added to Depot at /hab/svc/builder-api/data/pkgs/2f/c6/chef-authn-service-0.
1.0-20180102174520-x86_64-linux.hart
Jan 02 17:47:38 ip-10-0-0-147 hab[121944]: builder-api.live(O): INFO:habitat_depot::server: File added to Depot at /hab/svc/builder-api/data/pkgs/1e/e5/chef-automate-gateway
-0.1.0-20180102174653-x86_64-linux.hart
Jan 02 17:51:56 ip-10-0-0-147 hab[121944]: builder-api.live(O): WARN:builder_http_gateway::http::middleware: Bad response body from GitHub, Serialization(ErrorImpl { code: E
xpectedSomeValue, line: 1, column: 1 })

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #89](https://github.com/habitat-sh/builder/issues/89) via [**ZenHub**](https://www.zenhub.com/)
