### ISSUE TITLE
[feature] Increased visibility of failed builds

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#4401]
For a large origin (such as core-plans), it would be helpful if there was a way to find out about failed bldr builds. Some possibilities include:

- Email notification for failed builds to a configurable notification list
- Slack notification for failed builds
- Some sort of "dashboard" view that would show any failing builds.

**Comment by eeyun** [comment]
Yeah this is another excellent one. This might roll up into #4402 but I think we'll track them separately since they have slightly different areas of concern! Thanks @stevendanna !

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #90](https://github.com/habitat-sh/builder/issues/90) via [**ZenHub**](https://www.zenhub.com/)
