### ISSUE TITLE
[feature] Dashboard for current origin state

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#4402]
For a large origin (such as core-plans), it would be helpful if there was a way to get information about the overall state of packages in my origin in some sort of dashboard.  This dashboard could include things like:

- Plans with builds that are ready for promotion,
- Plans with failing builds,
- Perhaps other interesting facts about packages such as new reverse dependencies

**Comment by eeyun** [comment]
This would be super awesome and incredibly useful both inside of core-plans and outside of core-plans. Theres probably a lot to figure out here, but this is an excellent feature request.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #91](https://github.com/habitat-sh/builder/issues/91) via [**ZenHub**](https://www.zenhub.com/)
