### ISSUE TITLE
Sessionsrv migrations won't run in live

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#4403]
Migrations currently fail for sessionsrv in live. We suspect this is due to the transaction lock check that happens as part of the migration but so far we haven't been able to repro in dev or acceptance

**Comment by reset** [comment]
@elliott-davis @chefsalim and myself took a look at production today regarding this fix. We believe this is potentially fixed by #4160. Once that has been merged and tested we'll go to production and see if it resolves our issue and then close this out.
