### ISSUE TITLE
Notifications service

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4409]
We need a new service that will run as part of Builder that will receive notifications from various parts of Builder and store them for later processing.  It should also take whatever actions are necessary on the notifications in its data store.  Initially, we'll just be focused on email.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #92](https://github.com/habitat-sh/builder/issues/92) via [**ZenHub**](https://www.zenhub.com/)
