### ISSUE TITLE
Builds not working due to changed stderr log handling

### ISSUE THREAD

**Issue by schu** [habitat-sh/habitat#4410]
Since today (working on top of 81771d5126437b7a5ade50ab2b1fbf4059a877e9), my builds keep getting stuck. Nothing suspicious in the logs (I presume something is hanging/waiting in the `pipe` code). In the web UI this looks like

![hab-log](https://user-images.githubusercontent.com/366468/34566273-3a136ae6-f15e-11e7-8579-f3cce6508f4a.png)

Reverting https://github.com/habitat-sh/habitat/pull/4407 resolves the problem.

cc @elliott-davis

**Comment by elliott-davis** [comment]
Closed by: #4407

**Comment by schu** [comment]
@elliott-davis actually I had #4407 in my tree and for me reverting it make it work again. Did you mean to reference a different pull request?
