### ISSUE TITLE
Supervisor/Launcher should reap zombie processes

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#4412]
Sometimes parents die and leave their children orphaned. When this happens in the Habitat supervision tree, the process typically ends up owned by the launcher. If the launcher is owned by something like systemd, the zombies usually get reaped. However, in the case where the launcher is PID 1 the zombies live on for ever and eat your containers BRAINZ (causing it to crash). The launcher/supervisor should detect when it has zombied processes in it's tree and proactively reap them.

**Comment by irvingpop** [comment]
This would fix a known customer-impacting issue: https://github.com/habitat-sh/core-plans/issues/1099

**Comment by dmajere** [comment]
If its possible to vote for this one, then +1.
Cause this problem exists for more than a year, and I've reported it already twice.
