### ISSUE TITLE
`LD_LIBRARY_PATH` should default to `aggregate` type

### ISSUE THREAD

**Issue by smartb-pair** [habitat-sh/habitat#4419]
It seems that this variable defaults to the `primitive` type, but it seems to make more sense to assume the final value will be aggregated from several paths.

**Comment by bdangit** [comment]
What should this variable be set to?

**Comment by smartb-pair** [comment]
I’m suggesting a default _type_ - since it’s a path, it is likely to be a aggregate of several values.

Because other common `PATH` variables are of the `aggregate` type I assumed this one would be also and got really tripped up by packages clobbering each other’s `LD_LIBRARY_PATH` values.

**Comment by christophermaier** [comment]
@smartb-pair Going back to the end of discussion on #4067, it sounds like you may have more of an idea around usecases for `LD_LIBRARY_PATH`... is that right?

Still not clear where the right level of support in Habitat is for this, but adding the following to the top level (i.e., not in any callback hooks) of affected `plan.sh` files should help you in the near term:

```sh
export HAB_ENV_LD_LIBRARY_PATH_TYPE=aggregate
```

**Comment by smartb-pair** [comment]
That’s exactly what we did.

**Comment by rsertelon** [comment]
@christophermaier Would it make sense to create a PR to add it to the `__well_known_aggregate_env_vars` ?

**Comment by christophermaier** [comment]
Closing; see #6263 for future work.
