### ISSUE TITLE
[builder admin] Add labels in logs to distinguish Job ID and Group ID

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4423]
### Todo
In the Worker log, add a label to indicate which ID is the Job ID and which is Group ID. So that they can be easily identified, selected, copied and paste to other tools for further information.

### Example Worker logs in Sumologic
![image](https://user-images.githubusercontent.com/9401459/34626119-4f807bdc-f210-11e7-802b-91b7607054a6.png)
In fact, the first one is the Group ID, the second one is the Job ID. The digits look quite similar.

---
_This issue is created based on the research findings from the Chef Builder admin interviews. You can find the complete research summary [here](https://docs.google.com/document/d/1Gf0zNZllGLQh791e-d6ZZBYH6_xJQ51Hqu46VU9dEh8/edit) (visible to Chef employee only)_

**Comment by elliott-davis** [comment]
@apriofrost is this still something we want to tackle?

**Comment by apriofrost** [comment]
@elliott-davis all the issues started with [builder admin] are the actionable items I took through the Builder admin interviews. They would be helpful when we design Builder admin UI. But as far as I know, it's not on the roadmap yet. @tashimi do you have any comments on these?

**Comment by tashimi** [comment]
This was identified as an easy win for improving our logging for better systems awareness today. Might be a good thing to have a goalie knock out?
