### ISSUE TITLE
Ensure that all Habitat Builder service logs are being collected in SumoLogic

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4438]
Currently, we're collecting Builder worker logs and API logs in SumoLogic, but we've got several other services we should be collecting logs for (and alerting on).

We should ensure that the SumoLogic collector is present on the other services, and that they're collecting the proper log outputs.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #94](https://github.com/habitat-sh/builder/issues/94) via [**ZenHub**](https://www.zenhub.com/)
