### ISSUE TITLE
[www] Content and call-to-action doesn't match

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4446]
On the [homepage](https://www.habitat.sh) just above the footer, the copy on the left talks about the [Builder demo](https://www.habitat.sh/demo/build-system/steps/1/), but the Get Started call-to-action button points to the [Learn page](https://www.habitat.sh/learn/).
![image](https://user-images.githubusercontent.com/9401459/35021696-e3ab233c-fae6-11e7-8b1f-59a141fbd3cf.png)

Depending on the goal, we can either update the content to not just about Builder or update the call-to-action link to be the Builder demo described in the copy. 
@ryankeairns any thoughts?

**Comment by ryankeairns** [comment]
Let's do two things:
1) short term, change the button to link directly to the build system demo and 
2) longer term, do some research with an eye towards updating the home page copy (i.e. add a demo video, etc.)

Thanks Liz!

**Comment by cnunciato** [comment]
Closing this as no longer applicable.
