### ISSUE TITLE
[builder-web] Unable to sign in to acceptance

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4447]
Several people, including myself, have been unable to sign in to acceptance for some time.
The error message I see is listed below:

![screenshot 2018-01-17 10 03 11](https://user-images.githubusercontent.com/446285/35052683-cf6eb97e-fb6d-11e7-88b0-ca9519b26481.png)
![screenshot 2018-01-17 10 04 01](https://user-images.githubusercontent.com/446285/35052684-cf8a4d7e-fb6d-11e7-884f-20339251ee80.png)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #97](https://github.com/habitat-sh/builder/issues/97) via [**ZenHub**](https://www.zenhub.com/)
