### ISSUE TITLE
Docker exporter fails if `--registry-url docker.io` option is specified

### ISSUE THREAD

**Issue by zeenix** [habitat-sh/habitat#4455]
OS: Fedora 27
Habitat from git master (self-built)
Docker daemon & binary from hab package core/docker/17.09.0/20171001205930

With this command:

```
 hab pkg export docker --push-image --username zeenix --password $PASSWORD --registry-url docker.io --registry-type docker results/zeenix-testapp-0.2.0-20180118130531-x86_64-linux.hart
```

I get the following errors:

```
✗✗✗
✗✗✗ Could not determine Docker image ID for image: docker.io/zeenix/testapp:0.2.0-20180118130531
✗✗✗
```

If I remove the '--registry-url' option, everything works fine. I'm attaching the full console output of the nonworking commandline with RUST_LOG=debug.

[out.log](https://github.com/habitat-sh/habitat/files/1643112/out.log)

**Comment by eeyun** [comment]
@zeenix I think it's like this is an issue of the value of `--registry-url` thats getting passed in your above command. I believe that the actual docker registry url should be index.docker.io/v1 . This does however point to a potential pain point WRT UX around leveraging this flag. It's possible that we could enhance this to remove the possible pain around the special case of using the docker hub but we would prefer to have a different issue opened for this. I'm going to close this issue for now and if you have any more concerns or further concerns please feel free to comment here or reopen!
