### ISSUE TITLE
Add Fastly logs to SumoLogic

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4456]
When there are issues with Fastly, we don't have enough visibility to understand what's going on. Without access to Fastly request logs, we also don't have a complete picture of the usage patterns of Builder.

Fastly has support for aggregating logs in external systems; helpfully, they have instructions for SumoLogic, our current log aggregation service.

https://docs.fastly.com/guides/streaming-logs/log-streaming-sumologic

**Comment by chefsalim** [comment]
Moving to In Development -will have to do a terraform change for this
