### ISSUE TITLE
bldr rebuilt all Ruby packages when merging ruby25

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#4461]
When merging the plan for ruby25, I noticed that builds for ruby, ruby22, ruby23, and ruby24 were also started at approximately the same time (based on job duration and finish time). 

I suspect it has to do with the shared `paths` in `.bldr.toml`, but without additional logs that's just a guess. 

Relevant builds:
https://bldr.habitat.sh/#/pkgs/core/ruby/builds/897954664293146624
https://bldr.habitat.sh/#/pkgs/core/ruby22/builds/897954661021564928
https://bldr.habitat.sh/#/pkgs/core/ruby23/builds/897954667396947968
https://bldr.habitat.sh/#/pkgs/core/ruby24/builds/897954661323563008
https://bldr.habitat.sh/#/pkgs/core/ruby25/builds/897955661002407936

PR that was merged:
https://github.com/habitat-sh/core-plans/pull/1130

**Comment by smacfarlane** [comment]
I've been unable to confirm this behavior by modifying the tests in `components/builder-core/src/build_config.rs` as follows (existing code elided for brevity):

```const CONFIG: &'static str = r#"
    ....

    [ruby]
    plan_path = "ruby"

    [ruby25]
    plan_path = "ruby25"
    paths = [
        "ruby/*"
    ]
    ....
   "#;

    #[test]
    fn triggered_by() {
        ...
        let ruby = cfg.get("ruby").unwrap();
        let ruby25 = cfg.get("ruby25").unwrap();

        ...

        assert!(ruby25.triggered_by("master", &["ruby25/plan.sh"]));
        assert!(ruby25.triggered_by("master", &["ruby/plan.sh"]));
        assert!(ruby.triggered_by("master", &[".bldr.toml"]));
        // Test if a change to ruby25 would trigger ruby, expect this test to pass to confirm behavior noted in #4461 
        assert!(ruby.triggered_by("master", &["ruby25/plan.sh"]));

    }
```

**Comment by eeyun** [comment]
Issue moved to [habitat-sh/builder #161](https://github.com/habitat-sh/builder/issues/161) via [**ZenHub**](https://www.zenhub.com/)
