### ISSUE TITLE
Document running travis workflow locally

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#4472]
https://github.com/habitat-sh/habitat/wiki/Testing-travis-CI-workflows-locally-in-docker

**Comment by mwrock** [comment]
I just went through this and it worked great! Will close this.

**Comment by fnichol** [comment]
I ran through this procedure as well this morning and now I understand why this hasn't been more widely publicized--just more work than I thought it would take to get setup. However, you did a great job to draw a straight line to make it work, so I can also "thumbs up" this. Thanks for getting this written down--I suspect this is going to save someone a good deal of time in the next few months at least.

**Comment by baumanj** [comment]
Thanks, @fnichol. I'm going to be using it more myself shortly as I try to get the API tests running in the dev studio both locally and with travis. I may add some additional automation to make this simpler.

Thanks for taking the time to go through it!
