### ISSUE TITLE
Flag to load services in local mode only

### ISSUE THREAD

**Issue by wduncanfraser** [habitat-sh/habitat#4476]
# Issue

This is related to existing issues around starting services from locally installed pkgs: #4019 and #4065.
Currently, the only way to load a service from a locally installed packages is to specify the hart file directly, regardless if it has already been installed locally, such as:

```shell
sudo hab svc load results/mtasolutions-mymta-frontend-site-3.0.1.0-20180122230236-x86_64-linux.hart
```

This complicates management, especially via CM such as Chef.

If you were to try and install the pkg and then start it via origin/name or even by the fully qualified named, hab tries to check bldr for the package and doesn't respect the locally installed version.

```
[vagrant@ac-software-dev src]$ sudo hab pkg install results/mtasolutions-mymta-frontend-site-3.0.1.0-20180122230236-x86_64-linux.hart 
☛ Verifying mtasolutions/mymta-frontend-site/3.0.1.0/20180122230236
→ Using core/bzip2/1.0.6/20170513212938
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/curl/7.54.1/20171014214153
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
→ Using core/libedit/3.1.20150325/20170514030323
→ Using core/linux-headers/4.3/20170513200956
→ Using core/ncurses/6.0/20170513213009
→ Using core/nghttp2/1.24.0/20170830163632
→ Using core/nginx/1.11.10/20171014214153
→ Using core/openssl/1.0.2l/20171014213633
→ Using core/pcre/8.38/20170513213423
→ Using core/zlib/1.2.8/20170513201911
✓ Installed mtasolutions/mymta-frontend-site/3.0.1.0/20180122230236
★ Install of mtasolutions/mymta-frontend-site/3.0.1.0/20180122230236 complete with 1 new packages installed.
[vagrant@ac-software-dev src]$ sudo hab svc load mtasolutions/mymta-frontend-site
» Installing mtasolutions/mymta-frontend-site from channel 'stable'
hab-sup(ER)[src/error.rs:452:8]: Package not found
```

After some discussion in slack, I tried loading with NO_INSTALL_DEPS and a fully qualified package name, but this results in error:

```
[vagrant@ac-software-dev src]$ export NO_INSTALL_DEPS=1
[vagrant@ac-software-dev src]$ sudo hab svc load mtasolutions/mymta-frontend-site/3.0.1.0/20180122230236
» Installing mtasolutions/mymta-frontend-site/3.0.1.0/20180122230236 from channel 'stable'
hab-sup(ER)[src/error.rs:452:8]: Channel not found
```

# Request

It would be awesome if we could flag specific services when loaded to operate in a local context, never checking bldr and handling strategy when pkgs are installed locally.

This would not be specifically for air gapped environments such as #4039. This would be meant for environments where you may be running OSS packages from depot and internally built proprietary packages in parallel.

Example usage:

```hab svc load <origin>/<name>```

Would behave like today, where it checks against depot for the most recent packages. Where

```hab svc load <origin>/<name> --local``` 

would completely ignore bldr and check the local pkg cache. If the package is not found, throw an error (similar to not being found in bldr). If a new version of the package was installed, it would update the service according to the strategy.

More on our use case: We have common tooling and open source packages that we use from bldr but all our internal/proprietary software projects are built locally in CI and published to our local Artifactory server, and then deployed to machines via Chef. Certain packages such as postgresql are run directly using bldr integration, however our internal packages are 100% downloaded and installed locally via Chef.

**Comment by christophermaier** [comment]
@wduncanfraser Can you confirm that #4607 fixes this for you?

**Comment by wduncanfraser** [comment]
@christophermaier I apologize for the delay on this, I'll look at getting this tested with 0.54 ASAP.

**Comment by christophermaier** [comment]
@wduncanfraser no problem, thanks!

**Comment by wduncanfraser** [comment]
@christophermaier Just confirmed I was able to load services from locally installed packages with 0.54, so I'll be working on rolling us forward to 0.54 and cleaning up code on our end. Thanks!
