### ISSUE TITLE
Worker builds hang when running with debug error logging

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4483]
When turning on debug log (eg, on acceptance), the build worker builds are hanging.

This is because we are stalling on the log pipe in the runner:

cmd.stderr(Stdio::piped());

We need to find a better solution to piping stderr output in the runner.

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #100](https://github.com/habitat-sh/builder/issues/100) via [**ZenHub**](https://www.zenhub.com/)
