### ISSUE TITLE
Generate personal access tokens via Habitat Builder

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4484]
This work is related to the near-term objective of switching to use Habitat generated personal access tokens. It will require both backend/API changes in addition to UI work to generate/copy/regenerate/delete your access token (on your profile).

The UI feature work and flow can be viewed in this Invision prototype:
https://chef.invisionapp.com/share/C5E6NIURX#/261858081_profile

**Comment by ryankeairns** [comment]
![profile-token](https://user-images.githubusercontent.com/446285/35300275-8f845226-004d-11e8-998d-674a2a59f6bc.gif)

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/builder #101](https://github.com/habitat-sh/builder/issues/101) via [**ZenHub**](https://www.zenhub.com/)
