### ISSUE TITLE
Updating a running service does not obey new pkg_binds

### ISSUE THREAD

**Issue by jaym** [habitat-sh/habitat#4494]
When habitat auto-updates a package, it ignores newly required bindings. Once the package
has been updated, it will restart the service. If that service is unloaded, or the supervisor
is restarted, the service will fail to come up because of missing binds. In this case, `hab svc status` says no services are loaded, however trying to load the service again fails until it is unloaded.

This was done with the at-once update strategy.

**Comment by baumanj** [comment]
Are you still seeing this after v0.56, @jaym ?

I'll loop back and test it out myself when I'm done triaging other issues, but I thought I'd check with you first in case you have a repro right at hand.

**Comment by christophermaier** [comment]
I haven't reproduced yet, but I'm reasonably certain this is still an issue.

**Comment by jaym** [comment]
I think the correct thing to do for this is to document the expected behavior. I'll try to find my test environment tomorrow

**Comment by christophermaier** [comment]
See also #5201

**Comment by christophermaier** [comment]
It's possible that this may be addressed by work I'm currently doing around asynchronous service shutdown, which also involves upgrading, and reworks a lot of that logic.
