### ISSUE TITLE
Split up protocols repo

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4506]
We should split up the protocol repo, and move components to be closer to their usage, in order to enable the scenario of updating and building features with protocol changes using the new studio-based environments.

So:
builder protocol moves to builder repo
eventsrv and launcher protocols move to habitat repo

**Comment by mwrock** [comment]
Yeah thats a better world even if this worked.

**Comment by raskchanky** [comment]
After further discussion, eventsrv will stay in the protocols repo, but builder will go to the builder repo and launcher will go back to the habitat repo.

**Comment by raskchanky** [comment]
Done via
https://github.com/habitat-sh/habitat/pull/4509
https://github.com/habitat-sh/builder/pull/114
https://github.com/habitat-sh/protocols/pull/2
