### ISSUE TITLE
[builder ui] Buttons and tabs missing after creating a new Origin

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4523]
On the "**Create New Origin**" page (https://bldr.habitat.sh/#/origins/create), after clicking on the "**Save & Continue**" button, the following page shows up like this:
![snip20180130_9](https://user-images.githubusercontent.com/9401459/35598507-aa9257b2-05d8-11e8-91be-f4c388dbd6b4.png)

The "**Connect to a Plan File**" button and three other tabs are missing unless I go back to "**My Origin**" page and click on the one I just created. This page shows the all the tabs and button:
![snip20180130_10](https://user-images.githubusercontent.com/9401459/35598551-eb3996ea-05d8-11e8-832a-377abd293901.png)

Without the button, it is not clear what a user should do next.

**Comment by cnunciato** [comment]
What's actually happening here is that the call to create the origin succeeds, and then we make an immediate follow-up call to retrieve the user's origins &mdash; but the newly created origin isn't returned the list. It shows up a short time later.

I could insert an arbitrary delay here or do something manual, but I'd rather see if it's something we can address server-side first. @chefsalim @raskchanky thoughts?

**Comment by cnunciato** [comment]
It looks like waiting a second or so works, but yeah, that feels a bit icky.

**Comment by raskchanky** [comment]
@cnunciato My first thought is to make the call to retrieve the user's origins in the callback that's triggered when the call to create the origin succeeds.  Is that already happening?

**Comment by cnunciato** [comment]
@raskchanky It is, yeah -- we create, then fetch after successful create: https://github.com/habitat-sh/builder/blob/master/components/builder-web/app/actions/origins.ts#L128-L130

**Comment by raskchanky** [comment]
It turns out the reason for this is a design limitation of the Builder backend, which I've detailed [here](https://github.com/habitat-sh/builder/issues/142)

**Comment by cnunciato** [comment]
Thanks @raskchanky! I'll patch this on the client for now by adding a brief delay to allow a little time for that syncing.

**Comment by cnunciato** [comment]
Closing as done.
