### ISSUE TITLE
[builder ui] Disable Intercom sign-ups for dev environments

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4535]
We're using Intercom to measure user sign-ups, but it seems to be picking up sign ups from local dev environments as well.

For example, we core team members creating multiple accounts per day - presumably adding a new account each time they spin up their environment.

**Comment by cnunciato** [comment]
Just a note: There are client- and server-side components to this that probably both need to be togglable.

**Comment by mwrock** [comment]
closing since I don't think we use intercom anymore
