### ISSUE TITLE
`depart` command isn't clearly available from `hab` CLI

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4544]
We have a `hab` command to depart ring members, but it isn't obvious how to call it.

It is implemented via butterfly, and thus is available via `hab butterfly depart`, but running `hab --help` doesn't show anything about the `butterfly` subcommand.

Other `butterfly` commands are aliased (e.g., `config` and `file`), but `depart` isn't.

We should ensure that this subcommand in particular, but all subcommands in general, are discoverable through the standard `--help` flag.

**Comment by rsertelon** [comment]
@christophermaier What would be the command then? `hab butterfly depart`? or maybe `hab ring depart` seems to fit in current subcommands better.

**Comment by christophermaier** [comment]
@rsertelon The command right now is callable as `hab butterfly depart`, but it just doesn't show up when you run `hab --help`, so unless you already know it's there, you're not going to find it.

I'm not yet sure if we want to alias it under the `ring` namespace (sounds plausible, though), but it definitely needs to show up through `hab --help`. Renaming / aliasing could be a separate issue, just to keep scope small.

**Comment by rsertelon** [comment]
I really think "implementation details" like butterfly shouldn't appear in the cli, but that's just my 2 cents ;) I'll try to have a look!

**Comment by rsertelon** [comment]
@christophermaier so I've checked out a bit, and it seems to me that this issue is an already discussed problem where some commands do not pass into the cli app of `hab`.

IIRC @baumanj started to [work on this](https://github.com/habitat-sh/habitat/issues/3130#issuecomment-348630644) but it seems the right solution never made it to master.

**Comment by baumanj** [comment]
Yeah, I ended up getting to a dead-end with that work where the pursuit of de-duplication led to a dependency from `hab` → `hab-sup`, which we clearly don't want. The next thing I'd like to try is moving our CLAP config to YAML format to see if we can share it that way. It would also have future localization benefits. It's still on my to-do list, but so far hasn't been the highest priority yet.

**Comment by christophermaier** [comment]
This got fixed in #5379
