### ISSUE TITLE
Add worker promotion to Habitat release process

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4569]
Our current release documentation does not include promotion of a new stable `core/builder-worker` (possibly `habitat/builder-worker`, by the time you read this). This results in us publicizing new Habitat features that are not actually available on the Builder platform.

Part of the validation and release process should include promoting a new worker package, which will ensure that the production workers are running the latest code.

**Comment by chefsalim** [comment]
Service promotion of just worker (when there could be other service dependencies) may not be the correct process.  We just split up Habitat vs. Builder, so we should understand what the dependencies are that make the two joined to the hip again..

**Comment by christophermaier** [comment]
This was handled with https://github.com/habitat-sh/builder/pull/1309
