### ISSUE TITLE
Supervisor can incorrectly re-attach to process with orphaned PID

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4578]
Ran into an issue (in the Hab dev env), where one of the services did not start up properly.  After exiting and restarting studio (as well as the VM), an orphaned PID was left behind in the svc directory.

When the service was attempted to be reloaded again, the supervisor would "re-attach" to the process even though there was no actual living process with that PID.

From looking at the code flow, it looks like there may be a case in the is_alive check that could make it return true even if the process is no longer alive.  We should perhaps error out in the EPERM case rather than returning true, and make sure callers appropriately handle the error.

```
pub fn is_alive(pid: Pid) -> bool {
    match unsafe { libc::kill(pid as pid_t, 0) } {
        0 => true,
        _ => {
            match io::Error::last_os_error().raw_os_error() {
                Some(libc::EPERM) => true,
                Some(libc::ESRCH) => false,
                _ => false,
            }
        }
    }
}
```

**Comment by rsertelon** [comment]
Is this the same as in #4069 ?

**Comment by christophermaier** [comment]
@rsertelon Yes, I believe this is related to #4069... not 100% certain yet if it is exactly the same, though.

**Comment by christophermaier** [comment]
Closing this, since it should be addressed by https://github.com/habitat-sh/habitat/pull/7214; feel free to reopen if that's not the case.
