### ISSUE TITLE
Metadata for packages

### ISSUE THREAD

**Issue by jaym** [habitat-sh/habitat#4585]
I think it would be useful to be able to assign arbitrary metadata for packages. For example, it could be useful to describe things about the build such as the SHA of the sources I used. For some work we're doing, we have different classes of packages that could also be nicely described like this package provides a data service or it's a domain service.

**Comment by eeyun** [comment]
We've decided this is a feature that we want to implement. That being said, we still need to have a discussion around what the implementation of this feature might look like. 

It will likely require quite a bit of thought to get the right shape. So for now we're going to keep the `S-needs-discussion` label and determine the appropriate path going forward.

**Comment by christophermaier** [comment]
Still useful
