### ISSUE TITLE
pkg_bind_map multiple consumer services in composite file

### ISSUE THREAD

**Issue by luisdavim** [habitat-sh/habitat#4601]
When trying to build this plan:

```
# cat plan.sh
pkg_name="twx-ha"
pkg_origin="ptc"
pkg_type="composite"
pkg_version="0.1.0"

#pkg_svc_user="root"
pkg_services=(
    core/postgresql
    ptc/Thingworx
    ptc/haproxy
)

pkg_bind_map=(
    [ptc/Thingworx]="database:core/postgresql"
    [ptc/haproxy]="backend:ptc/Thingworx"
)
```

I get:
 ```
/hab/pkgs/core/hab-plan-build/0.52.0/20180119185615/bin/composite_build_functions.bash: line 144: all_binds_for_pkg[$bind_name]: bad array subscript
```

All the packages for the services mentioned in that plan are built and I'm able to run them with:
```
hab start core/postgresql
hab start ptc/Thingworx --bind database:postgresql.default
hab start ptc/haproxy --bind backend:Thingworx.default
```

**Comment by luisdavim** [comment]
Could this be related to #4059 ? I do have an optional bind in one of my packages.

**Comment by luisdavim** [comment]
Can anyone tell me if this is a bug or if I'm doing anything wrong?

**Comment by christophermaier** [comment]
@luisdavim Sorry, I replied to you in Slack, but it may have gotten lost in the backscroll. Yes, I believe it was related to #4059, a fix for which was merged a few days ago. It will go out in the next release, which we're planning on doing later this week. You should also be able to try it out by using a Habitat release from the `unstable` channel.

**Comment by elliott-davis** [comment]
This should be fixed. Please re-open if you are still seeing this issue with the latest release.
