### ISSUE TITLE
Getting "too many open files" when running butterfly tests

### ISSUE THREAD

**Issue by krnowak** [habitat-sh/habitat#4614]
Recently I have been doing a bit of refactoring of the butterfly server by abstracting the direct use of UDP and ZMQ sockets away (the PR is #4497). The result is that a butterfly server opens two more file descriptors (further just FDs) than before. That by itself is not a problem - Supervisor is running just one butterfly server which consumes around 5-10 FDs.

Different story is with tests - it basically is a single binary containing and running by default all the tests. And tests are often starting a bunch of butterfly servers, where each one starts several detached threads that hold open FDs to sockets. The threads never go away, so they are holding them until the process terminates.

There was no problem before my refactoring, but after those two more open FDs per server caused the process to break the soft limit for open FDs, which is 1024 on my system.

I worked it around by patching the function that creates `SwimNet` in a butterfly-test component to set the soft limit to a hard limit (which is 4096 on my system). The commit with the workaround is a part of the PR #4497 (https://github.com/habitat-sh/habitat/pull/4497/commits/ef69d91948d9ae45748dcd52d9328aeb82e86fba)

But it would be terrific if we could tell those threads to stop, so they could release the resources they hold.

It can be a bit problematic to fix, though… I'd imagine that in POSIX world we could have a pipe for each thread, so the thread could do `select` on the readable end of the pipe and on the socket (provided that we actually can get the fd of the socket…) and when dropping the main instance of the butterfly server, we could send stuff to the writable end of the pipe. But then there's also Microsoft Windows and I have no clue what to do here - `libc` package has no select or anything like that.

**Comment by baumanj** [comment]
Closing since [the PR this is predicated on](https://github.com/habitat-sh/habitat/pull/4497) was closed.
