### ISSUE TITLE
Regression in template variable handling

### ISSUE THREAD

**Issue by krnowak** [habitat-sh/habitat#4615]
Since 0.52 the following template fails to compile: `{{bind.foo.members[0].sys.ip}}`. The error is `Helper not defined: "bind"`.

I have written a test for it and used it in two branches, one that is on top of `0.51.0` tag and one that is on top of `0.52.0` tag. The branches are:

- https://github.com/kinvolk/habitat/tree/krnowak/bind-variable-51
- https://github.com/kinvolk/habitat/tree/krnowak/bind-variable-52

In each of those branches I did `(cd components/sup && cargo test templating::test::bind_variable)`. For 0.51.0 it passes, for 0.52.0 I'm getting:

```
running 1 test
test templating::test::bind_variable ... FAILED

failures:

---- templating::test::bind_variable stdout ----
	thread 'templating::test::bind_variable' panicked at 'called `Result::unwrap()` on an `Err` value: SupError { err: TemplateRenderError(RenderError { desc: "Helper not defined: \"bind\"", template_name: Some("t"), line_no: Some(1), column_no: Some(1), cause: None }), logkey: "TP", file: "src/templating/mod.rs", line: 62, column: 12 }', src/libcore/result.rs:906:4
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I suppose it the regression came after updating the packages in commit e8c5ff7ac3c5aa480704493f16864deaa249adc3

So, what could be the fix? Revert the handlebars from 0.29 to 0.26?

**Comment by christophermaier** [comment]
@krnowak Yup, it looks like setting the `handlebars` crate back to version `0.26.2` makes the regression test pass. I will do a bit more digging over in that codebase to see what the underlying cause might be.

Nice catch 👍
