### ISSUE TITLE
hab pkg download

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4616]
In order to facilitate things like air-gapped on-prem depot installs, where we want to bootstrap a fresh depot with a full set of core packages, we need the ability to do the equivalent of `hab pkg install` without the `install` part.  That is, we need a command that will download a package and all of its transitive dependencies to disk, and stop there.

This command should allow specifying an arbitrary location on disk for the resulting packages to be downloaded to, along with a sensible default (probably `/hab/cache/artifacts`).

**Comment by raskchanky** [comment]
After some discussion with @fnichol around this particular corner of the `hab` code, I'm going to spike out an experiment to see what this looks like in shell code.  If it works, it has the advantage of not touching part of our Rust code that is currently undergoing some changes, and keeps the entire bootstrapping process a bit simpler.

**Comment by raskchanky** [comment]
I completed this work in shell code, so as of now, `hab pkg download` doesn't exist.  Regardless, I'm going to close this.  We can revisit it in the future if we need to.

**Comment by themightychris** [comment]
@raskchanky could you share that here for posterity?

**Comment by raskchanky** [comment]
@themightychris The code I wrote lives in a private repo right now, and I'm not entirely sure if it will ever get open sourced or not.  I don't think there's anything sensitive in the script that I wrote, though, so I made a gist of the entire thing [here](https://gist.github.com/raskchanky/bb258afd1abbafb81daf79ffdd4af0a4).

**Comment by markan** [comment]
This has come back around, and after writing some code to do this as part of the on-prem-builder work, it feels like this belongs as a first class command in habitat.

Proposal:
```
Downloads a Habitat package or packages from Builder

USAGE:

hab pkg download [FLAGS] [OPTIONS] [<PKG_IDENT> | --file <FILENAME>]...

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
    --no-recurse     Do not transitively expand packages

OPTIONS:
    -z, --auth <AUTH_TOKEN>    Authentication token for Builder
    -u, --url <BLDR_URL>       Specify an alternate Builder endpoint. If not specified, the value will be taken from the
                               HAB_BLDR_URL environment variable if defined. (default: https://bldr.habitat.sh)
    -c, --channel <CHANNEL>    Install from the specified release channel (default: stable)

    -t, --target <TARGET>      Use this as the target architecture to fetch (multiple allowed)

    --file <FILENAME>          Newline separated list of package identifiers or filepaths
    --cache <DIRECTORY>        Directory to use for the cache. /hab/cache is the default

ARGS:
    <PKG_IDENT_OR_ARTIFACT>...    One or more Habitat package identifiers (ex: acme/redis) and/or filepaths to a
                                  Habitat Artifact (ex: /home/acme-redis-3.0.7-21120102031201-x86_64-linux.hart)

This command downloads but does not install packages into the cache,
along with the relevant origin public keys. The packages are specified
on the command line or in a file.  This can be used to fetch packages
to bootstrap a local builder instance.
```

**Comment by baumanj** [comment]
```
    -t, --target <TARGET>      Use this as the target architecture to fetch (multiple allowed)
```
It would probably be helpful to list the valid options, as well as the default

```
    --file <FILENAME>          Newline separated list of package identifiers or filepaths
```
Rather than `<FILENAME>` (we know it's a file), perhaps `<PKG_IDENTS>` or `<PKG_IDENTS_FILE>`?

```
    <PKG_IDENT_OR_ARTIFACT>...    One or more Habitat package identifiers (ex: acme/redis) and/or filepaths to a
                                  Habitat Artifact (ex: /home/acme-redis-3.0.7-21120102031201-x86_64-linux.hart)
```

If you had the artifact, what would be the point of this command? Should this should only take package identifiers?

```
This command downloads but does not install packages into the cache,
```
This is a bit confusing. Is this saying it downloads the `.hart` files into the cache directory, but doesn't install them? If so, that may be clearer if the wording is changed. Also, a reference to `hab pkg install` would be useful to contrast the behavior.

**Comment by markan** [comment]
My bias is towards parallel construction with hab pkg install, so some of the choices come from there.

'If you had the artifact, what would be the point of this command? Should this should only take package identifiers?' My thinking is that might not have the TDEPS of the artifact and want to download them; that seems to be what the hab package install pattern does. However that functionality is mostly to maintain parallel construction, so I could be convinced to skip it.

I edited my initial post to rephrase the confusing `This command downloads but does not install packages into the cache` line.

I'll make another pass to improve the verbiage around the command, but does the general shape of the proposed functionality seem sensible?

**Comment by baumanj** [comment]
> 'If you had the artifact, what would be the point of this command? Should this should only take package identifiers?' My thinking is that might not have the TDEPS of the artifact and want to download them

Is this a likely use case? I'm just trying to imagine how we get there and why it wouldn't be easier to just use the package identifier _anyway_ in that case. I believe our logic is smart enough to not re-download the `.hart`s that are already present on the system.

> I edited my initial post to rephrase the confusing This command downloads but does not install packages into the cache line.

There must be a typo; It currently reads:
```
This command downloads  into the cache but does not install them,
```
Add `artifacts that the given package identifier(s) resolve to` before `into`, and I think that sounds good to me. There's definitely some subtlety here in the relationships between a "package", "package identifier" and "artifact" that I think is important to state accurately.

> I'll make another pass to improve the verbiage around the command, but does the general shape of the proposed functionality seem sensible?

General shape seems reasonable to me.

**Comment by raskchanky** [comment]
If I were doing this, I'd probably make the usage

```
hab pkg download [FLAGS] [OPTIONS] <PKG_IDENTS>
```

where `<PKG_IDENTS>` is a space separated list of package identifiers to download.

```
<PKG_IDENT_OR_ARTIFACT>...    One or more Habitat package identifiers (ex: acme/redis) and/or filepaths to a
                                  Habitat Artifact (ex: /home/acme-redis-3.0.7-21120102031201-x86_64-linux.hart)
```

I think we definitely want to be clear on this part that we're specifying a package identifier to download, and not an artifact.  I'm guessing this part came from `hab pkg install`, but in that case, it's valid because you can call `hab pkg install` on a local artifact to get it properly installed, whereas here, we're specifically interested in downloading things.

On my initial read, it wasn't clear what the `--file <FILENAME>` option did.  I first thought it was trying to specify what to name the file that we download from Builder, which didn't seem right.  It wasn't until reading the help text that I realized what it was for.  I'd probably omit that option, if I was doing this, unless there's a strong need for it.  It seems like you could achieve the same functionality by allowing this command to read from `stdin`, so if you had a file called `idents.txt` that contained a newline separated list of package identifiers that you wanted to download, you could do:

```
cat idents.txt | hab pkg download
```


> I'll make another pass to improve the verbiage around the command, but does the general shape of the proposed functionality seem sensible?

Yeah, for sure.

**Comment by baumanj** [comment]
> It seems like you could achieve the same functionality by allowing this command to read from `stdin`, so if you had a file called `idents.txt` that contained a newline separated list of package identifiers that you wanted to download, you could do:
> 
> ```
> cat idents.txt | hab pkg download
> ```

If It's not even necessary to make the command read from stdin:
```sh
$ hab pkg download $(cat idents.txt)
```

**Comment by markan** [comment]
It's probably not a huge issue, but the xargs pattern becomes a little bit more troublesome on windows, which has short (2k to 8k) max command line lengths; that's where the external file becomes nice.

**Comment by baumanj** [comment]
Do we expect this command to be used with that many package identifiers? If so, I'd like to know more about those use cases. Is this for downloading every package on builder? Whole origins? Or is it really for a very specifically curated list of package identifiers that happens to be a really large number of them?

**Comment by markan** [comment]
Closing in favor of more detailed proposal in #6878. I've tried to incorporate or respond to all the feedback given here.
