### ISSUE TITLE
Source permissions persist in build artifacts

### ISSUE THREAD

**Issue by mattray** [habitat-sh/habitat#4625]
MacOS 10.13.3, Docker Version 18.02.0-ce-mac53 (22617)

For historical reasons I have ```umask 077``` in my ```.bashrc``` and all files I check out from GitHub have permissions of ```600``` by default. When I enter the studio and build packages, permissions on files in the package are not changed and root ownership is preserved. This means that the https://github.com/mattray/sample-node-app fails with the following error:
```
sample-node-app.default(SV): Starting service as user=hab, group=hab
sample-node-app.default(O): fs.js:646
sample-node-app.default(O):   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
sample-node-app.default(O):                  ^
sample-node-app.default(O):
sample-node-app.default(O): Error: EACCES: permission denied, open '/hab/pkgs/mattray/sample-node-app/1.0.1/20180216050235/app/routes/index.js'
sample-node-app.default(O):     at Object.fs.openSync (fs.js:646:18)
sample-node-app.default(O):     at Object.fs.readFileSync (fs.js:551:33)
sample-node-app.default(O):     at Object.Module._extensions..js (module.js:653:20)
sample-node-app.default(O):     at Module.load (module.js:556:32)
sample-node-app.default(O):     at tryModuleLoad (module.js:499:12)
sample-node-app.default(O):     at Function.Module._load (module.js:491:3)
sample-node-app.default(O):     at Module.require (module.js:587:17)
sample-node-app.default(O):     at require (internal/module.js:11:18)
sample-node-app.default(O):     at Object.<anonymous> (/hab/pkgs/mattray/sample-node-app/1.0.1/20180216050235/app/app.js:8:13)
sample-node-app.default(O):     at Module._compile (module.js:643:30)
hab-launch(SV): Child for service 'sample-node-app.default' with PID 40 exited with code exit code: 1
```

Manually updating the source permissions to 755 and 644 where appropriate and rebuilding the packages results in working demos.

I would expect habitat to set ownership of the files to the ```pkg_svc_user```

**Comment by fnichol** [comment]
Am I right that this would be using the Node Scaffolding? If so, yep, we should be adding some group/other read/execute bits where appropriate.

**Comment by mattray** [comment]
It's both scaffolding and regular plans. [sample-node-app](https://github.com/habitat-sh/sample-node-app), [sample-rails-app](https://github.com/habitat-sh/sample-rails-app) and the [national-parks](https://github.com/chef-cft/national-parks) demos all failed without fixing the permissions. ```chmod```ing the files properly fixed all of them.
