### ISSUE TITLE
[data collection] Decompose Builder Job Status data 

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4632]
Currently, on the [Live Builder Job Status dashboard](https://app.datadoghq.com/screen/221275/live-builder-job-status),  we aggregate total counts of **Completed Jobs** and **Failed Jobs**.

It will give us better Builder performance measurement if we can decompose the count number further by:

- Build jobs triggered by Habitat team, Chef internal team, and the rest community members
   - The complete and failed count of each segment  
- Failed build jobs caused by user error, and Builder error

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #287](https://github.com/habitat-sh/builder/issues/287) via [**ZenHub**](https://www.zenhub.com/)
