### ISSUE TITLE
RFC: Discussing Butterfly Optimizations

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4634]
For the purpose of transparency of on-going development conversations, the team is currently discussing how to make the Butterfly (SWIM-based gossip algorithm) protocol more performant. Please note that these changes are interesting but would not impact the end-user experience of using Habitat except for providing a more scaleable and robust low level experience. 

Current proposals/ideas being considered: 

- Changing the way sockets are handled.  Don't use ZeroMQ for butterfly anymore. Process messages or don't handle them, don't want them queuing since rumors are durable so redundancy isn't needed. 

- Consider moving to capnproto instead of using protobuf: for client (not for servers). Currently serialization vs deserialization takes time, and if we switch to a new threading model using a different reactor loop we don't want to spend the time doing this operation since the volume of rumors is high. A lot of times the framing around processing a rumor is more than its payload. In capnproto (https://capnproto.org/), the representation in memory is the same on the network as on the wire, so we don't have to do serialization/deserialization steps. 

- Goals: Get memory footprint down, reduce network chatter, and fix the threading model. Remove opportunity for race conditions which inaccurately inform application layer above that it should be waiting for something.   
-- Store everything in memory
-- Threading model completely changes, becomes delegate driven
-- When something changes, changes main thread
-- More closely coupled with a layer above it which is currently the Supervisor 
-- much less generic

**Comment by raskchanky** [comment]
Given that the reference implementation in the SWIM paper used UDP, moving from ZMQ to UDP seems like a good move.

**Comment by mwrock** [comment]
closing this since these points have either been addressed or are being worked on actively.
