### ISSUE TITLE
Replace the changelog generator with something that works

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4654]
Generating the changelog for a release has traditionally been one of the most painful points of the release process, amazingly enough. The generated content is often inconsistent (duplicating entries, etc.), frequently runs afoul of Github API limits, and can fail silently (I once had to resort to using `strace` to discover that it wasn't able to work with repositories cloned by SSH).

We either need to discover *why* nobody on the team seems to be able to use this tool successfully, or just replace it altogether.

An in-house option is [Expeditor](http://expeditor-docs.es.chef.io), which already has [changelog-generation capabilities](http://expeditor-docs.es.chef.io/configuration/changelog/). This approach uses formatted entries on a rolling basis, rather than generating a complete changelog at release time. We won't get rate-limited anymore, we won't have to manually wrestle with the changelog at release time, and we'll get a higher-quality changelog. It will introduce additional commits into our history, which will need to sensibly be dealt with in CI.

It can also take advantage of Github labels on PRs, which will allow us to control the structure of the changelog (e.g., highlight bugfixes, new features, breaking changes, etc.)

**Comment by raskchanky** [comment]
I'm firmly in the "replace it altogether" camp on this one, especially when given the option to use something that's able to take advantage of GH labels (whether that option is Expeditor or a home grown tool).

**Comment by christophermaier** [comment]
Based on Slack conversation, we're going to give Expeditor a try. I'll be working with @tduffield today to get the groundwork laid for that.

**Comment by christophermaier** [comment]
Update: Expeditor has been enabled in our organization, but we still need to write configuration files, mark up our changelog file appropriately, and settle on a convention for labels we want to highlight.

**Comment by tduffield** [comment]
@baumanj the way we recommend handling that is by having Expeditor trigger your CI :)

**Comment by baumanj** [comment]
Hey @tduffield, I have [a PR over here](https://github.com/habitat-sh/habitat/pull/4803) that I think should do what we need, but would you mind looking at it? I'm not really sure how to test without merging it.

Also not sure why I couldn't just @mention you on the PR itself, but I couldn't
