### ISSUE TITLE
[www] Update website content - Home and Pricing

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4660]
Update the Home and Pricing pages to reflect new messaging.
The Invision link below is peppered with notes that will guide you in building out the pages. Let me know if you have any questions.

**PREVIEW - Clickable prototype**
https://chef.invisionapp.com/share/ZVG7KTWK267#/283100669_step_1

**PREVIEW - Home and Enterprise mobile mockups --> including nav toggle**
https://chef.invisionapp.com/share/ZVG7KTWK267#/287144929_infographic_Mobile_View__-_V3_Step_1

-------------

**GET STYLES & COPY - Home page Invision Inspect**
https://chef.invisionapp.com/d/main/#/console/13570590/283100669/inspect

**GET STYLES & COPY - Pricing page Invision Inspect**
https://chef.invisionapp.com/d/main/#/console/13570590/286280609/inspect

**GET STYLES & COPY - Homepage mobile (with infographic assets) Invision Inspect**
https://chef.invisionapp.com/d/main/#/console/13570590/287144929/inspect (circles as a single asset)
https://chef.invisionapp.com/d/main/#/console/13570590/287144927/inspect (circles as separate 5 assets)

**New assets (icons, habicats, etc.)**
https://www.dropbox.com/s/2q1rhem44vmqdch/Habitat-v3-assets.zip?dl=0
You can also download assets from Invision Inspect either by clicking on the layer or switching over to the ASSETS tab:
![screenshot 2018-03-21 10 04 22](https://user-images.githubusercontent.com/446285/37717830-5cef4b12-2cef-11e8-8eb8-7d0a80b2e80a.png)

**Comment by ryankeairns** [comment]
@mgamini @cnunciato This issue contains mockups and Inspect links for the revised Home and Pricing pages. It also includes a couple of mobile mockups in addition to a tidied up mobile nav.

Garret, let's chat when you have some time. Thanks!

**Comment by cnunciato** [comment]
@ryankeairns Do you want to make any content changes to the video, or has your feedback been such that it's fine as-is? I have things set up such that editing should be pretty doable.

**Comment by ryankeairns** [comment]
@cnunciato it would be great if we could drop in a few graphic slides (beginning and end; maybe a shot of liz’s infographic). I’m thinking we could keep the audio/video as-is and just show these?

Let me know if that sounds doable and I’ll send you some graphics. 

Thanks!

**Comment by cnunciato** [comment]
@ryankeairns Totally doable, yep.

**Comment by ryankeairns** [comment]
@cnunciato great. What are the preferred pixel dimensions

**Comment by cnunciato** [comment]
@ryankeairns The current clip dimensions are 870x498, looks like.

**Comment by apriofrost** [comment]
I made a few changes to Ryan's main post:
1. change the "PREVIEW - Home and Enterprise mobile mockups --> including nav toggle" link to include the latest design with the infographics.
2. add the session "GET STYLES & COPY - Homepage mobile (with infographic assets) Invision Inspect" and two links for different slices (@mgamini you can choose whatever works the best). The infographics are the exact same on both screen sizes.
CC @ryankeairns
