### ISSUE TITLE
Studio failures should print the command that failed

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#4671]
In the context of https://github.com/habitat-sh/habitat/issues/4391, it would've been much easier for the user to understand the nature of the error if the failing `mount` command were printed. It's not immediately clear how feasible this is. Perhaps documenting https://github.com/habitat-sh/habitat/issues/4670 and providing a hint in the error message to rerun with that enabled is the best option.

**Comment by tashimi** [comment]
@baumanj is this done now?

**Comment by baumanj** [comment]
No, this a tangential issue to the problem that was blocking smartb-pair. The cause of that error (improper path quoting in the studio code) was fixed, but this is about making future errors more understandable by showing more information about what's going on when there's a failure.
