### ISSUE TITLE
Clean up `/tmp/rust-ipc-socket.XXXXXX` files

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4673]
The Launcher and Supervisor processes use a pair of sockets to communicate with each other, which are written out to `/tmp/rust-ipc-socket.XXXXXX` files. Furthermore, each restart of the Supervisor generates a new pair of socket files. 

It appears that we don't always do a good job of cleaning up these files (if at all), resulting in some users reporting the accumulation of a large number of these files. We should do better cleanup.

In the meantime, only the two most recently-created socket files are necessary, so if you encounter this, feel free to remove any unneeded files. (However, if you happen to be running other Rust binaries on the same host that use the [ipc-channel](https://github.com/servo/ipc-channel) crate, some of those socket files might be in use by those binaries; in that case, proceed with caution.)

**Comment by christophermaier** [comment]
Pinging @bdangit and @chrisortman since they've raised the issue in Slack before.

**Comment by bdangit** [comment]
Hi @christophermaier,

Yes.  I spent sometime deleting the files in /tmp. There’s definiately a lot more than can fit within the standard `*` so I had to iterate to remove files this way: 

```bash
rm -rf /tmp/rust-ipc-socket.A*
rm -rf /tmp/rust-ipc-socket.B*
...
rm -rf /tmp/rust-ipc-socket.Z*
rm -rf /tmp/rust-ipc-socket.a*
rm -rf /tmp/rust-ipc-socket.b*
...
rm -rf /tmp/rust-ipc-socket.z*
rm -rf /tmp/rust-ipc-socket.0*
rm -rf /tmp/rust-ipc-socket.1*
...
rm -rf /tmp/rust-ipc-socket.9*

```

I’m sures some for loop we can create to remove them.  

I also do remember seeing an issue from that crate where they want to use some other method for creating the ipc-channel (one that doesn’t involve generating a tmp file that plagues shm technique.)

**Comment by bdangit** [comment]
https://github.com/servo/ipc-channel/issues/125

Looks like memfd was considered but it’s a Linux only feature.

**Comment by smartb-pair** [comment]
As requested by @christophermaier, wanted to leave some notes here about our experience with this behavior. Habitat version is `0.53.0`:

Total number of tempfiles:
```
$ find /tmp -name rust-* | wc -l
339298
```
First and last datestamps of files in `/tmp`:
```
$ find /tmp -name rust-* | xargs ls -l | head -n1
srwxr-xr-x 1 root root 0 Mar 30 06:35 /tmp/rust-ipc-socket.009qK3
...
...
$ find /tmp -name rust-* | xargs ls -l | tail -n1
srwxr-xr-x 1 root root 0 Mar 30 11:19 /tmp/rust-ipc-socket.zzBQyX
```
Of note, the last time Supervisor systemd service changed state:
```
$ systemctl status supervisor
● supervisor.service - The Habitat Supervisor
   Loaded: loaded (/etc/systemd/system/supervisor.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-03-30 06:30:24 UTC; 1 weeks 3 days ago
 Main PID: 2390 (hab-launch)
    Tasks: 1
   Memory: 133.3M
      CPU: 25min 46.843s
   CGroup: /system.slice/supervisor.service
           └─2390 /hab/pkgs/core/hab-launcher/6083/20171101045646/bin/hab-launch run
```

**Comment by christophermaier** [comment]
Reading up on servo/ipc-channel#125, it looks like the code to use `memfd` is already in place, and is behind a feature gate... worth examining to see if we can take advantage of that.

**Comment by baumanj** [comment]
Still valid as of 0.56

**Comment by baumanj** [comment]
I'd like to address this (at least the launcher parts) in https://github.com/habitat-sh/habitat/issues/5300

**Comment by smartb-pair** [comment]
This broke some of our database servers today. Consider this an upvote for fixing :)

**Comment by bixu** [comment]
Actually, @baumanj, is there any chance of fixing the orphaned file problem separately from the Launcher overhaul? Asking only because I live in fear of a production DB server going down after running out of inodes (this has happened to us in Staging before).

**Comment by baumanj** [comment]
Yeah, this can come first. There's not going to be a monolithic "launcher overhaul", so much as a collection of issues that after they're fixed, we hope means we can *very* rarely update the launcher. 
https://github.com/habitat-sh/habitat/issues/5300 serves to focus the intent and mark the finish line, not hold back all the improvements.

Thanks for communicating your impact so this can be appropriately prioritized.

**Comment by baumanj** [comment]
This is merged now, @bixu. Once we have our next release, it'll require an update to your launcher to fully fix, though just a regular supervisor update will reduce the rate of accumulation by half.
