### ISSUE TITLE
Topics in sidebar won't link in docs

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4679]
Per convo in https://github.com/habitat-sh/habitat/pull/4678, the links for the topics on the sidebar don't link to the overview content per topic. 

For example, it would be nice if I could click on the topic "Best Practice Guides" and be taken to https://www.habitat.sh/docs/best-practices/ 

cc @cnunciato @mgamini

**Comment by ryankeairns** [comment]
Closed via #4701
