### ISSUE TITLE
Move documentation of labels into label details

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#4684]
GitHub labels now support descriptions, which will show up in useful places when you're using labels.

I copied this practice from you: https://github.com/habitat-sh/habitat/wiki/Label-Names-and-Definitions

But now you can document the labels directly in GitHub's labels model/ui instead of off in the wiki: https://github.com/SlateFoundation/slate-cbl/labels

**Comment by mwrock** [comment]
Hey nice!
