### ISSUE TITLE
Feature Request: hab pkg upload should default to the most recently built artifact

### ISSUE THREAD

**Issue by ncerny** [habitat-sh/habitat#4703]
As an application developer, I would like `hab pkg upload` to default to the most recently built package, so that I can more quickly build and test my packages.

**Comment by bdangit** [comment]
Hrmm how does uploading a `hart` into a depot help with building things fast?  The testing I might understand, if that package content gets integrated with other packages.

BTW, a workaround I have used to make sure I can use my last built is I made a bash function called `lastbuilt` which will grep the `results/lastbuilt.env` for last built. :). Then I can just run `hab pkg upload $(lastbuilt)`.

**Comment by elliott-davis** [comment]
I think this might be more of a documentation issue around last_built.env. The underlying request here feels a bit magical and could result in unexpected behavior. I'm going to close this for now. Please feel free to re-open if you'd like to discuss further.
