### ISSUE TITLE
Docker build failed when trying to publish to Docker Hub Container Registry

### ISSUE THREAD

**Issue by tgj** [habitat-sh/habitat#4705]
While going through the second tutorial in Habitat 101 (under the Learn tab at https://habitat.sh/), I encounter the following issue when trying to publish to the Docker Hub Container Registry.

Cannot connect to the Docker daemon at unix:///hab/svc/builder-worker/data/931311898694369280/dockerd/var/run/docker.sock. Is the docker daemon running?
✗✗✗
✗✗✗ Docker build failed with exit code: exit code: 1
✗✗✗

Any ideas why this would be happening? I have given Docker permissions for GitHub, and I don't have 2FA enabled. 

Also, the build passes when I remove the Docker Hub integration.

I've attached the build log here:
[build_log.txt](https://github.com/habitat-sh/habitat/files/1782783/build_log.txt)

**Comment by tgj** [comment]
Additional info: The build passes when I remove the Docker Hub integration.

**Comment by eeyun** [comment]
We'll have to look at this but it's very likely a serverside issue with the latest version of docker. I'll try and give this a full triage tomorrow.

**Comment by tgj** [comment]
Appreciate it Ian!

**Comment by eeyun** [comment]
Issue moved to [habitat-sh/builder #255](https://github.com/habitat-sh/builder/issues/255) via [**ZenHub**](https://www.zenhub.com/)
