### ISSUE TITLE
Extract various API client libraries

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4708]
We have an `http-client` crate in the `habitat` repository, which is used by the Supervisor, but also by `builder-api-client`, `builder-depot-client`, `github-api-client`, all of which need to be in the `builder` repository instead (they're not used in `habitat`, and are a vestige of previous repository separations).

There's also a `segment-api-client` in the `habitat` repository, which doesn't depend on `http-client`, but should also be in the `builder` repository.

The `http-client` crate should be extracted to a separate repository, and the API clients should be moved over to `builder`

**Comment by mwrock** [comment]
closing since all issues are closed
