### ISSUE TITLE
Better process for package removal

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4712]
There are some cases (security issues, significant user escalations, and a need to clean up core origin, etc) where we need to remove packages from origins.  This issue is about having some sort of redirection or notification process if someone tries to use the removed package.

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #286](https://github.com/habitat-sh/builder/issues/286) via [**ZenHub**](https://www.zenhub.com/)
