### ISSUE TITLE
Move http-client crate over to the core repository

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4726]
Our `http-client` crate is used by all our HTTP client libraries (_shocking!_); it provides some basic functionality, but also some important Habitat-specific tooling around SSL certs and proxying.

It currently lives in the `habitat` repository, but is used by our `builder-*-client` crates, as well as our `github-api-client`, which lives in the `builder` repository, which is an odd state of affairs.

Since it provides some basic Habitat-specific functionality, there's an argument to be made for moving it over to the `core` repository, which both `habitat` and `builder` repositories consume already; it shouldn't move to its own repository because it depends on our `core` crate itself, which could set up some odd dependency issues.

**Comment by christophermaier** [comment]
See also: https://github.com/habitat-sh/habitat/issues/4725

**Comment by raskchanky** [comment]
Yes, I'm definitely in favor of this.  In my mind, `http-client` fills a role for service specific API clients the same way `core` fills a role for things like `hab` and `sup`.

**Comment by christophermaier** [comment]
This is done.
