### ISSUE TITLE
habitat thinks it is supervising PID 0

### ISSUE THREAD

**Issue by jaym** [habitat-sh/habitat#4735]
A few times, we've gotten into a state where habitat is supervising a service, and it at some point writes 0 the that services PID file. In turn, it ends up thinking its supervising PID 0. It thinks that process always exists, and thus cannot bring up the actual service until the PID file is removed.

Our unit file gives it 60 seconds to go down. After 60 seconds, hab is SIGKILLED. A pattern seems to be that this happens when systemd calls `hab sup term` and then the 60 second timeout is hit.

hab-sup 0.54.0/20180221023448

**Comment by christophermaier** [comment]
I stumbled on a lead for this a bit ago... our `is_alive` check essentially runs `kill(pid, 0)` from `libc`. That `0` means to check if `pid` is alive, but if `pid` itself is `0`, then that means we're running `kill(0, 0)`, which basically means "check if the current process calling this is alive", which will always return true.

Thus, when the Supervisor thinks it's supervising a process with a PID of 0 (something that is impossible), it is actually "supervising" _itself_. :scream:

How the Supervisor comes to think that `0` is the "pid" it's supposed to be checking remains a bit mysterious, though. It seems that the only ways that might happen would be if the Launcher itself somehow returned a `0` when it started the process, or if a service's pidfile were to contain a `0`.

Further research is needed.

**Comment by christophermaier** [comment]
Closing this, since it should be addressed by https://github.com/habitat-sh/habitat/pull/7214; feel free to reopen if that's not the case.
