### ISSUE TITLE
[On-Prem Depot] Studio should support offline mode

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4765]
In order to better support developers who are not online (or have locked down/airgapped connectivity), we should support an ‘offline’ mode for the Habitat Studio so that it can function even when connectivity is not available to either an On-Prem Depot or the public Builder site.

**Comment by themightychris** [comment]
Could an offline mode for the studio also work without an on-prem depot, just checking the local artifact cache for available packages? If I've started up and built in it before, I should be able to start back up in offline mode and make use of the already downloaded package versions.
