### ISSUE TITLE
Hab studio rm can remove unexpected directories

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4774]
I don't have a repro of this, but ran into this issue today (using hab 0.54)

Removal of my builder dev studio (on a VMWare VM) ended up removing things that it shouldn't have, with the result that the entire VM was rendered inoperable (VMWare Tools scripts, and other system files looked like they were removed).

I suspect we might have some bug with removing mount points, where it incorrectly tried to remove mount points that were outside of the studio.  That seems to be the only thing that could have caused files outside of the studio to get removed.

**Comment by james-stocks** [comment]
I don't know if it's the same issue @chefsalim , but I see similar when working with the [chefes/buildkite](https://hub.docker.com/r/chefes/buildkite) image.

Reproduction steps:
1. Clone https://github.com/habitat-sh/core-plans and cd into it
2. (this step is to follow what our public CI does on my laptop) `docker run --privileged=true -it -v $(pwd):/workdir -w /workdir chefes/buildkite bash`
3. Inside the docker container, build a package e.g. `hab pkg build ant`
4. When the package build completes, try a `hab studio rm`

There are a bunch of errors and warnings but most notably the current directory (the `core-plans` clone) gets wiped out!
