### ISSUE TITLE
Document Jenkins + on-prem Habitat depot workflow

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4775]
According to our doc activity data, our users search for 'Jenkins' in the docs but receive no result. We need to add the documentation.

**Comment by brewn** [comment]
I don't know that we have this information just from failed search results, but it'd be useful to have a discussion about what we at least thin is the user story for people searching this. I'm guessing they're trying to figure out how to use core/jenkins, as opposed to trying to understand how to use Jenkins as a pipeline for Habitat.

**Comment by tashimi** [comment]
@brewn specifically, what I'm looking for here is "How to use Jenkins to build Habitat packages" as part of a Jenkins + on-prem Habitat depot workflow
