### ISSUE TITLE
[documentation] Update Docs to Reflect Dependency on Upstream Docker for Linux Users

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#4780]
That is a super long issue title...

Anyways, point is - there are forks of the docker engine floating around out there including one maintained by red hat. This came to light here: https://github.com/habitat-sh/habitat/issues/4094

In discussion with @fnichol and @elliott-davis  we determined that the right course of action (at least for now) is to update the docs to reflect a requirement of using "Vanilla" docker engine to be within support. This could change in the future but for now adding a link to our downloads page for linux users that calls out this dependency seems a reasonable course of action.

**Comment by brewn** [comment]
Yep! Closing.
