### ISSUE TITLE
Update Habitat Operator for Kubernetes links

### ISSUE THREAD

**Issue by tashimi** [habitat-sh/habitat#4790]
We've moved the Habitat Operator for Kubernetes into the Habitat github repo, and that's where it's going to be maintained and iterated on going forwards.

We need to:

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] update all links in habitat.sh/kubernetes

- [x] update links in blog posts

- [ ] update links in Kinvolk blog posts (@asymmetric & team)

- [x] update kinvolk/habitat-operator to point to habitat/habitat-operator (@asymmetric & team) 
- probably other things I haven't thought of
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by tashimi** [comment]
#4820 updates the step by step blog post

**Comment by raskchanky** [comment]
We've deprecated the Habitat Operator for Kubernetes so it will not be maintained or iterated on at all in the future.
