### ISSUE TITLE
[www] Add video graphics

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4792]
Add thumbnail, slides, and end screen graphics to the overview video for the home page.

The two graphics ending in **-yt** are in standard YouTube dimensions. 
- One is a [YouTube thumbnail](https://support.google.com/youtube/answer/72431?hl=en)
- the second (if possible) is a custom [YouTube end screen](https://support.google.com/youtube/answer/6388789?co=GENIE.Platform%3DDesktop&hl=en).

The other three PNGs are for adding directly into the video:
- habitat-overview-title.png is the initial screen for the first few seconds
- habitat-overview-infographic.png can be used either just after the title or before the end screen (or both)
- habitat-overview-end-slide.png can be used at the end of the video IF we can't do the YouTube specific end screen (mentioned above).

[habitat-overview-video-graphics.zip](https://github.com/habitat-sh/habitat/files/1835149/habitat-overview-video-graphics.zip)

**Comment by ryankeairns** [comment]
@cnunciato one other small request while you're poking around the video... Could you change the title to Build, Deploy, and Manage with Habitat (5:33)?

The embedded video does not show the time which was an important factor in users deciding whether or not to watch the video, so I was thinking we could just put it right into the video title.

**Comment by cnunciato** [comment]
Here's the finished product: https://www.youtube.com/watch?v=VW1DwDezlqM
