### ISSUE TITLE
On-prem depot usage data

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4799]
Following are potential metrics and tools that will tell us if people are installing the on-prem depot and if they're successful using it. The Automate team is using Telemetry/Segment/Heap to track similar items, we should chat with them about their approach and where we can potentially tie-in or replicate it (related: talk about how users enable/disable telemetry... last I was involved, this was done via the CLI for Automate).

*Potential metrics:*
- install completed
- who owns it (Automate license ID?)
- number of unique users
- number of sign-ins (?)
- number of origins
- number of packages (also by origin, including core)
- clicks on promote button
- enabled & disabled feature flags 
- what version are they running of Builder, Depot, Supervisor, Studio
- what platforms are they using & versions of platforms
- what browsers are they using to access 
- information about raw numbers of depots, build nodes, supervisors, studios, being managed, split up by number of rings, applications, environments 
- number of applications being deployed by habitat 

*Tools:*
- Heap (via Segment)
- GA (via Segment)
- Statuspage? (link to status page AND status indicator in the app)
- ~Intercom~ (presuming we won't use this as we've not staffed and monitored it on the public site yet) 

*Instructions:*
- what does the user, installing the depot, need to do to enable metrics (Telemetry)?
- can we leverage/acknowledge the Automate Telemetry setup?

**Comment by ryankeairns** [comment]
@cnunciato @tashimi @chefsalim We can use this issue to discuss what data we'd like to capture from on-prem depot installs. I have added some top-of-mind things, feel free to edit my initial text.

**Comment by cnunciato** [comment]
After chatting with Ryan, we're thinking it should suffice to use the `company.id` and `company.name` fields for this. I'm assuming both will be set as Habitat config items, either through some automated installer or manually, so Builder UI and services can make use of them.

**Comment by chefsalim** [comment]
Issue moved to [habitat-sh/builder #329](https://github.com/habitat-sh/builder/issues/329) via [**ZenHub**](https://www.zenhub.com/)
