### ISSUE TITLE
hab config clear ?

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#4804]
Is there a way to clean something done with the help of:
```
hab config apply --peer <per_ip> my.toml
```
For example, I again want to use the default value from the package

**Comment by rsertelon** [comment]
Hi @guskovd have you tried with an empty toml file? :thinking:

**Comment by guskovd** [comment]
thank you! it works!

**Comment by rsertelon** [comment]
Glad I could help :)
