### ISSUE TITLE
hab bldr job status looks broken

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#4810]
hab bldr job status --origin core    

error: The following required arguments were not provided:
    <GROUP_ID>

USAGE:
    hab bldr job status <GROUP_ID|--origin <ORIGIN>>

For more information try --help

--

Also, there is a report from #general that it is timing out on bldr.habitat.sh

**Comment by rsertelon** [comment]
To add information, it times out for the core origin. Works fine with mine (rsertelon)
