### ISSUE TITLE
Make it easier to run hab-sup in a non-systemd environment

### ISSUE THREAD

**Issue by jonlives** [habitat-sh/habitat#4818]
Getting hab-sup to run as a service on an environment without systemd is tricky for a couple of reasons:

* hab-sup has no built-in option to run in the background, so nohup must be used
* hab-sup has no configurable logging location, so redirecting stdout / stderr is necessary

It would be amazing if we could make the experience a little more simple for those in SysV Init land et. al. - supporting the above options would allow for a very simple init.d script to be used.

**Comment by mwrock** [comment]
It seems like it may be helpful to add a `-daemonize` flag that would wire up the sup in the background but we also want to be cautious about adding too many ways to run the supervisor.

**Comment by jonlives** [comment]
Agreed - I think just adding the --daemonize flag would suffice here though, will make it much easier to create init scripts for older operating systems

**Comment by Atalanta** [comment]
There's support for Debian-flavoured sysvinit in the Habitat cookbook, but not for CentOS:

https://github.com/chef-cookbooks/habitat/blob/master/templates/sysvinit/hab-sup-debian.erb

Not sure how much work is involved in adding `-d`, but if it supporting sysvinit can be done without altering the supervisor, I'd prefer it.

Right now, if I had to run supervisor on a non-systemd system, I'd probably use runit, but I get that there may be some opposition to installing another non-os supervisor just to run another non-os supervisor.
