### ISSUE TITLE
Automatically generate template render context documentation

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4824]
#4823 introduced a JSON Schema definition of our rendering context. It would be great if we could replace the hand-maintained documentation at https://www.habitat.sh/docs/reference/#template-data with documentation extracted from the schema itself.

Bonus points for adding examples to the schema.

**Comment by cnunciato** [comment]
I'll bet we could generate the hints for the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=cnunciato.habitat) as part of this, too -- I'll take a look at that as well.
