### ISSUE TITLE
Update the infographics URLs

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4857]
Because the URL of the infographics (currently called **diagrams**) will be changing from `/docs/reference#infographics` to `/docs/diagrams`. We need to update the existing URLs that contains `infographics`.

Dependent PR #4856

cc @cnunciato

**Comment by cnunciato** [comment]
Now that I look at this, we'll need to do this at the same time. I've got a commit handy that I can push onto your Diagrams branch containing all the link-fixer-upping. We'll just merge them both at the same time, and everything should be fine.
