### ISSUE TITLE
Habitat `pkg_license` implementation does not allow for valid compound SPDX licenses

### ISSUE THREAD

**Issue by tduffield** [habitat-sh/habitat#4860]
In the Habitat documentation, it specifies that you can provide an array of valid SPDX values.

https://github.com/habitat-sh/habitat/blob/7e012fa2744725a96585758311233297b26a623a/www/source/partials/docs/_reference-basic-settings.html.md.erb#L35-L38

However, the [SPDX 2.1 specification](https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60) requires that multiple licenses be separated with a compound word like OR, AND, or WITH.

As it stands, the `License` field in Habitat is not currently representing the true licensing requirements of software that has multiple license options, or requires that multiple licenses be adhered to.

**Comment by tashimi** [comment]
Should this be a core-plans RFC, or a docs ticket, or?

**Comment by rsertelon** [comment]
I think it belongs to core-plans RFC indeed.
