### ISSUE TITLE
Habitat binary for MacOS is not self-contained like non-MacOS binaries are because of OpenSSL

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#4871]
This was revealed by #2950 and papered-over by habitat-sh/homebrew-habitat#9.

On non-MacOS platforms, we go through some additional steps to set up an OpenSSL certificate chain without having to rely on the system certificates (since not all places Habitat will eventually be installed necessarily have certificates installed, or in the same places). Briefly, we defer to `SSL_CERT_FILE` or `SSL_CERT_DIR` if set, then fall back to our own `core/cacerts` package if it is installed, falling back finally to a certificate that we write out into `~/.hab/cache/ssl/cert.pem`, the contents of which are baked into the `hab` binary at build time. This basically allows the binary to be completely self-contained and independent, bootstrapping itself, so to speak, until such time as a `core/cacerts` package is around. See https://github.com/habitat-sh/core/blob/60720b714769b1aa6c0a6f4fa8e6d022efa71102/components/http-client/src/lib.rs#L59-L83 for concrete details.

We don't do this on MacOS, primarily because we don't yet have other packages building on that platform; the `hab` binary is the only thing we ship there. There, we simply defer to OpenSSL to resolve certificates according to its standard procedures. Because Apple has deprecated OpenSSL in favor of its own TLS implementation, this can cause issues, because `hab` will not be able to find certificates! This can be worked around in a few ways. First, you can specify `SSL_CERT_FILE` and / or `SSL_CERT_DIR` environment variables, which our OpenSSL binding will honor. Second, you can use Homebrew to install `openssl`, which generates a `/usr/local/etc/openssl/cert.pem` based on your `SystemRoots` keychain. This will in turn be found by `hab`. With habitat-sh/homebrew-habitat#9, `openssl` is now a recommended dependency of `hab`, which means that if you install `hab` with Homebrew, you'll be guaranteed to get a working OpenSSL environment automatically. As such, Homebrew is the recommended way of installing `hab` for MacOS.

While this works, it would be nice to have the `hab` binary be completely self-contained on MacOS just as it is on other platforms. Solving this problem like we have for other platforms likely entails building MacOS packages (specifically `core/cacerts`!), and should be a part of future efforts to fully support MacOS as a Habitat platform.

**Comment by baumanj** [comment]
Valid as of v0.57

**Comment by javiertoledos** [comment]
Just installed hab version 0.62.1/20180905002018 using brew and gives me the openssl error.

**Comment by javiertoledos** [comment]
Clarifying, just installing the hab via brew is not enough, setting up also the environment variable `SSL_CERT_FILE` makes this work

**Comment by nellshamrell** [comment]
I ran into the same thing as @javiertoledos on a Mac - I was able to do this as a workaround:

```
export SSL_CERT_FILE=/usr/local/etc/openssl/cert.pem
```

**Comment by christophermaier** [comment]
This is no longer necessary, after changes to how we manage SSL certs, and the removal of `openssl` from Homebrew (https://github.com/habitat-sh/homebrew-habitat/pull/35)
