### ISSUE TITLE
Adding new service group member does not drop (gossip) service files

### ISSUE THREAD

**Issue by gfodor** [habitat-sh/habitat#4877]
Hi there, we are running a small Habitat ring on Ubuntu linux on AWS and upload a few files to the ring (certificates, key files) for one of our service groups. It seems that when a new node comes online and joins the service group, the configuration is generated properly but none of the service files are dropped in place until we re-run `hab file upload` to re-upload them to the ring. It seems like the desired behavior is that the service files (like the configuration files) should be generated when a service group is joined by a new node. I've confirmed that the service files are available in the ring state (via `/census`) at the time the node joins.

**Comment by gfodor** [comment]
Oh it's worth noting that these files are uploaded via `file upload` using a (minor) fork of `hab` that we are running to temporarily get around the 4k file size limit until https://github.com/habitat-sh/habitat/issues/4066 is resolved. So if there is some reason the ring will ignore files beyond 4k at service group start time that could be the issue -- however as best I could tell the only place where this limit is checked is at upload time.

**Comment by wduncanfraser** [comment]
This definitely would be nice to have and confirmed the behavior on standard hab.

**Comment by adamhjk** [comment]
I'm having trouble reproducing this error.

If I do the following:

* Start 3 docker containers from 'ubuntu', install habitat on them
* Run a supervisor on one of them, with core/redis as the service.
* Start the other two, peered to the first, also running core/redis
* From a fourth location, I run `hab file upload --peer 172.17.0.2 redis.default 1 /tmp/mystuff.txt` 
* See that the file is distributed to `/hab/svc/redis/files/mystuff.txt` on all three
* Start a fifth supervisor, peer it to the ring running core/redis - the mystuff.txt file gets distributed

What's not working for y'all?

**Comment by adamhjk** [comment]
From slack, for posterity:
```
Duncan Fraser [1:55 PM]
should I be able to pressed a file for a service that isn't up yet in the ring? For example what I was initially trying to do, as I have a group managing concourse that contains concourse-web, postgresql, concourse-proxy, and arbitrary amount of concourse-worker. Services are on seperate VMs that are chef managed, what I was curious was if I could have part of a recipe say render out all the needed files onto the master node and then upload it to the ring (Which, when spinning up the cluster with terraform, workers come up after web, etc)
```

**Comment by adamhjk** [comment]
I see this behavior working just fine too, for what its worth.

**Comment by adamhjk** [comment]
Ok - looks like there is a bug in here, and it's that if you pre-seed a service group with a file, start a supervisor without the servcie group running, then later add a service group, you will fail to render.

In general, the issue is directly related to the way we keep track of files to be written, and when we decide we have written them out. To make a long story short, it's busted. :)

**Comment by baumanj** [comment]
Valid as of v0.57

**Comment by gfodor** [comment]
we are still experiencing this. our workaround is to have a shell script query the census on boot to dump these files, but this is problematic from a security perspective (we'd like to shut the census off on our nodes) so it'd be great if this could be fixed sometime soon.

**Comment by y-me-y** [comment]
This is critical to a service group. As an alter Is there any way with the redact feat turned on we can force a file sync?

**Comment by jsirex** [comment]
Me to seeing kind of this issue.
But I can reproduce it directly in studio with single supervisor.

Disclaimer: I'm using community fork `bio`, but I'm pretty sure it is also applies to `hab` because I didn't find any suspicious in code.

1. Start studio
2. Upload any file for your service by `hab file upload`
3. Load and start service

Actual result:
Service was loaded, but files were not rendered.

Expected result:
Files were rendered, service was loaded.

Blink issue:

1. Start studio
2. Load service
3. Do `hab file upload` after

Actual result: files were not rendered.
Re-Uploading files during running service mostly (2/3) fixes the issue.

I also inspected sup file (/hab/sup/default/data/e172b395f2d24d09aec2b36772097629.rst) and confirm that files are inside and supervisor knows them. and my files are less then 4K (one 2.7k, another 1.7k)

**Comment by jsirex** [comment]
This production critical  issue can lead to a catastrophic if you have service, which relays on files. If you have some applications' encryption keys or some file-based settings, service without these files can potentially start with default settings and corrupt your data or infra. Same as if you do `hab svc load` *before* `hab config apply`.

**Comment by sean-horn** [comment]
This has struck a customer with a distributed Hab Depot system. They have multiple bulder-api installs where this type of node all join the same ring and should pick up the same config. 

builder-api maintains a collection of files under /hab/svc/builder-api/files. A very important set of files, essential for verifying requests that should be authenticated are the public and private key files listed in the error here. When they are missing, no authenticated requests can succeed for things like package downloads, origin key updates, and other request types.

```
Mar 18 19:25:13 ito049716 hab[57562]: builder-api.default(O): [2020-03-18T23:25:13Z DEBUG habitat_core::crypto::keys::box_key_pair] Decrypt key path = /hab/svc/builder-api/files
Mar 18 19:25:13 ito049716 hab[57562]: builder-api.default(O): [2020-03-18T23:25:13Z DEBUG habitat_core::crypto::keys::box_key_pair] Can't find public key for name_with_rev bldr-20190918220205: No such file or directory (os error 2)
Mar 18 19:25:13 ito049716 hab[57562]: builder-api.default(O): [2020-03-18T23:25:13Z DEBUG habitat_core::crypto::keys::box_key_pair] Can't find secret key for name_with_rev bldr-20190918220205: No such file or directory (os error 2)
Mar 18 19:25:13 ito049716 hab[57562]: builder-api.default(O): [2020-03-18T23:25:13Z DEBUG builder_core::integrations] Unable to decrypt with bldr key pair, err=CryptoError("No public or secret keys found for name_with_rev bldr-20190918220205")
```

Solution: 
Picking up the same config is where the failure happened. It should be easier to do that by not having to care about the ordering of a ring startup, current state of the ring members, or initial config of the ring members.
