### ISSUE TITLE
Initial prototype dashboard with Habitat Supervisor health information

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4889]
In an effort to better expose Habitat data for an application (i.e. Supervisor data), we would like to prototype how this would look and work 3rd party tools like Splunk and Weave.works.

The prototype would use data from sources such as our running public Builder instance and/or using our sample apps (e.g. Node, .net, java).

**Comment by ryankeairns** [comment]
Looking through sample census data using the current HTTP endpoint (on localhost), the following data points seem most relevant for visualizing the Builder application:

- The top-level census group (containing 9 groups)
- The individual service groups (sharing a common member_id)
- Within each service group:
  - member_id
  - pkg info (which pkg the group is running) --> origin, name, version, release
  - application & environment are interesting, but currently `null`
  - whether it's a leader or follower
  - sys info --> ip, ports, hostname
  - whether it's alive, suspect, confirmed, departed
  - cfg (if anything is available)
- service_files (names of keys used, etc)

From this, we could potentially present a visualization of the app that shows how the service groups are connected and allow the user to get additional info (listed above) for each instance (`population` entry) within said group.

**Comment by ryankeairns** [comment]
@cnunciato After looking through the docs for Weave Scope, it appears the data visualized by default it some standard info from the containerized application. Upon further reading, you can generate custom metrics by writing Plugins. 

It seems we could use a custom Plugin to feed habitat-specific data (i.e. census data) into the Weave Scope UI. More information on how this works can be found here --> https://www.weave.works/docs/scope/latest/plugins/

**Comment by ryankeairns** [comment]
@tashimi The Splunk prototype is less obvious to me than the Weavworks alternative. Given that Splunk has many products (and cost), do you have any more insights on which product or solution we might use to visualize a habitat application/supervisor data? 

cc: @cnunciato

**Comment by tashimi** [comment]
@ryankeairns I've checked in with @jamesc to see if he has some ideas, what we've done in the past is: 
- for Chef: https://splunkbase.splunk.com/app/2687/
- cookbook integration to Splunk: https://supermarket.chef.io/cookbooks/chef-splunk

I think open questions are: 
- Is splunkbase the best spot for us to put a new dashboard integration, or is there another spot?
- how do we automate the Hab to Splunk data flow

**Comment by tashimi** [comment]
From James: 

- Easiest way to get started with Splunk integration is probably via the HTTP collector they have.
- Russell put together some demos of this using an Azure function (or AWS lambda).

**Comment by jamesc** [comment]
Some details from Russell on how he connected Automate. https://blog.turtlesystems.co.uk/2017/12/13/Splunking-with-Chef-Automate/

**Comment by cnunciato** [comment]
Here's the repo for this:

 https://github.com/cnunciato/habitat-splunk-hec

.. and accompanying demo:

https://www.youtube.com/watch?v=W-40gCJwkFE
