### ISSUE TITLE
[hab] Interrupted pkg install can leave package in bad state

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#4897]
If `hab pkg install` is interrupted when unpacking a hartifact, the result can be a situation in which `hab` will report the package as installed despite the installation being unusable.  Reproducing this by hand requires sufficient luck:

```
# hab pkg install core/erlang
» Installing core/erlang from channel 'stable'
☛ Verifying core/erlang/20.0/20171014214153
→ Using core/acl/2.2.52/20170513213108
→ Using core/attr/2.4.47/20170513213059
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
→ Using core/linux-headers/4.3/20170513200956
→ Using core/ncurses/6.0/20170513213009
→ Using core/openssl/1.0.2l/20171014213633
→ Using core/sed/4.2.2/20170513213123
→ Using core/zlib/1.2.8/20170513201911
^C
root@automate-deployment:/opt/automate-deployment# hab pkg exec core/erlang erl
✗✗✗
✗✗✗ `erl' was not found on the filesystem or in PATH
✗✗✗
```

Attempts to reinstall the package succeed:

```
# hab pkg install core/erlang
» Installing core/erlang from channel 'stable'
→ Using core/erlang/20.0/20171014214153
★ Install of core/erlang/20.0/20171014214153 complete with 0 new packages installed.
# hab pkg exec core/erlang erl
✗✗✗
✗✗✗ `erl' was not found on the filesystem or in PATH
✗✗✗
```

The user must remove the package contents from `/hab` and reinstall:

```
# rm -rf /hab/pkgs/core/erlang/
# hab pkg install core/erlang
» Installing core/erlang from channel 'stable'
☛ Verifying core/erlang/20.0/20171014214153
→ Using core/acl/2.2.52/20170513213108
→ Using core/attr/2.4.47/20170513213059
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
→ Using core/linux-headers/4.3/20170513200956
→ Using core/ncurses/6.0/20170513213009
→ Using core/openssl/1.0.2l/20171014213633
→ Using core/sed/4.2.2/20170513213123
→ Using core/zlib/1.2.8/20170513201911
✓ Installed core/erlang/20.0/20171014214153
★ Install of core/erlang/20.0/20171014214153 complete with 1 new packages installed.
# hab pkg exec core/erlang erl
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1>
User switch command
 --> q
```

My assumption is that the root cause is that the unpack function (https://github.com/habitat-sh/core/blob/master/components/core/src/package/archive.rs#L264) is unpacking directly to the final location and the other code in hab to detect if a package is installed doesn't do any verification of the contents.

One solution may be to unpack the archive into a temporary directory and then atomically rename() it once the unpack is complete.

**Comment by baumanj** [comment]
Appears valid bases on code inspection it v0.57, keeping.

@stevendanna's suggestion:
> One solution may be to unpack the archive into a temporary directory and then atomically rename() it once the unpack is complete.

sounds 💯 to me. That should be standard practice for all these types of filesystem tasks.

**Comment by stevendanna** [comment]
@baumanj One small note on my suggestion:

You will want to make sure the temporary directory is in the same parent directory as the directory you are eventually going to rename it too.  rename() is only atomic on the same filesystem and being in the same base directory helps ensure that.
