### ISSUE TITLE
Studio should import `auth_token` from cli.toml

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#4908]
After running `hab setup`, there will be an `auth_token` key in `~/.hab/etc/cli.toml`. This is automatically used for operations outside the studio:
```
➤ hab pkg promote jbauman/np-mongodb/3.2.9/20180412155926 stable
» Promoting jbauman/np-mongodb/3.2.9/20180412155926 to channel 'stable'
✓ Promoted jbauman/np-mongodb/3.2.9/20180412155926
```
but not inside the studio:
```
[2][default:/src:0]# hab pkg promote jbauman/np-mongodb/3.2.9/20180412155926 stable
✗✗✗
✗✗✗ No auth token specified
✗✗✗
```
This was surprising to me and seems seems inconsistent since the studio *does* access the `origin` key from `cli.toml` to import keys and set `HAB_ORIGIN`:
```
[4][default:/src:1]# echo $HAB_ORIGIN
jbauman
```
This was on Mac OS with hab 0.55.0/20180321215236.

**Comment by cnunciato** [comment]
I agree, and it's also inconsistent in that we do honor `HAB_AUTH_TOKEN` on studio entry when it's set. Seems like these should behave similarly.

**Comment by SkipKeats** [comment]
@baumanj : Thanks, but that does not seem to have worked. Now I receive a 403 error:
[33][default:/src:0]# hab pkg upload -z $HAB_ORIGIN ./results/wilfredk-webapp-0.2.0-20180509192311-x86_64-linux.hart
✓ Signed artifact with wilfredk-20180509184450.pub
» Uploading public origin key wilfredk-20180509184450.pub
    79 B / 79 B | [=====================================================================================] 100.00 % 592 B/s
✗✗✗
✗✗✗ [403 Forbidden]
✗✗✗

**Comment by baumanj** [comment]
Typically `$HAB_ORIGIN` is the name of your origin, not your auth token. The `-z` argument should be your personal access token generated from https://bldr.habitat.sh/#/profile.

Don't share it here, since it gives access to your builder account, but it should be 173 characters starting with `_` and the rest base64 encoded.

**Comment by mkorejo** [comment]
I'm on Learn Chef Rally right now going through the [Try Habitat](https://learn.chef.io/modules/try-habitat#/) module, hitting this problem. The lesson seems to highlight studio's ability to read from local config to set env variables, but then this.

**Comment by qubitrenegade** [comment]
I can start taking a look at this after ChefConf if we're on board with loading HAB_AUTH_TOKEN in the studio (I see the S-needs-discussion tag).

**Comment by baumanj** [comment]
That would be awesome, @qubitrenegade. I don't see any opposition to going forward with this, but I'll ping the team to double check before you invest your time.

**Comment by baumanj** [comment]
No objections from the team, @qubitrenegade. Let us know if there's anything you need to support the work on this.
