### ISSUE TITLE
loss of initial peer's `/hab/sup` data directory on restart causes ring dissolution

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat#4911]
## Description
In certain situations, this problem can occur when following the [best practices](https://www.habitat.sh/docs/best-practices/#running-a-habitat-container-as-a-non-root-user) for running a habitat container as a non root user.

When stopping the initial peer container, should the contents of the `/hab/sup` mounted directory be removed, the ring will be prevented from re-establishing on container restart.

In that situation, the other members of the ring will never see the restart of the the initial peer and will continually loop on waiting for service binds.

The fix for that scenario is to stop all the member containers in the ring, remove each member's `/hab/sup` data and then restart all.  This appears to create a "clean slate" for the ring to be re-created as if from scratch.

## Recreation of data loss

Execute the following:
```
#!/bin/bash

docker volume rm sup_state
docker volume rm svc_state

docker volume create --driver local \
       --opt type=tmpfs \
       --opt device=tmpfs \
       --opt o=size=100m,uid=888888 \
       sup_state

docker volume create --driver local \
       --opt type=tmpfs \
       --opt device=tmpfs \
       --opt o=size=100m,uid=888888 \
       svc_state

docker run --rm -it \
       --name="redis" \
       --user=888888:999999 \
       --mount type=volume,src=sup_state,dst=/hab/sup \
       --mount type=volume,src=svc_state,dst=/hab/svc \
       --detach \
       redis:latest

docker exec -it redis touch /hab/sup/IMPORTANT.dat
docker exec -it redis ls /hab/sup
docker stop redis
docker volume ls

docker run --rm -it \
       --name="redis" \
       --user=888888:999999 \
       --mount type=volume,src=sup_state,dst=/hab/sup \
       --mount type=volume,src=svc_state,dst=/hab/svc \
       --detach \
       redis:latest

docker exec -it redis ls /hab/sup
docker exec -it redis ls /hab/sup/IMPORTANT.dat

docker stop redis
```

## Expected output

Expect the `IMPORTANT.dat` file to exist after re-start

## Actual

`IMPORTANT.dat` is no longer in `/hab/sup`

```
[centos@ip-172-31-20-246 ~]$ sudo ./doit.sh
sup_state
svc_state
sup_state
svc_state
7136ea365d9dccbd1a299927d280546cb044faefb5a4ceb716fb2210f7186c6f
IMPORTANT.dat
redis
DRIVER              VOLUME NAME
local               sup_state
local               svc_state
5bf7d7df67d80a9e917ec77fa4f101c7a724b42945a752576903078d16e6bbac
ls: cannot access /hab/sup/IMPORTANT.dat: No such file or directory
redis
[centos@ip-172-31-20-246 ~]$
```

## Steps for a Repro of ring failure

Bring up a habitat ring with an initial peer with `/hab/sup` mounted. Stop the initial peer and remove the contents of `/hab/sup` directory mount point.  Restart the initial peer and you will witness that the other members continually loop on waiting for service binds.

## Analysis

This appears to be a known and somewhat [disputed](https://github.com/moby/moby/issues/17907) characteristic of docker volumes.

In the field, I've worked around this problem by using docker `bind` [mounts](https://github.com/chef-customers/dockerized-chef-services/blob/master/terraform/docker-chef.sh#L221-L222) from persistent directories on the Host as opposed to docker `volumes` so that the content of `/hab/sup` is preserved. Subsequent restarts of the initial peer do not result in ring dissolution problems.

Often this is masked in docker compose scenarios because `--rm` is not used (at least by default) there.

**Comment by baumanj** [comment]
Confirmed valid in v0.57

**Comment by christophermaier** [comment]
@jeremymv2 It seems as though this is more of a Docker issue than anything else. Provided that the container is brought up again and peered to some other Supervisor, it should be able to rejoin the network.

The odd thing is that it appears that a fix for this was merged [years](https://github.com/moby/moby/pull/19568) ago, but I still see the behavior.

If you've got additional information about this as a Habitat bug, I'd like to hear it. In the meantime, I'm going to close this issue. Thanks!
