### ISSUE TITLE
Date format in CHANGELOG.md is incorrect

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#4913]
The dates should be presented in an unambiguous format which can be understood by countries other than the US such as `YYYY-MM-DD`.

This might be an opinion, except it's not.

I'll fight for this one.

---

Context: I've been trying to document some backwards compatible fixes in the codebase and am trying to reference certain Habitat releases and their dates. Talk about confusing, oi!

**Comment by raskchanky** [comment]
Yeah, 100% agree here.  We should be using ISO 8601 everywhere, imo.
