### ISSUE TITLE
Builder timeout is too short

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#4922]
Hello!

I am currently not able to build the [llvm core plan](https://github.com/habitat-sh/core-plans/tree/master/llvm), builder times out when building it and the packages that are dependent on it.

I noticed that we define the timeout as 90 minutes [here](https://github.com/habitat-sh/builder/blob/master/components/builder-jobsrv/src/server/worker_manager.rs#L47).  Could we increase this number?

**Comment by bdangit** [comment]
For sure need to set a larger timeout, but also need to make sure you need a machine tons of memory.  I forget how much was required.  @rsertelon and @eeyun might be able to shed some light.

**Comment by nellshamrell** [comment]
Yep, I'm building it manually on my local machine, then uploading it

**Comment by mwrock** [comment]
closing since this is really a builder concern and the immediate issue with llvm was resolved
