### ISSUE TITLE
[package] Update for dotnet-core 2.1

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#4931]
Hi there :)

.Net Core is the new reference implementation of Microsoft`s .Net platform.
 
The current version on Habitat is 1.1.2, the current release is 2.0.6 and 2.1 preview is available as well: https://github.com/dotnet/core/releases

While Mono and .Net itself still get updates from Microsoft, is .Net Core the new and shiny thing in the .Net ecosystem, since it re-implements the whole thing in a modern, cross platform and lean way.

Since Habitat focuses on server deployments and because .Net plays a major role there, is it potentially beneficial for us to support it.

**Comment by mwrock** [comment]
I've been meaning to refresh those packages. I have just pushed updated runtime and sdk packages to the depot for both the stable and preview versions (see https://github.com/habitat-sh/core-plans/pull/1378). I have also refactored our [dotnet-core sample application](https://github.com/habitat-sh/habitat-aspnet-sample) to work on the 2.0 runtime.
