### ISSUE TITLE
Replace Habitat logo on Chef-managed web properties 

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#4941]
* [x] [Chef home page](https://www.chef.io/) 
* [x] [Chef Application Automation page](https://www.chef.io/solutions/application-automation/) 
* [x] **Products** nav dropdown
* [x] [ChefConf home page](http://chefconf.chef.io/)

**Comment by ryankeairns** [comment]
Ticket submitted to agency who handles chef.io and chefconf.chef.io updates.
