### ISSUE TITLE
`hab pkg exec` requires `.bat` extension to find batch files

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#4947]
On windows `.bat` files like `.exe` files can be launched without an extension from the command line. I recently got stumped when `hab pkg exec` could not find a batch file and after some random trial and error I found that including the `.bat` extension resolved the failuren to find it. This seems wrong and I would expect `hab pkg exec` to use the same resolution as the command line.

**Comment by btm** [comment]
This is probably related to how Rust shells out, but @robbkidd found some magic used in the RubyGems installer on Windows that could help, maybe?

```
:""||{ ""=> %q<-*- ruby -*-
@"%~dp0ruby" -x "%~f0" %*
@exit /b %ERRORLEVEL%
};{ #
bindir="${0%/*}" #
exec "$bindir/ruby" -x "$0" "$@" #
>, #
} #
#!/usr/bin/env ruby
[ ... actual ruby code ... ]
```

https://chefio.slack.com/archives/CG26VF2KU/p1568770157022400

**Comment by mwrock** [comment]
I was just having a look at this. Interestingly in most cases, `hab pkg exec` works with `.bat` files without the need to include the `.bat` extension. What is problematic in many of the chef family of packages is that you have both `FILENAME` and `FILENAME.bat` in the same directory. So `hab pkg exec core/package FILENAME` breaks because habitat is trying to invoke the extensionless file.  That behavior actually makes sense on linux but is certainly a bug on windows.
