### ISSUE TITLE
Allow docker exporter to override default base image

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#4948]
Particularly in Windows images, there are some service scenarios that require a one time initialization of some global machine settings that can potentially take several minutes to run. For a docker image, this "one time" event becomes "every time".

The main scenario I am thinking of applies to any IIS application where the init hook has to install the IIS windows features because they are not installed on the default `microsoft/servercore` base image. This could be easily  solved if exporting IIS based services using the `micosoft/iis` docker image as a base which is simply the servercore image with IIS added.

There are certainly other strategies besides using an alternate base image that we could use to solve this that would be more involved but could also apply to a broader range of potential scenarios. For example,  have the exporter have the supervisor run the `init` hook of the service. This would ensure that any startup logic is completed but therr is not currently a mechanism to have the supervisor do this. That may be relatively straightforward to implement but also possibly unnecessary.

**Comment by gscho** [comment]
I would like to see this for Linux as well!

**Comment by mwrock** [comment]
I am closing this for now. With #5866 one can create an `install` hook that will be executed during the export allowing for more customization of the image which at least satisfies my scenarios and without the risk of inviting unhabetized state from a random base image.
