### ISSUE TITLE
[www] Minor textual format change for homepage flow diagram

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#4950]
- Capitalize the `p` in `plan` in the paragraphs
- Capitalize the `d` in `depot` in the paragraphs

**Comment by cnunciato** [comment]
Plan should not be capitalized, actually. But I agree Depot should.

**Comment by tashimi** [comment]
Style guide has been that Habitat, Supervisor, Builder, and Studio are capitalized; everything else is lowercase

**Comment by tashimi** [comment]
So for example it is Habitat Builder depot

**Comment by apriofrost** [comment]
Sounds good! @tashimi 
So that means we should just close the issue I think? @cnunciato

**Comment by cnunciato** [comment]
Yep, sounds like it!
