### ISSUE TITLE
[Documentation] Advise against using bashisms in hooks

### ISSUE THREAD

**Issue by Atalanta** [habitat-sh/habitat#4956]
In the studio, `/bin/sh` is `bash`:

```
stat /bin/sh
  File: '/bin/sh' -> '/hab/pkgs/core/bash/4.3.42/20170513213519/bin/sh'
```
This means that it's possible to get away with using `bash` syntax in hooks with a `/bin/sh` shebang.

For example:

`mkdir -p {{pkg.svc_var_path}}/{logs,cache,run}`

In a container, unless `core/bash` is explicitly a runtime dependency, `/bin/sh` will be Busybox's bourne shell:

```
$ docker exec -it 84938876a0ec /bin/stat /bin/sh
  File: '/bin/sh' -> '/hab/pkgs/core/busybox-static/1.24.2/20170513215502/bin/sh'
```

We should explicitly warn plan authors against using bash syntax unless genuinely needed, and if genuinely needed, to make sure they add a runtime dependency.

**Comment by baumanj** [comment]
It might be worth running a linter (along with validation against our JSON schema of data available to handlebars templates) against the hooks at build time. If you have something like:
```bash
#!/bin/sh

mkdir -p {{pkg.svc_var_path}}/{logs,cache,run}
```
it can warn against it:
```
➤ shellcheck -e SC1083 /tmp/test.sh 

In /tmp/test.sh line 3:
mkdir -p {{pkg.svc_var_path}}/{logs,cache,run}
                              ^-- SC2039: In POSIX sh, brace expansion is undefined.
```
Excluding 1083 ignores the lints related to the handlebars interpolation `{{…}}`.

We already have a [shellcheck habitat package](https://bldr.habitat.sh/#/pkgs/alasconnect/shellcheck/latest), so it shouldn't be too hard to integrate.

**Comment by eeyun** [comment]
I go back and forth on this. Some of core plans actually calls bash from the core/bash package in the shebang and then deps on bash to ensure its available at runtime. It's an unfortunate added dep but it also 100% guarantees hook behavior from test to runtime.
