### ISSUE TITLE
Sign In button should indicate the actual auth solution being used

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4959]
Currently, the button always shows the Octocat icon and the text 'Sign in with GitHub' even if you are using GitLab or BitBucket. This was discussed in https://github.com/habitat-sh/builder/pull/359 but was pushed off due to the urgency of unblocking a customer.

This is obviously confusing, so let's fix it up to show the correct icon and text.

_To-do_
* [ ] Add Bitbucket icon and text - Sign in with Bitbucket
* [ ] Add GitLab icon and text - Sign in with GitLab

**Comment by ryankeairns** [comment]
Thanks for pointing that out, I've added to checkboxes to the description for tracking purposes.. if it's done, then we'll check it off :)

**Comment by cnunciato** [comment]
Indeed, we have icons for GitHub, BitBucket and GitLab and it's all wired up based on the `oauth_provider` config value.

**Comment by raskchanky** [comment]
Can this issue be closed then?

**Comment by cnunciato** [comment]
![](https://d3vv6lp55qjaqc.cloudfront.net/items/3V1T2F0f112O2H152e3G/Screen%20Recording%202018-04-18%20at%2009.39%20AM.gif?X-CloudApp-Visitor-Id=aee8eca7dd7ef2e10e53a727c6872dc1&v=24c18238)

**Comment by cnunciato** [comment]
@raskchanky probably -- @ryankeairns these look okay to you? ^

**Comment by raskchanky** [comment]
One thing worth noting is that it's technically spelled "Bitbucket", not "BitBucket".

**Comment by cnunciato** [comment]
Ah, good to know -- I'll fix that and reference here.
