### ISSUE TITLE
Display reason for rebuild in the Builder web UI

### ISSUE THREAD

**Issue by ryankeairns** [habitat-sh/habitat#4960]
As a user, I want to see a reason for each new version/build, so that I can understand why my package was rebuilt.

The topic of **reasons for rebuild** was previously discussed as part of the Notifications design work and has come up in feedback from both internal and external users. Below are the types of reasons we previously discussed and a mockup of how they could be displayed on the Build Jobs page:

_Reasons would include_
- Manual rebuild (i.e. user clicked 'Build latest version' button in the UI)
- GitHub webhook/trigger (e.g. PR was merged)
- Dependency was rebuilt (e.g. 'CVE fix for xxx/xxx', 'New version of xxx/xxx', etc.)
- An initial build when the plan was connected (this may fall under GitHub trigger)

**Note:** the 3rd item above might necessitate the person initiating the job to enter a reason, else we just generically state the lowest level core/package that was rebuilt?

_Where to potentially place the reason text in the UI_
- Package detail (Latest tab)
- Versions tab
- Build output (top metadata box)
- Build Jobs tab [See Invision mockup](https://chef.invisionapp.com/share/C5E6NIURX#/262349769_package_Detail_-_Build_Jobs)

* [ ] Add a link to a separate API issue

**Comment by raskchanky** [comment]
Issue moved to [habitat-sh/builder #380](https://github.com/habitat-sh/builder/issues/380) via [**ZenHub**](https://www.zenhub.com/)
