### ISSUE TITLE
Change language around job group demotion

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4961]
When you demote a job group in interactive mode, after saving the file that pops up, you see a prompt like this:

`Demoting 7 package(s) to channel 'stable'. Continue?`

The `to` in that sentence should be `from`, so it reads:

`Demoting 7 package(s) from channel 'stable'. Continue?`

It should still say `to` when doing promotion, however.

**Comment by rsertelon** [comment]
Hmm, maybe it would be nice to be able to see the list too (behind a flag)?
