### ISSUE TITLE
A tool to validate .bldr.toml files

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#4970]
This is related to https://github.com/habitat-sh/builder/issues/389

It can be challenging to write a `.bldr.toml` file that behaves exactly the way you want it to because of the trickiness and subtleties of file globbing.  It would be spectacular to have a tool that users could run on a `.bldr.toml` file to check that it's actually going to match what they care about.

Given a sample `.bldr.toml` file like so:

```toml
[api]
plan_path = "habitat"
paths = [
  "src",
]
```

If we had something that would output information like this:

```
Builder will trigger new builds when any of the following individual files change:

src
```
it would be very easy to see that something is wrong, particularly if you're expecting to see something more like this:

```
Builder will trigger new builds when any of the following individual files change:

src/census.rs
src/lib.rs
src/command/mod.rs
src/command/shell.rs
src/sys/unix/abilities.rs
src/sys/unix/mod.rs
src/sys/unix/exec.rs
src/sys/unix/users.rs
src/sys/mod.rs
src/sys/windows/abilities.rs
src/sys/windows/mod.rs
src/sys/windows/exec.rs
src/sys/windows/users.rs
src/http_gateway.rs
src/fs.rs
src/schema.rs
src/manager/peer_watcher.rs
src/manager/sys.rs
src/manager/file_watcher.rs
src/manager/service_updater.rs
src/manager/service/mod.rs.rej
src/manager/service/spec.rs
src/manager/service/package.rs
src/manager/service/composite_spec.rs
src/manager/service/health.rs
src/manager/service/mod.rs
src/manager/service/dir.rs
src/manager/service/supervisor.rs
src/manager/service/config.rs
...
```

**Comment by christophermaier** [comment]
Other things such a tool would be good for:
* Find paths that once existed, but now no longer do (e.g., due to refactoring)
* catch misspellings
* call out when a `paths` entry needlessly duplicates the `plan_path`. An example:
```toml
[foo]
plan_path = "/components/foo"
paths = [
    "/components/foo/*"
]
```
* Formatting. Keeping entries alphabetized helps you find things more easily.

**Comment by christophermaier** [comment]
Useful, but not a high priority.
