### ISSUE TITLE
[builder] Support for more flexible container-registry publishing

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#4980]
Currently we publish all new packages automatically, when configured (regardless of channel), which doesn't work for users who want some control over their automated container deployments. We should extend our existing container publishing behavior to include:

* [ ] Click-based/on-demand publication of a selected package release (e.g., a package that already exists in the Depot)
* [ ] Automatic publication of packages when promoted to a specific channel (or channels)

**Comment by cnunciato** [comment]
See also this feature request: https://github.com/habitat-sh/builder/issues/376

**Comment by tashimi** [comment]
Chatted with @eeyun and the workers are currently only able to publish unstable builds. The dev-exp team plans to pick up the work to get workers to publish to other channels in a few weeks (post KubeCon), this will coordinated nicely with the work the bldr team will be doing on automatic channel promotion soon. 

Related work: 
- https://github.com/habitat-sh/builder/issues/99 [coming soon] 
- https://github.com/habitat-sh/builder/issues/83
- https://github.com/habitat-sh/builder/issues/345
- https://github.com/habitat-sh/builder/issues/74
