### ISSUE TITLE
Hooks should be named consistently, with dashes

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#4986]
Currently our hook names use a mixture of underscores and dashes:

* health_check
* file_updated
* post-run
* post-stop

... which is maybe technically fine, but aesthetically irksome. We should name them all consistently, and according to @reset:

> the dash is correct and the underscore is not

So we should probably make them all use dashes (and probably honor the underscores for backward compatibility, too).

Adding a documentation label to ensure the docs also get updated when we address this.

**Comment by christophermaier** [comment]
Tagged for 1.0 Stability because we should settle this before 1.0

**Comment by rsertelon** [comment]
I would like to try to fix this one. The issue seems to be lying in the retro compatibility part of that. Here are some assumptions, do they seem legit to you?

For a given hook, in a given pkg:
  * check if hook filename exists
  * if hook defines an "old filename" check if it exists too
  * If pkg has an old and no new: warn and use it
  * If pkg has an old and a new: warn and use new
  * If pkg has no old and a new: use it
  * If pkg has no old and no new: use default mechanism of hab sup

**Comment by christophermaier** [comment]
@rsertelon That backwards compatibility logic sounds good to me. Allowing both versions to exist side-by-side (for a time, at least) would allow plenty of time for all core plans to be migrated, as well as not break people running newer packages (with "correct" hook names) on older Supervisors that don't recognize them.

For bonus points, adding some smarts to the package build process to warn users that they're using an "old" hook name would be interesting. Something along the lines of:

```
You have defined a "health_check" hook, but this name has been deprecated. 

If you are running this package in a Habitat Supervisor version X.X.X or later, 
we suggest using the name "health-check" instead. 

Supervisors prior to this version will only recognize "health_check", while those 
after will recognize both versions, preferring "health-check".
```
(The wording is up for discussion, of course, but giving users as much information as possible as early in the process as possible would be really nice.)

**Comment by rsertelon** [comment]
I see, I'll try to make retro compat work. Maybe addressing the hook at build time could be done with #5112 ?

**Comment by christophermaier** [comment]
Yeah, definitely. #5112 could grow to become "make sure all hooks are valid".
