### ISSUE TITLE
Hab bldr job demote help text is incorrect

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#4989]
The  `hab bldr job demote` subcommand has incorrect help text.

It shows:
```
<CHANNEL> The target channel name
```
But should actually read:
```
<CHANNEL> Demote from the specified release channel
```

If a user puts in 'unstable' the command will actually attempt to demote from unstable to unstable.

Further, when the demotion is happening the interactive text is incorrect showing demoting TO as opposed to demoting FROM.

**Comment by raskchanky** [comment]
Related https://github.com/habitat-sh/habitat/issues/4961
