### ISSUE TITLE
libsodium incompatible with my OS

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#4990]
On my OS, libsodium is named libsodium.so, libsodium.so.23 and libsodium.so.23.1.0

So, on installation I get: 

--> hab-install: Checking installed hab version
hab: error while loading shared libraries: libsodium.so.18: cannot open shared object file: No such file or directory

**Comment by ShalokShalom** [comment]
KaOS, its a full rolling

**Comment by ShalokShalom** [comment]
From experience, I can say that these kind of numbers in such files get randomly choosen by some specific component in the tool chain

Other packagers like AppImage also struggle with it, I will look for a recent issue about that.

**Comment by elliott-davis** [comment]
I need some more info here @ShalokShalom. What are you trying to install, etc. Would you mind filling out the issue template in full?

**Comment by ShalokShalom** [comment]
Yeah sorry, I could have mentioned that its about installing Habitat itself.

I simply followed the guide and used the second option to install it on Linux. 

As said, this issue is well known, these kinds of libraries have different numbers after the dot on all the different distros.

**Comment by Atalanta** [comment]
Thanks for adding some more info, @shalokshalom, but I'm still struggling to understand the issue, or how to reproduce it.  I'd love to help, but I'm a bit stuck without more context.  Could you please provide:

```
- [ ] The OS (including version) where you are running any of the Habitat commands.
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		RUST_LOG=debug RUST_BACKTRACE=1 hab ...
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		env | grep HAB | grep -v HAB_AUTH_TOKEN

	- ***DO NOT include `HAB_AUTH_TOKEN`*** or any other sensitive information. More info on Habitat environment variables can be found [here](https://www.habitat.sh/docs/reference/environment-vars/).
	- [ ] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:
		- [ ] a. before starting the studio
		- [ ] b. inside the studio

- [ ] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.

		ls -la /hab/cache/keys
		ls -la $HOME/.hab/cache.keys
```

**Comment by ShalokShalom** [comment]
I am on KaOS, as mentioned. 

The Habitat binary wants libsodium.so.18, while its called libsodium.so.23 here.

[This here is the issue I mentioned earlier](https://github.com/AppImage/AppImageKit/issues/343)

Why ask for debugging infos when the actual software is not installed yet?
I mentioned twice, in the initial comment and once again later on request that I am trying to install Habitat itself. 

There is no hab-install command in Habitat itself even. 
In my humble opinion, this gets very easily fixed by simply accepting all kinds of libsodium.so.xx packages. 

Alternatively can you simply hardcore an if then else for libsodium.so.23 in specific. 

Thanks a lot :D

**Comment by Atalanta** [comment]
OK... here's what we need in order to help:

1) What are you trying to do?

Answer: it seems like you're trying to install Habitat.

2) What are you doing?  Please show the commands you are running, and the output in full.

3) What do you expect to happen?

4) What is actually happening?

5) How does what is happening differ from your expectation?

I'm puzzled, because Habitat is statically compiled - it doesn't "want" anything at all, so I don't understand why you think it needs libsodium.  Are you trying to build Habitat on your machine?

Because you've not yet clarified exactly what you're doing, and exactly what you're trying to achieve, it's hard for me to help you, which is why I keep asking for more information.

Sorry if it's infuriating - I want to help, but I can't help without more context and info.

**Comment by ShalokShalom** [comment]
As said, I choose the second install option for Linux: https://www.habitat.sh/docs/install-habitat/#install-habitat

I successfully installed Habitat with another method in the meanwhile, so you can consider this as solved from my side. 

I am ready to help of course, if you are interested to discover the issue further.
