### ISSUE TITLE
hab pkg search - [403 Forbidden]

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#5002]
Recently I started getting an error:
```bash
hab pkg search core/coreutils
```
output:
```bash
∅ WARNING:
∅ Github tokens are being deprecated, please migrate to a Habitat Personal Access Token instead.
∅ To generate a Habitat Personal Access token, please visit the Builder Profile page (https://bldr.habitat.sh/#/profile).
∅ For more information, please read the documentation at https://www.habitat.sh/docs/using-builder/
✗✗✗
✗✗✗ [403 Forbidden]
✗✗✗
```

**Comment by raskchanky** [comment]
Hi @guskovd 

We no longer support GitHub tokens for authentication.  There was a forum post that [announced the feature](https://forums.habitat.sh/t/announcing-habitat-personal-access-tokens/432) and then a followup post where we announced that [the deprecation period had ended](https://forums.habitat.sh/t/deprecation-of-github-personal-access-tokens-for-hab-authentication/497) and you needed to upgrade to personal access tokens.

Based on the usage you provided and the results you're seeing, I'm guessing you have `HAB_AUTH_TOKEN` exported in your environment somehow (either manually or through a shell initialization file) and it's set to a GitHub token.  Changing that to a Habitat personal access token should solve your problem.

If the problem persists after that change, feel free to re-open this issue.
