### ISSUE TITLE
Error about missing /hab/cache/keys directory when entering a studio on a clean hab install

### ISSUE THREAD

**Issue by sandratiffin** [habitat-sh/habitat#5025]
I saw the issue on Windows Server 2016 using Windows Containers on two different VMs -- one local using Virtualbox, and one on EC2 -- when first running 'hab studio enter'.

```
PS C:\Users\stiffin\habitat> hab studio enter
0.55.0: Pulling from win-studio

3889bb8d808b: Pull complete
449343c9d7e2: Pull complete
4f5a6afcccf3: Pull complete
183f01b81ada: Pull complete
ae40e62e4eb7: Pull complete
1c2087427f37: Pull complete
b9af171479e3: Pull complete
Digest: sha256:8b821d56b71e75e8279fb97b94e70db506de7fbd6d232387d1bb77de6222314e
Status: Downloaded newer image for habitat-docker-registry.bintray.io/win-studio:0.55.0
C:\Program Files\Docker\docker.EXE: Error response from daemon: invalid bind mount spec "C:\\hab/cache/keys:c:/hab/cache
/keys": invalid volume specification: 'C:\hab/cache/keys:c:/hab/cache/keys': invalid mount config for type "bind": bind
source path does not exist.
See 'C:\Program Files\Docker\docker.EXE run --help'.
```
After creating a c:\hab\cache\keys directory (c:\hab\cache existed, but not c:\hab\cache\keys), and re-running 'hab studio enter', all seems well. Should this directory not be created automatically if it does not exist?

**Comment by mwrock** [comment]
This is great info! We should definitely validate that this directory exists and create it if it does not.

**Comment by mwrock** [comment]
Ends up this is not specific to Windows. Linux container exhibits the same behavior.

**Comment by ericcalabretta** [comment]
This issue still looks to be active. I ran into it today on 0.78.0. I received the same error even after I did hab setup. I declined to generate a new key during setup so maybe that had something to do with it. I could enter the studio after I manually created the keys directory.
