### ISSUE TITLE
hab-sup memory leak

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5038]
In our test environments we are seeing `hab-sup` take up a pretty substantial amount of memory:

```
$ hab sup --version
hab-sup 0.55.0/20180321222338
$ hab --version
hab 0.55.0/20180321220925
$ ps aux | grep [h]ab-sup
root      1351  0.3  6.2 588528 250916 ?       Sl   May04  13:45 /hab/pkgs/core/hab-sup/0.55.0/20180321222338/bin/hab-sup run
```

250916 is RSS in KB.  This usage goes up over time.

We suspect that this leak is not a steady-state leak but rather is the result of the frequent interactions that our application makes with hab-sup.  My apologies but I haven't yet been able to narrow this down to a better reproduction case.  However, I can tell you that our application does the following every 30 seconds

1) Polls the /services API for information on the current services
2) Re-renders any service configuration changes that the user has request by rewriting `/hab/user/SERVICE_NAME/config/user.tom`
3) Compares the running services with an internal manifest of services, unloads any services that should no longer be installed and loads any that should be installed.  Further, if we want to changes the binds or version of a service, we unload the service and load it again with the required changes.

I probably missed something here, Chef Software employees have access to the source in question.

**Comment by christophermaier** [comment]
@stevendanna Thanks for the report. I'll try and take a look at this soon. In the meantime, if you're able to narrow it down further, please share your findings 👍

**Comment by baumanj** [comment]
@stevendanna Any chance you can confirm whether you're still seeing this behavior with supervisor v0.56+? There were a _lot_ of changes in that release.

**Comment by stevendanna** [comment]
@baumanj We just updated our long-lived environment to 0.57.0 so I should be able to confirm in a few hours

**Comment by stevendanna** [comment]
We had fewer deploys than I expected yesterday, so the growth hasn't been too bad (previously we observed that memory only grows when we deployed new versions of our packages.  However, we can see even with just a few deploys the memory usage did grow:

```
root@a2-local-inplace-upgrade-dev:~# ps fauxww | grep '[h]ab-sup'
Fri Jun 22 14:46:39 UTC 2018
root      4123  0.7  2.1 385404 175884 ?       Sl   01:23   5:52  \_ /hab/pkgs/core/hab-sup/0.57.0/20180614232222/bin/hab-sup run --listen-http 127.0.0.1:9631 --listen-gossip 127.0.0.1:9638

... 2 or 3 deploys later ...

root@a2-local-inplace-upgrade-dev:~# ps fauxww | grep '[h]ab-sup'
root      4123  0.7  2.4 432688 201576 ?       Sl   Jun22  15:09  \_ /hab/pkgs/core/hab-sup/0.57.0/20180614232222/bin/hab-sup run --listen-http 127.0.0.1:9631 --listen-gossip 127.0.0.1:9638
```

**Comment by stevendanna** [comment]
A few more releases (although much time later):

```
root@a2-local-inplace-upgrade-dev:~# date; ps fauxww | grep '[h]ab-sup'
Mon Jun 25 17:39:57 UTC 2018
root      4123  0.6  2.8 486152 230556 ?       Sl   Jun22  37:04  \_ /hab/pkgs/core/hab-sup/0.57.0/20180614232222/bin/hab-sup run --listen-http 127.0.0.1:9631 --listen-gossip 127.0.0.1:9638
```

**Comment by stevendanna** [comment]
I think we can probably close this now.  The supervisor has seen a number of improvements and we haven't hit a memory issue with it in some time.  While there may be a leak in there, there isn't a particular egregious one that I have evidence of at the moment.
