### ISSUE TITLE
hab sup term doesn't clean up pid files

### ISSUE THREAD

**Issue by jaym** [habitat-sh/habitat#5045]
hab-sup 0.55.0

We're noticing that `hab sup term` doesn't clean up the PID files. `hab svc stop` does. This causes problems when hab starts back up against as it has fairly often reattached to the wrong PID. Also, sometimes those PIDs are actually threads and not processes making life even more confusing.

**Comment by jeremymv2** [comment]
@jaym @stevendanna this was resolved by #5236

**Comment by stevendanna** [comment]
🏆 Thanks!

**Comment by baumanj** [comment]
Resolved by https://github.com/habitat-sh/habitat/pull/5236

Praise be to @jeremymv2!
