### ISSUE TITLE
Incorrect documentation about hab sub command 

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#5051]
See here
![screenshot_20180510_165856](https://user-images.githubusercontent.com/6344099/39876474-909ba2a2-5473-11e8-8447-a8462e1b3112.png)

As you can see, it recommends hab-sup, while hab sup is the actual command.

**Comment by christophermaier** [comment]
I think this is a side effect if the fact that `hab` and `hab-sup` are separate binaries. We're currently investigating the possibility of merging them into a single binary, which should remove this (admittedly confusing) issue. 

It may be possible to provide some kind of override to the underlying library we use for CLI parsing, which is ultimately where this message is coming from.

Thanks for reporting this.

**Comment by ShalokShalom** [comment]
I think merging hab and hab sup is a great idea, thanks for the kind report :)

**Comment by baumanj** [comment]
This is fixed:
```
➤ sudo hab run --help
hab-sup-run 
Run the Habitat Supervisor

USAGE:
    hab sup run [FLAGS] [OPTIONS] [--] [PKG_IDENT_OR_ARTIFACT]
…
```
