### ISSUE TITLE
15 minutes tutorials lacks info that Docker is optional on Linux

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#5053]
https://www.habitat.sh/demo/packaging-system/steps/2/

This tutorial kinda suggests, that Docker is always required, while this is not the case on Linux. This increases the setup time.

**Comment by rsertelon** [comment]
It is indeed not required in this tutorial, but in the second one (Build System). I wanted to do it, but the images etc are not something I'm confident in changing ;)

**Comment by ShalokShalom** [comment]
It is not req. at all/in general, is what I mean. You can use Habitat without Docker. This tut suggests soemething different.
