### ISSUE TITLE
Template debugging tool

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5065]
Currently, it's difficult to know if templated content will behave as you expect until it's actually rendered by a live Supervisor. Unfortunately, this can mean unnecessarily long development and debugging cycles, and increased likelihood of escaped bugs.

In keeping with the general Habitat principle of pushing failure as close to the development phase as possible, it would be great to have a tool that could evaluate template files in a number of ways.

* Are variables being used actually available in the render context?
* Is valid Handlebars syntax being used?
* Are only recognized helpers being used?
* Will the rendered file be syntactically valid? This could be tricky, as this can mean different things depending on that kind of file is being templated (shell script, TOML file, JSON file, etc.)

Additionally, it would be nice to have a way to render the file using different input data to ensure it is working generally as expected.

**Comment by qubitrenegade** [comment]
I mentioned this in #1779 but I vote to name the linter tool `roomba` so I can `hab studio roomba`

**Comment by qubitrenegade** [comment]
Not sure if this fits in here or would belong another place, but it would be really cool to be able to stub or fake the gossip data.

E.g.:  I've been working on a "consul-client" plan which would bind to a "core/consul" cluster.  The only way to get that bind info to resolve is to actually build a 3node cluster then run my client plan against it.

I would like to be able to see that this:

  {{~#eachAlive bind.consul-server.members as |member|}}
    "{{member.sys.ip}}"{{~#unless @last}},{{/unless}}
  {{~/eachAlive}}

Actually resolves in the proper format, etc.  (I'm still not clear on where to use the `~` at the beginning or end of a handlebars statement, so the only way is to change it, rebuild the plan, test it, change it rebuild the plan, test it, etc.)

**Comment by jsirex** [comment]
I want to raise attention to that topic and drop few notes on how it might be implemented.
I believe this also can resolve: #1137, #1779, #1677.
I don't know Rust so I'm kindly asking maintainers or community to help here as this topic is crucial for habitat services development.

Could you please implement `hab-plan-render` command line tool.
ARGS: takes only one:
* PATH - the path to a plan/directory, should behave same as `hab-plan-build`s' PATH arg

FLAGS:
* `--input-toml` - path to "input" toml. Defaults to `$PLAN_CONTEXT/default.toml`
* `--extra-toml` - path to additional toml files. Can be repeated multiple times. Merges in occur order
* `--output` - where to put rendered files. Defaults to `$PLAN_CONTEXT/results`

Exit code:
* `0` - success
* `non-zero` - any codes for file not found, render issues, etc. 
* `STDERR` with explanations.

Code of this tool can easily be based on `hab-sup`s' code, so implementation should be easy.

Usage example:
1. I create `tests/user.toml` - emulate customization by changing default settings somehow
```toml
port=9999 # overridden port
```
2. I create `tests/svc.toml` - emulate `bind`ings, `sys` and other stuff I'm going to test
```toml
[sys]
ip = "100.100.100.100"
[bind]
[bind.database]
port = 5432
[bind.database.superuser]
name = "not_a_admin"
password = "not_a_password"
...
```
3. Now I can do write-check iterations with the single command:
```bash
hab-plan-render --extra-toml tests/svc.toml .
cat results/hooks/run # see what I got
grep 'db.admin = "not_a_admin" results/config/db.conf || echo "db.admin was not rendered!"

# OR INSPEC TEST
inspec inspec/template_contains_required_values_spec.rb
```

**Comment by christophermaier** [comment]
I commented on this in Slack, but will leave it here, too:

> I imagine it'd end up looking something like that, yes. Unfortunately, the core team isn't going to have bandwidth to get to that for a while. If anyone in the community wants to take a stab at a prototype, that'd be cool, though.

**Comment by qubitrenegade** [comment]
@christophermaier I'd like to take a crack at it!

Any advice on where to start?  E.g.: how does "render template" function work in "the real world"?

**Comment by christophermaier** [comment]
@qubitrenegade Looks like our configuration logic is a specialization of our hook compilation logic. This work may reveal additional opportunities for refactoring, consolidation, etc.

The configuration logic lives in: https://github.com/habitat-sh/habitat/blob/6784490755c51e62313a03ebe2e6b7750b546b7c/components/common/src/templating/config.rs#L464-L536

The templating logic lives in: https://github.com/habitat-sh/habitat/blob/6784490755c51e62313a03ebe2e6b7750b546b7c/components/common/src/templating/mod.rs#L82-L92

The key bit is that both take a "context", which is anything that implements serde's `Serialize`, which should come in quite handy here. In the Supervisor, we assemble a [RenderContext](https://github.com/habitat-sh/habitat/blob/6784490755c51e62313a03ebe2e6b7750b546b7c/components/sup/src/manager/service/context.rs#L83-L89), which is basically all the data you have available to you in a template. The structure in the Supervisor is a little complex, but all the rendering logic cares about is that it's something that you can basically treat like a big JSON object (the schema of which is defined [here](https://github.com/habitat-sh/habitat/blob/master/components/sup/doc/render_context_schema.json). You could create a `HashMap` of information and pass it into the rendering logic and it should be happy with that. You could also easily take in one or more JSON/TOML files and merge them all together to generate a "context"; the fact that it just needs to be something that implements `Serialize` means you've got lots of options.

Hopefully that gives you a better idea of how it all gets put together; let me know if you've got any other questions. And thanks for the help!

**Comment by qubitrenegade** [comment]
I opened PR #6114 as I figured it would be easier to discuss changes.

So first thing I did was wire up a [`hab plan render`](https://github.com/habitat-sh/habitat/pull/6114/files#diff-ee10e75b553edc813cf07f6a5036374cR571) subcommand.  That seemed like the most appropriate place to put it...  I had also considered a `hab plan debug render` which would provide the opportunity for other commands.  I'm certainly open to changing it!

I figured it would be easier to render one file and then I can figure out how to render a whole directory.

As you might infer from my variable names I was thinking that you'd want to maybe pass the path to a default.toml and some kind of "mock_data.json" file that could mock out the `sys.members` data structures.

So I kinda cheated and just copied `src/command/plan/init.rs` to `src/command/plan/render.rs`.  Then I used the `serde_json` method to slurp a json file and render the template!  Neat!

Unfortunately, the way the `init` renders the template is directly with the Handlebars library, so templates that make use of helpers can't be rendered.

So I attempted to use the `use crate::common::templating::TemplateRender` crate...

I did this:

```
    let mut renderer = TemplateRenderer::new();
    renderer
        .register_template_string(&template, &template)
        .expect("Could not register template content");
    let rendered_template = renderer.render(&template, &json).ok().unwrap();
```

Which I'm not sure I entirely understand, but I think does what I expect...  sort of...  

For instance, testing the [consul config template](https://github.com/habitat-sh/core-plans/blob/master/consul/config/basic_config.json) with this `test.json` file:

```
{
  "cfg": {
    "server": {
      "datacenter": "fooo"
    },
    "ports": {
      "dns": 8000,
      "http": 8500,
      "https": 8501
    }
  },
  "svc": {
    "members": [
      { "sys": { "ip": "1.1.1.1" }},
      { "sys": { "ip": "2.2.2.2" }},
      { "sys": { "ip": "3.3.3.3" }}
    ]
  }
}
```

I only get:

```
{
  "datacenter": "fooo",
  "data_dir": "",
  "log_level": "",
  "bind_addr": "",
  "client_addr": "",
  "server": ,
  "retry_join": [
  ],
  "ports": {
    "dns": 8000,
    "http": 8500,
    "https": 8501,
    "serf_lan": ,
    "serf_wan": ,
    "server": 
  }
}
```

So I need some way to mock out the running service members.

Any thoughts?

Also before I get too far, any thoughts on the path I'm going down?/Feedback on code?

Thanks!

**Comment by qubitrenegade** [comment]
Ok, a bit clumsy...  but try:

```
cd ~/habitat/components/hab/
cargo run -- plan render ../../test/fixtures/render/consul_config.json \
  --default-toml ../../test/fixtures/render/default.toml \
  --user-toml ../../test/fixtures/render/user.toml \
  --mock-data ../../test/fixtures/render/override.json \
  --render-dir result/config \
  --print
```

This should render:

```
{
  "datacenter": "fooo",
  "data_dir": "/hab/svc/consul/data/consul",
  "log_level": "INFO",
  "bind_addr": "9.9.9.9",
  "client_addr": "9.9.9.9",
  "server": true,
  "retry_join": [
  ],
  "ports": {
    "dns": 6666,
    "http": 6667,
    "https": 6668,
    "serf_lan": 8888,
    "serf_wan": 8302,
    "server": 9999
  }
}
```

Still haven't figured out how to render for `eachAlive`.

**Comment by qubitrenegade** [comment]
> Still haven't figured out how to render for `eachAlive`

Helps if you use "alive" not "active" :duck: 

https://github.com/qubitrenegade/habitat-1/blob/qbr/add-plan-render-command/test/fixtures/render/consul/override.json#L17-L22

**Comment by baumanj** [comment]
Now that https://github.com/habitat-sh/habitat/pull/6114 is merged, can we close this, or is there more to do?

**Comment by qubitrenegade** [comment]
Well...

* #5183
* #6204
* #6205
* #6206
* #6279

Is my current "todo" list :grin: 

#6114 is really only a starting point or "MVP"... there's still a bunch I'd like to do (if you're willing to continue to hand-hold me?).

So...  Maybe it makes sense to have a forum post and gather requirements and generate an overall "feature request list" and generate issues/requirements from that?  I think we have a good list of requirements going so far, but that's largely based on how I use Habitat (and how I want to be able to debug habitat...).

Is there a way to "assign" those tickets to me?  Then I don't have to keep a list of them?

Thanks!

**Comment by jsirex** [comment]
Is this ticket can be closed because we have `hab plan render`?

**Comment by christophermaier** [comment]
@jsirex Yup, looks like it... thanks for the nudge.
