### ISSUE TITLE
Add on-prem Builder Depot documentation to habitat.sh/docs

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#5076]
As a standalone section, this topic seems like a good fit under the Best Practices section of the docs - https://www.habitat.sh/docs/best-practices/. 

Additionally, where there might be additional steps to existing functionality, we should weave it into the existing docs for Builder. Specifically, the 'Working with Builder' section (and all of it's subsections where it's necessary to point out any nuances) - https://www.habitat.sh/docs/using-builder/ . To avoid managing the details of setup/configuration in two places, we can simply make reference (and link to) the Best Practices section for implementation level details.

**Comment by ryankeairns** [comment]
@chefsalim We need to get some amount of on-prem depot docs added to the docs portion of our website. I see there's a bunch of good stuff in the README... should we copy some of that over? At a minimum, we should at least have an on-prem page in the docs that links to the GitHub repo/README. Thoughts?

**Comment by ryankeairns** [comment]
@cnunciato @chefsalim  I have not seen any metrics coming in from the on-prem installs, which is likely because it's not documented anywhere (i.e. nobody has enabled it)? 

I forget how, exactly, that gets enabled by the user/installer and it's not documented in the on-prem README anywhere that I could find. Perhaps that needs added to the Setup section? --> https://github.com/habitat-sh/on-prem-builder#setup

**Comment by cnunciato** [comment]
@ryankeairns  We have facilities in place to allow on-prem users to opt into analytics, yes. The config values are these, and they map directly to the values we use for querying in Heap. The values we're running in acceptance, for example, are:

```
[analytics]
company_id    = "builder-acceptance"
company_name  = "Habitat Builder Acceptance"
```

They are not yet documented as part of the setup process, correct.

**Comment by ryankeairns** [comment]
@cnunciato cool, let's add them!

**Comment by ryankeairns** [comment]
@cnunciato we good to go on this one?

**Comment by cnunciato** [comment]
Just about -- wrapping up the PR now...
