### ISSUE TITLE
Learn Chef tutorial inaccurate with respect to auth tokens

### ISSUE THREAD

**Issue by nick-oliver** [habitat-sh/habitat#5085]
I am following the lesson track as described at https://learn.chef.io/modules/try-habitat#/

I have created an origin named nick-oliver and all installation criteria are followed and all seem to be completing correctly, up to the point where I enter:
`curl -s 127.0.0.1 | grep 'The time is'`
The track says that there is supposed to be output, but when I run the curl command, I get no output.

I then attempt to do the hab pkg upload, entering the correct .hart file name in the ./results directory.
At this point I get the error: No auth token specified

I am running CentOS Linux release 7.5.1804 (Core)
```
RUST_LOG=debug RUST_BACKTRACE=1 hab
DEBUG 2018-05-16T20:14:25Z: habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG 2018-05-16T20:14:25Z: habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG 2018-05-16T20:14:25Z: habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG 2018-05-16T20:14:25Z: hab: clap cli args: ["hab"]
DEBUG 2018-05-16T20:14:25Z: hab: remaining cli args: []
DEBUG 2018-05-16T20:14:25Z: hab::analytics: Event: v=1&tid=UA-6369228-7&cid=526351ec-186a-49f6-a6cd-1636b2bd0840&t=event&aip=1&an=hab&av=0.55.0%2F20180321220925&ds=cli--hab&ec=clierror&ea=MissingArgumentOrSubcommand--hab--
DEBUG 2018-05-16T20:14:25Z: hab::analytics: Creating directory /home/nick.oliver/.hab/cache/analytics
DEBUG 2018-05-16T20:14:25Z: hab::analytics: Creating file /home/nick.oliver/.hab/cache/analytics/event-1526501665.479903065.txt
hab 0.55.0/20180321220925
```
```
Authors: The Habitat Maintainers <humans@habitat.sh>
-----------------------------------------------------
env | grep HAB | grep -v HAB_AUTH_TOKEN
HAB_ORIGIN=nick-oliver

~/.hab/cache/keys$ ls -lash
total 8.0K
   0 drwxrwxr-x. 2 nick.oliver nick.oliver  84 May 16 14:39 .
   0 drwxrwxr-x. 6 nick.oliver nick.oliver  59 May 16 15:05 ..
4.0K -r--------. 1 nick.oliver nick.oliver  82 May 16 14:39 nick-oliver-20180516193924.pub
4.0K -r--------. 1 nick.oliver nick.oliver 126 May 16 14:39 nick-oliver-20180516193924.sig.key

ls -lash ~/.hab
total 4.0K
   0 drwxrwxr-x.  4 nick.oliver nick.oliver   28 May 16 14:39 .
4.0K drwx------. 31 nick.oliver nick.oliver 4.0K May 16 15:03 ..
   0 drwxrwxr-x.  6 nick.oliver nick.oliver   59 May 16 15:05 cache
   0 drwxrwxr-x.  2 nick.oliver nick.oliver   21 May 16 14:38 etc
```
I would appreciate any assistance you can provide.

**Comment by rsertelon** [comment]
Hey @nick-oliver have you run created a personal access token on builder? The tutorial says GitHub access token but they have been deprecated and are not supported anymore :)

**Comment by nick-oliver** [comment]
I used the Github access token, found on the Builder profile page. Assuming that is in a different location, I don't know where to generate a personal access token.  Unless I have to generate it locally - I will check the tutorial again and see if that is an option.

**Comment by christophermaier** [comment]
@nick-oliver You can generate a personal access token on your profile page: https://bldr.habitat.sh/#/profile

Does your `~/.hab/config/cli.toml` have a token present? Alternatively, do you have anything exported to `HAB_AUTH_TOKEN`?

**Comment by christophermaier** [comment]
@nick-oliver Also, the forums may be a more appropriate venue for this kind of question: https://forums.habitat.sh/

**Comment by nick-oliver** [comment]
Christopher,
Thanks very much for taking a look - yes, I generated my token on my profile page - I also confirmed that it was present in the cli.toml file.  I followed all the instructions in the tutorial, with no success.

I think, that given I have no use for this tech in my current position, and don't have time to beat this topic to death trying to get it to work, purely for the sake of getting it to work, I am going to close this issue.  Thanks for the suggestions.

**Comment by jasonwbarnett** [comment]
@christophermaier Just want to double-click this thread. I just attempted running through the try-habitat course and ran into the exact same issue.

Context:

1. Installed hab (hab 0.55.0/20180321215236) via homebrew
2. Created a new origin and generated a keypair via builder
3. Started tutorial which led to creating a new origin locally and a brand new key-pair
  - Verified that both `auth_token` and `origin` were in `~/.hab/etc/cli.toml`
4. Was unable to successfully finish [step 6](https://learn.chef.io/modules/try-habitat#/step6)
  - Received the same error that @nick-oliver mentioned in this issue.

**Comment by christophermaier** [comment]
@jasonwbarnett Hrmm... Thank you for the additional details. I'll see if I can reproduce this, and if so, get that tutorial updated.

**Comment by christophermaier** [comment]
@jasonwbarnett @susanev When you are in the studio, if you export the following values and then try to upload, does it work? The current suspicion is that the `cli.toml` file isn't quite being honored in the Studio like it should be. 

```
export HAB_ORIGIN=<the name of your origin from cli.toml>
export HAB_AUTH_TOKEN=<your auth token from cli.toml>
```

**Comment by jasonwbarnett** [comment]
I also had a 403 when passing -z

Oddly this reminds me of some unusually behavior in supermarket, also related to key pairs.

**Comment by nick-oliver** [comment]
This did it.
export HAB_AUTH_TOKEN=<your auth token from cli.toml>
This instruction is not part of the tutorial, and being a beginner where habitat is concerned, I don't step off the path too far.  I ran this one and was immediately able to do the hab pkg upload - and I now have 2 packages uploaded. Thanks very much for the assist.  Now I can move on with the tutorials.

**Comment by nick-oliver** [comment]
I also found a couple of other holes in the tutorial (I think). I found that just installing docker-compose did not give me the ability to export to a docker container.  
I removed docker-compose, then installed docker in the normal fashion (used the Digital Ocean page), then re-installed docker-compose. 
When I tried to do a docker-compose up, it failed, so had to run 
sudo chmod +x /usr/local/bin/docker-compose
I found that the $HAB_ORIGIN environmental variable had been lost, so reset that. Once that was reset, I was able to run docker-compose -p habquickstart up -d, which is where I am now.

**Comment by mkorejo** [comment]
I experienced this on macOS High Sierra 10.13.1

**Comment by tashimi** [comment]
Hi @mkorejo - sorry to hear that the learn chef tutorials are not working for you. The Habitat core team maintains the tutorials at https://www.habitat.sh/learn/ - the learn chef tutorials are maintained by a different team that we will escalate these problems to, but can't immediately fix ourselves. In the meantime, if you'd like to try the ones on the habitat site, they should provide a better experience. Thank you for trying out Habitat!

**Comment by susanev** [comment]
@christophermaier I have set the two environmental variables within studio and I am still getting a 403 Forbidden ... @jasonwbarnett did it work for you?

**Comment by elliott-davis** [comment]
@josephrdsmith We need to follow up with the learn chef team on this

**Comment by Daenks** [comment]
Can confirm this issue from two different machines.

**Comment by josephrdsmith** [comment]
Thanks Daenks.  We are working to get this content updated ASAP.

**Comment by jasonwbarnett** [comment]
I just validated that uploads work after exporting both `HAB_AUTH_TOKEN` and `HAB_ORIGIN` __inside__ the studio (`hab studio enter`)

**Comment by susanev** [comment]
403. I reset my auth token and exported in the studio. Will try again tomorrow.

**Comment by Daenks** [comment]
The missing step to resolve the 403 error is this: 
One must go to https://bldr.habitat.sh/#/origins and create the origin there before running `hab pkg upload`

The missing step to having the key available is one of two possibilities.
1) One can exit the habitat studio, and then use hab pkg upload as the tutorial already states
2) One can export the environment variables `HAB_AUTH_TOKEN` and `HAB_ORIGIN` inside the habitat studio as @jasonwbarnett stated.

**Comment by susanev** [comment]
Thanks @Daenks everything is working for me now.

**Comment by kagarmoe** [comment]
I bet they're still inaccurate...

**Comment by drrk** [comment]
This was fixed in May last year:, https://github.com/chef/chef-web-learn/commit/d1f1655c742ba610a0349dbb0e63d581dfcedc18

I suspect this can be closed, I recently went through the module and it works fine :)
