### ISSUE TITLE
Local development with project hierarchy is  not possible yet?

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#5123]
Hello!

I created `my/project1` locally. I built it and installed into the system via `sudo hab pkg install`
Now I have `my/project2` which is depends on `my/project1`.
And now I don't see a way/manual/bug how to build `my/project2`.

Probably we need to document that scenario somehow. Its kinda common use-case and really blocker.

Am I missing something?

**Comment by rsertelon** [comment]
Hey @jsirex 

You'd need to build them in the same studio:

* `hab studio enter, in `my/`
* `build project1`
* `build project2`

This way the studio will contain both packages and it should work.

When you use `hab pkg build`, I _think_ that the dependencies are only taken from builder, ie: it's isolated from your host installation.

**Comment by jsirex** [comment]
Thank you for this tip, @rsertelon .

I think we need document this as official approach for such use-cases or search for another possible solutions.
