### ISSUE TITLE
hab pkg search is not documented very well

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#5128]
Right now, there's no indication of what kind of search queries `hab pkg search` accepts, or what kind of results to expect either.  It'd be good to document this so it's not confusing for users.

**Comment by SoccerGee** [comment]
@raskchanky did you discover this: https://github.com/habitat-sh/habitat/blob/32e91104a79e5b791a7029edc03ea40d51ffb172/www/source/docs/habitat-cli.html.md#hab-pkg-search

**Comment by raskchanky** [comment]
@SoccerGee Right, I did know about that.  This issue is more about fleshing out what kind of values are acceptable for `SEARCH_TERM` and given those values, what kind of results you can expect to see back.

For example, is there special search syntax that needs to be used?  Are wildcards supported or not?  Things like that.
