### ISSUE TITLE
habitat studio cgroups

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#5132]
I'm trying to build mesos from sources and see that in studio `cgroup` not mounted, so `make check` fails.

Currently, I'm not sure is it a bug, lack of feature or normal behavior?
Probably you decide to mount cgroups automatically on linux-based systems.

**Comment by elliott-davis** [comment]
This is currently not possible in the studio (for the same reason you can't start docker in the studio). I *think* what is required here is to have a studio that's FS based. It should be treated as a one-off destroyed after run (VM).

**Comment by jsirex** [comment]
Currently I work-arounded it by mounting cgroup in `do_prepare` and unmounting them in `do_end`.
There is studiorc file. Probably, we can add hooks for the studio itself via studiorc file for such cases.

I unable to find any documentation about "FS based studio" as well as about studio types (I see them in https://github.com/habitat-sh/habitat/tree/master/components/studio/libexec)

If you think there is nothing to do here - you can close the ticket
