### ISSUE TITLE
Can't restore time (libarchive err_code=14)

### ISSUE THREAD

**Issue by jonasv** [habitat-sh/habitat#5133]
Hi,

when using private builder - we ran into this issue, not much of ideas at the moment how to fix this. Any help would be appreciated.

- [ ] Red Hat Enterprise Linux Server release 5.8 (Tikanga)
- [ ] RUST_LOG=debug hab pkg install -u https://habitat.private.com core/hab-launcher
DEBUG 2018-05-30T12:11:27Z: habitat_common::ui: InputStream(stdin): { is_a_terminal(): true }
DEBUG 2018-05-30T12:11:27Z: habitat_common::ui: OutputStream(stdout): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG 2018-05-30T12:11:27Z: habitat_common::ui: OutputStream(stderr): { is_colored(): true, supports_color(): true, is_a_terminal(): true }
DEBUG 2018-05-30T12:11:27Z: hab: clap cli args: ["hab", "pkg", "install", "-u", "https://habitat.private.com", "core/hab-launcher"]
DEBUG 2018-05-30T12:11:27Z: hab: remaining cli args: []
DEBUG 2018-05-30T12:11:27Z: hab::config: No CLI config found, loading defaults
DEBUG 2018-05-30T12:11:27Z: habitat_common::command::package::install: install key_cache_path: /hab/cache/keys
DEBUG 2018-05-30T12:11:27Z: habitat_http_client::ssl: Setting CA file for SSL context to: /hab/pkgs/core/cacerts/2017.09.20/20171014212239/ssl/cert.pem
DEBUG 2018-05-30T12:11:27Z: habitat_http_client::api_client: User-Agent: hab/0.55.0/20180321220925 (x86_64-linux; 2.6.18-308.0.0.0.1.el5xen)
» Installing core/hab-launcher from channel 'stable'
DEBUG 2018-05-30T12:11:27Z: habitat_http_client::api_client: GET https://habitat.private.com/v1/depot/channels/core/stable/pkgs/hab-launcher/latest with ApiClient { endpoint: "https://habitat.private.com/v1", inner: Client { redirect_policy: FollowAll, read_timeout: Some(Duration { secs: 60, nanos: 0 }), write_timeout: Some(Duration { secs: 60, nanos: 0 }), proxy: None }, proxy: None, target_scheme: "https", user_agent_header: UserAgent("hab/0.55.0/20180321220925 (x86_64-linux; 2.6.18-308.0.0.0.1.el5xen)") }
DEBUG 2018-05-30T12:11:27Z: hyper::net: http scheme
DEBUG 2018-05-30T12:11:28Z: hyper::net: https scheme
DEBUG 2018-05-30T12:11:28Z: hyper::http::h1: request line: Get "/v1/depot/channels/core/stable/pkgs/hab-launcher/latest" Http11
DEBUG 2018-05-30T12:11:28Z: hyper::http::h1: headers=Headers { Host: habitat.private.com
, User-Agent: hab/0.55.0/20180321220925 (x86_64-linux; 2.6.18-308.0.0.0.1.el5xen)
, }
DEBUG 2018-05-30T12:11:29Z: hyper::client::response: version=Http11, status=Ok
DEBUG 2018-05-30T12:11:29Z: hyper::client::response: headers=Headers { Access-Control-Allow-Headers: authorization, range
, Access-Control-Allow-Methods: PUT, DELETE, PATCH
, Access-Control-Allow-Origin: *
, Access-Control-Expose-Headers: content-disposition
, Cache-Control: private, no-cache, no-store
Cache-Control: private, no-cache, no-store
, Content-Type: application/json; charset=utf-8
, Date: Wed, 30 May 2018 12:11:29 GMT
, ETag: 551e3ebd7986a018c0fddda13d215e632c3cd36054224546741b8796c9edfa76
, Server: nginx/1.13.10
, Vary: Accept-Encoding
, Content-Length: 4537
, Connection: keep-alive
, }
DEBUG 2018-05-30T12:11:29Z: habitat_depot_client: Body: "{\"channels\":[\"stable\",\"unstable\"],\"checksum\":\"551e3ebd7986a018c0fddda13d215e632c3cd36054224546741b8796c9edfa76\",\"config\":\"\",\"deps\":[{\"name\":\"gcc-libs\",\"origin\":\"core\",\"release\":\"20170513212920\",\"version\":\"5.2.0\"},{\"name\":\"glibc\",\"origin\":\"core\",\"release\":\"20170513201042\",\"version\":\"2.22\"},{\"name\":\"libarchive\",\"origin\":\"core\",\"release\":\"20171018164107\",\"version\":\"3.3.2\"},{\"name\":\"libsodium\",\"origin\":\"core\",\"release\":\"20170905223149\",\"version\":\"1.0.13\"},{\"name\":\"openssl\",\"origin\":\"core\",\"release\":\"20171014213633\",\"version\":\"1.0.2l\"}],\"exposes\":[],\"ident\":{\"name\":\"hab-launcher\",\"origin\":\"core\",\"release\":\"20180321162126\",\"version\":\"7241\"},\"is_a_service\":false,\"manifest\":\"# core / hab-launcher\\n\\n\\n* __Maintainer__: The Habitat Maintainers <humans@habitat.sh>\\n* __Version__: 7241\\n* __Release__: 20180321162126\\n* __Architecture__: x86_64\\n* __System__: linux\\n* __Target__: x86_64-linux\\n* __Upstream URL__: upstream project\'s website or home page is not defined\\n* __License__: Apache-2.0 \\n* __Source__: source URL not provided or required\\n* __SHA__: SHA256 checksum not provided or required\\n* __Path__: `/hab/pkgs/core/hab-launcher/7241/20180321162126`\\n* __Build Dependencies__: `core/coreutils core/rust core/gcc core/git `\\n* __Dependencies__: `core/glibc core/gcc-libs core/libarchive core/libsodium core/openssl `\\n* __Interpreters__: no interpreters or undefined\\n\\n# Plan\\n\\n## Build Flags\\n\\n```bash\\nCFLAGS: -I/hab/pkgs/core/glibc/2.22/20170513201042/include -I/hab/pkgs/core/libarchive/3.3.2/20171018164107/include -I/hab/pkgs/core/libsodium/1.0.13/20170905223149/include -I/hab/pkgs/core/openssl/1.0.2l/20171014213633/include -I/hab/pkgs/core/gcc/5.2.0/20170513202244/include\\nCPPFLAGS: -I/hab/pkgs/core/glibc/2.22/20170513201042/include -I/hab/pkgs/core/libarchive/3.3.2/20171018164107/include -I/hab/pkgs/core/libsodium/1.0.13/20170905223149/include -I/hab/pkgs/core/openssl/1.0.2l/20171014213633/include -I/hab/pkgs/core/gcc/5.2.0/20170513202244/include\\nCXXFLAGS: -I/hab/pkgs/core/glibc/2.22/20170513201042/include -I/hab/pkgs/core/libarchive/3.3.2/20171018164107/include -I/hab/pkgs/core/libsodium/1.0.13/20170905223149/include -I/hab/pkgs/core/openssl/1.0.2l/20171014213633/include -I/hab/pkgs/core/gcc/5.2.0/20170513202244/include\\nLDFLAGS: -L/hab/pkgs/core/glibc/2.22/20170513201042/lib -L/hab/pkgs/core/gcc-libs/5.2.0/20170513212920/lib -L/hab/pkgs/core/libarchive/3.3.2/20171018164107/lib -L/hab/pkgs/core/libsodium/1.0.13/20170905223149/lib -L/hab/pkgs/core/openssl/1.0.2l/20171014213633/lib -L/hab/pkgs/core/rust/1.24.1/20180312213347/lib -L/hab/pkgs/core/gcc/5.2.0/20170513202244/lib -L/hab/pkgs/core/git/2.14.2/20171016215544/lib\\nLD_RUN_PATH: /hab/pkgs/core/glibc/2.22/20170513201042/lib:/hab/pkgs/core/gcc-libs/5.2.0/20170513212920/lib:/hab/pkgs/core/libarchive/3.3.2/20171018164107/lib:/hab/pkgs/core/libsodium/1.0.13/20170905223149/lib:/hab/pkgs/core/openssl/1.0.2l/20171014213633/lib\\n```\\n\\n## Plan Source\\n\\n```bash\\nsource \\\"../../../support/ci/builder-base-plan.sh\\\"\\npkg_name=hab-launcher\\npkg_origin=core\\npkg_maintainer=\\\"The Habitat Maintainers <humans@habitat.sh>\\\"\\npkg_license=(\'Apache-2.0\')\\npkg_deps=(core/glibc core/gcc-libs core/libarchive core/libsodium core/openssl)\\npkg_build_deps=(core/coreutils core/rust core/gcc core/git)\\npkg_bin_dirs=(bin)\\nbin=\\\"hab-launch\\\"\\n\\ndo_prepare() {\\n  do_builder_prepare\\n\\n  export LIBARCHIVE_LIB_DIR=$(pkg_path_for libarchive)/lib\\n  export LIBARCHIVE_INCLUDE_DIR=$(pkg_path_for libarchive)/include\\n  export OPENSSL_LIB_DIR=$(pkg_path_for openssl)/lib\\n  export OPENSSL_INCLUDE_DIR=$(pkg_path_for openssl)/include\\n  export SODIUM_LIB_DIR=$(pkg_path_for libsodium)/lib\\n}\\n```\",\"target\":\"x86_64-linux\",\"tdeps\":[{\"name\":\"bzip2\",\"origin\":\"core\",\"release\":\"20170513212938\",\"version\":\"1.0.6\"},{\"name\":\"cacerts\",\"origin\":\"core\",\"release\":\"20171014212239\",\"version\":\"2017.09.20\"},{\"name\":\"gcc-libs\",\"origin\":\"core\",\"release\":\"20170513212920\",\"version\":\"5.2.0\"},{\"name\":\"glibc\",\"origin\":\"core\",\"release\":\"20170513201042\",\"version\":\"2.22\"},{\"name\":\"libarchive\",\"origin\":\"core\",\"release\":\"20171018164107\",\"version\":\"3.3.2\"},{\"name\":\"libsodium\",\"origin\":\"core\",\"release\":\"20170905223149\",\"version\":\"1.0.13\"},{\"name\":\"linux-headers\",\"origin\":\"core\",\"release\":\"20170513200956\",\"version\":\"4.3\"},{\"name\":\"openssl\",\"origin\":\"core\",\"release\":\"20171014213633\",\"version\":\"1.0.2l\"},{\"name\":\"xz\",\"origin\":\"core\",\"release\":\"20170513214327\",\"version\":\"5.2.2\"},{\"name\":\"zlib\",\"origin\":\"core\",\"release\":\"20170513201911\",\"version\":\"1.2.8\"}],\"visibility\":\"public\"}"
DEBUG 2018-05-30T12:11:29Z: habitat_common::command::package::install: Found core/hab-launcher/7241/20180321162126 in artifact cache, skipping remote download
☛ Verifying core/hab-launcher/7241/20180321162126
DEBUG 2018-05-30T12:11:32Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20180119235000: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:32Z: habitat_common::command::package::install: Verified core/hab-launcher/7241/20180321162126 signed by core-20180119235000
→ Using core/bzip2/1.0.6/20170513212938
→ Using core/cacerts/2017.09.20/20171014212239
→ Using core/gcc-libs/5.2.0/20170513212920
→ Using core/glibc/2.22/20170513201042
DEBUG 2018-05-30T12:11:32Z: habitat_common::command::package::install: Found core/libarchive/3.3.2/20171018164107 in artifact cache, skipping remote download
☛ Verifying core/libarchive/3.3.2/20171018164107
DEBUG 2018-05-30T12:11:32Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:32Z: habitat_common::command::package::install: Verified core/libarchive/3.3.2/20171018164107 signed by core-20160810182414
DEBUG 2018-05-30T12:11:32Z: habitat_common::command::package::install: Found core/libsodium/1.0.13/20170905223149 in artifact cache, skipping remote download
☛ Verifying core/libsodium/1.0.13/20170905223149
DEBUG 2018-05-30T12:11:33Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:33Z: habitat_common::command::package::install: Verified core/libsodium/1.0.13/20170905223149 signed by core-20160810182414
DEBUG 2018-05-30T12:11:33Z: habitat_common::command::package::install: Found core/linux-headers/4.3/20170513200956 in artifact cache, skipping remote download
☛ Verifying core/linux-headers/4.3/20170513200956
DEBUG 2018-05-30T12:11:33Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:33Z: habitat_common::command::package::install: Verified core/linux-headers/4.3/20170513200956 signed by core-20160810182414
DEBUG 2018-05-30T12:11:33Z: habitat_common::command::package::install: Found core/openssl/1.0.2l/20171014213633 in artifact cache, skipping remote download
☛ Verifying core/openssl/1.0.2l/20171014213633
DEBUG 2018-05-30T12:11:34Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:34Z: habitat_common::command::package::install: Verified core/openssl/1.0.2l/20171014213633 signed by core-20160810182414
DEBUG 2018-05-30T12:11:34Z: habitat_common::command::package::install: Found core/xz/5.2.2/20170513214327 in artifact cache, skipping remote download
☛ Verifying core/xz/5.2.2/20170513214327
DEBUG 2018-05-30T12:11:34Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:34Z: habitat_common::command::package::install: Verified core/xz/5.2.2/20170513214327 signed by core-20160810182414
DEBUG 2018-05-30T12:11:34Z: habitat_common::command::package::install: Found core/zlib/1.2.8/20170513201911 in artifact cache, skipping remote download
☛ Verifying core/zlib/1.2.8/20170513201911
DEBUG 2018-05-30T12:11:34Z: habitat_core::crypto::keys::sig_key_pair: Can't find secret key for name_with_rev core-20160810182414: No such file or directory (os error 2)
DEBUG 2018-05-30T12:11:34Z: habitat_common::command::package::install: Verified core/zlib/1.2.8/20170513201911 signed by core-20160810182414
✗✗✗
✗✗✗ Can't restore time (libarchive err_code=14)
✗✗✗

**Comment by elliott-davis** [comment]
Issue moved to [habitat-sh/on-prem-builder #54](https://github.com/habitat-sh/on-prem-builder/issues/54) via [**ZenHub**](https://www.zenhub.com/)
