### ISSUE TITLE
[56.0] How to load the service asynchronously

### ISSUE THREAD

**Issue by guskovd** [habitat-sh/habitat#5140]
Before the new version, I did this with the help of:

```bash
hab sup load <my_svc>
```

But in the new version there is no such command.

```bash
hab svc load <my_svc>
```
Does not work as it should. If the supervisor is not ready, I get:

```bash
✗✗✗
✗✗✗ No connection could be made because the target machine actively refused it. (os error 10061)
✗✗✗
```

It is very inconvenient to automate the creation of virtual machines, in which the supervisor starts as a systemd service (for example)
````

**Comment by cnunciato** [comment]
Right. The behavior as of 0.56.0 is that [the supervisor must first be started](https://www.habitat.sh/demo/process-supervisor/steps/10/) before services can be loaded:

```
hab sup run
hab svc load myorigin/myservice
```

At the very least, we should add some behavioral smarts and documentation around this, but there may also be some improvements we could make to how this works more generally. 

For now, we'll take on the docs portion of this and file additional issues as necessary.

**Comment by reset** [comment]
@guskovd you will need to wait until the Supervisor has started before sending it a command to load a service. I'd put some retry logic in your load command, wait for the Supervisor's PID file to be present, or check for the port to be listening. If you only need to start one service, you can alternatively start the Supervisor with an initial package with `hab sup run myorigin/myservice` so you don't need to wait!

I'm going to close this out but feel free to leave any additional ideas on how you'd like to see this solved if the suggestions above aren't satisfactory :smile:
