### ISSUE TITLE
Plan variables to do not interpolate when iterating over array

### ISSUE THREAD

**Issue by smford22** [habitat-sh/habitat#5144]
Building on Mac OS X 10.13.4 
hab 0.55.0/20180321215236

Issue
If I create an array in my `default.toml` like this...

`test_array=["apples", "oranges", "bananas"]`

and then I iterate over that in a hook (`init`, `run`) and try to call any of the plan variables like $pkg_svc_var_path or $pkg_svc_config_path those variables do not interpolate within the loop, but the interpolate just fine outside of the loop...

My test `init` hook
```
#!/bin/sh

exec 2>&1

{{#each cfg.test_array as |i| ~}}
echo {{i}} {{pkg.svc_config_path}} {{pkg.svc_data_path}} {{pkg.svc_var_path}}
{{/each ~}}

echo {{cfg.test_array}} {{pkg.svc_config_path}} {{pkg.svc_data_path}} {{pkg.svc_var_path}}
```

Load the package `hab svc load <myorigin>/test_package` then echo the contents of `/hab/svc/test_package/hooks/init` and it expands like this...

```
#!/bin/sh

exec 2>&1

echo apples
echo oranges
echo bananas
echo [apples, oranges, bananas, ] /hab/svc/test_package/config /hab/svc/test_package/data /hab/svc/test_package/var
```

Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [ ] The OS (including version) where you are running any of the Habitat commands.
- [ ] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:

		RUST_LOG=debug RUST_BACKTRACE=1 hab ...
		
- [ ] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

		env | grep HAB | grep -v HAB_AUTH_TOKEN

	- ***DO NOT include `HAB_AUTH_TOKEN`*** or any other sensitive information. More info on Habitat environment variables can be found [here](https://www.habitat.sh/docs/reference/environment-vars/).
	- [ ] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:
		- [ ] a. before starting the studio
		- [ ] b. inside the studio

- [ ] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.

		ls -la /hab/cache/keys
		ls -la $HOME/.hab/cache.keys

**Comment by elliott-davis** [comment]
you need to do this:

```
#!/bin/sh

exec 2>&1

{{#each cfg.test_array as |i| ~}}
echo {{i}} {{../pkg.svc_config_path}} {{../pkg.svc_data_path}} {{../pkg.svc_var_path}}
{{/each ~}}

echo {{cfg.test_array}} {{pkg.svc_config_path}} {{pkg.svc_data_path}} {{pkg.svc_var_path}}```
