### ISSUE TITLE
Feature Request: flag to `hab` CLI that would add Supervisor as an OS-level service

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#5146]
Thinking about how to further reduce friction for Habitat users, I've realized that much of the nasty work that needs to happen when bootstrapping hosts to run Habitat services is around running the Supervisor itself as a service.

From a UX perspective, a nice solution might be:
```
hab start --persistent-supervisor
```
Passing the `--persistent-supervisor` flag would tell Habitat to detect the OS we're running on and install & enable the appropriate service management for the Supervisor.

**Comment by rsertelon** [comment]
I think #2090 is similar :)

**Comment by baumanj** [comment]
I think https://github.com/habitat-sh/habitat/issues/2090 captures the same sentiment. Feel free to re-open with explanation of the difference if not, @bixu.
