### ISSUE TITLE
hab-sup 0.56.0 crashes if hab-sup client is killed before response is sent

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5151]
The title is a best guess at the cause, here is behavior I've seen while reproducing #5150

1) Block the supervisor by loading a service with a blocking init script as in #5150 
2) Attempt to load another service, this command will not return. 
3) Interrupt (CTRL+C) the command you ran in (2)
4) Unblock the supervisor by unblocking the init script from the service in (1)

The supervisor will crash with:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError("...")', libcore/result.rs:945:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: <unknown>
  31: __libc_start_main
  32: <unknown>
```

The backtrace isn't too useful.

**Comment by reset** [comment]
@stevendanna thanks for reporting this one, we'll get it fixed up!

FYI: The backtrace isn't useful because we strip symbols in our release builds
