### ISSUE TITLE
[feature] hab-sup controlled upgrade

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5162]
## Background

The auto-upgrade feature of hab-sup allows the supervisor to upgrade without killing the running services.  This is a great feature.

We have an application that makes heavy use of Habitat.  While we some day hope to move almost all coordination into the hands of habitat, right now, one part of that application orchestrates certain lifecycle events by interacting with hab-sup via the hab command line.  This application thus has command line flags and workarounds that are specific to a particular version of habitat.  As new versions of Habitat come out, we'd like to upgrade since it allows us to remove workarounds and pass more responsibilities to Habitat.  However, since we depend on particular command line switches, we cannot upgrade hab-sup at any time.  Rather, we need to upgrade only after our own software has been upgraded to a version that supports the new version of hab-sup.

## Feature

`hab-sup` should allow the user to initiate restart of the supervisor in a way that does not shutdown any of the services.  This would allow us to upgrade the hab-sup package on disk and then trigger the restart when we were ready for it.

Right now, `hab sup term` and killing the `hab-sup` process with a signal both result in all supervised processes being shutdown.

## Possible implementation

Either of these would work for us, but I imagine there are others y'all could dream up:

1. Define a signal we can send to hab-sup that will cause hab-sup to exit in the same way it exits before an auto-upgrade.

2. Define a new `hab sup BLAH` command that will cause hab-sup to exit cleanly OR which can upgrade the hab-sup to a given hab-sup version.

**Comment by baumanj** [comment]
This seems like a good thing to have and which should be very easy to implement with the capabilities that the supervisor already possesses.

**Comment by stevendanna** [comment]
@baumanj In thinking about this more.  I think some more thought about how this would interact with other behavior might work.

Namely, right now, if we want to be sure that a rouge package install can't break us, we set HAB_SUP_BINARY in our supervisor startup script.  While we remove that environment variable, that would leave us open to hab-sup being upgraded on us unexpectedly.  I think it might be good to take a look at how users are expected to manage hab-sup's lifecycle.

**Comment by baumanj** [comment]
@stevendanna: take a look at https://github.com/habitat-sh/habitat/pull/5409

Basically it should let you `hab sup run` without `--auto-update`, but it will still update the supervisor (without taking down services) if you send `SIGHUP`, so you have control over exactly when that happens.
