### ISSUE TITLE
base64Encode and base64Decode handlebars helpers

### ISSUE THREAD

**Issue by HT154** [habitat-sh/habitat#5176]
Some software, like Kubernetes, asks that some values in configuration files (or manifests, etc.) be base64 encoded. Currently, I have no way to take plain text configuration values, base64 encode them, and template them into a config file or lifecycle hook.

Adding custom helpers for dealing with base64 encoding would improve the ergonomics of working with config files for services that require it.

**Comment by HT154** [comment]
This would still be very useful! Though maybe a more general way to have hab packages provide handlebars filters would be even better

**Comment by AfzalSabbir** [comment]
I also need this.
