### ISSUE TITLE
Override plan.sh values at build time

### ISSUE THREAD

**Issue by StuporHero** [habitat-sh/habitat#5192]
I'm currently working to integrate building a habitat package into my CD pipeline, and it would save some headaches to be able to specify the version of the package with a flag of some kind. The particular tool I'm using, [rultor](http://www.rultor.com/), gives me the ability to define a release flow which includes creating a tag in git with the version number, and it would simplify things if I could set a placeholder in the plan.sh that is overridden by the version I give to rultor. For now, I'll probably be using `sed -i "s/version-placeholder/${tag}/g" ./habitat/plan.sh` in the flow before running `hab pkg build .` to accomplish the same effect. I appreciate your consideration.

**Comment by elliott-davis** [comment]
I was looking for this in the docs but I can't seem to find them. You can use `pkg_version()` as shown here: https://github.com/habitat-sh/builder/blob/master/support/ci/builder-base-plan.sh#L1-L5 and make sure you call `update_package_version` in a `do_before` hook.

Full Example: 

```
pkg_version() {
  echo $TAG
}

do_before() {
  update_package_version
}
```

**Comment by StuporHero** [comment]
Thanks for giving me a full example! I appreciate the help. I should have realized sooner that, being a shell script, I have access to the environment. derp
