### ISSUE TITLE
0.57.0-dev `hab svc status` shows state column value as integer

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat#5196]
What's currently in master, when compiled and running, has a different behavior then prior versions.

0.56.0:
```
[root@default-centos-74 ~]# /hab/pkgs/core/hab-sup/0.56.0/20180530235935/bin/hab-sup --version
hab-sup 0.56.0/20180530235935
[root@default-centos-74 ~]# hab --version
hab 0.56.0/20180530234036
[root@default-centos-74 ~]# hab svc status
package                          type        state  uptime (s)  pid   group
core/redis/3.2.4/20170514150022  standalone  up     609         3428  redis.default
[root@default-centos-74 ~]#
```

0.57.0-dev:
```
root@7acf309aaf97:/src# /src/target/debug/hab-sup --version
hab-sup 0.57.0-dev
root@7acf309aaf97:/src# /src/target/debug/hab --version
hab 0.57.0-dev
root@7acf309aaf97:/src# /src/target/debug/hab svc status
package                          type        state  uptime (s)  pid   group
core/redis/3.2.4/20170514150022  standalone  1      256         2895  redis.default
root@7acf309aaf97:/src#
```

Notice that `state` now appears as an integer value.

I see that @baumanj had similar output variance result in an unrelated [issue](https://github.com/habitat-sh/habitat/issues/5172) filed.

Was this change in output intentional?

**Comment by jeremymv2** [comment]
I believe perhaps this is a result of the switch from the `protobuf` to `prost` crate.

With `protobuf` we had `state` as `::std::option::Option<ProcessState>`:
https://github.com/habitat-sh/habitat/blob/0.56.0/components/sup-protocol/src/generated/types.rs#L644

With `prost` we have it as `i32`:
https://github.com/habitat-sh/habitat/blob/master/components/sup-protocol/src/generated/sup.types.rs#L29

**Comment by baumanj** [comment]
Thanks for the issue! I had seen that myself, but hadn't gotten around to filing it. I've moved this into our backlog.

**Comment by baumanj** [comment]
Resolved by https://github.com/habitat-sh/habitat/pull/5214
