### ISSUE TITLE
pkg_svc_run fails outside of a studio on windows

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#5198]
When writing out the `run` file, plan-build expects the presense of the `$FS_ROOT` which is not defined outside of a studio. This the script in the `run` file errors trying to pass `$null` to `join-path`. We should null check that variable in the script.

**Comment by elliott-davis** [comment]
@mwrock I thought I saw something come thought with a fix for this. Is it still an issue?

**Comment by mwrock** [comment]
yeah still an issue
