### ISSUE TITLE
Update Expeditor configuration to categorize CHANGELOG.md

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#5205]
We need to update our Expeditor configuration to preserve the categories we use in our CHANGELOG.md. This makes it easier for users to track bugs against new features, helps to call out behavior-changing items, and surface other items as needed.

We should also update this before the next release if possible.

For more details see: http://expeditor.es.chef.io/configuration/changelog/#categories

**Comment by fnichol** [comment]
For reference, here's [InSpec's CHANGELOG](https://github.com/inspec/inspec/blob/master/CHANGELOG.md) and [Expeditor config](https://github.com/inspec/inspec/blob/master/.expeditor/config.yml).

**Comment by christophermaier** [comment]
Fixed with #5280
