### ISSUE TITLE
`hab bldr job status` unwraps if no job id is passed to it.

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#5209]
If a user runs `hab bldr job status` in v0.57.0 without a job id the command unwraps and panics.

**Comment by elliott-davis** [comment]
@eeyun are you seeing a clap error on a panic? We are unable to repro. Please re-open if you're still having the issue with some additional debugging deets

**Comment by eeyun** [comment]
This was corrected in v0.57.0 - sorry I had mistyped the comment, this was an issue with v0.56.0
