### ISSUE TITLE
`hab bldr channel create||destroy` fails with `No auth token specified` no `--auth` flag available

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#5210]
When attempting to run `hab bldr channel create` or `hab bldr channel destroy` on v0.56.0 no matter the origin specified the command fails with
```
XXX
XXX No auth token specified
XXX
```

**Comment by baumanj** [comment]
Note that the `HAB_AUTH_TOKEN` environment variable works to specify auth information, but this is poor UX and inconsistent with our other commands.

@apriofrost: this may be of interest to you.

See https://forums.habitat.sh/t/how-to-revert-a-published-package-with-incorrect-version-number
