### ISSUE TITLE
0.56.0: hab pkg export does not resolve built packages in /hab/pkgs/

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#5218]
If you build `myorigin/myapp` within a studio, and then try to execute `hab pkg export [tar|docker] myorigin/myapp`, you get an error about the package not being found. The package must either be uploaded to the depot or you must provide a path to a specific .hart file.

Other commands will resolve locally-built packages under /hab/pkgs

**Comment by cnunciato** [comment]
This behavior is actually intentional and documented here: https://www.habitat.sh/docs/developing-packages/#pkg-exports

One way to make it a little easier, though, if you're looking to do some automation around it, is to use the `last_build.env` file in `./results/`:

```
[1][default:/src:0]# build
[2][default:/src:0]# source results/last_build.env
[3][default:/src:0]# hab pkg export docker results/$pkg_artifact
...
★ Docker image 'cnunciato/chris' created with tags: 0.1.0-20180619171632, 0.1.0, latest
Ω Creating build report /src/results/last_docker_export.env
```

**Comment by themightychris** [comment]
Ah I see, I guess that makes sense because what's in the /hab/pkgs tree isn't a .hart file

The trouble with using `last_build.env` is that in a project with multiple services, any service might have been built last. So my documentation for how to export multiple services to containers ends up looking like:

```bash
hab pkg export docker $(ls -1t /src/results/${HAB_ORIGIN}-myapp-*.hart | head -n 1)
hab pkg export docker $(ls -1t /src/results/${HAB_ORIGIN}-myhttp-*.hart | head -n 1)
```

I'd much rather be getting to leverage habitat's existing logic for turning `${HAB_ORIGIN/myapp` into the best available package, but if the `hab pkg export` process requires a whole `.hart` file as input rather than a package file tree I see how that might not be doable

I think I have noticed somewhere else some logic existing that when you install a `.hart` from a `results/` directory, any missing dependencies that match a neighboring `.hart` file will get resolved and installed. Maybe some similar logic could exist when you do `hab pkg export origin/package` that `.hart` files in `./results/` can be detected and used as a fallback with the same version+build sorting applied?

**Comment by mwrock** [comment]
It feels like there is a disconnect between how the exporters treat an identifier vs how all the other commands behave. All the other cli commands that deal with an ident such as `pkg exec`, `svc load`, etc. work off of the local `pkgs` store and fallback to a depot. I'd love to see the exporters use the same behavior.

**Comment by cnunciato** [comment]
I see, yeah. @fnichol thoughts on this?
