### ISSUE TITLE
Add a `--force` (or equivalent flag) for `hab bldr job cancel`

### ISSUE THREAD

**Issue by fnichol** [habitat-sh/habitat#5223]
Hi there!

As an operator of a Builder service
I would like to be able to use the `hab bldr job cancel` in a script in order to automate bulk activities
So that I can use this command in an unattended fashion, and I won't fall prey to manual copy/paste errors, tedious operations activities in production, etc.

Possibly something like this: `hab bldr job cancel --force …`

**Comment by chefsalim** [comment]
This is completed and merged.
