### ISSUE TITLE
v0.57.0 `hab svc status` no longer shows state as a string

### ISSUE THREAD

**Issue by eeyun** [habitat-sh/habitat#5224]
`hab svc status` on habitat v0.57.0 no longer shows appropriate output. Instead of showing "up" "stopped" etc, the column now shows an integer that I assume refers to the status of the services.

For example:
```
[1][default:/src:0]# hab svc status
package                          type       state   uptime(s)   pid     group
core/sccache/0.2.4/20180310001750 standalone 1 76 6312 sccache.default
```

**Comment by jeremymv2** [comment]
@eeyun I fixed via #5214 🙂
