### ISSUE TITLE
Re-implement Release Process in Buildkite

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5228]
Our existing TravisCI-based release process is a bit baroque, fragile, and hard to maintain and update. This is due both to the particulars of our release process, as well as to the limitations of TravisCI's model.

The rest of Chef engineering has been transitioning to Buildkite for internal pipelines with great success. We can create a more robust and simpler release pipeline in Buildkite, which will also bring us more in line with broader engineering department practices.

I've implemented the main Linux release process already (I'm a bad developer that started work without a card), but the remaining checklist lays out everything that remains.

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Get MacOS builder queue set up

- [x] Get Windows builder queue set up

- [x] Port MacOS `hab` build process to Buildkite

- [x] Port Windows `hab` build process to Buildkite

- [x] Port Windows `hab-plan-build-ps1` build process to Buildkite

- [x] Port Windows `hab-bintray-publish` build process to Buildkite

- [x] Port Windows Studio build process to Buildkite

- [x] Port Windows Supervisor build process to Buildkite

- [x] Port Windows `hab-pkg-export-docker` build process to Buildkite

- [x] Port Windows `hab-pkg-export-tar` build process to Buildkite

- [x] Port Windows Bintray publication process to Buildkite

- [x] Port MacOS Bintray publication process to Buildkite

- [x] Implement Launcher addition to the release channel

- [x] Implement Bintray promotion to stable channel for all platforms

- [x] Implement automated Homebrew tap update for MacOS

- [x] Automate creation and upload of "bootstrap bundle" to S3

- [ ] Automate addition of new `core/backline` artifact to the Acceptance environment

- [ ] Trigger rebuild and promotion of `habitat/builder-worker` to pick up latest releases

- [ ] Automate creation of a Github Release

- [ ] Trigger rebuild of autogenerated documentation for new release (e.g. CLI docs, template context docs, etc.)

- [x] Remove release-related steps from TravisCI setup, TravisCI-specific release scripts, etc.

- [x] Update release documentation to reflect the new reality.
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

**Comment by christophermaier** [comment]
For Homebrew updates, see https://github.com/chef/homebrew-chef/blob/master/.expeditor/update_version.sh

**Comment by scotthain** [comment]
Closing this epic, having captured remaining tasks here:
https://github.com/habitat-sh/release-engineering/issues/70
https://github.com/habitat-sh/release-engineering/issues/71
https://github.com/habitat-sh/release-engineering/issues/72
https://github.com/habitat-sh/release-engineering/issues/73
