### ISSUE TITLE
Simplify and Improve Stability of the Habitat Release Process

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5232]
The Habitat release process has traditionally been a source of pain, leading to some "fun" times in the past. While significant improvements have already been made, we can take further steps to improve the stability of the process. There are additional steps we can take to further simplify the process, which will also translate into increased ease-of-use for _users_ of Habitat.

**Comment by baumanj** [comment]
I think we're on a good path towards making the release process simpler by improving our automation. I think there are a few core principles we should hold to which should help us achieve this goal:

1. Release every two weeks regardless of the state of master. Delaying for code we want to land encourages rushing the code review and testing process. We should never let master get into a state which is unreleasable. The only exception I see to this is if everyone who could do the release is needed to work on a must-address-today customer-facing issue.

2. Have a rotating schedule for who will drive the release so people can clear their schedule in advance and prioritize their work appropriately. Many hands touching this process will help surface usability and documentation issues. I'd go so far as to say this should be in PagerDuty for the sake of easy schedule maintenance.

3. Some team (I suggest the supervisor vertical) needs to own the release process and have accountability for addressing the issues that are discovered with it.

Thoughts?

**Comment by raskchanky** [comment]
1. Agreed. Once upon a time, this was the case. Getting back to this place is a good idea.
1. I like the idea of a rotating schedule. Putting it in PagerDuty is probably the least amount of friction at this point, given on-call and goalie schedules are already in there, and people are already paying attention to it.
1. I agree that some group of people should own the release process and have accountability for addressing issues. I don't particularly care which people, but this seems like a good way to ensure things are steadily improving.

**Comment by christophermaier** [comment]
Agree on all points. As a way to help address point 1, I'd like us to start using feature flags, conditional compilation, etc. as we implement bigger refactorings and changes. This should help keep master releasable, while allowing us the room to implement and test things appropriately. It would also let us avoid "code bombs", too, which is always nice.

My ideal CI pipeline would allow us to matrix out over feature flags et al. to get continuous feedback on the state of various in-flight changes, while still preserving the overall releasability of things.
