### ISSUE TITLE
Add hooks documentation to the plan-writing docs

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#5235]
Hooks are a common part of writing a plan. We should explain what they are and how to use them in the [Writing a Plan section of the docs](https://www.habitat.sh/docs/developing-packages/#write-plans).

**Comment by christophermaier** [comment]
Closing this in favor of #6784

**Comment by kagarmoe** [comment]
Writing a plan and using hooks are two separate topics. We need a good guide on writing plans.
