### ISSUE TITLE
Document how to specify a branch in .bldr.toml

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#5239]
The docs here:

https://www.habitat.sh/docs/using-builder/#automated-builds

... suggest a branch can be specified in .bldr.toml (i.e., "as seen in the previous section"), but the "previous section" doesn't say anything about how to do that.

**Comment by tashimi** [comment]
If I recall correctly, we had documented how to auto publish to a channel with builder but the functionality did not actually exist, so we removed the docs. There should be an open issue to add the functionality and re-add the docs

**Comment by raskchanky** [comment]
@tashimi is correct.  That issue is here:  https://github.com/habitat-sh/builder/issues/99

Since that functionality doesn't actually exist in the code, I'm going to close this issue.  It's probably best if there are no docs at all around specifying a channel in `.bldr.toml` until that functionality comes back.

**Comment by cnunciato** [comment]
Ok cool, thanks all. I'll get the docs changed to remove the suggestion that this functionality does exist.

**Comment by cnunciato** [comment]
I'm just going to reopen this temporarily to have something to link [this PR](https://github.com/habitat-sh/habitat/pull/5241) to.

**Comment by cnunciato** [comment]
Mistake here -- I wrote "channels" into the issue, but I meant "branches". Updated the title and description accordingly and the PR associated should make more sense now. Apologies for the momentary lapse of my language center. 😄
