### ISSUE TITLE
Remove support for multiple supervisors on a single host

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5266]
The support for multiple supervisors on a single host is currently poor and error-prone. Since it's possible to cleanly do this with VMs or containers, there's little incentive to maintain a tricky feature which is little used and hard to get right.

It's still fine to be in multiple chroot studios at the same time. This is useful for building even without the supervisor running. But only on studio should have a running supervisor. It's simple to start and stop with the `sup-run` and `sup-term` helpers.

Additional issues will be filed to address usability issues around what happens when a supervisor is expected to be running but isn't and if starting a supervisor fails because there's already one running.

See [v0.56.0 [Err: 4] secret key mismatch on sup restart studio](https://github.com/habitat-sh/habitat/issues/5169)

**Comment by baumanj** [comment]
When implementing this, it might be worth changing the standard `/hab/sup/default` path to supervisor files to just `/hab/sup`.

**Comment by irvingpop** [comment]
We have at least one production customer situation where this is needed.   It's using docker containers, but with host-based networking.

**Comment by baumanj** [comment]
Can you go into more detail, @irvingpop? Since the containers have their own process space/file system, that still sounds like one supervisor process per what we mean by "host" in this sense.

**Comment by irvingpop** [comment]
Habitat in containers has already been pretty painful to deal with when the network namespace is shared (documented in #3025), and unfortunately the remote controlled supervisor feature made it even more painful. 

In Kubernetes land, sharing process namespaces appears to be quite commonplace.  Specifically the "side car" pattern for loading multiple containers into a single pod.  I'm concerned that we could make that impossible to load two different habitat-created containers into the same pod, and it would be a very difficult to troubleshoot gotcha. 

To answer your question, I don't believe it's possible to do `--override-name` in docker-launched supervisors.

**Comment by baumanj** [comment]
If they're not using `--override-name`, then this issue shouldn't affect them. We're just trying to eliminate a feature that was never particularly well functioning or supported anyway.

The design of the supervisor isn't really amenable to running multiple instances on the same host. It's purpose is to coordinate *between* hosts. All services in a single process space/file system should be running under the same supervisor.

**Comment by irvingpop** [comment]
Okay, I understand the rationale behind this and it makes sense.    Two things I would ask for:
1.  If at all possible, can you please ensure that a second supervisor fails gracefully and logs a useful error message?
2.  Until we have a cleaner solution for multi-process supervision in docker (like Composite plans exporting to docker),  I would caution against assuming that either process or network namespace sharing isn't being used in practice or assuming it isn't a good idea for Habitat to embrace.
