### ISSUE TITLE
Have feature flags enabled by presence of an environment variable

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5275]
To enable a feature flag in `hab` right now, you must set the appropriate environment variable (say, `HAB_FEAT_OFFLINE_INSTALL` for the offline install feature) to either the string`"true"` or `"TRUE"`. This is too restrictive, in that we shouldn't really care what the value is, merely that it exists.

Alternatively, we could recognize values of `""`, `0`, `false`, `False`, `false`, etc., as signals to _not_ enable the flag, whereas any other value would be a signal to enable the flag.

(Be sure to check for instances of us using `HAB_FEAT_*` flags in e.g., release process code, and ensure that we simplify as appropriate.)

**Comment by baumanj** [comment]
My vote would be for setting the environment variable to anything but the empty string turns it on. This is consistent with [the way we use `DEBUG` in many of our shell scripts](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L337-L341).

How about separate comments for alternatives and we can 👍 the ones we like best.

**Comment by baumanj** [comment]
We could take the approach rust does with the `RUST_BACKTRACE` env var:

Setting the env var to *anything* other than `0` (zero), including the empty string is true.
