### ISSUE TITLE
Process for avoiding undesired commits to master during release

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5286]
Currently releases are done from the tip of `master`, so during the process of a release (which still takes a couple days on average), it's important that no commits (or merges) to master occur or else we can end up releasing code which hasn't been validated.

Right now we agree by convention to not make any commits to `master` during the release process, but this is error-prone and we should have a better system.

**Comment by baumanj** [comment]
Add comments with alternative solutions and we can 👍 / 👎  them

**Comment by baumanj** [comment]
We could do our releases from the release tag rather than the tip of `master`. The downside is that if we discover problems while doing the release, we may end up with a situation like this:

1. Create release `X.0` tag
2. New feature commit
3. Bugfix for release `X`

We want to release `1` and `3`, but not `2`. Since tags are just SHAs, we can't cherry-pick `3` and omit `2`. One way to resolve resolve this would be:

4. Revert `2`
5. Create release `X.1` tag
6. Re-apply `2`

With a little automation, it could be as simple as:
```
$ patch-release-tag <sha-for-3> […other shas to keep]
```

**Comment by baumanj** [comment]
An alternative to releasing off a tag or the tip of `master` would be to create release branches and release from the tip of them. This would help avoid releasing commits unintentionally without requiring a pause in development or team awareness of the state of the release process.

The main downside is that we'd have to make sure to merge back any necessary bug fixes that were committed to the release branch.

**Comment by christophermaier** [comment]
I'm interested in the release branch approach. The fact that we just re-push tags when we run into a build problem kinda defeats the purpose of tags. It also leaves open the possibility of "emergency" bugfix releases, which can be difficult with our current approach.

**Comment by christophermaier** [comment]
No longer required with our current release process.
