### ISSUE TITLE
Windows `hab studio run` runs interactively

### ISSUE THREAD

**Issue by wduncanfraser** [habitat-sh/habitat#5289]
On windows, running `hab studio run '<command>'` runs interactively, which causes problems when run via CI systems like concourse. Running `hab studio run '<command'` directly on windows behaves like it is non-interactive in that the command runs and then exits, however it seems as far as powershell/hab is concerned, it is interactive. When attempting to run the above command via Concourse, I receive the following error:

`the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'`

Running a `hab pkg build` goes through without issue. However, I am using `hab studio run` as I need to do some setup prior to the build, such as installing some locally built packages that are dependencies. I would expect `hab pkg build` and `hab studio run` to behave similarly.

**Comment by mwrock** [comment]
I'm starting to dig into this and having a hard time reproducing although I know this looks super familiar. @wduncanfraser can you tell me if you are using the `-w` parameter or calling into a containerized studio? Also can you share the command you are passing?

My suspicion is that there is something that is causing the console to prompt for input and then this happens but that is just a suspicion.

**Comment by mk-valluri** [comment]
I've faced similar issue using jenkins. @mwrock You can reproduce using the following:

- You need a CI system (Jenkins in my case)
- Create a powershell script (build-packages.ps1) which has instructions to build a package. Ex:
```
hab-plan-build.ps1 .
```
- Execute this script through habitat studio run command
```
hab studio run .\build-packages.ps1
```

This should throw an error "the input device is not a TTY. If you are using mintty, try prefixing the command with 'winpty'"
