### ISSUE TITLE
Restarting a service when any hook changes is too extreme and leads to unnecessary restarts

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5305]
Currently, whenever _any_ lifecycle hook file is updated in response to census changes, we trigger a restart of the service.

Based on how the hooks in question are actually run, this is actually far too aggressive, and could lead to services restarting more than is strictly necessary.

For example, the `post-stop`, `suitability`, `file_updated`, and `health_check` hooks are all run on-demand, and actually outside of the "main loop" of the service hook lifecycle. They cannot, by definition, impact how a service process runs. Yet, if any of them change, we restart the service.

Similarly, the `init` hook is only run when the service is first loaded, or when it has been updated with a new release from Builder. It does not run each time before the main `run` hook does. Therefore, any changes to this hook are actually completely irrelevant, because it won't be run again anyway.

The `reload` hook is a bit of an outlier (see #5306, #5307), and a change to the `reconfigure` hook seems like it should just trigger a reconfiguration, rather than a restart, since that's its sole purpose.

Changes to the `run` hook should definitely trigger a restart. Changes to `post-run` could also trigger a restart (but also see #2364).

**Comment by baumanj** [comment]
![second](https://user-images.githubusercontent.com/5906042/42576584-c0614e8a-84f0-11e8-90bd-799a1616fa2c.jpg)
"Second"
