### ISSUE TITLE
Reload / reconfigure logic is incorrect

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5306]
Currently, if the Supervisor changes any hook files, it's a signal for the service to be restarted. Similarly, any changes to configuration files are a signal for the service to be reconfigured.

However, if either is true, we end up going down the same code path. We first run a `reload` hook if it exists, or restart the service if it doesn't. _Then_, we execute a `reconfigure` hook if it exists.

Thus, if you need to simply send a `SIGHUP` to your service to read the new configuration, and you don't have a no-op `reload` hook, your service is going to restart anyway.

See https://github.com/habitat-sh/habitat/blob/01de8a13af3b823211c8d8484773e05528111b04/components/sup/src/manager/service/mod.rs#L828-L837

Instead, we should treat these scenarios distinctly.
- If we have only hook changes, we should restart the service (subject to #5305)
- If we have configuration changes AND hook changes, we should just restart the service (subject to #5305); that's going to pick up the configuration changes anyway.
- If we have configuration changes AND ONLY changes to the `reconfigure` hook, just reconfigure; see #5305)
- If we ONLY have configuration changes AND a `reconfigure` hook, then just run that hook.
- If we ONLY have configuration changes and NO `reconfigure` hook, we should restart the service

**Comment by baumanj** [comment]
![seconded](https://user-images.githubusercontent.com/5906042/42578034-b0b59542-84f3-11e8-888d-3fdc53b37497.png)

**Comment by christophermaier** [comment]
See also https://github.com/habitat-sh/habitat/issues/1838

**Comment by davidMcneil** [comment]
Resolved by #6668
