### ISSUE TITLE
Deprecate and remove the reload hook

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5307]
Based on #5306 the intended purpose of the `reload` hook is unclear.

Based on https://github.com/habitat-sh/habitat/blob/01de8a13af3b823211c8d8484773e05528111b04/components/sup/src/manager/service/mod.rs#L272-L295, it appears that `reload` is intended to be a substitute for restarting the service, but it's not clear how this can actually work in practice, given that the Launcher is the thing that owns the actual process.

If we re-organize the hook invocations as detailed in #5306, it's unclear what `reload` is really accomplishing. It is likely that it is a vestige of the time before the Launcher, and possibly before the multi-service Supervisor; we may lose nothing by removing it (subject to appropriate deprecation notices, of course).

There are several other issues for hooks and other methods of dealing with various aspects of service shutdown that may be interesting to consider here:
- https://github.com/habitat-sh/habitat/issues/4923
- https://github.com/habitat-sh/habitat/issues/5135
- https://github.com/habitat-sh/habitat/issues/2447

**Comment by baumanj** [comment]
> it appears that reload is intended to be a substitute for restarting the service, but it's not clear how this can actually work in practice, given that the Launcher is the thing that owns the actual process

Can you elaborate? Launcher owns the process, but the supervisor can still kill it and direct launcher to restart it. I must be missing what you're getting at.

**Comment by christophermaier** [comment]
I mean that I'm not clear what running a script (the alternative to which is having the Launcher restart a service) would do to "reload" a service that wouldn't mess up the bookkeeping that the Launcher already does.

**Comment by baumanj** [comment]
Ah, I think I understand. If I think of it in terms of what is possible with `load`/`unload`, it would make sense that it could be used as a signal to changes of bindings and such. Would in make more sense if we had something like [`hab config edit`](https://github.com/habitat-sh/habitat/issues/5032)?

**Comment by christophermaier** [comment]
I haven't fully plumbed the depths of Git history on this yet, but it seems that at some point that `reload` was actually intended as `reconfigure`: https://github.com/habitat-sh/habitat/commit/9e1203fdea435462ce74ef3fc34714112cbfbafb, but somehow we ended up with both.

I'm not sure exactly how these wires got crossed, but if that is the case, it does suggest that `reload` could go away.

**Comment by christophermaier** [comment]
See also https://github.com/habitat-sh/habitat/issues/1838

**Comment by davidMcneil** [comment]
Resolved by #6668
