### ISSUE TITLE
Add new hooks for more complete service lifecycle control

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5318]
In order to run effectively, services may need more control over their lifecycle than Habitat currently provides. 

By using new hooks that run at additional control points, we can provide users with Habitat packages that are better tuned to the specific needs of their services.

Some concrete examples are provided in the linked issues, but further research and community engagement should be done to determine the final suite of hooks to add.

**Comment by themightychris** [comment]
I was just asking about something like this in Slack. Are you talking about defining a bunch upfront or letting users add their own arbitrary service hooks?

I'm picturing something like `hab pkg exec` but instead `hab svc exec` that takes a service identifier and runs a rendered hook of your own with proper environment
