### ISSUE TITLE
Templates don't honor binds declared by composite packages in pkg_bind_map

### ISSUE THREAD

**Issue by OkJaybird** [habitat-sh/habitat#5333]
I have a Hab service that has an optional bind, and decides on DB connection parameters based on whether or not a bind is provided using a template like:

```shell
  {{#if bind.database}}
    HOST="{{bind.database.first.sys.ip}}"
    PORT="{{bind.database.first.cfg.port}}"
    USER="{{bind.database.first.cfg.superuser_name}}"
    PASS="{{bind.database.first.cfg.superuser_password}}"
  {{else}}
    HOST="{{cfg.connect.host}}"
    PORT="{{cfg.connect.port}}"
    USER="{{cfg.connect.user}}"
    PASS="{{cfg.connect.pass}}"
  {{/if}}
```

That works as expected when running on its own:

```shell
hab svc load okjaybird/hab_poc_db # Uses the TOML cfg values

hab svc load okjaybird/hab_poc_db --bind database:postgresql.default # Uses the bound service values
```

But when I bundle the service in a composite package and declare the binds through `pkg_bind_map`, the `bind.database` value used in the template doesn't evaluate to true:

```shell
# plan.sh
...

pkg_services=(
  core/postgresql
  okjaybird/hab_poc_db
)

pkg_bind_map=(
  [okjaybird/hab_poc_db]="database:core/postgresql"
)
```

```shell
hab svc load okjaybird/hab_poc_master # Uses TOML cfg values, but I'd expect the bound DB values to be used
```

To achieve the desired behavior, I have to still declare my binds explicitly:

```shell
hab svc load okjaybird/hab_poc_master --bind okjaybird/hab_poc_db:database:postgresql.default
```

Thanks! Here's some additional info:

- OS: Mac OS (in the studio)
- Hab Version: 0.58.0/20180629144346

**Comment by christophermaier** [comment]
Closing as we are [removing support for composites](https://www.habitat.sh/blog/2018/10/shelving-composites/)
