### ISSUE TITLE
Launcher does not restart a crashed supervisor

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5358]
The [launcher documentation](https://github.com/habitat-sh/habitat/blob/master/components/launcher/README.md) states that one of the launcher's three responsibilities is to
> Restart the Habitat Supervisor on shutdown (Supervisor for the Supervisor)

However, it appears that this functionality is currently broken. The [run loop of the launcher calls `reload`](https://github.com/habitat-sh/habitat/blob/master/components/launcher/src/server/mod.rs#L388), in the event of an error that causes the supervisor to exit. This spawns a new supervisor process, but immediately upon starting, the supervisor calls [`Manager::is_running`](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/main.rs#L233) which checks if the process identified by the `FsCfg.proc_lock_file` (default: `/hab/sup/default/LOCK`) is alive. [`write_process_lock`](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L1814-L1818) shows that this is the process ID for the launcher, not the supervisor. Running the code confirms:

```
➤ ps -p (cat /hab/studios/home--jbauman--habitat/hab/sup/default/LOCK)
   PID TTY          TIME CMD
 50621 pts/0    00:00:00 hab-launch

➤ pgrep -afl hab-sup
50630 /hab/pkgs/core/hab-sup/0.58.0/20180629150614/bin/hab-sup run
```

If [Manager::is_running](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/main.rs#L233), the supervisor immediately exits with `OK_NO_RETRY_EXCODE`, causing the launcher to exit as well.

In general, the launcher should be responsible for ensuring only one child supervisor process is running and restarting the supervisor in the event that it exits unexpectedly. The current logic attempts to reload the supervisor once a second, unless it exits [`OK_NO_RETRY_EXCODE` (84) or `ERR_NO_RETRY_EXCODE` (86)](https://github.com/habitat-sh/habitat/blob/master/components/launcher-protocol/src/lib.rs#L33-L39). Instead, the launcher should attempt restarting the supervisor a limited, tunable number of times when it has been unsuccessful in a short period.

**Comment by fnichol** [comment]
What you're seeing looks about right to me. Or to put it another way: I wouldn't be surprised if the current behavior isn't working as we expected. I'd say to got for this work and let's see where you get!
