### ISSUE TITLE
Unsafe, platform-specific Process struct is obviated by rust stdlib now

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5361]
At the time we added [`try_wait`](https://github.com/habitat-sh/habitat/blame/master/components/launcher/src/sys/unix/service.rs#L88-L101) to the launcher, the rust standard library lacked the functionality we needed and so we had to implement it ourselves. However, it requires both unsafe code and two platform-specific implementations as the process models for Linux and Windows is fairly different.

Since rust added [`try_wait`](https://doc.rust-lang.org/std/process/struct.Child.html#method.try_wait) with release [1.18.0](https://blog.rust-lang.org/2017/06/08/Rust-1.18.html) in June 2017, we now have all the primitives we need in the `std::process::Child` struct which is provided by the standard library.

We should remove our custom [`Process`](https://github.com/habitat-sh/habitat/blob/master/components/launcher/src/sys/unix/service.rs#L35) struct in favor of using standard library implementations.

**Comment by mwrock** [comment]
I believe `kill` was another specialized implementation where we initially attempt to gracefully terminate the process before resorting to killing it. We also have some logic to determine if we need to send the signal to the process group.

**Comment by fnichol** [comment]
In general, yeah!! This comes up as we often need an implementation before APIs stabilize in the Rust standard library. Can you imagine how great it'll be when [`TryConvert`](https://doc.rust-lang.org/std/convert/trait.TryFrom.html) finally stabilizes? Yes!

Having said that, we'll want to make sure we cover our basis to make sure that we have the functionality and features as @mwrock alluded to above.

**Comment by fnichol** [comment]
Oh, I should say that in the past we've removed code in favor of newly stabilized Rust APIs and occasionally crate updates as well, so I'd be for looking at swapping out these implementations. Also, I want to keep this practice moving forward 😄

**Comment by mwrock** [comment]
Yes! Love removing code!!

**Comment by baumanj** [comment]
Good point, @mwrock. I'll definitely make sure to preserve any special logic we have. I think the kill one is the most special, but comparing the others (`wait`, `try_wait`, etc.) our code looks almost identical to the rust stdlib.
