### ISSUE TITLE
Access Denied error in persisting rumors on windows

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#5368]
I have seen this from time to time in supervisor logs:

```
Error persisting rumors to disk, Error reading or writing to DatFile, C:\hab/sup\default\data\43b0d1d39edb4f8c9784e123f21487f0.rst, Access is denied. (os error 5)
```

In my experience supervisor behaviot continues just fine with no negative outcome but I'd love to get this solved.

**Comment by mwrock** [comment]
It took a while to get a repro for this and the repro is intermittent but occurs enough that it is not too hard to see. I have a ring of 3 supervisors: s1, s2, and s3. s2 and s3 are peered to s1. s1 and s2 each run the same 2 services: `sqlserver` and `sqlserver-ha-ag` forming a sql HA cluster where `sqlserver-ha-ag` binds to `sqlserver`.

I can trigger this error on s1 by unloading and reloading `sqlserver-ha-ag` on s2. Also restarting the s3 supervisor can trigger it as well. The error occurs about 30% of the time.

Watching a process monitor as the error occurs on `hab-sup` and filtering all file activity on the `.rst` file, I see two threads that attempt to rename their own temp file to the same `.rst` file. Obviously the second one loses and gets the above error when attempting the rename before the other thread closes the file.

This is the nature of the `dat_file` struct used to edit `.rst` files. Modifications are written to a temp file and then renamed to the `.rst` file. The butterfly service which owns the `dat_file` holds it as a `Arc<RWLock>`, but its `persist_data` function takes a shared read lock when writing to the file. I am assuming that the original assumption was that the final rename would be so fast that threads would not compete for the `.rst` file. Perhaps this is more likely on a Linux file system (I am not sure), but it is clearly experiencing contention on Windows.

**Comment by christophermaier** [comment]
Interesting... It looks like we clone the butterfly server for each of the threads that it runs, one of which happens to be the one that periodically writes this dat file by calling `persist_data`. The only other time that `persist_data` is called, though, is in the `Drop` implementation of the butterfly server. I wouldn't expect any of those threads to stop and be restarted (or drop and recreate their Butterfly server) in response to unloading an individual service, let alone doing that on  a remote Supervisor.

I wonder if you have perhaps discovered some deeper issue?

**Comment by mwrock** [comment]
Oh it wasn't the unload that triggered but calling load after the unload.

**Comment by christophermaier** [comment]
@mwrock either way, it's surprising that contention like this would be triggered based on changes to the services running on another Supervisor (based on my current understanding of how things are wired up, at least). I'll make a note to investigate this a bit more, since I'm already working in the Butterfly code anyway.

**Comment by mwrock** [comment]
one thing to note is that loading the service on one supervisor impacts the config of the same service on the other supervisor. Both s1  and s2 were running `sqlserver-ha-ag.default`. Each `unload`/`load` would surface:
```
2018-08-22 23:46:56,343 - sqlserver-ha-ag.default(SR): The group 'sqlserver.default' satisfies the `database` bind
2018-08-22 23:46:56,359 - sqlserver-ha-ag.default(HK): Hooks compiled
2018-08-22 23:46:56,390 - sqlserver.default(HK): Hooks compiled
```
It is odd that loading `sqlserver-ha-ag` on s2 would trigger the above bind satisfaction on s1.
