### ISSUE TITLE
Services are discoverable before they complete their init hook

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#5374]
Some services may have an `init` hook that takes several seconds or even minutes to complete. Other services should not be able to bind to a service until the service one wants to bind to is ready (ie has finished its init hook). Currently a service can bind to another that is not ready to interact and this can cause problems in the hooks of the service reaching out to the initializing service.

**Comment by christophermaier** [comment]
Closing out as a duplicate of https://github.com/habitat-sh/habitat/issues/5327
