### ISSUE TITLE
Move launcher PID file management to launcher

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5382]
Currently the file `/hab/sup/default/LOCK` and it's management have a number of issues:
1. It's a PID file, not a lock of any sort, despite [the functions which manage it having lock-sounding names like `obtain_process_lock` and `release_process_lock`.](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L1754-L1832).
2. It doesn't contain the PID of the supervisor process as the path would indicate. It contains the PID of the launcher process.
3. It's managed by the supervisor process, which requires a [complex sequence of conditional deletion and recreation](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L240-L243) orchestrated across processes of the file even when the launcher process hasn't changed.
4. The supervisor doesn't need a PID file to identify the supervisor process which launched it, because [that information is present in its environment](https://github.com/habitat-sh/habitat/blob/master/components/launcher/src/server/mod.rs#L484-L487).

For all these reasons, it makes sense to move the management of this launcher PID file to the launcher itself. It may also be advantageous to rename it to something like `/hab/launcher.pid`, `/hab/launcher/PID` or `/hab/sup/default/launcher.pid`.

**Comment by jaym** [comment]
We currently use this file to find the pid of hab-sup so that we can send it a SIGHUP. It might be worth having a command that takes care of that or passing the launcher pid in the environment of all the things it starts.

**Comment by jaym** [comment]
@stevendanna pointed out we can not rely on that file by looking at our parent pid, so ignore the comment about the environment variable

**Comment by baumanj** [comment]
Also note that you can send the `SIGHUP` to either hab-launch or hab-sup. And even in the absence of a pid file, only one process should be running, so `pkill -HUP hab-sup` or `pkill -HUP hab-launch` should work.
