### ISSUE TITLE
cli.toml should be able to set bldr_url

### ISSUE THREAD

**Issue by wduncanfraser** [habitat-sh/habitat#5386]
Ideally, cli.toml should be able to set bldr_url and any other config that is currently only set via environment variables.

This would allow you to set everything you need in a single location for easily bootstrapping hab regardless if your team is using the public bldr or on-prem.

**Comment by bdangit** [comment]
this is a dupe to https://github.com/habitat-sh/habitat/issues/5663

**Comment by christophermaier** [comment]
Closing as a dupe.
