### ISSUE TITLE
Feature request: nomad task/job exporters

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#5422]
Hello!

Do you have any plans to export habitat packages as nomad job/task?

**Comment by jsirex** [comment]
There is also possible to do a little improvement to the habitat-exporter-tar.
Is it possible to implement `habitat-exporter-chroot`? Such exporter do exactly same as tar, but builds root already in specified folder without tar-ing it.

So from nomads' side it is possible to utilize raw-execute: hab export chroot && chroot into_exported_dir
Also nomads' developer can easily implement a driver for this.

**Comment by qubitrenegade** [comment]
We would definitely be interested in this too.

**Comment by elliott-davis** [comment]
I can't ensure that this will get prioritized. However, if a PR came in that added support for this type of exporter I can't imagine it would be rejected.

**Comment by jsirex** [comment]
I have been thinking a lot on this. Looks like its better to implement that in nomad's Task Driver.
Habitat can nicely export tar archive with all stuff bundled. Nomad in turn can consume it with `source` url as artifact or using `pkg_ident` + `builder` to reconstruct chroot environment.
Probably we need something like `hab-pkg-export-dir` in future.

As now - closing this.
