### ISSUE TITLE
Supervisor crashes in studio after use of CTRL-C.

### ISSUE THREAD

**Issue by bdausses** [habitat-sh/habitat#5432]
Running hab 0.59.0/20180712162348 on Mac OSX 10.13.6

No HAB environment variables set on host, 2 set in the studio:
`HAB_ORIGIN=bdausses`
`HAB_BINLINK_DIR=/hab/bin`

Issue is that there are seemingly random crashes of the supervisor inside the studio.  I'm getting this as I attempt to go through the learn.chef.io tracks pertaining to Habitat... Specifically https://learn.chef.io/modules/try-habitat#/habitat-build...    Although I don't believe this is being caused by the content there.  I am, admittedly, guilty of using CTRL-C when I typo something on a line and want to start over.

I've had it crash on any random command after a CTRL-C is used...
- running an `ls`
- loading a package
- running the `alias` command to see available aliases
- installing the curl package

Each time, it crashes with:
`[1]+  Done                    hab sup run "$@" > /hab/sup/default/sup.log 2>&1  (wd: /)
(wd now: /src)`
as the output.

Here is an example of making it fail:

```
[1][default:/src:0]# hab sup status
No services loaded.
[2][default:/src:0]# typo some command here and press CTRL-C foobar^C
[2][default:/src:130]# hab sup status
✗✗✗
✗✗✗ Connection refused (os error 111)
✗✗✗
[1]+  Done                    hab sup run "$@" > /hab/sup/default/sup.log 2>&1  (wd: /)
(wd now: /src)```

**Comment by christophermaier** [comment]
This is fixed in https://github.com/habitat-sh/habitat/pull/5348 and will be in the next release.

**Comment by bdausses** [comment]
Thanks @christophermaier !
