### ISSUE TITLE
Binds fail for composite package

### ISSUE THREAD

**Issue by skylerto** [habitat-sh/habitat#5448]
We're currently running into this issue on hab v0.59.0, when we load the same package using v0.55.0 everything works as expected.

We're running linux containers on windows 10, so the studio we're entering and executing from is linux on windows.

```
pkg_services=(
  aem/aem-author
  aem/AEM-6_4_1_0-6_4_1
)

pkg_bind_map=(
  [aem/AEM-6_4_1_0-6_4_1]="aem-svr:aem/aem-author"
)
```

The supervisor output is as follows:

```
hab-sup(AG): The aem/AEM-6_4_1_0-6_4_1 service was successfully loaded
hab-sup(AG): The aem/aem-author service was successfully loaded
...
hab-sup(MR): Starting aem/AEM-6_4_1_0-6_4_1
hab-sup(MR): Unable to start aem/AEM-6_4_1_0-6_4_1, hab-sup(SS)[components/sup/src/manager/service/spec.rs:358:24]: Missing required bind(s), aem-svr
```

Looking in `/hab/sup/default/specs/AEM-6_4_1_0-6_4_1.spec` the binds array is completely empty.

```
ident = "aem/AEM-6_4_1_0-6_4_1"
group = "default"
channel = "stable"
topology = "standalone"
update_strategy = "none"
binds = []
binding_mode = "strict"
desired_state = "up"
composite = "aem-author-composite"
```

**Comment by elyardwilliams** [comment]
Doesn't look like anyone has been assigned this ticket.  Whats the OLA on assignments?  Apologies..I'm the new guy not versed on procedure.
