### ISSUE TITLE
0 byte dat file

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5460]
We recently had a user report that a Habitat supervisor was failing to start. The supervisor log showed:

```
Aug 15 18:30:17 redacted.host hab[1242]: hab-sup(ER)[components/sup/src/error.rs:449:9]: Butterfly error: Error reading or writing to DatFile, /hab/sup/default/data/cab66ba4cf12423db7b6cce2a1d76c54.rst, failed to fill whole buffer
```

Further investigation showed that `/hab/sup/default/data/cab66ba4cf12423db7b6cce2a1d76c54.rst` existed but was a 0-byte file.

While we haven't been able to investigate the problem further yet, the code that handles the writes:

https://github.com/habitat-sh/habitat/blob/52b8c4eafbc35bf3efaaab4dd702bb5fa740757e/components/butterfly/src/rumor/dat_file.rs#L234-L267

appears to be missing at least two calls to fsync if we want those writes to be durable.  We likely need an fsync on the temporary file before the rename to ensure that the content of the file has been written to disk and an fsync on the enclosing directory after the rename to ensure that the rename operation is flushed to disk.

**Comment by mwrock** [comment]
Closed by #5461
