### ISSUE TITLE
Import studio environment variables explicitly rather than based on HAB_STUDIO_SECRET prefix

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5462]
Currently any environment variable whose name begins with `HAB_STUDIO_SECRET` will be imported into the studio environment with the `HAB_STUDIO_SECRET` prefix stripped. For example:
```
➤ env HAB_STUDIO_SECRET_FOO=bar hab studio enter
…
   hab-studio: Entering Studio at /hab/studios/home--jbauman--habitat (default)
   hab-studio: Exported: HAB_AUTH_TOKEN=[redacted]
   hab-studio: Exported: HAB_ORIGIN=jbauman
   hab-studio: Exported: FOO=[redacted]
   hab-studio: Exported: GITHUB_TOKEN=[redacted]
…
[1][default:/src:0]# echo $FOO
bar
```

This is valuable functionality, but it lacks [affordances](https://en.wikipedia.org/wiki/Affordance) and operates in an implicit rather than explicit manner. To improve usability, moving to an interface where environment variables to export to the studio are specified via CLI options. For example:
```
➤ hab studio enter --env FOO=bar
```

This will require some changes to utilities that invoke `hab studio` and depend upon the implicit behavior such as the worker (h/t @elliott-davis), but in the long run, it should make the system more robust. It's also possible to implement the new behavior and gradually deprecate the old style to help minimize the risk of the transition.

See also https://github.com/habitat-sh/habitat/issues/5274

**Comment by seth** [comment]
Having to specify the environment variables on the command line makes things explicit, which is nice. It might be helpful to have a mode where you only need to provide the list of env variable names to take across if those vars are set already. For transferring secrets, it would be better not to have to put var=val onto the command line. In many setups, you want to carry across the same set of env vars each time (our dev flow, e.g.). So this change as currently proposed doesn't seem like an improvement.

**Comment by baumanj** [comment]
Totally agree on the ability to export an existing env var without putting it on the command line, @seth. It could work something like:
```
➤ hab studio enter --env FOO=bar HAB_AUTH_TOKEN
```
Where the existing value of `HAB_AUTH_TOKEN` in the environment would be exported inside the studio, but FOO could either not exist or be overridden. What should happen if `HAB_AUTH_TOKEN` isn't already set in the current environment is open to discussion. This is just an issue to say that the current approach isn't very user-friendly or robust (easy to pollute the studio env unintentionally as well), not to say exactly what the solution looks like.

**Comment by baumanj** [comment]
This would obviate https://github.com/habitat-sh/habitat/issues/3355
