### ISSUE TITLE
Allow hab pkg export tar to export additional packages

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#5497]
I believe this is trivial: we can add few flags to export additional packages in tar archive.
My use-case: I'm preparing full bundle I'm going to run on the server, possible in air-gapped env.
So my deployment process will be:
1. Upload bundle.tar.gz
2. `tar xf bundle.tar.gz -C /`
3. Start habitat supervisor and load services

I think it is low priority, because it can be easily work-arounded by studio. I leave example here in case someone also faced to this issue:

```bash
#!/usr/bin/bash

set -e

export HAB_BLDR_URL=https://bldr.habitat.sh
export HAB_BLDR_CHANNEL=unstable

packages=(
    core/hab
    core/hab-sup
    habitat/builder-datastore
    habitat/builder-minio
    habitat/builder-api
    habitat/builder-api-proxy
    habitat/builder-jobsrv
    habitat/builder-originsrv
    habitat/builder-router
    habitat/builder-sessionsrv
)
export PKGS="${packages[*]}"

ROOTFS="$(mktemp -t -d hab-studio-XXXX)"
test -d $ROOTFS || (echo "Failed to create temporary directory. Continue is unsafe. Exiting."; exit 1)

build_studio() {
    hab studio -r $ROOTFS -n -t baseimage new
}

clean_studio() {
    hab studio -r $ROOTFS rm
}

archive_studio() {
    local cur_dir="$(cd "$(dirname "$0")"; pwd)"
    tar zcf "$cur_dir"/habitat-complete-$(date +%F-%H-%M-%S).tar.gz -C $ROOTFS hab
}

trap clean_studio SIGHUP SIGINT SIGTERM

build_studio
archive_studio
clean_studio
```

Hope this safe some time.

**Comment by bdangit** [comment]
This would be a really nice feature in the face when there isn’t a hab builder or any way to get packages to the box other than sneaker-net. 

A workaround we have done is add in a bunch of tools in the `$pkg_deps` of our  `plan.sh` and then we are able to create a tarball.  Talking out loud, the workaround is just create an empty plan and all it has is just a bunch of runtime deps.

**Comment by christophermaier** [comment]
Still seems useful.
