### ISSUE TITLE
Process supervisor tutorial gives command examples that don't work

### ISSUE THREAD

**Issue by micgo** [habitat-sh/habitat#5538]
On step 10, I'm asked to run the following two commands:
```
[1][default:/src:0]# hab sup run
[2][default:/src:0]# hab svc load yourorigin/sample-node-app --strategy at-once
```
Unfortunately, the terminal just hangs after `hap sup run` so you can't really ever execute the second command.

**Comment by fnichol** [comment]
Agreed, we should be able to update the tutorial to use the `sup-run` Studio shell helper which runs the Supervisor in the background.
