### ISSUE TITLE
Searching for a period `.` will cause session timeout in builder UI

### ISSUE THREAD

**Issue by predominant** [habitat-sh/habitat#5543]
Searching for `.` (period) in the builder UI causes logout.

Gif attached below for reference.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3b3J0v2N0O0k1Y3R2T0h/Screen%20Recording%202018-09-03%20at%2003.51%20PM.gif)

**Comment by srenatus** [comment]
From reproducing and looking at the network tab, it looks like the UI is constructing a request to `GET https://bldr.habitat.sh/v1/depot/pkgs/search/?range=0&distinct=true` when search for `.`.
(For `asdf`, it'll `GET /depot/pkgs/search/asdf?range=...`.)

Now, that requests gets redirected to `v1/depot/pkgs/search?range=0&distinct=true` (dropped the trailing `/`); and _this_ 301 response contains no JSON body, so [something in this code](https://github.com/habitat-sh/builder/blob/06d82dde894e85a933f12fa6fd1010d36a8e6f61/components/builder-web/app/client/depot-api.ts#L157-L199) triggers the `handleError`, which [kills your session and logs you out](https://github.com/habitat-sh/builder/blob/06d82dde894e85a933f12fa6fd1010d36a8e6f61/components/builder-web/app/client/depot-api.ts#L38-L53).

I think the same might happen if you searched for `/`? 😉

**Comment by mwrock** [comment]
No longer able to repro. I get an immediate 404
