### ISSUE TITLE
Hab 0.62.1 release is missing release notes

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5557]
The latest stable release of Habitat appears to be 0.62.1; however, I only see release notes for 0.62.0.  Are the release notes for 0.62.0 all of the changes in the 0.62.1 release or where there additional changes.  Even if there weren't additional changes, it might be nice to put out release notes for every version a user might see in the stable channel, even if those release notes just say "this was a patch version bump because of an issue during the build process for X -- no additional changes."

**Comment by elliott-davis** [comment]
We went back and fourth on this. This particular change was to get out a release for a customer and we decided not to announce it. In the future, we should have release notes for all releases.
