### ISSUE TITLE
SWIM: Membership update piggybacking limit

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5566]
Per section 4.1 of the [SWIM paper](http://www.cs.cornell.edu/projects/Quicksilver/public_pdfs/SWIM.pdf), membership update messages should be piggybacked on `ping` and `ping-req` messages at most λ.log _n_ times.

This limit should be tracked globally, but the current implementation may be tracking it on a per-member basis, leading to over-piggybacking by a factor of _n_. This needs to be validated, and if so, corrected.

**Comment by dmccown** [comment]
This may have performance implications for ram consumption as we plan for 1.0.
