### ISSUE TITLE
SWIM: Track ping round-trip times

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#5567]
Since the relationship between protocol period _Tʹ_ and connection latencies is vital to achieving the properties described in the [SWIM paper](http://www.cs.cornell.edu/projects/Quicksilver/public_pdfs/SWIM.pdf), it would be useful to track the latency in terms of `ping`/`ack` round-trip times (RTT). Some basic instrumentation at a tunable log level coupled with stats that can be dumped upon receiving a signal would be useful.

Since the protocol breaks down unless _Tʹ_ is at least 3x RTT, there should be warnings and errors issued when observed values approach or exceed this threshold.

**Comment by christophermaier** [comment]
We're going to be instrumenting the Supervisor for Prometheus (#5871); this would be a natural fit.
