### ISSUE TITLE
Revisit our travis caching strategy

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#5575]
[This article](https://levans.fr/rust_travis_cache.html) implies that there are dramatic speed increases to be had by tuning the way Travis caches rust builds.  We should experiment with the technique mentioned in the article and see if we observe any performance difference.  If it works, it'd be good to apply this to the `builder` and `core` repos as well.

**Comment by christophermaier** [comment]
We're in Buildkite now, so I'm going to close this.
