### ISSUE TITLE
Documentation links with anchor tags are partially hidden behind the banner

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#5608]
When linking to a subsection of the docs,  it places the content linked to at the top of the page.  This unfortunately hides it behind the banner section of the page.

Ex: 
https://www.habitat.sh/docs/using-builder/#enter-an-origin-name

![habitat docs - working with builder 2018-09-11 09-49-01](https://user-images.githubusercontent.com/36851/45374765-ef138580-b5a7-11e8-8700-0a17924e2ca8.png)

Expected results:
![habitat docs - working with builder 2018-09-11 09-49-34](https://user-images.githubusercontent.com/36851/45374787-00f52880-b5a8-11e8-8c63-fe6530b0e150.png)

This was tested with Chrome 68 and Firefox 62 on MacOS 10.13.2

**Comment by apriofrost** [comment]
Solved by PR https://github.com/habitat-sh/habitat/pull/7212
