### ISSUE TITLE
Need better UX around rooting hab on Windows somewhere other than c:\

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#5612]
Many prefer the hab file root to live somewhere other than `c:\hab` on Windows. This is possible using a combination of cryptic environment variables and clever mounting or symlinking techniques. However it is very unintuitive and the technique differs for different habitat scenarios: cli, supervisor and studio.

Ideally we should add either a `hab setup` step or a publicly documented environment variable (unlike `FS_ROOT`) on Windows where one can specify the preferred location that would apply across the board.

**Comment by trevorghess** [comment]
👍

**Comment by mwrock** [comment]
Unless/until we find a compelling reason otherwise, I am inclined to keep our `/hab` location as is in the system drive's top level `hab` folder. While this location will be rightfully unacceptable for some customers, it is very simple to create a `junction` at `c:\hab` that points to a `hab` folder on a different drive.

Ideally this should be done before habitat is installed:
1. Create an empty `hab` folder on the drive where you want to keep all hab data
2. Create a junction on the system drive that points to the above `hab` folder

```
New-Item -ItemType Directory -Path D:\hab
New-Item -ItemType Junction -Path (Join-Path $env:SYSTEMDrive hab) -Target D:\hab
```

Completing these two steps should result in all data that habitat writes to `c:\hab` actually being saved to the other drive.

If this is being done on a system where hab had already been  installed and packages already downloaded:
1. stop the supervisor and any studios
2. Move `c:\hab` to the drive where you want hab to reside
3. Create the junction on the system drive pointing to this new folder as shown above.

**Comment by mwrock** [comment]
closing and documenting this on [the wiki](https://forums.habitat.sh/t/relocating-c-hab-to-a-different-drive-or-folder/1294)
