### ISSUE TITLE
Bad package download from the studio

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5627]
A package built and uploaded without error cannot be downloaded and appears to be gzipped:

```
[50][default:/src:0]# hab pkg install chef/deployment-service/0.1.0/20180914090453
» Installing chef/deployment-service/0.1.0/20180914090453
↓ Downloading chef/deployment-service/0.1.0/20180914090453
    6.49 MB / 6.49 MB \ [========================================================================================================] 100.00 % 2.24 MB/s  
✗✗✗
✗✗✗ stream did not contain valid UTF-8
✗✗✗
[70][default:/src:0]# file /hab/cache/artifacts/chef-deployment-service-0.1.0-20180914090453-x86_64-linux.hart 
/hab/cache/artifacts/chef-deployment-service-0.1.0-20180914090453-x86_64-linux.hart: gzip compressed data, max speed
```

If I gunzip the package, the uncompressed content appears to be a valid hartifact (header looks correct).

Because of the current depot problems I have not been able to confirm if the actual uploaded hart is corrupt, if some gzipped HTTP traffic is being handled incorrectly, or if there is some other cause.

**Comment by stevendanna** [comment]
These packages appear to be affected:

```
chef/automate-cli/0.1.0/20180914090201
chef/automate-cs-oc-erchef/12.18.4/20180914085849
chef/automate-load-balancer/0.1.0/20180914085823
chef/automate-workflow-nginx/1.8.98/20180914090125
chef/automate-workflow-server/1.8.98/20180914090003
chef/deployment-service/0.1.0/20180914090453
```

**Comment by elliott-davis** [comment]
/v1/depot/pkgs/chef/automate-cli/0.1.0/20180914090201/download
/v1/depot/pkgs/chef/automate-cs-oc-erchef/12.18.4/20180914085849/download
/v1/depot/pkgs/chef/automate-load-balancer/0.1.0/20180914085823/download
/v1/depot/pkgs/chef/automate-workflow-nginx/1.8.98/20180914090125/download
/v1/depot/pkgs/chef/automate-workflow-server/1.8.98/20180914090003/download
/v1/depot/pkgs/chef/deployment-service/0.1.0/20180914090453/download

All purged from fastly cache
