### ISSUE TITLE
Remove explicit `pkg_deps` pins from Supervisor, etc.

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5642]
We currently have a handful of `pkg_deps` in plans in this repository pinned to specific releases before the big base plans refresh earlier this year. Now that the support for older Linux kernels is wrapping up, we'll be able to remove these pins. 

However, this should only happen after we've had at least one release with a kernel 2-compatible Supervisor. Any users that are running on older kernels will need to switch to running the kernel 2-compatible Supervisor first; otherwise, they'll be updating to a kernel 3 Supervisor, which would break them.

**Comment by stevendanna** [comment]
Based on a quick survey of the plans in the repository, I think this issue can be closed.

**Comment by christophermaier** [comment]
Yup, this has already been done.

Good find @stevendanna; thanks!
