### ISSUE TITLE
Incorrect error message on invalid token

### ISSUE THREAD

**Issue by elliott-davis** [habitat-sh/habitat#5653]
I'm seeing:

```
✗✗✗
✗✗✗ [401 Unauthorized] Your GitHub token requires both user:email and read:org permissions.
✗✗✗
```

We haven't use GitHub auth tokens for awhile so this message is probably confusing for users when they get a 401 from builder when downloading packages with an invalid token.

**Comment by chefsalim** [comment]
This has been resolved for a while, the error message now refers to Habitat tokens.
