### ISSUE TITLE
Downloading Private Key appears to be broken in Builder UI

### ISSUE THREAD

**Issue by nellshamrell** [habitat-sh/habitat#5662]
To reproduce:

Log into Builder
Navigate to one of your origins
Click on "Keys"
Click on the "Download" button next to the PRIVATE key (downloading the public key works fine)
Observe that no download takes place.

**Comment by jamesc** [comment]
I ran into this and it was my popup blocker causing it to fail.

**Comment by christophermaier** [comment]
Issue moved to [habitat-sh/builder #668](https://github.com/habitat-sh/builder/issues/668) via [**ZenHub**](https://www.zenhub.com/)
