### ISSUE TITLE
Package upload should include the public keys of dependent packages

### ISSUE THREAD

**Issue by cnunciato** [habitat-sh/habitat#5693]
Currently, `hab pkg upload` submits only the public key of the specified package, and not those of its dependencies. We should include the keys of its dependencies as well.

**Comment by eeyun** [comment]
I'm taking a look at this one @cnunciato but I'm also curious why we would need/want to do this - I'm sure there's a reason I just want to make sure I know what it is so I don't build the wrong thing here!
