### ISSUE TITLE
[supervisor]  Service update channel persists between services unload/load

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#5734]
When changing the update channel for a service via `hab svc unload/load `,  the initial channel used persists until the supervisor is restarted.  This behavior is a little difficult to explain, so the reproduction steps are listed below.

######
Build a package twice and upload both:

```
smacfarlane/redis/4.0.10/20181010173224
smacfarlane/redis/4.0.10/20181010173335
```

Promote the older of the two packages to a channel;  

```
hab pkg promote smacfarlane/redis/4.0.10/20181010173224 foo
```

Start the supervisor and load the package with an at-once update strategy watching channel foo.

```
sup-run  # Studio environment
hab svc load smacfarlane/redis --channel foo --strategy at-once
```

The `20181010173224` version of the service is loaded as expected. 

Unload the service and load it again from the unstable channel. 

```
hab svc unload smacfarlane/redis
hab svc load smacfarlane/redis --channel unstable --strategy at-once
```

The expected behavior would be that the `20181010173335` version would be installed and loaded as it is in the unstable channel and newer. 

Stop the supervisor

```
hab sup term
```

Start the supervisor. Package should immediately update. 

```
sup-run
sup-log
```

I've tested this with Habitat 0.65.0 and 0.59.0 in a Linux studio.  There are also reports of this behavior with 0.65 on Windows.

**Comment by mikemol** [comment]
Fun! So this impacts Windows and Linux.

Two questions/clarifications:

1. Does running `hab sup term` stop the services being run by the supervisor? Does it trigger lifecycle hooks?

2. What version of the supervisor first introduced this problem?

**Comment by stevendanna** [comment]
I wonder if the underlying cause is similar with this issue we've seen: https://github.com/habitat-sh/habitat/issues/4815

**Comment by raskchanky** [comment]
It's very possible that the work done as part of https://github.com/habitat-sh/habitat/pull/5828 fixed this issue, so I'm going to close it.  If you still see the problems reported here, re-open and we'll take a fresh look.

**Comment by y-me-y** [comment]
@raskchanky - do you have any proof or verification this was resolved? I am just wondering when these are accepted when how do you mark them resolved?
