### ISSUE TITLE
`HAB_FEAT_IGNORE_LOCAL` is not honored with `hab pkg build --docker`

### ISSUE THREAD

**Issue by tduffield** [habitat-sh/habitat#5739]
When running `hab pkg build --docker` on Ubuntu 16.04, the `HAB_FEAT_IGNORE_LOCAL` environment variable is injected into the studio, but it is not honored. 

Here is the output from a Linux chroot build (`hab pkg build`):
```
   hab-studio: Exported: HAB_AUTH_TOKEN=[redacted]
   hab-studio: Exported: HAB_ORIGIN=chef
   hab-studio: Exported: HAB_BLDR_CHANNEL=expeditor-chef-a2-master
   hab-studio: Exported: HAB_NONINTERACTIVE=true
   hab-studio: Exported: HAB_FEAT_IGNORE_LOCAL=[redacted]
   hab-studio: Exported: GITHUB_TOKEN=[redacted]
âˆ… Enabling feature: IgnoreLocal
```

Here is the output from a Docker build (`hab pkg build --docker`):
```
   hab-studio: Exported: HAB_AUTH_TOKEN=[redacted]
   hab-studio: Exported: HAB_ORIGIN=chef
   hab-studio: Exported: HAB_BLDR_CHANNEL=expeditor-chef-a2-master
   hab-studio: Exported: HAB_FEAT_IGNORE_LOCAL=[redacted]
   hab-studio: Exported: GITHUB_TOKEN=[redacted]
   : Loading /src/components/authz-service/habitat/plan.sh
   authz-service: Plan loaded
```

I have full logs available, but they are hidden behind the ChefVPN.

**Comment by stevendanna** [comment]
I'm guessing this is because in the chroot you inhereit the entire environment since you end up in a child process of your original shell process but with docker we only pass through HAB_STUDIO_SECRET_ prefixed vars

**Comment by tduffield** [comment]
@stevendanna I am passing it via `HAB_STUDIO_SECRET_HAB_FEAT_IGNORE_LOCAL`

**Comment by stevendanna** [comment]
@tduffield OIC!  Definitely looks like a bug thent, thanks for clarifying!

**Comment by elliott-davis** [comment]
There is a workaround for this in 0.64.0 https://github.com/habitat-sh/habitat/commit/e6db9a490922f4f909113f1536fe3923e9b25f00. However, the full fix would be to allow `HAB_FEAT_` like https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/studio/docker.rs#L100-L104

**Comment by stevendanna** [comment]
On 1.5.71, this now works assuming you are using `HAB_STUDIO_SECRET_HAB_FEATURE_INGORE_LOCAL`.  It doesn't work with just `HAB_FEAT_INGORE_LOCAL` as far as I can tell because we don't appear to have special handling for HAB_FEAT_ env variables for docker studios.  

Given that, I think we can close this in favor of https://github.com/habitat-sh/habitat/issues/5274
