### ISSUE TITLE
Package download can corrupt cache in powerloss/hard reset scenario

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#5779]
The follow code is unsafe in the face of a hard reset of the machine

https://github.com/habitat-sh/habitat/blob/master/components/builder-api-client/src/lib.rs#L1204-L1222

since filesystem operations can happen out-of-order and since there are no explicit sync's, the rename at line 1221 can be processed before the data has been flushed to the file.  If the machine is reset before the data is flushed to the file, a 0-byte file will be on disk in the cache when the machine comes back up, preventing future attempts to install the package.

To prevent this, the file needs to be fsync'd before the rename operation.

**Comment by raskchanky** [comment]
@stevendanna Does the flush that happens here https://github.com/habitat-sh/habitat/blob/master/components/butterfly/src/server/incarnation_store.rs#L85 do something similar to fsync?  I can't quite tell from the Rust docs.

**Comment by stevendanna** [comment]
@raskchanky I don't think so.  That flushes the bufwriter out to the OS.  But the flush we need is to call fsync so the OS puts our data on disk.

**Comment by raskchanky** [comment]
@stevendanna Gotcha, makes sense.

**Comment by raskchanky** [comment]
@stevendanna So something more like this?  https://doc.rust-lang.org/std/fs/struct.File.html#method.sync_all

**Comment by stevendanna** [comment]
@raskchanky I've updated my comment with all of the locations I could find that have this problem.

> So something more like this? https://doc.rust-lang.org/std/fs/struct.File.html#method.sync_all

Yes, you can see the changes I made previously that fixed a similar problem: 

- https://github.com/habitat-sh/habitat/pull/5461
- https://github.com/habitat-sh/habitat/commit/b688d8ae25d9f38b4053fd29372e2733c9254327

Those changes also include an fsync on the enclosing directory, which presents a bit of a tradeoff because it ensures the rename has been processed but isn't allowed on every filesystem, so I'm not sure we'd always want to do that.

I should have searched for other uses of this pattern when fixing those.

I'd recommend we get a `atomic_write` library function going given how common this pattern is.

**Comment by raskchanky** [comment]
@stevendanna Awesome!  Thanks for the thorough write-up.

**Comment by stevendanna** [comment]
No problem.  If I get some time I can try to look at doing a PR for this.

Some additional links that I always find helpful:
- https://danluu.com/file-consistency/
- https://github.com/postgres/postgres/blob/master/src/common/file_utils.c#L342-L403
