### ISSUE TITLE
Builder is not offering private keys for download, correctly.

### ISSUE THREAD

**Issue by predominant** [habitat-sh/habitat#5797]
Creating a new origin, and then logging into builder (web) to download the private key yields a download with an incorrect filename:

It downloaded a file called `attachment; filename=_originname-20181030065810.sig.key_` (edited)

```
$  ls -la ~/Downloads           
-rw-r--r--@  1 graham.weldon  REDACTED         124 Oct 30 15:58 attachment; filename=_originname-20181030065810.sig.key_
```

**Comment by raskchanky** [comment]
Issue moved to [habitat-sh/builder #756](https://github.com/habitat-sh/builder/issues/756) via [**ZenHub**](https://www.zenhub.com/)
