### ISSUE TITLE
It is not possible to specify channel or url when exporting a packge

### ISSUE THREAD

**Issue by russellseymour** [habitat-sh/habitat#5802]
OS - Ubuntu 18.04
Habitat Version - hab 0.67.0/20181029215023

When running the `hab pkg docker export` command it is not possible to set any of the options.

For example the `hab pkg export` accepts `-u` and `-c`. However if I specify these in the order as described in the help, e.g. `hab pkg export -c dev -u https://bldr.habitat.sh docker russellseymour/mypkg`, I get the following error:

```
✗✗✗
✗✗✗ Unsupported export format: docker
✗✗✗
```

If I change the order of the options so that they are _after_ the package name, e.g. `hab pkg export  docker russellseymour/mypkg -c dev -u https://bldr.habitat.sh`, then the image is exported. However when I look at the services from the services URL I see that the channel is set to 'stable'.

![image](https://user-images.githubusercontent.com/791658/47846461-d5303b00-ddbf-11e8-87d2-a330452329bd.png)

Logging output from the command is:

```
DEBUG 2018-11-01T10:24:36Z: habitat_common::ui: UI { shell: Shell { input: InputStream { isatty: true }, out: OutputStream { coloring: Auto, isatty: true, is_colored(): true, supports_color(): true }, err: OutputStream { coloring: Auto, isatty: true, is_colored(): true, supports_color(): true } } }
DEBUG 2018-11-01T10:24:36Z: hab: clap cli args: ["hab", "pkg", "export", "-c", "dev", "docker", "results/russellseymour-blog-0.0.1-20181101093819-x86_64-linux.hart"]
DEBUG 2018-11-01T10:24:36Z: hab: remaining cli args: []
DEBUG 2018-11-01T10:24:36Z: hab::config: No CLI config found, loading defaults
✗✗✗
✗✗✗ Unsupported export format: docker
✗✗✗
```

I may have misunderstood what the `channel` option on the export command is for, but it prevents the command from running correctly anyway.

**Comment by fnichol** [comment]
Hi there! The current implementation of this subcommand requires you to specify the exporter name/component directly after `hab pkg export`, i.e. `hab pkg export docker`, `hab pkg export tar`, etc. Can you try to re-arrange your arguments to the following and see if that helps?

```sh
hab pkg export docker  -c dev -u https://bldr.habitat.sh russellseymour/mypkg
```

You can also think about it this way: the `-c` and `-u` options are on the `hab pkg export docker` subcommand, not common options on `hab pkg export`.

**Comment by chefsalim** [comment]
Note that hab pkg export help is indicating that the params go right after the export, so that may need fixing also:
```
hab-pkg-export
Exports the package to the specified format

USAGE:
    hab pkg export [OPTIONS] <FORMAT> <PKG_IDENT>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -u, --url <BLDR_URL>       Specify an alternate Builder endpoint. If not specified, the value will be taken from the
                               HAB_BLDR_URL environment variable if defined. (default: https://bldr.habitat.sh)
    -c, --channel <CHANNEL>    Retrieve the container's package from the specified release channel (default: stable)

ARGS:
    <FORMAT>       The export format (ex: aci, cf, docker, kubernetes, mesos, or tar)
    <PKG_IDENT>    A package identifier (ex: core/redis, core/busybox-static/1.42.2) or filepath to a Habitat
                   Artifact (ex: /home/acme-redis-3.0.7-21120102031201-x86_64-linux.hart)
```

**Comment by russellseymour** [comment]
@fnichol  Thanks for the pointers. However I changed the options around so that they are part of the docker export as suggested, e.g.

`hab pkg export docker --url https://bldr.habitat.sh/ --channel dev russellseymour/mypkg`

and I the image is still looking a the `stable` channel as before.

![image](https://user-images.githubusercontent.com/791658/48261255-5ddd5580-e416-11e8-884b-a4b65defc50a.png)

**Comment by russellseymour** [comment]
After asking for some help to do a workaround on the Habitat Forum (https://forums.habitat.sh/t/is-it-possible-to-change-the-channel-that-a-running-supervisor-monitors/929) I have been advised that the way I am doing this is incorrect.

The channel option is not for setting the channel that your image is for.

So to do what I need to do I need to set `HAB_BLDR_CHANNEL`.

I was not 100% about using the `--channel` flag in this way. As I now know how to do this properly I am closing the issue.

**Comment by 7qi** [comment]
i want to ask a question. the hab pkg export's format can be docker hub?
