### ISSUE TITLE
Migrate all uses of `tempdir` crate to `tempfile`

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5806]
In various places, particularly in tests, we make use of the [tempdir](https://crates.io/crates/tempdir) crate. There is also some usage of the [tempfile](https://crates.io/crates/tempfile) crate, as well.

The `tempdir` crate has been deprecated, and all future work will be done in the `tempfile` crate.

We should remove all uses of the `tempdir` crate in our code, and migrate over to using `tempfile` everywhere.

Additionally, any places where we are manually constructing temporary file names should be changed to use `tempfile` to ensure consistency and reduce extraneous code. Most of this is probably taken care of naturally by #5803, but any remaining cases should be cleaned up now.

Checklist:
- [ ] this issue
- [x] https://github.com/habitat-sh/core/issues/82
- [x] https://github.com/habitat-sh/builder/issues/769

**Comment by rsertelon** [comment]
@christophermaier I've seen the tweet of @fnichol and I'd be interested in trying to do this :) would that be okay? ^^

**Comment by christophermaier** [comment]
@rsertelon Yeah, sure! Feel free to assign yourself.

Thanks!

**Comment by rsertelon** [comment]
Hehe, still can't ;)

**Comment by christophermaier** [comment]
@rsertelon Hrm, looks like you can only assign members of the organization.

Well, for anyone that comes to this in the future, @rsertelon is working on it 😄
