### ISSUE TITLE
Managing "run-less" services

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#5815]
Organizations want to use Habitat to install and update applications on a system. These applications might not be “typical” habitat services that include a single process a run hook invokes and runs indefinitely. Often these may be COTS applications or utilities that need to be present and are used by other applications. Once installed, Habitat has served its purpose. One may think these could simply be treated as “binary” packages and pulled in as dependencies or other habitat services. However, for one or more of the following reasons, these applications must run as a service package:

* The application must be updatable and leverage an Update Strategy
* Enterprise monitoring tools need to probe the status of these tools which the health_check hook perfectly accomplishes
* The application includes installation and configuration scripts that need to be run at install time. They need init hook capabilities and possibly need to support configuration templates

In order to satisfy the above requirements, an organization may package these applications as a service package. This introduces the following problems:
* Supervisors may run many such services. Only one or two is an actual service. This consumes supervisor and census ring overhead.
* Each service consumes a shell interpreter per hook. This is particularly problematic on Windows where Powershell startup time is over a second and health_checks may spawn a Powershell instance per service resulting in CPU spikes every 5 minutes.

This issue proposes the creation of a specialized Habitat Service that can manage these kinds of packages. At least in the initial iteration, the service will target Windows and will be written in Powershell. This particular scenario tends to be present in windows environments and if the service runs in Powershell, hooks can be executed "in-process" and eliminate the need for expensive spawning of new powershell processes.

The service will support the following `toml` inputs:

```
update_interval_seconds = 30

[app1]
ident = “origin/pkg1”
channel = “my_channel”

[app2]
ident = “origin/pkg2”
channel = “my_channel”
```

User's of this service will provide their own `user.toml` which will include a list of the packages they want the service to manage.

For each listed package, the service will insure that the package is installed. If the service includes an `init` hook, that hook will be executed. Based on the interval specified in `update_interval_seconds`, the service will check the builder service for available updates. If one is available, the service will install it and call its `init` hook if present. The service will include a `health_check` hook that will run the `health_check` hooks for each package that it manages that include one. If any of these checks fail, the service will mark itself as unhealthy. The service will include a json object in its health's stdout that reflects the health of each managed package.

**Comment by mwrock** [comment]
related to #5813 and #5808

**Comment by themightychris** [comment]
I see a need for this often outside Windows too. I regularly encounter cases where the config workflow and hooks are enough to provide a service, and I want the supervisor to be doing everything it's already doing, but I don't actually need an ongoing process to be running and just feed it a noop loop to run

**Comment by mwrock** [comment]
also related to #5866 which partially addresses this scenario. It will allow "non-services" to leverage templates and an `install` hook but does not address updates or health. However it does "remember" if installation was successful or not which can be leveraged in a service like the one mentioned above.

**Comment by mwrock** [comment]
We have been getting feedback and seeing other customers adopting patterns where habitat is deploying tools and not services. Addressing this scenario could provide some great value.

**Comment by themightychris** [comment]
It seems like all that is really missing at this point is a way to trigger `config_install` to re-render (unless there's a case for "tools" getting config updates from the supervisor ring vs just from env and user.toml as config_install already does during initial rendering)
