### ISSUE TITLE
Services orphaned and reattach unsuccessfully if launcher and supervisor are forced to terminate on windows

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#5903]
This is related but separate from #5645 

If Both the launcher and the supervisor are forcefully terminated, service processes continue to run and their `PID` files survive. That is expected. When the launcher/supervisor is restarted, the supervisor reports that the services are being "reattached" but alas, all is not well.

All stdout is lost and the services fail to stop or unload vis `hab svc stop` or `hab svc unload`. These commands result in `Service stop failed: hab-sup(ER)[components\sup\src\error.rs:519:9]: NoPID:`

Then restarting/loading the service simply claims to reattach again.

Ideally reattaching should truly reattach and recapture output with the ability do stop the services normally. Currently the only way out of this situation is to remove the `PID` file of the service and also terminate all processes associated with that services which can be tough to track down and may require a reboot to truly cleanup. 

I'm assuming this broken behavior is specific to windows but have not validated that.

**Comment by mwrock** [comment]
Additionaly this scenario can be caused when habitat is running as a windows service and stopping it is unable to gracefuly stop the launcher. When that happens the `service_stop` routine forcefully kills the launcher.

**Comment by ericcalabretta** [comment]
@mwrock This condition is fairly easy to hit when other process may be rebooting or shutting down the Habitat supervisor. I've run into errors similar to this:

```
Unable to start Habitat Supervisor because another instance is already running with the pid 4692.
[2019-08-21T15:26:55Z ERROR hab_launch] Launcher exiting with code 86
```

When the supervisor is ungracefully shut down via the chef roboot action, restarting windows in the task manager, power issues, ctrl+c, etc. 

The resolution is normally to delete `C:\HAB\SUP\Default\LOCK`. I haven't seen the Launch PID file cause the issue personally. 

Adding this logic into the launcher would make hab-sup more reliable in messy environments.

**Comment by mwrock** [comment]
This issue has basically gone away since we no longer generate PID files for services. I created a new issue #7501 to track the error mentioned by @ericcalabretta above.
