### ISSUE TITLE
Can't hab pkg export with a private origin dependency

### ISSUE THREAD

**Issue by TheDarkula** [habitat-sh/habitat#5952]
I'm having an issue with gitlab's CI and habitat.

I have a plan which its `pkg_deps` includes a hart file from a private origin of mine.

If I enter a studio, build the plan which needs the dependency, everything is great.
I can export it with `hab pkg export docker`.

I implemented this in my gitlab CI script and broke up the build step and export into two separate stages.

The build step succeeds and sends the resultant `.hart` file to the export stage.

When that stage tries to do `hab pkg export docker` (not having the private origin dependency installed), it fails with:

```
✗✗✗
✗✗✗ We tried 5 times but could not download origin_name/pkg_name/pkg_version/hash. Giving up.
✗✗✗
```

If I add `hab pkg install origin_name/pkg_name` (which is the private origin dependency) before the export command, the export succeeds.

I have `HAB_ORIGIN` and `HAB_AUTH_TOKEN` exported.

The docker images I'm using are Alpine Linux.

**Comment by chefsalim** [comment]
This is resolved for Docker (https://github.com/habitat-sh/habitat/pull/5203/files) but that fix also needs to be propagated to all other exporters
