### ISSUE TITLE
Fix existing lifecycle hook logic

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#5960]
## Description
This is a collection of tasks related to misbehaving hooks, hooks that are no longer needed, and addressing some technical debt associated with hooks.

## Acceptance Criteria
* We should only restart a service when:
  1. Changes to `run`, `post-run`, and `reload` hooks (#5305)
  2. Configuration changes with no `reconfigure` hook (#5306)

* We should never restart a service when:
  1. Changes to `post-stop`, `suitability`, `file_updated`, `health_check`, and `init` hooks (#5305) 
  2. Changes to configuration and a `reconfigure` hook is present should just run `reconfigure` hook (#5306)

* When a service is started
  1. `post-run` hook should re-run until it succeeds (#2364)

* When a service is upgraded
  1. `post-stop` hook should execute (#5332)
  2. All life-cycle hooks removed from the package are removed from disk on the supervisor node (#4925)

* When a service is stopped
  1. Application will gracefully shutdown with the correct termination signal (user configurable) (#2447)

* `reload` hook is deprecated with a warning given to the user when package is built or run (#5307)
* `smoke-test` hook is removed from Habitat. `smoke-test` hooks are NEVER executed in our system. (#5961)

**Comment by christophermaier** [comment]
Depending on how things unfold, we may also want to pull https://github.com/habitat-sh/habitat/issues/5135 into this.

**Comment by davidMcneil** [comment]
Below represents how I believe lifeclycle hooks work today.
![lifecycle-hooks-old](https://user-images.githubusercontent.com/1497626/60046410-44cba100-9695-11e9-964f-80abd565d44b.png)
Below represents how I believe lifecycle hooks work in this [PR](https://github.com/habitat-sh/habitat/pull/6668)
![lifecycle-hooks-current](https://user-images.githubusercontent.com/1497626/60046409-44cba100-9695-11e9-9e67-b7ab0cc371ee.png)
Below represents how I would like lifecycle hooks to work. This is still a work in progress.
![lifecycle-hooks-proposed](https://user-images.githubusercontent.com/1497626/60046412-45643780-9695-11e9-8a39-738840b72b02.png)
