### ISSUE TITLE
Collect diagnositcs so support can self-diagnose

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#5970]
## Description
We need to start collecting relevant metrics to help troubleshoot deployments. Support will need to be able to self diagnose run time issues.

## Acceptance Criteria
Collect the following metrics:
- memory usage (broken down by subsystem if possible)
- Number of rumors, by type
- CPU utilization (possibly by thread/subsystem)
- bytes sent
- bytes received
- SWIM messages sent (by type)
- SWIM messages received (by type)
- SWIM ping/ack/pingreq round-trip time
- gossip messages sent (by type)
- gossip messages received (by type)
- gossip round trip time
- supervisor "tick" time
- service "tick" time
- hook run times
- number of alive peers
- number of suspect peers
- number of confirmed peers
- number of departed peers
- RPC call counts / timing 
  
  load, unload, start, stop, etc.
- timing for how long metric collection itself takes
- HTTP gateway requests, timings

**Comment by raskchanky** [comment]
I'm in the middle of implementing supervisor metrics right now.  Are there any in particular you'd like me to add?

**Comment by dmccown** [comment]
I don't have any off of the top of my head. Do you have some suggestions on what would be helpful? Have we had reports of data people would like to see that we don't have right now?

**Comment by dmccown** [comment]
Where's that list? Can we incorporate that into acceptance criteria for this epic?

**Comment by raskchanky** [comment]
It's roughly everything mentioned [here](https://github.com/habitat-sh/habitat/issues/5871), give or take.
