### ISSUE TITLE
No way to access confirmed members

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#5984]
I see in sources `svc.members` populated from `active_members` only:
```rust
Svc {
            service_group: Cow::Borrowed(&census_group.service_group),
            election_status: Cow::Borrowed(&census_group.election_status),
            update_election_status: Cow::Borrowed(&census_group.update_election_status),
            members: Cow::Owned(
                census_group
                    .active_members()
                    .iter()
                    .map(|m| SvcMember::from_census_member(m))
                    .collect(),
```
but there is no way to get `suspected`, `confirmed` and `departed` members..
So how to get these members?

Use-case: I have a clustered setup with something like `hosts = host1 host2 host3`. `host2` temporary goes down. I want (usually **must**) persist `host2` settings and prevent scale down. Is it possible?
For example I don't want to reconfigure mongodb replicaset (drop node out) if slave temporary unavailable.

**Comment by chefsalim** [comment]
Keeping this in Needs Triage for further discussion.  Would be great to get more info on the use case.

**Comment by jsirex** [comment]
My personal use-case was about building clustered `core/minio`. When any single node goes down configs will be re-rendered and service will fail because it requires even number of members. So for me there were no way to use service discovery and persist exact number of members. Finally I have got workaround - I don't use service discovery here, but explicit list of members. 

I don't know a better solution right now. Probably, I should close this issue, unless somebody sees here another use-case.
