### ISSUE TITLE
hab sup term panics

### ISSUE THREAD

**Issue by jaym** [habitat-sh/habitat#5988]
I have a studio in which running `hab sup term` panics:

```
[104][default:/src:127]# hab --version
hab 0.70.0/20181205193615
[105][default:/src:0]# hab sup --version
sup 0.70.0/20181205195836
[106][default:/src:0]# hab sup term
thread 'main' panicked at 'LISTEN_GOSSIP should always have a value.', libcore/option.rs:1000:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
[107][default:/src:101]# RUST_BACKTRACE=1 hab sup term
thread 'main' panicked at 'LISTEN_GOSSIP should always have a value.', libcore/option.rs:1000:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: __libc_start_main
  17: <unknown>
```

**Comment by mpeck** [comment]
`hab sup term` was calling the same function that `hab sup run` does to generate a ManagerConfig but with different ArgMatches. This was basically implicitly setting everything to their default values. An initial fix was done here https://github.com/habitat-sh/habitat/pull/5990 and then a follow up that just explicitly sets the ManagerConfig to default was done here https://github.com/habitat-sh/habitat/pull/5950/files#diff-cebe13127ff4a329c357419d517b1b65R198
