### ISSUE TITLE
Habitat studio doesn't respect minikube/docker environment variables

### ISSUE THREAD

**Issue by TheDarkula** [habitat-sh/habitat#6011]
I'm running Arch linux.

When running `eval $(minikube docker-env)`, there are 4 environment variables exported. The relevant commands will be something like:
```
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="~/.minikube/certs"
```

When starting up a habitat studio, the debug output shows us that it's using the docker socket regardless of these environment variables:

```
[2018-12-21T04:51:04Z DEBUG habitat_core::os::process::imp] Calling execvp(): ("/usr/bin/docker") ["run", "--rm", "--privileged", "--tty", "--interactive", "--env", "--volume", "/var/run/docker.sock:/var/run/docker.sock", "habitat/default-studio-x86_64-linux:0.70.0", "enter"]
```

Adding the ability to have the studio use these environment variables would add the ability to export images directly to minikube for local development.

**Comment by TheDarkula** [comment]
I dug through the Rust source and tracked it down to `habitat/components/hab/src/command/studio/docker.rs`. A solution seems to be to push a new value for `DOCKER_HOST` into the `env_vars` vector. It would need to mount the minikube certs folder into the studio as well.

**Comment by eeyun** [comment]
I'm not sure that we would write a whole new exporter for this rather than making the studio aware of the environment variable. That being said, have you tried using the `HAB_DOCKER_OPTS` envvar to set the `-H` flag?

**Comment by TheDarkula** [comment]
That's a great idea. I just ran the studio with `env RUST_LOG=debug HAB_DOCKER_OPTS="-H tcp://0.0.0.0:2376" hab studio enter -D`, but the output showed:
```
unknown shorthand flag: 'H' in -H
See 'docker run --help'.
```

**Comment by avoidik** [comment]
even if you'd have DOCKER_HOST enabled it won't be able to pass through docker volumes to a remote host, any ideas how to do it?

```
/usr/local/bin/docker run --rm --privileged --tty --interactive --env HAB_AUTH_TOKEN=AAA --env HAB_LICENSE=accept-no-persist --env HAB_ORIGIN=blah --env RUST_LOG=debug --volume /home/vja/blah:/src --volume /home/vja/.hab/cache/keys:/hab/cache/keys --volume /home/vja/.hab/cache/artifacts:/hab/cache/artifacts --volume /home/vja/.hab/cache/ssl:/hab/cache/ssl habitat/default-studio-x86_64-linux:0.90.6 enter
```
