### ISSUE TITLE
How used in old syntax in core plans

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6015]

**Comment by dmccown** [comment]
## Description
We'd like to understand how often the incorrect handlebar array syntax is used in core-plans. Habitat currently supports: `{{foo[0]}}`. We'll use this information to understand how much work is involved in making a change.

## Acceptance Criteria
- Report how many instances of that syntax occurs in core-plans

**Comment by mpeck** [comment]
We don't use this syntax at all on core-plans. We only have a single instance of array access in the kibana package, and there we use the good syntax `{{ foo.[0] }}`.

https://github.com/habitat-sh/core-plans/blob/master/kibana/config/kibana.yml#L12
