### ISSUE TITLE
Announce Handlebar change

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6016]

**Comment by dmccown** [comment]
## Description
When we make a syntax change we'll need to communicate this publicly. Post on our Habitat blog explaining the change, when the change will occur, and what you'll need to do to update your plans.

## Acceptance Criteria
- Create a blog post describing the change, timing of the change, and how to update your code to support the change.
- Make sure the changelog clearly communicates that this is a breaking change.
- Give internal communication referencing the blog post.

**Comment by mpeck** [comment]
We have let folks know that the update is coming and that they should update their syntax accordingly, https://github.com/habitat-sh/habitat/issues/6323. We've also let folks know internally so they can help inform customers. Furthermore we also added a deprecation notice to the supervisor, https://github.com/habitat-sh/habitat/pull/6360, and plan on pointing out the upcoming update in the CHANGELOG until we actually do the update. Some folks will probably slip through the cracks, but hopefully this catches the majority.
