### ISSUE TITLE
habitat.sh/try web pages capture all commands

### ISSUE THREAD

**Issue by echohack** [habitat-sh/habitat#604]
![habitat_try](https://cloud.githubusercontent.com/assets/3253989/15719817/83d97b04-27e6-11e6-8925-4bfb4d81a0fe.gif)

When on https://www.habitat.sh/try or any of its child pages, commands do not work. IE: Opening a new tab (ctrl + t) or copy (ctrl + c) or paste (ctrl + v).

It appears what's happening is that there is no way to unfocus the command shell in the window and that the command shell prevents any kind of regular browser behavior. So while this might be a side effect of the cool in-browser command shell, it also doesn't feel great to the user, who might want to copy and paste commands out from the tutorial, open new tabs in their browser, etc.

**Comment by ryankeairns** [comment]
We'v also heard that this does not work on FF for Android.

**Comment by ryankeairns** [comment]
Changed from 'Ready' to 'Icebox' as this appears to be an underlying issue with the javascript tool that we're using for terminal emulation... likely the culprit on #957 as well. Sounds like we would end up gutting this solution for another which would also entail re-writing the response framework, etc.

**Comment by smurawski** [comment]
I think the in-browser experience is best effort.  If we find a way to improve that experience, we can circle back.
