### ISSUE TITLE
hab studio -k / -D (docker) switches do not work together

### ISSUE THREAD

**Issue by gfodor** [habitat-sh/habitat#6071]
Starting with habitat 0.60.0, it seems no longer possible to run a hab studio by passing an origin on the command switches via `-k` and forcing a docker container via `-D`. The studio fails to start with "Unkown Studio Command".

Using HAB_ORIGIN as a way to specify the origin also seems to fail for different reasons, but is outside of the scope of this bug.

OS: Ubuntu Linux 18.04

Command: `hab studio -k foo -D run ls`

Expected behavior: studio should run, or if "foo" has no sig keys, should error complaining about missing keys

Actual behavior: hab fails to run no matter what, saying "Unknown Studio Command"

In versions prior to 0.60.0, this combination of switches worked as expected.

Environment only has HAB_AUTH_TOKEN

**Comment by smacfarlane** [comment]
Ref: #6056

**Comment by dmccown** [comment]
This only appears to happen on Linux. Windows is not affected.
