### ISSUE TITLE
Proposal for Rumor Persistence

### ISSUE THREAD

**Issue by mpeck** [habitat-sh/habitat#6079]
## Problem
During operation rumors are held in memory and persisted to disk approximately every 30 seconds. Persisted rumors are kept in a binary file. Due to way that the file is constructed interrogating it is not straight forward. As a result we only seem to read the file on startup to load rumors into memory; from that point on we only write to it. We also have no way to determine which rumors have been persisted and which haven’t. This results in us writing the complete set of rumors in memory to disk approximately every 30 seconds.

Additionally the logic that handles the storing and persistence bits is a bit fragmented. Persistence logic is located in `rumor/dat_file`. The rumor store is separate and in `rumor/RumorStore`. The persistence loop is run in a function in the main server module, `server/mod/persist_loop`, which is kicked off in it’s own thread in `server/Server/start`. This isn’t technically a problem, but I wonder if it would be better to add some additional abstractions to help unify these bits.
Food for thought 
Currently the rumor store is just a type on the server struct. Persistence is handled by spinning up a new thread and with a reference to the server instance via `Arc`. This means that we have multiple processes sharing a chunk of memory, so we have to deal with memory locks and whatnot further complicating things. If instead we refactored the rumor store to work as an actor and spun it up in its own thread, we could abstract away rumor persistence to the rumor store. That gives us the flexibility to switch out the persistence layer with whatever we see fit.

To be clear I’m not suggesting that we rewrite butterfly right now to use the actor pattern. I only bring it up because it feel like it would be a good architecture for the type of system that butterfly is trying to be and I would like to keep that in mind while we discuss things. 

## The Solution
Regardless of how we decide to solve this particular issue we will most likely also need a way to determine which rumors have been persisted and which haven’t. We currently track an `update_counter` on the `RumoreStore` type which we may be able to leverage somehow, but I’m thinking that we will need to have a more granular way to identify un-persisted rumors. Maybe just a flag on individual rumors, or we could add an index to the `RumorStore` that lists un-persisted rumors?

### Solution 1: Multiple files
Split rumors up between multiple files based on the rumor type.

Pros:
* Allows us to simplify the format of our files (We don’t have to worry so much about headers and space calculations)
* Makes appending data fairly simple. 
* Allows us to add some simple optimizations without necessarily changing the structure of rumors. Like only writing a specific rumor type to disk if there are new rumors. We already have a field for `update_counter` that we could potentially leverage.

Cons:
* If we are appending rumors to files we would need to come up with a solution for removing rumors. We get that for free now since we rewrite the entire file every time. We could write rumors to disk as operations instead of actual rumors, something akin to an event stream. That would likely require us to periodically reconcile the stream at set intervals to compact the data.

Unknowns:
* I’m also not sure what the complexity implications are for having multiple files.
* Would this actually help to reduce our disk IO? We could do an initial implementation behind a feature flag as an opt-in and gather metrics.
* Would this be a net increase or decrease in complexity?

### Solution 2: Add an index
Add an index to the existing rumor file.

Pros:
* Would give us a way to randomly access rumors

Cons:
* I think we would basically be implementing a database
* I don’t want to build a database

Unknowns:
* Do we really want to build a database?

### Solution 3: Utilize a third party datastore
Use something like sqlite to persist rumors.

Pros:
* We don’t have to think about it quite so much.
* We could potentially eliminate a lot of code.

Cons:
* It adds another dependency.

Libraries:
* https://github.com/stainless-steel/sqlite
* https://github.com/jgallagher/rusqlite (Seems to be the most active)

### Solution 4: Event Stream
As mentioned in solution 1 we could use something akin to an event stream. But instead of maintaining separate files for each rumor type we could keep everything in one or two files. Maybe one file for reconciliation and then another for the actual event stream?

Pros:
* Makes appending data easier
* Keeps file count low

Cons:
* Requires a reconciliation step

Unknowns:
* Would this actually reduce disk IO?

## Migration
Regardless of which solution we decide to use changing the format of the rumor file will likely necessitate some migration work. Fortunately I don’t think any of these proposed solutions would require us to break existing functionality. We should be able to build things out behind a feature flag and allow users to opt in. This also allows us to gather some metrics around the old vs new implementations; then we can make decisions based on actual data. Speaking of metrics...

## Metrics
It seems like it would behoove us to add some tooling around this particular bit of the supervisor and start gathering data now. Then we have something to compare to before we actually flip the switch.

## JSON
There was some discussion on converting the existing file format from our own proprietary binary format to json. Obviously json would make the file much more human readable; but with that file sizes would likely grow much larger. Given the sizes that we see now I think it would be a mistake to use json as the primary format. However I do think it would be worth us to develop some tooling to convert the binary file to json for debug purposes.

**Comment by christophermaier** [comment]
An easy first step would be adding some metrics around the current persistence. If we need to change something, that'd provide a good baseline.

**Comment by mpeck** [comment]
I'm in agreement with @christophermaier. It seems like adding some metrics around it would be a good place to start. Maybe then the first thing is to decide what those metrics might be?

**Comment by baumanj** [comment]
I think the qualitative question ("Does this make performance noticeably bad?") is more important than the quantitive question ("How much time/disk bandwidth are we using to persist the rumors?"), but as far as metrics go, the two that jump out for me are:

1. bytes written each time we persist
2. time to persist

We already know (1) because that's just the size of the .rst on disk, but (2) should be easy enough to instrument. I'd say the average isn't as interesting as the variance and standard deviation since if the time to write is very consistent, it implies there's little contention for the disk resources. However, that's going to depend a lot on the particular environment we're running in.

I'm assuming that all the work to serialize the rumors is highly efficient, so I'd say we're down to a question of how much data we can write before we're causing I/O problems. That's going to be a question of the hardware we're running on as well as the services we're competing against for disk resources.
