### ISSUE TITLE
Inconsistent results location between Windows and Linux studio builds

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6084]
Currently, if you build from the root of the studio, and your plan path is not in the root, Linux and Windows builds will generate results in different locations if you issue a build from the root.  Linux will generate results in the root, whereas Windows will generate results where the plan path is.  We should make these consistent.

**Comment by fnichol** [comment]
Oh yeah, the idea was to always create the results dir in your starting working directory. That is `./results` from where you run `hah pkg build`.

I guess what I’m suggesting is that we correct the Windows behavior and preserve the Linux behavior.
