### ISSUE TITLE
Create a "hab svc restart" command

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6110]
Running `hab svc stop` followed by `hab svc start` has a few race conditions inherent to how the code is currently structured. If you really want to restart a service, it'd be nice to have a way to say that explicitly.

The logic already exists inside the Supervisor, since this is effectively what happens when a service is updated (this is more streamlined and explicit in https://github.com/habitat-sh/habitat/pull/6107 [unmerged at present]).

**Comment by davidMcneil** [comment]
A `hab pkg reload` (`hab pkg unload && hab pkg load`) would be very useful as well.
