### ISSUE TITLE
Configure rustfmt to consistently wrap comments

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6130]
People have different editor settings, which can result in inconsistent wrapping of comment blocks, particularly blocks in moderately-to-heavily indented code.

`rustfmt` [can be configured](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#wrap_comments) to do this consistently, so we should get that set up.

**Comment by raskchanky** [comment]
I had no idea that `rustfmt` was so configurable.  Is it worth taking a pass through all the configuration options and making sure we have everything configured the way we want it?  I realize, given the number of options, that could be kind of a big task.  😁

**Comment by christophermaier** [comment]
@raskchanky Yeah, could be. We could do something like @baumanj did with https://github.com/habitat-sh/habitat/pull/6100.

**Comment by raskchanky** [comment]
That sounds good to me.  I'm kinda interested to dig into this, tbh.  😁

**Comment by baumanj** [comment]
Go for it!

**Comment by raskchanky** [comment]
I notice in the configuration options, some are stable, and some are unstable.  My first instinct was to only configure stable items, but there are _a lot_ of good things that are considered unstable.  One example is [merge_imports](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#merge_imports).  Any thoughts on enabling unstable items?

**Comment by baumanj** [comment]
I'm not really sure what unstable means in this case, so I guess part of the work would be investigating that, but my guess is that it means they may remove or change the semantics of the option later without deprecating it nicely. In that case, it just means our rustfmt CI will break and we'll fix it. So, I'm not concerned about using unstable options if they sound beneficial to us.

**Comment by raskchanky** [comment]
It turns out that unstable options are only available to nightly toolchains 😞

**Comment by raskchanky** [comment]
Also `wrap_comments`, the whole reason for making this issue, isn't stable, so we can't use it.  😭

**Comment by christophermaier** [comment]
This is why we can't have nice things 😦

**Comment by baumanj** [comment]
We can run parts of our CI on nightly. Why shouldn't we? It's pretty easy with travis, and I don't see why BuildKite should be any harder.

**Comment by baumanj** [comment]
Even if we don't go that route, we can use these tools on our local machines to do one-off fixes to the whole codebase that stable `rustfmt` will leave alone.

**Comment by raskchanky** [comment]
That's a fair point that I hadn't considered.  I'll revisit my PR and add in all of the unstable options as well.  If stable `rustfmt` just ignores those, then it won't hurt to have them present, and as you say, we can do one-off fixes locally.
