### ISSUE TITLE
Add `ssl_cert_file` to `cli.toml`

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/habitat#6158]
As a regular user that uses hab behind a Corp firewall, it would make life easier to configure the hab cli to respect a config file versus always having to export environment vars.

While it’s nice to configure with envvars or command switches, over time we had to create wrapper scripts that always set SSL_CERT_FILE and HAB_BLDR_URL.  This is problem number one. Wrapper scripts for new hab users have made using hab even more obscure. 

dev
```
#!/bin/bash

HAB_BLDR_URL=... SSL_CERT_FILE=... hab $@
```

```
./dev studio enter
```

You tell them to just do hab commands and they look at you funny...

Another thing we noticed is that our users have inconsistent profiles when doing deployments on a hab-machine.  We ssh in with a headless deploy user and normally have to sudo as root in order to modify things under /hab filesystem.  We have had to setup the hab environment variables for the deploy user and for the root user.  Also if the machine is shared, we also had to setup the environment variables for that user as well.  This is problem number 2 - hab should just work without telling people that you need to set special envvars (all the time). 

While we can tell our team to create bash exports in their profile for this, it would be nice when we provision a new dev machine or another hab machine, we can just set up the hab cli to look at `/etc/hab/cli.toml`  It doesn’t matter what user you are, the hab cli can just refer to this for sane global defaults. 

So yes, I am tired of always adding this to my hab commands:

```
SSL_CERT_FILE=/path/to/corp.pem hab ...
```

I'm also tired of always having to export that env var.

Like how we added `bldr_url` to the `cli.toml` in #5663.  We should do the same for `ssl_cert_file` as a parameter in the `cli.toml`.

**Comment by eeyun** [comment]
So I think this points to a more general usability issue and I think you're onto something here! Would you mind potentially adding some more context around when/why you're using this envvar to the issue and consider renaming the title to express the problem more specifically? Thanks for opening this one @bdangit !!

**Comment by bdangit** [comment]
Hey @eeyun just updated the ticket with more context. I can’t modify the title though. 

Perhaps it should be renamed “hab needs a global default config”
