### ISSUE TITLE
Remove docker-studio publish for windows from studio and bintray-publish

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6179]
The creation and upload of the windows docker studio image is now handled by the release pipeline. The `components/studio/build-docker-image.ps1` script should be removed and the `bintray-publish` script and plan should be refactored to remove that dependency.

**Comment by mwrock** [comment]
closing. this was done via https://github.com/habitat-sh/habitat/commit/660cccc3a86cd71b1c7ab3a80eb17572224ca06a#diff-17607e73f3b54ac2a84e26358ce59512
