### ISSUE TITLE
`hab plan render` should load user data

### ISSUE THREAD

**Issue by qubitrenegade** [habitat-sh/habitat#6204]
If `--user-toml` is not supplied to `hab plan render`, should load the `/hab/user/myservice/config/user.toml` if it exists.

This would require knowing the name of the package that is running.

**Comment by themightychris** [comment]
That might be problematic for using `hab plan render` for dev/testing, as in introducing a possibly unexpected environmental variable

Maybe solve both problems at once with a new option like `--user-toml-service=myservice`

**Comment by themightychris** [comment]
no not stale!
