### ISSUE TITLE
Add friendly output to hab svc load

### ISSUE THREAD

**Issue by echohack** [habitat-sh/habitat#6230]
Currently (0.75.0) `hab svc load` output in practice looks like so:

(Run inside of Terraform)

```
module.elasticsearch.null_resource.elasticsearch[2] (remote-exec): + sudo -E hab svc load jeremymv2/automate-backend-elasticsearch --topology leader --strategy rolling --channel unstable
module.elasticsearch.null_resource.elasticsearch[1] (remote-exec): » Installing jeremymv2/automate-backend-elasticsearch
...
```

These logs make it tough to understand the conditions under which the service was started, especially when folks use default arguments instead of explicitly specifying all of the arguments. This can lead to simple mistakes in specifying arguments to `hab svc load` resulting in hours of debugging when things don't start up as planned. For example, what if someone was trying to start an elasticsearch cluster, which requires leader election, but forgot to specify the leader topology? They might spend unnecessary time pulling out tcpdump and other tools when they are surprised that the leader election component isn't working properly.

Instead, what if we provided some simple feedback to the user?

```
module.elasticsearch.null_resource.elasticsearch[2] (remote-exec): + sudo -E hab svc load jeremymv2/automate-backend-elasticsearch --topology leader --strategy rolling --channel unstable
module.elasticsearch.null_resource.elasticsearch[2] (remote-exec): » Loading service jeremymv2/automate-backend-elasticsearch, application: <none>, binds: <none>, binding-mode: strict, url: https://bldr.habitat.sh, environment: <none>, health-check-interval: 30, remote-sup: 127.0.0.1:9632, group: default, topology: leader, strategy: rolling, channel: unstable
module.elasticsearch.null_resource.elasticsearch[2] (remote-exec): » Installing jeremymv2/automate-backend-elasticsearch
...
```

I think this simple feedback can be a great way of helping operators or support personnel more quickly solve simple argument issues.

**Comment by jeremymv2** [comment]
👍 Agreed - essentially logging the serialized service spec file would go a long way to help with troubleshooting when the user isn't aware of the service spec file or doesn't have direct access to it.
