### ISSUE TITLE
Ability to skip artifact creation during iteration in the Studio

### ISSUE THREAD

**Issue by bixu** [habitat-sh/habitat#6233]
Studio-based development would be dramatically faster if there were an option to skip the artifact-creation state - collecting, tar-ing and compressing files (especially when using Node or Python modules with lots of dependencies) can be excruciatingly slow.

UX ideas:
```
hab pkg build --no-artifact
build --no-artifact # inside the Studio
```
Currently, I'm experimenting with overriding `_generate_artifact` to get around this. (Thanks @jsirex for the suggestion).

**Comment by bixu** [comment]
Here's one workaround, albeit a bit clunky (it requires the we set `HAB_CREATE_PACKAGE=false` somewhere:
```
do_after() {
  if [ $HAB_CREATE_PACKAGE == 'false' ]
  then
    build_line "WARN: Skipping artifact creation because 'HAB_CREATE_PACKAGE=false'"

    _generate_artifact() {
      return 0
    }

    _prepare_build_outputs() {
      return 0
    }
  fi
}
```

**Comment by stevendanna** [comment]
One note that might give some short-term relief: You can set `HAB_HART_COMPRESSION_LEVEL=0` during development.  You will get much larger artifacts, but they are MUCH faster to create.

**Comment by bixu** [comment]
We also use this setting. While it does help, for packages with a lot of files included (think Pip or NPM projects), just enumerating and tar-ing the files is pretty time-consuming.
