### ISSUE TITLE
Plan build works under 0.74 but not 0.76

### ISSUE THREAD

**Issue by chrisortman** [habitat-sh/habitat#6245]
I have a plan that fails to build under hab 0.76.0

It appears that when the plan build sets up the PATH variable it does not include transitive dependencies.

Successful build with hab explicitly set to 0.74 https://travis-ci.org/ui-icts/aptamer-web/builds/500442889

Failed build where it uses 0.76 https://travis-ci.org/ui-icts/aptamer-web/builds/500403895

plan file: https://github.com/ui-icts/aptamer-web/blob/master/habitat/plan.sh

**Comment by stevendanna** [comment]
It's possible it is related to: https://github.com/habitat-sh/habitat/pull/6240

**Comment by chrisortman** [comment]
@stevendanna Looks like it thanks!
