### ISSUE TITLE
Resolve the illusive bug in hab-plan-build.sh

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#6250]
Changes to `hab-plan-build.sh` were made in https://github.com/habitat-sh/habitat/commit/65a1f99e0e240d582f099c322a5ca63ae82a06b0 and https://github.com/habitat-sh/habitat/commit/a03510ce2745ca3bcd1c320b21c1e7e280b702d1 that caused things to break.  Specifically, an extra line was added to the `TDEPS` file.  In the interest of not leaving our users in a broken state, those changes were reverted by https://github.com/habitat-sh/habitat/pull/6248.

However, it's been recognized that the lints that were added were good ones that are worth keeping.  There is apparently some kind of deeper issue that caused a failure when those lints were put in place and the corresponding code changed.

We should solve the deeper problem and re-enable the lints.

**Comment by raskchanky** [comment]
It sounds like my assessment of this is not entirely correct.  Apparently the 0.76.0 release is only writing `DEPS` to the `TDEPS` file.

**Comment by baumanj** [comment]
Ok, I have what I think is a repo. Here are the basic steps:

1. Install 0.76.0:
    ```sudo bash ~/habitat/components/hab/install.sh -v 0.76.0```
1. Check out `core-plans` repo (I used revision `549f91f0ae9a71cc13c963913d1942395fb93071`)
1. From root of `core-plans` repo, remove any existing studio
    ```hab studio rm```
1. ```hab studio enter```
1. ```build rust```
1. Examine the TDEPS file (`/hab/pkgs/jbauman/rust/1.32.0/20190301222052/TDEPS` in my case) and see that these 3 entries are missing from the same procedure with 0.75.0:
    - `core/gmp/6.1.2/20190115003943`
    - `core/libmpc/1.1.0/20190115004027`
    - `core/mpfr/4.0.1/20190115004008`

**Comment by baumanj** [comment]
Here's where I see the logs above diverge around line 418 of the logs. This is the code difference:

```bash
_set_build_tdeps_resolved() {
  # Copy all direct build dependencies into a new array
  pkg_build_tdeps_resolved=("${pkg_build_deps_resolved[@]}")
  # Append all non-direct (transitive) run dependencies for each direct build
  # dependency. That's right, not a typo ;) This is how a `acme/gcc` build
  # dependency could pull in `acme/binutils` for us, as an example. Any
  # duplicate entries are dropped to produce a proper set.
  for dep in "${pkg_build_deps_resolved[@]}"; do
```
```bash
    tdeps=($(_get_tdeps_for "$dep"))
```
0.75 → 0.76
```bash
    read -r -a tdeps <<< "$(_get_tdeps_for "$dep")"
```
```
    for tdep in "${tdeps[@]}"; do
      tdep="$HAB_PKG_PATH/$tdep"
```
```bash
      pkg_build_tdeps_resolved=(
        $(_return_or_append_to_set "$tdep" "${pkg_build_tdeps_resolved[@]}")
      )
```
0.75 → 0.76
```bash
      read -r -a pkg_build_tdeps_resolved <<< "$(_return_or_append_to_set "$tdep" "${pkg_build_tdeps_resolved[@]}")"
```
```
    done
  done
}
```

The logs show:
```
+ for tdep in "${tdeps[@]}"
+ tdep=/hab/pkgs/core/gcc-libs/8.2.0/20190115011926
```
in 0.75 the next line is:
```
+ pkg_build_tdeps_resolved=($(_return_or_append_to_set "$tdep" "${pkg_build_tdeps_resolved[@]}"))
```
in 0.76, it's (as expected, different):
```
+ read -r -a pkg_build_tdeps_resolved
```
Then they return to being the same for awhile:
```
++ _return_or_append_to_set /hab/pkgs/core/gcc-libs/8.2.0/20190115011926 /hab/pkgs/core/patchelf/0.9/20190115011946 /hab/pkgs/core/findutils/4.6.0/20190115013303 /hab/pkgs/core/coreutils/8.30/20190115012313
++ local appended_set
++ _array_contains /hab/pkgs/core/gcc-libs/8.2.0/20190115011926 /hab/pkgs/core/patchelf/0.9/20190115011946 /hab/pkgs/core/findutils/4.6.0/20190115013303 /hab/pkgs/core/coreutils/8.30/20190115012313
++ local e
++ for e in "${@:2}"
++ [[ /hab/pkgs/core/patchelf/0.9/20190115011946 == \/\h\a\b\/\p\k\g\s\/\c\o\r\e\/\g\c\c\-\l\i\b\s\/\8\.\2\.\0\/\2\0\1\9\0\1\1\5\0\1\1\9\2\6 ]]
++ for e in "${@:2}"
++ [[ /hab/pkgs/core/findutils/4.6.0/20190115013303 == \/\h\a\b\/\p\k\g\s\/\c\o\r\e\/\g\c\c\-\l\i\b\s\/\8\.\2\.\0\/\2\0\1\9\0\1\1\5\0\1\1\9\2\6 ]]
++ for e in "${@:2}"
++ [[ /hab/pkgs/core/coreutils/8.30/20190115012313 == \/\h\a\b\/\p\k\g\s\/\c\o\r\e\/\g\c\c\-\l\i\b\s\/\8\.\2\.\0\/\2\0\1\9\0\1\1\5\0\1\1\9\2\6 ]]
++ return 1
++ appended_set=("${@:2}" "$1")
++ echo /hab/pkgs/core/patchelf/0.9/20190115011946 /hab/pkgs/core/findutils/4.6.0/20190115013303 /hab/pkgs/core/coreutils/8.30/20190115012313 /hab/pkgs/core/gcc-libs/8.2.0/20190115011926
++ return 0
```
But *after* this is the key, I think. 0.75 has:
```
+ for tdep in "${tdeps[@]}"
```
which is another iteration in the inner loop, whereas 0.76's next line is
```
+ for dep in "${pkg_build_deps_resolved[@]}"
```

0.75 doesn't see another occurrence of `for dep in "${pkg_build_deps_resolved[@]}"` until line 474 of the log output. Based on that we can see that the inner loop of 0.75 saw the following values for `tdep`:
```
+ tdep=/hab/pkgs/core/gcc-libs/8.2.0/20190115011926
+ tdep=/hab/pkgs/core/glibc/2.27/20190115002733
+ tdep=/hab/pkgs/core/linux-headers/4.17.12/20190115002705
```
But 0.76 only saw
```
+ tdep=/hab/pkgs/core/gcc-libs/8.2.0/20190115011926
```
Since both use the same `for tdep in "${tdeps[@]}"; do`, it must be the case that 0.75's `tdeps=($(_get_tdeps_for "$dep"))` is properly creating an array with separate values whereas 0.76's `read -r -a tdeps <<< "$(_get_tdeps_for "$dep")"` is creating a single element array.

This seems to be the issue addressed in https://github.com/habitat-sh/habitat/pull/6240. I'm going to try applying that patch and see if there's still an issue.

**Comment by baumanj** [comment]
Aha! With the changes from https://github.com/habitat-sh/habitat/pull/6240, now I see the extra newline:
```
[5][default:/src:0]# cat /hab/pkgs/jbauman/rust/1.32.0/20190301233023/TDEPS 

core/binutils/2.31.1/20190115003743
core/busybox-static/1.29.2/20190115014552
core/cacerts/2018.12.05/20190115014206
core/gcc-libs/8.2.0/20190115011926
core/gcc/8.2.0/20190115004042
core/glibc/2.27/20190115002733
core/gmp/6.1.2/20190115003943
core/libmpc/1.1.0/20190115004027
core/linux-headers/4.17.12/20190115002705
core/mpfr/4.0.1/20190115004008
core/zlib/1.2.11/20190115003728
```
`DEPS` seems fine though:
```
[6][default:/src:0]# cat /hab/pkgs/jbauman/rust/1.32.0/20190301233023/DEPS
core/busybox-static/1.29.2/20190115014552
core/cacerts/2018.12.05/20190115014206
core/gcc-libs/8.2.0/20190115011926
core/gcc/8.2.0/20190115004042
core/glibc/2.27/20190115002733
core/zlib/1.2.11/20190115003728
```
I'll re-run with a full trace to track down where that extra newline is coming from.

**Comment by baumanj** [comment]
Here are full logs. I don't have time to dig into them now, but will return to them on Monday.

[plan-build-bug-0.76-6240-debug.txt](https://github.com/habitat-sh/habitat/files/2921452/plan-build-bug-0.76-6240-debug.txt)

**Comment by baumanj** [comment]
There's definitely an `/hab/pkgs/` entry at the end here that gets converted to that blank line by [the `cut` command in `_render_dependency_metadata_file`](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/shared.bash#L317):
```
+ _render_dependency_metadata_file /hab/pkgs/jbauman/rust/1.32.0/20190301233922 TDEPS pkg_tdeps_resolved
+ local prefix=/hab/pkgs/jbauman/rust/1.32.0/20190301233922
+ local metadata_file_name=TDEPS
+ declare -n arr=pkg_tdeps_resolved
++ echo /hab/pkgs
++ grep -o /
++ wc -l
+ local cutn=4
+ local deps
++ printf '%s\n' /hab/pkgs/core/glibc/2.27/20190115002733 /hab/pkgs/core/gcc-libs/8.2.0/20190115011926 /hab/pkgs/core/zlib/1.2.11/20190115003728 /hab/pkgs/core/gcc/8.2.0/20190115004042 /hab/pkgs/core/cacerts/2018.12.05/20190115014206 /hab/pkgs/core/busybox-static/1.29.2/20190115014552 /hab/pkgs/core/linux-headers/4.17.12/20190115002705 /hab/pkgs/core/binutils/2.31.1/20190115003743 /hab/pkgs/core/gmp/6.1.2/20190115003943 /hab/pkgs/core/libmpc/1.1.0/20190115004027 /hab/pkgs/core/mpfr/4.0.1/20190115004008 /hab/pkgs/
```

Now to figure out how that `/hab/pkgs/` is getting in there.

**Comment by baumanj** [comment]
The first thing that looks suspicious are these logs lines on L1208 and 9:
```
+ tdep=/hab/pkgs/
+ read -r -a pkg_tdeps_resolved
```
Why is `tdep` getting set to just `/hab/pkgs/`? This is what gets stripped out later to end up a blank line. The proximity of the `read -r -a pkg_tdeps_resolved` tells us this occurs [at line 1105](https://github.com/habitat-sh/habitat/blob/5052ace7034b3221044f87242c9a43f569e4952f/components/plan-build/bin/hab-plan-build.sh#L1105) in the PR #6240 code.

That means it must've come from:
```bash
mapfile -t tdeps < <(_get_tdeps_for "$dep")
```
In the logs, this shows up as:
```
++ _get_tdeps_for /hab/pkgs/core/cacerts/2018.12.05/20190115014206
```
Checking locally, there's no TDEPS file for this package:
```
[10][default:/src:1]# ls /hab/pkgs/core/cacerts/2018.12.05/20190115014206/
FILES  IDENT  MANIFEST  TARGET  TYPE  ssl
```
Looking at the code for `_get_tdeps_for`
```bash
_get_tdeps_for() {
  local pkg_path="$1"
  if [[ -f "$pkg_path/TDEPS" ]]; then
    cat "$pkg_path"/TDEPS
  else
    # No file, meaning an empty set
    echo
  fi
  return 0
}
```
In the event the `TDEPS` file doesn't exist, the function prints a newline. This results in an array with a single element which is the empty string:
```bash
$ mapfile -t tdeps < <(echo)
$ declare -p tdeps
declare -a tdeps=([0]="")
```
If instead the function prints nothing (`:` is bash for a no-op), we get properly empty array:
```bash
$ mapfile -t tdeps2 < <(:)
$ declare -p tdeps2
declare -a tdeps2=()
```
When I change these functions
```bash
_get_tdeps_for() {
  local pkg_path="$1"
  if [[ -f "$pkg_path/TDEPS" ]]; then
    cat "$pkg_path"/TDEPS
  fi
}

_get_deps_for() {
  local pkg_path="$1"
  if [[ -f "$pkg_path/DEPS" ]]; then
    cat "$pkg_path"/DEPS
  fi
}
```
and rerun `build rust`, The values for TDEPS and DEPS appear to be correct:
```
[14][default:/src:0]# cat /hab/pkgs/jbauman/rust/1.32.0/20190302053135/TDEPS 
core/binutils/2.31.1/20190115003743
core/busybox-static/1.29.2/20190115014552
core/cacerts/2018.12.05/20190115014206
core/gcc-libs/8.2.0/20190115011926
core/gcc/8.2.0/20190115004042
core/glibc/2.27/20190115002733
core/gmp/6.1.2/20190115003943
core/libmpc/1.1.0/20190115004027
core/linux-headers/4.17.12/20190115002705
core/mpfr/4.0.1/20190115004008
core/zlib/1.2.11/20190115003728
[15][default:/src:0]# cat /hab/pkgs/jbauman/rust/1.32.0/20190302053135/DEPS  
core/busybox-static/1.29.2/20190115014552
core/cacerts/2018.12.05/20190115014206
core/gcc-libs/8.2.0/20190115011926
core/gcc/8.2.0/20190115004042
core/glibc/2.27/20190115002733
core/zlib/1.2.11/20190115003728
```
