### ISSUE TITLE
Output a full plan.sh when initializing a new project

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6267]
## Description
When creating a new plan with `hab plan init` we lay down a base plan file. Suppose you are building a Java project and run your first build. You'll start seeing error related to building a C project. You'll then look at your plan file and have no idea what build step you need to override or where that C related command is even coming from. You'll need to find our source and then see the specific step you need to override.

 It would be really helpful to do something like [default_build_call_backs.sh · GitHub](https://gist.github.com/ericcalabretta/a2609425ae9e51c3deba7687f4fa2715) which in-lines all the default behaviors, so you can quickly determine what steps to override and when without referring to source. 

We should also link directly to documentation where appropriate.

## Acceptance Criteria
1. Run `hab plan init` to create a new project
2. Verify the plan is complete with a default implementation, so it's easy to update.

**Comment by davidMcneil** [comment]
It looks like there are currently options to `init` to output a complete plan `--with-all`, `--with-docs`, `--with-callbacks`. `--with-all` was broken so I am adding a pull request to fix that. These options do not list the implementation of the `do_default_*` functions but the output does give a [link](https://github.com/habitat-sh/habitat/tree/master/components/plan-build/bin/hab-plan-build.sh) to the implementations. Is that sufficient?

**Comment by dmccown** [comment]
If possible it would be great to get the `do_default_*` implementations in-lined in the initial plan. That would save users from having to look up the default implementation. @christophermaier any thoughts on this?

I'm open  if this would take a couple of steps to achieve as well. E.g. first cut would be doing as you described and from there we could look at in-lining these functions.
