### ISSUE TITLE
Alias hab studio enter to an easier command for dictation

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6268]
## Description
Alias `hab studio enter` to something easier like `hab studio`. While we were trying to pair with a new Habitat user I would say, "type hab studio enter" and 90% of the type they would push "enter" after typing "hab studio".

**Comment by ericcalabretta** [comment]
I think we can close this issue. 

At least on MacOS `hab studio` now behaves identical to `hab studio enter`
