### ISSUE TITLE
Modify verify pipeline to have more direct control over Rust version used

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6274]
When we recently updated to Rust 1.33.0, we discovered that our verify pipeline is pulling Rust from a pre-built Docker image, rather than installing Rust using a repository-controlled configuration variable, as we do in our release pipeline: 

https://github.com/habitat-sh/habitat/blob/2a42a321b6766bcbd24d1c14f4209160a4536ba8/.buildkite/env#L10-L12)).

While we can ask Release Engineering to create a new version of the Docker image easily enough, it adds friction to the process, and is unexpected, given how our release pipeline is currently configured.

One thing we might want to do is use the `core/rust` package from Builder. We build and promote a package to stable when we're ready to consume it in our packages, so that could reduce the number of places where we have to manually manage version pins. Additionally, the rest of the dependencies needed to build our code and run tests are already pulled in from Builder:

 https://github.com/habitat-sh/habitat/blob/2a42a321b6766bcbd24d1c14f4209160a4536ba8/test/run_cargo_test.sh#L33-L55)

Whichever path we ultimately choose, it would be nice to have a consistent and low-friction way to control what version of Rust is being used in our various pipelines.

**Comment by raskchanky** [comment]
I vote for using `core/rust`, since we always bump that at the same time we bump the rest of the repos.  As you say, going that route will reduce the number of places we have to manually manage pins.

**Comment by scotthain** [comment]
Do we have a `core/rust` crate for windows? I feel like there was an issue with using `core/rust` but I could be wrong. That being said, I'm all for using it if we can.

**Comment by raskchanky** [comment]
@scotthain Yes sir https://github.com/habitat-sh/core-plans/blob/master/rust/plan.ps1

**Comment by baumanj** [comment]
I *think* this was addressed by https://github.com/habitat-sh/habitat/pull/6593, but please re-open if not.
