### ISSUE TITLE
Remove license boilerplate from the top of each file

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6286]
I heard back from the legal department, and we can safely remove all the license boilerplate from the top of our source code files, relying instead on the presence of the `LICENSE` file at the root of the repository.

No more worrying about whether or not we need to update copyright years!

EDIT: We should also fix this 😂 : https://github.com/habitat-sh/habitat/blob/2dfd144489bdbe3f3d9439b80f53bc89b2d2b8fe/LICENSE#L190

**Comment by echohack** [comment]
I don't know why but I am hype for this change!

I guess I am hype because license boilerplate has always bothered me in other contexts, and removing it entirely makes the code instantly more readable.

<3
