### ISSUE TITLE
'hab pkg upload' fails with permission denied when uploading from /hab/cache/artifacts directory

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6298]
It is a fairly useful scenario to be able to upload packages to a depot from a cached artifact directory (eg /hab/cache/artifacts).  As of 0.78 this fails with a 'permission denied' error because we are writing the downloaded artifacts with a root-only read access.  So a user has to do a 'sudo' in this case.  Also we don't give any indication of which file the permission denied is happening on, so its not super obvious to debug from a users perspective.

We should consider changing the privileges back to what they were prior to 0.78 so we don't require sudo in such cases.  The installed packages themselves are fully world readable, just the artifact is locked down.

This is a side effect of this change - https://github.com/habitat-sh/habitat/pull/5803#issuecomment-465790809

**Comment by chefsalim** [comment]
Also note this behavior may possibly also break on-prem package sync and other scenarios where we manipulate hart files

**Comment by baumanj** [comment]
Given that the artifact must have been installed with `sudo`, it seems reasonable to require `sudo` to access it again. In the case of private origins, it may be restrict access to only certain users on a host.

The fact that the installed package has different permissions than the artifact does seem like an improper inconsistency. If we want to allow users to lock things down, we should. In the past, users have desired more secure and granular access configuration, so this may be a good opportunity to review what we'd like to make available. Possibly we can default to a more locked-down approach but provide an option for configuring a more permissive default.

**Comment by stevendanna** [comment]
Some issues mentioned in chat and other thoughts:

- Should files downloaded from private origins also be world readable?

- The permissions on files inside the package depends on what they were when they were built.  So, it is possible for a user to create packages where the files are not world readable:

```
ls -al /hab/pkgs/ssd/teams-service/0.1.0/20190314224410/bin/
total 20344
drwxr-xr-x 2 root root     4096 Mar 14 22:45 .
drwxr-xr-x 7 root root     4096 Mar 14 22:45 ..
-r-------- 1 root root        0 Mar 14 22:45 foo
-rwxr-xr-x 1 root root 20822669 Mar 14 22:45 teams-service
```
- In addition to packages, other files such as public keys are also now 0600.  Public keys seem less controversial to change back to 0666.

- I'm wondering if maybe the path is to change packages back to 0666 while we sort out solutions to the various use cases.  It seems like non-root users need to be able to read these packages because we have started using this cache to support other functionality.

**Comment by stevendanna** [comment]
Also note: Technically, previously the permissions completely depended on the umask of the user running the command, since we weren't explicitly chmod'ing the files.  So for some users the permissions have changed, for others with a restrictive 077 umask, they are exactly the same.

**Comment by chefsalim** [comment]
At least for public harts, there is absolutely no security, and our download links are wide open. Given 99% of the artifacts we are going to encounter are public harts, a policy to root lock down those artifacts is zero value.  The main issue is private harts / pkgs.

I'm in favor to change packages back to 0644.  Then we can create a new issue to discuss whether private packages should be fully locked down.  If there is a scenario where someone is asking for this file system level lockdown for private packages, it would be good to get those requirements (and others).  In the meantime, it's just an un-intentional side effect that is more likely to distract and break things than fix an actual threat.

**Comment by stevendanna** [comment]
If we were to change them back, would we want them to still have the umask applied?

**Comment by chefsalim** [comment]
That may be better and closer to the original behavior, and also provide for a lockdown path - then a user who really wanted lock down could change their umask to 077 or something.  I don't know what else havoc that would do though as I don't think we've tested all those cases.

**Comment by stevendanna** [comment]
@chefsalim We run with 077 in CI and basically nothing works without temporarily resetting the umask so that is maybe also indication of what most of our users are running.

**Comment by stevendanna** [comment]
On the windows side I'm less sure what the expected behavior will be.  We can translate the unix permissions into a set of user acls using GENERIC_READ, GENERIC_WRITE, and GENERIC_EXECUTE masks and the "CreatorOwner" and "Everyone" SIDs (maybe just ignoring "group" bits) (https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems).

It's a bit of a shame because the tempfile API doesn't allow us to set any of the open options so we'll have to manually call set_permissions and handle the umasking ourselves.

If anyone has advice on the unix side I can probably at least get the feature into the atomic writer and then we can decide where to use it.

**Comment by dmccown** [comment]
For a user or a customer we changed the behavior here and didn't mention it in our release notes as well. I would like to see them changed back. I'm OK with applying the umask as long as we can test to ensure their aren't any surprising side effects (both Linux and Windows).

@chefsalim Can you create a new issue to open up a discussion on how we should handle permissions on private packages?

**Comment by chefsalim** [comment]
Opened new issue https://github.com/habitat-sh/habitat/issues/6302  @dmccown

**Comment by mwrock** [comment]
Just to weigh in on the windows implications here. I don't think these recent changes impact Windows at all. The attributes like GENERIC_READ, GENERIC_WRITE, etc. seen in the stdlib and tempfile code apply to how the file should be opened and not the ACLs that govern which users and groups can read and write to the file over its lifetime. Both `file::create` and `tempfile::create` on windows do not explicitly declare any ACLs beyond the ACLs inherited from the directory.

There are a few spots where we do alter these ACLs in the [`win_perm`](https://github.com/habitat-sh/core/blob/master/components/core/src/util/win_perm.rs) module (the sibling to `posix_perm`) where we leverage the [`windows_acl`](https://crates.io/crates/windows-acl) crate to access the underlying windows APIs. Generally our handling of file privileges is quite simple. Either we (1) do nothing which typically means any authenticated user has read/write access unless a user has altered the directory ACLs or we (2) alter the ACLs to only give a SYSTEM or Admin user access.

**Comment by stevendanna** [comment]
> Both file::create and tempfile::create on windows do not explicitly declare any ACLs beyond the ACLs inherited from the directory.

So from this it seems like the default situation probably has *not* changed on windows, and perhaps for now we could just set the mode on unix only to get back the original behaviour.

**Comment by stevendanna** [comment]
I've added a feature over here where we could change the permission on the files we write with atomic writer.  We might consider using it for this as well if this is something we still think we should fix: https://github.com/habitat-sh/habitat/pull/7489
