### ISSUE TITLE
Handle LF/CRLF errors sooners

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6299]
## Description
We should handle LF/CRLF issues up front before any build or run commands start. If we detect issues we should abort the build or run with an error about having mixed LF/CRLF issues. 

We could have an article in our documentation that describes why you may be having this issue and how to configure Git and your editor to avoid the warning in the future. 

Alternative idea: prompt the user to automically fix the line endings and correct it for them.

**Comment by christophermaier** [comment]
Hrmm... wonder if there was a regression somewhere? 

https://github.com/habitat-sh/habitat/pull/5648

Or are there line endings elsewhere that aren't covered by that fix?

**Comment by mwrock** [comment]
It would be helpful if we had concrete scenarios where `CR`s break things. I know I have bumped up against this in the past but cant recall the exact circumstances. Is it a build issue, a runtime/supervisor issue? both/neither?
