### ISSUE TITLE
Build macOS hab packages in Verify pipeline

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6308]
During the 0.78.0 release, we ran into an unexpected failure when building `hab` for macOS; namely, it could not build due to recent changes to our stripping behavior.

- [initial change of stripping behavior](https://github.com/habitat-sh/habitat/pull/6275)
- [note of failure during 0.78.0 release](https://github.com/habitat-sh/habitat/issues/6284#issuecomment-472009202)
- [fix for 0.78.0 release](https://github.com/habitat-sh/habitat/pull/6289)

This was unexpected, because the `hab` binary on macOS is the only package we _don't_ currently build in our verify pipeline. If that had been in place, this would have been detected before #6275 merged.

Our current macOS infrastructure may not be sufficient to build on every PR push, though, as it is limited and uses long-lived VMs. We will probably need to increase capacity before implementing this to maintain overall pipeline throughput.

**Comment by scotthain** [comment]
Once we migrate the mac builds to the new ephemeral pipeline (which we haven't built yet) we can address this.
