### ISSUE TITLE
Release 0.79.0

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#6357]
- [x] Determine if you need a new Launcher release, based on changes since the last release. The pipeline will ask you if it needs to build a new one.
- [x] Declare merge freeze and update slack status
- [x] [Create PR](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#prepare-master-branch-for-release) to update [`VERSION`](https://github.com/habitat-sh/habitat/blob/master/VERSION): https://github.com/habitat-sh/habitat/issues/6392
- [x] Fix up any miscategorization in [CHANGELOG.md](https://github.com/habitat-sh/habitat/blob/master/CHANGELOG.md) and add to PR updating [`VERSION`](https://github.com/habitat-sh/habitat/blob/master/VERSION)
- [x] [Merge PR](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#prepare-master-branch-for-release) to update [`VERSION`](https://github.com/habitat-sh/habitat/blob/master/VERSION)
- [x] Tag the repo when the above PR merges and push. This is the trigger for the Buildkite release pipeline.
- [x] [Create blog announcement PR](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#submit-a-release-notes-blog-post-pr) and solicit team member input: https://github.com/habitat-sh/habitat/pull/6359
- [x] [Buildkite](https://buildkite.com/chef/habitat-sh-habitat-master-release) run success
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [darwin binaries](https://bintray.com/habitat/stable/hab-x86_64-darwin)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [linux binaries](https://bintray.com/habitat/stable/hab-x86_64-linux)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [linux-kernel2 binaries](https://bintray.com/habitat/stable/hab-x86_64-linux-kernel2)
- [x] [Validate](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#validate-the-release) [windows binaries](https://bintray.com/habitat/stable/hab-x86_64-windows)
- [x] Confirm validation in Buildkite to complete promotion
- [x] Declare merge thaw and update slack status
- [x] ~Merge blog announcement PR. Upon publication, this will also automatically trigger a tweet from `@habitatsh`~ Skipping pending blog changes
- [x] [Update builder bootstrap bundle](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-builder-bootstrap-bundle)
- [x] [Update chocolately package](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#rerun-chocolatey-validation-tests)
- [x] [Publish release](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#publish-release) on GitHub
- [x] [Update `hab-backline` to release version in acceptance environment](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-acceptance-environment-with-the-new-hab-backline)
- [x] [Update docs](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-docs) https://github.com/habitat-sh/habitat/pull/6393
- [x] [Update CHANGELOG.md](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-changelog)
- [x] [Bump version](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#bump-version) to new `-dev` version
- [x] [Update `hab-backline` to new `-dev` version in acceptance environment](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-the-acceptance-environment-with-the-new-hab-backline-1)
- [x] ~[Promote Linux builder worker](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#promote-the-builder-worker) and confirm build uses new version~ (Skipping for this release due to bug; will use old workers until next release)
- [x] ~[Promote Windows builder worker](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#promote-the-builder-worker) and confirm build uses new version~
- [x] Post announcement in [Chef discourse](https://discourse.chef.io/c/habitat) https://discourse.chef.io/t/habitat-0-79-0-released/14915
- [x] Post announcement in [Habitat forums](https://forums.habitat.sh/c/announcements) https://forums.habitat.sh/t/habitat-0-78-0-released/1047
- [x] [Update `Cargo.lock`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-cargolock) for [`core`](https://github.com/habitat-sh/core) https://github.com/habitat-sh/core/pull/146
- [x] [Update `Cargo.lock`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-cargolock) for [`habitat`](https://github.com/habitat-sh/habitat) https://github.com/habitat-sh/habitat/pull/6394
- [x] [Update `Cargo.lock`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-cargolock) for [`builder`](https://github.com/habitat-sh/builder) https://github.com/habitat-sh/builder/pull/1015
- [x] [Update `rustfmt`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-rustfmt) for [`habitat`](https://github.com/habitat-sh/habitat) https://github.com/habitat-sh/habitat/pull/6395
- [x] [Update `rustfmt`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-rustfmt) for [`core`](https://github.com/habitat-sh/core) https://github.com/habitat-sh/core/pull/147
- [x] [Update `rustfmt`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#update-rustfmt) for [`builder`](https://github.com/habitat-sh/builder) https://github.com/habitat-sh/builder/pull/1016
- [ ] Review release automation and/or [`RELEASE.md`](https://github.com/habitat-sh/habitat/blob/master/RELEASE.md) and add necessary fixes https://github.com/habitat-sh/habitat/pull/6398
  - [x] Add some documentation to for "Ensure that Builder is stable on the new release"
  - [x] Note that `terraform/scripts/create_bootstrap_bundle.sh` needs `sudo` if run outside studio
  - [x] change `brew update hab` to `brew upgrade hab`
  - [x] Add [issue for generated docs](https://github.com/habitat-sh/habitat/issues/5948) related to https://github.com/habitat-sh/habitat/pull/6393/commits/ace4e3e497466f917280f0b6961595d8818e31b9 to release docs
  - [x] make clear which docs files are generated https://github.com/habitat-sh/habitat/pull/6399
  - [x] change "Update hab-backline to release version in acceptance environment" to "verify"
  - [x] ~Make note about blog posts still being published by travis (see https://travis-ci.org/habitat-sh/habitat/builds/518011787?utm_source=github_status&utm_medium=notification)~
  - [x] remove blog posting instructions per https://github.com/habitat-sh/habitat/pull/6225
  - [x] More details in "Update the Acceptance environment with the new hab-backline"
  - [x] Add promote worked confirm build uses new version for linux2 to checklist

**Comment by baumanj** [comment]
Found a bug due to https://buildkite.com/chef/habitat-sh-habitat-master-release/builds/3292#6700f42f-3002-4361-814c-91e822a4a560. Fix is in https://github.com/habitat-sh/habitat/pull/6363

**Comment by dmccown** [comment]
We are canceling this release due to a bug we ran into: https://github.com/habitat-sh/builder/issues/940

We will create a new release card when our pipeline is fixed.

**Comment by baumanj** [comment]
Restarting the release process now that https://github.com/habitat-sh/habitat/pull/6368 has merged

**Comment by baumanj** [comment]
Aborted again due to issues with the fixes for the previous abort

**Comment by baumanj** [comment]
TODO: Add some documentation to `https://github.com/habitat-sh/habitat/blob/master/RELEASE.md` (and the checklist) for "Ensure that Builder is stable on the new release"
