### ISSUE TITLE
Possible Release Improvement: re-release off prior tag

### ISSUE THREAD

**Issue by scotthain** [habitat-sh/habitat#6361]
What would the risks/benefits be for releasing a new version of the previous tag, in the event that a full release escapes and is non-salvageable. This would be instead of yanking a release, which can cause a lot of downstream sadness.

Let's discuss the following:
- how would this work
- what are the benefits to downstream consumers
- what are the risks for downstream consumers
- under what circumstances (if any) would we do this.

The sequence of events would essentially be as follows:
- Release 1.1.8 (arbitrarily chosen number) goes out with defect
- After defect is identified, we decide to do this process rather than yanking *or* waiting til next release.
- We identify Release 1.1.7 as the last good tested release
- We release 1.1.9 from the 1.1.7 tag (somehow technically? a branch maybe?)
- Set master to 1.1.10 and move forward

The theory here would be we could release 1.1.9 (which is 1.1.17) and bypass some/much of the verification testing since functionally the code is the same and should be tested already.

**Comment by christophermaier** [comment]
Added #6575 for documenting how to yank a release. It's obviously preferable to _not_ have to do that, though 😄
