### ISSUE TITLE
Handling potential breaking changes with services when upgrading the supervisor

### ISSUE THREAD

**Issue by mpeck** [habitat-sh/habitat#6369]
Conversation around https://github.com/habitat-sh/habitat/pull/6360 and https://github.com/habitat-sh/habitat/issues/6323 have brought to light some potential issues that could arise when upgrading the supervisor.

Basically the issue revolves around some code not executing until the service that the supervisor is running is restarted. Since upgrading the supervisor does not involve a restart of its services this could lead to users breaking their installation and not realizing it for multiple releases; this could potentially make debugging things very difficult. It also makes it difficult for us to deprecate or modify some features.

How could we solve for such instances? Is there a general mechanism that we could employ to help alleviate some of these potential issues; on-the-fly config update, requiring major updates to be a more manual process, etc?

**Comment by baumanj** [comment]
One thing I think we should do for these scenarios is have a sort of check that we can run to at least give some initial validation that the already-running services would be ok running under the upgraded supervisor. I imagine a flow like:
1. Supervisor version X.Y.Z is running with service S and auto-update enabled
1. Supervisor detects availability of version X.Y.(Z+1)
1. Package for supervisor X.Y.(Z+1) is downloaded (but not installed)
1. `hab sup check` is executed on with supervisor X.Y.(Z+1) and service S as arguments and checks that there are no errors before completing the install and restarting
1. If there are errors, supervisor X.Y.Z remains running with service S
1. If there are no errors, after restart X.Y.(Z+1) is running with service S

This would require some changes to allow a package to be downloaded and have commands executed without actually installing it. Also, we can't guarantee `hab sup check` would be perfect, but we can explicitly use it for deprecating functionality in a more controlled manner.

The other thing I think we should look at is making auto-update behavior different according to the version number. Assuming we do things according to [semantic versioning](https://semver.org), any upgrade where only the PATCH version changes should be as safe as possible and we should probably always allow them. MINOR version should also be safe and shouldn't ever remove functionality, but MAJOR version changes should either have all the breaking parts verifiable in something like `hab sup check`, or we should not allow auto updates across major version changes.

Another option would be to make the auto update behavior user configurable. Semantic versioning has a whole scheme we could rely on for letting users opt-in to the kind of auto updates they want.

**Comment by raskchanky** [comment]
> Another option would be to make the auto update behavior user configurable. Semantic versioning has a whole scheme we could rely on for letting users opt-in to the kind of auto updates they want.

I think this is a terrific idea.  Different users will have different risk tolerances and we shouldn't presume that what works for us will work for everyone.  The level of effort involved to make this happen is also quite small when compared to the rest of the work anyway.
