### ISSUE TITLE
Binlink command should provide an option for generating stub instead

### ISSUE THREAD

**Issue by HT154** [habitat-sh/habitat#6383]
I'm packaging a CLI tool that only works when `LD_LIBRARY_PATH` is set (python loading a native module). I can set this up in my plan.sh with `push_runtime_env`, but this is only effective if I run my CLI via `hab pkg exec`. If I binlink the executable, the env var isn't set and nothing works.

`hab pkg binlink` should provide a flag (`--stub` or `--binstub` maybe?) that changes the behavior to generate a binstub like this instead of symlinking:

```
#!/bin/sh

hab pkg exec <IDENT> <EXECUTABLE> $@
```

**Comment by HT154** [comment]
Actually, this isn't an issue in the case that prompted me to write this up. The env var only needs to be set at build time in this case.

It would still be nice to have this!

**Comment by dmccown** [comment]
@smacfarlane Can you check if there's an issue open for this already?

**Comment by smacfarlane** [comment]
@HT154   This looks like a duplicate of #4493.  Would you mind adding your use-case to that issue and we can close this one out.

**Comment by HT154** [comment]
The other issue pretty much covers it. I'll close this out.
