### ISSUE TITLE
Add api-ms-win-core-job-12-1-0.dll to powershell core

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6385]
On Windows 7, using `Start-Process` with the `-Wait` arg will error if this DLL is not included. This is ultimately a PS bug (see https://github.com/PowerShell/PowerShell/issues/6561) but we can easily either patch it in our plan or add a runtime dep.

**Comment by gscho** [comment]
@mwrock Is there a habitat package for this that we can use as a runtime dep?

**Comment by mwrock** [comment]
Not yet. I did some initial investigation and it was not clear where I could download that file from (preferably some official download link). Need to research further unless anyone else might know.

**Comment by gscho** [comment]
Looks like this can be worked around by doing this:

```
try {
    $p = Start-Process my-process -WindowStyle Hidden -PassThru # do not add -Wait arg
    $p.WaitForExit()
  } finally {
    if(!$p.HasExited) { $p.Kill() }
  }
```

In my case it was the use of -Wait on the start process command.

**Comment by mwrock** [comment]
Yeah. Thats a great strategy. I think I am going to close this issue since this is really a powershell issue and not habitat specific. I am hesitant to put an API DLL in its bin that it does not add itself. The above seems like a solid workaround.
