### ISSUE TITLE
Migrate bintray hosting to Depot

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6388]
Now that we have the ability to host MacOS packages on Depot, we should migrate over the hosting on release packages to Depot. In addition, the curl | bash script should be updated to get packages from the Depot.

**Comment by smacfarlane** [comment]
Closed by #7312

Release tar/zips are now hosted on packages.chef.io to align with other projects at Chef.  Builder hosts the .hart files that can be used once a system is bootstrapped.
