### ISSUE TITLE
TTY detection would make docker studios a lot nicer

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#6403]
Right now, docker studios are assumed to be interactive and require a tty by default.  If you're running builds on a headless system, you need to explicitly pass `--no-tty --non-interactive` in order to disable that behavior.

Once upon a time, studios were always interactive.  Then we disabled that to provide a better experience on headless systems.  Then that broke macOS, so https://github.com/habitat-sh/habitat/pull/6295 was introduced, and we've come full circle.

What would be _even better_ though, is if we could automatically detect if a tty is present or not, and based on that, set the appropriate command line options in Docker.  Then it would Just Work™ for everyone, without a lot of mucking about.

https://github.com/softprops/atty is one possible solution.

**Comment by mwrock** [comment]
yeah I know cargo uses `atty` . See https://github.com/rust-lang/cargo/blob/5c6aa46e6f28661270979696e7b4c2f0dff8628f/src/cargo/core/shell.rs

**Comment by raskchanky** [comment]
As part of this work, the flags added in https://github.com/habitat-sh/builder/pull/1018 can be removed

**Comment by baumanj** [comment]
This will need to be coordinated with https://github.com/habitat-sh/habitat/pull/6347. Hopefully this lands first and 6347 can be a bit simpler.
