### ISSUE TITLE
Nodes sometimes are not auto updating

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6405]
For investigation -

Even though builder acceptance services are set up to auto update the supervisor, hab sup does not appear to be self updating consistently.  Various nodes are running different versions of hab sup.  Need to understand why this is happening..

**Comment by chefsalim** [comment]
We've seen this on both acceptance and prod, and this is a significant stability issue and we should prioritize fixing it ASAP

**Comment by krasnow** [comment]
This was fixed with this PR: https://github.com/habitat-sh/habitat/pull/6717. Closing the issue.
