### ISSUE TITLE
`hab pkg install --binlink` does not use `HAB_BINLINK_DIR` environment variable

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6418]
It seems like a recent change in 0.79.0 (maybe) has introduced a bug where binlinked binaries are not on the path in a local linux studio. Note that docker studios and windows studios are not affected. Also this is only affected by `hab pkg install --binlink` and not `hab pkg binlink`. studio.

`hab pkg install --binlink` links to `/bin` and not `HAB_PKG_BINLINK`

**Comment by baumanj** [comment]
The change that's causing the issue seems to be https://github.com/habitat-sh/habitat/pull/6315/commits/6232c6728f29f825b4324b81ff7c77b7eec95d79. Specifically the handling of the `-b|--binlink` argument to `hab pkg install`; `hab pkg binlink` itself seems to still work correctly.
