### ISSUE TITLE
Pipewire

### ISSUE THREAD

**Issue by ShalokShalom** [habitat-sh/habitat#6431]
Pipewire is the future on the Linux desktop and probably also for a couple of server applications:

Pulseaudio, JACK and the video handling get all replaced by it, plus it offers remote access and Flatpak integration. So I suggest to provide a way for Habitat to interact with it as well. 

Website: https://pipewire.org/
News: https://www.phoronix.com/scan.php?page=news_item&px=PipeWire-2019-Looking-Good
API: https://pipewire.github.io/pipewire/

**Comment by chefsalim** [comment]
This doesn't appear to be something we will be integrating with.

**Comment by raskchanky** [comment]
@ShalokShalom If Pipewire is something you'd like to use with Habitat, feel free to write a plan for it and submit a PR to the [core-plans repo](https://github.com/habitat-sh/core-plans).  Habitat as a product is not focused on audio or video, and those plans are unlikely to change any time soon.  As such, integration with Pipewire is not a priority.
