### ISSUE TITLE
Plan names should support common application naming conventions for .NET eg. Namespace.Package.Web

### ISSUE THREAD

**Issue by trevorghess** [habitat-sh/habitat#6434]
Currently plan names can't have "." in them

A common convention in .net is to namespace with "." which is included as part of the apps name in areas like IIS for example MovieApp.Web.API

So I'd want to set the package name to "MovieApp.Web.API" so that it can be consistent with the rest of the app naming convention.

**Comment by chefsalim** [comment]
This seems reasonable - as long as there is no technical limitation to including the dots in the plan name

**Comment by baumanj** [comment]
Seems like this should be fine based on how [`PackageIdent` implements `from_str`])(https://github.com/habitat-sh/core/blob/master/components/core/src/package/ident.rs#L212-L225).

**Comment by mwrock** [comment]
See #6569, Closing for now based on team discussion. The value gained here just is not nearly as high as the risk introduced and there are easy workarounds to mitigate the lack of support for dots in names.
