### ISSUE TITLE
Make the docs searchable

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#6441]
A Habitat docs search should return relevant content. The structure of the docs and the installed search engine work together to confound searchability. Who among us has not `ctr+f`'d our way to usable information?

Steps:

- [x] Break up large pages
- [ ] Write frontmatter descriptions to improve SEO
- [ ] Correct Markdown
- [ ] Check/fix internal docs links
- [ ] Check/fix site links
- [ ] Check/fix the HTML links on the nav bar

NOTE: This does not contain any content editing

**Comment by stidhamlisa** [comment]
Pending UI help (expected in February)
