### ISSUE TITLE
Windows signal handling incomplete and misleading

### ISSUE THREAD

**Issue by baumanj** [habitat-sh/habitat#6461]
Currently [the Windows signal handling](https://github.com/habitat-sh/core/blob/master/components/core/src/os/signals/windows.rs) relies on [the ctrlc crate](https://crates.io/crates/ctrlc). This means that only `CTRL_C_EVENT` or `CTRL_BREAK_EVENT` are supported and [SIGHUP-triggered supervisor restarts](https://github.com/habitat-sh/habitat/pull/5445) (for controlled upgrade) do not work.

In addition to implementing this code for Windows, it would be good to modify the API here to avoid the misleading situation where a specific platform is incapable of handling the signal it appears to in the code. For example, there's nothing about [this line](https://github.com/habitat-sh/habitat/blob/master/components/sup/src/manager/mod.rs#L699):
```rust
            if let Some(SignalEvent::Passthrough(Signal::HUP)) = signals::check_for_signal() {
```
which indicates it would not work on Windows. Changing to something like `signals::check_for_sighup()` would allow for errors like this to be caught at compile time.

**Comment by mwrock** [comment]
I think this can be closed by #6332 which made it much more explicit and unmagical what was happening on which platform. That takes care of "misleading" and as for "incomplete" sadly the Windows semantics are so different that we will never have one to one mappings for the various posix signals. However, what we have now is likely sufficient.

Please reopen @baumanj if you feel more should be done.
