### ISSUE TITLE
Plan must specify pkg_version even if scaffolding provides it

### ISSUE THREAD

**Issue by HT154** [habitat-sh/habitat#6463]
I'm trying to write my own scaffolding for Python CLI tools. I'm having issues supplying `pkg_version` without also specifying it in consuming plans.

In scaffolding.sh:
```bash
pkg_version() {
  python "${PLAN_CONTEXT}/../setup.py" --version
}
do_default_before() {
  update_pkg_version
}
```

In plan.sh:
```bash
pkg_name=...
pkg_origin=...
pkg_scaffolding=.../scaffolding-python-cli
```

Produces error:
```bash
ERROR: Failed to build. 'pkg_version' must be set or 'pkg_version()' function must be implemented and then invoking by calling 'update_pkg_version()'.
```

If I add this to plan.sh, it works as expected and the scaffolding populates the version:
```bash
pkg_version=_version_from_scaffolding_
```

I suspect that [this check](https://github.com/habitat-sh/habitat/blob/e1c54e18dcbe5e7e23eed5a1138f8ea7d874e817/components/plan-build/bin/hab-plan-build.sh#L2509) is being called too early. It should run after the scaffolding is loaded.

**Comment by robbkidd** [comment]
> If I add this to plan.sh, it works as expected:
> 
> ```
> pkg_version=x
> ```

What is the result? A package with the literal version of `x`? Or does your custom scaffolding's `pkg_version` computation succeed in setting a real version number based on the thing being scaffolded?

Many moons agos, prior to supporting `pkg_version` as a function, the idiom in Habitat was for a plan that intended to compute its version to declare that in its metadata. So if setting `pkg_version` to _something_ gets your scaffolding's version computation to take effect, past practice might have you declare this in your plans:

```
pkg_version=_computed_by_the_scaffolding_
```

There's a part of me that likes the clarity this might give future readers of the plan asking "where the heck did that version number come from?" What do you think?

**Comment by robbkidd** [comment]
Additionally, I think you are correct about the timing. The plan build checks for `pkg_version` to have been set to either a string or be a function prior to loading a scaffolding for the scaffolded behavior to have any effect.

**Comment by HT154** [comment]
When `pkg_version=x` the scaffolding logic succeeds and sets the version correctly.

x was just a placeholder. I’m shipping plans with a more explanatory message like you mentioned and agree that it makes it much clearer. I still think that this behavior in the plan build is incorrect the error is misleading.

**Comment by robbkidd** [comment]
@HT154 I totally agree there is _something_ to fix here! It's good to know there's a workaround. The question may be now whether to update the error message for this case or to change the "`pkg_version` is set to something" validation to some time after a scaffolding has been loaded.

**Comment by muralivishnu** [comment]
i am also facing same issue. Is there any issue with pkg_version() in habitat 0.74.0 version.  The following code we used for pkg_version update, it working fine in 0.57.0 but it is not working in 0.74.0. if we use pkg_version=x , its working in 0.74.0
```
pkg_version() {
  cat "$PLAN_CONTEXT/../VERSION"
}
 
do_before() {
  do_default_before
  update_pkg_version
}
```
The following is pre_build.env
```
pkg_origin=xx
pkg_name=yy
pkg_version=__pkg__version__unset__
pkg_release=20190424170059
pkg_ident=xx/yy/__pkg__version__unset__/20190424170059
```

**Comment by HT154** [comment]
This still needs addressing
