### ISSUE TITLE
Allow multiple scaffolding or something like hab-plan-build plugin

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#6477]
When packaging software we often see some basic patterns which can be extracted and re-used. In context of project it is good to use `.studiorc` or something like `base-plan.sh` with all stuff defined.

When I want to share number of helpers across the projects or community I can create a scaffolding package which enhances habitat experience. However I can specify only one scaffolding. I'm sure that scaffolding must be only one and this ok.

It would be really useful if I can specify plugin-packages which extend my `hab-plan-build`.
For example, Debian has set of build helpers to make packages directly from git repositories.

I see good potential of this feature and easy implementation.

I create package with `plugin/main.sh` (or `lib/plugin.sh`, or something like that. need to think about naming).
That script adds set of methods typical for an use-case.

Example:
```bash
: "${pkg_git_branch:=master}"
# I implement git-source plugin
# in file lib/plugin.sh
pkg_version() {
  pkg_git_version()
}

pkg_git_version() {
    git rev-list master --count
}

do_download() {
  do_git_download
}

do_git_download() {
    if [ -d "$CACHE_PATH/.git" ]; then
        build_line "Git repository exists. Attempt to reuse"
        pushd "$CACHE_PATH" > /dev/null
        # shellcheck disable=SC2154
        git remote set-url origin "$pkg_source"
        git fetch --depth 1 origin "$pkg_git_branch"
        popd > /dev/null
    else

        build_line "Git download! Doing shallow clone from $pkg_source to $CACHE_PATH"
        git clone --depth 1 --no-checkout --branch "$pkg_git_branch" "$pkg_source" "$CACHE_PATH"
    fi
}

do_verify() {
  do_git_verify
}

do_git_verify() {
    build_line "Skipping checksum verification on the repository we just created."
    return 0
}

go_clean() {
  do_git_clean
}

do_git_clean() {
    build_line "Clean up repository using git"
    pushd "$CACHE_PATH" > /dev/null
    git reset --hard HEAD
    git clean -fdx
    popd > /dev/null
}

do_unpack() {
  do_git_unpack
}

do_git_unpack() {
    build_line "Force checkout $pkg_git_branch"
    pushd "$CACHE_PATH" > /dev/null
    git checkout -f "origin/$pkg_git_branch"
    popd > /dev/null
}
```

Now, in my package I can use scaffolding and multiple plugins like following:
```bash
# in plan.sh

pkg_name=my_package
pkg_scaffolding=core/scaffolding-go

# Source them during plan load in order listed
pkg_build_plugins=(
  jsirex/plan-plugin-git-source
  jsirex/plan-plugin-any-another-plugin
)
...
pkg_source="github.com:jsirex/project-sources.git"
pkg_branch="v1.65.6" # tag also allowed, but not commit id
...

do_build() {
  build_line "Now I'm in git repo which downloaded similar to artifact via pkg_source"
  build_line "Feeling like git source now native for habitat build process"
}
...
```

This feature also replaces scaffolding feature because of same behavior.

**Comment by jsirex** [comment]
UPD: Another use-case is `bixu/cacher`. His methods can be extracted to functions and loaded into plan as they needed.

**Comment by bdangit** [comment]
This would be nice to have!  I hate having to source a `common-plan.sh` across the many packages we build. Even after scaffolding, we still need a couple helpers.  Mainly we do versioning a certain way and we do that for any package.

**Comment by jsirex** [comment]
Just copy-paste from forum few examples of implementation of tsuch plugins (compatible with habitat):
https://github.com/biome-sh/bio-plugin-secret - manages your secrets in .secrets/ automatically
https://github.com/biome-sh/bio-plugin-wrapper - automatically wraps an upstream package, uses packages hooks, configs, exports, binding, etc unless defined in a wrapper
https://github.com/biome-sh/bio-plugin-git-source - allows use git url in pkg_source
https://github.com/biome-sh/bio-plugin-git - if project itself under git plugin helps to keep files clean by copying all files to CACHE_DIR before build. For example, no more maven target directories in source root.

It will nice if I will be able to specify plugins in my plan without explicit sourcing them like:
```
...
pkg_plugins=(biome/bio-plugin-secret biome/bio-plugin-wrapper)
...
```
