### ISSUE TITLE
put binaries in the root of the windows release zip

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6480]
We currently place all of our binaries in a folder called something like `hab-0.79.1-20190410221450-x86_64-windows`. This makes our installation instructions more convoluted than they need to be and asks users to add that folder to their path. This folder would of course change any time habitat is updated making updating more awkward and requiring a path change.

**Comment by kagarmoe** [comment]
A related problem is the UX for installing the hab binaries. There's no success/failure message for the installation. I wasn't even sure the installation succeeded or what the next step was. We should consider putting the binary into a windows MSI installer, having it load the files in the right manner & location, automatically adding/updating the path, and providing an installation success/failure message.

**Comment by mwrock** [comment]
I'd like to avoid an MSI install if we can. Doesn't what we have now mimic what we have on the mac?

**Comment by mwrock** [comment]
I'm closing this for now since the `install.ps1` scripts the logistics of unpacking the zip.
