### ISSUE TITLE
Add an uninstall hook

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6481]
Now that we have `install` hooks for performing one-time machine wide installation tasks AND an `uninstall` command. It makes sense to have an `uninstall` hook that would be invoked at uninstall time to uninstall any machine state that was installed in the `install` hook. Foe example, `core/sqlserver` would uninstall its sql server instance from the OS.

**Comment by mwrock** [comment]
There is an interestingly problematic use case here. Here are some notes on the case and a proposed solution. Would love feedback.

### What is the uninstall hook
The primary goal of the uninstall hook will be to uninstall software installed via the install hook. This is super useful because typically an install hook is used to install software that impacts the global state of the system - things that lie outside of the /hab directory tree. SQL Server is a good example. Installing SQL Server is a multi-minute process that interacts with the registry, windows services, and the "Program Files" folder. Currently if one wants to completely remove a Habitat installation of SQL Server, they must not only uninstall the habitat /hab/pkgs folder for their SQL Server package but they must invoke the SQL Server uninstaller. Ideally an uninstall hook would include this final step. Given an uninstall hook, when hab pkg uninstall is run, the uninstall hook would be run similar to how we run the install hook on hab pkg install.

### Where things can get complicated
Consider this scenario. A user installs SQL Server via Habitat. A user updates their SQL Server package with a new package that includes the latest SQL Server Cumulative Update patch. This new package would perform a full SQL Server install only if no SQL Server instance is installed, then it will patch that installation. Next, someone (or the supervisor during a cleanup) uninstalls the older SQL Server package. This uninstall runs the SQL Server uninstaller and BOOM - no more SQL Server is on the box and the updated and running SQL Server package is totally busted.

### What to do?
So how would be handle this case because wiping out SQL Server as part of a routine supervisor cleanup would be the wrong thing to do. First, like the --ignore-install-hook flag of hab pkg install, we need a --ignore-uninstall-hook for hab pkg uninstall. This at least allows users a way to not run the uninstaller when manually running the hab pkg uninstall command. With this, I would propose that when the supervisor is uninstalling old packages it always uses the --ignore-uninstall-hook behavior. Basically we should never automatically run a script that can uninstall global state without some kind of willful act from a user.

**Comment by davidMcneil** [comment]
> Basically we should never automatically run a script that can uninstall global state without some kind of willful act from a user.

If there is only one version of the package installed when the uninstall is taking place would it be ok to run the uninstall hook? I think it would be.

 The `--keep-latest` flag adds some nuance. If the user sets `--keep-latest` to `0` it would be safe to run the uninstall hook.

 Maybe the logic could be:
* If an uninstall operation would end with any versions of the package still installed a warning is emitted stating that the uninstall hook will not be run (if the package has an uninstall hook).
* If an uninstall operation would remove all versions of the package run the uninstall hook for each package version from oldest to newest
* If the `--ignore-uninstall-hook` is set no uninstall hooks are run

**Comment by mwrock** [comment]
Yes that logic looks right @davidMcneil. I was not thinking of dependency packages. I was thinking of the top level service package in which case the latest version would be running and we would never want to run the uninstall hook but for dependency packages it may very well be that we could end up uninstalling the last version on the system in which case running the hook would be safe.
