### ISSUE TITLE
'hab file upload' files don't get automatically propagated on new service instances

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6499]
I thought we had this logged already but can't find the issue so re-logging.

When a file is uploaded to the gossip ring via 'hab file upload', it is successfully sent to already running instances.  However, if a new service instance is started and joins the ring, the files are not propagated over, and have to be uploaded again in order to be seen by the new instance.

This is a stability issue on acceptance when starting new nodes.  

We've worked around it for some cases (eg, see https://github.com/habitat-sh/habitat/issues/4012) but would like to see this prioritized for a fix ASAP.

**Comment by baumanj** [comment]
> I thought we had this logged already but can't find the issue so re-logging.

Is https://github.com/habitat-sh/habitat/issues/4877 what you were thinking of?

**Comment by chefsalim** [comment]
Ah yes that's the one, thanks @baumanj

**Comment by chefsalim** [comment]
Closing as duplicate of https://github.com/habitat-sh/habitat/issues/4877
