### ISSUE TITLE
Design Proposal : Artifactory Depot enablement

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#6504]
This issue will serve as a Design Proposal for enabling the Habitat client side components to use an Artifactory instance in lieu of a Habitat Builder Depot.

# Background / Use Case
The use case is primarily for an on-prem rollout of Habitat, where there may already be an artifact store provisioned, and adding new server infrastructure may be difficult or a lengthy process. In these situations, being able to use already existing infrastructure makes the adoption of Habitat much more frictionless. 

The Artifactory-based 'depot' should handle the main usage scenarios - eg, package builds, uploads, supervisor updates, etc. At a later point in the Habitat on-prem adoption, a full fledged Builder Depot may be added / migrated to that would be able to provide additional functionality.

# Design Goals:
1. Simple configuration of the Habitat client to point to Artifactory 
2. Do not require installation of plug-ins or custom code on the Artifactory instance
3. Abstract out the changes into a single crate - the bulk of the Habitat client code should not require code changes or even be aware that the Depot functionality is provided by a different infra
4. Have a reasonable path for migration to Builder Depot at a later point
5. Don't put undue stress on the Artifactory instance (ie, performance should be reasonable)

# Design Non-Goals:
1. Provide 100% of the functionality of the Builder Depot with the Artifactory-only solution

# Detailed Design:

## Depot functionality used by the Supervisor and Studio

The primary need for the Supervisor and Studio is to be able to search for the latest packages in a given channel, download origin keys, and install new packages. For those needs, only a subset of the Depot API is needed:
* Getting the latest fully qualified version for a given origin/package in a specified channel
* Downloading a specific origin key (for package validation)
* Downloading the current private key (for package signing)
* Downloading a specific package (for installation)

Also - the promotion and demotion of packages, while not explicitly triggered by the Supervisor or Studio, is a central part of the Habitat workflow, and therefore is required to be supported.

## Artifactory API and functionality map

The Artifactory REST API is documented [here](
https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API)

The minimum capabilities we need are provided by the Artifactory Pro edition (eg, Properties, and AQL)

Mapping of Depot functionality to Artifactory capabilities is in the table below.

Depot | Artifactory
-- | --
User / account management | Since there is no Builder Depot, there will be no UI for account management, login, etc. We will rely on Artifactory user accounts to provide the auth (via a user API key).  More info on managing Artifactory users: https://www.jfrog.com/confluence/display/RTF/Managing+Users
Origins | Origins will map to an explicit trust relationship (permissions) for a given user to a repo. We will need a repo for each origin provisioned by the Artifactory admin, and appropriate permissions assigned. See https://www.jfrog.com/confluence/display/RTF/Managing+Permissions
Origin Keys | Origin keys (both public and private) will be stored as artifacts in a folder within the origin's repo.
Packages | Packages will be stored as artifacts in a folder hierarchy that is optimized for search queries. Package visibility will be public only - if a package should not be visible for a user, that users permission will need to be revoked to the repo by the Artifactory admin.
Channels | Channels will be stored as a property on the packge artifact. AQL search can be used to get the “latest package in a given channel”. It is easy to get the list of channels for a given package. Promotion and demotion operations will be two phased - get the list of channels, add / remove the desired channel, then set the property on the artifact.
Builder CI related functionality | Build functionality will not be directly available. A reverse-dependency API may be added at a later time.

## Habitat Client changes

The Habitat client components (eg, habitat cli, launcher, supervisor) will be enabled to talk to the Artifactory API instead of the Builder API.

This will be done with the addition of a new Artifactory provider within the builder-api-client crate, which will support the same interface as the one used by the hab components currently. Therefore, it will be an almost transparent switch over to the users of the builder-api-client crate. Of course, functionality that Artifactory does not support will not be available. 

The builder-api-client crate will be configured to talk to Artifactory with the addition of a new environment variable, eg, HAB_BLDR_PROVIDER=artifactory

The existing HAB_BLDR_URL and HAB_AUTH_TOKEN environment variables and parameters will continue to be leveraged to provide the URL and API Key token to the Artifactory store.

We may also modify the ‘hab setup’ flow to allow users to select Artifactory as the Builder API provider and save that preference in their cli.toml.

## Repository Layout and Properties

Due to the way Artifactory permissions are targeted, each origin will be in a distinct repo.

The repo naming will be optionally configurable via a HAB_ARTIFACTORY_REPO_NAME environment variable, and will default to “habitat-artifact-store-local”.  The origin will be appended after the name with a “.” separator.

The repositories will need to be pre-created and permissions assigned by the Artifactory admin prior to use by the Habitat client.

Since Artifactory does not support anonymous AQL queries, an auth token will be required for all operations.

The following are proposed paths for packages and keys:

*Packages:*
```
pkgs/[target]/[origin]/[package]/[version]/[origin]-[package]-[version]-[revision]-[target].[ext]
```

*Keys:*
```
keys/[origin]/[origin]-[revision].[ext]
```

Being able to directly view metadata such as the plan.sh or the contents of the hart repository is not a current requirement.

## Repository Search

The most common search is for the latest revision of a package that is in a given channel (eg, stable).

This search query can be done with an Artifactory AQL query - for example:

```
items.find(
{
  "$and":[
           {"repo":{"$eq":"habitat-artifact-store-local.core"}},
           {"path":{"$match":"x86_64-linux/testapp/*"},
           {"name":{"$match":"core-testapp-*"}},
           {"@channels":{"$eq":"stable"}},
         ]
}
```

## Performance and Scale

Performance testing will need to be done to ensure that the cost of the queries to Artifactory is reasonable. 

## Migration to full Builder Depot

Functionality such as being able to get reverse dependency graphs, or build ordering for packages will not be available via native Artifactory.

We may provide a migration path to a full fledged Builder Depot. Details of the migration are TBD.

**Comment by HT154** [comment]
This is extremely appealing for my org!

One addition that would make this a no-brainer for adoption would be some sort of configuration that would enable repos to be set up as remotes mirroring public builder or another on-prem one. Maybe the full builder could provide an API endpoint like https://bldr.habitat.sh/artifactory/origins/core that would serve redirects at the correct sub-paths for artifacts and keys. Artifactory has special capabilities when communicating with remote Artifactory servers, maybe this API could be emulated to allow synchronization of channel properties as well.

I'd like to eventually like to see some sort of hybrid configuration that keeps as much data in Artifactory as possible but provides the full suite of builder features (esp. builds)

**Comment by baumanj** [comment]
I'm wondering whether the addition of the `HAB_BLDR_PROVIDER` env var together with overloading the interpretations of `HAB_BLDR_URL` and `HAB_AUTH_TOKEN` opens us up to more potentially invalid states.

Since the set of these three variables are inherently tied together, why not make them a single value (with deprecated support for the legacy `HAB_BLDR_URL` and `HAB_AUTH_TOKEN`)? Something like:
```
HAB_DEPOT=provider:bldr,url:https://bldr.habitat.sh,auth:_BASE64DATAHERE=
```
or
```
HAB_DEPOT=provider:artifactory,url:http://some.artifactory.url,auth:WHATEVER_ARTIFACTORY_USES
```
We could support allowing whitespace after the commas to enhance readability. The only thing I can think of that we'd need to be careful of is if colons `:` or commas `,` are legal parts of the auth values for artifactory or some other provider we might want to support in the future.

**Comment by chefsalim** [comment]
@HT154 Absolutely.. this card doesn't include the design for core package sync, but we will definitely explore the possibility of enabling a remote mirror.

@baumanj The token consolidation is an interesting idea, and worth thinking about.  We might want to look at the cli args for token/url as well, and whether we either consolidate or include a param for the provider as well.  This will probably be a separate follow-on issue/PR, as for the initial effort I'd like to keep the code changes as contained as possible.

**Comment by larkinc** [comment]
On-prem-builder script should include a function to retrieve habitat packages and public keys for older versions of a package when necessary. (See on prem builder issue [#144](https://github.com/habitat-sh/on-prem-builder/issues/144).  There are 2 business reasons for this:
1.  The on prem builder populate process pulls a package that is dependent on an older transient package not included in the LATEST.tar.gz resulting in a failed upload to the on prem builder.
2.  The company using an on prem builder has a software project that is being converted to a habitat package that has a dependency that can not be timely updated on an older version a piece of software that has a habitat package but was not included in the LATEST.tar.gz.  (i.e. dependency on a specific version of jdk8 release that is not latest)

On prem builder storage should allow for a file list of packages and channels to be stored in the Artifactory storage that can be used to populate a new instance of the on prem builder application in the event of a application server failure.  This would allow a new application server to be stood up, pointed to the Artifactory storage, and have all stored packages/channels be immediately available.  Additionally, this may assist in some air-gapped environments where Artifactory is allowed to push replicate from one instance of Artifactory to an air-gapped instance of Artifactory with its own on prem builder in front for air-gapped servers to utilize.

**Comment by larkinc** [comment]
Habitat CLI delete function ``` hab pkg delete ``` should have a delete from Artifactory option.  Option would allow for the package to be deleted from Artifactory as well as the builder.  Assumption is this is an admin command as the auth token being used for Artifactory has to belong to a user with rights to delete.

**Comment by baumanj** [comment]
> We might want to look at the cli args for token/url as well, and whether we either consolidate or include a param for the provider as well.

Good point. I think `--url` makes sense as an override only if used for doing operations that don't require any auth token, so we could probably deprecate `--auth` and `--url` in favor of a `--depot` argument whose syntax mirrors the consolidated env var. Or (or possibly in addition), we could look at at adding a `--provider` argument that required `--url` to be specified as well.

It's worth pondering the best UX here and I'm not a UX expert, but I just wanted to raise the concern about how tightly coupled these three pieces of data are at a juncture we have the leeway to avoid the possibility of invalid combinations.

**Comment by chefsalim** [comment]
@larkinc Thanks for the feedback.. so for the main scenario, there would not be any 'on-prem builder' service - Artifactory would provide the needed services.  For an 'upgrade' case, where at some later point there was a need / desire for a full-fledged on-prem builder service, then yes it would make sense that we could just point that service to Artifactory and be good to go.  We're not quite there yet tho.

@kagarmoe Any thoughts on the cli UX options above?

**Comment by larkinc** [comment]
> @larkinc Thanks for the feedback.. so for the main scenario, there would not be any 'on-prem builder' service - Artifactory would provide the needed services. For an 'upgrade' case, where at some later point there was a need / desire for a full-fledged on-prem builder service, then yes it would make sense that we could just point that service to Artifactory and be good to go. We're not quite there yet tho.
>

@chefsalim I might have been a little unclear.  I'm not actually suggesting Artifactory in place of the on-prem-builder, but more that the configuration of the on-prem-builder including an understanding of the hart files and channels could be stored and sourced from Artifactory.  So a new application (this is where I introduced the confusion I think in my comment above) ... I should say a new on-prem-builder application is launched it could be pointed to an existing Artifactory backed hart repo, collect its information from Artifactory and be fully aware of all the hart files in Artifactory and their channels.

While allowing Artifactory to be the whole point of delivery would be nice.  I was thinking more about two scenarios:
1. Failed on-prem-builder server that required a new instance be stood up that needs to know what has already been built.
2. Air-gapped env, where Artifactory is allowed machine to machine replication to move artifacts would allow a new builder to be stood up in the Air-gapped area and collect its information from the artifact store.
