### ISSUE TITLE
Add options to `plan init` to force creating a powershell or bash template regardless of OS

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#6516]
By default `plan init` outputs a powershell template on windows and bash for any other OS. It would be nice if there was a way to override this behavior and output either template regardless of host OS. Possible UX for this are:

1. Mutually exclusive flags `--bash` vs `--powershell` or `--linux` vs `--windows` 
2. `--template` flag with potential values such as `linux`, `windows`, `bash`, `powershell`

**Comment by raskchanky** [comment]
I'd probably trend away from platform specific identifiers like `linux` and `windows`.  macOS support will come at some point in the future, which uses `bash`, like `linux`.

**Comment by davidMcneil** [comment]
Agreed. I think I lean towards the mutually exclusive flags `--bash` and `--powershell`.

**Comment by jmassardo** [comment]
I like the `--bash` and `--powershell` options as well. I have a fair number of folks that use Macs for their primary workstation even though they manage Windows fleets.

The option of specifying a template would be super awesome too.

**Comment by christophermaier** [comment]
I don't seem to have written this up anywhere yet, but for a while I've wanted to overhaul `hab plan init` to make it pluggable. While the idea isn't fully fleshed out yet, in theory, I'd like to be able to encapsulate the logic to create a plan in a habitat package, and then provide a way to specify which such package you'd like to use when you create a plan. Something like:

```sh
hab plan init --template=core/bash-plan
```
or
```sh
hab plan init --template=core/powershell-plan
```

It gets even better when you start thinking about how companies could define their own templates. For instance, if Company X has a specific way it likes to build, say, Tomcat services, you could imagine something like:

```sh
hab plan init --template=mycompany/standard-tomcat-plan
```
(Ignore the probably-terrible UX shown here; just focus on the nifty behavior it would enable :sweat_smile:)

Habitat itself would just need to define the basic interface for such a template package, and then users would be free to do whatever they wanted with it.

(For what it's worth, I'd like to do something similar with exporters, too, but that's a different can of worms :smile: )

**Comment by jmassardo** [comment]
![ooo](http://giphygifs.s3.amazonaws.com/media/nVXzt7FSJlX7W/giphy.gif)

I like that idea. Great way to standardize the plans for an org.

**Comment by Snohio** [comment]
Can we reopen this issue.. With `hab studio enter -D` a thing to use a Docker container for the studio, it would be helpful for some, maybe. :smile_cat:
