### ISSUE TITLE
Fails to load/configure new plan version

### ISSUE THREAD

**Issue by epcim** [habitat-sh/habitat#6532]
## issue 
Having a supervisor, where epcim/vesbox-ipxe is already loaded (without --trategy rolling; version 0.1.1), assuming there is new version in builder (0.1.2). (Note vesbox-ipxe is just and wrapped core/nginx plan)

Pls. explain what is the correct behavior. If it's not supposed to be a bug, what is the proper way to manage versions on supervisors to avoid this?

## Hab versions deployed on supervisor:
```
/hab/pkgs/core/hab/0.79.1/20190410220617/ 
/hab/pkgs/core/hab-sup/0.79.1/20190410223329/
```
## Steps to reproduce

Step 1. - unload the service: 

  hab svc unload epcim/vesbox-ipxe --remote-sup=$HAB_REMOTE:9632 
  
Step 2. - load the service:

  hab svc load epcim/vesbox-ipxe --force --channel unstable --topology standalone --group default --strategy rolling --remote-sup=$HAB_REMOTE:9632

NOTE: actually ends up with running version 0.1.1 (plan not upgraded)

Step 3. - load the service (specific version):

 unload again
  `hab svc unload epcim/vesbox-ipxe --remote-sup=$HAB_REMOTE:9632 `

load specific
 ` hab svc load epcim/vesbox-ipxe/v0.1.2 --force --channel unstable --topology standalone --group default --strategy rolling --remote-sup=$HAB_REMOTE:9632`

```
  » Installing epcim/vesbox-ipxe/v0.1.2
  ☁ Determining latest version of epcim/vesbox-ipxe/v0.1.2 in the 'unstable' channel
  ↓ Downloading epcim/vesbox-ipxe/v0.1.2/20190503112955
      9.17 KB / 9.17 KB | [=================================================================================================================================================] 100.00 % 3.71 GB/s  ☛ Verifying epcim/vesbox-ipxe/v0.1.2/20190503112955
  → Using core/bzip2/1.0.6/20190115011950
  → Using core/cacerts/2018.12.05/20190115014206
  → Using core/curl/7.63.0/20190305215321
  → Using core/gcc-libs/8.2.0/20190115011926
  → Using core/glibc/2.27/20190115002733
  → Using core/libedit/3.1.20150325/20190115154039
  → Using core/linux-headers/4.17.12/20190115002705
  → Using core/ncurses/6.1/20190115012027
  → Using core/nghttp2/1.34.0/20190115160823
  ↓ Downloading core/nginx/1.16.0/20190426173510
      367.94 KB / 367.94 KB | [===========================================================================================================================================] 100.00 % 172.60 GB/s  ☛ Verifying core/nginx/1.16.0/20190426173510
  → Using core/openssl-fips/2.0.16/20190115014207
  → Using core/openssl/1.0.2r/20190305210149
  → Using core/pcre/8.42/20190115012526
  → Using core/zlib/1.2.11/20190115003728
  ✓ Installed core/nginx/1.16.0/20190426173510
  ✓ Installed epcim/vesbox-ipxe/v0.1.2/20190503112955
  ★ Install of epcim/vesbox-ipxe/v0.1.2/20190503112955 complete with 2 new packages installed.
  The epcim/vesbox-ipxe/v0.1.2 service was successfully loaded
```  
  
 But then:
 `hab svc load epcim/vesbox-ipxe/v0.1.2 --channel unstable --topology standalone --group default --strategy rolling --remote-sup=$HAB_REMOTE:9632 `  returns:
  
    ✗✗✗
    ✗✗✗ [Err: 3] Service already loaded, unload 'epcim/vesbox-ipxe/v0.1.2' and try again
    ✗✗✗
     
 And:
 
   hab svc status --remote-sup=$HAB_REMOTE:9632                                              
```
   No services loaded.
```

 And the content of /hab/svc/vesbox-ipxe is the one from version 0.1.1
 
 The deployed spec: 
```
../sup/default/specs/vesbox-ipxe.spec 
ident = "epcim/vesbox-ipxe/v0.1.2"
group = "default"
bldr_url = "https://bldr.habitat.sh"
channel = "unstable"
topology = "standalone"
update_strategy = "rolling"
binds = []
binding_mode = "strict"
desired_state = "up"

[health_check_interval]
secs = 30
nanos = 0
```
 
 ## Expected behaviour
 
 * supervisor upgrade the SVC binnaries and svc_path content.
 * load comamnd fails if does not procceed with all required configuration
 * on step2 I would expect plan would be upgraded to 0.1.2 (but seems pkg from cache was used).

**Comment by epcim** [comment]
Worth to mentin, seems my plan is buggy ```May 09 13:51:09 volterra-SYS-1 hab[22462]: hab-sup(MR): Unable to start epcim/vesbox-ipxe, hab-sup(ER)[components/sup/src/error.rs:459:55]: TemplateError(TemplateError { reason: InvalidSyntax, template_name: Some("content/isomount.sh"), line_no: Some(4), column_no: Some(23) })``` that's probably why not in the service status

**Comment by epcim** [comment]
You were almost right on triage, it's not because of leader was not elected in cluster (As only one node).

The problem why pkg do not upgrade is because of ```
--channel unstable
```  - which I later found in docs (unstable ch. is never auto updated) So not a bug..

What was buggy, but no longer problem:
```
The epcim/vesbox-ipxe/v0.1.2 service was successfully loaded
``` even it failed to start, and the fact that `hab svc status` did not listed any - But here I guess there is a fix on latest hab-sup, as I havent reproduce the behaviour recently.


What I see a bug is 
The actual reason to TemplateError was this
```
3 VERSION="${1:-{{cfg.ves.image_revision}}}"   
4 [[ $VERSION =~ ^{{cfg ]] && VERSION=  
```  where busybox bash basically rejects this expression `$VERSION =~ ^{{cfg`

**Comment by baumanj** [comment]
Sounds like the issue may be resolved, so I'm going to close this. Feel free to re-open with more explanation if there's still something to fix here.
