### ISSUE TITLE
Studio should pull in appropriate ca certs as needed

### ISSUE THREAD

**Issue by scotthain** [habitat-sh/habitat#6541]
When using a custom CA cert with the `SSL_CERT_FILE` it is possible to exclude the cert itself when entering the studio, depending on where the cert file is located.

Current behavior:
cert is located at `/some/random/cert.pem`
studio is entered at `/home/person/project`
studio chroot is created from `project` and cert.pem is outside. (specifically `/some/random/cert.pem`, which the env variable is set to doesn't exist in the chroot)

Desired behavior:
cert is located at `/some/random/cert.pem`
studio is entered at `/home/person/project`
studio chroot is created from `project` and during creation process `/some/random/cert.pem` is somehow included in appropriate location in chroot and `SSL_CERT_FILE` is set/updated inside the studio environment. (there's lots of options for implementation: mounting file, straight copy, etc)

**Comment by bdangit** [comment]
Yes!!!! This would be amazing to get this.
