### ISSUE TITLE
Remove description implementation for std::error::Error

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6555]
The `description` function for the `std::error::Error` trait has been ["soft-deprecated"](https://doc.rust-lang.org/1.34.0/std/error/trait.Error.html#method.description).

Historically, this implementation has always been a bit "noisy" in our codebase, since it largely duplicates the `Display` trait implementation for our error types.

The docs say that we no longer need to implement `description`, and should favor implementing `Display` on new types. Since we already do the latter, we should now to the former and remove all `description` implementations in all the crates of this repository.

**Comment by menoude** [comment]
Hi,
I'm looking for a first contribution to a project, do you only need to remove the method implementation everywhere or is there a need for some replacement? If it's the former, I can try to handle that :)

**Comment by christophermaier** [comment]
@menoude Yes, this is just about removing the current method implementations; we don't need anything to replace them.

(Rather, it _should_ be just about removing the current code... I don't think we're explicitly using the `description` method ourselves, and have only implemented it to conform to the then-current definition of the `Error` trait. If you get into it and find otherwise, let's chat 😅 )

Thanks for your interest in Habitat; we're very glad to have you around!
