### ISSUE TITLE
Add an option to remove cached packages

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6576]
`hab pkg uninstall` will uninstall a package and any dependencies that can safely be removed. However, it might also be nice to remove cached packages as well to save space.

There could be an extra option added to `hab pkg uninstall` (say, `--cached`) that will remove any cached artifacts for any packages that get removed.

It may also be useful to have a dedicated command to manage the cached packages directly (e.g., `hab cache clear --all`, `hab cache clear mycompany/myapp`, etc.)

**Comment by baumanj** [comment]
Should we connect this work to https://github.com/habitat-sh/habitat/issues/6426 at all?

Also, I wonder if removing cached dependencies should be the default for uninstall. We should consider what the expected and desired behavior of
```bash
$ hab pkg install origin/foo
$ hab pkg uninstall origin/foo
$ hab pkg install origin/foo
```
Should be in terms of forcing a new download and such.

> It may also be useful to have a dedicated command to manage the cached packages directly (e.g., `hab cache clear --all`, `hab cache clear mycompany/myapp`, etc.)

👍 similar to what [`brew cleanup`](https://docs.brew.sh/Manpage#cleanup-options-formulacask)
