### ISSUE TITLE
hab studio rm inside a container with the current working directory mounted may delete directory contents

### ISSUE THREAD

**Issue by james-stocks** [habitat-sh/habitat#6591]
**Note:** This issue seems to be tangled up with https://github.com/habitat-sh/habitat/issues/6577 - I felt it best to raise a separate issue due to the severity of this bug's effect (deleted files!)

**Versions:**
Using https://hub.docker.com/r/chefes/buildkite which currently has `hab 0.77.0/20190301212334`

**To reproduce:**

On your workstation:

```
cd /tmp
mkdir test_folder
touch a b c d
docker run --privileged=true -it -v $(pwd):/workdir -w /workdir chefes/buildkite bash
```

You are now inside Chef's standard CI docker image, with the current directory with files `a b c d` available inside the container as `/workdir`.
Note that this is how Chef's CI uses the container - it checks out the repo to build/test then steps inside the container to run build instructions.

Inside the container:

```
hab studio enter
exit # the studio
hab studio rm
exit # the container
ls
```

**Expected:**

Enter and exit the studio without error; exit the container; then running `ls` will show the 4 files `a b c d`

**Actual:**

`hab studio rm` causes a very large number of permission errors like

```
rm: can't remove '/hab/studios/workdir/proc/263/oom_score': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/oom_adj': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/oom_score_adj': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/loginuid': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/sessionid': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/coredump_filter': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/io': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/uid_map': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/gid_map': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/projid_map': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/setgroups': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/timers': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263/timerslack_ns': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc/263': Operation not permitted
rm: can't remove '/hab/studios/workdir/proc': Resource busy
rm: can't remove '/hab/studios/workdir/dev/console': Resource busy
rm: can't remove '/hab/studios/workdir/dev/shm': Resource busy
rm: can't remove '/hab/studios/workdir/dev/mqueue': Resource busy
rm: can't remove '/hab/studios/workdir/dev/pts/ptmx': Operation not permitted
rm: can't remove '/hab/studios/workdir/dev/pts': Resource busy
rm: can't remove '/hab/studios/workdir/dev': Resource busy
rm: can't remove '/hab/studios/workdir/src': Resource busy
rm: can't remove '/hab/studios/workdir': Directory not empty
```

The 4 files `a b c d` are gone!

**Comment by smacfarlane** [comment]
The behavior I see is that when reading `/proc/mounts` the busybox mount command reads 1024 bytes into its buffer twice, performs an `lseek` and then exits without any further output or error code.  

I only have one test case currently (the chefes container), so my suspicion is either length of output from `/proc/mounts`, as the overlayfs for that container is very long and the normal studio doesn't exhibit this behavior, or something specific in that containers `/proc/mounts` that is causing this.  It also appears to be related to the musl libc, as I'm unable to reproduce with glibc based busybox binaries. 

I'm going to see if I can work up a reproduction that doesn't depend on busybox or the chefes container to narrow down what might be causing this.

**Comment by smacfarlane** [comment]
I've put together a couple test cases and am fairly confident that this is a bug in musl that is exposed when busybox reads a line in /proc/mounts > 1024 characters. I can reproduce the error on Alpine Linux, which is musl based, but also uses glibc so feel safe eliminating something Hab specific. `core/busybox`,which is built against glibc also does _not_ exhibit the behavior, so I'm fairly certain it's not a busybox bug, but I don't yet have a test case that exhibits the behavior without busybox or /proc/mounts being involved.

**Comment by irvingpop** [comment]
I can confirm.  Fairly stock Ubuntu 18.04 with a number of other docker containers running:

```
#  mount | wc --max-line-length
1169
```

You can also see this in a docker/sudo enabled Travis-CI xenial system.

**Comment by fnichol** [comment]
@smacfarlane OMG if this ends up being true, you deserve a certified gold trophy! Your logic tracks really well to me and that's like 3 steps further than I was able to get (triangulating against musl and Glibc was a stroke of genius). GOOD. SLEUTHING.

![tenor-12163345](https://user-images.githubusercontent.com/261548/58743173-05899780-83ea-11e9-894c-9337061311b7.gif)

**Comment by smacfarlane** [comment]
I've confirmed this is a bug in how busybox is using getmntent_r to get t the mounted filesystems.  Musl's implementation of (getmntent_r)[https://git.musl-libc.org/cgit/musl/tree/src/misc/mntent.c#n37] will return 0 if it fills its buffer without encountering a newline.  This behavior was (patched in 2016)[https://www.openwall.com/lists/musl/2016/09/08/1] to allow for a dynamically allocated buffer, however it appears that busybox (does not take advantage)[https://git.busybox.net/busybox/tree/util-linux/mount.c#n2235] of this functionality and uses a static buffer.

Note: My C is pretty rusty 🥁 but the above tracks with the behavior I've been seeing.
