### ISSUE TITLE
Finish the simplification of Protobuf generation across the project

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6628]
This was a follow-on task for https://github.com/habitat-sh/habitat/issues/5949 that we never got to.

In particular, the [generation logic for sup-protocol](https://github.com/habitat-sh/habitat/blob/master/components/sup-protocol/build.rs) is _far_ too complex. It does a lot of custom code generation that really should just be written out normally. Check out #6105 for some guidance; all our protobuf generation should basically look like that.

Additionally, we should ensure that all generated protobuf code is _not_ committed to the repository, and generated at compile time. This ensures a consistent experience for all our crates.

**Comment by raskchanky** [comment]
Specifically, the 2 crates that this concerns are:

https://github.com/habitat-sh/habitat/tree/master/components/sup-protocol
https://github.com/habitat-sh/habitat/tree/master/components/butterfly

Yes?

**Comment by christophermaier** [comment]
@raskchanky Yup... how could I forget about Butterfly?!?!
