### ISSUE TITLE
 Refactor `studio enter`

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6633]
`hab studio enter` has to handle a multitude of ways of creating a studio. For example, from a script, from a package, docker containers, windows vs Linux vs MacOS, etc. This has lead to a very complicated set up in determining what studio to launch and a lot of code duplication between Unix and windows implementations.

We should look at refactoring this code to reduce duplication and make it easier for a developer to understand how, and which, studios are invoked.

**Comment by ericcalabretta** [comment]
@smacfarlane Would this also deal with refactoring the studio enter UX? 

The different UX behavior between MacOS/Linux/Windows platforms and the different behavior of `hab studio enter` vs hab studio enter -D` can be confusing. Folks forget to do `hab studio rm` for non -D studios which causes problems. 

`hab studio` also won't accept `--help` so it can be difficult to understand the various options like `hab studio run build`
