### ISSUE TITLE
Add HAB_STUDIO_SUP support to Windows studio

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6650]
The Linux chroot studio support the ENV var `HAB_STUDIO_SUP=` which can be set to `false` or `no` in order to disable the starting of the supervisor when entering a studio. 

This would be useful when running tests on the studio in CI, as the sup install and start often takes longer than than test to run leading to failures in CI.

**Comment by mwrock** [comment]
It may be worth adding in #5453 along with this work

**Comment by mwrock** [comment]
still relevant
