### ISSUE TITLE
In Windows, hab pkg exec should add to PATH instead of replace it

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6657]
This is definitely a problem on Windows and **might** be on Linux too. For instance, any windows program pretty much expects `c:\windows\system32` to be on the path and may fail if it is not. `hab pkg exec` adds the package deps and any other vars from `Invoke-SetupEnvironment` to the environment. Ideally it should add to the `PATH` and not replace it.

**Comment by smacfarlane** [comment]
On Linux, at least, this is correct behavior. If we were to add to the path rather than replace we would lose some of the isolation guarantees. Depending on ordering, we would either potentially use system commands instead of the desired hab commands or mask a missing dependency.

@mwrock Would it be fair to say for `hab pkg exec` the behavior should be 

Windows: `$env:PATH=C:\windows\system32:$env:RUNTIME_ENVIRONMENT_PATH`
Linux: `PATH=$RUNTIME_ENVIRONMENT_PATH`   

Where $RUNTIME_ENVIRONMENT_PATH comes from the metadata file `RUNTIME_ENVIRONMENT` ?

**Comment by mwrock** [comment]
close. There are a couple other windows system dirs to add as well. Ultimately I'd expect the same behavior that the supervisor uses which is to prepend the dep paths to the current path. That way those deps should take precedence over anything else in the path.

**Comment by mwrock** [comment]
Thinking more on this I am leaning that this behavior (appending existing `PATH` entries) would be correct linux behavior. I think the isolation guarantees are largely the responsibility of the studio environment. Even in a studio, the build system and binlinks will honor the existing `PATH` entries which can be edited inside a studio environment.

**Comment by smacfarlane** [comment]
@mwrock I don't think you want system paths to come first in Linux.  I kinda don't feel they should be present at all, but you definitely don't want them to come first.  

Contrived example: consider a package that relies on busybox behavior for core utility packages (or even bsd versions of them if they were to be made available). By putting the system paths first, you'll always get those versions of the packages,coupling the behavior of the package to the distro it's installed on and in the worst case breaking the package.

**Comment by mwrock** [comment]
totally not first @smacfarlane . I think you always want the packages runtime dep `PATH` entries to be first. In the supervisor and plan-build we prepend the runtime path entries.

**Comment by smacfarlane** [comment]
Ahh, I must be misunderstanding what you wrote, sorry.  

I'm not certain on the supervisor, but in plan-build I'm fairly positive we ensure that PATH is calculated to only contain direct and transitive dependencies that set PATH values (via `pkg_bin_dirs=`) during the build process. 

I had assumed the supervisor has the same behavior, for the same reasons I note for `hab pkg exec`, but that warrants further reading on my part to better understand the how it sets up the environment for the lifecycle hooks.  

Again, I might be misunderstanding what you're saying, I probably need to see some concrete examples to wrap my head around it.

**Comment by mwrock** [comment]
oh ok it looks like the linux studio calls the plan-build script via `hab pkg exec` which would wipe the `PATH`. Thus `INITIAL_PATH` in https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L1513 would only have the environment from `plan-build`. The windows script doesn't go through `hab pkg exec` so it looks like thats how it does retain the PATH.

For reference, the Supervisor hooks uses [append_interpreter_and_path](https://github.com/habitat-sh/habitat/blob/master/components/common/src/util/path.rs#L145) to append the interpreter path and the existing `PATH` to the hook environment.

**Comment by stevendanna** [comment]
I've always seen the supervisor's behavior on Linux (appending both busybox-static AND the existing path) to be less about "correctness" and more about easing the on-ramp to getting real-world services into the supervisor.  If we do change the behavior of `hab pkg exec` to have the same behavior, I would prefer if we had a user-controlled option to turn that behavior off in both the supervisor and `hab pkg exec`?  

You might ask, "Why, what is the possible harm if the Habitat controlled path entries come first?"  and to me the answer is that part of the goal of Habitat is to drive your packages towards a complete description of the runtime environment. Appending the path means that unrealized runtime dependencies can go unnoticed for some period of time.

**Comment by robbkidd** [comment]
From my own experiments:

In `Invoke-SetupEnvironment`:
```
Push-RuntimeEnv PATH "C:\windows"
Push-RuntimeEnv PATH "C:\windows\system32"
Push-RuntimeEnv PATH "C:\WINDOWS\System32\WindowsPowerShell\v1.0"
```

During build:
```
_Exit-With : Cannot directly manipulate environment variable PATH! Add appropriate entries to the 'pkg_bin_dirs' variable in plan.ps1 instead!
```

**Comment by robbkidd** [comment]
The Habitat philosophy of "a package delivers all its dependencies" conflicts with "package any application, anywhere, and this application makes calls to system utilities we don't foresee being able to package."

Among the things I see chef-client attempting to shell-out and execute at runtime is the shell itself (`powershell.exe`), `net.exe` and `schtasks.exe`.

This smells a bit like a scenario that has come up in the past for Linux: repackaging a binary without modifying the libraries it links to, thereby opting out of the Habitat feature of "owning all your dependencies." The scenario is often driven by a Habitat user trusting a Linux distribution's library builds over Habitat's, particularly around accredited crypto libraries for consumers that care about that sort of thing. The package's assumption then is that something else has installed those dependencies to locations the binary expects, while the user gets to benefit from the service runtime goodness features of Habitat.

Allowing the addition of directories to `PATH` that do not descend from Habitat origins similarly allows a packager and end-users to opt-out of the dependency guarantees of a Habitat package. We should consider allowing this or we'll need to figure out how to package and legally redistribute utilities shipped with the Windows operating system.

**Comment by robbkidd** [comment]
Yea. Definitely see the need for being able to add directories to the PATH that are not from other Habitat packages. With `pkg exec` and when a package's service is managed by the supervisor.

**Comment by mwrock** [comment]
Maybe the best "first stab" at a solution here is a windows only implementation where the system directories are added to the path. Bottom line is that without those, nothing can be guaranteed to work on windows.

**Comment by robbkidd** [comment]
I might be discovering that Chef-on-Linux also expects to be able to shell out and call commands supplied by the host operating system.

Certainly baby-steps are good. As a user of Habitat across platforms, I worry about the behavior and user experience differing too much between Linux and Windows. Between solving this only for Windows' `pkg exec` and the existing difference between Windows and Linux binstubs, it is difficult to get an cross-platform app behaving similarly outside the supervisor.
