### ISSUE TITLE
Add delay before starting healthchecks

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#6701]
It would be a good idea to tweak the health check future to wait for some delay (say 5 seconds?) and _then_ launch into its check-wait-check cycle. This allows the service some warm up time before the first health check. You would get this same initial delay behaviour for restarts as well as for reconfigure (as well as plain old starts, of course). Reducing the amount of special cases seems like a good thing. We'd still want to ensure that the "handle" we keep to the overall health checking future still works, such that it would still kill the future if for some reason we needed to kill the service before that initial delay expired.

**Comment by stevendanna** [comment]
@davidMcneil Just for certainty, the proposal here is still have an initial health check that happens sooner than the typical interval, but to move it to a slightly longer delay as opposed to happening on the first "server tick"?

**Comment by davidMcneil** [comment]
Right. The thinking is to give the services some time to reach a "steady state" before they run their first health check. The delay amount is arbitrary but in practice, it might work well enough to prevent odd behavior for the first health check.
