### ISSUE TITLE
more useful error message for multiple linux studios or supervisors

### ISSUE THREAD

**Issue by ericcalabretta** [habitat-sh/habitat#6732]
The Linux studio should have a more useful error messages if a user attempts to launch two studios simultaneously. This is an easy mistake to make in the non-docker Linux studio. Users can easily forget `hab studio rm` when switching projects or are unaware of the non-docker studio behavior to persist the studio after `exit`.

Here's the Linux error message which directs users towards a secret rather than the root cause of a supervisor is already running on the machine. The studio also allows a user to enter it without an obvious error message about the supervisor failing to start. Any supervisor commands receive the following error: 

```
[10][default:/src:0]# hab svc load eric/sample/2.0.0/20190627215150
✗✗✗
✗✗✗ [Err: 4] secret key mismatch
✗✗✗
[11][default:/src:1]# hab svc status
✗✗✗
✗✗✗ [Err: 4] secret key mismatch
✗✗✗
```
The windows studio error is a good example of a more helpful message. The windows studio makes it it obvious when entering the studio that the supervisor was unable to start. This correctly directs users to the root cause of the problem, being another supervisor exists somewhere. 
```
hab-sup(MR)[components\sup\src\manager\mod.rs:1652:36]: Unable to start Habitat Supervisor because another instance is already running with the pid 18848.
[2019-07-16T01:18:31Z ERROR hab_launch] Launcher exiting with code 86```

**Comment by baumanj** [comment]
There's no issue with launching two studios simultaneously (and if they're docker-based, they can also have their own supervisors), so the issue to address is a better error message when there is a supervisor already running. https://github.com/habitat-sh/habitat/issues/5169 exists for that, so I'm going to close this one.
