### ISSUE TITLE
Restart `post-run` retries following a supervisor restart

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#6739]
This [PR](https://github.com/habitat-sh/habitat/pull/6705) adds retry logic to the `post-run` hook. If the supervisor is restarted before the `post-run` hook succeeds the `post-run` will not be retried.

In order to fix this, we would need to store the state of the `post-run` hook before a supervisor restart and check this state to determine if the `post-run` hook should be retried.

**Comment by jsirex** [comment]
So its fixed now?

**Comment by davidMcneil** [comment]
The `post-run` hook will be retried. However, if the Supervisor is restarted while the `post-run` hook is still trying to run successfully the `post-run` hook will not start trying again once the Supervisor starts back up. So no the exact scenario this issue is refuring to is not fixed.
