### ISSUE TITLE
hab reports broken pipe with lots of erroneous output when used in a pipeline

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#6754]
If hab receives a broken pipe error, it returns a large error message that is mostly erroneous:

```
# hab svc status | head -0
✗✗✗
✗✗✗ Unable to contact the Supervisor.
✗✗✗ 
✗✗✗ If the Supervisor you are contacting is local, this probably means it is not running. You can run a Supervisor in the foreground with:
✗✗✗ 
✗✗✗ hab sup run
✗✗✗ 
✗✗✗ Or try restarting the Supervisor through your operating system's init process or Windows service.
✗✗✗ 
✗✗✗ Original error is:
✗✗✗ 
✗✗✗ Broken pipe (os error 32)
✗✗✗
```

The real problem here is that we got a broken pipe because I used the command in a pipeline where 0 rows were read.  While I haven't looked into the code, I imagine this isn't usually hit because I'll bet in most cases hab is able to output all of its status data in a single write call and thus only the pathological case will ever see the broken pipe.

**Comment by raskchanky** [comment]
Is it possible to get some more information on how to reproduce this?  I tried running the command you did on a machine where the supervisor was running, but had no services loaded, and I got an empty response.  The only way I've been able to reproduce that error is running that same command when no supervisor is running at all.

**Comment by stevendanna** [comment]
This is kinda interesting. You need at least one service loaded to reproduce the bug. With no services loaded, hab writes "No services loaded." to stdout, receives the bad pipe error from the write system call, but indeed does not emit the large error message above:

```
[pid 13357] write(1, "No services loaded.\n", 20) = -1 EPIPE (Broken pipe)
[pid 13357] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=13357, si_uid=0} ---
[pid 13357] exit_group(0)               = ?
[pid 13361] <... epoll_pwait resumed> <unfinished ...>) = ?
[pid 13361] +++ exited with 0 +++
[pid 13357] +++ exited with 0 +++
```

With 1 service loaded, we start to write the status output, get an EPIPE, retry the write (??), get an EPIPE again, and then start writing the error message:

```
[pid 13435] write(1, "package                         "..., 100) = -1 EPIPE (Broken pipe)
[pid 13435] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=13435, si_uid=0} ---
[pid 13435] write(1, "package                         "..., 100) = -1 EPIPE (Broken pipe)
[pid 13435] --- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=13435, si_uid=0} ---
[pid 13435] write(2, "\33[0m", 4)       = 4
[pid 13435] write(2, "\33[0m", 4)       = 4
[pid 13435] write(2, "\33[1m", 4)       = 4
[pid 13435] write(2, "\33[31m", 5)      = 5
[pid 13435] write(2, "\342\234\227\342\234\227\342\234\227", 9✗✗✗) = 9
[pid 13435] write(2, "\33[0m", 4)       = 4
.... 
[pid 13435] +++ exited with 1 +++
````

In the case of no services loaded we print directly to stdout with the `println!` macro:

https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L1572

but in the case of service output, we are writing to an internal buffer provided by TabWriter (for pretty aligntment:

https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L1601

which then gets flushed:

https://github.com/habitat-sh/habitat/blob/master/components/hab/src/main.rs#L1108

*speculation starts here*

In the case of just calling println! I assume any errors to stdout just get ignored, whereas with the tabwriter, the call to flush() is likely returning epipe again and then we return that error.  I fear that in this case the detective may have caught himself:

https://github.com/habitat-sh/habitat/commit/115a42a3680f59579c360e5c2b0538d806b27aa6

**Comment by raskchanky** [comment]
@stevendanna Thank you for the detailed writeup!  I've opened https://github.com/habitat-sh/habitat/pull/6755, which at least in my tests, seems to fix this problem.
