### ISSUE TITLE
NATS client library does not support self-signed certificates

### ISSUE THREAD

**Issue by gpeers** [habitat-sh/habitat#6769]
The NATS client library ([mnetship/ratsio](https://github.com/mnetship/ratsio)) we use to integrate with Automate has proven to be insufficient for our purposes: it is missing required features (support for self-signed server certificates), and we've needed to patch the library with multiple fixes to basic functionality such as client reconnect (#6737, #6761).

Unfortunately NATS client library support for the Rust language is both sparse and limited feature-wise. The team considered packaging one of the Go client libraries with Habitat and communicating via protobuf, but decided going with another Rust client library would likely mean fewer maintenance headaches overall. To resolve this situation, the team has proposed the following next steps:
- evaluate any other Rust client libraries we can find (so far, [YellowInnovation/nitox](https://github.com/YellowInnovation/nitox) and [Rust-NATS](https://github.com/jedisct1/rust-nats)) to help us decide whether to keep patching the current library or to move to another one
- consider using only NATS messaging features, adding streaming features back into the product when customer need drives it

**Comment by davidMcneil** [comment]
Since our last evaluation of NATS client libraries, there has been a new addition [davidMcneil/rants](https://github.com/davidMcneil/rants). Full discloser, I wrote it, but I think it provides improvements over other clients. Two things to be aware of with the library: it will only work on stable rust when 1.39 lands and TLS support is still in the works.

**Comment by gpeers** [comment]
thanks @davidMcneil, appreciate you sharing this information!
