### ISSUE TITLE
0.83.0 hab studio enter no longer auto-installs core/hab-studio (chroot studio)

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6771]
### Scope 
This bug only affects the 0.83.0 Linux chroot studio.  Windows, MacOS and Linux Docker studios appear to be unaffected.  

### Workaround 
As a workaround, you can run `hab pkg install core/hab-studio/0.83.0` on any Linux machines that require the chroot studio before executing those commands. 

### Details
With the 0.83.0 release, there was a small change to how the studio is invoked on Linux in order to enable us to make the hab-backline package an explicit dependency of the studio. #6549. 

Unfortunately, the process for entering a studio attempts to read the RUNTIME_ENVIRONMENT metadata [[link](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/studio/enter.rs#L122)] before the package is installed [[link](https://github.com/habitat-sh/habitat/blob/master/components/hab/src/command/studio/enter.rs#L135)].

This appears to have been missed in the release process because we always explicitly install the studio [link](https://github.com/habitat-sh/habitat/blob/master/.buildkite/scripts/shared.sh#L123-L126). 

### Tasks:
 - [ ] Ensure studio is installed before attempting to read package metadata
 - [ ] Add end-to-end test to verify studio can be invoked from a clean system

**Comment by scotthain** [comment]
This is a workaround for our release process https://github.com/habitat-sh/habitat/pull/6775

Let's remember to remove it once we get this resolved!
