### ISSUE TITLE
Thorough overhaul of lifecycle hook documentation

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6784]
We should do a thorough review and refresh of all lifecycle hook documentation. 

In particular, we should:

- provide a state diagram that shows how all hooks are related to each other, when they run, etc.
- document particular behaviors of each hook (e.g., health-check re-runs periodically, post-run re-runs until success). This includes any special meanings for exit statuses (e.g. health-check hook exit codes).
- provide concrete examples of what each hook should be used for
- document any known platform-based differences or idiosyncrasies.
- ensure that this documentation is prominently linked from the documentation around how to write plans.

**Comment by sirajrauff** [comment]
This seems like it would still be useful two years later, especially RE: behaviours such as re-trying on failure, etc.
