### ISSUE TITLE
No studio docker image for Windows Server 2019

### ISSUE THREAD

**Issue by jmassardo** [habitat-sh/habitat#6786]
When running the Habitat (0.83) studio on Windows Server 2019, the docker based options are not available as there is no Windows Server 2019 image available. 

Repo:
```
hab pkg build . -D

Error response from daemon: manifest for habitat/win-studio-x86_64-windows:ltsc2019-0.83.0 not found: manifest unknown: manifest unknown
XXX
XXX The Docker image habitat/win-studio-x86_64-windows:ltsc2019-0.83.0 is unreachable due to a network error.
XXX The image must be reachable to ensure the versions of hab inside and outside the studio match.
XXX You can specify your own Docker image using the HAB_DOCKER_STUDIO_IMAGE environment variable.
XXX
```

`hab pkg build .` works as expected.

**Comment by mwrock** [comment]
We have manually published the 2019 docker image for 0.83.0 and added automation to automatically publish both 2016 and 2019 studios in future releases starting with 0.84.0.
