### ISSUE TITLE
Adopt Design Proposals

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6792]
# Description

As we continue to iterate on our open source business mode we would like to adopt [design proposals](https://github.com/chef/chef-oss-practices/blob/bc374ecaa5d0236f8dde3e92dfa5964bac43e2e5/contributors/guide/design-proposals.md). A design proposal shall be introduced on major changes that will allow all interested parties to discuss the impact and provide durable documentation of the design.

# Acceptance Criteria
- [ ] Design proposals are documented and used in the Habitat project
- [ ] Design proposals are documented and used in the Builder project

**Comment by nellshamrell** [comment]
Working on one right now in #6793
