### ISSUE TITLE
Spike: Investigate the utility of Jepsen for more thoroughly testing the Supervisor

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#6820]
[Jepsen](https://github.com/jepsen-io/jepsen) is a tool for testing and verifying distributed systems. It has been successfully used to verify (and find bugs in) many distributed systems (mostly databases). It's not immediately obvious if it would be appropriate for testing the Supervisor. If it is, though, it seems like it would be very useful for us. We should investigate and see if it is something we could use.

# Acceptance Criteria
A decision to either move forward with more in-depth use of Jepsen, or to abandon it as inappropriate for our needs.

**Comment by raskchanky** [comment]
Is it worth making an issue for TLA+ as well?

**Comment by christophermaier** [comment]
_Narrarator: It was - https://github.com/habitat-sh/habitat/issues/6823_
