### ISSUE TITLE
Spike: Investigate the utility of TLA+ for more thoroughly testing the supervisor

### ISSUE THREAD

**Issue by raskchanky** [habitat-sh/habitat#6823]
From [the website](https://learntla.com/introduction):

> TLA+ is a formal specification language. It’s a tool to design systems and algorithms, then programmatically verify that those systems don’t have critical bugs. It’s the software equivalent of a blueprint.

The [wikipedia page](https://en.wikipedia.org/wiki/TLA%2B) for TLA+ lists several use cases that sound like they're in a similar vein to the supervisor.  There's no guarantee that this tool is a good fit for our use case, but it's intriguing enough to warrant a more complete investigation.

# Acceptance Criteria
A decision to either move forward with more in-depth use of TLA+, or to abandon it as inappropriate for our needs.

**Comment by christophermaier** [comment]
Potentially relevant for us: https://github.com/spacejam/tla-rust
