### ISSUE TITLE
Create Special Habitat Build

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6872]
# Description

We need to create a one off build for a customer with some special fixes. Follow the instructions produced in #6869.

# Acceptance Criteria
1. Create a build off of master
2. Put all the release artifacts into the event-stream channel in Builder

**Comment by davidMcneil** [comment]
Build artifacts
linux: `core/hab-sup/0.83.0/20190821024733`
windows: `core/hab-sup/0.83.0/20190820225530`
