### ISSUE TITLE
[Design] - Handle Windows health checks from a single Powershell instance per service

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6873]
# Powershell startup is expensive
Health checks run for each service at an interval. If a health check hook is defined, a `pwsh.exe` shell is spawned to execute the hook. In most scenarios this works well. There are two particular cases where we see CPU spikes during health check spawning:

* Lots of services on a single node define a heath check hook resulting in many instances of Powershell spawning at once.
* Resource constrained environments with low memory/processor power.

This problem is discussed in #5584 and the root cause is that powershell is expensive to startup. This [Powershell repo issue](https://github.com/PowerShell/PowerShell/issues/6443) discusses some of the Powershell details behind this. While this is something Microsoft is focusing on for version 7. It is not clear if this work will be completed soon or if the improved startup performance will be acceptable especially for some of our more constrained environments.

## Running a single Powershell instance per service
The introduction of the health check interval mitigated the first of the above scenarios by allowing habitat users to stagger the checks so that multiple powershell instances are not opened at once. However in a constrained environment, just one instance can cause CPU to spike. Ideally we need to limit the number of Powershell instances we spawn. Thus we must have the ability to invoke multiple health checks without spawning a new instance each time.

There may be more options but I can easily think of two possible approaches we can take here:

### Communicating from Supervisor to Powershell via named pipe
Here a service spawns a powershell instance at startup (just after invoking `run`) and that shell will run indefinitely as a named pipe server.

Each time the Supervisor invokes a health check hook's `run` , it will signal to the above powershell instance to execute the actual rendered health check hook which will return the stdout/stderr and the exit status of that hook.

### Single Powershell instance invokes hook on a timer and saves result to a file
Here, like the above named pipe based solution, we spawn a powershell instance at startup that will continually invoke the rendered health check hook and save its result to a file. The supervisor would read this file instead of spawning the health check each interval.

On the one hand this approach is simpler since it does not incur the IPC plumbing but it does not work as cleanly with our `Hook` trait abstraction. Also, this solution assumes that the health check interval between the supervisor and the Powershell instance will be in sync but they will likely be slightly off causing a delay in the actual health status by one health check iteration.

**This proposal is recomending the named pipe approach.**

### Implementation

On the Supervisor side, this should only require an alternate Windows platform implementation of the `run` function in `HealthCheckHook`. The windows `HealthCheckHook` struct will have an additional field: `pipe_hook_client: Option<PipeHookClient>`. The `run` hook of the `HealthCheckHook` will create a new `PipeHookClient` if it is `none` or if the current client's `is_connected` returns `false` (see below) and use it to communicate with a `pwsh` instance throughout the lifetime of the `HealthCheckHook`.

### PipeHookClient

A `PipeHookClient` struct will be responsible for spawning a `pwsh` based named pipe server and creating its own rust based (using the `mio-named-pipes` crate ([Github](https://github.com/alexcrichton/mio-named-pipes), [RustDocs](https://docs.rs/mio-named-pipes/0.1.6/x86_64-pc-windows-msvc/mio_named_pipes/))) named pipe client. It will expose the following public functions:

* `new` - Spawns a `pwsh` process, creates a `mio_named_pipes::NamedPipe` and sets up the polling/eventing goo. It also spawns threads to stream stdout/err of the `pwsh` process to the current stdout/err in separate threads similar to how the launcher forwards the stdout/err of the `run` hook. `new` will take a `Path` argument pointing to the health check hook file location.
* `check_health` - Signal the `pwsh` service to invoke the hook and return the exit status. 
* `is_connected` - This will return a `bool` indicating if the client is actively connected to a listening named pipe. Ideally this will always return `true` but would be `false` if, for example` someone forcefully terminated the `pwsh` service.

The `PipeHookClient` will implement `drop` to signal to the `pwsh` process  to end and shutdown.

### pipe_hook_service.ps1

This is the powershell instance that initiates the named pipe and listens for signals to invoke the health check hook. The `new` function of the `PipeHookClient` struct will spawn `pwsh.exe` to execute this script. This script will take the following arguments:

* `-HookPath` - The path to the hook file to invoke.
* `-PipeName` - The named pipe name to start. This will be in the format of `<SERVICE_GROUP>_HEALTH_<GUID>`. The `PipeHookClient` will be in charge of defining the `GUID`. The advantage here is that it ensures any `PipeHookClient` instance will have its own named pipe without the risk of connecting to an existing named pipe.

This service will be pretty simple. It will first take a snapshot of all environment variables that it will restore after each health check. Next, it will wait for a connection and that connection should be present throughout the lifetime of the pipe. The `PipeHookClient` will not disconnect and reconnect. Next it will continually loop waiting for one of two possible signals:

`check_health` - This will invoke the health check hook script, return its exit code back over the pipe to be received by the client, and finally restore all environment variables to the snap shot it took at startup.
`quit` - Exits the loop and disposes the named pipe. This terminates the execution of the script resulting in the termination of its `pwsh` process.

### Prototype

While investigating this approach I created a dummy rust executable to explore the `mio-named-pipes` API and some of the basic concepts discussed here. This is SUPER rough and ugly but serves as good reference: https://github.com/mwrock/health

**Comment by baumanj** [comment]
The spikes we're contending with are an artifact of spawning `pwsh.exe` many times on the same system, correct? It's not clear to me whether the issue is that we don't have the resources to spawn one `pwsh.exe` process per health check run period, or whether the **timing** of the spawns leads to resource overuse.

If it's the later, an alternative approach that wouldn't require any changes to habitat, would be a thin wrapper around `pwsh.exe` that serializes the various health check invocations and only runs one instance of `pwsh.exe` at a time. The benefit would be localizing the complexity to the smallest necessary scope. Then, if version 7 resolves the issue, we can easily drop the wrapper.

**Comment by ericcalabretta** [comment]
From my testing the performance impact is present for even a single service. We do not have the resources to spawn one `pwsh.exe` without impacting the operations of the system its a very expensive windows operations. 

We tested with simple or even blank health-checks.  Loading a Powershell 6 process at any increment appropriate for a health-check is a major performance impact to the running system.

**Comment by baumanj** [comment]
So the constraint is that **no** `pwsh.exe` processes are _ever_ launched during the normal running of the service; any processes we need must start up when the service does and stay resident. Is that accurate, @ericcalabretta ?

**Comment by mwrock** [comment]
Yes its the startup activity of `pwsh` that kills us. Every time any single instance of `pwsh` is spawned, a constrained environment will suffer a spike in cpu usage. The goal here is to never need to spawn a new `pwsh` instance after the initial service loading is performed.

**Comment by ericcalabretta** [comment]
@baumanj I don't know if ever is exactly fair, but with the default health-check interval being 30 seconds the performance hit is far to high to run at that frequency. It'd be unacceptable for any interval that would also be appropriate for a health-check interval. The launching process also can easily take longer than the health-check interval. 

I have seen similar performance impacts with Chef-clients runs  with something that spawns a `pwsh.exe` process. Those can also be problematic but they only occur every 30 minutes potentially only every 24 hours depending on the config.

**Comment by baumanj** [comment]
That makes sense, @ericcalabretta. I wonder if we should at least consider the option of supporting health checks on windows that don't rely on `pwsh.exe` specifically. If the typical implementation is just doing a curl or something, I imagine there are lighter-weight approaches. Or is it just the case that all Windows processes are too heavyweight for doing an `exec` per health check?

**Comment by mwrock** [comment]
Its specifically `pwsh` startup. For example, `cmd.exe` (the standard windows command shell) is extremely light weight and starts up MUCH more quickly than `pwsh` (100's of milliseconds faster). Unfortunately it really lacks the ability to interact with the native .net http client. One could install a windows compiled version of `curl` but then `cmd` scripting is very limited/awkward when it comes to parsing anything but the most basic stdout.

One of the key benefits I see with this approach is it allows us to keep the hook operating model consistent and from a user facing POV, we are not adding/altering functionality. Also from a technical stand point i do not see this as more complex than supporting `pwsh` alternatives.

**Comment by gpeers** [comment]
This is a great design doc, @mwrock. Really appreciate the time you took to write this up and help all of us understand the high-level solution and its alternatives in a nutshell. Great job!
