### ISSUE TITLE
Add 'hab pkg download'

### ISSUE THREAD

**Issue by markan** [habitat-sh/habitat#6878]
## History and context:

This work is to support:

https://app.zenhub.com/workspaces/habitat-iteration-board-5d0267716553d87b0348bb21/issues/habitat-sh/on-prem-builder/166

The purpose of that ticket is to ease the bootstrapping and updating of on-prem builders. Currently users can download all of the core plans in LATEST.tgz, or by hand download what they need, but it's a very clunky process. A user may well want to use both a subset of core packages and non-core origins (particularly for windows users). We want to make it easy to sync an on-prem builder with a specific set of top-level packages that are needed for a customer deployment. To assist with this, we wanted the on-prem-builder script (scripts/on-prem-archive.sh) to be able to take as input a set of top-level packages in a simple text based file, and create a bootstrap bundle with all the required packages and keys with transitive dependencies accounted for.

During the development process, we realized that expanding the packages transitively and downloading them was much easier implemented in Rust, so we could reuse habitat code that already did this, culminating in pull https://github.com/habitat-sh/on-prem-builder/pull/175. On review, we realized that the work not only should reuse habitat code, but really belonged as part of habitat. That would allow us to leverage even more of the habitat code
base, including UX cues like progress bars, and fold some improvements back into the habitat base.

This caused us to revisit https://github.com/habitat-sh/habitat/issues/4616; which proposes a `hab pkg download` command. Our primary purpose is to provide the functionality required for the on-prem builder script, but it still is worthwhile making it a usable command for general usage.

## Proposed Command API:

    Downloads a Habitat package or packages from Builder

    USAGE:

    hab pkg download [FLAGS] [OPTIONS] [<PKG_IDENT> | --file <FILENAME>]...

    FLAGS:
        -h, --help       Prints help information
        -V, --version    Prints version information

    OPTIONS:
        -z, --auth <AUTH_TOKEN>    Authentication token for Builder
        -u, --url <BLDR_URL>       Specify an alternate Builder endpoint. If not specified, the value will be taken from the
                                   HAB_BLDR_URL environment variable if defined. (default: https://bldr.habitat.sh)
        -c, --channel <CHANNEL>    Install from the specified release channel (default: stable)
        --cache <DIRECTORY>        Directory to use for the cache. /hab/cache is the default
        --file <FILENAME>          Newline separated list of package identifiers or filepaths
        -t, --target <TARGET>      Use this as the target architecture to fetch (default is host architecture <insert actual list of architectures here>).  
    ARGS:
        <PKG_IDENT>...             One or more Habitat package identifiers (ex: acme/redis)
 
    This command downloads package artifacts and their transitive dependencies into the cache, but does not install 
    them. It also downloads the relevant origin public keys. The packages are specified on the command line or in a
    file. This primary use of this is fetch packages to a local cache as part of bootstrapping a local builder instance.

## Design notes:

This command follows parallel construction with `hab pkg install` wherever it makes sense.

AUTH\_TOKEN, BLDR\_URL, and CHANNEL are taken from `hab pkg install`, as both commands have a similar requirement to select and download packages from a builder.

There are a few points of difference, centered around the requirement to download but not install the packages.

The following options have been removed or changed:

1) We only take package identifiers, not artifacts. The install command can be used to install local artifacts, and that isn't needed here.
2) Binlinking is part of package install, and isn't applicable, so the BINLINK, BINLINK\_DIR, FORCE, and IGNORE\_INSTALL\_HOOK options are not provided.
3) OFFLINE\_INSTALL is not applicable; the whole point is to download packages
4) IGNORE\_LOCAL isn't initially provided; however there may be some value in providing that down the road.

There are a few new flags to support the download use case better:

1) We allow the target to be provided. The TARGET option accommodates the possibility that the machine we are downloading on (say a bastion host) may be running a different OS or architecture than the machines we are building packages for. The actual implementation of the --target feature should list available architectures in the command line help. 

2) The cache directory helps us avoid cluttering the local habitat cache with packages that aren't necessary. 

3) The FILENAME option is a convenience feature. Some synchronization use cases (e.g. cloning an existing on-prem builder) could generate a long list of targets. While these could be provided on the command line, this can be burdensome, particularly on Windows, which limits command line lengths. However, this could be worked around in the script if necessary.

One option that was considered and rejected was to add a 'no recursion' flag, limiting the packages fetched to those provided, not the transitive dependencies. However that didn't seem to add much value, and was dropped.

**Comment by baumanj** [comment]
> Downloads a Habitat package or packages from Builder

I think the top level description should make it clear that this is downloading package *artifacts*. There's a fairly subtle but important difference here and it's already somewhat muddied by being in the `hab pkg` namespace.

>     --file <FILENAME>          Newline separated list of package identifiers or filepaths

Why "or filepaths"? I thought we took out support for specifying local `.hart` files in favor of only using package identifiers.

Also, `--file` makes it clear it takes a file, so can `<FILENAME>` be something more illustrative, like `<PKG_IDENT_LIST>` or something?

> This primary use of this is fetch packages to a local cache as part of bootstrapping a local builder instance.

I'm not sure this sentence is necessary, so I'd just as soon leave it out

Otherwise, I think this looks really good. Thanks for taking all that feedback and laying out the process up to here.

**Comment by ericcalabretta** [comment]
This could help in other use cases too where a user may want to pre-stage Artifacts like in situations with a suspect network or when/if the .harts are huge to fit upgrades in a change window.

**Comment by jeremymv2** [comment]
@markan @dmccown a nice refinement to the ability to download "bundles" might be something like supporting the download of meta groups like linux-build-essential, windows-build-essential or even customer app-specific tags. That way the user doesn't have to specify each individual pkg line in the source file.

**Comment by jeremymv2** [comment]
Also, just wanted to point out there is existing and possibly re-usable implementation in `hab pkg export tar` that does the .hart and tdep downloads. It's missing the ability to download keys and read from a source file.

**Comment by jeremymv2** [comment]
An idea for the use-case of bootstrapping a private Depot follows below.

Perhaps an additional argument like `--out <HARTS_DOWNLOADED_FILE>` would allow users to specify an output file containing a newline delimited list of file paths to harts downloaded.

This would harmonize nicely with a new `hab pkg upload` argument, perhaps `--file <HARTS_TO_UPLOAD>` so that the process of bootstrapping a private Depot is essentially two steps, utilizing native `hab` commands and not requiring any extra shell glue:

  • `hab pkg download --cache /var/tmp/cache --file /var/tmp/pkg_idents.txt --out /var/tmp/hart_paths.txt`
  • `hab pkg upload --url https://private.depot --cache-key-path /var/tmp/cache --file /var/tmp/harts_paths.txt`

**Comment by krasnow** [comment]
@markan Several customers have asked for better ways to sync packages between several on-prem builder instances. It would be great if I could specify the builder to download from, so that I can choose bldr.habitat.sh or my own on-prem instance.

**Comment by markan** [comment]
@krasnow the BLDR_URL option will allow the user to specify the source builder to download from.

**Comment by markan** [comment]
One thing that has come up in discussion was better support for the update case. An on-prem builder exists and has already had packages uploaded to it, but we want to make sure that it has up to date references. Right now we would download *every* package needed, whether or not it was already present on the on-prem builder. It might be useful to allow the user to specify a destination builder to use to filter what is downloaded; we would only download what was not already present there.

**Comment by chefsalim** [comment]
One other thought - we need to specify what happens if the package idents are not fully qualified. By default, we'll grab the latest for the packages.  However, it might be very useful to have an option (eg, --get-all or something similar) that lets us get all the packages for the ident.  This could be very useful in testing or other scenarios where we care about packages other than the latest.
