### ISSUE TITLE
Cannot find a release of package: core/hab-studio/0.83.0 when running 'hab studio enter'

### ISSUE THREAD

**Issue by codeconcept-tech** [habitat-sh/habitat#6901]
> After installing Habitat from script and setting up the Habitat with 'hab cli setup', when i run 'hab studio enter', i am getting the following error,

Cannot find a release of package: core/hab-studio/0.83.0

`ubuntu@chef-workstation:~/hab-two-tier$ hab studio enter
✗✗✗
✗✗✗ Cannot find a release of package: core/hab-studio/0.83.0
✗✗✗
ubuntu@chef-workstation:~/hab-two-tier$
`

**Comment by stevendanna** [comment]
You are likely hitting: https://github.com/habitat-sh/habitat/issues/6771 

I believe you can work around this by installing the package explicitly: `hab pkg install core/hab-studio/0.83.0`

**Comment by codeconcept-tech** [comment]
Thanks very much for the help.
Cheers
