### ISSUE TITLE
Upload set of packages from custom directory

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6903]

**Comment by jeremymv2** [comment]
`hab pkg upload /path/to/harts/<fileglob>` seems to already provide this functionality - is it missing a feature?

**Comment by jeremymv2** [comment]
Actually, file globbing can be susceptible to the [MAX_ARG_STRLEN](https://unix.stackexchange.com/a/120842) limit and really wouldn't be a reliable cross-platform method when uploading a directory full of thousands of .harts.

I think a better solution would be to add a `--file <HART_PATHS_TO_UPLOAD>` argument, as I proposed [here](https://github.com/habitat-sh/habitat/issues/6878#issuecomment-528600086).
