### ISSUE TITLE
On Prem Builder has all the packages I need

### ISSUE THREAD

**Issue by dmccown** [habitat-sh/habitat#6904]
## What problem are we solving? 

I need on-prem builder to have all the packages I need so that I can use Habitat in my enterprise. I need an easy way to know what packages I need. I need to be able to update packages on a regular basis.

## The ideal flow is 

    Define the list of packages I need (or even better, get a list of recommended starter packages) from SaaS builder

    Download these packages to a machine with internet access

    Upload packages to a unstable channel on my on-prem builder

    Test those packages and promote to stable when they have been validated.

​

## Objective and key results.

Key customers using on-prem builder will be more satisfied that the solution is "enterprise grade." Habitat POCs are easier and shorter.

​

## Acceptance criteria. 

    We can successfully walk through the ideal flow as described above.

    There is an acceptance environment to show this working end to end.

    We have end-to-end tests for the flow.

​

## Dependencies and blockers. 

n/a

​

## Evidence. 

Most customers using on-prem builder have complained about the difficulty of getting packages seeded and keeping them updated. At one customer, there is a person who's full time job is keeping packages synced. This is proving to be significant hurdle for POCs. One of our partners have written their own script to attempt to fix this issue, with mixed results. 

​

## Out of scope. 

This is focused on a CLI-only flow to accomplish this task. There are no changes to the Builder UI proposed here. It also doesn't include any mechanism to notify users of updates to packages.

​

## Open questions. 

n/a

**Comment by markan** [comment]
Issue #6963 is deliberately left out of this epic, as it's probably not needed
