### ISSUE TITLE
Supervisor network configuration should be more predictable

### ISSUE THREAD

**Issue by krasnow** [habitat-sh/habitat#6922]
**What problem are we solving?** 

When I'm starting the supervisor, I need to make sure it has a valid IP for itself so that it can communicate with its peers.

Today, if we can't find a valid IP, we'll set it as 127.0.0.1 which results in sadness.

​

**Acceptance criteria.**

I can manually specify an IP address.

If the supervisor cannot determine its IP, then we'll return an error.

​
**Evidence.** 

Issue [#5079​](https://github.com/habitat-sh/habitat/issues/5079)

**Comment by ericcalabretta** [comment]
@krasnow Will this improve how the hab cli commands interface with the local supervisors? I've noticed if users have permission errors or conditions things where the supervisor hasn't finished starting, we'll get the dreaded  ```✗✗✗ Unable to contact the Supervisor.``` error message. 

It makes it seem like you've had some critical failure when maybe the IP isn't available yet to the supervisor or you have some other simple issue.

**Comment by krasnow** [comment]
@ericcalabretta I'd love to dig into this issue with you, but what you describe is unrelated to the changes we're making in this epic.
