### ISSUE TITLE
Requirement for TOML for config introduces unnecessary restrictions; provide JSON as an option

### ISSUE THREAD

**Issue by HT154** [habitat-sh/habitat#6924]
I have some configurations for my service that uses arrays with mismatched item types, eg. (in JSON)
```json
{
  "array": [
    "value 1",
    {"key": "value"}
  ]
}
```

When I TOML-encode this value, it looks like this:
```toml
array = [
  "value 1",
  {key = "value"}
]
```

When I add this in my user.toml file and attempt to load my service, I'm met with an error:
```
hab-sup(MR): Unable to start my/service, Failed to parse TOML: mixed types in an array at line X
```

For a system that aims to be as general as possible and accommodate all types of applications, this limitation is a major obstacle

The supervisor should be changed to accept JSON configuration for user configs so that any JSON-expressible data may be used as Habitat configs. This could be gated behind an env var (eg. `HAB_SUP_USER_CONFIG_JSON`) for compatibility.

**Comment by HT154** [comment]
For added context:

This particular service interacts with Artifactory and has a need for [AQL](https://www.jfrog.com/confluence/display/RTF/Artifactory+Query+Language) queries in its configuration and AQL makes heavy use of mixed-type arrays. These queries are rendered out in a config template with `toJson`.

**Comment by dmccown** [comment]
I'm going to reclassify this is a feature instead of a bug. Let me know if you have any concerns.

**Comment by HT154** [comment]
I've just run into another case where TOML imposes harmful restrictions:

This same service has a different config section (again rendered with `toJson`) that defines static JSON data that gets passed on to a different external service. This service has a JSON API and expects some keys to be present, but with null value. TOML does not allow null values at all, so it becomes impossible to configure this aspect of our service.

**Comment by christophermaier** [comment]
I think accepting JSON configuration makes a lot of sense for the product, particularly as all this data ultimately ends up as JSON anyway for feeding into the templating engine.

A complete solution will require modification of configuration-handling code at various levels (e.g., `default.toml`, `user.toml`, `hab config apply`, each of which have their own particular wrinkles. I think that each piece of that puzzle can be tackled relatively independently, once we deal with the core configuration layering logic (which is currently implemented in terms of TOML explicitly).
