### ISSUE TITLE
`hab studio run` in windows only accepts single argument

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#6954]
Observed on Windows 10,  Habitat 0.83.0

When executing `hab studio run` on Windows,  the Studio only receives the first argument passed: 

```
> hab studio run Write-Host "hello" 
...
   hab-studio: Running 'Write-Host' in Studio at c:\hab\studios....

>
``` 

When running an equivalent command on Linux,  the studio accepts multiple arguments:
```
$ hab studio run echo \$HOME
...
   hab-studio: Running 'echo $HOME' in Studio at /hab/studios/.... 
/root
```

**Comment by mwrock** [comment]
duplicate of #6409
