### ISSUE TITLE
install script failing for me

### ISSUE THREAD

**Issue by prashi89** [habitat-sh/habitat#6961]
--> hab-install: Installing Habitat package using temporarily downloaded hab
+ /var/tmp/tmp.1ubyu3CYl1/hab-0.83.0-20190712231625-x86_64-linux/hab pkg install --binlink --force --channel stable core/hab
» Installing core/hab
☁ Determining latest version of core/hab in the 'stable' channel
✗✗✗
✗✗✗ Invalid Status provided
✗✗✗
+ print_hab_version
+ need_cmd hab
+ command -v hab
+ exit_with 'Required command '\''hab'\'' not found on PATH' 127

can any one suggest me what is getting wrong here ?

**Comment by stevendanna** [comment]
@prashi89 Are you still experiencing this problem?  It looks like this _might_ have been a temporary problem talking to the Habitat Depot.

If it is still happening, can you try:

`export RUST_LOG=debug`

and then running the install script again. This should produce considerably more output that can help us track down the issue.

**Comment by chefsalim** [comment]
This seems like it was an intermittent issue, please reopen if it is recurring

**Comment by prashi89** [comment]
Hi thanks for response , i think it is again access to some URLs through proxy . i am again checking in the proxy side . 
problem is: it is no where mention how many source URLs are accessed by install scripts , because every time we have to do some changes in proxy .

Thanks a lot for the response :)
