### ISSUE TITLE
Failed install hook should bubble up exit code to hab pkg install

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6964]
Today if an install hook fails with, for example, code `50000`. The cli command `hab pkg install` will exit with `1`. It would be helpful if `hab pkg install` exited with the same failed code as the install hook.

One case where this could be particularly helpful is code `3010` which an MSI exits with when a install is "successful" but a reboot is required to guarantee that running it will work. If an automated process is running `hab pkg install` it could perhaps reboot the machine if it detects `3010`.

**Comment by sdelano** [comment]
This issue also likely exists with the `uninstall` hook (when it exists)
