### ISSUE TITLE
fs:cache_XXX_path functions effectively ignore 'Some' arguments

### ISSUE THREAD

**Issue by markan** [habitat-sh/habitat#6976]
The cache_XXX_path functions don't work as expected. (e.g. fs:cache_artifact_path)

Let's take cache_artifact_path (https://github.com/habitat-sh/habitat/blob/master/components/core/src/fs.rs#L119)
The code (and usage throughout the codebase) suggests that passing a Some(PATH) argument will allow you to generate an appropriate path with PATH as a prefix. E.g. if you wanted to override the default path for artifacts to be /foo/bar/hab/cache/artifacts you could pass Some('/foo/bar') and the path would expand to be what you would expect. 

And it works that way if you are root. However, if you are not root, MY_CACHE_ARTIFACT_PATH (https://github.com/habitat-sh/habitat/blob/master/components/core/src/fs.rs#L79) resolves to an absolute path, and path.join discards the prefix when you append an absolute path.

The core issue seems to be the MY_CACHE_XXX_PATH constants can either be relative or absolute, and joining that on the end of your specified path isn't quite what you want there. This leaves these functions less than helpful when you want to specify an alternate cache location.

**Comment by chefsalim** [comment]
Agreed, these functions are not consistent and that can lead to inadvertently incorrect code. Probably over time we should migrate over to a different set of cache APIs, that allow for more flexibility and consistency.  For example, another use case is for the cache SSL - we would like to have the ability to get at both the cache folders (root level and user) even if the user is non-root so we can combine those.
