### ISSUE TITLE
Supervisor reattaches to a service after reboot that is not actually running

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#6977]
If a system is rebooted or if both the supervisor and launcher are terminated, when the supervisor and launcher come back up and a service's `PID` file exists and the pid is associated with a running process but that process is not the same as the service process then habitat will think it has reattached to the service but not run its `init` or `run` hooks effectively orphaning the service giving the impression that all is well.

I think one thing to check is if the supervisor/launcher are gracefully terminated, do they remove the PID files. It seems like they should but seems like they do not.

If they are forcefully terminated it makes sense that the PID file would remain. So we need a way beyond just seeing if the pid is alive to ensure that the actual service is running.

**Comment by mwrock** [comment]
It looks as though we indeed make an effort to remove the pid file on service stop. If I explicitly `hab svc stop`, I see that the file is deleted. However if I stop the windows service, the pid file remains.

**Comment by ericcalabretta** [comment]
@mwrock is the re-attach logic used in other circumstances? Like when hab-sup or the launcher is upgraded/restarted to keep the processes running during those actions? 

We could add additional identifying info so it's PID + something else to ensure we're re-attaching to the right thing. I'm also struggling to determine when the re-attach logic comes into play. 

The end result is we'd want the system, supervisor, or launcher to be able to gracefully or ungracefully shutdown/restart & still have Habitat put services under management in a good state.

**Comment by mwrock** [comment]
@ericcalabretta this should (I still need to do a bit more investigation when I attack this issue in earnest) only be an issue when forcefully terminating the launcher. I agree we need additional metadata beyond the PID to properly identify the service for reattachment.

There are really 2 things that need to be addressed here:

1. Fix the issues with graceful shutdown to properly clean the PIDs
2. As mentioned above, ensure that the PID file is truly associated with the service being started

@jmassardo as a work around until this is properly fixed, a user could/should delete all PID files prior to supervisor shutdown or reboot.

**Comment by christophermaier** [comment]
It should be noted that for the workaround, you would only want to remove the PID files before you start the Supervisor *only* if it shut down because it was forced. 

*Do not* remove PID files if the Supervisor is coming back up because it is updating itself. The PID files are how it figures out what services it was watching before.

I have ideas on how we might be able to remove PID files altogether, but it still needs a bit of planning.

**Comment by mwrock** [comment]
This should be addressed with #5954 and #5908

**Comment by mwrock** [comment]
also see final comment of #6986 for details.

**Comment by christophermaier** [comment]
Closing this, since it should be addressed by https://github.com/habitat-sh/habitat/pull/7214; feel free to reopen if that's not the case.
