### ISSUE TITLE
Move website completely onto Buildkite

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#6987]
Currently, website deploys are handled in Travis when a change that affects the website merges to master. However, we also have Expeditor pushing changelog changes to master right after our code merges. We have auto-cancellation set up in Travis, which kills a running job if a new merge comes in while it's running. Thus, Expeditor is effectively canceling all our website deploys. We need to remove our website update logic from Travis and put it into Buildkite where it belongs.

**Comment by kagarmoe** [comment]
Examples:
[Chef-web-docs Makefile](https://github.com/chef/chef-web-docs/blob/master/Makefile)
[Chef-web-docs .expeditor directory](https://github.com/chef/chef-web-docs/tree/master/.expeditor)

[A2 Makefile](https://github.com/chef/automate/blob/master/components/automate-chef-io/Makefile)
[A2 docs .expeditor](https://github.com/chef/automate/blob/master/.expeditor) 
[A2 specific config lines](https://github.com/chef/automate/blob/master/.expeditor/config.yml#L41) (Notice that there are separate configs for docs from data files that need synced and for release notes)

**Comment by krasnow** [comment]
Acceptance criteria
* We can update the docs on the website.
