### ISSUE TITLE
Encrypted transport between Automate and the Supervisor

### ISSUE THREAD

**Issue by krasnow** [habitat-sh/habitat#7017]
## What problem are we solving? 
I want the event information from the supervisor to be encrypted when it is sent to Automate

## Objective and key results. 
We can GA the Applications view in Automate, customers will install it in production

## Acceptance criteria.
* The data is encrypted via TLS
* There is documentation on how to configure (find the cert, put it in the right directory)

## Dependencies and blockers. 
none

## Out of scope. 
Making supervisor config easier
Use of NATS streaming

## Open questions
none

**Comment by chefsalim** [comment]
User story card - https://github.com/habitat-sh/habitat/issues/7019
