### ISSUE TITLE
Use new custom cert model for NATS connections

### ISSUE THREAD

**Issue by chefsalim** [habitat-sh/habitat#7019]
As a user of Habitat, I want my supervisor events that are sent to Automate to be encrypted

Acceptance criteria;
1. Connecting to a NATS server should require SSL
2. The SSL cert should be retrieved in a manner consistent with the http-client (eg, leverage /hab/cache/ssl, etc)
3. The TLS support should work across all supported platforms
4. There should be an end-to-end and/or unit test

**Comment by gpeers** [comment]
For anyone taking on this issue, here's what needs to be done:
- NATS client must check the SSL_CERT_FILE env var for certs according to (to be continued...)

**Comment by davidMcneil** [comment]
Closed by #7120
