### ISSUE TITLE
Panic from health-check on startup

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#7020]
We have a system with many services, some of which fail repeatedly on start up.  While the service is failing, we occasionally see the following error message in the logs:

```
thread 'health-check-authz-service.default' panicked at 'Couldn't send oneshot signal from HookRunner: receiver went away: (Some(ProcessOutput { standard_streams: StandardStreams { stdout: Some(""), stderr: Some("critical: context deadline exceeded\n") }, exit_status: ExitStatus(ExitStatus(512)) }), 5.0371276s)', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

As far as I can tell this isn't causing a problem, but perhaps a more user-friendly error message might be appropriate here if this is behavior that can be seen in normal operation.

**Comment by mwrock** [comment]
This looks related to #7136

**Comment by mwrock** [comment]
closing this as #7128 captures the root of the issue.
