### ISSUE TITLE
Design spike: Config file for supervisor

### ISSUE THREAD

**Issue by krasnow** [habitat-sh/habitat#7033]
Acceptance criteria:
* Define breakdown of epic

**Comment by davidMcneil** [comment]
One approach would be to transition to using the [`structopt`](https://github.com/TeXitoi/structopt) crate. `structopt` uses `clap` under the hood, but handles argument parsing by defining a single struct and then making heavy use of macros to define how the structs fields map to subcommands, arguments, flags ...

How does this help with a config file? We could use `serde` to define `Serialize` and `Deserialize` on the struct and we would be able to read and write this struct to file, network, or stdout (#7225) nearly for free. It would also make supporting a variety of formats (toml, json, yaml ...) easy (for better or worse).

I think this approach would have another pretty cool benefit. Wrapping the singelton instance of the struct in an `Arc<RwLock<T>>` would give us a safe and easy way to allow dynamically updating the config while the supervisor is running. This has been requested for parts of the config (#6864) This would no longer require a special case. The entire config could be dynamic.

A big negative of using `structopt` would be if their macro language did not allow us to do everything we wanted to do and would be possible by using `clap` directly (I have used `structopt` for pretty complicated interfaces but am not sure what the exact restriction are). There are [plans](https://clap.rs/2019/03/08/clap-v3-update-structopt/) to make `structopt` a native part of `clap`.

It would require a lot of work to port the existing interface, but an incremental transition to `structopt` should be possible. Honestly, I think any addition of a config file will require significant changes to the way the cli code works.

**Comment by christophermaier** [comment]
@davidMcneil That sounds like a really fruitful avenue to pursue. I've long wanted a way to be able to dynamically update a number of aspects of how the Supervisor runs that shouldn't require restarts (e.g., where Supervisor updates come from, if the Supervisor should auto-update at all, etc.)

If this gets us closer to that world, then I think it's definitely worthwhile!

**Comment by davidMcneil** [comment]
See more design work [here](https://github.com/davidMcneil/unified-dynamic-rust-app-config).
