### ISSUE TITLE
Feature: hab svc load should allow to stand up the the same pkg_ident as many as times as you want

### ISSUE THREAD

**Issue by bdangit** [habitat-sh/habitat#7034]
## Scenario

```
hab svc load myorigin/myapp
hab svc load myorigin/myapp
hab svc status
```

I should expect to see myapp loaded twice.  Instead, I only see myapp once.  

## Why we should?

Just like any other "container" tech, we can spin the same binary as many times but with different configurations.

## Workaround

Don't use hab-sup for "services" that require to be instantiated more times.  Instead just spin up the binaries yourself via `hab pkg exec {pkg_ident} {binary_name}` unsupervised.

**Comment by christophermaier** [comment]
This seems like it would require a large reworking of the internals of the Supervisor to accomplish. Can you provide a concrete example of something that would require this?

**Comment by mwrock** [comment]
going to close for now but feel free to reopen and add details.
