### ISSUE TITLE
Sidebar nav: Fix to work with sub-directories

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#7070]
As part of improving the Habitat docs search, we need to create sub-directories of short pages instead of long pages with many headers.

We need to change the sidebar to work with sub-directories and pages. The sidebar we have now uses Zurb's Magellan with Foundation to create a smooth side-bar experience for long pages.

- [ ] The top-level header unfolds to show the nav items when I select it
- [ ] The top-level header folds back up and hides the nav items when I select it again
- [ ] The active page is highlighted in the navigation
- [ ] The navigation remains visible (pegged in place) even if I scroll down a long content page.

**Comment by SEAjamieD** [comment]
Speaking with @kagarmoe later this week on possible larger upcoming changes to these docs

**Comment by SEAjamieD** [comment]
Closing this card because the Habitat Middleman site is being moved into maintenance mode.  The team is now starting the move to Hugo early so this work in no longer necessary.
