### ISSUE TITLE
Allow multiple service groups in binds of the same name

### ISSUE THREAD

**Issue by predominant** [habitat-sh/habitat#7085]
The best way to explain this is with a scenario.

I'm launching a prometheus server. It should consume any habitat service that I specify, as long as it has a metric-http-port exported.

I want to be able to specify multiple service groups for the same bind name:

```
hab svc load \
  core/prometheus \
  --bind targets:haproxy.pool1 \
  --bind targets:haproxy.pool2 \
  --bind targets:mysql.default \
  --bind targets:nginx.pool1 \
  --bind targets:nginx.pool2
...
```

or, alternatively:

```
hab svc load \
  core/prometheus \
  --bind targets:haproxy.pool1,haproxy.pool2,mysql.default,nginx.pool1,nginx.pool2
```

Allowing this would simplify standard interfaces like how promtetheus works, and how it loops binds to gather IPs and port configuration with a standard expectation on metric path/gathering.

The end result would be a single "targets" bind, with members from all the specified service groups, in no particular order.

**Comment by christophermaier** [comment]
@predominant Interesting idea! Might take a bit of internal reworking to achieve, but could be a useful tool for people.

I wonder if it would be worth differentiating between binds that should only attach to a single service group (maybe like a database) vs more open binds like what you describe?

**Comment by predominant** [comment]
@christophermaier I think what makes sense here is to permit multiple service groups to be bound to a name, as long as they meet the exported variable contract / requirement.

Any binding needs to handle what happens in the case of a single bind, or multiple binds. This is up to the plan author to deal with intelligently. In the case of a single point of failure database, currently most people would just use `bind.servicename.first....`.

But in the case of Cassandra, you can bind one node to many for the cluster. Thats a database that understands, and uses multiple nodes. Applications binding to the cluster can be provided with one or multiple nodes (doesn't matter) and it communicates with the cluster.

I think every bind should be treated, and templated around as if it has `n` binds, never assume `1` bind member.

**Comment by christophermaier** [comment]
@predominant Yeah... I guess I'm wondering if there would need to be some additional affordances provided to deal with multi-binds. Right now you can bind to a single service group, which can have multiple members, but this would be adding another layer on top of that, by having multiple service groups.

But if distinguishing between groups in that way doesn't make sense (as it seems not to in your Prometheus example), then maybe not.

It'd be interesting if anyone has concrete usecases that might be served by binding multiple service groups, but still needing to distinguish between them somehow; there may not be any :thinking:

**Comment by predominant** [comment]
@christophermaier I think if you need to distinguish between service groups, you need to use a different named bind.

We *should* be considering a bind as "any service that meets the contract requirements of the bind", beyond that (service name, group name, application name, environment name... ) we shouldn't care what it is.

Bind contracts declare exactly what is required to identify a service as compatible. In the example of HAProxy:

```
pkg_binds=(
  [backend]="port"
)
```

Anything that `pkg_exports` a `port` is a valid `backend` as far as HAProxy is concerned.

**Comment by predominant** [comment]
This issue still affects me.

**Comment by predominant** [comment]
This issue still affects me.
