### ISSUE TITLE
Allow incremental changes to service bindings

### ISSUE THREAD

**Issue by predominant** [habitat-sh/habitat#7086]
Again, with an example.

As someone managing long running services, I would like to be able to manage service bindings in an incremental fashion. This would be extremely helpful when plans are built with optional binds, and super-double-extra useful when combined with the request in #7085 

```
hab svc bind-add prometheus.default targets:redis.cluster1
hab svc bind-add prometheus.default targets:minio.default
```

Additionally, to remove:

```
hab svc bind-remove prometheus.default targets:redis.cluster1
```

There are a couple of cases where this becomes interesting:

1. if #7085 is implemented, it would allow in-place expansion of service binding to grow the binds between along running service and new members.
2. it would allow the initial deployment of config-based binds (optional binds, backed by default config values), and a simple transition to habitat-based supervised services that can be bound later.

A bind would likely result in a service restart. This is what we have to do currently, but its a manual stop / reload of service. This change would improve administrator burden.

**Comment by christophermaier** [comment]
This seems to fit in with a broader refactor I'd like to do that would make changes to different aspects of how the Supervisor manages individual service _not_ require a restart.
