### ISSUE TITLE
Update CLI style guide to include writing style for commands

### ISSUE THREAD

**Issue by apriofrost** [habitat-sh/habitat#7095]
## Problem
We have an existing [CLI style guide](https://forums.habitat.sh/t/habitat-cli-ux-principles/628) for the general UX design principle. However, we haven't been strict about the writing style we use to describe the command, its definitions, usage, as well as the error messages. 
## Proposed Solution
Update the CLI style guide to include:
-  Use of verb tenses
-  Upper- and lower-case use in the text
- Translation of acronyms
- Translation or conversion of units of measure
- The sentence pattern to use to describe a command: its definition, flags, options, and arguments
etc.

**Comment by kagarmoe** [comment]
A couple of style guide resources:

Error message style guide:
https://docs.microsoft.com/en-us/windows/win32/debug/error-message-guidelines

Documenting command-line syntax:
https://developers.google.com/style/code-syntax
