### ISSUE TITLE
Investigate moving releases to 'habitat' origin

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#7132]
Prior to a 1.0 release, it would be worth investigating the level of effort it would take to move the `habitat` packages (`hab`, `hab-sup` etc.) from the `core` origin to the `habitat` origin.  

The primary driver behind this is that there currently exists a possibility of an accidental promotion of an untested artifact, as the `hab-*` packages are built as part any build generated by `core-plans` and would be eligible for promotion as part of the build group.  This is somewhat mitigated by the fact that  `hab` and `hab-sup` only depend on the base plans which change infrequently, however packages like the exporters have a wider range of deps and are more likely to see an accidental promotion.  

One question that would need to be answered as part of this is that there is an unknown amount of assumption on packages coming from the `core` origin baked into our code. We'd need to determine what and where those assumptions are. 

Another question that would need to be answered is the migration path for existing services from `core/hab-sup` to `habitat/hab-sup`.  This in particular feels like something that should be done pre-1.0, if we are going to make this change.

**Comment by krasnow** [comment]
The scope of this work is to define the plan and create issues to execute the plan.

**Comment by smacfarlane** [comment]
This issue is superseded by #7383
