### ISSUE TITLE
Add Supervisor-only Docker images as release artifacts

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7161]
The only currently-supported way to get Habitat into a container image is to export an existing service using `hab pkg export docker`. While you can invoke this kind of container with arguments that will cause it to not actually run that service, it's not really intuitive. Furthermore, a Supervisor-only container is very useful for testing scenarios, as well as for use in Kubernetes with the so-called "bastion pattern" (documented in this currently-open-at-the-time-of-writing PR: #7144).

Creating a Supervisor-only container is not difficult (I'm sure many exist in the wild), but having the team provide such an artifact would be useful for everybody.

Containers for each of the currently-supported platforms (`x86_64-linux`, `x84_64-linux-kernel2`, and `x86_64-windows`; the Supervisor doesn't run on `x86_64-darwin`) would be needed, and should be built in our release pipeline with all our other release artifacts.

**Comment by smacfarlane** [comment]
Do we need to include `x86_64-linux-kernel2`?  Docker, from what I recall, requires a 3.x or newer kernel to run. If you're moving your apps into Docker, then you _should_ already be on a system that will run `x86_64-linux`.  

The containers we do provide for `x86_64-linux-kernel2` are for build compatibility, but I would generally expect the apps to run on metal or virtualized systems. 

I do see the use case for our own testing as part of the release process though.

**Comment by christophermaier** [comment]
Hah, that's an excellent point @smacfarlane :sweat_smile: 

Maybe just `x86_64-linux` and `x86_64-windows` for now.
