### ISSUE TITLE
Hab Pkg Build - set_buildtime_env function issue?

### ISSUE THREAD

**Issue by y-me-y** [habitat-sh/habitat#7190]
- Initial Slack post: [Original Habitat Slack Message](https://habitat-sh.slack.com/archives/C0VBY57UP/p1573585811277200)

- [x] The OS (including version) where you are running any of the Habitat commands.
   - __OS:__ Docker Linux Studio and Sles 12 Sp3 chroot studio
   - __HAB BINARY:__ `0.83.0` and `0.88.0`
   

- Issue with set_buildtime_env _maybe_

   Inside my plan.sh I am using the `do_setup_environment` and `do_build` functions

   ```bash
   do_setup_environment () {
     GOPATH="/hab/cache" 
     set_buildtime_env -f GOPATH "${GOPATH}"
   }
 
   do_build() {
     pushd "${pkg_build_dir}" || exit 1
     go build
     local code=$?
     popd || exit 1
     return ${code}
   }
   ```

   If I don’t export GOPATH - the enviroment of the do_build function isn’t properly updated with the GOPATH. _added attach to grab info_

   ```bash
   [44] habitat_exporter(do_build)> go env | grep PATH
   GOPATH="/root/go"
   [45] habitat_exporter(do_build)> env | grep GOPATH
   [46] habitat_exporter(do_build)> echo $GOPATH
   /hab/cache
   ```

**Comment by mwrock** [comment]
Closing this as it looks to have been fixed.
