### ISSUE TITLE
Trigger documentation update after Habitat release

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7194]
We have a few `Makefile` targets for updating our auto-generated documentation, namely
```sh
cd www
make cli_docs
make template_reference
```
We should have a post-release pipeline step that runs these steps and creates a PR for the changes. Ideally, each set of changes would be a separate commit in the PR.

The pipeline stage would be successful if the PR was submitted. It should _not_ wait for the PR to be merged. This allows a human to inspect the PR and make any changes, should that be necessary.

It might be interesting to additionally post the URL of the resulting PR back into our team's Slack channel to ensure that everyone sees it.... that's not strictly necessary, though.

**Comment by scotthain** [comment]
Ideally later in the process, this should be deployed as a "unit" and promoted deployed to the acceptance/staging environments along with the current release so it can be viewed in that way.
