### ISSUE TITLE
Automate bumping of nightly Rust version for tests after a Habitat release

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7198]
For a subset of tests, we run `cargo test` using a nightly version of Rust. After each release (only because that's a convenient time to do it), we bump the version of Rust to the latest available nightly (that is, we update the contents of [RUST_NIGHTLY_VERSION](https://github.com/habitat-sh/habitat/blob/master/RUST_NIGHTLY_VERSION).

This change should then be submitted as a new PR from a new post-release pipeline stage. The stage would be successful if the PR was submitted. It should not wait for the PR to be merged. This allows a human to inspect the PR and make any changes, should that be necessary, which may be the case, if the latest nightly Rust introduces complications (e.g., something breaks on Windows, which has happened in the past).

It might be interesting to additionally post the URL of the resulting PR back into our team's Slack channel to ensure that everyone sees it.... that's not strictly necessary, though.

**Comment by jeremymv2** [comment]
Closed by #7274
