### ISSUE TITLE
Document saving license file on *nix & Windows

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#7227]
Document on chef/chef-web-docs & habitat.sh/habitat

From Slack notes:
1. Hi, I was looking at https://docs.chef.io/chef_license_accept.html#habitat, and didn't see where to put the file for license acceptance on windows. What's the path to use for that?
2. c:\hab\accepted-licenses\habitat (edited)

**Comment by mwrock** [comment]
I think the docs are ok here since the file location is the same across all platforms. Closing for now but feel free to reopen if more clarity is needed.
