### ISSUE TITLE
Allow the Supervisor to know what version of the Launcher it is working with

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7228]
As we approach 1.0, preserving backward compatibility becomes more important. Depending on the nature of new features being added, either to the Supervisor, the Launcher, or both, it may be necessary for the Supervisor to know what version of the Launcher it is talking to in order to modify its behavior. For instance, if such a capability existed when #7214 was written, we could have simplified the implementation a bit (see [this discussion](https://github.com/habitat-sh/habitat/pull/7214#discussion_r347949351) for more).

The Launcher already knows what version of the Supervisor it is running, and can thus modify its behavior if needed; this is just handling the inverse.

**Comment by mwrock** [comment]
This was implemented in #7840 which added a `version()` to the launcher protocol so that the supervisor can query the version of the launcher it is talking to.
