### ISSUE TITLE
Allow default.toml to have template variables

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7268]
When I have a service with yaml/toml/json config I can create for example `config/config.json` as follow:
```
{{toJson cfg}}
```
In default.toml

```
[foo]
bar = 123
# this does not work and passed as text
data_path = "{{pkg.svc_data_path}}"
# And current workaround is to hard code the path
data_path = "/hab/svc/my-package/data"
```

Hard-coded path is not a big problem because there is no way to change services' path, but in wrappers it can lead to issues.

This issue is not critical, but "nice to have".

**Comment by sirajrauff** [comment]
Had this just crop up for me. Wanting to use `{{pkg.svc_path}}` or even `$pkg_svc_path` inside default.toml due to my config file being:
```
{{toYaml cfg}}
```
due to how YAML works, however, I was able to get away with the following:
```
{{toYaml cfg}}

more-data:
  data:   {{pkg.path}}
```
But here's hoping I can include that inside the actual .toml file in the future, as I would love to be able to say ignore the configuration templates entirely, everything is translated directly from the values file. This would then also remove the confusion/possibility of duplicate handling, etc.

**Comment by themightychris** [comment]
there was another conversation somewhere that was another route to achieving this -- a new `pre-config` hook of some sort that could take as JSON STDIN the full config template data calculated by habitat (defaults + current config + injected config) and then output a transformed JSON structure for what gets sent to the config templates for rendering

Such a capability could handle dynamically filling in any blanks, covering this use case, but then also handle arbitrarily-complex logic or data organization to fill in for the limitations of handlebars

**Comment by jsirex** [comment]
Up on this

**Comment by sirajrauff** [comment]
Still an issue

**Comment by themightychris** [comment]
I think pluggable template renderers and/or a config hook offer better routes to this. Does anyone feel strongly about templating default.toml being a better approach?

I do a lot of merging default.toml files together when I build config plans so the idea of default.toml being more than just data gives me a lot of pause. Plus handlebars is pretty much the least convenient way possible to introduce some dynamic behavior into structured data

I'm wondering if a better way to maybe start getting traction on this could be to rewrite it into proposing a config hook?
