### ISSUE TITLE
/dev/shm is not mounted in chroot studio

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7272]
When running in linux chroot studio there is issue with /dev/shm (which is actually hasn't mounted).
For example, postgresql12 declines to start because of could not open shared memory segment "/PostgreSQL.53946557": Permission denied
If I mount it inside the studio it seems to work.
Should it be mounted by studio by default - so it is a bug :bug: or there is a purpose to NOT mount /dev/shm

Steps to reproduce:
```
if /hab/pkgs/core/hab/0.90.6/20191112141314/bin/hab studio run grep /dev/shm /proc/mounts >/dev/null; then echo "all is ok"; else echo "/dev/shm has not mounted"; fi

**Comment by krasnow** [comment]
@smacfarlane - Can you take a look at this and validate if it is indeed a bug?

**Comment by jsirex** [comment]
There only mention about shm: https://github.com/habitat-sh/habitat/blob/master/components/studio/bin/hab-studio.sh#L440-L441
So no code related to mount at all

**Comment by jsirex** [comment]
Some software use /dev/shm (like postgresql12) and it fails during startup.
This directory is not writable. And its correct, because it is bad idea to write directly onto fs instead ram.

**Comment by smacfarlane** [comment]
I don't know that this is necessarily a bug, but I think it is something we should look into fixing.   

The primary purpose of the studio is building software, but it also provides a convenient place to run packages as you are developing them.  I would like to do some additional reading and testing to ensure we're not going to affect the former by making this change, and some research to determine if it was intentionally left out.  I'm fairly certain we're ok, but out of an abundance of caution I'd like to make sure. 

In the mean-time, are you able to use the docker studio for running services when testing?

**Comment by jsirex** [comment]
Docker mounts `/dev/shm`, so yes. But I'm using linux and native studio.
