### ISSUE TITLE
bulkupload takes too long identifying package origins

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat#7275]
`hab pkg bulkupload` takes into account the package origins and then queries BLDR for those origins in order to determine if they need to be created first or not.

This operation is very expensive since it uses `PackageArchive::new()` on each artifact in the download directory to render a `PackageIdent` and determine the pkg's origin.

We need to make this a more efficient operation as it can consume a lot of time for large numbers of package sets. Also, we can provide the user feedback as origins are being read in.

**Comment by jeremymv2** [comment]
A possible solution for optimization of origin discovery is to read the list of origins from the pkg signing keys as opposed to the packages.

**Comment by markan** [comment]
It's a little bit of scope creep, but it may be worth looking again at the idea of having download generate a manifest. #6963 was one approach, but maybe something simpler would work.

**Comment by jeremymv2** [comment]
Also, this seems relevant to optimizing `PackageArchive::new()` https://github.com/habitat-sh/habitat/issues/5153
