### ISSUE TITLE
Remove the HAB_FEAT_EVENT_STREAM feature flag

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7294]
This will also require adding a cli option to enable the event stream.

**Comment by ericcalabretta** [comment]
@davidMcneil Would this require an additional flag to enable or would specifying the EAS flags like URL/Token be enough to enable the event stream? 

What will we do if customers are still feeding the old flag at the CLI? Wondering the impact to deployment processes, not a big deal either way.

**Comment by davidMcneil** [comment]
@ericcalabretta I will have to experiment some, but I agree this should not require a new flag.
