### ISSUE TITLE
Question: is there any plan to publish butterfly as a crate?

### ISSUE THREAD

**Issue by balajijinnah** [habitat-sh/habitat#7317]
Hi folks,

We are planning to use butterly in our project. Is there any plans to publish butterfly as crate to crates.io?

Thanks

**Comment by raskchanky** [comment]
Hi @balajijinnah 

We don't have any plans to publish butterfly to crates.io at this time.  The implementation details are highly coupled to the habitat project, and making them generic enough for general use hasn't been a priority so far.  It's possible those priorities will change in the future, but I would wager that won't happen any time soon.
