### ISSUE TITLE
Remove the `--application` and `--environment` flags on `hab sup run` and `hab svc load` 

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7339]
The `--application` and `--environment` flags on `hab sup run` and `hab svc load` have been deprecated. After a few releases they can be removed.

**Comment by davidMcneil** [comment]
See #7335 for the deprecation work.

**Comment by mwrock** [comment]
still relevanr

**Comment by mwrock** [comment]
this is done
