### ISSUE TITLE
PID file permissions are wrong

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7351]
I can't find any code related to set PID file permissions. So if service is running under the `hab` user I unable to read `PID` from `reconfigure` hook.

```
-rw-------  1 root root   5 Jan 21 11:30 PID
```

```
my-elasticsearch.default hook[reconfigure]:(HK): cat: can't open '/hab/svc/my-elasticsearch/PID': Permission denied
```

**Comment by stevendanna** [comment]
This was likely introduced in https://github.com/habitat-sh/habitat/pull/6738

Since the AtomicWriter uses more restrictive permissions by default. (Similar to https://github.com/habitat-sh/habitat/issues/6298)
