### ISSUE TITLE
Upgrade to time 0.2

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7353]
The `time` crate has substantially changed between 0.1 and 0.2. This [issue](https://github.com/time-rs/time/issues/197) describes some of the changes. The change that most impacts us is the removal of [`TimeSpec`](https://docs.rs/time/0.1.42/time/struct.Timespec.html). This is a fairly simple struct so we should be able to replicate its functionality. 

See this [issue](https://github.com/time-rs/time/issues/201) for help in converting format strings.

**Comment by christophermaier** [comment]
![](https://media.giphy.com/media/3iUMl1Fh6HRew/giphy.gif)
