### ISSUE TITLE
Default options for `hab setup` lead to multiple dead-ends for first-time users

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#7361]
A first-time user will not have on hand, and doesn't need for their first build, several tokens that `hab setup` will prompt them for if they accept default options:

- `Connect to an on-premises bldr instance? [**Yes**/no/quit]`
  - Explained well enough
  - Not needed to start though, and you can come back when you want to switch to one
  - Not practical that a user could set this up during `hab setup`
  - Should default to **no**
- `Set up a default Habitat personal access token? [**Yes**/no/quit]`
  - Explained well enough
  - Not needed to start though, and you can come back when you want to switch to one
  - Enough information is provided that a user could set up a token while at the prompt
  - Defaulting to **no** would provide the least first-run friction, but defaulting to **yes** might provide the least first-publish friction. Seems like a priority call for product leaders
- `Set up a default Habitat Supervisor CtlGateway secret? [Yes/no/quit]`
  - No explanation offered
  - Not needed to start though, and you can come back when you want to switch to one
  - Not practical that a user could set this up during `hab setup`
  - Should default to **no**
  - Should have a clear explanation

In each of these cases, accepting the default of **yes** leads to a prompt the user may not be able to answer. Forcing them to decide to brave terminating `hab setup` and starting over.

This provides a bad experience for first-time users, and is a regression from previous releases since the additions of the on-premises bldr and CtlGateway prompts. In my experience referring users to try Habitat, I've found them getting frequently hung up here and needing to come back for guidance on how to get through it (if not simply deferring the entire effort)

**Comment by mwrock** [comment]
I have to agree. I find my self almost always specifying "no" to most of these when testing/demoing habitat.

**Comment by eeyun** [comment]
Same agreement here. I'm sure it's useful to a subset of users but "default" behavior should always look like the common public configuration.
