### ISSUE TITLE
Windows Builds Behave Differently than Linux Builds

### ISSUE THREAD

**Issue by sirajrauff** [habitat-sh/habitat#7397]
Habitat builds on Windows currently are inconsistent when it comes to context during do_build/Invoke_build.

On Linux, many plans such as [sample node app](https://github.com/habitat-sh/sample-node-app/blob/master/habitat/plan.sh) are defined such that do_build() expects to be called from the parent of the `habitat/` directory (i.e. in this case, the repository root); this works due to do_build being called specifically at the ["source path"](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L1831-L1833) which is set from the [context](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L2384-L2391) given to the [build function](https://github.com/habitat-sh/habitat/blob/master/components/plan-build/bin/hab-plan-build.sh#L345-L347). This means that if you are calling `build` from a different directory, passing in the repo root works:
```
$ tree -L 2
.
└── parent-directory
    └── sample-node-app

2 directories, 0 files

$ hab pkg build parent-directory/sample-node-app
hab pkg build parent-directory/sample-node-app
   hab-studio: Importing 'sirajrauff-public' secret origin key
   ...
   sample-node-app: I love it when a plan.sh comes together.
   sample-node-app:
   sample-node-app: Build time: 0m44s
```
If, however, you pass in the location of the `habitat/` subdirectory, it fails:
```
$ hab pkg build parent-directory/sample-node-app/habitat
   hab-studio: Importing 'sirajrauff-public' secret origin key
   ...
   sample-node-app: Installing
cp: cannot stat 'node_modules': No such file or directory
cp: cannot stat 'public': No such file or directory
cp: cannot stat 'routes': No such file or directory
cp: cannot stat 'views': No such file or directory
cp: cannot stat 'package.json': No such file or directory
cp: cannot stat 'app.js': No such file or directory
cp: cannot stat 'index.js': No such file or directory
   sample-node-app: Build time: 0m17s
   sample-node-app: Exiting on error
```
This can be [circumvented](https://github.com/Indellient/chef-conf-sample-node-app/pull/2) by making use of `PLAN_CONTEXT` to map the files relatively (assuming the working directory when entering the studio is an ancestor of the required files, as this is what gets mounted). 

On Windows, however, this is not the case. Instead, it seems to assume  `pkg_source` is set to a ZIP file and tries to `Push-Location` to [`$HAB_CACHE_SRC_PATH\$pkg_dirname`](https://github.com/habitat-sh/habitat/blob/master/components/plan-build-ps1/bin/hab-plan-build.ps1#L1013-L1014). This means that if the same plan as given above is [converted to Powershell](https://github.com/ShuttleOps/sample-node-app-windows/blob/master/habitat/plan.ps1), it fails. Once again, this is not necessarily a problem if the location is set [relative to $PLAN_CONTEXT](https://github.com/ShuttleOps/sample-node-app-windows/pull/1/files).

This being said, it would be preferable if the context [given to the build](https://github.com/habitat-sh/habitat/blob/master/components/plan-build-ps1/bin/hab-plan-build.ps1#L3) which is used as the plan context [1](https://github.com/habitat-sh/habitat/blob/master/components/plan-build-ps1/bin/hab-plan-build.ps1#L62),[2](https://github.com/habitat-sh/habitat/blob/master/components/plan-build-ps1/bin/hab-plan-build.ps1#L1560) was used in `Invoke-BuildWrapper` to be consistent with Linux.

**Comment by mwrock** [comment]
Definitely a bummer that #2074 was not implemented for both platforms. Thats likely because at the time windows support was extremely experimental.

I totally agree that both linux and windows builds should be consistent in this regard. One thing we will need to be careful about here is the risk of breaking plans that depend on this different context.

**Comment by sirajrauff** [comment]
@mwrock do you think it might make sense to use `PLAN_CONTEXT` as the do_build() context if `pkg_source` is not defined, otherwise leave it as it is?

**Comment by mwrock** [comment]
There are several plans that copy `$PLAN_CONTEXT` over to `$CACHE_PATH` as part of the build and then assume that temporary build artifacts are landing there. Personally I prefer the builds to take place outside of my source repo to ensure that it does not get mutated by the build.

**Comment by mwrock** [comment]
While it is possible that changing the windows build to be consistent with the linux build in regards to `SRC_PATH` could break existing builds, it seems that windows builds tend to use absolute paths in `Invoke-Build`, et al. That is based on looking at plan.ps1s in core-plans, the habitat repo and our demo plans.

I'm willing to speculate that there are few plans if any in the wild that this would break and consistency would be good overall so I think we should just duplicate the `SRC_PATH` reasoning in the powershell build.
