### ISSUE TITLE
Use daemon-less container creation in our Docker exporter

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7412]
Our current Docker exporter uses Docker to create images (:tada: _surprise!_ :tada:). This requires a running Docker daemon, which introduces a host of security concerns when trying to build within a container. If we could pivot to using one of the new crop of daemon-less container creation tools in our exporter, we could eliminate these security concerns, allowing things like `habitat/builder-worker` to run in unprivileged containers. 

Some possible tools include [img](https://github.com/genuinetools/img) and [buildah](https://github.com/containers/buildah), among others. While it currently appears that building Windows containers with such tools ranges from extremely difficult to impossible, nothing prevents us from implementing this first for Linux container export; the benefits would still be significant.

**Comment by jeremymv2** [comment]
Here's a great in-depth article covering some of the best in breed tools on this topic along with their security trade-offs: https://www.tngtech.com/fileadmin/Public/Images/BigTechday/BTD12/Folien/Slides_MartinHoefling_PatrickHarboeck_compressed.pdf

**Comment by chefsalim** [comment]
Agreed, the ability to run builder-worker unprivileged could even be a/the main use case to start with.  So the unprevileged Docker export could be a means to an end in addition to being a "good thing".  Going after that use case, we'd want to look at all of the exporters.

**Comment by christophermaier** [comment]
Closed with https://github.com/habitat-sh/habitat/pull/7685
