### ISSUE TITLE
Update API endpoint to contain platforms and connections

### ISSUE THREAD

**Issue by SEAjamieD** [habitat-sh/habitat#7423]
The UI team has run into some issues working on card #1178 https://github.com/habitat-sh/builder/issues/1178 where we do not have the data we need in a manageable format given the current constraints.

An ideal scenario for us would be:
If we use the same endpoint that is currently being used in production `${urlPrefix}/depot/${origin}/pkgs`, some items will need to be added.

If we use the newly suggested endpoint `${urlPrefix}/depot/pkgs/${origin}`, some items will need to be added, the data object will need to be sorted alphabetically, and pagination will need to be fixed.
Here is our ideal object:
```
{
  "range_start": 0,
  "range_end": 49,
  "total_count": 599,
  "data": [
    {
      "origin": "core",          // this is a connected plan that has not been built (no artifacts)
      "name": "7zip",
      "platforms": [],
      "connected": ["x86_64_linux"]
    },
    {
      "origin": "core",          // this is an empty package
      "name": "acbuild",
      "platforms": [],
      "connected": []
    },
    {
      "origin": "core",         // this is a package with artifacts, but connected via windows
      "name": "ruby26",
      "platforms": ["x86_64_linux", "windows"],
      "connected": ["windows"]
    }
  ]
}
```

**Comment by chefsalim** [comment]
Resolved by https://github.com/habitat-sh/builder/pull/1306
