### ISSUE TITLE
provide guidance on http 409 error

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat#7432]
Now that there are [guard rails](https://github.com/habitat-sh/builder/pull/1298) for `hab origin delete`, we need to provide the user some helpful guidance on how to handle a HTTP 409 response when an origin is in use and needs to be cleaned up prior to deletion.

**Comment by apriofrost** [comment]
Share the idea @jeremymv2 and I came up with for the guidance in the error messages. Suggestions and comments are welcome. 😸 
![`hab origin delete` activity flow (1)](https://user-images.githubusercontent.com/9401459/74367204-524dac80-4d86-11ea-9d4b-3e7c954c791a.jpeg)
