### ISSUE TITLE
Introduce feature flag to toggle named-pipe based health checks on windows

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#7464]
This is related to research conducted in #7439. In an environment with many health checks (~15 services), having a `pwsh` process running for the lifetime of the service increases total memory overhead by 35MB per service which is prohibitive in a  large constrained environment.

For now we want such users to be able to run on the older model where a health check spawns a `pwsh` process only for the duration of the health check. While this has proven to result in CPU spikes, such spikes can be mitigated by providing different health check intervals per service.

**Comment by gscho** [comment]
@mwrock I was under thee assumption that the named pipe powershell process was used for all services and there wasn't one named pipe process per service. I'm guessing I was mistaken?

**Comment by mwrock** [comment]
right. We only use named pipes for health checks.
