### ISSUE TITLE
hab pkg download with seedfile exception if package not in channel

### ISSUE THREAD

**Issue by drakoswraith** [habitat-sh/habitat#7498]
Feature/functionality request

I setup a sync script that would work for backups of packages from a given channel, or to sync a downstream hab depot from a primary on-prem depot.

To do that, i was leveraging the newer hab pkg download functionality with seed files, by dynamically populating the seed file with the results of hab pkg search: 
```
hab pkg search ORIGIN > pkg_list.txt
hab pkg download --file pkg_list.txt ....
```
hab pkg search will include packages that are in development, and may not be promoted to a given channel.
hab pkg download will throw an exception and exit if it attempts to download a package that does not exist in the specified channel.

Consequently, if a package is under initial development, and has never been promoted to the channel i am syncing, the process fails.

I'd like to suggest these improvements:
1. update "hab pkg search" to allow specifying a channel requirement
2. update "hab pkg download" to have a flag to ignore missing packages

Either would solve my use case, but i think both would improve the overall functionality of the tool. Without either of these, i would require fairly complex logic to determine which packages actually existed in the channel or more interactive methods of determining packages to sync.

**Comment by smacfarlane** [comment]
Thanks for this feedback @drakoswraith!  We've added a `--ignore-missing-seeds` flag to `hab pkg download` based on this which was included in the latest release.  Note this is slightly different than ignoring missing packages.  This will only ignore package names specified on the cli or in a seed file if it can't expand them to a fully qualified identifier, taking channel into account.  We will still fail if it's unable to download a package, as you wouldn't want to seed a depot with a package that is missing dependencies. 

As for adding channel support to search, we investigated and found that adding channel awareness to search would cause a negative performance impact and have decided not to pursue that.  We do have a channels api that you could use to list packages in a channel.  It's paginated and emits the package names in a different format than `hab pkg search`, so would require a little glue to put together. It's also target aware, so if you're seeding multiple targets (Linux, Windows), you'd need to take that into account. 

`https://<BUILDER_URL>/v1/depot/channels/<ORIGIN>/<CHANNEL>/pkgs?range=0&target=x86_64-linux`
 
```bash
curl "https://bldr.habitat.sh/v1/depot/channels/core/stable/pkgs" | jq 
{
  "range_start": 0,
  "range_end": 49,
  "total_count": 7445,
  "data": [
    {
      "origin": "core",
      "name": "7zip",
      "version": "16.02",
      "release": "20180608191514"
    },...
```

The `?range=` parameter controls the start of the range, and `?target=` sets the target (Defaults to `x86_64-linux`.
