### ISSUE TITLE
Retain service PID files for use by hooks only

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7508]
Removing PID files for services and getting service PIDs directly from the Launcher (the true parent process of the services, and thus the source of truth for this information) is good for overall stability, but it broke an important usecase: users of `reconfigure` hooks need a way to access the PID of a service so they can, for example, send it a signal to reload its configuration files.

While the Supervisor should not go back to using PID files to determine what processes it is monitoring, it should continue to write them out for the benefit of hooks that need them.

See https://github.com/habitat-sh/habitat/issues/6076#issuecomment-588867077

**Comment by mwrock** [comment]
What if we exposed the pid via the `sys` namespace allowing users to access the pid via a handlebar helper?

**Comment by christophermaier** [comment]
@mwrock The `sys` namespace is really more of a Supervisor-scoped thing... it's possible we could find another place for it. Putting the PID file back preserves the old behavior, though, as the path to that file is in the template data already. Whether we eventually expose the data in other ways, we probably need to restore the old interface first.

**Comment by jsirex** [comment]
Instead of sys it can be included in `svc` or `svc_member` structure, so in handlebars I can write something like `kill -1 {{svc.pid}}` or `kill -1 {{svc.me.pid}}`. Anyway, thank you for resurrecting PID file.
