### ISSUE TITLE
Only build Launcher, Windows Service packages when absolutely necessary

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7547]
Currently, we unconditionally build new versions of the Launcher and Windows service for each run through our release pipeline, whether the code in the packages has changed or not. 

It has recently been brought to my attention that the Habitat Chef cookbook always keeps these packages up-to-date on a system, and triggers full restarts of the Supervisor (and thus all its services) as a result. While this is logical and appropriate behavior, our build strategy unintentionally creates a situation where Supervisors and services are needlessly restarting each time we release new packages. We can help to address this by only building new Launcher and Windows service packages when those packages actually change. 

One idea would be to examine whether changes in the incoming commit involve code for those packages; if it does, then build. If it doesn't, take whatever the current stable artifacts are and promote them into the release candidate channel (where a newly-built package would go).

A wrinkle for this would be if a build was triggered, creating a new Launcher package, but the overall release pipeline failed. Without additional logic, this build would effectively be lost, because the next merged PR might not have changes to trigger a new Launcher build. (The same logic goes for the Windows service, of course)

Another wrinkle, albeit a significantly more minor one, would be what happens if a change is a non-meaningful one. Examples of this might be updating documentation comments, or reformatting code. We might like to confirm that we can still build a package, but that doesn't necessarily mean we need to promote it as a new release. Reliably distinguishing between meaningful and non-meaningful changes could be challenging to do in a completely automated way.

Yet another wrinkle: there may not be code changes to the Launcher or Windows service, but there may be updated _dependencies_ that merit a new build. And now, we start to sound like we're re-implementing Builder.... :thinking: 

All this *might* suggest that the Launcher and Windows service are distinct projects, with their own release pipelines and logical flow. The artifacts of such pipelines would need to feed into our overall release process, but in a way that still makes it clear what the collection of packages is that we're ultimately promoting as a release.

**Comment by davidMcneil** [comment]
Two thoughts not sure how feasible they are, but just throwing them out there.

> A wrinkle for this would be if a build was triggered, creating a new Launcher package, but the overall release pipeline failed

If the launcher was versioned separately from the rest of the software, we could use the commit content to increment the launcher version. Then use a difference in versions to determine if we need a rebuild.

> Another wrinkle, albeit a significantly more minor on , would be what happens if a change is a non-meaningful one
> Yet another wrinkle: there may not be code changes to the Launcher

If we had reproducible builds, I think all of our problems would be solved. We could just compare the resulting binaries, correct? No idea how hard that would be in Rust though. Looks like there is some [prior work](https://users.rust-lang.org/t/testing-out-reproducible-builds/9758).

**Comment by mwrock** [comment]
I think breaking the launcher and windows-service is probably the easiest and clearest way forward in my mind.
