### ISSUE TITLE
Non-existent hab user/group results in `Failed to set permissions` error

### ISSUE THREAD

**Issue by fujin** [habitat-sh/habitat#755]
I was missing the hab user/group and trying to run `hab start core/postgresql`. It would be nice to detect this state specifically from other generic failed to set permissions errors.

`hab-sup(ER)[src/error.rs:321:8]: Failed to set permissions`

``` rust
impl From<hcore::Error> for SupError {
    fn from(err: hcore::Error) -> SupError {
        sup_error!(Error::HabitatCore(err))
    }
}
```

**Comment by adamhjk** [comment]
Probably best to build a new error type, and then return it early. That will make the error message useful.

**Comment by adamhjk** [comment]
Another option here would be to use `hab` if it exists, or use `nobody` as a fallback.

**Comment by mike-marcacci** [comment]
Additionally, it would be very useful to if this requirement were documented in:

- [Get Habitat](https://www.habitat.sh/docs/get-habitat/)
- [Set up your environment](https://www.habitat.sh/tutorials/getting-started-setup-environment/)

**Comment by brandocorp** [comment]
Just ran into this issue myself, I had seen the hab user mentioned in the docs. Would it make sense to make this a part of the cli configuration?

**Comment by metadave** [comment]
addressed in https://github.com/habitat-sh/habitat/pull/1050
