### ISSUE TITLE
Augment pkg download to sync arbitrary channel contents

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#7555]
Occasionally, it is desirable to sync the contents of a channel without knowing what packages are in it ahead of time.  

The initial use case is we need to be able to sync the contents of the core-plans refresh channel from the live builder to acceptance. In this case, we know we want everything in the channel to be synced. The requirement of enumerating packages in a seed file means we have extra effort required to maintain an updated list, and there is the possibility of missing an added package.

Longer term, we would like to extend this to the stable channel to ensure the two environments stay in sync.

An additional use case, supported by #7498, is that users may have a single depot that developers work against.  The user would then like to sync the contents of a channel to builder instances that are in geographically diverse locations that their production instances pull from. Developers may add or remove packages as their projects mature, and a seed file could quickly become out of date.

**Comment by mwrock** [comment]
relevant
