### ISSUE TITLE
Add ability to use a user ssh key in the studio

### ISSUE THREAD

**Issue by TheLunaticScripter** [habitat-sh/habitat#7568]
This is more a feature request. Currently, in the Effortless model, we have users who need to make git calls during build to private git repositories or private artifactory repositories. This requires them to modify their code and then pass in a username and secret to the studio. The request is would it be possible to mount the users `.ssh` folder into the studio so that they can use their standard `id_rsa` key pair for git based authentications.

**Comment by mwrock** [comment]
So if you are using a docker based studio (windows or linux) you could do this today with the `HAB_DOCKER_OPTS` environment variabble. Entering a studio (or running a `hab pkg build`) will inject whatever value you assign to that variable into the `docker run`. So on windows you could set it to `$env:HAB_DOCKER_OPTS="--volume c:/users/matt/.ssh:C:/Users/ContainerAdministrator/.ssh"`. On Linux I **think** it would be `export HAB_DOCKER_OPTS="--volume ~/.ssh:~/.ssh"`.

**Comment by TheLunaticScripter** [comment]
Awesome I will test that out thank you.

**Comment by TheLunaticScripter** [comment]
I tested this out and it works great. One gotcha is that when someone is on Windows and they mount the `.ssh` directory for Linux the permission on the key's are not correct. the workaround for this is to mount the directory to `/tmp/.ssh` and then copy the directory to `/root/.ssh`  and then change the file permissions. I think this can be more delightful but I don't think this is a bug in habitat as much problem with Docker on Windows.

Here is the script to change the file permissions after setting the variable to mount `.ssh` to the `/tmp` directory:
```
cp -R /tmp/.ssh /root/.ssh
chmod 0700 /root/.ssh
chmod 0644 /root/.ssh/id_rsa.pub
chmod 0600 /root/.ssh/id_rsa
```

**Comment by christophermaier** [comment]
At the very least, this sounds like a documentation issue, but there may be more we can do in the product to make the experience better for users.

Ping @habitat-sh/docs-team

**Comment by mwrock** [comment]
I am going to close this due to lack of activity. I agree that this is not a habitat bug but a byproduct of mounting accross different platforms. Feels like an edge case best addressed with the workaround mentioned above.
