### ISSUE TITLE
Create alias for hab studio enter -D when users use hab studio enter -d

### ISSUE THREAD

**Issue by ericcalabretta** [habitat-sh/habitat#7578]
This is a quality of life request to make the Hab cli friendlier.

If a user enters `hab studio enter -D` a Docker studio is created, if they mistakenly type `hab studio enter -d` the flag misses and a non-docker studio is created. 

I purpose we create an alias so both the lowercase/capital flags `-d` and `-D` create a Docker studio. 

We could also provide users an error message for `-d` rather than enter a non-docker studio.

**Comment by davidMcneil** [comment]
When run `hab studio enter -d`, it outputs an error message saying `-d` is not a valid options.
```sh
hab-studio-enter 1.5.71/20200318174607

The Habitat Maintainers <humans@habitat.sh>

Habitat Studios - interactively enter a Studio

USAGE:
        hab-studio [COMMON_FLAGS] [COMMON_OPTIONS] enter

ERROR: Invalid option:  -d
```

Do you know what version was producing differnet results?

**Comment by mwrock** [comment]
Just checked and Windows will ignore the `-d` and enter a local studio. So it is a windows specific issue.

**Comment by davidMcneil** [comment]
Gotcha, thanks @mwrock!

**Comment by ericcalabretta** [comment]
I should have specified this was on windows, I tested with a recent version whatever was most current last week 1.5.x.

I didn't realize the behavior was OS Specific, In that case we should make the behavior consistent. and error on `-d` is a fine behavior. I don't like the behavior where you think you're in a Docker studio and you're actually not.
