### ISSUE TITLE
Describe elevated privileges problem when building packages in CI

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#7584]
Users would like to be able to build Habitat packages in their CI systems,  but as they move workloads into Docker or Kubernetes, they find that package builds in containers require those containers be run in privileged mode.   This is not a desired mode of operation for our users.  

In order to discuss potential solutions, it is important to understand what capabilities the Studio provides, why we need it, and why we are running into this issue at a high level.  The output from this issue should be a document describing the Studio and enough implementation detail to facilitate discussion of solutions and drive follow-on design and implementation issues.

**Comment by davidMcneil** [comment]
I know this is an issue to describe the problem and not necessarily come up with the solutions, but just to get my thoughts out there I wonder if [podman](https://github.com/containers/libpod) and specifically [buildah](https://github.com/containers/buildah) could help with this. They allow building and running unprivileged containers.
