### ISSUE TITLE
hab cli subcommand for builder user role management

### ISSUE THREAD

**Issue by jeremymv2** [habitat-sh/habitat#7599]
With the advent of lightweight RBAC in builder (https://github.com/habitat-sh/builder/pull/1378), we need to add a CLI subcommand for users to manage roles within an origin.

**Comment by jamesma100** [comment]
Hey @jeremymv2  I'm interested in this issue, could I work on it? Since this would be my first contribution it would be great if I could have some guidance!

**Comment by jeremymv2** [comment]
@jamesma100 thanks for looking into potential contributions to Habitat!  There's always plenty to be done 😄 

I've begun work on this feature and have a branch that I pushed up:
https://github.com/habitat-sh/habitat/tree/jeremymv2/rbac_subcommand 

I haven't pushed to move forward with the work since I'm waiting on two issues to harmonize first:

- https://github.com/habitat-sh/builder/issues/1367#issuecomment-628802308
- https://github.com/habitat-sh/builder/issues/1403

Finalizing RBAC is definitely on the short list of action items though! cc: @eeyun, @markan, @smacfarlane

**Comment by jamesma100** [comment]
@jeremymv2 Thanks for getting back to me. I'd be happy to help out with RBAC. I see we have the owner, admin, and maintainer roles left to implement. Thanks.
