### ISSUE TITLE
Allow hab-pkg-export-tar to specify name

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7612]
There was the issue https://github.com/habitat-sh/habitat/issues/5924 I decided to close.
But I'm hitting this issue every time again and again when I'm working with exporting to tar.

If you want to automate exporting in a script or ansible/chef it is not possible to reliable guess the tars' name. 

There are couple of issues:
- I cannot specify folder where to export, I must change dir before
- I cannot use mask/glob to automation because of name clash: `habitat-builder-api-*.tar.gz` matches `habitat-builder-api-proxy-*.tar.gz`. 

The only reliable way to detect it: create temporary folder, go into, export there, glob file name, move filename to desired directory/filename, provide back new name.

In docker export we have:
```
    -i, --image-name <IMAGE_NAME>
            Image name (default: "{{pkg_origin}}/{{pkg_name}}" supports: {{pkg_origin}}, {{pkg_name}}, {{pkg_version}},
            {{pkg_release}}, {{channel}})
        --tag-custom <TAG_CUSTOM>
            Tag image with additional custom tag (supports: {{pkg_origin}}, {{pkg_name}}, {{pkg_version}},
            {{pkg_release}}, {{channel}})
```

Probably we need a flag 
```
--tar-name <TAR_NAME>  tar archive name 
    (default: "{{pkg_origin}}-{{pkg_name}}-{{pkg_version}}-{{pkg_release}}.tar.gz"
     supports:  {{pkg_origin}}, {{pkg_name}}, {{pkg_version}}, {{pkg_release}}, {{channel}})
```

**Comment by christophermaier** [comment]
Agreed; no reason not to do this. Should be relatively straightforward to add.

Conveniently, there's already a function for generating the name: https://github.com/habitat-sh/habitat/blob/c1c08bd63b93a785ac353ffe261aee19bdcaa408/components/pkg-export-tar/src/lib.rs#L87-L93

We should, for consistency, do like we do in the Docker exporter, where we treat the provided name as a Handlebars template, with keys like `{{pkg_origin}}` and the like. In that case, the default name becomes a default Handlebars template.

https://github.com/habitat-sh/habitat/blob/d9fa60f35698a4924836ce1bf213e60fc3712ceb/components/pkg-export-docker/src/docker.rs#L448-L455

(Ignore my TODO to myself in that code; I obviously figured it out :sweat_smile:)
