### ISSUE TITLE
Ability to change channel and update strategy without reloading service

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#7635]
We have some customers with an extremely large number of Supervisors where they need to roll out updates in an extremely controlled manner. Rolling updates does not really accommodate this scenario well because it can only update one node at a time and is intended to update a single clustered service and not thousands of applications installations. It makes more sense to leverage channels for phasing in updates at this scale. For instance, you may have several channels: prod-a, prod-b, etc. Then promote packages to these channels one by one where each channel has a larger number of subscribed services.

Some feedback we have gotten is that there is a need to move some services from one channel to another during different deployment cycles. For instance server group A who was in the `prod-a` channel during the last deployment and was the first to deploy, may wand to move to channel `prod-y` in the next deployment. Further, there may be a batch of very "sensitive" applications that require reboots and want to temporarily change their update strategy to `none`.

Unfortunately today changing either channel or update strategy requires a service reload which can be disruptive. What would be great is something like a `hab svc update` where one could edit some service metadata without needing to unload and reload services. Certainly some metadata would be very difficult to update while a service is running like binds or topology. However channel, update strategy and some other properties may be more feasible to update live.

**Comment by davidMcneil** [comment]
Just calling this out as a specific instance of #7243. It would be nice if any solution took into account the possibility of a general approach to dynamic configuration.

**Comment by christophermaier** [comment]
I was coming here to make that exact same suggestion @davidMcneil but you beat me to it :joy:
