### ISSUE TITLE
hab studio version check fails on darwin

### ISSUE THREAD

**Issue by MindNumbing** [habitat-sh/habitat#7638]
Hab studio version isn't recognised as a command on darwin systems.

# Expected Behaviour
When `hab studio version` is run, it will return `hab-studio 1.6.0/20200420202004`

# Actual Behaviour
When `hab studio version` is run, it returns `Unknown Studio Command`

# Steps To Reproduce
Run `hab studio version` on a darwin machine.

# Details
OS Version: macOS Mojave Version 10.14.5
HAB Version: 1.6.0/20200420195152 
Studio Version: hab-studio 1.6.0/20200420202004

## Environment Variables (before entering studio):
- None aside from HAB_AUTH_TOKEN

## Environment Variables (after entering studio):
- HAB_ORIGIN=mindnumbing
- HAB_LICENSE=accept-no-persist
- HAB_BLDR_URL=https://bldr.habitat.sh/ 

Log File(s):
[hab_studio_version_error_darwin.log](https://gist.githubusercontent.com/MindNumbing/4cd072c6062fbabca5f7c042704dd4b1/raw/f0fc92cc478e4831b54d08312313a62572769307/hab_studio_version_error_darwin.log)

**Comment by christophermaier** [comment]
This is down to a difference between the studio implementations on Linux and "non-Linux". The proximal cause is here:

https://github.com/habitat-sh/habitat/blob/c1c08bd63b93a785ac353ffe261aee19bdcaa408/components/rootless_studio/default/entrypoint.sh#L23

That is, we simply don't allow for passing `version` as a command in this environment, which we probably should.

There may be additional restructuring of the different platform-specific code flows that could help to address the issue in other ways.
