### ISSUE TITLE
#templateChanged helper method

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7644]
While it is possible to play with `sha256sum` in the `run` hook, validate checksum in the `reconfigure` hook and do some action it will really handy to have such helper.

Here is example:
``` bash
# reconfigure
NETWORK_CHANGED='{{#templateChanged "config/network.conf"}}'
MAIN_CHANGED='{{#templateChanged "config/main.conf"}}'
FOLLOWER='{{svc.me.follower}}'
PID='{{pkg.svc_pid_file}}'

if [[ "$NETWORK_CHANGED" == true ]]; then
  echo "Network change requires restart"
  kill "$PID"
  exit 0
fi

if [[ "$MAIN_CHANGED" == "true" ]] && [[ "$FOLLOWER" == true ]]; then
  echo "Restarting because of config change on follower"
  kill "$PID"
  exit 0
fi

echo "Trying soft-reload on config change"
kill -1 "$PID"
```

My real use-case is building postgresql cluster: 
1. when `primary_conninfo` changes I must restart database, b/o it cannot be reload
2. however, if server was follower, but now it is leader, I must not restart, ignore `primary_conninfo` change and just call `pg_ctl reaload`.

**Comment by christophermaier** [comment]
This is a good idea, and a nice way to refine exactly how your reconfigure behavior works. We have this information in the Supervisor already (it's how we figure out whether to trigger a reconfigure in the first place), and could potentially pass it into templates directly as part of the data we provide already. That way, helper functions might not be needed.

:thumbsup:
