### ISSUE TITLE
Make `hab pkg info` return more package metadata

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7662]
The existing `hab pkg info` command can be used to programmatically extract package identifier information from the internal metadata of a `hart` file. However, `hart` files contain extensive metadata beyond just the identifier.

It would be useful to make this metadata accessible through `hab pkg info`. In particular, dependency information would be very valuable (it would have come in quite handy when addressing https://github.com/habitat-sh/habitat/pull/7661, for instance). The same logic could also be useful in a planned rewrite of the dependency resolver (per @markan). There's lots of other uses that would also be unlocked by programmatic access to `hart` metadata.

The command already has the ability to return JSON-formatted output, which would come in very handy here, particularly as a key motivator is making this information available to _automation_, and not necessarily people.

Here's what it might look like (subject to refinement, of course):

```sh
hab pkg info --json --tdeps ${HART} | jq
{
    "origin": "core",
    "name": "gzip",
    "version": "1.10"
    "release": "20200306002325",
    "ident": "core/gzip/1.10/20200306002325"
    "tdeps": [
        "core/gcc-libs/9.1.0/20200305225533",
        "core/glibc/2.29/20200305172459",
        "core/grep/3.3/20200305232635",
        "core/less/530/20200305235121",
        "core/linux-headers/4.19.62/20200305172241",
        "core/ncurses/6.1/20200305230210",
        "core/pcre/8.42/20200305232429",
        "core/zlib/1.2.11/20200305174519",
    ]
}
```
This keeps it backwards compatible with the current output, but allows the user to specify additional metadata keys they'd like to see in the output.

**Comment by jeremymv2** [comment]
I've also heard that a desired piece of data to emit is the name of the public key used to sign the package.

**Comment by jeremymv2** [comment]
closed via https://github.com/habitat-sh/habitat/pull/7814
