### ISSUE TITLE
Bootstrapping services is easy to manage

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7667]
Customers have provided us feedback that bootstrapping their habitat deployments is difficult.

This epic contains features that will make it easier to stand up habitat services on customer systems.

Once this epic is completed, it will be easier for folks to use similar methods to deploying Chef and InSpec clients to get Habitat deployed and running services on their machines.

Features:

Add ability to load multiple services in a single command

Load service on supervisor start up using 'hab svc load' config

Add config file support to `hab svc load`

Aha! Link: https://chef.aha.io/features/SH-104

**Comment by sdelano** [comment]
Comment added by Lisa Stidham in Aha! - [View](https://chef.aha.io/comments/6923237518464720514)

[Issue 7667](https://github.com/habitat-sh/habitat/issues/7667)  
noting issue number for move to App Delivery workspace
