### ISSUE TITLE
Container Exporter Improvements

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7698]
We need to improve our capabilities to manage and deliver containers.

This epic includes various refinements to make our container experience better.

Including

Improving Layered Docker Images

Capabilities to leverage external caches in Docker export

Build images from exported base images

Bare-bones bastion supervisor container

Exporter Tweaks

1. Generic repository push options
2. Fast fail if using docker w/ wrong permissions
3. Stop allowing channel in custom tags
4. Add metadata labels for containers

Aha! Link: https://chef.aha.io/features/SH-106

**Comment by sdelano** [comment]
Comment added by Lisa Stidham in Aha! - [View](https://chef.aha.io/comments/6923238444935564405)

[Issue 7698](https://github.com/habitat-sh/habitat/issues/7698)  
Noting issue number for move to App Delivery workspace.
