### ISSUE TITLE
pkg upload and pkg bulk-upload should promote all packages listed

### ISSUE THREAD

**Issue by markan** [habitat-sh/habitat#7704]
### Describe the Enhancement
pkg upload and pkg bulk-upload only promote the packages they actually upload. Other packages listed do not get promoted. The upload command should (perhaps as an option, perhaps as the default) promote all packages named.

### Describe the need
The current behavior becomes a problem when trying to upload/promote groups of packages built outside of builder. For example, if an error occurs midway through, a rerun of the command only promotes the packages uploaded during that attempt.

There are a couple of ways this could be addressed.

1) a --promote-all flag could be added to the CLI for upload (and bulk-upload); this would directly enable the workflow.

2) There may also need to be some refinement around promotion. The API only allows promotion of one package at time. Entire channels can be promoted atomically, but not subsets of packages outside of a channel. We might want to add a process to atomically promote a list of packages.

That would change the upload workflow above. Instead, the user would upload their packages somewhere (the channel doesn't matter, could just be unstable), and no promotion would occur. Then as a separate event those packages could be promoted as an atomic group.

3) alternatively we could rethink the workflow around channels as short lived entities, (maybe 'sandbox ' channels as first class entities, that would be intended as staging areas, not long lived entities)

In any event, we should enhance this workflow, or propose an alternative method to achieve this.

**Comment by collinmcneese** [comment]
👍 
We had to come up with another way to do package syncs due to this for  a use case with multiple on-prem builder instances. 
https://github.com/collinmcneese/hab_opbldr_update

**Comment by jeremymv2** [comment]
Pointing out that the `--force` argument on `bulkupload` will always perform the channel promotion, even if the package already exists on the target. While this may on the surface seem like a scary argument, it's actually rather benign. `--force` will only succeed and re-upload the package if the package checksum matches the checksum of the package that is already in Builder.
