### ISSUE TITLE
Habitat windows service v0.6.0 fails to start

### ISSUE THREAD

**Issue by gscho** [habitat-sh/habitat#7712]
I'm seeing this issue on a fresh install of the `core/windows-service` package.

```
2020-05-27 18:12:03,583 - Error occured in OnStart
System.InvalidOperationException: Missing 'launcherPath' application setting in config.
   at HabService.HabService.get_LauncherPath() in C:\hab\studios\workdir\hab\cache\src\windows-service-0.6.0\HabService.cs:line 156
   at HabService.HabService.OnStart(String[] args) in C:\hab\studios\workdir\hab\cache\src\windows-service-0.6.0\HabService.cs:line 91
```

Looks like the config file ships without a value in `launcherPath` field.

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <appSettings>
    <!--
    The 'debug' setting is deprecated and may not work as desired in a future release
    of the windows-service. Use the 'ENV_RUST_LOG' setting instead and set it to 'debug'.

    Note that any setting key beginning with 'ENV_' will be set in the supervisor's
    environment. For example, setting 'ENV_RUST_LOG' to 'debug' will set the 'RUST_LOG'
    environment variable to the value 'debug'.
    -->
    <add key="debug" value="false" />
    <add key="launcherArgs" value="--no-color" />
  </appSettings>
</configuration>
```

According to the README.md `By default this will point to the latest version of the launcher installed` but looking at the code it throws an exception if this value is not present in the config.
Probably need to handle this in https://github.com/habitat-sh/habitat/blob/master/components/windows-service/HabService.cs.

**Comment by mwrock** [comment]
hmm. The `install` hook of `windows-service` should be injecting the LauncherPath. When you `hab pkg installed` the windows service did it output indicating it was running the `install` hook?

**Comment by gscho** [comment]
@mwrock Looks like the `core/windows-service` was using the `hab pkg exec core/windows-service install` command still. When I just install the package and start the service, it works fine. Feel free to close.

**Comment by sirajrauff** [comment]
Came across this situation just now using an older Habitat version that is unaware of the `install` hook, requiring the use of `hab pkg exec core/windows-service install`. Seems after this command is run, the following line needs to be added to `<HAB_ROOT>\hab\svc\windows-service\HabService.dll.config` under `configuration > appsettings` (i.e. same level as `launcherArgs` and `debug`):
```
<add key="launcherPath" value="C:\hab\pkgs\core\hab-launcher\14385\20200824150106\bin\hab-launch.exe" />
```
Obviously the `<version>/<release>` bit may have to be modified if a newer version is used.
