### ISSUE TITLE
Processes started by hab-sup/launcher do not have supplementary group list set

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#7731]
# Summary and Example

Processes started with the Habitat supervisor/launcher may not be able to access the files that a user expects because Habitat does not set the process's supplementary group IDs.

For example, consider the following situation:

```
 > ls -al /tmp/testfile
-rw-rw----. 1 vagrant foo 30 Jun  3 09:03 /tmp/testfile
> getent group foo
foo:x:1005:hab,vagrant
> sudo -u hab cat /tmp/testfile
This is the testfile content!
> sudo -u chrony cat /tmp/testfile
cat: /tmp/testfile: Permission denied
```

However, when we run a service with the following run hook:

```
#!/bin/bash

echo "Attempting to access /tmp/testfile as hab svc (PID: $$, EIUD: $EUID)"

cat /tmp/testfile
sleep 300
```

we get:

```
test-hab-service.default(SV): Starting service as user=hab, group=hab
test-hab-service.default(O): Attempting to access /tmp/testfile as hab svc (PID: 13326, EIUD: 1001)
test-hab-service.default(E): cat: can't open '/tmp/testfile': Permission denied
```

This difference is because when a process is launched via `sudo` we get our supplementary group list set, but when it is launched under Habitat it does not:

```
> sudo grep 'Groups' /proc/13326/status 
Groups:	 
> sudo -u hab bash -c 'grep "Groups" /proc/$$/status'
Groups:	1001 1005 
```

# Background

On Linux and other unix systems, one part of a process's credentials is a list of _Supplementary group IDs_.  From [credentials(7)](https://www.man7.org/linux/man-pages/man7/credentials.7.html):

>  This is a set of additional group IDs that are used for permission checks when accessing files and other shared resources... A process can obtain its set of supplementary group IDs using getgroups(2), and can modify the set using setgroups(2).

This lists of groups is inherited from a processes parent and can be explicitly modified with the [initgroups](https://www.man7.org/linux/man-pages/man3/initgroups.3.html) and [setgroups](https://www.man7.org/linux/man-pages/man2/setgroups.2.html) system calls.

When the launcher starts our run hook, we use `uid` and `gid` from `std::os::unix::process::CommandExt` to set the effective UID and effective GID of the process:

https://github.com/habitat-sh/habitat/blob/master/components/launcher/src/sys/unix/service.rs#L97-L98

But these do not set the supplementary group IDs list.  There is currently a pull request open to add such a feature here: https://github.com/rust-lang/rust/pull/72160

For comparison, systemd sets the supplementary group IDs automatically:

> If the User= setting is used the supplementary group list is initialized from the specified user's default group list, as defined in the system's user and group database. Additional groups may be configured through the SupplementaryGroups= setting (see below).

(https://www.freedesktop.org/software/systemd/man/systemd.exec.html)

# Potential Path for a Patch

Until the standard library supports setting supplementary groups directly, we could use https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html#tymethod.pre_exec to call initgroups or setgroups ourselves before the process is exec'd.

**Comment by christophermaier** [comment]
Yup, this sounds like a good addition (as well as a good approach for a patch).
