### ISSUE TITLE
exempt `hab --version` from license check

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#7751]
I have [STRTA bootstrap](https://github.com/github/scripts-to-rule-them-all#scriptbootstrap) scripts that check developer workstations for dependencies, and recently added a check of `hab --version` to notify anyone running a dated version

I'm handling walking them through license acceptance separately (#6978 would help a lot there), and the license prompt potentially happening while running `hab --version` breaks my version parsing. I want to get their `hab` CLI current before they modify the state of their workstation with it. It is common for someone who has checked out one of my projects previously to have an ancient pre-0.80 hab binary on their workstation already.

It was surprising to me that `hab --version` could fail due to environmental state, I think it's reasonable to expect it to _only_ report the version of the binary and be a reliable way to check that an executable and current binary is present. Consider exempting `hab --version` from license checking so introspection tools can measure the state of the hab binary separately from environment setup

**Comment by jmealo** [comment]
The current behavior is unexpected. It caused a thoughtfully written bootstrap script to fail for first-time Habitat users.

**Comment by sdelano** [comment]
@themightychris thanks for reporting this. We're going to follow up and check for consistent behavior with other Chef products requiring license checks: `chef`, `inspec`, etc. and try to achieve consistency here. It looks as if `chef-client` doesn't require license acceptance to execute the version command, so it appears this is a pattern we've followed elsewhere.

We're also going to audit the rest of the `hab` commands to ensure we have coverage of other areas where license acceptance should not be required, e.g. `uninstall`.
