### ISSUE TITLE
opensuse leap install doesn't binlink hab to /usr/bin/hab

### ISSUE THREAD

**Issue by moutons** [habitat-sh/habitat#7769]
I was doing some testing on multiple distros and opensuse leap doesn't binlink to /usr/bin/hab when installed using the curlbash installer. I dug around in the installer script and hab pkg install code just enough to know that I'm out of my depth trying to figure out why and how to make it work the same on opensuse as it does ubuntu and centos. My assumption is that this is the same for a SLES installation as well, although I haven't yet validated that.

Where I'm working:
```
lsb_release -d
Description:    openSUSE Leap 15.1
```

What I did:

- Provision a minimal VM on KVM using the 15.1 Leap iso
- Log in as `root`
- curlbash the thing `curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | sudo bash`
- run `which hab` (I was doing this on all the test systems using tmux synchronize-panes, which is how I noticed a difference)
- run `ls -l /bin/hab ; ls -l /usr/bin/hab` to check how things were laid down on centos 7 & 8, ubuntu 20, and this opensuse system

It would seem to me that ensuring binlink behavior is predictable across distributions would ensure that documentation, learn.chef.io modules, and examples in blogposts are applicable to all Linux environments.

Aha! Link: https://chef.aha.io/features/SH-2413

**Comment by sdelano** [comment]
@moutons - what does end up getting binlinked here? Is `/bin/hab` available?

@smacfarlane is going to try and repro this and see what needs to be updated.

**Comment by smacfarlane** [comment]
@moutons  Unfortunately, I think this is out of our control without changing our defaults, as distros treat `/bin` and `$PATH` differently.  By default, `hab pkg binlink` will use `/bin`. This is what we use in the install.sh: 

```bash
OPTIONS:
    -d, --dest <DEST_DIR>    Sets the destination directory [env: HAB_BINLINK_DIR=]  [default: /bin]
```

On openSUSE leap, this behaves as expected.  However, on CentOS 8.2 (and I suspect this is true for other systems you looked at) `/bin` is a symlink to `/usr/bin` and `/bin` isn't included on the PATH:

```bash
[vagrant@localhost ~]$ ls -la /bin
lrwxrwxrwx. 1 root root 7 May 11  2019 /bin -> usr/bin
[vagrant@localhost ~]$ cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
[vagrant@localhost ~]$ echo $PATH
/home/vagrant/.local/bin:/home/vagrant/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
```

Changing our defaults, while possible, I feel warrants a larger discussion as it could be a breaking change for existing users. It would certainly affect the tooling around Habitat such as the studio and exporters that would need to be carefully validated.  Changing `install.sh` may be something to explore. It would be less impactful but I'd have similar concerns about breaking existing workflows or tooling.
