### ISSUE TITLE
Create a command to "patch" a running service configuration

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#7771]
With https://github.com/habitat-sh/habitat/pull/7770, we have the ability to change how Habitat manages a running service without restarting that service. That PR specifically adds the ability to reconfigure service updating, revolving around 4 different values:

* `bldr_url`
* `channel`
* `strategy`
* `update_condition`

Currently, the only way to access this ability is to use `hab svc load --force`, specifying what you wish to change. 

Unfortunately, `hab svc load --force` is not a "patchy" operation, meaning you must specify any non-default values your service is running with if you wish to retain them. 

To make this concrete, say you started a service like this:

```sh
hab svc load mycompany/myapp --strategy=at-once
```
By default, this will check for updates from the `stable` channel.

Now, if you want to change the channel to `my-other-channel` instead, you would _want_ to do this:

```sh
hab svc load mycompany/myapp --force --channel=my-other-channel
```
However, this will actually end up disabling updates altogether, because it will revert to the default update strategy of `none`. In reality, you would have to use this command:

```sh
hab svc load mycompany/myapp --force --strategy=at-once --channel=my-other-channel
```

The more non-default options you specified in your initial `hab svc load` command, the more painful this becomes.

Instead, we should provide a "patchy" operation for this that behaves as you would expect (maybe it is `hab svc patch`, maybe it is `hab svc load --patch`). This would greatly improve the UX of managing Habitat services.

**Comment by jeremymv2** [comment]
Just my two cents on this fantastic idea. Since we're mutating the underlying service's spec file, maybe re-using that same language makes sense?
For example:

```
hab svc spec my/service  # a convenience function for displaying the content of /hab/sup/default/specs/service.spec
hab svc spec my/service --patch --channel=some
```

**Comment by mwrock** [comment]
I wonder how much we really want to expose users to the `spec` term or keep it internal. Seems that add one more concept that could remain in the overall concept of "service". I also kind of like the idea of making this an entirely different command instead or making it a `--patch` arg off of `load`. Like `hab svc patch` or `hab svc update`.

**Comment by christophermaier** [comment]
I think that some of the work that @davidMcneil is working on will ultimately lead to a user-facing representation of a service's configuration, which may or may not be what we currently call "spec files". Until that settles, I think I'd like to avoid enshrining the current spec file in any commands, though a command like @jeremymv2's `hab svc spec my/service` to show a current configuration would ultimately be pretty cool.

I may tentatively begin with @mwrock's `hab svc update`, and we can collectively refine as the feature work progresses. In any event, the underlying internal logic should be largely the same, regardless of the user-facing facade we put on top of it.

Thanks for the input; much appreciated :bow:

**Comment by christophermaier** [comment]
Closed with https://github.com/habitat-sh/habitat/pull/7781
