### ISSUE TITLE
hab cli completers fails

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#7818]
Under linux:

```
. <(hab pkg exec core/hab/1.6.90 hab cli completers --shell bash)
/proc/self/fd/11:16: parse error near `)'
```

It causes `hab studio enter` to fail:

```
bash: /dev/fd/63: line 16: syntax error near unexpected token `)'
bash: /dev/fd/63: line 16: `            )'
```

**Comment by davidMcneil** [comment]
Thanks for opening this. It looks like there is a subcommand with an empty name (ie its name is the empty string) which throws off the cli completion script. I see why this is happening and am working on a fix.
