### ISSUE TITLE
`hab sup run --channel` should pull `hab-sup` and `hab-launch` from the specified channel 

### ISSUE THREAD

**Issue by davidMcneil** [habitat-sh/habitat#7833]
Currently, the `--channel` attribute only applies to `hab-sup` updates. It should also apply when first trying to install `hab-sup` and `hab-launch`. The fact that it does not requires explicitly running `hab pkg install --channel <channel> core/hab-sup` before running `hab sup run` when using anything but the `stable` channel.

**Comment by smacfarlane** [comment]
For testing pre-releases, we have `HAB_BLDR_INTERNAL_CHANNEL`,  https://github.com/habitat-sh/habitat/blob/master/RELEASE.md#what-to-test.   Having it be a parameter on the cli is :+1: but we should ensure the interaction between the two behaves as expected.
