### ISSUE TITLE
hab studio enter can fail with license check

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#7846]
This behavior applies only to the Linux chroot studio. 

During the set up phase of chroot studio creation, we have need to import the appropriate keys into the file tree of the chroot studio. This is done with `hab origin key export` and `hab origin key import`.  The later is wrapped with `busybox env FS_ROOT=/path/to/studio` so that the key is written to the correct location.  https://github.com/habitat-sh/habitat/blob/master/components/studio/libexec/hab-studio-type-default.sh#L31-L32

The hab licensing check is performed before any subcommand is evaluated, checking on disk and in the environment for license acceptance.  When looking at the filesystem, the "global" location is prepended with `FS_ROOT`, which is typically `/`.

In the case where the root user has accepted the license, writing out `/hab/accepted-licenses/habitat`, but the user invoking the studio has not AND the HAB_LICENSE env var is not set to an allowable value,  the studio will fail to run and the user will be presented with the License prompt, which will immediately exit.  

This is caused by the combination of the interplay of how licensing checks work and how the studio uses FS_ROOT to construct itself, combined with piping the `key export` output directly into `key import` forcing the license check to fail. 

There are a few ways we could solve this, possibly both should be done.

1) Move the setting of `HAB_LICENSE` earlier in the studio creation process, such that the `_hab` command (which is how we invoke hab commands that need FS_ROOT set) always contains a valid HAB_LICENSE if the host has accepted the license. 
2) Don't use FS_ROOT in the evaluation of the license.  I suspect this was done for portability across operating systems, but is _possibly_ not correct, since it can be influenced by the environment set when running `hab` commands

**Comment by sirajrauff** [comment]
Noticing some strange behaviour with this, as I'm seeing the opposite scenario occur.

CentOS8 Stream
kernel 4.18.0
hab 1.6.288/20210402191717

The user has accepted the license but `root` has not, resulting in an interactive prompt when starting the process, followed by a non-interactive prompt later which fails:
```
$ hab studio enter
+---------------------------------------------+

            Chef License Acceptance


Before you can continue, 1 product license must be accepted.
View the license at https://www.chef.io/end-user-license-agreement

License that needs accepting:

  * Habitat

Do you accept the 1 product license? [yes/No/quit] yes

Accepting 1 product license...
✓  1 product license accepted.

+---------------------------------------------+

∵ Missing package for core/hab-studio/1.6.288
» Installing core/hab-studio/1.6.288
...
[REMOVED FOR BREVITY]
...
★ Install of core/hab-studio/1.6.288/20210402194444 complete with 43 new packages installed.
   hab-studio: Creating Studio at /hab/studios/home--hab--sample-node-app (default)
   hab-studio: Importing 'sirajrauff' secret origin key
+---------------------------------------------+

            Chef License Acceptance


Before you can continue, 1 product license must be accepted.
View the license at https://www.chef.io/end-user-license-agreement

License that needs accepting:

  * Habitat

Do you accept the 1 product license? [yes/No/quit] Do you accept the 1 product license? [yes/No/quit] 
If you do not accept this license you will not be able to use Chef products.

Do you accept the 1 product license? [yes/No/quit] 
+---------------------------------------------+

✗✗✗
✗✗✗ License agreement not accepted
✗✗✗
```
Note that before this `/home/hab/.hab/accepted-licenses/habitat` did exist, and `/hab/accepted-licenses/habitat` did not. After this, however, both exist. Attempting to enter the studio again is fruitless and fails on the same **importing <origin> secret origin key** line. I tried removing `origin = sirajrauff` from `/home/hab/.hab/etc/cli.toml`, the prompt is now interactive:
```
 hab studio enter
   hab-studio: Creating Studio at /hab/studios/home--hab--sample-node-app (default)
   hab-studio: No secret keys imported! Did you mean to set HAB_ORIGIN?
To specify a HAB_ORIGIN, either set the HAB_ORIGIN environment
variable to your origin name or run 'hab setup' and specify a
default origin.
+---------------------------------------------+

            Chef License Acceptance


Before you can continue, 1 product license must be accepted.
View the license at https://www.chef.io/end-user-license-agreement

License that needs accepting:

  * Habitat

Do you accept the 1 product license? [yes/No/quit] yes

Accepting 1 product license...
✓  1 product license accepted.

+---------------------------------------------+

» Installing core/hab-backline/1.6.288/20210402194335
...
[REMOVED FOR BREVITY]
...
[1][default:/src:0]#
```
At this point I can now re-add the origin to my `cli.toml` and I'm able to enter/exit the studio on a whim. However, after running a `hab studio rm` I'm back to failure to enter unless I once again remove the `origin` from cli.toml.

Note `HAB_ORIGIN` is equivalent to `origin` in the cli configuration in my testing.
