### ISSUE TITLE
Hab license cannot be accepted by user if root has already accepted

### ISSUE THREAD

**Issue by smacfarlane** [habitat-sh/habitat#7849]
If the root user has already accepted the Habitat license with `accept` so that the `/hab/accepted-licenses/habitat` file is written to disk,  a user is then unable to accept the license for the current user and will be presented with `You have already accepted the license.` when trying to accept. 

This is generally not a problem, but it causes an issue in the context of #7846 , where a user would need to accept on behalf of the current users account in order to enter the studio.  

To reproduce: 
```
vagrant@vagrant:~$ sudo hab license accept

Accepting 1 product license...
✓  1 product license accepted.

+---------------------------------------------+

vagrant@vagrant:~$ hab license accept
You have already accepted the license.
```

**Comment by jeremymv2** [comment]
Just ran into this myself. It's probably a good one to tackle fixing soon.
