### ISSUE TITLE
[hab pkg exec] Has it stopped setting up runtime environment?

### ISSUE THREAD

**Issue by gavindidrichsen** [habitat-sh/habitat#7902]
Has ``hab pkg exec`` stopped setting up the execution environment for hab packages?  I'm seeing unexpected behaviour in my studio environment explained below

### Steps to reproduce

1. Open studio and install core/gecode.  Doing ``hab pkg install core/gecode`` installs, among other things, 2 binaries "fz" and "mzn-gecode".  
1. Run mzn-gecode without "hab pkg exec" prefix.  
1. Run mzn-gecode with the "hab pkg exec" prefix

Step (2) shows suggests that the mzn-gecode binary may require some extra runtime environment setup as it throws an error:

```bash
[46][default:/src/gecode:130]# /hab/pkgs/core/gecode/3.7.3/20200403223326/bin/mzn-gecode --help
/hab/pkgs/core/gecode/3.7.3/20200403223326/bin/mzn-gecode: line 41: minizinc: command not found
[47][default:/src/gecode:127]# 
```

Step (3) produces unexpected output, not from mzn-gecode but from hab:

```bash
[41][default:/src/gecode:127]# hab pkg exec core/gecode/3.7.3/20200403223326 mzn-gecode --help
hab-pkg-exec 1.6.139/20200824142405
Executes a command using the 'PATH' context of an installed package

USAGE:
    hab pkg exec <PKG_IDENT> <CMD> [ARGS]...

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <PKG_IDENT>    A package identifier (ex: core/redis, core/busybox-static/1.42.2)
    <CMD>          The command to execute (ex: ls)
    <ARGS>...      Arguments to the command
[42][default:/src/gecode:0]# 
```

### Further Observations

"fz --help" works fine on its own but produces same output as mzn-gecode when prefixing with "hab pkg exec...":

```bash
[45][default:/src/gecode:100]# /hab/pkgs/core/gecode/3.7.3/20200403223326/bin/fz --help
Gecode FlatZinc interpreter
 - Supported FlatZinc version: 1.5

Gecode configuration information:
 - Version: 3.7.3
 - Variable types: BoolVar IntVar SetVar
 - Thread support: enabled (4 processing units)
 - Gist support: disabled
...
...
```

Now prefixing the binaries with ``hab pkg exec <PKG_IDENT>`` returns usage for the "hab pkg exec" command not the core/gecode ones.  For example:

```bash
[37][default:/src/gecode:0]# hab pkg exec core/gecode/3.7.3/20200403223326 fz --help        
hab-pkg-exec 1.6.139/20200824142405
Executes a command using the 'PATH' context of an installed package

USAGE:
    hab pkg exec <PKG_IDENT> <CMD> [ARGS]...

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

ARGS:
    <PKG_IDENT>    A package identifier (ex: core/redis, core/busybox-static/1.42.2)
    <CMD>          The command to execute (ex: ls)
    <ARGS>...      Arguments to the command
```

### Environment Details
- [x] The OS (including version) where you are running any of the Habitat commands.
Mac Catalina 10.15.5
- [x] Debug/backtrace of the command you are trying to run. You can set the following environment variables before running the `hab` command to generate a trace:
N/A
- [x] Current Habitat environment variables where the `hab` command or supervisor is running.  These can be gathered using:

```bash
➜  .hab hab --version
hab 1.6.139/20200824142820
```
	- [x] If you're running into problems with the [Habitat Studio](https://www.habitat.sh/docs/concepts-studio/), please use the `env | grep ...` command specified above to include environment variables:
		- [x] a. before starting the studio

```bash
➜  gecode git:(gavindidrichsen/master/pr/add_to_organization) ✗ env | grep HAB | grep -v HAB_AUTH_TOKEN
HAB_ORIGIN=core
```
		- [x] b. inside the studio
```bash
[42][default:/src/gecode:0]# env | grep HAB | grep -v HAB_AUTH_TOKEN
HAB_BLDR_URL=https://bldr.habitat.sh
HAB_ORIGIN=core
HAB_LICENSE=accept-no-persist
```

- [x] If this is a key related issue, please include the list of files (including user/group permissions) in `/hab/cache/keys` and `$HOME/.hab/cache/keys` via `ls -la`.
N/A

**Comment by davidMcneil** [comment]
As of `1.6.139` `--help`, `-h`, `-V`, and `--version` are passed to the hab cli and not the `exec`ed command. If you would like to use one of these flags use `--` as a prefix (eg `hab pkg exec core/gecode/3.7.3/20200403223326 -- fz --help`). See #7893
