### ISSUE TITLE
Migrate the docs to docs.chef.io

### ISSUE THREAD

**Issue by kagarmoe** [habitat-sh/habitat#7925]
We'll hugo-tize the docs this iteration, culminating with publishing them at docs.chef.io

@IanMadd is in charge of this; he will fill out the steps.

**Comment by IanMadd** [comment]
This has mostly been take care of with:

- #7968 
- #7967 
- #7962
- #7961 
- #7959 
- #7953
- #7948 
- #7947 
- #7939 
- chef/chef-web-docs#2730
- chef/chef-web-docs#2742

We're still working on automating the CLI and Service Template Data documentation.

**Comment by IanMadd** [comment]
I think we're done with this.

Automation PRs:
habitat-sh/habitat#7993
chef/chef-web-docs#2753

**Comment by IanMadd** [comment]
We're done.
