### ISSUE TITLE
[CI] Update pipeline's Github release automation

### ISSUE THREAD

**Issue by christophermaier** [habitat-sh/habitat#8063]
We have [some automation](https://github.com/habitat-sh/habitat/blob/f71885a4ed50f658262b0185063bf0d9d0efb446/.expeditor/finish_release.pipeline.yml#L13-L24) for creating a Github release after we have released a new version of the Supervisor, but it does not work properly. It appears to be due to the user in our pipeline not having sufficient privileges to do so. For now, we'll leave the automation in place (allowing failures), but it should be eventually be addressed conclusively.

**Comment by mwrock** [comment]
this got magically fixed. I think related to a change in secrets mgmt
