### ISSUE TITLE
Habitat Supervisor Ignores `--shutdown-timeout` flag when loading a service with `hab svc load --shutdown-timeout ...`

### ISSUE THREAD

**Issue by patrick-baldridge** [habitat-sh/habitat#8084]
This has been reproduced in a clean environment with a fresh installation of the latest version of habitat. No hab environment variables have been set. We are using oracle linux 7.x, hab version 1.6.235 (latest stable).

Below are steps to reproduce the bug. We are loading the core/redis package with a shutdown-timeout value of 30, however when we query the supervisor API for service info, we can see it's set to the default value of 8.
```
$ docker pull oraclelinux:7
$ docker run -it oraclelinux:7 /bin/bash
$ curl https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh | bash
$ hab license accept
$ hab sup run &> /tmp/supervisor.log &
$ hab svc load core/redis --shutdown-timeout 30
$ hab pkg install -b core/jq-static
$ curl -s -S localhost:9631/services/redis/default | jq .pkg.shutdown_timeout
> 8
```

**Comment by patrick-baldridge** [comment]
After a second review, I believe the values shown under the pkg grouping are the default values provided by the package. I assume if I build a package setting the plan variable `pkg_shutdown_timeout_sec ` to something other than `8`, that value would be reflected here.

If that's the case, then it feels like a gap to not show the effective `shutdown_timeout` for the service. What would be the best way to open a request to include `shutdown_timeout` in the details the supervisor provides for a loaded service?

FYI the `habitat` community cookbook is checking the pkg.shutdown_timeout value when determining of the service is configured correctly. This would be a bug if this value is not the effective shutdown_timeout value. If it's a bug then there's no way to find the actual effective value to correct this. The behavior I see right now is the resource being updated each converge because the resource always compares against 8 wether or not the effective value is 8.
https://github.com/chef-cookbooks/habitat/blob/master/resources/service.rb#L194-L195

Any comments or advice here would be appreciated. Thank you.

**Comment by mwrock** [comment]
I agree that the data presented by the http gateway's endpoints should reflect the "effective timeout." #8099 should fix that.
