### ISSUE TITLE
Habitat 

### ISSUE THREAD

**Issue by JohnLKramer** [habitat-sh/habitat#8173]
Hello - thanks for reporting an issue with Habitat.

In order to help us troubleshoot the issue, please be sure to include the following information if applicable:

- [x] The OS (including version) where you are running any of the Habitat commands.

    $ uname -a
    Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux
		
- [x] Current Habitat environment variables where the `hab` command or supervisor is running.  

Outside studio:

    HAB_BLDR_URL=https://bldr.paneracloud.com/
    HAB_ORIGIN=john_kramer
    HAB_LICENSE=accept

Inside studio:

    HAB_BLDR_URL=https://bldr.paneracloud.com/
    HAB_BINLINK_DIR=/hab/bin
    HAB_ORIGIN=john_kramer
    HAB_LICENSE=accept-no-persist

I am seeing this issue when trying to build my npm project with habitat:
    > www-ui@1.60.0 lint /src
    > tslint -c tslint.json 'src/**/*.ts'

    sh: tslint: not found
    npm ERR! code ELIFECYCLE

From my plan.sh:

    pkg_build_deps=(
     core/busybox-static
      core/node
      core/coreutils
      core/git
    )
    do_before() {
      do_default_before
      update_pkg_version
      npm config set registry <registryurl>
    }
    do_prepare() {
      pushd "${PLAN_CONTEXT}"/..
      npm install --no-color
      ls -al node_modules/.bin
      npm run lint
      popd
    }
    do_build() {
      npm run build ${package_name} ${new_version} ${BUILD_NUMBER} --no-color
      return 0
    }

The relevant line from my package.json:
    
    "lint": "tslint -c tslint.json 'src/**/*.ts'",

When running npm scripts outside Habitat, the path is the shell path + node_modules/.bin and tslint is there:

    [10][default:/src:0]# ls -al node_modules/.bin/tslint 
    lrwxr-xr-x 1 1000 1000 20 Apr 12 20:50 node_modules/.bin/tslint -> ../tslint/bin/tslint
    [11][default:/src:0]# ls -al node_modules/tslint/bin/tslint 
    -rwxr-xr-x 1 1000 1000 50 Jan 10  2019 node_modules/tslint/bin/tslint
    [12][default:/src:0]#

So I'm not sure what Habitat is doing with the path. Any help is appreciated.

[hab.log](https://github.com/habitat-sh/habitat/files/6319969/hab.log)

**Comment by mwrock** [comment]
looks like you run `pushd "${PLAN_CONTEXT}"/..` just before `npm install`. So I would bet `node_modules` is created one folder up from `${PLAN_CONTEXT}` (this is the directory where `plan.sh` exists) and I would check there.

**Comment by JohnLKramer** [comment]
Yes. I `pushd "${PLAN_CONTEXT}"/..` and `npm install` succeeds. `node_modules` is created one directory up from `${PLAN_CONTEXT}`. And that's where I run `npm run lint`. 

I can even list the current directory like so:

do_prepare() {
  pushd "${PLAN_CONTEXT}"/..
  npm install --no-color
  ls -al node_modules/.bin
  echo "pwd"
  pwd
  ls
  npm run lint
  popd
}
```

```
pwd
/src
Jenkinsfile
README.md
build
config
content-build
dist
docs
hab.log
habitat
i18n
index.html
jest.config.js
karma.conf.js
mocks
node_modules
package-lock.json
package.json
scripts
sonar-project.properties
src
static
tsconfig.json
tslint.json
typedoc.js

> www-ui@1.60.0 lint /src
> tslint -c tslint.json 'src/**/*.ts'

   [1;36mwww-ui: [1;37mBuild time: 0m42s[0m
   [1;36mwww-ui: [1;31mExiting on error[0m
```

And you can see that node_modules is there, but it still can't find the path.

**Comment by JohnLKramer** [comment]
Resolved my issue:
I had to change the lint script from:

`"lint": "tslint -c tslint.json 'src/**/*.ts'",`
to:
"lint": "$(npm bin)/tslint -c tslint.json 'src/**/*.ts'",

This some fixes the path.

I also had to binlink env because that is referenced in tslint. Like so:

`hab pkg binlink core/busybox-static -d /usr/bin -f env`

**Comment by mwrock** [comment]
Glad you got it working. You can avoid the `binlink` by adding `core/coreutils` as a `pkg_build_dep`.
