### ISSUE TITLE
Links in the readme aren't working. 

### ISSUE THREAD

**Issue by bennyvasquez** [habitat-sh/habitat#8206]
These links in the [root README](https://github.com/habitat-sh/habitat) aren't working, as they appear to be pointing to old web files. 

Not sure where they should be updated to yet, but we definitely want to update them.

![image](https://user-images.githubusercontent.com/13630986/118493747-6f8eca80-b6ef-11eb-9b99-dbe7a8f39e6b.png)

Aha! Link: https://chef.aha.io/features/APPDL-113

**Comment by pozsgaic** [comment]
Links have been updated - please see https://github.com/habitat-sh/habitat/pull/8268
