### ISSUE TITLE
Platform Support : Build Hab cli binary in Mac / M1 processor instance.

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/habitat#8270]
Mac with Intel processor uses the same Linux binaries for performing some tasks. For example, build a package, enter the studio, etc.
It is dependent on the below docker container for performing the above tasks:
`habitat/default-studio-x86_64-linux`

Even though hab does not support building packages for the native Mac platform, it allows building for the x86_64 platform. It works fine because the underlying architecture of Intel-based Macs and the target of hab Linux binaries are based on x86_64/amd64 architecture.

For the hab CLI to be useful on Mac with Apple Silicon (M1 processor), we need to provide support similar to working with Mac with an Intel-based processor. Apple Silicon (M1 processor) is based on aarch64 architecture.

On Mac with Intel-based processor, the following docker container is used to build a package and/or enter the studio.
`habitat/default-studio-x86_64-linux`

For the initial phase, we can provide support similar to Macs with Intel-based processors where the user of the hab CLI  enters the studio. For this, we need to build the docker container for the Arm64(aarch64) architecture. 

[Docker Desktop for Apple silicon](https://docs.docker.com/desktop/mac/apple-silicon/) supports multi-platform images, which allows you to build and run images for both x86 and ARM architectures. We can reuse the same docker container built for Linux. 

We can pull Pulling a specific tag works fine:
`docker pull habitat/default-studio-x86_64-linux:1.6.371`

We need to explicitly specify the tag otherwise it will through an error as shown below because we are not publishing the container with the **latest** tag.
```
docker pull habitat/default-studio-x86_64-linux
Error response from daemon: manifest for habitat/default-studio-x86_64-linux:latest not found: manifest unknown: manifest unknown
```

We can run the docker container, it will throw a warning but works fine.
```
docker run -it  habitat/default-studio-x86_64-linux:1.6.371
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Next steps:

1. Publish the hab for the M1 processor.
should be able to download from https://raw.githubusercontent.com/habitat-sh/habitat/master/components/hab/install.sh
2. Build the docker container for Arm
The code/image files for building containers is present in components/rootless_studio
3. Enable support for entering the studio or any usable commands in the hab CLI.

**Note:** Docker Desktop for Apple silicon supports to build and run images for both x86 and ARM, we can skip step 2 and focus on steps 1 and 3.
**Note:** Can we build the container for multi platform (https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/)

In a later phase, if we can provide full natively support for the Arm64 platform, we can target the following hardware:

1. Macs with Apple silicon
2. Linux machines with Arm64 
3. Other Arm64 devices (Raspberry Pi for example)

**Comment by mwrock** [comment]
I actually get the same `manifest unknown` unknown issue as well on linux. You need to include the version tag. So try `docker pull habitat/default-studio-x86_64-linux:1.6.351`
