### ISSUE TITLE
Build failed when multiple hooks

### ISSUE THREAD

**Issue by jsirex** [habitat-sh/habitat#8278]
https://github.com/habitat-sh/habitat/commit/2901d4d25fc0394793cf830b44c43c3aae5ec8ff

```
   builder-worker: Writing configuration
   builder-worker: ERROR: Multiple hook files found for run hook. No more than one hook file permitted per lifecycle hook.
   builder-worker: Build time: 7m7s
   builder-worker: Exiting on error
```

```
[18][default:/src/components/builder-worker:0]# ls habitat/hooks/
run  run.ps1
```

**Comment by mwrock** [comment]
Yes. If you want to have a `run.ps1` and a `run` (or `run.sh`) for linux you will want to use a target specific directory. See https://docs.chef.io/habitat/plan_writing/#writing-a-plan-for-multiple-platform-targets

**Comment by jsirex** [comment]
Oh, my fault. Looked at old builders' code.
