### ISSUE TITLE
Fix hab-sup 1.6.416 which had an issue where invalid IP address on event stream url caused hab supervisor to crash

### ISSUE THREAD

**Issue by rahulgoel1** [habitat-sh/habitat#8358]
Customer Bug : https://github.com/chef/customer-bugs/issues/515.

Add test case coverage to https://github.com/habitat-sh/habitat/blob/main/test/end-to-end/test_event_stream.ps1 for the case of IP address and DNS as event stream URL

Setup E2E testing environment.

During Pre-Release phase testing in collaboration with Customer Architect team

**Comment by pozsgaic** [comment]
The nats.io crate that we integrated to replace rants crate does not support use self-signing certificates.  The current integration between hab supervisor and automate requires a token and a self-signed certificate.
To use nats.io crate this would require changes on the automate side.

**Comment by mwrock** [comment]
Test coverage now encompasses full automate integration and DNS name. We will be keeping rants and not moving forward with nats.io. Details as to why will be commented on in #8386
