### ISSUE TITLE
Supervisor SelfUpdater should track supervisor at head of channel in the event a supervisor is demoted

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#8359]
@rahulgoel1 commented on [Thu Oct 28 2021](https://github.com/habitat-sh/builder/issues/1648)

Customer Bug :  https://getchef.zendesk.com/agent/tickets/28967
https://github.com/chef/customer-bugs/issues/501

**Comment by mwrock** [comment]
As discussed in the customer bug, the supervisor's `--auto-update` feature which enables a supervisor to update itself does not take into account a demoted supervisor. If a locally installed supervisor is at a higher version than the supervisor in the `--channel` then that local supervisor will always be chosen.

We should consider taking a similar approach to updating the supervisor that we use with services with a `--update-condition` of `track-channel`. In those cases, the supervisor always runs what is at the head of the channel. If a service is demoted, then the supervisor loads the version now at the head.

That all said, I think this functionality would rarely ever be used since we try to NEVER demote the supervisor. When we release the supervisor, the release is made available on brew, packages.chef.io, and chocolatey. Demoting the supervisor would mis align what is on bldr with what is in the other above distribution channels. We prefer to "roll forward" a new release rather than demote.

**Comment by eric51893** [comment]
Supervisor demotion did happen with 1.6.373 being demoted 10/9/21 and 1.6.351 being the next stable version.  Outside of a fix to the supervisor code is there any internal process or check being implemented to avoid a similar demotion without a newer stable roll out?  This event created a lot of issues and work for your customers.

**Comment by mwrock** [comment]
I have just read through the entirety of the customer zendesk ticket and feel I have a better understanding of what happened here. My apologies for not doing that earlier. I was previously responding to comments about `--auto-update` behavior. However, `--auto-update`  does not appear to be at all in play hear.

First let me recap the scenario for the sake of others that may visit this issue in the future and lack context:

A user had deployed an AMI with hab 1.6.373 installed. At the time the AMIs were created, 1.6.373 was the stable version of `core/hab`. When these VMs were provisioned with these AMIs, they were unable to download the supervisor because between creating the AMI and provisioning the VM, 1.6.373 was demoted to unsatble.

When habitat is installed on a fresh image (or any machine), only the CLI (core/hab) is being installed. The very first time `hab sup run` is invoked, it will download `core/hab-sup`. So in this case `--auto-update` had never attempted to update the supervisor because there simply was no supervisor present to update itself.

Now lets assume a scenario where an older supervisor was installed and running and managed to update to 1.6.373 which then got demoted. In that scenario 1.6.373 would continue to run even though it was unstable and would eventually update to a newer version once that version got promoted.

In this case, one could have run `hab pkg install core/hab-sup/1.6.373 --channel unstable` and than a subsequent `hab sup run` would have succeeded. However, I think uninstalling hab and getting the stable version of the CLI which is what the customer did was the correct way forward because 1.6.373 was inadvertently promoted to stable as part of the "core plans refresh" without going through a proper release pipeline.

The mistake here (which was totally internal to Chef) was not so much the demotion of 1 .6.373 but rather its previous promotion to stable. We will ensure that future core-plan refreshes will not include a promotion of non-core plans.

I would also recommend to anyone baking a hab install into a compute image that is destined to run as a supervisor to include a `hab pkg install core/hab-sup` after the hab install. This will wnsure the image has the supervisor installed on disk and will not incur an attempt to download it from bldr.

I am going to close this issue but please let me know if there is anything I have wrong with this scenario.
