### ISSUE TITLE
bump rust toolchain to 1.56.1

### ISSUE THREAD

**Issue by mwrock** [habitat-sh/habitat#8368]
This just requires us to bump https://github.com/habitat-sh/habitat/blob/main/rust-toolchain and also build and promote core/rust/1.56.1 packages.

**Comment by mwrock** [comment]
Note from our conversation offline, the best way to test core/rust builds on windows is to spin up a windows ec2 instance, install habitat, clone core-plans and then run `hab pkg build rust`.

**Comment by pozsgaic** [comment]
Bumping to 1.56.1, clippy error #suspicious_else_formatting for 
#[structopt(...)] constructs is observed.  We are using a habitat-sh crate for structopt, but I tested this out and see similar issue using the official crate.  

Above these errors is an overarching 
#[derive(ConfigOpt, StructOpt)]

There may be errors in configopt crate - link below shows an instance where there is an "else if" clause without the "else":
https://github.com/davidMcneil/configopt/blob/master/configopt-derive/src/configopt_type/parse.rs#L168

**Comment by mwrock** [comment]
Do you mean Structopt @pozsgaic ?

**Comment by pozsgaic** [comment]
Out of curiosity, I added the clippy::suspicious_else_formatting to the allowed lints file (support/allowed_lints.txt) to see if this was the only issue.  I found a large number of errors from the ConfigOpt crate:
#[derive(ConfigOpt, StructOpt, Deserialize)]
         ^^^^^^^^^ the borrow produces a value

   = note: `-D unused-must-use` implied by `-D warnings`
   = note: this error originates in the derive macro `ConfigOpt` (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by mwrock** [comment]
closed by #8378
