### ISSUE TITLE
Supervisor crashes in Docker studio on M1 macbooks

### ISSUE THREAD

**Issue by themightychris** [habitat-sh/habitat#8406]
When a Docker Habitat studio is launched in amd64 compatibility mode, everything generally seems to work but supervisor crashes and can't be run manually.

## Steps to reproduce

```bash
HAB_DOCKER_OPTS="--platform linux/amd64" hab studio enter -D
hab svc status
```

## Observations

![Screen Shot 2021-12-31 at 4 47 31 PM](https://user-images.githubusercontent.com/458494/148122471-a766e039-2bfb-4c57-a840-280ca75a7db5.png)

- Binaries all work
- `uname` shows `x86_64` architecture
- Any attempt to run supervisor crashes with:

    ```console
    Notify error: other os error
    [2021-12-31T21:46:41Z ERROR hab_launch] Launcher exiting with code 86
    ```

## Theory

Docker is confirmed to be emulating amd64, and the supervisor binary is linked and executes alright at the surface level, so Supervisor or some dependency must be making some system calls to examine the OS and finding an unexpected value

**Comment by mwrock** [comment]
Did a bit of triage here. With debug logging we see:
```
hab-sup(MR): Supervisor Member-ID 361fdbea52b04217989055736e24cb8c
[2022-01-13T21:06:16Z DEBUG habitat_launcher_client::client] Removed old pipe to launcher /tmp/rust-ipc-socket.8pWgVP
Notify error: other os error
[2022-01-13T21:06:16Z DEBUG hab_sup] start() returned Err(NotifyError(Io(Os { code: 9, kind: Other, message: "Bad file descriptor" }))); Exiting 86
```
This is coming from the `notify` crate which we use for file system watching. I'm certain this specific error is [`SpecWatcher::run`](https://github.com/habitat-sh/habitat/blob/de33e5fcf3eab04e79c903d9cc41190e187716d8/components/sup/src/manager.rs#L693). Its the first file watching mechanism spawned after the `Member-ID` is printed. Right after launching the spec watcher we print out some info on the event stream if we have an event stream config. I launched tghe supervisor with event configuration and this did not get printed which would confirm that the failure is prior to that.

So the root of this is likely either in `notify` or in `inotify` which is the underlying library that `notify` uses on linux.

**Comment by mwrock** [comment]
Looks like the root is that `inotify_init`, which the `inotify` crate calls when creating a watcher, will fail when emulating x86. https://github.com/docker/for-mac/issues/5321. Will need to investigate but there may not be a simple fix for this. One thing worth looking into is if we need the watcher functionality in a studio environment and if not then don't create one, at least not on x86 emulation.

**Comment by mwrock** [comment]
We do need the watcher functionality in order for the supervisor to find loaded services. Another avenue to explore here is using the `PollWatcher` instead of `RecomendedWatcher` on x86 emulation. Its slower but that should not be a deal breaker in a studio and it does not use inotify.

**Comment by themightychris** [comment]
the watcher is also important for user config TOML files

**Comment by sajjaphani** [comment]
https://github.com/notify-rs/notify#fsevents

**Comment by atultherajput** [comment]
> When a Docker Habitat studio is launched in amd64 compatibility mode, everything generally seems to work but supervisor crashes and can't be run manually.
> 
> ## Steps to reproduce
> ```shell
> HAB_DOCKER_OPTS="--platform linux/amd64" hab studio enter -D
> hab svc status
> ```
> 
> ## Observations
> ![Screen Shot 2021-12-31 at 4 47 31 PM](https://user-images.githubusercontent.com/458494/148122471-a766e039-2bfb-4c57-a840-280ca75a7db5.png)
> 
> * Binaries all work
> * `uname` shows `x86_64` architecture
> * Any attempt to run supervisor crashes with:
>   ```
>   Notify error: other os error
>   [2021-12-31T21:46:41Z ERROR hab_launch] Launcher exiting with code 86
>   ```
> 
> ## Theory
> Docker is confirmed to be emulating amd64, and the supervisor binary is linked and executes alright at the surface level, so Supervisor or some dependency must be making some system calls to examine the OS and finding an unexpected value

I am also getting the same error while setting dev environment for automate (https://github.com/chef/automate/blob/main/dev-docs/DEV_ENVIRONMENT.md).

**Comment by pozsgaic** [comment]
I tried to run the above command on the M1 machine CHF-V-001-MM001 and
received the error:
_Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
✗✗✗
✗✗✗ The Docker image habitat/default-studio-x86_64-linux:1.6.420 is unreachable due to a network error.
✗✗✗ The image must be reachable to ensure the versions of hab inside and outside the studio match.
✗✗✗ You can specify your own Docker image using the HAB_DOCKER_STUDIO_IMAGE environment variable.
✗✗✗_

**Comment by atultherajput** [comment]
> I tried to run the above command on the M1 machine CHF-V-001-MM001 and received the error: _Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? ✗✗✗ ✗✗✗ The Docker image habitat/default-studio-x86_64-linux:1.6.420 is unreachable due to a network error. ✗✗✗ The image must be reachable to ensure the versions of hab inside and outside the studio match. ✗✗✗ You can specify your own Docker image using the HAB_DOCKER_STUDIO_IMAGE environment variable. ✗✗✗_

I was also getting this error and to resolve this I had to manually start docker application before running habitat.

**Comment by pozsgaic** [comment]
I found that "hab pkg build" is not succeeding for the components/hab and components/sup components.
I was able to build these with cargo build at the command line but the executable type does not match
what is deployed.
The desired executable type is:  ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /hab/pkgs/core/glibc/2.33/20210826050111/lib/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, not stripped

Cargo build is producing executables of type:  
Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>

Will now get this built with correct type and retry

**Comment by pozsgaic** [comment]
@sajjaphani I checked the link and there is a disclaimer at the top of the readme:
Cross-platform filesystem notification library for Rust.
Caution! This is unstable code!

**Comment by pozsgaic** [comment]
I did find this crate that looks promising:
https://docs.rs/fsevent/2.1.2/fsevent/

**Comment by themightychris** [comment]
Looks like it might be a while/forever for Docker's x86 emulation to support inotify :-(

One suggested solution was to ship multi-arch images: https://github.com/docker/for-mac/issues/5321#issuecomment-824283216

How hard would it be to publish multi-arch studio container images?

**Comment by themightychris** [comment]
@mwrock the docker-for-mac issue got autoclosed by a bot with no indication they're going to do something about this. This issue is rapidly undermining Habitat's viability has M1 laptops become more prevalent. We gotta figure out how to work around this and at least stop supervisor from crashing, even if it takes a degradation of functionality for now

**Comment by themightychris** [comment]
Newer issues in `docker/for-mac` reporting this are getting closed right away with a reference to it being a "documented issue": 

https://github.com/docker/for-mac/issues/6174#issuecomment-1048928733

**Comment by mwrock** [comment]
We are nearing completion of this work in #8449 which should go out in the next release.
