### ISSUE TITLE
Meaning in Habitat configuration templates section is unclear

### ISSUE THREAD

**Issue by moutons** [habitat-sh/habitat#8407]
https://github.com/habitat-sh/habitat/blob/09fe25922eb96de5b95c008caf7378784a2cb092/components/docs-chef-io/content/habitat/config_templates.md?plain=1#L30-L34

My understanding of this section is that the preference is to use default.toml, then config at runtime, then environment variables, and that the order of precedence is in the reverse order. However, this is not clear from the documentation.

Can this section be clarified to properly convey the preferred usage and the order of precedence?

**Comment by mwrock** [comment]
closed via #8408
