### ISSUE TITLE
Create a build.sh script for Habitat builds

### ISSUE THREAD

**Issue by pozsgaic** [habitat-sh/habitat#8448]
Summary:
In practice it is easier to use a custom script to perform Habitat builds.  On the linux side,
we have been copying the buildkite verify script run_cargo_test.sh and modifying that
to perform builds as it captures the environment we need.

Issue:
Create a build.sh script that will reside in root of Habitat repository that can be used to run
builds similar to the windows script we have for habitat:  build.ps1

**Comment by mwrock** [comment]
Just for the sake of idiomaticness (if thats a word?) we should probably have this be a `make` command instead of calling `build.sh`.

**Comment by pozsgaic** [comment]
Sure we can do that.  For builder we updated the makefile as well as introducing the build.sh script.

**Comment by mwrock** [comment]
oh yeah. Sorry I don't mean that we can't have a build.sh, but devs and other technical folks just expect `make build` to "work".
