### ISSUE TITLE
RAML depot/builder-api endpoints

### ISSUE THREAD

**Issue by metadave** [habitat-sh/habitat#845]
We have a start [here](https://github.com/habitat-sh/habitat/blob/master/components/depot/doc/api.raml), but we also need the new origin API added and builder-api docs as well.

**Comment by Hoverbear** [comment]
Correct link is https://github.com/habitat-sh/habitat/blob/master/components/builder-depot/doc/api.raml

**Comment by reset** [comment]
Both APIs now have RAML documentation along with the supervisor's http-gateway aswell
