### ISSUE TITLE
RFE: libpcre2 

### ISSUE THREAD

**Issue by arthurschneiderv** [habitat-sh/habitat#8462]
Hello, I'm trying to do a build of latest ClamAV, and its failing on pcre2 missing and I don't see it anywhere. Is it hidden somewhere? If not could it be added? 

https://www.pcre.org/current/doc/html/

**Comment by mwrock** [comment]
Hi @arthurschneiderv this repo is for issues with the behavior of habitat and its components. It looks as though you are reporting a problem with a package. I dont see a `core/clamav` in any of our core plans repositories. Regarding adding new software to our core packages, we encourage users to maintain their own dependencies. So the guidance here would be to create your own pcre2 in your origin and then have clamav depend on that. Thanks!
