### ISSUE TITLE
`[err=2] bad_verification_code` When signing without GitHub public email available

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#861]
When attempting to sign in with GitHub, a `[err=2] bad_verification_code` error happens if you do not have a public email address.

In order for sign in to work, you need to go to your GitHub profile and set the *Public email* to something other than "Don't show my email address" in your [GitHub profile](https://github.com/settings/profile).

![screenshot](https://dl.dropboxusercontent.com/s/s8q2djsgmdi0g0v/2016-06-15%20at%208.40%20AM%20(1).png)

**Comment by metadave** [comment]
fixed in https://github.com/habitat-sh/habitat/pull/897, awaiting release

**Comment by reset** [comment]
Fixed in `core/hab-builder-api/0.7.0/20160623113610` which is now live

**Comment by brianpeiris** [comment]
A similar error occurs when your GitHub account never had a public email in the first place. The error code was different `[err=7]`. Setting a public email fixes sign in.

**Comment by reset** [comment]
@brianpeiris thank you for the report! I'm taking a look at this one right now
