### ISSUE TITLE
-R option is either mis documented, or not implemented

### ISSUE THREAD

**Issue by spuder** [habitat-sh/habitat#876]
According to the docs:

> By default, the studio is destroyed after you exit it; however you can override this by specifying the -R option when calling the hab studio enter subcommand.

Yet I've tried every permutation of this -R with no luck. Not sure if I'm just a little slow, of if that option doesn't exist. 

```bash
hab studio -R -k spuder enter
hab studio -k spuder -R enter
hab studio -k spuder enter -R
```

    ERROR: Invalid option: -R

**Comment by smith** [comment]
Thanks!

For reference, the place in the docs where `-R` is mentioned is https://www.habitat.sh/docs/create-packages-build/#interactive-build

**Comment by akalyaev** [comment]
It is not clear, do you want to add `-R` option for `hab studio enter`? If yes, why it is a bug - not feature?

**Comment by davidwrede** [comment]
@spuder, I have since updated the docs. You can use the `-R` flag when building packages via `hab pkg build`.

See https://www.habitat.sh/docs/create-packages-build/#non-interactive-build for more info and sorry for the confusion earlier.

**Comment by reset** [comment]
@spuder this is because the `-R` flag is only available on Linux, sorry for the confusion! I'm going to close this issue out in favor of #1367
