### ISSUE TITLE
Hab has issues installing package dependencies on Mac

### ISSUE THREAD

**Issue by bscott** [habitat-sh/habitat#879]
Example:
```
➜  hab install core/hab-depot
» Installing core/hab-depot
↓ Downloading core/bzip2/1.0.6/20160612075040
    141.05 KB / 141.05 KB / [========================================================================================] 100.00 % 899.75 KB/s  ✗✗✗
✗✗✗ Can't create '/hab/pkgs/core/bzip2/1.0.6/20160612075040' (libarchive err_code=2)
✗✗✗
```

**Comment by smith** [comment]
Are you in a studio here? If not, it looks like you don't have permissions to write to /hab.

We don't support running packages on Mac as of now, so you can install them (with `sudo` it appears in this case) but not really do anything with them once they are installed.

If this is happening in a studio it must be something else.

**Comment by paulczar** [comment]
I have this same problem trying to run `hab studio` on ubuntu.   I have to run it with `sudo` which is a bit crazy.   Why are we even writing to `/hab` ...  wouldn't `~/.hab` or something be a better option ?

**Comment by metadave** [comment]
related: https://github.com/habitat-sh/habitat/issues/903

**Comment by adamhjk** [comment]
Closing this issue in favor of #903.
