### ISSUE TITLE
sh: 1: cd: can't cd to components/director

### ISSUE THREAD

**Issue by Coopeh** [habitat-sh/habitat#883]
When running make on OS X 10.11.5 with Docker beta for Mac installed, I get the following at the end of the run:

Creating habitat_cargo_1
Creating habitat_cache_keys_1
Creating habitat_etc_1
Creating habitat_cache_artifacts_1
sh: 1: cd: can't cd to components/director
make: **\* [build-director] Error 2

**Comment by smith** [comment]
Not sure why you would be seeing this. If you `make shell` can you `cd` into components/director?

**Comment by Coopeh** [comment]
I can cd to that directory if I use make or make shell, not sure why the make command can't.

**Comment by metadave** [comment]
I'm curious is this works with the Docker Toolbox instead of the Beta.

**Comment by adamhjk** [comment]
Is this still an issue, @Coopeh?

**Comment by Coopeh** [comment]
I'm afraid so, I removed all the images and containers and tried from a fresh git clone today, results pasted here http://pastebin.com/ksVZc3AM, still exactly the same. I can try docker toolbox, but I'm working on some things at the moment using the beta, so it might be a week or so before I get chance.

**Comment by smurawski** [comment]
@Coopeh Please reopen if this is still an issue.  The make shell/dev environment has undergone several revisions.
