### ISSUE TITLE
[builder-web] Upgrade to Angular 2 RC

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#884]
## The Story

As a Habitat engineer, I want be running the latest release candidate of Angular 2, so I can keep up to date with the current features of the software.

## Description

Angular 2 is now release candidate: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc2-2016-06-15

Some things have changed, like the names of the packages and where different things are stored, so there's a little work upgrading.

We should *not* switch to the new router, that's a separate ticket. Use the `router-deprecated` module instead.

## Acceptance Criteria

* The latest release candidate is in package.json and npm-shrinkwrap.json
* Everything in the app works as expected

**Comment by raskchanky** [comment]
https://github.com/habitat-sh/habitat/pull/1213 resolves this.
