### ISSUE TITLE
[builder-web] Upgrade to new Angular 2 Router

### ISSUE THREAD

**Issue by smith** [habitat-sh/habitat#885]
## The Story

An a Habitat engineer, I would like to use the new Angular 2 router, so I can stay current with its features.

## Description

Starting in Angular 2 RC 0 (see #884), there's a new Router (see https://docs.google.com/document/d/1WLSNV3V1AKdwLwRiLuN7JqbPBKQ_S5quRlcT5LPIldw/edit#heading=h.blfh5ya9sf5r).

Upgrade from using the deprecated router to using the new router.

## Acceptance Criteria

* `@angular/router` is used instead of `@angular/router-deprecated`
* The app works as expected

**Comment by smith** [comment]
The docs now have a guide for the new router: https://angular.io/docs/ts/latest/guide/router.html

**Comment by smith** [comment]
Blog post on how the router works: http://victorsavkin.com/post/145672529346/angular-router

**Comment by raskchanky** [comment]
https://github.com/habitat-sh/habitat/pull/1213 resolves this.
