### ISSUE TITLE
Running build outside studio leads to odd log filenames

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#888]
On OSX:

``` shellsession
~/plans/mytutorialapp $ hab pkg build .
...snip...
Script done, file is /src/results/logs/..2016-06-16-145637.log
~/plans/mytutorialapp $ ls -la results/logs/
total 232
drwxr-xr-x  2 miketheman  staff     102 Jun 16 10:57 .
drwxr-xr-x  3 miketheman  staff     272 Jun 16 10:56 ..
-rw-r--r--  1 miketheman  staff  117898 Jun 16 10:56 ..2016-06-16-145637.log
```

**Comment by adamhjk** [comment]
![Yep](http://gif.co/ssRr.gif)

**Comment by akalyaev** [comment]
It is the same on Linux.

I've located the related source file: https://github.com/habitat-sh/habitat/blob/cdcb72335a653d5850dc6bc14ebfdbf6565c6ca2/components/studio/bin/hab-studio.sh#L610,L616

I was thinking about something like this:

```bash
    if [ $name = '.' ]; then
      name="$program"
    fi
```

But it looks like a hack %) I don't know...

Anyway, it seems like there is **no way** to get the program's name if somebody passes `.` as `plan_context`.

**Comment by smacfarlane** [comment]
@akalyaev I was looking at this one as well,  and I think you could do something like 

```
name="$(basename $(realpath $1))"; shift
```

I _think_ the intent behind the naming scheme is tie the log file name to the `$pkg_name`.  The solution above gets us mostly there,  but falls apart in cases like `myapp/habitat/`. I'd argue that that is better than log files named `..TIMESTAMP.log` though 😆 

Unfortunately, using `$program` would always (assuming I'm reading the source correctly) result in log files named `hab-studio.TIMESTAMP.log`, which would be confusing in multi-app repos like the core-plans.

**Comment by smacfarlane** [comment]
Turns out my idea gets you nothing.  I forgot that in the context of the build studio '.' is going to resolve to `/src` by default. Instead of `..TIMESTAMP.log` you'd end up with `src.TIMESTAMP.log`

**Comment by smacfarlane** [comment]
@akalyaev Were you still looking at this or do you mind if I take another swing at it?

**Comment by akalyaev** [comment]
@smacfarlane go ahead, I don't mind

**Comment by juliandunn** [comment]
Closed by #888.

**Comment by miketheman** [comment]
Closed by self?

**Comment by juliandunn** [comment]
Updated :-)
