### ISSUE TITLE
hab version outside studio doesn't match version inside studio

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#889]
On OSX:
```shellsession
~/plans/mytutorialapp $ hab --version
hab 0.7.0/20160614231131
~/plans/mytutorialapp $ hab studio enter
   hab-studio: Creating Studio at /hab/studios/src (default)
   hab-studio: Importing miketheman secret origin key
» Importing origin key from standard input
★ Imported secret origin key miketheman-20160616143833.
   hab-studio: Entering Studio at /hab/studios/src (default)
   hab-studio: Exported: HAB_ORIGIN=miketheman
[1][default:/src:0]# hab --version
hab 0.6.0/20160613074414
```

**Comment by miketheman** [comment]
Likely due to the studio image not being populated with the 0.7.0 release: https://bintray.com/habitat/registry/studio/view

How does that happen?

**Comment by fnichol** [comment]
Looks like I got a little excited on launch day and forgot to push the final publish button on the updated Studio image. So I got that [all fixed up](https://bintray.com/habitat/registry/studio/0.7.0-20160614232531/view).

If you'd like to update to that version, as it is nothing more than a Docker image you can run: `docker pull habitat-docker-registry.bintray.io/studio` on your Mac to get the latest. The tag will be `0.7.0-20160614232531` which is the release of Studio that it is based on.

**Comment by fnichol** [comment]
Thanks for reporting @miketheman!

**Comment by miketheman** [comment]
Awesome, thanks.

- Is there something that needs to be automated during a release cycle to
prevent this oversight?

- Should hab check to see if there is a newer studio and do the pull for
me? I am likely to never remember to do that, nor the registry path.

**Comment by juliandunn** [comment]
1. yes
2. we are considering that, like a `hab studio image-update` or whatever. Let's see who else asks for it :-) and also, it has to be done intelligently and not impact the user if the their network is slow, which is why I'm personally 👎  on the just checking every time

**Comment by fnichol** [comment]
Yes, the automated publishing will start to happen with the launching of the build service.
