### ISSUE TITLE
Why Rust?

### ISSUE THREAD

**Issue by iamthemuffinman** [habitat-sh/habitat#891]
Just curious to know why Habitat was written in mostly Rust? What other languages were considered? What was the final deciding factor for using Rust?

**Comment by reset** [comment]
We evaluated a number of languages before, during, and after the prototype phase. We ultimately chose Rust becasue it is a fast systems programming language without a VM and with memory safety. Rust is also very expressive (see the traits system) and has a solid story for concurrent primitives.

I'm getting this question a lot and I'm really surprised. Out of all the choices that we made during development, to me, choosing Rust was the most obvious and correct decision we made.

small note: In the future, please use our [public forums](http://forums.habitat.sh) or [public Slack](http://slack.habitat.sh) for questions! Thank you for reaching out :smile:

**Comment by iamthemuffinman** [comment]
Thank you! I didn't know there was a Slack team. 😄
