### ISSUE TITLE
[builder-web] Origins failing to load

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#894]
Via Chrome https://app.habitat.sh/#/origins

I created a self-named origin on one computer yesterday.

Today, on another computer, I get:

> Failed to load origins: Cannot read property 'map' of undefined

Source of message is here: https://github.com/habitat-sh/habitat/blob/74b18048a277fc3beac04481c1dea64e9e4f5122/components/builder-web/app/origins-page/OriginsPageComponent.ts#L33-L36

From the second computer, I can see these in the inspector console:

> GET https://willem.habitat.sh/v1/user/origins 401 (Unauthorized)
> GET https://willem.habitat.sh/v1/user/invitations 401 (Unauthorized)

Signing out fully and signing in again works.

**Comment by moutons** [comment]
I had this message crop up this morning (although I didn't switch computers), but as you noted signing out and back in again allowed me to see origins again.

**Comment by stevendanna** [comment]
I saw this again a few minutes ago.

**Comment by smith** [comment]
It has not yet been deployed as of right now.
