### ISSUE TITLE
Unbound Variable on line 105 in install.sh

### ISSUE THREAD

**Issue by josephalan42** [habitat-sh/habitat#8996]
konsole on  develop via  
❯ sudo ./install.sh
./install.sh: line 105: XDG_DATA_HOME: unbound variable

**Comment by mwrock** [comment]
closing for now. We have one `install.sh` file in `components/hab` that has no reference to `XDG_DATA_HOME` and line 105 simply is `need_cmd uname`. I'm suspecting this is coming from a different `install.sh`.
