### ISSUE TITLE
support core/pip for python

### ISSUE THREAD

**Issue by HackerWilson** [habitat-sh/habitat#904]
in `do_build()` I want to install pip deps, but I get these errors:
```
Traceback (most recent call last):
  File "get-pip.py", line 19177, in <module>
    main()
  File "get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    import pip
zipimport.ZipImportError: can't decompress data; zlib not available
```
the problem is core/python didn't compiled with zlib.

so could you please support pip for python?

**Comment by bixu** [comment]
+1

**Comment by iamthemuffinman** [comment]
`core/zlib` is in `pkg_deps`. Does it need to be in `pkg_build_deps` as well?

**Comment by metadave** [comment]
> core/zlib is in pkg_deps. Does it need to be in pkg_build_deps as well?
yes. 

I played with this a few months ago, but had to switch to something else so it was left unfinished. Leaving these links here as I was trying some of the suggested techniques:
http://stackoverflow.com/questions/12344970/building-python-from-source-with-zlib-support
http://stackoverflow.com/questions/6169522/no-module-named-zlib

**Comment by jtimberman** [comment]
@scassiba just added `zlib` support in PR #874 - it's merged and we'll get a new release of the package out.

**Comment by jtimberman** [comment]
Going to wait on SSL support, and possibly pip, for both python and python2 before cutting a new package of either.

**Comment by bixu** [comment]
+1 to `pip` - dependency management is gnarly enough when using Python with `pip` that any ability to wrap it up in a Habitat package would be fantastic (and most Python projects I know of are using `pip`).

**Comment by scassiba** [comment]
`core/python` and `core/python2` now ship pip binaries
