### ISSUE TITLE
plan.sh file not seen when on a mounted disk image path

### ISSUE THREAD

**Issue by walterdolce** [habitat-sh/habitat#923]
Hi all
I am on OS X El Capitan 10.11.5 and I use a mounted disk image (.dmg) for projects, etc. While I was learning Habitat by the documentation, I noticed when entering the studio with `hab studio enter` from `/my/mounted/folder/plans/myproject` then running `build` it would say 

`ERROR: Plan file not found at /src/plan.sh or /src/habitat/plan.sh`

If I follow the docs/tutorial strictly, and I do the same from `~/plans/myproject` it runs.

Is this expected?

**Comment by smith** [comment]
The studio on Mac uses Docker for the studio, and I think the source of your problem might be related to Docker not being able to mount the disk image.

The Dockerfile in the studio does this: https://github.com/habitat-sh/habitat/blob/2b6804fc2e607d6ee5fa01b5a077b74bcb4180db/components/studio/build-docker-image.sh#L90-L91

Can you try making a simple Dockerfile that does the same thing and see if you are able to see your files then? At least we would be able to reproduce what's happening and take it from there.

**Comment by walterdolce** [comment]
@smith 
> Can you try making a simple Dockerfile that does the same thing and see if you are able to see your files then?
What same thing: do you mean what's highlighted in between L90-91?

**Comment by smith** [comment]
Yes, that's what I was thinking.

Are you using Docker with Virtual Box and Docker Machine? If so, you could try looking at the /etc/fstab of your Docker machine to see what it has mounted.

I wasn't able to reproduce this using Docker for Mac Beta.

**Comment by walterdolce** [comment]
> Are you using Docker with Virtual Box and Docker Machine?

Yep. `5.0.22` and `0.7.0` respectively (should that matter).

`/etc/fstab` from within the docker machine says:
```
# /etc/fstab
proc            /proc        proc    defaults          0       0
sysfs           /sys         sysfs   defaults          0       0
devpts          /dev/pts     devpts  defaults          0       0
tmpfs           /dev/shm     tmpfs   defaults          0       0
/dev/zram0  swap         swap    defaults,noauto   0       0
/dev/sda1       /mnt/sda1       ext4     noauto,users,exec    0 0 # Added by TC
/dev/sda2       none            swap     defaults             0 0 # Added by TC
/dev/sr0        /mnt/sr0        auto     noauto,users,exec    0 0 # Added by TC
```
In the meantime I tried with using a separate Dockerfile but it didn't mount the content over.

**Comment by fnichol** [comment]
@walterdolce From what I recall, the docker-machine instances mounts the entire `/Users/<your_user>` into the virtual machine in order to get this bind mount trick to work. In other words, the full path of `/Users/fnichol/Projects/habitat-sh/habitat` is mounted and present inside the boot2docker instance. Both horrifying and super clever to make the resulting user behavior of `docker run … -v `pwd`:/mnt …` work 80%+ of the time.

There may be a way to add additional local FS mounts into the docker-machine instance, and the Docker Beta prereleases may even have different behavior--I haven't had a chance to switch over. Does this make sense?

**Comment by walterdolce** [comment]
@fnichol it does make sense. My mounted disk image resides on `/Volumes`, simlinked somewhere in `/Users/me/...`.

> There may be a way to add additional local FS mounts into the docker-machine instance

I will investigate this and let you know whether we have a final solution to this. Until then, if anyone does it before me or knows the answer please post it here! ;)

**Comment by smurawski** [comment]
Another option would be to use the `HAB_DOCKER_OPTS` environment variable to add another volume mounting (from https://github.com/habitat-sh/habitat/pull/1410 - and yeah, it's `HAB_DOCKER_OPTS` now, not `OPS` as in that PR. :)  ).
