### ISSUE TITLE
be able to modify and rebuild from plan.sh without rerunning a full build.

### ISSUE THREAD

**Issue by paulczar** [habitat-sh/habitat#927]
Doing a build of mariadb takes 30+ minutes,  it would be great if I could update stuff in the `plan.sh` that does not affect the build and thus skip the do_build() step.

It would be cool if habitat could autodetect that I didn't change anything critical to the build, but I'd be okay with passing a flag like `--skip-build` or something.

**Comment by adamhjk** [comment]
Interesting. The hard part here is being certain that you have a build that is easy to reproduce. 

Something like a "TAINTED" file might work, along with a flag that modifies the current latest package on disk. Once you do it, it drops the TAINTED file, and that package is never allowed to be built into a `.hart`.  

What do you think, @fnichol ?

**Comment by paulczar** [comment]
The major use case here is updating the start hooks or config templates and not having to rerun a full build.

My current workflow to get around this is to export to docker, figure out what I did wrong,  modify the files in docker, test, then copy and paste any changes I make back to the hab files and rebuild.

This is cumbersome and results in as much human (copy/paste) error as it solves.

**Comment by smith** [comment]
If you override `do_download` and `do_verify`, a build will use what's left over in /hab/cache/src from last time, so, with some judicious disabling of things your plan does, you can speed getting to the part when you actually have a package.

This is not the ideal situation, but I've found it to be useful.

**Comment by fnichol** [comment]
Hm, this is an interesting use case that I suspect is only for development time. I can certainly empathize with the long waits--gcc is excruciatingly long and worse when the test suite is activated. At the moment the `build` program isn't super focused on idempotent/convergent behavior--it's more concerned with a from-zero clean build. @smith's trick of having a `do_download() { return 0; }` and `do_verify() { return 0; }` is not a bad idea and something that hadn't even occurred to me after months of building software!

What I've done is run the service directly inside of the Studio (using a `hab studio enter` and the running `build .`) to get some of the post-install things right before circling back. That's a main reason why `vim` and `mg` (micro emacs) is present inside a Studio. Once the package is built, it is also installed in its usual location, meaning that you can change up anything in the spirit of "working on it".

**Comment by juliandunn** [comment]
@paulczar is your use case solved by the `--config-from` flag that shipped in Habitat 0.10.x?

**Comment by fnichol** [comment]
Good point, would be excellent if that addresses the 80% case.

**Comment by juliandunn** [comment]
I'm going to close this for now under the assumption we captured the use case by adding the `--config-from` flag. If not, let's get another issue opened for other use cases.
