### ISSUE TITLE
studio and docker-machine cloud drivers don't really play well together

### ISSUE THREAD

**Issue by katzj** [habitat-sh/habitat#948]
When using hab-studio with docker-machine, the local filesystem path for ~/.hab/cache and the current source dir are set up to be mounted as volumes in your docker container.  This works with VirtualBox and VMWare as docker-machine sets up shared folders accordingly for the location of where your home directory is and so the directory can be mounted from the VM into the container.  When using a cloud driver, there isn't the concept of shared folders and so this doesn't work.  When it fails, you just get something like

```
[jeremy@yavin foo]$ RUST_LOG=debug hab   studio -vv -n new
DEBUG:hab::config: Loading CLI config from /Users/jeremy/.hab/etc/cli.toml
DEBUG:hab::command::studio: Setting default origin katzj via CLI config
DEBUG:hab::command::studio::inner: Propagating environment variable into container: HAB_ORIGIN=katzj
DEBUG:hab::exec: Calling execv: ("/usr/local/bin/docker") ["run", "--rm", "--tty", "--interactive", "--privileged", "--env", "HAB_ORIGIN=katzj", "--volume", "/var/run/docker.sock:/var/run/docker.sock", "--volume", "/Users/jeremy/.hab/cache/keys:/hab/cache/keys", "--volume", "/Users/jeremy/src/hab/plans/foo:/src", "habitat-docker-registry.bintray.io/studio", "-vv", "-n", "new"]
   hab-studio: Creating Studio at /hab/studios/src (default)
'/hab/studios/src/lib64/lib' -> 'lib'
'/hab/studios/src/usr/lib64/lib' -> 'lib'
'/hab/studios/src/var/lock' -> '/run/lock'
'/hab/studios/src/etc/mtab' -> '/proc/self/mounts'
changed ownership of '/hab/studios/src/var/log/lastlog' to 0:13
mode of '/hab/studios/src/var/log/lastlog' changed to 0664 (rw-rw-r--)
mode of '/hab/studios/src/var/log/btmp' changed to 0600 (rw-------)
'/etc/hosts' -> '/hab/studios/src/etc/hosts'
'/etc/resolv.conf' -> '/hab/studios/src/etc/resolv.conf'
   hab-studio: Importing katzj secret origin key
» Importing origin key from standard input
✗✗✗
✗✗✗ Crypto error: Unsupported key version: ✗✗✗
✗✗✗
```

**Comment by katzj** [comment]
The driver being used can be detected with 'docker-machine inspect $DOCKER_MACHINE_NAME' and looking at the DriverName in the json.  That would at least allow for a nicer warning as it's entirely not obvious what's going wrong

**Comment by adamhjk** [comment]
@davidwrede it's probably worth updating the documentation to point out that using the cloud providers aren't supported.

Would absolutely accept a PR that fails if you try and use a machine with the wrong driver.

**Comment by fnichol** [comment]
Sadly, @adamhjk is right here--doing Docker volume mounting across hosts isn't something that's supported in the Docker client itself (as far as I know). Additionally, these days we're recommending Docker for Mac (and Docker for Windows) as the Docker companion software. While these Docker clients technically can still target a remote Docker host it just isn't feasible to support the volume mounting in this setup. It is far better (and faster) at that point to either work in a Linux VM or directly on the remote host and use the native studios (i.e. no Docker in the workflow).
