### ISSUE TITLE
Automatic Environment Variable Dependency Propagation

### ISSUE THREAD

**Issue by fujin** [habitat-sh/habitat#949]
I had to set the Git config environment variable `GIT_SSL_CAINFO` to use `go get` in a plan that depends on `core/go` (cacerts), would it be possible to automatically inject this?

e.g.:

``` shell
do_prepare() {
    export GIT_SSL_CAINFO=$(pkg_path_for cacerts)/ssl/certs/cacert.pem
    build_line "Setting GIT_SSL_CAINFO=$GIT_SSL_CAINFO"

    # XXX(fujin): Figure out GOPATH convention for Habitat
    export GOPATH=${pkg_prefix}
    go get -u github.com/FiloSottile/gvt
}
```

**Comment by adamhjk** [comment]
I think this is an obvious feature to add. Ideally, this would enable software to set *both* build and runtime environment variables.

Basically, if we allowed you to do:

```
cat $pkg_prefix/BUILD_ENV <<-EOF
GIT_SSL_CAINFO=$(pkg_path_for cacerts)/ssl/certs/cacerts.pem
```

In the `core/git` package or whatnot, and then when we built the top level package, we walked for every BUILD_ENV and just eval-ed them, this would work.

For RUNTIME_ENV, we would need the supervisor itself to set those same variables. I think this would solve a whole class of emergent bugs.

@fnichol - what do you think?

**Comment by metadave** [comment]
examples of other env vars that would be super useful to propagate:  [`JAVA_HOME`, `CLASSPATH`, `M2_HOME`](https://github.com/habitat-sh/habitat/blob/master/plans/maven/README.md) etc

**Comment by fnichol** [comment]
Not a bad idea! Better to encode that into the plans themselves (if possible) than to figure out how to propagate certain environment variables into the Studio.

**Comment by smith** [comment]
Related proposal on Discourse: https://forums.habitat.sh/t/allow-env-vars-to-be-passed-from-plan-to-runtime/264/5

**Comment by smartb-pair** [comment]
Ran into this today around `SSL_CERT_PATH` needed by a Python app (`wal-e`).
