### ISSUE TITLE
hab pkg install does not work through a proxy

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#950]
I tried `hab` at work through a corporate proxy and it can't download any of the packages, while at home it worked.

`rustup` [had this issue](https://github.com/rust-lang-nursery/rustup.rs/issues/35) before too, it uses curl now, like `cargo`.

**Comment by dlakatos847** [comment]
I think it has to do with #892

**Comment by lilianmoraru** [comment]
I added info into the initial issue, thanks.
