### ISSUE TITLE
Sodiumoxide cargo config override can be removed

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#952]
In `components/core/Cargo.toml` you have a note that says that the `components/.cargo/config` can be removed when `https://github.com/dnaq/sodiumoxide/pull/103` is merged, and it is.

**Comment by metadave** [comment]
Thanks for submitting this issue!

I'll take a look. While https://github.com/dnaq/sodiumoxide/pull/103 has been merged, sodiumoxide still doesn't have a higher level hashing API that we can use without `unsafe` blocks. This cargo hack allows us to use high level and low level sodiumoxide/libsodium-sys functions at the same time. Also, there have been some recent changes to `cargo` that we might be able to use.

**Comment by metadave** [comment]
I submitted an issue to the sodiumoxide repo to see if there are plans to implement high level `crypto_generichash_*` functions: https://github.com/dnaq/sodiumoxide/issues/139
