### ISSUE TITLE
[feature request] plan.sh generator

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#953]
Something like `hab create {planname}` or such that would generate a plan.sh with some boilerplate variables.
Maybe similar to Homebrew's [create](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/cmd/create.rb) - where passing in a github release tag url activates a lot of the default variables

This would lower the "getting started" bar for a new plan.

**Comment by miketheman** [comment]
Added value: tries to get the correct sha during invocation - either with a curl header, or some other trickery.

**Comment by miketheman** [comment]
Apparently there's _something_ already here: https://github.com/habitat-sh/habitat/blob/master/plans/plan-tmpl.sh

**Comment by smith** [comment]
We originally had `make new-plan plan=foo` in the plans/ directory, but removed it with the expectation that we would come up with something more fully integrated in the future. The future is now!

**Comment by adamhjk** [comment]
We should do this.

**Comment by metadave** [comment]
@rmoshier and I are going to take a look at this next week.

**Comment by metadave** [comment]
For the first iteration, we'll create a subcommand titled `hab pkg create <PKG_NAME>`, which does the following:
- bail if a directory called PKG_NAME exists, otherwise, create a directory in the cwd titled PKG_NAME.
- create a `PKG_NAME/plan.sh` file with the following contents:

```
pkg_name=<PKG_NAME>
pkg_origin=<HAB_ORIGIN env var or some other value?>
pkg_version=0.0.1
pkg_description="The package description"
# Please choose a license from http://spdx.org/licenses/
pkg_license=('Apache-2.0')
pkg_maintainer="The Habitat Maintainers <humans@habitat.sh>"
pkg_source=http://some_source_url/releases/${pkg_name}-${pkg_version}.tar.gz
pkg_shasum=TODO
pkg_bin_dirs=(bin)
pkg_build_deps=(core/make core/gcc)
pkg_deps=(core/glibc)
```

- The subcommand `hab pkg create` may be aliased to `hab create`.
- we're not targeting any other package template files for this iteration (`default.toml`, `config/**` etc), but we can certainly discuss them in followup issues + PR's.
- a future iteration could take a URL as an additional argument and calculate the correct `pkg_shasum`

**Comment by jtimberman** [comment]
A few ideas I brainstormed

Run in the current directory:

```
hab plan create [PLAN]
```

If `PLAN` is not specified:

A `habitat` directory is created with a templated `plan.sh` using the `PWD` as the `pkg_name`. This is intended to be used inside an application.

If `PLAN` is specified:

A `PLAN` directory is specified with a templated `plan.sh` using `PLAN` as the `pkg_name`. This is intended to be used in the `core-plans` repository or other similar collections of Habitat plans.

The `pkg_origin` will be set from `~/.hab/etc/cli.toml`.

**Comment by miketheman** [comment]
Should this be a top-level cli command? As @metadave pointed out earlier, `hab pkg create foo` seems to map nicely with my brainspace of where I would find a command like this.

**Comment by metadave** [comment]
we've been sticking with `hab [noun] [verb]`, as noted in @juliandunn's post [here](http://www.juliandunn.net/2016/08/09/designing-great-command-line-user-experiences/).

We can alias frequently used commands, for example:
```
ALIASES:
    apply      Alias for: 'config apply'
    install    Alias for: 'pkg install'
    setup      Alias for: 'cli setup'
    start      Alias for: 'sup start'
```

**Comment by metadave** [comment]
also: ping @ryankeairns

**Comment by miketheman** [comment]
Then `hab pkg createplan` ??

**Comment by ryankeairns** [comment]
A few thoughts:

1. This whole concept is 💯 I'm excited to see this come together so quickly as it something we had hoped to have around launch
2. I had originally assumed `hab plan create` but as discussed above, there is a natural extension from from `hab package` and I personally like 'hab package create' with future possible flags for different app flavors --java, etc. Also, you could get a bit more of the tree (as stated in the future) so it's more than just the plan
3. In a future iterations we could add the default.toml, hook and run folders, etc. That said, I'd propose everything gets put into a `/habitat/plan.sh` directory. This is not simply cleaner, but allows for us to more easily located habitat files that we may want to auto-detect for certain commands (as we do with `hab setup` currently).

Great work, look forward to seeing it come alive!

**Comment by metadave** [comment]
@miketheman I'm 👎  on `hab pkg createplan`, as `createplan` combines verb + noun.

**Comment by miketheman** [comment]
@metadave I'm all ears for a better verb, I'm 👎 for creating more top-level namespaces without a compelling reason to do so.

**Comment by metadave** [comment]
I don't understand, is there a new top-level namespace?

**Comment by miketheman** [comment]
The proposal of `hab plan create` introduces a new namespace `plan`.

**Comment by metadave** [comment]
https://github.com/habitat-sh/habitat/issues/953#issuecomment-239907833 item 2 seems to indicate that the command will be `hab pkg create`

**Comment by ryankeairns** [comment]
@metadave @miketheman Hey guys, after further thought and discussion we'd prefer to use 'hab plan create' . The reason is that 'hab pkg create' insinuates you're creating an actual package and other commands for the pkg noun also deal with 'real' packages.

It seems quite likely we'll be iterating on this new 'plan' noun in the near future and that it warrants its own place. 

Thanks for sifting through this discussion, it all pays off down the road when wet judicious up front!

**Comment by bdangit** [comment]
I have been hacking away on this. https://github.com/bdangit/habitat/tree/add-hab-plan-create

**Comment by Hoverbear** [comment]
While waiting for a flight I implemented the bulk of a `hab pkg init` command. @bdangit maybe we can collaborate and get something nice this week for a PR? Will be on slack monday after flying!

**Comment by bdangit** [comment]
Hey @hoverbear 

Sure! Although I'm computerless for the next 4 days. Tuesday I'll be on late. 

Also you mean `hab plan init`?

**Comment by Hoverbear** [comment]
@bdangit Hm I suppose that would work too. :) I was offline so couldn't reference this issue.

**Comment by juliandunn** [comment]
In the next release, thanks to #1416, we will be shipping a `hab plan init`.
