### ISSUE TITLE
Copy/paste doesn't work in Try Habitat interactive console

### ISSUE THREAD

**Issue by metadave** [habitat-sh/habitat#957]
reported [here](https://forums.habitat.sh/t/about-the-user-experience-category/25/6?u=metadave)

**Comment by ryankeairns** [comment]
Just noting that some related work was done recently towards this capability - https://github.com/habitat-sh/habitat/pull/759 ...we ought to re-test once we get this backlog of stuff pushed out and see if it has already been fixed.

**Comment by smith** [comment]
@ryankeairns that post was reported after the change to allow copy/paste was pushed out. I'm pretty sure the browser support of the thing we're using is the culprit.

**Comment by ryankeairns** [comment]
OK - seems the case with #604 as well... these could result in significant gut jobs of this feature. The assigned Icebox tag seems appropriate given those elements.

**Comment by eeyun** [comment]
We haven't had any update on this issue since Jun and haven't had any more reports of issues along these lines. If this is still an issue we can reopen but I'm going to close for now.
