### ISSUE TITLE
Document build log behavior (for hab pkg build) and record() function

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#961]
Some software takes a long time to build.  When working on a plan for such software, I've found myself doing this:

```
build /src/mysoftware 2>&1 | tee build.log
```

It might be nice if the build command had a flag that did that for me.

**Comment by adamhjk** [comment]
Would happily take this. Closing the issue for hygiene.

**Comment by fnichol** [comment]
@stevendanna ah my friend, I have you covered! Inside each Studio, there is a `record()` [shell function](https://github.com/habitat-sh/habitat/blob/master/components/studio/bin/hab-studio.sh#L604-L622) which takes a session name and the command to run (Usage: `record <SESSION> [CMD [ARG ..]]`).

I found that `tee` just wasn't cutting it sometimes and auto-naming log files was getting tedious. The `record()` function will append a timestamp to the log file so you don't nuke a previous build. It uses `script` under the covers, so ansi coloring gets captured, but that isn't impossible to remove in any case.

So, try out `record mysoftware build /src/mysoftware` and see if that's what you're after.

As a side note, the `hab pkg build` (provided under the covers by `hab studio build`) automatically wraps the build process with this helper to give you a log for each build command.

**Comment by fnichol** [comment]
If that is helpful, perhaps the closing condition is appropriate documentation?

**Comment by stevendanna** [comment]
💯 Nice.  That record helper really helps.  Good enough for me, I'd be +1 on closing this and getting that documented.
