### ISSUE TITLE
CPPFLAGS not set by default

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#962]
I've hit a few software packages where I need to set CPPFLAGS to get it to compile properly. Usually this is in the form of:

```
export CPPFLAGS="$CPPFLAGS $CFLAGS"
```

Would it make sense to set CPPFLAGS by by default like habitat does for CFLAGS?

**Comment by metadave** [comment]
related: https://github.com/habitat-sh/habitat/issues/926

**Comment by adamhjk** [comment]
This was fixed.
