### ISSUE TITLE
Ctrl+C mid-download doesn't quit

### ISSUE THREAD

**Issue by miketheman** [habitat-sh/habitat#964]
On OSX 10.11.1, docker 1.12.0-rc2, hab 0.7.0

```
$ hab pkg build .
...
» Installing core/cmake
→ Using core/gcc-libs/5.2.0/20160612075020
→ Using core/glibc/2.22/20160612063629
→ Using core/linux-headers/4.3/20160612063537
↓ Downloading core/cmake/3.5.2/20160612153830
    351.05 KB / 10.93 MB \ [>-----------------------------] 3.14 % 1.54 MB/s 7s ^C
Session terminated.
    2.59 MB / 10.93 MB \ [=======>-----------------------] 23.73 % 2.04 MB/s 4s ^C
Session terminated.
    3.23 MB / 10.93 MB / [=========>---------------------] 29.59 % 1.73 MB/s 4s ^C
Session terminated.
    3.42 MB / 10.93 MB / [=========>---------------------] 31.31 % 1.66 MB/s 5s ^C
Session terminated.
    3.48 MB / 10.93 MB / [=========>---------------------] 31.88 % 1.62 MB/s 5s ^C
Session terminated.
    3.59 MB / 10.93 MB \ [==========>--------------------] 32.88 % 1.49 MB/s 5s ^C
Session terminated.
    3.64 MB / 10.93 MB / [==========>--------------------] 33.31 % 1.43 MB/s 5s ^C
Session terminated.
...
```

Some sort of control characters should interrupt the session and terminate it, instead of allowing it to continue.

**Comment by adamhjk** [comment]
Adding this to the "Next" queue. We should figure out why that thread isn't terminating.

**Comment by fnichol** [comment]
@miketheman I have noticed the same and am suspecting that the `docker attach` (i.e. the container) isn't propagating the signal down to the `build` program (and thus down to its child processes such as wget). In short, am I frustrated with this too 😄 

IIRC I didn't see this running the same on Linux (i.e. without Docker in mix) which is what lead me to this hypothesis.
