### ISSUE TITLE
Search for depot in the packages does not result in hab-depot

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#967]
In `Search Packages`, if you type **depot**, it won't find **hab-depot**.
The search seems a bit sensitive.
Of course, searching for **hab-depot** gives correct results.

**Comment by reset** [comment]
This is working as intended. It's actually an auto-complete more than a search. In the future, we may add tags/categories to help people find software via another means. Thanks for the ticket!
