### ISSUE TITLE
hab-depot is built in debug mode

### ISSUE THREAD

**Issue by lilianmoraru** [habitat-sh/habitat#968]
I don't know if it is intentional but in `do_build()` of `hab-depot`, the build is run with `cargo build`, not `cargo build --release`, generating a debug binary/unoptimized binary.
Also, if it is changed to `cargo build --release`, the parallel codegen should be disabled because it generates less optimized code.

**Comment by adamhjk** [comment]
We're building everything in debug mode on purpose right now, as we want to be able to shake out any critical runtime bugs. We plan to flip when we've had enough folks using the `hab-sup` in production.

Let us know if you encounter performance/optimization problems in the meantime, and we'll consider turning this sooner.

Closing this request, but feel free to re-open it if you have questions or concerns.

**Comment by lilianmoraru** [comment]
I thought about this but then I guessed that may be this was an internal `plan` that moved to `core/` at a later date.

I am ok with the issue being closed.
