### ISSUE TITLE
utilize existing distributed key/value systems

### ISSUE THREAD

**Issue by paulczar** [habitat-sh/habitat#971]
Many of us are already running etcd or consul,  it would be great if hab supervisor could be set to utilize their APIs rather than doing its own gossip ring thing.

If I could use consul, then it opens up the possibilties of my other systems already using consul to become aware of my habitat apps which would be pretty delightful.

**Comment by adamhjk** [comment]
What kind of integration makes sense here? 

We won't offer consul/etcd/zookeeper as alternative backends to the ring - when we did that originally, the results were habitat services that behaved differently according to your service discovery choices, which violates a design goal (packages must behave the same way, everywhere). 

What you could do is write a service that literally translates from the rings state to etcd or consul. Would that help?

**Comment by paulczar** [comment]
My thoughts were to (initially at least) just use their API to put/get/etc key values to store its metadata.     something like `hab sup start --kv-provider=consul://10.3.3.3:5800 --kv-root=/service/habitat/myapp`    then if I want to get more creative I can have my app itself ( or a sidecar ) work with say consul to add healthchecks, or other more consul specific things.

**Comment by paulczar** [comment]
I guess you could still run your own gossip ring and allow for settings to also publish service and healthcheck data to consul, or collect credentials from vault.  that way consul is participating in the app configuration directly but is being notified or consulted by hab as needed.

**Comment by adamhjk** [comment]
I'm pretty suspicious of adding that kind of specific integration into habitat's supervisor. If your only goal was to have the service groups publish into consul, I think you could accomplish that with a microservice that joins the ring, watches for changes in the census, and updates consul.

I think that's really the path forward here. We would be happy to work with you on getting something like that spiked.

**Comment by styk-tv** [comment]
My thought was to use Redis with Webdis snap on http://webd.is/ ?  Either way a Rest API as part of the solution where I can retrieve but also store custom data and learn about the infra. Single point of truth (distributed way) 

Is there a way to Rest query The Ring with ability to store additional data already?

**Comment by tomrobison** [comment]
I agree that reading and writing to the non-default key store should be a separate service.  This would allow for a better separation of concerns between the sup and "the way you update config settings".

**Comment by adamhjk** [comment]
@styk-tv each supervisor has a REST API already, and the `gossip` endpoint has everything the ring knows. So it will be very easy to build that service.

**Comment by adamhjk** [comment]
Unless @paulczar wants to discuss this further, I'm going to close this request. FWIW, as the decider, I would totally take a service into the core components that knows how to plug from the REST API in a supervisor to consul/etcd/zookeeper.

**Comment by reset** [comment]
As @adamhjk already pointed out, we originally had this behaviour before deciding to implement our own gossip ring. We ultimately made this choice to ensure that Habitat behaved as expected regardless of the guarantees that the underlying gossip ring was bound by.

The http-gateway that is made available on the supervisor contains *all* of the information in the gossip ring under the `/butterfly` endpoint in the current master branch. I would suggest consuming that endpoint if you need that data.
