### ISSUE TITLE
pkg-config integration for plan-build

### ISSUE THREAD

**Issue by stevendanna** [habitat-sh/habitat#972]
Opening this for discussion since I'm not sure it is a good idea.

Some packages have configuration scripts that use pkg-config extensively to find require dependencies.  While `core/pkg-config` exists, it usually also requires setting up PKG_CONFIG_PATH manually.  For example:

```
    PKG_CONFIG_PATH="$(pkg_path_for libpng)/lib/pkgconfig"
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(pkg_path_for zlib)/lib/pkgconfig"
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(pkg_path_for libpng)/lib/pkgconfig"
    PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:$(pkg_path_for pixman)/lib/pkgconfig"
    export PKG_CONFIG_PATH
```

It would be nice for a plan to indicate that it exports pkg-config configuration and then use that to populate PKG_CONFIG_PATH automatically.

Is this too far over the "too much magic" line?  An advantage is that more software packages will "just work" without overriding do_build().  On the other hand, it is more magic that the user doesn't become aware of until it bites them somehow.

**Comment by adamhjk** [comment]
I could go either way on this. On the one hand, it's nice to let the configure magic do its thing. On the other, the current system of exporting CFLAGS, LDFLAGS, etc. cover most of this ground, and where they don't, you often have options to take care of things.

I would take a patch to `hab-plan-build.sh` that implements dropping a PKG_CONFIG_PATH metadata from a configuration setting akin to `pkg_pconfig_dirs=(lib/pkgconfig)`.

Closing this issue, but feel free to write the patch.
