### ISSUE TITLE
studio plan is dependent on removed package - hab-static

### ISSUE THREAD

**Issue by tomrobison** [habitat-sh/habitat#974]

**Comment by tomrobison** [comment]
A nested dependency from busybox-static. https://github.com/habitat-sh/habitat/blob/master/components/studio/plan.sh#L8

**Comment by fnichol** [comment]
@tomrobison I might not be understanding this correctly but…I don't see `core/hab-static` present anymore in this Plan. However, the `core/busybox-static` package is used by this plan for sure.
