### ISSUE TITLE
Document required structure of run hook

### ISSUE THREAD

**Issue by jamesc** [habitat-sh/habitat#989]
The run hooks needs to always do a couple of things - 

* `exec 2>&1`
* Always `exec` the command to avoid a bash shell between the supervisor and child

This should be documented. Also not all of our plans follow this right now - e.g
* https://github.com/habitat-sh/habitat/blob/master/plans/polipo/hooks/run
* https://github.com/habitat-sh/habitat/blob/master/plans/artifactory-pro/hooks/run

**Comment by smith** [comment]
Note that if you just specify `pkg_svc_run` in a plan, and don't specify a run hook, what it generates is this: https://github.com/habitat-sh/habitat/blob/66d1c61048a2bff5ee6db2f9f1cb08dfb633b84b/components/plan-build/bin/hab-plan-build.sh#L1979-L1996

**Comment by schisamo** [comment]
^^ Fixed `artifactory-pro`

**Comment by schisamo** [comment]
@davidwrede Can you work with @juliandunn on creating some content in the docs?

**Comment by davidwrede** [comment]
@schisamo, yup. Working on other doc sets atm, but will circle back to the Habitat docs in a day or two.

**Comment by adamhjk** [comment]
We should make most people use `pkg_svc_run`, not write a run hook. It's the right thing (tm) for 90% of software.
