### ISSUE TITLE
hab studio enter: Doesn't create valid chroots on non-FHS-compliant systems

### ISSUE THREAD

**Issue by rushmorem** [habitat-sh/habitat#994]
When I run `hab studio enter` I get the following instead:-

``` text
   hab-studio: Creating Studio at /hab/studios/src (default)
   hab-studio: Importing root secret origin key
» Importing origin key from standard input
✗✗✗
✗✗✗ No such file or directory (os error 2)
✗✗✗
```

This is the case with both the latest released binaries (0.7.0) and current master. As a result I can't build packages nor export existing packages to my preferred container format (ACI).

**Comment by metadave** [comment]
This looks like https://github.com/habitat-sh/habitat/issues/736, which platform are you running the `hab` command on?

**Comment by rushmorem** [comment]
Yes it did look to me like that same issue. I'm on Linux, specifically `NixOS`.

**Comment by rushmorem** [comment]
However, in my case, `/hab/pkgs` already exists so the workaround mentioned there doesn't apply.

**Comment by metadave** [comment]
can you paste the output of 

        RUST_LOG=debug hab studio enter

?

**Comment by rushmorem** [comment]
Here:-
```text
[root@coordinator:/src]# RUST_LOG=debug hab studio enter
DEBUG:hab::config: Loading CLI config from /hab/etc/cli.toml
DEBUG:hab::analytics: Event: v=1&tid=UA-6369228-7&cid=7643fa6e-0aa8-4ea1-9f24-5f9fe313cc4d&t=event&aip=1&an=hab&av=0.7.0&ds=cli--hab&ec=invoke&ea=hab--studio--enter
DEBUG:hab::analytics: Creating directory /hab/cache/analytics
DEBUG:hab::analytics: Creating file /hab/cache/analytics/event-1467034932.152960764.txt
DEBUG:hab::command::studio: Setting default origin root via CLI config
DEBUG:hab::exec: Calling execv: ("/hab/pkgs/core/hab-studio/0.7.0/20160614232531/bin/hab-studio") ["enter"]
   hab-studio: Creating Studio at /hab/studios/src (default)
   hab-studio: Importing root secret origin key
DEBUG:hab: clap cli args: ["/hab/pkgs/core/hab-studio/0.7.0/20160614232531/libexec/hab", "origin", "key", "export", "--type", "secret", "root"]
DEBUG:hab: remaining cli args: []
DEBUG:hab: clap cli args: ["/hab/pkgs/core/hab-studio/0.7.0/20160614232531/libexec/hab", "origin", "key", "import"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_core::crypto::keys: checking file: root-20160627122801.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: core-20160612031944.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: root-20160627122801.sig.key
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys::sig_key_pair: Attempting to read key name_with_rev root-20160627122801 for root
DEBUG:hab::command::origin::key::export: Streaming file contents of secret /hab/cache/keys/root-20160627122801.sig.key to standard out
» Importing origin key from standard input
DEBUG:habitat_core::crypto::keys::sig_key_pair: Writing temp key file /hab/studios/src/hab/cache/keys/root-20160627122801.sig.key.438002e967eb
✗✗✗
✗✗✗ No such file or directory (os error 2)
✗✗✗
```

**Comment by rushmorem** [comment]
Please note that though `hab` reports version `0.7.0`, I actually compiled it from the current master `94b8ba1bb75c6f7873c89133473a0f95c587fe39`.

**Comment by metadave** [comment]
after you run this command, does the `/hab/studios/src/hab/cache/keys/` directory exist? If not, what directories 

also, I'm curious why you ran `mkdir /src && cd /src`?

**Comment by rushmorem** [comment]
Yes the directory does exist but it's empty. I don't have any special reason to do this from the `/src` directory. I only did it because I was trying to replicate @adamhjk's demo during the announcement (I noticed he was in `/src` dierctory) plus it gives me a clean workspace to work from.

**Comment by rushmorem** [comment]
I have tried this on `ArchLinux` and I am able to get into the studio (even though it does seem to run into a similar error?). Here is the output:-
```text
[root@arch src]# RUST_LOG=debug hab studio enter
DEBUG:hab::config: Loading CLI config from /hab/etc/cli.toml
DEBUG:hab::command::studio: Setting default origin root via CLI config
DEBUG:hab::exec: Calling execv: ("/hab/pkgs/core/hab-studio/0.7.0/20160614232531/bin/hab-studio") ["enter"]
   hab-studio: Creating Studio at /hab/studios/src (default)
   hab-studio: Importing root secret origin key
DEBUG:hab: clap cli args: ["/hab/pkgs/core/hab-studio/0.7.0/20160614232531/libexec/hab", "origin", "key", "export", "--type", "secret", "root"]
DEBUG:hab: remaining cli args: []
DEBUG:habitat_core::crypto::keys: checking file: core-20160612031944.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: root-20160628113922.pub
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys: checking file: root-20160628113922.sig.key
DEBUG:habitat_core::crypto::keys: valid key suffix
DEBUG:habitat_core::crypto::keys::sig_key_pair: Attempting to read key name_with_rev root-20160628113922 for root
DEBUG:hab::command::origin::key::export: Streaming file contents of secret /hab/cache/keys/root-20160628113922.sig.key to standard out
DEBUG:hab: clap cli args: ["/hab/pkgs/core/hab-studio/0.7.0/20160614232531/libexec/hab", "origin", "key", "import"]
DEBUG:hab: remaining cli args: []
» Importing origin key from standard input
DEBUG:habitat_core::crypto::keys::sig_key_pair: Writing temp key file /hab/studios/src/hab/cache/keys/root-20160628113922.sig.key.421a46e96a1c
DEBUG:habitat_core::crypto::keys::sig_key_pair: New content hash matches existing file /hab/studios/src/hab/cache/keys/root-20160628113922.sig.key hash, removing temp key file /hab/studios/src/hab/cache/keys/root-20160628113922.sig.key.421a46e96a1c.
DEBUG:habitat_core::crypto::keys::sig_key_pair: Can't find public key for name_with_rev root-20160628113922: No such file or directory (os error 2)
★ Imported secret origin key root-20160628113922.
   hab-studio: Entering Studio at /hab/studios/src (default)
   hab-studio: Exported: HAB_ORIGIN=root

[1][default:/src:0]# 
```

**Comment by rushmorem** [comment]
I found out the reason for this. When creating a chroot for studio using the default type, `hab` assumes that the filesystem is FHS compliant, which `NixOS` isn't. In the end, the directory structure created isn't valid, for example:-
```text
├── lib
│  └── lib -> /hab/studios/src/lib/lib
│     └── <Too many levels of symbolic links (os error 40)>
├── lib64 -> /hab/studios/src/lib
```
So `hab studio` can't find the libraries it needs in the chroot which is most likely what's causing the `No such file or directory (os error 2)`. If I create an FHS clompliant chroot on `NixOS` I'm able to run `hab studio enter` just fine.

**Comment by rushmorem** [comment]
Just an idea... Since we already have all the libraries we need, say `core/libsodium`, how about we install those and use them when creating a chroot (rather than relying on the underlying system). Some systems may not even have all the libraries installed by default even if they are FHS compliant. I'm guessing that's why I got that warning on `ArchLinux`...

I think another advantage to doing it this way is it makes it easier to support other environments like Windows (for those who care). Is this something feasible?

**Comment by chetan** [comment]
I ran into this as well. I was trying to build a hab package from within a hab environment ( and I guess it turns out this environment is far too minimal. I did a bunch of stracing but was still unable to figure out exactly where the `No such file or directory (os error 2)` was coming from. It seems to create the key at a temp location and then unlink it before erroring out. I guess it failed some check after writing the temp key, but not sure.

**Comment by rushmorem** [comment]
I have just realised that what I was proposing in https://github.com/habitat-sh/habitat/issues/994#issuecomment-231108865 is actually the documented behaviour.

https://www.habitat.sh/docs/concepts-studio/ says the following:-

> The Habitat Studio is a clean, self-contained, minimal environment in which you can develop, build, and package software that is free from any upstream operating system distribution. All tools and dependencies included in the Studio are installed through Habitat packages, thus preventing any unwanted dependencies from being used by your package.

This is _not_ the current behaviour. Currently the default studio relies a lot on the underlying operating system even for libraries like `libsodium`.

**Comment by sfiggins** [comment]
I just ran into a similar error after upgrading to hab 0.13.0.  I believe this was confusion from a previous setup though. I ran hab studio rm to get rid of some old studios in /hab/studios then removed my /hab directory and .hab directory.  I ran hab setup again, not using sudo, and then hab studio enter inside my project directory.  This time I had no problem with missing keys.

**Comment by rushmorem** [comment]
This is no longer an issue on newer versions. `v0.30.2` works just fine on NixOS.
